### ISSUE TITLE
int progress = (int) ((long)position * 100 / (duration == 0 ? 1 : duration));

### ISSUE THREAD

**Issue by hui928636443** [lipangit/JiaoZiVideoPlayer#1054]
int progress = (int) ((long)position * 100 / (duration == 0 ? 1 : duration));
要是播放时长比较长的话这里必须转成long  不然播放进度条会出问题

**Comment by lipangit** [comment]
能说一下你遇到的具体的吗，视频长度是多少，seek到多少回有问题

**Comment by hui928636443** [comment]
播放到7 8个小时之后

**Comment by hui928636443** [comment]
我播放了12个小时的视频

**Comment by lipangit** [comment]
好的，你可以提交个pr

**Comment by hui928636443** [comment]
pr是什么

**Comment by lipangit** [comment]
pull request
![image](https://user-images.githubusercontent.com/2038071/28523815-87154f50-70b0-11e7-99e8-635b157fbd18.png)

提交修改的代码，可以加入到项目的开发

**Comment by lipangit** [comment]
计划之内了
