### ISSUE TITLE
大视频加载有点慢

### ISSUE THREAD

**Issue by SoulEaterVTT** [lipangit/JiaoZiVideoPlayer#1055]
不知道大神有什么好的优化建议吗？还是有什么需要设置的参数啥的我没搞上去

**Comment by lipangit** [comment]
android.media.MediaPlayer好像就没有配置的参数能影响加载速度，这个问题很重要，我也一直在研究

**Comment by LYM-mg** [comment]
不知道大神搞出来没，超清视频加载速度好慢

**Comment by lipangit** [comment]
@LYM-mg 一时半会出不来，原理还在研究，原因还没确定
