### ISSUE TITLE
leadked

### ISSUE THREAD

**Issue by cdyidaimanong** [lipangit/JiaoZiVideoPlayer#1057]
JCVideoPlayer$ProgressTimerTask.this refrerences JCVideoPlayerStandard.mcontext

**Comment by lipangit** [comment]
怎么解决好一些

**Comment by cdyidaimanong** [comment]
试试用weakhandler 加Runnable 去实现进度刷新  我以前更改过源码 用这种好像能避免progresstimertask 泄漏

**Comment by cdyidaimanong** [comment]
public void startProgressTimer() {
//        cancelProgressTimer();
//        UPDATE_PROGRESS_TIMER = new Timer();
//        mProgressTimerTask = new ProgressTimerTask();
//        UPDATE_PROGRESS_TIMER.schedule(mProgressTimerTask, 0, 300);
        if (mRunnable == null) {
            mRunnable = new MyRun(reference.get());
        }
        mHandler.post(mRunnable);
    }
    private static Runnable mRunnable;
    class MyRun implements Runnable {
        public MyRun(Context context) {

        }
        @Override
        public void run() {
            if (currentState == CURRENT_STATE_PLAYING || currentState == CURRENT_STATE_PAUSE || currentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
                setProgressAndText();
            }
            mHandler.postDelayed(this, 300);
        }
    }
    public static void cancelProgressTimer() {
//        if (UPDATE_PROGRESS_TIMER != null) {
//            UPDATE_PROGRESS_TIMER.cancel();
//        }
//        if (mProgressTimerTask != null) {
//            mProgressTimerTask.cancel();
//        }
        if (mRunnable != null) {
            mHandler.removeCallbacks(mRunnable);
            mRunnable = null;
        }
    }

我修改了这两个方法以后  没出现这种泄漏了

**Comment by ldy441040480** [comment]
这个的泄露原因是开启全屏时播放view的时候启动了timer,退出全屏只移除了view,没有取消task

public void clearFloatScreen() {
    JCUtils.getAppCompActivity(getContext()).setRequestedOrientation(NORMAL_ORIENTATION);
    showSupportActionBar(getContext());
    JCVideoPlayer currJcvd = JCVideoPlayerManager.getCurrentJcvd();
   // 移除timer
    currJcvd.cancelProgressTimer();
    currJcvd.textureViewContainer.removeView(JCMediaManager.textureView);
    ViewGroup vp = (ViewGroup) (JCUtils.scanForActivity(getContext()))//.getWindow().getDecorView();
            .findViewById(Window.ID_ANDROID_CONTENT);
    vp.removeView(currJcvd);
    JCVideoPlayerManager.setSecondFloor(null);
}

**Comment by lipangit** [comment]
Q群:490442439 验证信息:jcvd  进群 咱俩唠唠。

最好提交pull request，这种代码片段验证起来很麻烦。

**Comment by lipangit** [comment]
记下来了，有时间尝试修改一下，最近只看到UER_ACTION的内存泄露，这方面有研究吗
