### ISSUE TITLE
NestedScrollView嵌套JieCaoVideoPlayer和RecyclerView的时候有出问题

### ISSUE THREAD

**Issue by HRobbie** [lipangit/JiaoZiVideoPlayer#1058]
当NestedScrollView里面有一个JieCaoVideoPlayer和多个RecyclerView时。正常点开全屏和退出全屏没有问题，但是一旦点开其中一个RecyclerView的itemView.(我的是点击item跳转到另一个activity)。这个时候，点击全屏，而后退出全屏，会滑动到点击的那个RecyclerView的第一项。而不是正常屏幕播放。
布局如下：
<android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            >
            <fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                android:id="@+id/jc_video"
                android:layout_width="match_parent"
                android:layout_height="200dp"
                />
            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_1"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"></android.support.v7.widget.RecyclerView>
            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_2"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"></android.support.v7.widget.RecyclerView>
            <android.support.v7.widget.RecyclerView
                android:id="@+id/rv_3"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"></android.support.v7.widget.RecyclerView>
            
        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>
复现过程：
1.如上面的布局，rv_1、rv_2、rv_3有多个item，每个item都可以点击跳转到一个固定的activity。
2.首先点击rv_2的item，进入activity，再按回退键，返回这个布局所在的界面。
3.点击jc_video的全屏按钮，进入全屏，按回退键退出全屏。就会布局发现滑动到了rv_2的位置

**Comment by lipangit** [comment]
确认一下全屏和退出全屏的过程是否刷新了recycleView，否则列表是不会动的

**Comment by lipangit** [comment]
退回到的这个item的url和全屏时候的一样吗
