### ISSUE TITLE
分屏之后视频停止播放怎么解决？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1060]

**Comment by lipangit** [comment]
如果不是pause不是release，怎么能停呢

**Comment by StevenNick88** [comment]
可是分屏之后不是会调用onPause（）吗，你的文档不是要求要在
@Override
protected void onPause() {
    super.onPause();
    JCVideoPlayer.releaseAllVideos();
}
onPause中releaseAllVideos吗，这个怎么处理啊？

**Comment by lipangit** [comment]
你有什么好办法吗，没遇到过这种问题

**Comment by StevenNick88** [comment]
怎么会没遇到呢，现在Android 7.0不是可以分屏吗，我现在是正在播放着视频，可是分屏之后停止播放了，我知道是调用了protected void onPause() ，但是你的sdk又要求onPause中releaseAllVideos，所以我不知道怎么解决，给点思路啊？

**Comment by lipangit** [comment]
你能区别出来onPause什么时候是分屏什么时候是退出吗

**Comment by lipangit** [comment]
分屏有特定的回调和监听吗

**Comment by lipangit** [comment]
如果能拿到分屏的事件的话，在分屏onResume的时候继续播放视频。

**Comment by lipangit** [comment]
所以说我觉得目前最优化的解法是分屏的过程中视频停止播放，分屏之后继续loading，开始播放

**Comment by StevenNick88** [comment]
分屏, Activity首先调用onMultiWindowChanged->onPause->onStop->onDestroy->onCreate->onStart- >onResume->onPause(焦点切入到另一屏)

**Comment by StevenNick88** [comment]
所以说我觉得目前最优化的解法是分屏的过程中视频停止播放，分屏之后继续loading，自动继续播放

我也是这么认为的，现在的问题是分屏之后没有loading，而是停止了

**Comment by StevenNick88** [comment]
分屏之后继续loading，自动继续播放， 这个怎么实现呢？没有相关的api啊

**Comment by lipangit** [comment]
startButton.performClick()会点击开始按钮播放，如果你检测到分屏就调这个函数

默认会自动记录播放位置的。
