### ISSUE TITLE
只有声音没有画面

### ISSUE THREAD

**Issue by pck77627** [lipangit/JiaoZiVideoPlayer#1061]
http://171.221.224.161:8000/ispace2_upload3/12/2017-03-20/502/content/ch010401/HD4-1-1.mp4 
最新版本的播放器也是一样的。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28401746-ae85d452-6d4e-11e7-9e71-19df5071613a.png)
先对比一下这个，这个地址现在无法下载和播放

**Comment by pck77627** [comment]
@lipangit 应该是编码问题。那除了重新编码。就没其它方法了么？

**Comment by lipangit** [comment]
服务器上的视频编码应该是一致的

**Comment by pck77627** [comment]
@lipangit 那就只有视频重新编码了

**Comment by pck77627** [comment]
@lipangit http://171.221.224.161:8000/ispace2_upload2/11/2017-07-20/1769/content/ch010301/HD3-1-1.mp4
