### ISSUE TITLE
播放一会视频就会出现错误，必出现

### ISSUE THREAD

**Issue by Lionet6** [lipangit/JiaoZiVideoPlayer#1063]
播放这个视频地址：http://sg.v-ask.net/954-1500438087235-export.mp4 每次都会出错，试着下了demo也是这样。
我试着找了下问题，应该是MediaPlayer缓冲到一定数值之后（此视频是80%左右）缓冲变得特变慢，然后播放到已缓冲的地方之后就出错了，报错是MediaPlayer Error(1, -1004)

**Comment by lipangit** [comment]
这个视频播放时候网速比较慢，在手机上20K左右的下载速度，迅雷能达到500k的速度，我感觉视频本身没问题，速度太慢导致了seek进度的一系列问题

**Comment by lipangit** [comment]
这个问题会一直保持关注，如果解决会极大提升用户体验

**Comment by Newwaygo** [comment]
一定要解决啊，问题太严重了，播放个20分钟的视频，不到5分钟，就出错了！对于大视频来说没法用哦！

**Comment by lipangit** [comment]
因为我之前在本地搭建了一tomcat，播放2G大的电影，没这种问题，出来缓存的进度没有显示之外其他的没有问题，所以一直就忽略这个大视频的问题了，确实很严重

**Comment by 494293346** [comment]
好像是部分机型不会， 目前发现公司的锤子7.0的手机会有这个问题，跪求老铁解决方案？？？

**Comment by Lionet6** [comment]
目前暂时的解决方案是把Jiecao库里边使用的官方MediaPlayer替换为bilibili的ijkplayer，（问题是安装包会变大好多）它的使用方法跟官方MediaPlayer的方法基本一样，所以不用改什么东西。经过测试，目前出现的问题已经基本解决，而且大视频播放问题也已经解决（demo里边有2小时的长城大电影，没有发现问题）。
期待作者能早日修复。
这里放出修改后的官方Demo（已替换ijkplayer），直接继承里边的Library就可以了，因为基本没改东西，最好自己弄一下吧。网盘若出现问题发我邮件2950527715@qq.com
https://pan.baidu.com/s/1kUBCpTH

**Comment by Lionet6** [comment]
我暂时的解决方案是把Jiecao库里边使用的官方MediaPlayer替换为bilibili的ijkplayer，（问题是安装包会变大好多）它的使用方法跟官方MediaPlayer的方法基本一样，所以不用改什么东西。经过测试，目前出现的问题已经基本解决，而且大视频播放问题也已经解决（demo里边有2小时的长城大电影，没有发现问题）。
期待作者能早日修复。
@494293346 @Newwaygo 修改后的官方Demo（已替换ijkplayer），直接继承里边的Library就可以了，因为基本没改东西，最好自己弄一下吧。网盘若出现问题发我邮件2950527715@qq.com
https://pan.baidu.com/s/1kUBCpTH

**Comment by 494293346** [comment]
老哥， 之前我也听了你的建议， 把MediaPlayer换成ijk，http://sg.v-ask.net/954-1500438087235-export.mp4  这个视频是可以播了没错， 但是我从其他网站采过来的大部分视频变成不能播了， 也不知道是否我的打开方式错误呢？@Lionet6

**Comment by Lionet6** [comment]
你试试我发的改过的demo，我试了好几个没发现问题啊，大视频也试了。 @494293346

**Comment by lijun952048910** [comment]
小米手机6.0会播放一段时间后，就不会缓冲了，播放到缓冲的位置就报MediaPlayer Error(1, -1004)

**Comment by HolickABC** [comment]
@Lionet6 你好  我用你的demo这个 https://www.wowaplace.com/upload/video/1509686697189.mp4 还是播不了  这个视频iOS上传的  所以大佬能帮忙提供什么建议和解决办法吗？

**Comment by lipangit** [comment]
@HolickABC 这个地址可以播，刚才亲测了，正在直播，可以到直播间看看

**Comment by HolickABC** [comment]
@lipangit 我是下午的菊花  刚刚用6.1.2和6.1.1的demo试了这个链接还是播不了，我昨天在公司测试发现7.0之前的版本都是可以播放的，我这个手机三星s8 7.0播不了，这个链接的视频是iOS同事上传到服务器的，我自己上传到服务器的视频7.0是可以播放的

**Comment by lipangit** [comment]
可以试试新版本ijkplayer的版本
