### ISSUE TITLE
Error during detachFromGLContext

### ISSUE THREAD

**Issue by hymlv** [lipangit/JiaoZiVideoPlayer#1064]
全屏播放的时候会报如下错误
 Error during detachFromGLContext (see logcat for details)
                                                                      at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)

尝试解决:
   TextureView所在的Activity需要设置android:hardwareAccelerated="true"，现在全都设置了还是会报错。

**Comment by lipangit** [comment]
是特定机型的问题吗

**Comment by hymlv** [comment]
是这样的,华为的,红米的. 下载最新的demo,也有这个问题

**Comment by lipangit** [comment]
如果demo就有这个问题的话，这是系统的坑，解决不了

**Comment by hymlv** [comment]
从小屏到全屏又要执行一次onSurfaceTextureAvailable()方法,这时候就会调用textureView.setSurfaceTexture(savedSurfaceTexture);也就是重新attach,就会error了.从这点入手处理一下呢? 像今日头条等播放在这些机型上未出现问题.

**Comment by lipangit** [comment]
这问题暂时解决不了，把你遇到的机型列出来吧，给大家提个醒

**Comment by lipangit** [comment]
特别低端的机型
