### ISSUE TITLE
在4.4手机上youtube的地址不能播放

### ISSUE THREAD

**Issue by ryanz91** [lipangit/JiaoZiVideoPlayer#1066]
https://r3---sn-i3belnez.googlevideo.com/videoplayback?beids=%5B9466594%5D&signature=0EB69F145EC712E3D87373AE380EA2EDF3B098B3.40EC7678534868C8132236BD1293B39E9E5743CB&source=youtube&clen=4887336&requiressl=yes&gir=yes&mime=video%2Fmp4&ratebypass=yes&lmt=1496423156259589&expire=1500663781&ip=47.89.50.110&mn=sn-i3belnez&ipbits=0&mm=31&pl=18&mv=m&dur=60.859&mt=1500642055&itag=18&ms=au&initcwndbps=10023750&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-AHGXpgQJtjMtlSu0-msbh2R2iagQXC_VQ0ZYtl1sQwsl&ei=hftxWcC2JYmu4QLohIK4Cw&key=yt6

这个地址，4.2和6.0都可以播放
07-21 13:04:40.257 4855-4963/fm.jiecao.jiecaovideoplayer E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
07-21 13:04:40.257 4855-4963/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-21 13:04:40.257 4855-4963/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
07-21 13:04:40.407 4855-4869/fm.jiecao.jiecaovideoplayer E/MediaPlayer: error (1, -1004)
07-21 13:04:40.407 4855-4963/fm.jiecao.jiecaovideoplayer E/MediaPlayer: Error (1,-1004)
07-21 13:04:40.407 4855-4855/fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError 1 - -1004 [1103742680] 

这是错误日志

**Comment by ryanz91** [comment]
https://r2---sn-i3b7kn7k.googlevideo.com/videoplayback?mime=video%2Fmp4&clen=4887336&signature=10CF0E4CDE3193DB04261C0291638167CBFF365E.4DB306078EB6CADC95318A8E5133894C5C678DA9&source=youtube&key=yt6&lmt=1496423156259589&dur=60.859&mn=sn-i3b7kn7k&initcwndbps=10605000&ipbits=0&id=o-ALrMHU5oLd17xM4-qvrNH1ccXFiUJALpQ4ADjg1uDRR8&ratebypass=yes&requiressl=yes&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&pl=18&itag=18&mt=1500691904&ms=au&ei=Ib5yWYO0Oaiu4ALivqDABQ&expire=1500713602&mm=31&ip=47.89.50.110&mv=m

**Comment by lipangit** [comment]
直接的视频地址才能播放
