### ISSUE TITLE
How to remove fullscreen button

### ISSUE THREAD

**Issue by fongfuse** [lipangit/JiaoZiVideoPlayer#1067]
i like your library! 
and I get some problem ,I want to remove fullscreen button

How to set it?  thanks!

**Comment by lipangit** [comment]
See SmallChangeUiActivity in Demo

**Comment by lipangit** [comment]
Extends JCVideoPlayerStandard then Override some function

**Comment by fongfuse** [comment]
Ok I got it but right times is leave out 
example:

left times                 right times
00.01----------------00.0

is right times is just show 00.0
but so true right times is 00.02

**Comment by lipangit** [comment]
You mean the precision of the time callback is not enough?

**Comment by fongfuse** [comment]
Actually the right side time is missing 1 digit. So how can I solve this problem 
Thank you in advance.

**Comment by fongfuse** [comment]
https://www.img.in.th/image/NXhg 

Please see as the attached file.

**Comment by lipangit** [comment]
Yes It is, if duration < 2s, something wrong with progress, Can you fix?

**Comment by fongfuse** [comment]
How to setvisible jc_battery in fullscreen?
