### ISSUE TITLE
 点击播放按钮，视频正在加载的时候点击播放界面，播放控制条怎么没显示出来？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1074]

**Comment by lipangit** [comment]
loading的时候点击空白部分是不会有效果的，播放的时候才有效果

**Comment by StevenNick88** [comment]
我现在的需求要在loading的时候也要点击显示和隐藏控件切换，怎么做？

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写onClickUiToggle函数
onClickUiToggle(){
   if (currentState == CURRENT_STATE_PREPARING) {
   // 你的逻辑
   }
    super.onClickUiToggle();//屏蔽父类的CURRENT_STATE_PREPARING状态
}
