### ISSUE TITLE
可以连续播放多个视频吗

### ISSUE THREAD

**Issue by JadonPsycho** [lipangit/JiaoZiVideoPlayer#1082]
可以播放多个视频吗 全屏状态下 播放完成第一个视频 直接跟上第二个视频

**Comment by lipangit** [comment]
可以，继承JCVideoPlayerStandard，复写onAutoComplete函数拿到自动播放完成状态，播放下一个视频

**Comment by JadonPsycho** [comment]
对的 我已经弄好了，但是能在全屏状态下直接切换吗

**Comment by lipangit** [comment]
可以参照没发布的版本的change_url分支，onStatePreparingChangingUrl函数可以无缝切换视频

**Comment by lipangit** [comment]
onAutoComplete函数中屏蔽父类函数就不会退出全屏了

**Comment by RadinLy** [comment]
请问一下没发布的版本的change_url分支这个在哪里下载？ @lipangit

**Comment by lipangit** [comment]
v6.0.0   https://github.com/lipangit/JiaoZiVideoPlayer/tree/v6.0.0

或者develop是最新提交
