### ISSUE TITLE
全屏播放结束后，再点击播放按钮出错

### ISSUE THREAD

**Issue by shenxueyuan** [lipangit/JiaoZiVideoPlayer#1087]
7-28 14:32:14.709 4160-4160/fm.jiecao.jiecaovideoplayer D/AudioManager: AudioManager dispatching onAudioFocusChange(-2) for android.media.AudioManager@c2e447bfm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1@4fc5351
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err: java.lang.IllegalStateException
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.isPlaying(Native Method)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1.onAudioFocusChange(JCVideoPlayer.java:786)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2246)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:159)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6326)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
07-28 14:32:14.710 4160-4160/fm.jiecao.jiecaovideoplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
07-28 14:32:14.711 4160-4160/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: AUDIOFOCUS_LOSS_TRANSIENT [83645265]

**Comment by lipangit** [comment]
能复现吗，这块是如果系统其他地方播放声音，就会暂停视频播放
