### ISSUE TITLE
ineffective without a SurfaceHolder

### ISSUE THREAD

**Issue by pck77627** [lipangit/JiaoZiVideoPlayer#1088]
07-28 16:42:35.826 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStateNormal  [214183536] 
07-28 16:42:35.833 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onClick start [214183536] 
07-28 16:42:35.834 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: startVideo [214183536] 
07-28 16:42:35.835 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: addTextureView [214183536] 
07-28 16:42:35.839 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePreparing  [214183536] 
07-28 16:42:35.842 14140-14140/com.lemon.u_course I/JCResizeTextureView: onMeasure  [155860476] 
07-28 16:42:35.843 14140-14140/com.lemon.u_course I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
07-28 16:42:35.843 14140-14140/com.lemon.u_course I/JCResizeTextureView: viewRotation = 0
07-28 16:42:35.843 14140-14140/com.lemon.u_course I/JCResizeTextureView: onMeasure  [155860476] 
07-28 16:42:35.844 14140-14140/com.lemon.u_course I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
07-28 16:42:35.844 14140-14140/com.lemon.u_course I/JCResizeTextureView: viewRotation = 0
07-28 16:42:35.853 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onSurfaceTextureAvailable [226349999] 
07-28 16:42:35.855 14140-26464/com.lemon.u_course E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
07-28 16:42:35.856 14140-26464/com.lemon.u_course E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-28 16:42:35.856 14140-26464/com.lemon.u_course E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
07-28 16:42:35.856 14140-26464/com.lemon.u_course E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-28 16:42:35.862 14140-26464/com.lemon.u_course W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-28 16:42:35.868 14140-14152/com.lemon.u_course D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
07-28 16:42:35.868 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:36.017 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:36.175 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:36.270 14140-14151/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:43.600 14140-14226/com.lemon.u_course D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
07-28 16:42:43.601 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:43.783 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:44.116 14140-26590/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:44.306 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:44.818 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onVideoSizeChanged  [214183536] 
07-28 16:42:44.818 14140-26464/com.lemon.u_course D/MediaPlayer: setSubtitleAnchor in MediaPlayer
07-28 16:42:44.827 14140-14140/com.lemon.u_course I/JCResizeTextureView: onMeasure  [155860476] 
07-28 16:42:44.827 14140-14140/com.lemon.u_course I/JCResizeTextureView: videoWidth = 448, videoHeight = 336
07-28 16:42:44.827 14140-14140/com.lemon.u_course I/JCResizeTextureView: viewRotation = 0
07-28 16:42:44.827 14140-14140/com.lemon.u_course I/JCResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
07-28 16:42:44.827 14140-14140/com.lemon.u_course I/JCResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 426]
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JCResizeTextureView: onMeasure  [155860476] 
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JCResizeTextureView: videoWidth = 448, videoHeight = 336
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JCResizeTextureView: viewRotation = 0
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JCResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JCResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 426]
07-28 16:42:44.828 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onSurfaceTextureSizeChanged [226349999] 
07-28 16:42:44.834 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onPrepared  [214183536] 
07-28 16:42:44.836 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePlaying  [214183536] 
07-28 16:42:44.870 14140-14152/com.lemon.u_course D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
07-28 16:42:44.871 14140-14226/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:44.912 14140-14221/com.lemon.u_course D/MediaHTTPConnection: proxy null port 0
07-28 16:42:45.067 14140-14226/com.lemon.u_course W/MediaPlayer: info/warning (703, 0)
07-28 16:42:45.067 14140-14226/com.lemon.u_course W/MediaPlayer: info/warning (701, 0)
07-28 16:42:45.068 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 703 extra - 0
07-28 16:42:45.068 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
07-28 16:42:45.068 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePlaybackBufferingStart  [214183536] 
07-28 16:42:45.070 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
07-28 16:42:45.089 14140-26590/com.lemon.u_course W/MediaPlayer: info/warning (703, 0)
07-28 16:42:45.090 14140-14152/com.lemon.u_course W/MediaPlayer: info/warning (702, 0)
07-28 16:42:45.092 14140-14152/com.lemon.u_course W/MediaPlayer: info/warning (703, 0)
07-28 16:42:45.092 14140-14221/com.lemon.u_course W/MediaPlayer: info/warning (701, 0)
07-28 16:42:45.094 14140-14221/com.lemon.u_course W/MediaPlayer: info/warning (703, 0)
07-28 16:42:45.094 14140-14221/com.lemon.u_course W/MediaPlayer: info/warning (701, 0)
07-28 16:42:45.100 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 703 extra - 0
07-28 16:42:45.108 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
07-28 16:42:45.108 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePlaying  [214183536] 
07-28 16:42:45.113 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END
07-28 16:42:45.114 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 703 extra - 0
07-28 16:42:45.114 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
07-28 16:42:45.114 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePlaybackBufferingStart  [214183536] 
07-28 16:42:45.115 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
07-28 16:42:45.115 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 703 extra - 0
07-28 16:42:45.115 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
07-28 16:42:46.092 14140-26590/com.lemon.u_course W/MediaPlayer: info/warning (703, 0)
07-28 16:42:46.092 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 703 extra - 0
07-28 16:42:46.092 14140-26590/com.lemon.u_course W/MediaPlayer: info/warning (702, 0)
07-28 16:42:46.099 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
07-28 16:42:46.099 14140-14140/com.lemon.u_course I/JieCaoVideoPlayer: onStatePlaying  [214183536] 
07-28 16:42:46.108 14140-14140/com.lemon.u_course D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END

http://171.221.224.161:8000/ispace2_upload3/12/2017-03-27/572/content/ch010301/HD3-1-1.mp4

**Comment by lipangit** [comment]
解决了吗 怎么样了

**Comment by chnouman** [comment]
still facing the same issue.
`2019-03-30 19:03:52.807 6090-6802/com.app.winsshare W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
2019-03-30 19:03:52.820 6090-6802/com.app.winsshare W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at cn.jzvd.JZMediaSystem.lambda$prepare$0(JZMediaSystem.java:51)
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at cn.jzvd.-$$Lambda$JZMediaSystem$1SfpWnrQJjBakrZ3K2nGWWoyock.run(lambda)
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-03-30 19:03:52.822 6090-6802/com.app.winsshare W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
`

**Comment by lipangit** [comment]
maybe you are not  same question.

check out whitch vraiable is null
