### ISSUE TITLE
播放webm

### ISSUE THREAD

**Issue by lbwstco** [lipangit/JiaoZiVideoPlayer#1090]
播放webm格式的时候，解析有问题，alpha通道被解析成黑色

**Comment by lipangit** [comment]
你是怎么知道的，教教我alpha通道解析

**Comment by lbwstco** [comment]
@lipangit 额，我有个webm的视频实际是透明的，播放的时候成黑色了

**Comment by lipangit** [comment]
可能是控件的背景色，控件不是透明的
