### ISSUE TITLE
重力感应问题

### ISSUE THREAD

**Issue by wjy591416** [lipangit/JiaoZiVideoPlayer#1093]
如何实现在小屏幕是不使用，重力感应，只在全屏时使用重力感应
现在出现的情况是，在activity中setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);强制横屏
也参考前辈，将 
JCVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;正常屏幕设置成横屏
在初次进入activity的时候，没有重力感应，在全屏后，回到小屏幕，就有可重力感应

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28753739-763ebc2e-756b-11e7-8343-5c226c59ad9c.png)  默认不是这样的吗

**Comment by lipangit** [comment]
JCVideoPlayer.NORMAL_ORIENTATION  这两个变量是全局，坑你也得根据自己的实际情况多次赋值

**Comment by wjy591416** [comment]
刚刚打开activity的时候是这样的，可以，当进入全屏后再回到默认屏幕的时候，重力感应就开启了

**Comment by wjy591416** [comment]
在dome中好像并不存在这个问题

**Comment by wjy591416** [comment]
ActivityInfo.SCREEN_ORIENTATION_USER,，我打印出来设置变成这个，了

**Comment by wjy591416** [comment]
在ublic void init(Context context)这个方法中设置这个是为了什么？ NORMAL_ORIENTATION = context.getResources().getConfiguration().orientation;

**Comment by wjy591416** [comment]
找到问题所在，请教大神为什么我的手机不管怎么设置最终都是ActivityInfo.SCREEN_ORIENTATION_USER这个参数

**Comment by lipangit** [comment]
这。。  demo有问题吗  有其他地方干扰吗

**Comment by wjy591416** [comment]
@lipangit 经过研究你的代码，知道问题所在，
JCVideoPlayer 下init方法不能这么写
 NORMAL_ORIENTATION = context.getResources().getConfiguration().orientation;
需要修改为
try{
if (isCurrentJcvd()) {
            NORMAL_ORIENTATION = ((Activity)context).getRequestedOrientation();
        }
        }catch(Exception e){
        	 e.printStackTrace();
        }

这样就能满足你设计思路中的获取当前屏幕下屏幕模式，

**Comment by lipangit** [comment]
有道理，修改之

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28780071-12641352-7638-11e7-9972-f257921d100b.png)

这两个方法有什么区别吗，看文档里没啥区别

**Comment by wjy591416** [comment]
getConfiguration().orientation  获得当前资源的方向
getRequestedOrientation() 获得当前请求的方向

**Comment by lipangit** [comment]
已经修改
