### ISSUE TITLE
测试了，小米和Google模拟器4.4手机系统统统无法播放

### ISSUE THREAD

**Issue by li-xiansheng** [lipangit/JiaoZiVideoPlayer#1097]
如题

**Comment by lipangit** [comment]
模拟器不适合测试 缺东西

**Comment by lipangit** [comment]
小米无法播放的地址发来试试

**Comment by li-xiansheng** [comment]
测试中，模拟器8.0能访问，真机7.0能播放,就是不明白4.4的系统都不行,小米和模拟器两个都是：http://video2.zhcw.com/vod_storage/vol1/2017/07/30/597dddb8a98d7/7c2e7bf0752b11e78c02a4badb2ed31b.mp4

**Comment by VMystery** [comment]
已修复JCMediaManager类中过早调用  method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);将此句放到后面调用即可，暂时未测出其他问题
      mediaPlayer.setScreenOnWhilePlaying(true);
                        mediaPlayer.setOnSeekCompleteListener(JCMediaManager.this);
                        mediaPlayer.setOnErrorListener(JCMediaManager.this);
                        mediaPlayer.setOnInfoListener(JCMediaManager.this);
                        mediaPlayer.setOnVideoSizeChangedListener(JCMediaManager.this);
                        method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);//放到设置监听语句后面
                        mediaPlayer.prepareAsync();
                        mediaPlayer.setSurface(new Surface(savedSurfaceTexture));

**Comment by mrldroid** [comment]
4.3、4.2也不行。。

**Comment by lipangit** [comment]
请不要用模拟器，咱们开发视频就告别模拟器了，可以卸载模拟器了
