### ISSUE TITLE
全屏播放结束后，再点击播放按钮怎么重新播放？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1098]

**Comment by lipangit** [comment]
难道不应该重新播放吗

**Comment by StevenNick88** [comment]
你理解错了，现在的现象是：视频横着全屏播放完之后自动回到列表界面了，这块在哪里实现的，我看你在新版本加入了重播的按钮，这块代码在哪？

**Comment by lipangit** [comment]
就是你说的现象，设计如此。

onAutoComplete(),自动播放完成调用。

retry在JCVideoPlayerStandard的布局的最下方。
