### ISSUE TITLE
 视频在全屏播放时，点击手机home键回到桌面，再进入app点击播放视频时，视频从头开始播放而不是接着之间的进度播放？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1099]

**Comment by StevenNick88** [comment]
没有全屏的时候是可以接着播放的

**Comment by lipangit** [comment]
恩是个问题，这就修改

**Comment by StevenNick88** [comment]
这个什么时候改好啊？项目急用

**Comment by lipangit** [comment]
正在研究，预计今天改完，常规周日发版

**Comment by StevenNick88** [comment]
周日才发版？今天改完给个大致代码啊，谢谢！

**Comment by lipangit** [comment]
好

**Comment by StevenNick88** [comment]
改完了吗？

**Comment by StevenNick88** [comment]
楼主进度如何了？

**Comment by lipangit** [comment]
马上改，昨天清晰度的整到大半夜然后忘了

**Comment by lipangit** [comment]
fixed 825d659

**Comment by StevenNick88** [comment]
如上，我看你这次加上了onStateNormal();   我用的是之前的版本，
之前里面有句代码是
 jcVideoPlayer.setUp(url, JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, objects);

 现在新版本是：
  jcVideoPlayer.setUp(urlMap, currentUrlMapIndex, JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, objects);

这个不用改没关系吧？

**Comment by lipangit** [comment]
这两个setUp都有，带map的是清晰度相关的
