### ISSUE TITLE
现在视频正处于Preparing状态，这时我按home键回到桌面，我需要让MediaPlayer暂停而不是销毁，怎么做？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1108]

**Comment by StevenNick88** [comment]
楼主回个话，很急啊。。。

**Comment by StevenNick88** [comment]
楼主这个回一下

**Comment by lipangit** [comment]
1.暂停JCMediaPlayer.instance().mediaPlayer
2.resume的时候TextureView会avalible，set mediaplayer的surface
理论上是这两个步骤。以后会添加这个功能

**Comment by StevenNick88** [comment]
现在没有啊？我现在遇到的问题是：我在Preparing状态，这时我按home键回到桌面，先不回来app，然后一会儿视频开始在后台播放了

**Comment by lipangit** [comment]
不应该吧，onPause的时候直接回releaseMediaPlayer，不可能播放的。

**Comment by StevenNick88** [comment]
我改了onPause的时候我改成mediaPlayer.pause()了，因为我需要再回来app的时候继续播放

**Comment by StevenNick88** [comment]
你的设计是再回来app的时候mediaPlayer已经release了，可是现在视频软件可不是这么做的，你看爱奇艺再回来的时候也是继续播放的

**Comment by lipangit** [comment]
暂时的标准和头条看齐

但是我觉的这个功能很重要，研究明白就只就会添加，你也可以提交pr

**Comment by lipangit** [comment]
onPause不确定是按home键还是back键，这个怎么判断

**Comment by lipangit** [comment]
已经有这功能了
