### ISSUE TITLE
我现在网络视频播放到一半，但是由于网速跟不上卡住了，这时候视频开始缓冲，这个时候视频是处于什么状态？ 是CURRENT_STATE_PLAYING_BUFFERING_START这个状态吗？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1110]

**Comment by lipangit** [comment]
是这个状态

**Comment by 401885064** [comment]
6.2.3版本取消了这个CURRENT_STATE_PLAYING_BUFFERING_START状态吗？  我搜索没发现

**Comment by lipangit** [comment]
对新版本取消了这个状态，因为我判断视频放到云上，播放很少出现卡的情况，所以把它取消了

如果不取消的话，seek进度拖动进度条的时候还会闪一个loading图标，难看

如果你必须加的话可以参考旧版本，不到20行代码
