### ISSUE TITLE
如何缓存

### ISSUE THREAD

**Issue by shbGitHub** [lipangit/JiaoZiVideoPlayer#1111]
咱们这有缓存的逻辑吗，如果需要缓存，应该如何配置？ 同一个视频重复播放不希望还是去网上加载

**Comment by lipangit** [comment]
只有临时的缓存，一次播放的缓存，再次播放需要重新缓存。无法配置。如果细想也很复杂，如果看了个2g的视频缓存了，本地要多个2g的文件吗

**Comment by shbGitHub** [comment]
嗯，也是，如果都下载到本地 确实造成存储太大的问题

**Comment by ldy441040480** [comment]
边播边缓存：https://github.com/danikula/AndroidVideoCache，jiecao里面可以考虑引入一下

**Comment by lipangit** [comment]
试过了，拖动进度有问题，感觉它解决了90%的问题，但是还有95%工作，就是说解决的这90%的问题只是一小部分。
