### ISSUE TITLE
播放在线或本地视频时，拔掉耳机视频不会暂停

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1112]

**Comment by lipangit** [comment]
试了几款app没发现有暂停的，我觉得这个需求也算合理

**Comment by StevenNick88** [comment]
来个暂停和继续播放的api吧，自己写的总是有些问题，希望官方出api

**Comment by StevenNick88** [comment]
暂停的方法这样可以吗，我参照你的onclick方法写的：
   private void onPause(JCVideoPlayer video_player){
        video_player.onEvent(JCUserAction.ON_CLICK_PAUSE);
        JCMediaManager.instance().mediaPlayer.pause();
        video_player.onStatePause();
    }

**Comment by lipangit** [comment]
可以，onEvent是友盟埋点统计，可以不写
