### ISSUE TITLE
有两个bug：

### ISSUE THREAD

**Issue by CaiZhihao** [lipangit/JiaoZiVideoPlayer#1114]
1.Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class fm.jiecao.jiecaovideoplayer.CustomView.JCVideoPlayerStandardShowShareButtonAfterFullscreen

2.Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

at fm.jiecao.jiecaovideoplayer.UISmallChangeActivity.onCreate(UISmallChangeActivity.java:36)，即UISmallChangeActivity中的setContentView(R.layout.activity_ui_small_change);

**Comment by lipangit** [comment]
哦 这个改了布局之后出的问题，这个版本会修改
