### ISSUE TITLE
全屏播放是如何去播放右下角的那个返回竖屏的按钮

### ISSUE THREAD

**Issue by 2966325911** [lipangit/JiaoZiVideoPlayer#1115]
全屏播放是如何去播放右下角的那个返回竖屏的按钮？需求是进入之后直接横屏播放，不支持竖屏，得让那个按钮不显示?

**Comment by lipangit** [comment]
全屏横屏的方法：参照demo的orientationActivity设置全屏前和全屏后的屏幕方向

隐藏全屏按钮，参照demo的smallChangeUiActivity，复写setUp函数if current_screen=全屏 把按钮隐藏

**Comment by ldy441040480** [comment]
if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
            fullscreenButton.setVisibility(GONE);
            LinearLayout.LayoutParams lp = (LinearLayout.LayoutParams) totalTimeTextView.getLayoutParams();
            lp.setMargins(0, 0, BabyVideoUtils.dip2px(getContext(), 14), 0);
            totalTimeTextView.setLayoutParams(lp);
        }

**Comment by ldy441040480** [comment]
setup方法里面

**Comment by lipangit** [comment]
@ldy441040480  [看这里 ](https://github.com/lipangit/JieCaoVideoPlayer/issues/1057)
