### ISSUE TITLE
无法播放长视频

### ISSUE THREAD

**Issue by lilyBeijing** [lipangit/JiaoZiVideoPlayer#1120]
在播放长视频的时候(视频长度大概一个小时左右),当播放到中间的时候,会出现一个加载的进度圈,然后视频就一直卡在那里,等了很长时间依然是这样,而且是必出现的,这是怎么回事啊,希望知道的人解答一下,

**Comment by MrQK** [comment]
请问解决了嘛,我播放大一点的视频也是出现这种情况

**Comment by lipangit** [comment]
来个链接试试

**Comment by fiona0419** [comment]
我觉得在长视频的问题解决之前，作者可以扩展自定义选择ijkplayer

**Comment by lipangit** [comment]
是的已经在计划了
