### ISSUE TITLE
为什么在onpause里面执行JCVideoPlayer.releaseAllVideos(); 而不是在ondestory，这样如果回到onresume还能继续播放吗？

### ISSUE THREAD

**Issue by shbGitHub** [lipangit/JiaoZiVideoPlayer#1122]
为什么在onpause里面执行JCVideoPlayer.releaseAllVideos(); 而不是在ondestory里执行，这样如果回到onresume如何继续播放吗？

**Comment by 164738777** [comment]
#851 
大兄弟看这里~我也遇到你这个问题了。

**Comment by lipangit** [comment]
这个问题如果研究出来可以提交pull request，分享给大家

**Comment by shbGitHub** [comment]
我目前是在ondestory里面执行JCVideoPlayer.releaseAllVideos();，
自己定义了一个player继承JCVideoPlayerStandard
 在onpause里面执行
if (currentState == CURRENT_STATE_PLAYING) {
            onEvent(JCBuriedPoint.ON_CLICK_PAUSE);
            JCMediaManager.instance().mediaPlayer.pause();
            setUiWitStateAndScreen(CURRENT_STATE_PAUSE);
        }   
在onresume里面执行
if (currentState == CURRENT_STATE_PAUSE) {
            onEvent(JCBuriedPoint.ON_CLICK_RESUME);
            JCMediaManager.instance().mediaPlayer.start();
            setUiWitStateAndScreen(CURRENT_STATE_PLAYING);
        }
暂时能满足需求，不知道有没有什么问题

**Comment by lipangit** [comment]
好的 有时间我试试

**Comment by 164738777** [comment]
大兄弟 , 这种写法在视频进入全屏时候,  startBtn的状态有点错乱,可能导致图标问题什么的。

**Comment by ldy441040480** [comment]
/**
     * 页面触发onPause
     * 播放中或缓冲中-->视频暂停
     * 视频准备中-->视频停止
     * @param tag
     *           任意对象，防止多个视频页面切换造成视频恢复混乱
     */
    public void onActivityPause(Object tag) {
        BabyVideoLog.i(TAG, "onActivityPause tag=[" + tag + "];");
        if (currentState == CURRENT_STATE_PLAYING || currentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
            startActivityPauseTimer();
            pausePlayer();
            BabyViewController.setCurrentPauseTag(tag);
            currentState = CURRENT_STATE_ACTIVITY_PAUSE;
        } else if (currentState == CURRENT_STATE_PREPARING) {
            stopActivityPauseTimer();
            releaseAllVideos();
        }
    }

    /**
     * 页面触发onResume
     * 满足以下条件：
     * 1.是当前播放的视频
     * 2.恢复对象tag与暂停对象一致
     * 3.当前状态是 CURRENT_STATE_ACTIVITY_PAUSE
     * @param tag
     *          任意对象，防止多个视频页面切换造成视频恢复混乱
     * @return
     */
    public boolean onActivityResume(Object tag) {
        BabyVideoLog.i(TAG, "onActivityResume tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            if (currentState == CURRENT_STATE_ACTIVITY_PAUSE) {
                startPlayer();
                return true;
            }
        }
        return false;
    }

    /**
     * 页面主动释放视频
     * @param tag
     *       任意对象，防止多个视频页面切换释放混乱
     */
    public void onActivityRelease(Object tag) {
        BabyVideoLog.i(TAG, "onActivityRelease tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            releaseAllVideos();
        }
    }

**Comment by ldy441040480** [comment]
/**
     * 页面触发onPause
     * 播放中或缓冲中-->视频暂停
     * 视频准备中-->视频停止
     * @param tag
     *           任意对象，防止多个视频页面切换造成视频恢复混乱
     */
    public void onActivityPause(Object tag) {
        BabyVideoLog.i(TAG, "onActivityPause tag=[" + tag + "];");
        if (currentState == CURRENT_STATE_PLAYING || currentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
            startActivityPauseTimer();
            pausePlayer();
            BabyViewController.setCurrentPauseTag(tag);
            currentState = CURRENT_STATE_ACTIVITY_PAUSE;
        } else if (currentState == CURRENT_STATE_PREPARING) {
            stopActivityPauseTimer();
            releaseAllVideos();
        }
    }

    /**
     * 页面触发onResume
     * 满足以下条件：
     * 1.是当前播放的视频
     * 2.恢复对象tag与暂停对象一致
     * 3.当前状态是 CURRENT_STATE_ACTIVITY_PAUSE
     * @param tag
     *          任意对象，防止多个视频页面切换造成视频恢复混乱
     * @return
     */
    public boolean onActivityResume(Object tag) {
        BabyVideoLog.i(TAG, "onActivityResume tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            if (currentState == CURRENT_STATE_ACTIVITY_PAUSE) {
                startPlayer();
                return true;
            }
        }
        return false;
    }

    /**
     * 页面主动释放视频
     * @param tag
     *       任意对象，防止多个视频页面切换释放混乱
     */
    public void onActivityRelease(Object tag) {
        BabyVideoLog.i(TAG, "onActivityRelease tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            releaseAllVideos();
        }
    }

**Comment by ldy441040480** [comment]
/**
     * 页面触发onPause
     * 播放中或缓冲中-->视频暂停
     * 视频准备中-->视频停止
     * @param tag
     *           任意对象，防止多个视频页面切换造成视频恢复混乱
     */
    public void onActivityPause(Object tag) {
        BabyVideoLog.i(TAG, "onActivityPause tag=[" + tag + "];");
        if (currentState == CURRENT_STATE_PLAYING || currentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
            startActivityPauseTimer();
            pausePlayer();
            BabyViewController.setCurrentPauseTag(tag);
            currentState = CURRENT_STATE_ACTIVITY_PAUSE;
        } else if (currentState == CURRENT_STATE_PREPARING) {
            stopActivityPauseTimer();
            releaseAllVideos();
        }
    }

**Comment by ldy441040480** [comment]
/**
     * 页面触发onResume
     * 满足以下条件：
     * 1.是当前播放的视频
     * 2.恢复对象tag与暂停对象一致
     * 3.当前状态是 CURRENT_STATE_ACTIVITY_PAUSE
     * @param tag
     *          任意对象，防止多个视频页面切换造成视频恢复混乱
     * @return
     */
    public boolean onActivityResume(Object tag) {
        BabyVideoLog.i(TAG, "onActivityResume tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            if (currentState == CURRENT_STATE_ACTIVITY_PAUSE) {
                startPlayer();
                return true;
            }
        }
        return false;
    }

**Comment by ldy441040480** [comment]
/**
     * 页面触发onResume
     * 满足以下条件：
     * 1.是当前播放的视频
     * 2.恢复对象tag与暂停对象一致
     * 3.当前状态是 CURRENT_STATE_ACTIVITY_PAUSE
     * @param tag
     *          任意对象，防止多个视频页面切换造成视频恢复混乱
     * @return
     */
    public boolean onActivityResume(Object tag) {
        BabyVideoLog.i(TAG, "onActivityResume tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            if (currentState == CURRENT_STATE_ACTIVITY_PAUSE) {
                startPlayer();
                return true;
            }
        }
        return false;
    }

**Comment by ldy441040480** [comment]
/**
     * 页面主动释放视频
     * @param tag
     *       任意对象，防止多个视频页面切换释放混乱
     */
    public void onActivityRelease(Object tag) {
        BabyVideoLog.i(TAG, "onActivityRelease tag=[" + tag + "];");
        if (BabyViewController.getCurrentPauseTag() != null && BabyViewController.getCurrentPauseTag().equals(tag)) {
            stopActivityPauseTimer();
            BabyViewController.setCurrentPauseTag(null);
            releaseAllVideos();
        }
    }

**Comment by ldy441040480** [comment]
改的太多了，只能提供这样的思路了

**Comment by shbGitHub** [comment]
666，研究研究，

**Comment by ldy441040480** [comment]
/**
     * 开始播放视频
     * 1、视频处于正常、错误、播放完成：prepareVideo
     * 2、视频处于暂停或activity暂停（是当前播放的视频）：继续播放
     */
    public void startPlayer() {
        BabyVideoLog.i(TAG, "startPlayer currentState=[" + currentState + "] ");
        if (!TextUtils.isEmpty(url)) {
            if (currentState == CURRENT_STATE_NORMAL || currentState == CURRENT_STATE_ERROR || currentState == CURRENT_STATE_AUTO_COMPLETE) {
                prepareVideo(url, true);
            } else if (currentState == CURRENT_STATE_PAUSE || currentState == CURRENT_STATE_ACTIVITY_PAUSE) {
                if (url.equals(BabyMediaManager.instance().getCurrentPlayingUrl())) {
                    BabyMediaManager.instance().start();
                    onStatePlaying(true);
                }
            }
        }
    }

    /**
     * 暂停播放视频（是当前播放的视频）
     * 1、视频处于播放或缓冲中：暂停
     * 2、视频处于准备中：释放
     */
    public void pausePlayer() {
        if (url.equals(BabyMediaManager.instance().getCurrentPlayingUrl())) {
            if (currentState == CURRENT_STATE_PLAYING || currentState == CURRENT_STATE_PLAYING_BUFFERING_START) {
                BabyMediaManager.instance().pause();
                onStatePause(true);
            } else if (currentState == CURRENT_STATE_PREPARING) {
                releaseAllVideos();
            }
        }
    }

**Comment by lipangit** [comment]
用新版，有这功能了

**Comment by SuperKung** [comment]
大哥，新版这个功能怎么调用啊，pause和resume的
