### ISSUE TITLE
rtsp、h264直播流 延时5s左右

### ISSUE THREAD

**Issue by hnyer** [lipangit/JiaoZiVideoPlayer#1123]
rtsp流来自本地摄像头 ，局域网， 延时有点严重。请问如何优化。thanks

**Comment by lipangit** [comment]
超出老臣解决范围

**Comment by ts5210ts** [comment]
rtsp流来自本地摄像头 ，局域网， 延时有点严重。请问怎么接入？
另外，使用原生的Player，延迟一般不会超过3s的。

**Comment by lipangit** [comment]
超出老臣解决范围 @ts5210ts  你问问  @hnyer

**Comment by fengbenpaao** [comment]
ijkplay
