### ISSUE TITLE
用5.8版本切换清晰度时总是自动在第一个视频

### ISSUE THREAD

**Issue by GTooo** [lipangit/JiaoZiVideoPlayer#1125]
用5.8版本切换清晰度时，切换清晰度总是在第一个视频

**Comment by lipangit** [comment]
5.8.1

**Comment by GTooo** [comment]
@lipangit 就是5.8.1

**Comment by lipangit** [comment]
有这问题！！ 详细说说 一共几步，每步做了什么，点了什么按钮，看到什么现象

**Comment by GTooo** [comment]
周五的那个分支版本没问题，正式版才出现的，我这边就是更换lib库，以及gralde文件下的那个文件m开头的文件，其它的就正常调用，然后一开始就切换失败了，正常的操作流程，点击切换按钮，选择清晰度


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Nathen <notifications@github.com>
时间：周二 8月8日 18:53
收件人：lipangit/JieCaoVideoPlayer <JieCaoVideoPlayer@noreply.github.com>
抄送：GTooo <13751734622@163.com>,Author <author@noreply.github.com>
主题：Re: [lipangit/JieCaoVideoPlayer] 用5.8版本切换清晰度时总是自动在第一个视频 (#1125)

**Comment by lipangit** [comment]
5.8.1 有问题吗

**Comment by lipangit** [comment]
哪个版本，怎么操作，出现什么问题。你的描述看不太懂

**Comment by GTooo** [comment]
用的就是5.81的


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Nathen <notifications@github.com>
时间：周二 8月8日 20:17
收件人：lipangit/JieCaoVideoPlayer <JieCaoVideoPlayer@noreply.github.com>
抄送：GTooo <13751734622@163.com>,Author <author@noreply.github.com>
主题：Re: [lipangit/JieCaoVideoPlayer] 用5.8版本切换清晰度时总是自动在第一个视频 (#1125)

**Comment by junmei520** [comment]
切换清晰度有demo吗？

**Comment by GTooo** [comment]
@junmei setup 数据源传map就行了

**Comment by junmei520** [comment]
切换清晰度，如果视频是.m3u8格式的，每次切换过后都从头开始播，这个该怎么改？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29273651-af186568-8137-11e7-9ac0-19b1ca55bf8f.png)

断点这个函数，断点这个变量的改变，看看seekTo是否生效

**Comment by FanYimin** [comment]
楼主GTooo ，同样是5.8.1，我用魅族mx5切换清晰度遇到了视频变绿的问题，你有没有遇到啊？

**Comment by lipangit** [comment]
@FanYimin 发个视频看看效果吧

**Comment by FanYimin** [comment]
不好意思，没有测试机啊。客户的手机，不能拿过来。有人说是魅族mx5 gpu的问题，让我设置layertype为software。关闭了view的硬件加速。结果任何视频都不能播放了

**Comment by lipangit** [comment]
硬件加速必须开启，否则textureView无法工作

**Comment by GTooo** [comment]
@FanYimin没遇到视频变绿的情况啊
