### ISSUE TITLE
点击视频全屏按钮，app Force Close

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1129]
--------- beginning of crash
08-10 10:16:42.195 32553 32553 E AndroidRuntime: FATAL EXCEPTION: main
08-10 10:16:42.195 32553 32553 E AndroidRuntime: Process: com.afmobi.boomplayer, PID: 32553
08-10 10:16:42.195 32553 32553 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:335)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.View.layout(View.java:18410)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.View.layout(View.java:18410)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.View.layout(View.java:18410)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.View.layout(View.java:18410)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.View.layout(View.java:18410)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:917)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:715)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:650)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:903)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:836)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6288)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
08-10 10:16:42.195 32553 32553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
08-10 10:16:42.198 32553 32670 D GraphicBuffer: unregister, handle(0x80776300) (w:640 h:360 s:640 f:0x23 u:0x002933)
08-10 10:16:42.199 32553 32670 D GraphicBuffer: unregister, handle(0x8a3452f0) (w:640 h:360 s:640 f:0x23 u:0x002933)
08-10 10:16:42.201   800  1181 W ActivityManager:   Force finishing activity com.afmobi.boomplayer/com.tecno.boomplayer.newUI.MainActivity

**Comment by lipangit** [comment]
invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

这个问题可能水很深，全屏切换的时候不小心就会出现，还根本不是控件可不可见的问题，改库了吧。

断点一下surfaceAvalible，releaseVideo这两处，看看是不是有意外发生。

**Comment by StevenNick88** [comment]
08-11 13:57:38.259 10053 10053 W System.err: java.lang.IllegalStateException
08-11 13:57:38.260 10053 10053 W System.err: 	at android.media.MediaPlayer.getCurrentPosition(Native Method)
08-11 13:57:38.261 10053 10053 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:683)
08-11 13:57:38.261 10053 10053 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:522)
08-11 13:57:38.261 10053 10053 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:796)
08-11 13:57:38.261 10053 10053 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
08-11 13:57:38.261 10053 10053 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:561)
08-11 13:57:38.261 10053 10065 D BufferQueueProducer: [SurfaceTexture-0-10053-0](this:0x80097000,id:0,api:3,p:272,c:10053) cancelBuffer: slot 15
08-11 13:57:38.261 10053 10053 W System.err: 	at com.tecno.boomplayer.newUI.fragment.DiscoverVideoFragment$1.onScrolled(DiscoverVideoFragment.java:127)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3679)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.261 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.262 10053 10053 W System.err: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
08-11 13:57:38.263 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.263 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.263 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.263 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.263 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.264 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.265 10053 10053 W System.err: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
08-11 13:57:38.265 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.266 10053 10304 D BufferQueueProducer: [SurfaceTexture-0-10053-0](this:0x80097000,id:0,api:3,p:272,c:10053) cancelBuffer: slot 14
08-11 13:57:38.268 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.268 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.269 10053 10053 W System.err: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.270 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
08-11 13:57:38.271 10053 10053 W System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.View.layout(View.java:18410)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5921)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2711)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
08-11 13:57:38.271 10053 10053 W System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6965)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:917)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:715)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:650)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:903)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.os.Handler.handleCallback(Handler.java:836)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.os.Looper.loop(Looper.java:203)
08-11 13:57:38.272 10053 10053 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6288)
08-11 13:57:38.272 10053 10053 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 13:57:38.272 10053 10053 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
08-11 13:57:38.272 10053 10053 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
08-11 13:57:38.273 10053 10053 I JieCaoVideoPlayer: onStateNormal  [183801320] 


我在 
 @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                    JCVideoPlayer videoPlayer = JCVideoPlayerManager.getCurrentJcvd();
                    if (!Utils.checkIsVisible(getActivity(),videoPlayer) && videoPlayer.currentState == CURRENT_STATE_PLAYING) {
                        JCVideoPlayer.releaseAllVideos();
                    }
                }
            }

然后	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:683) 抛出了异常，为什么？

**Comment by lipangit** [comment]
只有这些吗，这就不应该了

**Comment by lipangit** [comment]
解决了吗
