### ISSUE TITLE
遇到2处内存泄漏问题

### ISSUE THREAD

**Issue by gaojunhuiBS** [lipangit/JiaoZiVideoPlayer#1131]
![image](https://user-images.githubusercontent.com/19830343/29161379-95c199d8-7de8-11e7-9958-356460cec4a7.png)
![image](https://user-images.githubusercontent.com/19830343/29161463-e6bc669c-7de8-11e7-899d-120a804333cc.png)

使用的时候已经传ApplicationContext了。
麻烦帮忙看一下。

**Comment by lipangit** [comment]
是的，代码变得极其简洁，static变量。代价就是内存泄漏，是我偷懒，你也可以研究研究怎么解决。

**Comment by lipangit** [comment]
这两个泄露解决了，可以更新一下，现在还有埋点的内存泄露
