### ISSUE TITLE
固定成横屏后，退出全屏后屏幕被固定成了竖屏，怎么解决？

### ISSUE THREAD

**Issue by ZhangYe135** [lipangit/JiaoZiVideoPlayer#1132]
activity固定成横屏后，播放视频返回键退出，activity变成了竖屏的，怎么能不让它改变屏幕方向？
还有一个情况是，activity随屏幕旋转，但是播放视频然后按返回键退出，方向还是被固定成了竖屏，怎么解决？

**Comment by lipangit** [comment]
参照demo的origintationActivity 分别设置全屏前和全屏后的屏幕方向。
