### ISSUE TITLE
Show image insted of Video and stream audio

### ISSUE THREAD

**Issue by abhay222** [lipangit/JiaoZiVideoPlayer#1138]
I am using jieCaoVideo player in my app. I want it to streaming audio but during audio streaming i want my image to be shown in the background instead of black background. Can anyone tell me how i do it.

**Comment by lipangit** [comment]
You need Thumbnails right?

You shoule put some pictures on server.

**Comment by abhay222** [comment]
Yes, i need thumbnail. but it should also be displayed when the audio is playing.

**Comment by lipangit** [comment]
extends JCVIdeoPlayerStandard
Override
onStatePlaying(){
    super.onStatePlaying();
   //visible thumbnail
}

![image](https://user-images.githubusercontent.com/2038071/29248349-ab397558-8048-11e7-9494-d4afdfe4cf32.png)

**Comment by abhay222** [comment]
@Override
    public void onStatePlaying() {
        super.onStatePlaying();
        changeUiToPlayingShow();
        startDismissControlViewTimer();
    }

    @Override
    public void changeUiToPlayingClear() {
        switch (currentScreen) {
            case SCREEN_LAYOUT_NORMAL:
            case SCREEN_LAYOUT_LIST:
                setAllControlsVisible(View.INVISIBLE, View.INVISIBLE, View.INVISIBLE, 
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE); 
                break;
            case SCREEN_WINDOW_FULLSCREEN:
                setAllControlsVisible(View.INVISIBLE, View.INVISIBLE, View.INVISIBLE,
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE);
                break;
            case SCREEN_WINDOW_TINY:
                break;
        }

    }
    @Override
    public void changeUiToPlayingShow() {
        switch (currentScreen) {
            case SCREEN_LAYOUT_NORMAL:
            case SCREEN_LAYOUT_LIST:
                setAllControlsVisible(View.INVISIBLE, View.INVISIBLE, View.INVISIBLE,
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE);
                updateStartImage();
                break;
            case SCREEN_WINDOW_FULLSCREEN:
                setAllControlsVisible(View.INVISIBLE, View.INVISIBLE, View.INVISIBLE,
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE);
                updateStartImage();
                break;
            case SCREEN_WINDOW_TINY:
                break;
        }

    }

i did something like this but it didn't worked.  i made thumbnail visible only in both the methods changeUiToPlayingClear() and changeUiToPlayingShow() but thumnail never show when player starts playing.

**Comment by lipangit** [comment]
Did solved the problem?

**Comment by Muriti** [comment]
@lipangit I did it and it worked fine. But It has another problem that I couldn't touch on video to show control view.
Can you help me resolve this problem? Many thanks!

@override
public void onStatePlaying() {
super.onStatePlaying();
thumbImageView.setVisibility(View.VISIBLE);
}

**Comment by lipangit** [comment]
Show me your complete code
Tips: you should set view visibily or invisibily in every state, or it will be covered by other state.

**Comment by Muriti** [comment]
This is my code. 
![image](https://user-images.githubusercontent.com/15323996/36037608-d66941d8-0def-11e8-9c05-ba8f9e80c5c0.png)
![image](https://user-images.githubusercontent.com/15323996/36037645-f36b1b8a-0def-11e8-87a3-cef5c93a7744.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/36059901-e682b034-0e78-11e8-854b-01a6a463fefd.png)
It does not need.

**Comment by Muriti** [comment]
I did it. Many thanks for your support. 👍

**Comment by lipangit** [comment]
Ok， be happy

**Comment by TurKurT656** [comment]
how u did it?
i've tried all of this but problem not solved. @Muriti @lipangit 
can u give me full code?

**Comment by TurKurT656** [comment]
i've log the class. onStateNormal called. i then clicked play but other states not calling and audio is playing

**Comment by TurKurT656** [comment]
http://chitaacc.ir/res/voice/vsSY03w3O17YCxtUVuMoO1IqArWNxPZKZ2rujB0i.mpga

this is the url for audio file

**Comment by lipangit** [comment]
@TurKurT656  whitch version of the lib

**Comment by TurKurT656** [comment]
6.2.10

**Comment by TurKurT656** [comment]
looks like player doesn't know that audio started
