### ISSUE TITLE
如何静音？

### ISSUE THREAD

**Issue by AwinHe** [lipangit/JiaoZiVideoPlayer#1145]
怎样在播放视频的时候静音呢？求解

**Comment by lipangit** [comment]
有朋友提交这部分代码，只静音播放器，系统还有音量，我总结一下加进来

**Comment by AwinHe** [comment]
赞

**Comment by saurylip** [comment]
同问 想知道何时加进来?

**Comment by lipangit** [comment]
这几天尽快

**Comment by zsl5684** [comment]
在自己的代码里已经解决掉声音和系统分开控制，静音啥的都没有问题

**Comment by lipangit** [comment]
@zsl5684 能提交pr分享出来吗

**Comment by zsl5684** [comment]
@lipangit 可以的 需要整理下 然后我提上去吧 刚好大家可以发现更多的问题补足下

**Comment by lipangit** [comment]
好

**Comment by w0080626** [comment]
@AwinHe  你的问题我有个解决方案 [#1549](https://github.com/lipangit/JiaoZiVideoPlayer/issues/1549)
