### ISSUE TITLE
URL redirect

### ISSUE THREAD

**Issue by nemdaz** [lipangit/JiaoZiVideoPlayer#1147]
How can I enable the process of a  url with redirect? 
Example: 
`url = http://some.com/videoxasas/item32 ` 
redirect to 
`url_final = http://newsome.com/videofinal/video32.mp4  `

```
mVideoView.setUp(url, ...) /* Not work */
mVideoView.setUp(url_final, ...) /* Work */
```

But i only have `url`

**Comment by lipangit** [comment]
android.media.MediaPlayer  do not support redirect

You can extends JCVideoPlayerStandard, get final url first, then play real video
