### ISSUE TITLE
5.8版本播放mp3除了有声音，其他操作无效，显示时长和进度也无效

### ISSUE THREAD

**Issue by 867588763** [lipangit/JiaoZiVideoPlayer#1149]
5.8版本播放mp3除了有声音，其他操作无效，显示时长和进度也无效

**Comment by lipangit** [comment]
能发我个测试连接吗，可以发到邮箱或者qq里

**Comment by 867588763** [comment]
http://so1.111ttt.com:8282/2017/1/05m/09/298092041338.m4a?tflag=1502933064&pin=e11b2213835f72ad93a03e968e120415&ip=220.248.21.202#.mp3

**Comment by lipangit** [comment]
这是个问题，因为为了解决开始播放界面没有0.1s(z左右)的黑屏，以开始render图像为播放开始的标志，mp3没有图像所以不会进入播放状态，你可以先用5.7版本

**Comment by 867588763** [comment]
好的

**Comment by luckyXingYan** [comment]
去哪里 下载 5.7版本？想 用 音视频兼容的

**Comment by lipangit** [comment]
v5.7分支 @luckyXingYan

**Comment by lipangit** [comment]
用新版
