### ISSUE TITLE
在andorid 5.1的机器上播放视频，然后按最近任务键，再次选择app回到播放界面，视频表现为继续播放，但画面不动，请问可能的原因是什么？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1151]

**Comment by StevenNick88** [comment]
能上传视频吗？我可以提供视频

**Comment by lipangit** [comment]
按最近任务键是否进入activity的onPause？

**Comment by lipangit** [comment]
这应该和具体的视频无关

**Comment by StevenNick88** [comment]
是进入了activity的onPause，我在但是onPause中暂停了视频，但是我在onResume方法中我又继续播放视频了。下面是我在onPause和onResume中分别调的方法：
  /**
     * Pause the standard video player.
     * Used in the method such as onPause() in Activity or Fragment.
     */
    public static void pauseVideo() {
        try {
            int state = 10;
            if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                JCVideoPlayer videoPlayer = JCVideoPlayerManager.getCurrentJcvd();
                state = videoPlayer.currentState;
                Log.v(TAG, "----state: " + state);
                if (state == CURRENT_STATE_PREPARING) {
                    Log.v(TAG, "resumeVideo mediaPlayer CURRENT_STATE_PREPARING mediaPlayer.release()");
                    JCMediaManager.instance().mediaPlayer.release();
                    return;
                }
                Log.v(TAG, "pauseVideo mediaPlayer" + JCMediaManager.instance().mediaPlayer + "----state: " + state);
                if (JCMediaManager.instance().mediaPlayer != null &&
                        JCMediaManager.instance().mediaPlayer.isPlaying() || state == CURRENT_STATE_PLAYING_BUFFERING_START) {
                    JCMediaManager.instance().mediaPlayer.pause();
                    isPauseByClick = false;
                    Log.v(TAG, "pauseVideo1" + "----mediaPlayer" + JCMediaManager.instance().mediaPlayer + "----state: " + state);
                }
            }

        } catch (IllegalStateException e) {
            e.printStackTrace();
        }
    }

    /**
     * Resume the standard video player.
     * Used in the method such as onResume() in Activity or Fragment.
     */
    public static void resumeVideo() {
        try {
            int state=10;
            if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                JCVideoPlayer videoPlayer = JCVideoPlayerManager.getCurrentJcvd();
                state = videoPlayer.currentState;
                Log.v(TAG,"----state: "+state);
                if (state == CURRENT_STATE_PREPARING || state == CURRENT_STATE_AUTO_COMPLETE) {
                    Log.v(TAG,"resumeVideo mediaPlayer CURRENT_STATE_PREPARING mediaPlayer.release()");
//                    JCMediaManager.instance().mediaPlayer.release();
                    return;
                }
                Log.v(TAG,"resumeVideo mediaPlayer"+JCMediaManager.instance().mediaPlayer+"----state: "+state);
                if (JCMediaManager.instance().mediaPlayer != null && !JCMediaManager.instance().mediaPlayer
                        .isPlaying() && !isPauseByClick) {
                    JCMediaManager.instance().mediaPlayer.start();
                    Log.v(TAG, "resumeVideo1" + "----mediaPlayer.start()----state: " + state);
                }
            }
        } catch (RuntimeException e) {
            e.printStackTrace();
            Log.v(TAG,"resumeVideo e"+e.getMessage());
        }
    }

**Comment by StevenNick88** [comment]
我说的是上传出现这个问题的视频录屏，不是说播放的那个视频

**Comment by StevenNick88** [comment]
是否是该控件在该机型上解码跟不上导致？

**Comment by lipangit** [comment]
reSume的时候一个操作MediaPlayer，一个通过setState操作UI，这块再调试调试吧

**Comment by StevenNick88** [comment]
我这个没问题，我在所以机器上再回来都可以继续播放的，就只有一个5.1的机器画面不动，但是声音和进度都在播

**Comment by lipangit** [comment]
断点一下这个函数
![image](https://user-images.githubusercontent.com/2038071/29394053-7f8afc0c-833a-11e7-991f-c48927d9cb7b.png)

**Comment by StevenNick88** [comment]
那个出问题的手机没root过啊，内置有那个app，没法调试啊

**Comment by lipangit** [comment]
log能看到吗

**Comment by lipangit** [comment]
没图像基本都是这的问题

**Comment by StevenNick88** [comment]
log有，我每行都加了log，和正常的机器打出的log是一样的，好像不是这的问题

**Comment by lipangit** [comment]
这个你帮忙研究研究吧，怎么会有这样的问题

**Comment by lipangit** [comment]
还有这个问题吗
