### ISSUE TITLE
急！急！急！播放过程中进行wifi和4G切换问题

### ISSUE THREAD

**Issue by hui928636443** [lipangit/JiaoZiVideoPlayer#1152]
网络切换后 播放完缓冲，播放状态会变成ERROR,急需解决

**Comment by lipangit** [comment]
没网了，进入error状态应该是合理的，你觉得呢

**Comment by hui928636443** [comment]
只是网络切换 网还是在的，只是把Wi-Fi切换成4g或者4g切换成Wi-Fi，频繁切换就会偶现error 不是必现

**Comment by lipangit** [comment]
刚才测试了一下，一般情况从wifi切换到4g应该是不影响播放，我觉得android.media.MediaPlayer有重连机制。  这个问题可能超出老臣解决范围，我不知道android.media.MediaPlayer做了什么，不知道怎么修改

**Comment by hui928636443** [comment]
进入error后点击屏幕中间出现的按钮视频又从头播放 没有记住以前播放的位置这个地方还是要改的，别的播放器不会从头播放

**Comment by lipangit** [comment]
有道理，onError的时候也要记录播放位置

**Comment by hui928636443** [comment]
在那里记住播放位置，让我先改一把，急

**Comment by lipangit** [comment]
onError 函数，  JCUtil.saveProgress保存进度

**Comment by hui928636443** [comment]
谢了 明天试试

**Comment by hui928636443** [comment]
能否加个微信 还有个问题需要请教

**Comment by lipangit** [comment]
lipanhelloworld
