### ISSUE TITLE
怎么禁止横竖屏自动切换？

### ISSUE THREAD

**Issue by lizi0588** [lipangit/JiaoZiVideoPlayer#1153]
调用JCVideoPlayer.releaseAllVideos()方法后自动切换了竖屏，请问怎么禁止横竖屏自动切换？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29396908-7c70edac-834d-11e7-853b-07848d8f5639.png)

这两个变量控制全屏前和全屏后的屏幕方向，参照demo的origintationActivity
