### ISSUE TITLE
播放出错

### ISSUE THREAD

**Issue by raymondcqk** [lipangit/JiaoZiVideoPlayer#1154]
![image](https://user-images.githubusercontent.com/19503881/29400667-c33a88de-8360-11e7-939d-2ec2b0e27a0b.png)
异常如图
是播放到自动缓冲的位置就播放失败了
不能继续自动缓冲下去

**Comment by loveRose** [comment]
同样的问题

**Comment by henry-newbie** [comment]
+1

**Comment by m5314** [comment]
我也遇到，我的情况是播了一部分后链接失效了（如优酷视频，抓回来的链接是有时效的），导致视频无法继续缓存

**Comment by lipangit** [comment]
@m5314 时效这么短

**Comment by hui928636443** [comment]
+1
