### ISSUE TITLE
如何将setProgressAndText()这个里面的参数回调到最外面？

### ISSUE THREAD

**Issue by AwinHe** [lipangit/JiaoZiVideoPlayer#1156]
@Override
    public void setProgressAndText(int progress, int position, int duration) {
        super.setProgressAndText(progress, position, duration);
        if (progress != 0) bottomProgressBar.setProgress(progress);
        Log.e("============", "===progress=====" + progress + "====duration===" + duration);
        onJCVideoPlayerListener.onJCVideoPlayer(progress, position);
    }

 public interface OnJCVideoPlayerListener {
        public void onJCVideoPlayer(int progress, int position);
    }

    private OnJCVideoPlayerListener onJCVideoPlayerListener;

    public void setJCVideoPlayerClickListener(OnJCVideoPlayerListener onClickListener) {
        this.onJCVideoPlayerListener = onClickListener;
    }

我这样写一个接口回调出去调用全屏的时候这个接口会报空 ，有好的解决办法吗

**Comment by lipangit** [comment]
因为全屏和非全屏的jcvd不是一个实例
![image](https://user-images.githubusercontent.com/2038071/29442179-87921520-8402-11e7-8e44-399cf8deaf6e.png)

参照demo，复写setProgressAndText函数，这是建议的做法

**Comment by AwinHe** [comment]
还有视频设置静音和取消静音的代码可以给出来吗
