### ISSUE TITLE
自动播放下一集的需求

### ISSUE THREAD

**Issue by hui928636443** [lipangit/JiaoZiVideoPlayer#1157]
JCVideoPlayerStandard 怎么实现播放一个集合的视频地址，自动播放完一集跳转下一集

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写函数
Override 
onAutoComplete(){//自动播放完毕
    onStatePreparingChangingUrl();//参照切换清晰度切换url,调用这个函数可以随时切换url
}

Override
onComplete(){
}

**Comment by Billhome** [comment]
你好，自动播放功能修改好了吗？我修改的在播放地方第二个视频时候会出现进度错乱的问题，，，

**Comment by hui928636443** [comment]
还没开始搞，过几天就要搞了，啥时候能修复 老哥

**Comment by lipangit** [comment]
进度是怎么错乱法 @Billhome
