### ISSUE TITLE
【建议】增加一个CurrentState回调的Listener

### ISSUE THREAD

**Issue by 164738777** [lipangit/JiaoZiVideoPlayer#1158]
对比了 **5.5.4** 与 **5.8.1** ，发现 `setUiWitStateAndScreen(...)` 这个方法被‘打散’成几个方法。因为需求在 `setUiWitStateAndScreen(...)` 里面，对几个状态的处理写了一些代码，但是被打散后不怎么方便。（虽然也是复制黏贴而已= =）

# 打扰大佬们~

**Comment by lipangit** [comment]
就是说有些修改是所有状态都要修改的，这块我还是欠考虑，并且需要重构，感谢你的提醒，日后会修改。
