### ISSUE TITLE
进度条更新问题

### ISSUE THREAD

**Issue by TxShon** [lipangit/JiaoZiVideoPlayer#1160]
JieCaoVideoPlayer这个类的onTouch()中，ACTION_CANCEL没处理，会导致详情页的底部进度条无法更新。
复现步骤：在列表页触发ACTION_CANCEL后进入详情查看进度

**Comment by lipangit** [comment]
onTouch是全屏时候手势的判断，范围是全屏的，什么情况下会触发ACTION_CANCEL？
