### ISSUE TITLE
怎么打开视频就隐藏loadingProgressBar和bottomProgressBar

### ISSUE THREAD

**Issue by jiaok** [lipangit/JiaoZiVideoPlayer#1165]
重写了JCVideoPlayerStandard但是loadingProgressBar和bottomProgressBar隐藏不了，请问怎么让这两个ProgressBar自始至终都不显示？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29518431-dcfdbacc-86ab-11e7-9b5e-6b0624b90eff.png)

分别设置这些状态的UI，否则控件的操作会被覆盖
