### ISSUE TITLE
5.8.1解决黑屏跳帧问题的修改，存在问题，请知悉

### ISSUE THREAD

**Issue by wjy591416** [lipangit/JiaoZiVideoPlayer#1166]
JCMediaManager方法中
@Override
    public void onPrepared(MediaPlayer mp) {
        mediaPlayer.start();
    }
这么修改是有问题的，在部分机型上回出现只有声音，没有图像的问题
出现（-38，0）错误，

 mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                  
                }
            }
        });
还是需要有这个的

但是在其中添加了mainThreadHandler的话，由会有图片到视频有跳帧的问题，
请知悉

**Comment by wjy591416** [comment]
经过测试，如果在onPrepared，调用
  mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                    JCVideoPlayerManager.getCurrentJcvd().onVideoRendingStart();
                }
            }
        });
有可能会出现快进的情况

**Comment by lipangit** [comment]
@Lionet6  看看这哥们说的，有这个问题吗？

并且现在是以视频render开始为标志，mp3没有，所以mp3不会进入播放状态，这个问题

**Comment by wjy591416** [comment]
@lipangit 确实有，用没替换jcvideo之前的suferview+ MediaPlayer，在4.0.4的平板上是能播放的，5.7的jcvideo也没有问题，但是5.8.1的就不行
经过测试，
JCMediaManager这个方法中不修改，依旧使用
@override
public void onPrepared(MediaPlayer mp) {
mediaPlayer.start();
mainThreadHandler.post(new Runnable() {
@override
public void run() {
if (JCVideoPlayerManager.getCurrentJcvd() != null) {
CVideoPlayerManager.getCurrentJcvd().onPrepared();
            }
        }
    });
}
在JCVideoPlayer中还原，onPrepared方法，，onVideoRendingStart只需要 isVideoRendingStart = true;
 public void onVideoRendingStart() {
        isVideoRendingStart = true;
    }
这样也能达到无黑屏效果，同时，在我的测试机中能正常播放

**Comment by ldy441040480** [comment]
部分机型？能详细说一下吗，那个设备

**Comment by lipangit** [comment]
MP3建议用5.7版本，新版有问题

**Comment by ldy441040480** [comment]
帮提供一个.mp3格式视频链接，谢谢
