### ISSUE TITLE
视频添加header

### ISSUE THREAD

**Issue by wangbiaohome** [lipangit/JiaoZiVideoPlayer#1174]
有的视频地址需要添加referer和cookie.用jiecaomamager里面的header貌似没有用  很久以前的版本好像setup支持传header.gsyvideo这个目前支持header且有效！。

**Comment by lipangit** [comment]
用android.media.MediaPlayer的header测试一下是否管用。

![image](https://user-images.githubusercontent.com/2038071/29614403-9e9f58e8-883c-11e7-8275-0317af94b8bd.png)

这个变量不管用吗

**Comment by wangbiaohome** [comment]
这个变量最后不是赋值给了JCManager的一个map吗
设置的好像无效

**Comment by lipangit** [comment]
用android.media.MediaPlayer的header测试一下是否管用。

**Comment by wangbiaohome** [comment]
我主要用你的播放器啊 android的原生功能都没有。我用你这个怎么对接原生那个呢？另外我截图了  你看你的那个header。`public void setUp(String url, int screen, Object... objects) {
        if (!TextUtils.isEmpty(this.url) && TextUtils.equals(this.url, url)) {
            return;
        }
        this.url = url;
        this.objects = objects;
        this.currentScreen = screen;
        this.headData = null;
        onStateNormal();
    }`这个构造方法把headData设为null。
后面的startvideo又把null给了JCMediaManager.

`public void startVideo() {
        JCVideoPlayerManager.completeAll();
        Log.d(TAG, "startVideo [" + this.hashCode() + "] ");
        initTextureView();
        addTextureView();
        AudioManager mAudioManager = (AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE);
        mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        JCUtils.scanForActivity(getContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        JCMediaManager.CURRENT_PLAYING_URL = url;
        JCMediaManager.CURRENT_PLING_LOOP = loop;
        JCMediaManager.MAP_HEADER_DATA = headData;
        onStatePreparing();
        JCVideoPlayerManager.setFirstFloor(this);
    }`

**Comment by lipangit** [comment]
你就用最简单的android.media.MediaPlayer设置header是否管用，你先别管库，管用还是不管用，这个库的播放引擎就是android.media.MediaPlayer系统播放器。

把header设置在setUp之后就好了
