### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by IHansan** [lipangit/JiaoZiVideoPlayer#1177]
项目上线，大概有几百个人用有一个用户出现空指针情况
java.lang.NullPointerException
Attempt to invoke virtual method 'int java.util.LinkedHashMap.size()' on a null object reference
1 fm.jiecao.jcvideoplayer_lib.JCUtils.getCurrentUrlFromMap(Unknown Source)
2 fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(Unknown Source)
3 fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(Unknown Source)
4 android.view.View.performClick(View.java:4757)
5 android.view.View$PerformClick.run(View.java:19757)
6 android.os.Handler.handleCallback(Handler.java:739)
7 android.os.Handler.dispatchMessage(Handler.java:95)
8 android.os.Looper.loop(Looper.java:135)
9 android.app.ActivityThread.main(ActivityThread.java:5305)
10 java.lang.reflect.Method.invoke(Native Method)
11 java.lang.reflect.Method.invoke(Method.java:372)
12 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

手机信息：
系统版本
Android 5.0.2,level 21
ROM
vivo/FUNTOUCH
CPU架构
armeabi-v7a
使用时长
12 秒
可用内存大小 | 580.13 MB ( 30.34% ) | 可用存储空间 | 1.23 GB ( 11.63% )
jiecao版本
compile 'fm.jiecao:jiecaovideoplayer:5.8.1'

**Comment by lipangit** [comment]
估计LinkedHashMap是空了，需要确认一下setUp传的视频地址不能为空

![image](https://user-images.githubusercontent.com/2038071/29725107-97d92210-89fd-11e7-9433-ec11eb108535.png)

复写这个函数打印一下getCurrentUrlFromMap相关变量，为什么有空
