### ISSUE TITLE
全屏问题

### ISSUE THREAD

**Issue by 2366634662** [lipangit/JiaoZiVideoPlayer#1178]
JCVideoPlayerStandard.startFullscreen(mContext, JCVideoPlayerStandard.class, item.video_address, "");   开启全屏后，可以自动切换横竖屏，但是点右下角的切换横竖屏不能生效，始终是退出播放视屏页面

**Comment by lipangit** [comment]
右下角是退出全屏按钮，不能切换横竖屏。

**Comment by shaomiao** [comment]
可以在全屏播放的时候监听到返回的事件吗

**Comment by lipangit** [comment]
可以，继承JCVideoPlayerStandard，复写onClick函数，参照父类，取得各种按钮的点击事件

**Comment by shaomiao** [comment]
那物理按键返回可以监听吗 就是在继承JCVideoPlayerStandard的类

**Comment by lipangit** [comment]
返回键在Activity的backPress监听
