### ISSUE TITLE
这个怎么不能播放

### ISSUE THREAD

**Issue by marscl** [lipangit/JiaoZiVideoPlayer#1179]
http://222.37.159.225:13164/playurl.m3u8?playtype=live&protocol=ios&accesstoken=R58466B04U387E6625K7735CA24M2FF85C5W3078869&verifycode=2000000610&playtoken=ABCDEFGH&programid=4200000154

**Comment by lipangit** [comment]
08-26 01:13:55.579 28675-28675/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: startVideo [168595523] 
08-26 01:13:55.585 28675-28688/fm.jiecao.jiecaovideoplayer D/AudioSystem: getIoDescriptor: ioHandle = 2, index = -2, mIoDescriptors = 0x7f5dc71550
08-26 01:13:55.585 28675-28732/fm.jiecao.jiecaovideoplayer D/AudioSystem: getIoDescriptor: ioHandle = 4, index = -2, mIoDescriptors = 0x7f5dc71550
08-26 01:13:55.587 28675-28675/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: addTextureView [168595523] 
08-26 01:13:55.590 28675-28675/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onStatePreparing  [168595523] 
08-26 01:13:55.593 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [111306925] 
08-26 01:13:55.593 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
08-26 01:13:55.593 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
08-26 01:13:55.594 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [111306925] 
08-26 01:13:55.594 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
08-26 01:13:55.594 28675-28675/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
08-26 01:13:55.601 28675-28675/fm.jiecao.jiecaovideoplayer I/BufferQueue: [unnamed-28675-0](this:0x7f5dc64000,id:0,api:0,p:-1,c:-1) BufferQueue core=(28675:fm.jiecao.jiecaovideoplayer)
08-26 01:13:55.602 28675-28675/fm.jiecao.jiecaovideoplayer I/BufferQueueConsumer: [unnamed-28675-0](this:0x7f5dc64000,id:0,api:0,p:-1,c:28675) connect(C): consumer=(28675:fm.jiecao.jiecaovideoplayer) controlledByApp=true
08-26 01:13:55.602 28675-28675/fm.jiecao.jiecaovideoplayer I/BufferQueueConsumer: [unnamed-28675-0](this:0x7f5dc64000,id:0,api:0,p:-1,c:28675) setConsumerName: unnamed-28675-0
08-26 01:13:55.602 28675-28675/fm.jiecao.jiecaovideoplayer I/BufferQueueConsumer: [SurfaceTexture-0-28675-0](this:0x7f5dc64000,id:0,api:0,p:-1,c:28675) setConsumerName: SurfaceTexture-0-28675-0
08-26 01:13:55.602 28675-28675/fm.jiecao.jiecaovideoplayer I/BufferQueueConsumer: [SurfaceTexture-0-28675-0](this:0x7f5dc64000,id:0,api:0,p:-1,c:28675) setDefaultBufferSize: width=1080 height=600
08-26 01:13:55.603 28675-28675/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureAvailable [168595523] 
08-26 01:13:55.604 28675-28704/fm.jiecao.jiecaovideoplayer I/GLConsumer: [SurfaceTexture-0-28675-0] attachToContext
08-26 01:13:55.609 28675-28759/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
08-26 01:13:55.619 28675-28759/fm.jiecao.jiecaovideoplayer D/MediaPlayer: Don't notify duration to fm.jiecao.jiecaovideoplayer!
08-26 01:13:55.621 28675-28759/fm.jiecao.jiecaovideoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
08-26 01:13:55.626 28675-28759/fm.jiecao.jiecaovideoplayer I/BufferQueueProducer: [SurfaceTexture-0-28675-0](this:0x7f5dc64000,id:0,api:3,p:488,c:28675) connect(P): api=3 producer=(488:???) producerControlledByApp=true
08-26 01:13:55.642 28675-28732/fm.jiecao.jiecaovideoplayer D/MediaHTTPConnection: disconnect finish
08-26 01:13:55.646 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk hostname=222.37.159.225; servname=(null); netid=0; mark=0
08-26 01:13:55.646 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo( app_uid:10388
08-26 01:13:55.646 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() uid prop:
08-26 01:13:55.646 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() getuid():10388
08-26 01:13:55.646 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-26 01:13:55.647 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk hostname=222.37.159.225; servname=(null); netid=0; mark=0
08-26 01:13:55.647 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo( app_uid:10388
08-26 01:13:55.647 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() uid prop:
08-26 01:13:55.648 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() getuid():10388
08-26 01:13:55.648 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk hostname=222.37.159.225; servname=(null); netid=0; mark=0
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo( app_uid:10388
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() uid prop:
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() getuid():10388
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
08-26 01:13:55.649 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk hostname=222.37.159.225; servname=(null); netid=0; mark=0
08-26 01:13:55.650 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo( app_uid:10388
08-26 01:13:55.650 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() uid prop:
08-26 01:13:55.650 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: getaddrinfo() getuid():10388
08-26 01:13:55.650 28675-28687/fm.jiecao.jiecaovideoplayer D/libc-netbsd: [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
08-26 01:13:55.651 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [CDS]rx timeout:60000
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:10
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:2
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [socket][0] connection /222.37.159.225:13164;LocalPort=46655(30000)
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:2
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [CDS]connect[/222.37.159.225:13164] tm:30
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer D/Posix: [Posix_connect Debug]Process fm.jiecao.jiecaovideoplayer :13164 
08-26 01:13:55.652 28675-28687/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:2
08-26 01:13:55.740 28675-28687/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:2
08-26 01:13:55.740 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [socket][/192.168.31.164:46655] connected
08-26 01:13:55.741 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [CDS]rx timeout:60000
08-26 01:13:55.741 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [CDS]SO_SND_TIMEOUT:0
08-26 01:13:55.741 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [OkHttp] sendRequest>>
08-26 01:13:55.742 28675-28687/fm.jiecao.jiecaovideoplayer I/System.out: [OkHttp] sendRequest<<
08-26 01:13:55.850 28675-28687/fm.jiecao.jiecaovideoplayer D/MediaHTTPConnection: mTotalSize=-1
08-26 01:13:56.942 28675-28766/fm.jiecao.jiecaovideoplayer D/MediaHTTPConnection: teardownConnection
08-26 01:13:56.943 28675-28766/fm.jiecao.jiecaovideoplayer I/System.out: Close in OkHttp
08-26 01:13:56.943 28675-28766/fm.jiecao.jiecaovideoplayer E/NetworkUtilities: [MTK_net]ss.ss_family:2
08-26 01:13:56.944 28675-28766/fm.jiecao.jiecaovideoplayer I/System.out: close [socket][/192.168.31.164:46655]
08-26 01:13:56.944 28675-28766/fm.jiecao.jiecaovideoplayer D/MediaHTTPConnection: disconnect finish
08-26 01:13:56.946 28675-28732/fm.jiecao.jiecaovideoplayer D/MediaHTTPConnection: disconnect finish
08-26 01:13:56.959 28675-28766/fm.jiecao.jiecaovideoplayer E/MediaPlayer: error (1, -1004)
08-26 01:13:56.959 28675-28759/fm.jiecao.jiecaovideoplayer D/MediaPlayer: handleMessage msg:(100, 1, -1004)
08-26 01:13:56.959 28675-28759/fm.jiecao.jiecaovideoplayer E/MediaPlayer: Error (1,-1004)
08-26 01:13:56.961 28675-28675/fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError 1 - -1004 [168595523] 
08-26 01:13:56.961 28675-28675/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onStateError  [168595523]

**Comment by lipangit** [comment]
对不起，超出老臣解决范围，我在群里问问

**Comment by Mezart** [comment]
不支持的视频格式！
