### ISSUE TITLE
手势滑动快进快退太多

### ISSUE THREAD

**Issue by wangbiaohome** [lipangit/JiaoZiVideoPlayer#1182]
播放过程中  手势滑动快进快退一下快进了好几分钟   请问怎么让滑动10s一次呢    这个可以修复吗

**Comment by lipangit** [comment]
没研究过，你可以研究研究 提交代码

**Comment by lipangit** [comment]
没研究过，你可以研究研究 提交代码

**Comment by lipangit** [comment]
这功能完成了吗

**Comment by abc20899** [comment]
//计算快进位置  mScreenWidth * 4     修改
mSeekTimePosition = (int) (mGestureDownPosition + deltaX * totalTimeDuration / (mScreenWidth * 4));

**Comment by shuncaigao** [comment]
请问这个问题修复了吗？

**Comment by shuncaigao** [comment]
请问这个修改进度问题放出接口了吗？

**Comment by lipangit** [comment]
暂时没有，可以通过复写onTouch函数，自定义，把父类的东西copy出来，然后修改个别位置即可
