### ISSUE TITLE
如何显示视频加载进度百分比？

### ISSUE THREAD

**Issue by jayleco** [lipangit/JiaoZiVideoPlayer#1187]
由于默认加载时显示的就是一个圈，没有百分比显示，遇到加载较久的资源时用户可能会觉得资源失效或者有问题，用户体验不是很好，如何实现加载时直接显示加载进度百分比呢？

**Comment by lipangit** [comment]
android.media.MediaPlayer暂时无法取得加载百分比，你可以研究一下

**Comment by jayleco** [comment]
我可能描述的不准确，应该缓冲百分比

**Comment by lipangit** [comment]
@jayleco 你可以调研一下android.media.MediaPlayer如何取得prepare的缓冲百分比，应该是没有

**Comment by jayleco** [comment]
好的，感谢作者
