### ISSUE TITLE
如何让视频填充整个控件

### ISSUE THREAD

**Issue by ERICLIKESMILE** [lipangit/JiaoZiVideoPlayer#1188]
在播放的时候 视频左右两侧无法填充整个控件 (控件有固定大小)

**Comment by lipangit** [comment]
这是正常显现

如果不能接受的话继承JCVideoPlayerStandard复写onVideoSizeChanged函数，修改textureView的大小

**Comment by lipangit** [comment]
用新版，demo中有例子
