### ISSUE TITLE
在点击右下角的全屏按钮的时候报空指针异常

### ISSUE THREAD

**Issue by guozhiqiang123** [lipangit/JiaoZiVideoPlayer#1190]
![tim 20170831171358](https://user-images.githubusercontent.com/20378988/29915978-008cfb12-8e70-11e7-823e-6769dfb3a1e7.png)
我已经继承V7包的AppCompatActivity了。而且application的主题使用的是Theme.AppCompat

**Comment by lipangit** [comment]
断点，看看那个变量是null

**Comment by guozhiqiang123** [comment]
![tim 20170905094348](https://user-images.githubusercontent.com/20378988/30041711-e82cc41e-921e-11e7-9181-94421a146d53.png)
在JCVideoPlayer这个类中。我使用红米note3测试的，5.1的系统。但是在红米1上又不会报错。

**Comment by guozhiqiang123** [comment]
![tim 20170905101508](https://user-images.githubusercontent.com/20378988/30042762-e3222da4-9225-11e7-88a9-09bce99d9717.png)
![tim 20170905101731](https://user-images.githubusercontent.com/20378988/30042758-e1d2d69c-9225-11e7-8c4e-ff9540a2cf88.png)
![tim 20170905103358](https://user-images.githubusercontent.com/20378988/30042759-e1f6627e-9225-11e7-9b33-990eb34fb755.png)

**Comment by lipangit** [comment]
包含jzvd的activity要继承AppCompatActivity

**Comment by guozhiqiang123** [comment]
没有直接继承，但是我自的BaseActivity是继承自AppCompatActivity的

**Comment by guozhiqiang123** [comment]
而且我刚试了下 直接继承 还是那个地方出错，崩溃！！！手动泪崩！

**Comment by guozhiqiang123** [comment]
按物理返回键 或者是点击重播，这个方法返回的都是null，导致直接崩溃
![tim 20170905151700](https://user-images.githubusercontent.com/20378988/30049454-55408c06-924d-11e7-9391-7bb257a0bba6.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/30054661-5b052810-925f-11e7-8fba-ef58cdc2b13d.png)

好像这个有问题

**Comment by guozhiqiang123** [comment]
这个是我后来自己想解决方案瞎改的 截图的时候忘记改回去了。

**Comment by lipangit** [comment]
demo有这问题吗，私自改库了吗
