### ISSUE TITLE
在列表中点击item播放的时候，直接让他全屏播放，请问该怎么修改，谢谢！急。

### ISSUE THREAD

**Issue by quguangle** [lipangit/JiaoZiVideoPlayer#1195]
在列表中点击item播放的时候，直接让他全屏播放，请问该怎么修改，谢谢！急。

**Comment by lipangit** [comment]
参照demo的playDirectrlyActivity

**Comment by LinkSy** [comment]
@quguangle  请问你怎么解决的

**Comment by quguangle** [comment]
它里面有个API，但是有个缺陷，就是放完之后就直接退出来了，这样用户体验很差

**Comment by LinkSy** [comment]
@quguangle  能否贴一下代码
