### ISSUE TITLE
在小米tv上面,只有声音,没有画面!

### ISSUE THREAD

**Issue by wingfordream** [lipangit/JiaoZiVideoPlayer#1197]
在做tv盒子的应用,在大部分盒子上面正常,但是目前就碰到在小米tv上,只有声音没有画面,硬件加速也开了!

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98  有声音无画面

**Comment by wingfordream** [comment]
之前看过这个,目前就只在小米tv上没画面,硬件加速啥也都开了,都一样,直接用的demo.apk跑也一样!

**Comment by lipangit** [comment]
新建个项目，用单纯的MediaPlayer和TextureView试试，能播放视频吗

**Comment by wingfordream** [comment]
只用单纯的MediaPlayer和TextureView还真播放不了!

**Comment by lipangit** [comment]
硬件加速的问题吧，研究textureView在小米tv的兼容的问题，这是个问题
