### ISSUE TITLE
支持这种直播流吗？

### ISSUE THREAD

**Issue by lhxx225** [lipangit/JiaoZiVideoPlayer#1198]
http://cdn1.myntv.cn/mytv4/mytv4.flv/playlist.m3u8?wsSecret=8FC0533E573FCB656BA71B82BE294C77andwsTime=59AD28CA->video/mp4
有声音，没有画面，且声音也只有14s

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 有声音无画面
