### ISSUE TITLE
Not Playing the Video

### ISSUE THREAD

**Issue by ABBIGADDU** [lipangit/JiaoZiVideoPlayer#1199]
/M4U_L:  ioctl MTK_M4U_T_M4UDrv_CONSTRUCT fail! 2, No such file or directory 
 E/MediaPlayer: error (260, -110)
 E/MediaPlayer: Error (260,-110)
 E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
 E/MediaPlayer: error (-38, 0)
 E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
 E/MediaPlayer: error (-38, 0)
 E/MediaPlayer: Error (-38,0)
 E/MediaPlayer: Error (-38,0)
E/JieCaoVideoPlayer: onError 260 - -110 [1154239456] 
 E/JieCaoVideoPlayer: onError -38 - 0 [1154239456] 
 E/JieCaoVideoPlayer: onError -38 - 0 [1154239456]

**Comment by lipangit** [comment]
Often appear？

When mediaPlayer hase released can not getDuration

**Comment by ABBIGADDU** [comment]
Previously it's working with same video now it's not working why ?
and one more thing i need when video started and pause condition's need to read how ?

**Comment by lipangit** [comment]
extends JCVideoPlayerStandard
![image](https://user-images.githubusercontent.com/2038071/30048918-0a13ba98-924b-11e7-9f4f-7488bb546845.png)

you can catch lifecycle

**Comment by ABBIGADDU** [comment]
no actually i am using its on recycler adapter .
any one of the case i needed in that if which video is started for playing
        if (holder.video_view.startButton.isPressed()) {
            postIncrementViwer(video_id);
            postingHistorylist(video_id);
        }

**Comment by lipangit** [comment]
Did you solved the problem?
