### ISSUE TITLE
M3u8 的播放不了啊

### ISSUE THREAD

**Issue by csh159** [lipangit/JiaoZiVideoPlayer#1200]

**Comment by YangShaoXiong** [comment]
怎么会呢！只要是3.0以上的系统，自带的MediaPlayer是支持m3u8格式的视频的

**Comment by csh159** [comment]
09-05 09:40:14.519 998-2830/com.jxnews.jxtt E/MediaPlayer: Error (-2147483648,0)
09-05 09:40:14.522 998-998/com.jxnews.jxtt I/JieCaoVideoPlayer: onStatePlaying  [29407646] 
                                                                
                                                                [ 09-05 09:40:14.527   791:10563 E/         ]
                                                                Service not available yet
09-05 09:40:14.552 998-998/com.jxnews.jxtt E/JieCaoVideoPlayer: onError -2147483648 - 0 [29407646] 
09-05 09:40:14.553 998-998/com.jxnews.jxtt I/JieCaoVideoPlayer: onStateError  [29407646] 
09-05 09:40:14.560 998-998/com.jxnews.jxtt E/MediaPlayer: Attempt to call getDuration in wrong state: mPlayer=0xc907a020, mCurrentState=0
09-05 09:40:14.560 998-998/com.jxnews.jxtt E/MediaPlayer: error (-38, 0)

**Comment by lipangit** [comment]
m3u8的问题可能超出老臣解决范围 研究好android.media.MediaPlayer就能解决这个问题
