### ISSUE TITLE
视频列表内存问题，请重视一下。

### ISSUE THREAD

**Issue by gaojunhuiBS** [lipangit/JiaoZiVideoPlayer#1201]
您好，我这MainActivity中的一个Fragment是一个视频列表，每次打开应用初始化这个页面后，内存就暴升了，又由于这个视频列表MainAcitivity里面，内存就一直降不下去，请问，您有什么好的解决方案嘛？

**Comment by lipangit** [comment]
如果不播放视频内存会涨，爆升涨了多少，是缩略图的问题还是视频的问题，确认一下

**Comment by gaojunhuiBS** [comment]
![image](https://user-images.githubusercontent.com/19830343/30056238-8f021966-9264-11e7-8250-6d087ff23ba5.png)
感谢您的回复，我已经去掉缩略图了，基本这个视频列表初始化完之后，内存就会直接从40+升到80~100之间，而且再就降不下去了。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/30056728-708d7758-9266-11e7-8bee-73388d615999.png)

我觉得不是视频的原因，咱们用android.media.MediaPlayer播放视频占用的资源是非常少的，这是demo的ListActivity的monitors
