### ISSUE TITLE
黑边的问题总结

### ISSUE THREAD

**Issue by lipangit** [lipangit/JiaoZiVideoPlayer#1204]
如果视频的高宽比例和屏幕的高宽比例不一致，肯定会有黑边的。

如果非要去掉黑边，一种方法是指定视频的的比例和容器的比例一致，比如16:9 或 4:3。另一种方法复写onVideoSizeChanged函数，放大textureView的大小

**Comment by keaitao0321** [comment]
@Override
    public void onVideoSizeChanged() {
        //super.onVideoSizeChanged();
        if (JCMediaManager.textureView != null) {
            JCMediaManager.textureView.setVideoSize(new Point(textureViewContainer.getWidth(),textureViewContainer.getHeight()));//视频大小与控件大小一致
        }
    }

我是这样解决的,好像没什么问题.

**Comment by lipangit** [comment]
上面的是通过修改容器的高宽
也可以修改容器内的视频的高宽，参考demo的ActivityApiRotationVideoSize，可以旋转和铺满

**Comment by sunxlfred** [comment]
但是如果设置了 
```
JZVideoPlayer.setVideoImageDisplayType(JZVideoPlayer.VIDEO_IMAGE_DISPLAY_TYPE_FILL_SCROP);
```
或者 VIDEO_IMAGE_DISPLAY_TYPE_FILL_PARENT

在点击全屏后反而会充满整个屏幕, 
所以是否有接口监听到全屏模式的开启？可以在全屏下设置为VIDEO_IMAGE_DISPLAY_TYPE_ORIGINAL

**Comment by lipangit** [comment]
JZVideoPlayer.setVideoImageDisplayType这个函数随时设置随时生效

你可以继承JZVideoPlayerStandard，复写onClick函数，监听全屏的点击。参考demo的MYJZVideoPlayerStandard。

**Comment by yixiu30** [comment]
@override
public void onVideoSizeChanged() {
//super.onVideoSizeChanged();
if (JCMediaManager.textureView != null) {
JCMediaManager.textureView.setVideoSize(new Point(textureViewContainer.getWidth(),textureViewContainer.getHeight()));//视频大小与控件大小一致
}
}
我也是调用了这个没有用诶

**Comment by lipangit** [comment]
@yixiu30 demo中生效吗
