### ISSUE TITLE
播放的时候只有声音没有图像

### ISSUE THREAD

**Issue by lipangit** [lipangit/JiaoZiVideoPlayer#1205]
1. 检查硬件加速，硬件加速必须开启，否则TextureView不工作，导致黑屏
2. 断点JCMediaPlayer.java 110行附近instance().mediaPlayer.setSurface(holder);是否运行，如果setSurface失败或者没走到也会导致黑屏(如果库没改动这里不容易出问题)
3. 播放器不支持的图像编码，MP4视频格式中，图像有不同的图像编码，声音也有不同的编码

另外可以新建一个项目，用最简单的android.media.MediaPlayer和TextureView测试

**Comment by yangtuhua** [comment]
@lipangit 请问这个问题解决了吗？我也遇到了同样的问题，后端给到的音频链接是mp4格式的，在播放时，音频已经在播了，然后界面还是处于加载中，未执行onStatePrepared方法。

**Comment by lipangit** [comment]
把后缀改成mp3试试



---原始邮件---
发件人: "yangtuhua"<notifications@github.com&gt;
发送时间: 2020年4月2日(周四) 上午10:35
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 播放的时候只有声音没有图像 (#1205)




 
@lipangit 请问这个问题解决了吗？我也遇到了同样的问题，后端给到的音频链接是mp4格式的，在播放时，音频已经在播了，然后界面还是处于加载中，未执行onStatePrepared方法。
