### ISSUE TITLE
视频缓存的问题

### ISSUE THREAD

**Issue by lipangit** [lipangit/JiaoZiVideoPlayer#1206]
就用android.media.MediaPlayer的缓存，他是什么样，咱们就用什么，测试demo中可以永久缓存视频，经测试16M以下的视频小视频可以永久缓存，重启手机之后还有

视频缓存框架的问题，一直在关注，但是没找到效果好的，最复杂的可以说是断点离线缓存，网一断，视频拖动进度到非缓存的地方，效果非常不好，如果有好的框架，即刻考虑集成之

**Comment by Android-AwesomeRoy** [comment]
能否提供可配置的磁盘缓存大小, 16M的话确实不够用. 这个数值由 Coder 自己控制的话, 几百M内应该不会出现很严重的 seekbar 的问题吧.

**Comment by lipangit** [comment]
应该改变不了，没想找到相关api，android.media.MediaPlayer，你可以研究研究 然后告诉我

**Comment by lll-01** [comment]
可以试试这个缓存
https://github.com/danikula/AndroidVideoCache

**Comment by lipangit** [comment]
这个框架可以自行使用，demo并不推荐
