### ISSUE TITLE
jiaoZiVideoPlayer在Manifest里面设置了android:hardwareAccelerated="false"就播放不了视屏了

### ISSUE THREAD

**Issue by luckbing** [lipangit/JiaoZiVideoPlayer#1210]
jiaoZiVideoPlayer在Manifest里面设置了android:hardwareAccelerated="false"就播放不了视屏了。demo也是一样的，不知道是什么原因，楼主大神有时间看看么？不知道原因心里总是有个疙瘩😄，所以现在要用的最好开启硬件加速，即设置application的（android:hardwareAccelerated="trues"）。在楼主没有解决之前希望对遇到同样问题的一个帮助（毕竟我找了好久才找到这个原因）

**Comment by lipangit** [comment]
textureView在硬件加速关闭的情况下无法工作，必须开启没得商量，默认情况是开启的，不需要特殊设置

腼腆青年：发issue又有表情又有括号

**Comment by luckbing** [comment]
好的谢谢，学艺不经嘿嘿，总是踩很多坑，哎。。。
