### ISSUE TITLE
Facing issue on Media Player error

### ISSUE THREAD

**Issue by ABBIGADDU** [lipangit/JiaoZiVideoPlayer#1212]
I am getting this issue and not playing video..!
E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
 E/MediaPlayer: error (-38, 0)
 E/MediaPlayer: Error (-38,0)
 E/JieCaoVideoPlayer: onError 260 - -110 [1151961832] 
E/JieCaoVideoPlayer: onError -38 - 0 [1151961832] 
 E/JieCaoVideoPlayer: onError -38 - 0 [1151961832]

**Comment by lipangit** [comment]
Does it crash?

getDuration when mediaPlayer has released will show this error

IF not often happen you can ignore this

**Comment by ABBIGADDU** [comment]
ya i can ignore but client not accept bcz, it's not start playing...!

**Comment by lipangit** [comment]
Did you solved the problem?

**Comment by ABBIGADDU** [comment]
No still I am facing that issue

**Comment by lipangit** [comment]
I think this is a video format, if you can not modify the video format, you can try a new version of the code switch MediaPlayer
