### ISSUE TITLE
如何获取播放到第三分钟时刻

### ISSUE THREAD

**Issue by wh121** [lipangit/JiaoZiVideoPlayer#1213]
视频试看三分钟功能，打算使用定时器，可是当拖拽播放进度条时就不行了。自动播放下一个视频功能，为什么是当前视频播放完成，要点击一下“重播”按钮才能播放下一个视频。我应该怎么修改状态 或者是直接切换到播放下一个视频。我应该怎么做？

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard 复写setProgressAndText函数 可监听到播放时间

复写onAutoComplete可得到播放完毕的回调，在这个函数里调用onStatePreparingChangingUrl函数播放下一个url，和修改清晰度一个道理

**Comment by wdza** [comment]
setProgressAndText中的duration，为啥都是一个值？我的需求是视频播放，到20s暂停，让其付费，弹出窗口，如何实现啊？

**Comment by lipangit** [comment]
duration 是总时长

检测另一个变量是当前播放的时长(名字忘了)，如果>20分钟就执行自己的逻辑

**Comment by zhupengxiang** [comment]
@wh121 @wdza  这个功能实现了么
