### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1214]
JCVideoPlayerStandard的：
    public void updateStartImage() {

        if (currentState == CURRENT_STATE_PLAYING) {
            startButton.setImageResource(R.drawable.jc_click_pause_selector);
            retryTextView.setVisibility(INVISIBLE);
        } else if (currentState == CURRENT_STATE_ERROR) {
            startButton.setImageResource(R.drawable.jc_click_error_selector);
            retryTextView.setVisibility(INVISIBLE);
        } else if (currentState == CURRENT_STATE_AUTO_COMPLETE) {
            startButton.setImageResource(R.drawable.jc_click_replay_selector);
            retryTextView.setVisibility(VISIBLE);
        } else {
            startButton.setImageResource(R.drawable.jc_click_play_selector);
            retryTextView.setVisibility(INVISIBLE);
        }

    }

     第一个 startButton.setImageResource(R.drawable.jc_click_pause_selector);这行会报内存溢出，可能的原因是什么？2G内存，5.0的手机，这不能上传图片，不然给你来张log图

**Comment by lipangit** [comment]
这设置按钮图片 怎么会内存溢出啊
