### ISSUE TITLE
The video which is taken from Android phones are working but others videos which are taken from IOS doesn't work

### ISSUE THREAD

**Issue by atakankersit** [lipangit/JiaoZiVideoPlayer#1215]
I have too many videos, some of them were taken from iOS, others were taken from Android. All of these videos' extension is mp4. These videos was uploaded to amazon. When I'm trying to play video which was taken from IOS not working. What is different of these videos? 

Thank you for help

This video taken from IOS:
https://s3.eu-central-1.amazonaws.com/viatori-s3/Content/Timeline/144/1CC31EEE-D5E8-4505-B698-00441854E5C7-2046-0000019BB3745187.mp4

This video taken from Android:
https://s3.eu-central-1.amazonaws.com/viatori-s3/Content/Timeline/19213/VID_20170907_111535.mp4

**Comment by lipangit** [comment]
![screenshot_2017-09-07-17-32-08-470_cn jzvd demo](https://user-images.githubusercontent.com/2038071/30156540-8a1e066e-93f2-11e7-9b93-16f417ca4435.png)

I can play by hongmi note4

**Comment by atakankersit** [comment]
Can you insert mine url to videoUrls array in VideoConstant.java.
After that please try for recyclerView. You will see it doesn't work or I did something wrong.

Like This:

`  public static String[][] videoUrls =
            {
                    {
                            "https://s3.eu-central-1.amazonaws.com/viatori-s3/Content/Timeline/19213/VID_20170906_161958.mp4",
                            "http://jzvd.nathen.cn/35b3dc97fbc240219961bd1fccc6400b/8d9b76ab5a584bce84a8afce012b72d3-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/df6096e7878541cbbea3f7298683fbed/ef76450342914427beafe9368a4e0397-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/384d341e000145fb82295bdc54ecef88/103eab5afca34baebc970378dd484942-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/f55530ba8a59403da0621cbf4faef15e/adae4f2e3ecf4ea780beb057e7bce84c-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/6340efd1962946ad80eeffd19b3be89c/65b499c0f16e4dd8900497e51ffa0949-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/f07fa9fddd1e45a6ae1570c7fe7967c1/c6db82685b894e25b523b1cb28d79f2e-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/d2e969f2ec734520b46ab0965d2b68bd/f124edfef6c24be8b1a7b7f996ccc5e0-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/4f965ad507ef4194a60a943a34cfe147/32af151ea132471f92c9ced2cff785ea-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
                    },
                    {
                            "http://jzvd.nathen.cn/623f75c3beea4b1781ea37940e70bbe4/b9cee3fd1a09487ca99ef789cdc41312-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/d8c137ceba9849f8b2f454a55a96266f/910c8381ff894905b5bc272f8194382a-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/b8a589e5f12c45fdad96674d08affd31/f1d7229f553f414283033af3e292c6c9-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/8abcdf98ec6a418b945a70fe9dd6fc7f/5cb36416a23a4da8b15d3eaa5e19a1e6-5287d2089db37e62345123a1be272f8b.mp4"
                    },
                    {
                            "http://jzvd.nathen.cn/1b61da23555d4ce28c805ea303711aa5/7a33ac2af276441bb4b9838f32d8d710-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/d525f756aabf4b0588c2152fb94e07f5/d9f59bef829a472a9ca066620d9b871a-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/6e2fdec45dfa44a6802e95f8e4bc3280/a6a5273ac4244333923991be0583ffc7-5287d2089db37e62345123a1be272f8b.mp4",
                            "http://jzvd.nathen.cn/22b4de0e2b1245959c5baa77fe0bf14e/896a137559084b7eb879f5441faff20d-5287d2089db37e62345123a1be272f8b.mp4"
                    }
            };

    public static String[][] videoThumbs =
            {
                    {
                            "https://s3.eu-central-1.amazonaws.com/viatori-s3/Content/Timeline/19213/thumb_4e19e94e-34e9-4340-8443-53c030e45211.png",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/f2dbd12e-b1cb-4daf-aff1-8c6be2f64d1a.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/ccd86ca1-66c7-4331-9450-a3b7f765424a.png",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/2adde364-9be1-4864-b4b9-0b0bcc81ef2e.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/2a877211-4b68-4e3a-87be-6d2730faef27.png",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/aaeb5da9-ac50-4712-a28d-863fe40f1fc6.png",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/e565f9cc-eedc-45f0-99f8-5b0fa3aed567%281%29.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/3430ec64-e6a7-4d8e-b044-9d408e075b7c.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/2204a578-609b-440e-8af7-a0ee17ff3aee.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/1bb2ebbe-140d-4e2e-abd2-9e7e564f71ac.png"
                    },
                    {
                            "http://jzvd-pic.nathen.cn/jzvd-pic/f18ee453-6aec-40a5-a046-3203111dd303.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/00f5a243-1e9f-426c-94f4-888971987edb.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/7df34ee9-1e4f-48f4-8acd-748c52368298.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/ef46e139-e378-4298-8441-144888294f1f.png"
                    },
                    {
                            "http://jzvd-pic.nathen.cn/jzvd-pic/0e58101d-5b47-4100-8fb3-0cce057fd622.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/d6d3a520-b183-4867-8746-5b6aba6c1724.png",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/caa3dade-5744-486d-a1b7-9780aebb9eb5.jpg",
                            "http://jzvd-pic.nathen.cn/jzvd-pic/2c3e62bb-6a32-4fb0-a1d5-d1260ad436a4.png"
                    }
            };`

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/30161598-d1c1ed94-9403-11e7-89fc-03fc3bb4dbd9.png)

I cannot request that url in china.

I think you should just test android.media.MediaPlayer and TextureView can play that video url

**Comment by atakankersit** [comment]
This is my log file. Can it help you to figure it out my problem ?
Thank you for everything.

<img width="781" alt="screen shot 2017-09-07 at 15 13 18" src="https://user-images.githubusercontent.com/11357510/30162867-3895c0c4-93df-11e7-91a2-b6c958f62921.png">

**Comment by lipangit** [comment]
timeout

**Comment by atakankersit** [comment]
Thank You :)
