### ISSUE TITLE
内存泄露 

### ISSUE THREAD

**Issue by wufannet** [lipangit/JiaoZiVideoPlayer#1216]
![_20170907171638](https://user-images.githubusercontent.com/13639215/30155816-67ee7d3c-93f0-11e7-9909-5d348f3a5fef.png)

**Comment by lipangit** [comment]
哥们有时间你研究研究

**Comment by wufannet** [comment]
源代码没怎么看, 是使用不正确吗?

**Comment by lipangit** [comment]
不是
