### ISSUE TITLE
播放时点击其他item，会自动横屏，原因暂时未知突然出现，退出后再进入又没有这个现象了

### ISSUE THREAD

**Issue by yaoxin2017** [lipangit/JiaoZiVideoPlayer#1218]
在listview或recycleView中播放时，点击其他item，此时发生自动横屏，原因暂时未知突然出现，退出后再进入又没有这个现象了

不知道怎么重现这个问题，先反馈再跟进继续提交问题

**Comment by yaoxin2017** [comment]
好像发现了原因，我运行的是github上面的demo，点击 about api 按钮，进入后再点击 orientation 按钮后退出再去listView或者recycleView播放视频就会出现我上面说的问题。不明白为什么在那边设置会影响其他的播放

**Comment by yaoxin2017** [comment]
还有内存泄漏问题一会就有好几兆！

**Comment by lipangit** [comment]
内存泄漏的问题你可以帮忙研究研究
