### ISSUE TITLE
onStatePreparingChangingUrl

### ISSUE THREAD

**Issue by wdza** [lipangit/JiaoZiVideoPlayer#1219]
onStatePreparingChangingUrl，我传入新地址的时候，为啥进度条不是从第一帧开始，我设置的JCMediaManager.instance().mediaPlayer.seekTo(0);不起作用吗？还是有别的方式，找到一天了。

**Comment by lipangit** [comment]
可以模拟用户拖动进度条，把进度条拖到0

**Comment by wdza** [comment]
我感觉onStatePreparingChangingUrl方法少什么东西？播放新地址的时候下面的进度条也没了？而且停在10s那了？

**Comment by lipangit** [comment]
少什么，研究一下，帮忙找找原因。
