### ISSUE TITLE
三星s7 手机播放视频会出现JieCaoVideoPlayer: onError 1 - -2147483648 [221797181] 

### ISSUE THREAD

**Issue by cat1024** [lipangit/JiaoZiVideoPlayer#1221]

**Comment by cat1024** [comment]
视频地址：https://image-public.touhaozhubo.com/video201709081440375260859956629.mp4

**Comment by lipangit** [comment]
咱们就是用android.media.MediaPlayer播放视频，三星的问题不清楚

**Comment by fetchingly** [comment]
小米手机播放页出现同样的问题

**Comment by suweya** [comment]
就是和VideoView是类似的吧，受系统版本和手机厂商的影响吧， @lipangit

**Comment by lipangit** [comment]
对，建议用最常见的视频格式，别耍花样 @suweya
