### ISSUE TITLE
我想请问一下,,我可以直接播放本地视频和用本地的图片作为封面吗?

### ISSUE THREAD

**Issue by chenmingdu** [lipangit/JiaoZiVideoPlayer#1222]

**Comment by lipangit** [comment]
both ok

**Comment by RadinLy** [comment]
我想知道，如果在同一个视频控件中切换视频，能做到不闪屏？ 或者一个视频播完，切换到下一个视频的时候，有一个默认图，使视频无缝衔接的播放

**Comment by benniaobuguai** [comment]
播放assets里面的视频，不支持

**Comment by lipangit** [comment]
@benniaobuguai 是的  android.media.MediaPlayer是支持assert的，但是咱们这个库变量没设置好 传不进去

**Comment by benniaobuguai** [comment]
@lipangit 现在主要问题，是JZMediaManager里面缺少一个Context去取AssetManager，下面是我测试时，简单修改的代码

`
@Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what) {
                case HANDLER_PREPARE:
                    try {
                        currentVideoWidth = 0;
                        currentVideoHeight = 0;
                        mediaPlayer.release();
                        mediaPlayer = new MediaPlayer();
                        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
                        mediaPlayer.setLooping(CURRENT_PLING_LOOP);
                        mediaPlayer.setOnPreparedListener(JZMediaManager.this);
                        mediaPlayer.setOnCompletionListener(JZMediaManager.this);
                        mediaPlayer.setOnBufferingUpdateListener(JZMediaManager.this);
                        mediaPlayer.setScreenOnWhilePlaying(true);
                        mediaPlayer.setOnSeekCompleteListener(JZMediaManager.this);
                        mediaPlayer.setOnErrorListener(JZMediaManager.this);
                        mediaPlayer.setOnInfoListener(JZMediaManager.this);
                        mediaPlayer.setOnVideoSizeChangedListener(JZMediaManager.this);

                        Class<MediaPlayer> clazz = MediaPlayer.class;
                        //Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
                        //method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);

                        if (CURRENT_PLAYING_URL.startsWith("file:///android_asset/")) {
//                            Method method = clazz.getDeclaredMethod("setDataSource", FileDescriptor.class, Long.class, Long.class);
//
//                            AssetManager assetManager = JZMediaManager.this.application.getAssets();
//                            AssetFileDescriptor afd = assetManager.openFd("video/1.mp4");
//
//
//                            method.invoke(mediaPlayer, afd, afd.getStartOffset(), afd.getLength());

                            AssetManager assetManager = JZMediaManager.this.application.getAssets();
                            //AssetFileDescriptor afd = assetManager.openFd("video/1.mp4");
                            AssetFileDescriptor afd = assetManager.openFd(CURRENT_PLAYING_URL.replace("file:///android_asset/", ""));
                            mediaPlayer.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
                        } else {
                            Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
                            method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);
                        }


                        mediaPlayer.prepareAsync();
                        mediaPlayer.setSurface(new Surface(savedSurfaceTexture));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                case HANDLER_RELEASE:
                    mediaPlayer.release();
                    break;
            }
        }
    }
`

**Comment by benniaobuguai** [comment]
@lipangit 现在主要问题，是JZMediaManager里面缺少一个Context去取AssetManager，下面是我测试时，简单修改的代码

``` java
@override
public void handleMessage(Message msg) {
super.handleMessage(msg);
switch (msg.what) {
case HANDLER_PREPARE:
try {
currentVideoWidth = 0;
currentVideoHeight = 0;
mediaPlayer.release();
mediaPlayer = new MediaPlayer();
mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
mediaPlayer.setLooping(CURRENT_PLING_LOOP);
mediaPlayer.setOnPreparedListener(JZMediaManager.this);
mediaPlayer.setOnCompletionListener(JZMediaManager.this);
mediaPlayer.setOnBufferingUpdateListener(JZMediaManager.this);
mediaPlayer.setScreenOnWhilePlaying(true);
mediaPlayer.setOnSeekCompleteListener(JZMediaManager.this);
mediaPlayer.setOnErrorListener(JZMediaManager.this);
mediaPlayer.setOnInfoListener(JZMediaManager.this);
mediaPlayer.setOnVideoSizeChangedListener(JZMediaManager.this);

                    Class<MediaPlayer> clazz = MediaPlayer.class;
                    //Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
                    //method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);

                    if (CURRENT_PLAYING_URL.startsWith("file:///android_asset/")) {
// Method method = clazz.getDeclaredMethod("setDataSource", FileDescriptor.class, Long.class, Long.class);
//
// AssetManager assetManager = JZMediaManager.this.application.getAssets();
// AssetFileDescriptor afd = assetManager.openFd("video/1.mp4");
//
//
// method.invoke(mediaPlayer, afd, afd.getStartOffset(), afd.getLength());

                        AssetManager assetManager = JZMediaManager.this.application.getAssets();
                        //AssetFileDescriptor afd = assetManager.openFd("video/1.mp4");
                        AssetFileDescriptor afd = assetManager.openFd(CURRENT_PLAYING_URL.replace("file:///android_asset/", ""));
                        mediaPlayer.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
                    } else {
                        Method method = clazz.getDeclaredMethod("setDataSource", String.class, Map.class);
                        method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);
                    }


                    mediaPlayer.prepareAsync();
                    mediaPlayer.setSurface(new Surface(savedSurfaceTexture));
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case HANDLER_RELEASE:
                mediaPlayer.release();
                break;
        }
    }
}
```

**Comment by lipangit** [comment]
是的，这块还需要修改

**Comment by lipangit** [comment]
mediaPlayer传参问题已经解决，参考自定义播放器
