### ISSUE TITLE
webviewActivity直接跳转全屏播放有问题

### ISSUE THREAD

**Issue by Cyrus-github** [lipangit/JiaoZiVideoPlayer#1223]
我按照demo里PlayDirectlyActivity 里的配置在我自己的app里，但是却没有效果。

我是和js交互，js给我视屏地址我播放，然后我的界面是webview 配合原生控件，webview我用的x5 tbs 浏览器内核，不知道是否有什么影响

还有这种直接跳转全屏播放有什么条件和限制吗？

**Comment by lipangit** [comment]
没限制，在网页js的回调里启动全屏，和activity里启动全屏一样

**Comment by Cyrus-github** [comment]
我这边测试了下，我在有webview的activity的layout里面加了一个Button,这个button就可以正常直接全屏播放，但是webview的回调里调用直接全屏播放的代码还是无效，原因是啥？

**Comment by Cyrus-github** [comment]
问题解决了 ，关键点在于，直接开启全屏播放视屏的线程问题，全屏播放的执行逻辑是要在Ui主线程的，所以JS回调Android这边的接口里直接使用 
JCVideoPlayerStandard.startFullscreen(WebActivity.this, JCVideoPlayerStandard.class,
                                "http://video.jiecao.fm/11/14/xin/%E5%90%B8%E6%AF%92.mp4", "xxx");
是没有作用的，我注意到demo里 WebViewActivity 在回调接口里有使用
   runOnUiThread(new Runnable() {}）；所以加上这个，问题解决

**Comment by lipangit** [comment]
好
