### ISSUE TITLE
切换视频，怎么做才能看起来切换的流畅，不闪屏

### ISSUE THREAD

**Issue by RadinLy** [lipangit/JiaoZiVideoPlayer#1224]
我想知道，如果在同一个视频控件中切换视频，能做到不闪屏？ 或者一个视频播完，切换到下一个视频的时候，有一个默认图，使视频无缝衔接的播放

**Comment by lipangit** [comment]
参照demo的切换清晰度，切换清晰度的本质就是切换视频

你换一下视频地址，测试一下 是否符合你的要求

**Comment by RadinLy** [comment]
现在让设计出了一个把几个视频合到一起，然后控制播放进度来切换

**Comment by pokerfaceCmy** [comment]
大神，切换清晰度的代码我只找到了这一段
  `LinkedHashMap map = new LinkedHashMap();
        String proxyUrl = ApplicationDemo.getProxy(this).getProxyUrl(VideoConstant.videoUrls[0][9]);
        map.put("高清", proxyUrl);
        map.put("标清", VideoConstant.videoUrls[0][6]);
        map.put("普清", VideoConstant.videoUrlList[0]);`
但是这只是将连接添加到JZDataSource中，切换的时候该怎么做呢？

**Comment by lipangit** [comment]
demo apiActivity有切换清晰度的例子，切换清晰度本质上就是播放中切换url

**Comment by pokerfaceCmy** [comment]
> demo apiActivity有切换清晰度的例子，切换清晰度本质上就是播放中切换url

ActivityApi中切换清晰度也会闪屏。。。我视频URL是保存在本地的，应该不会有需要加载的情况才对

**Comment by lipangit** [comment]
闪屏是什么现象，能录个小视频看看吗，你觉得demo中切换清晰度算闪屏吗

**Comment by pokerfaceCmy** [comment]
> 闪屏是什么现象，能录个小视频看看吗，你觉得demo中切换清晰度算闪屏吗

稍等我录个视频

**Comment by pokerfaceCmy** [comment]
> 闪屏是什么现象，能录个小视频看看吗，你觉得demo中切换清晰度算闪屏吗

https://github.com/pokerfaceCmy/leetcode/blob/master/device-2019-06-26-183715.mp4

代码如下：
https://github.com/pokerfaceCmy/leetcode/blob/master/1561545755(1).jpg?raw=true

**Comment by lipangit** [comment]
5秒 7秒 9秒 10秒分别闪了一次，其中5秒的闪屏更明显一些，他们又什么区别吗

**Comment by pokerfaceCmy** [comment]
> 5秒 7秒 9秒 10秒分别闪了一次，其中5秒的闪屏更明显一些，他们又什么区别吗

怎么才能不闪呢。。。

**Comment by lipangit** [comment]
两个视频衔接的时候好像很难做到不闪一下。

这个问题研究一下两个视频衔接的时候，exoplayer好像可以，用同一个mediaplayer队列播放视频地址。

我看过exoplayer的介绍。

**Comment by pokerfaceCmy** [comment]
> 两个视频衔接的时候好像很难做到不闪一下。
> 
> 这个问题研究一下两个视频衔接的时候，exoplayer好像可以，用同一个mediaplayer队列播放视频地址。
> 
> 我看过exoplayer的介绍。

好的  我去研究一下
