### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by yulinwoniu666** [lipangit/JiaoZiVideoPlayer#1225]
通过buildle.gradle编译不了啊 Demo能跑起来 什么问题啊 一直是Error:(22, 13) Failed to resolve: cn.jcvd:jiaozivideoplayer:6.0.0
<a href="openFile:E:/demo/JZvideoplayDmeo/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by lipangit** [comment]
是不是把仓库改了

用android studio新建个项目，然后加入这个cn.jcvd:jiaozivideoplayer:6.0.0，亲测可以

**Comment by yulinwoniu666** [comment]
是真的不行 AS2.3.3Gradle3.3在两台电脑上都试过 都是新建一个项目再依赖 都是同样的问题 没改仓库 用的默认的Jcenter

**Comment by GraysonGao** [comment]
我也是, 之前用5.8.1版本可以, 换了6.0.0就不行了, 难道和本地的gradle缓存有关?

**Comment by lipangit** [comment]
cn.jzvd:jiaozivideoplayer:6.0.0   写错了

**Comment by yulinwoniu666** [comment]
哈哈 大神也会犯这种低级错误啊

**Comment by lipangit** [comment]
低调

**Comment by yulinwoniu666** [comment]
哈哈 我懂我懂 还有个问题请教一下哦 为什么ijkPlayer这个库不直接编译出SO库给大家用呢 而是提供的C代码让大家去编译了才能用

**Comment by lipangit** [comment]
问错地方了 兄弟
