### ISSUE TITLE
6.0.0版不支持api22和以下版本

### ISSUE THREAD

**Issue by gsnhear** [lipangit/JiaoZiVideoPlayer#1227]
虚拟机测试
api22-21 :出现视频时间不对，不播放视频，只播放音频。播放操作界面无法调出的情况
api19-16:出现加载时直接显示！号提示，无法播放。

**Comment by yulinwoniu666** [comment]
兄弟你能依赖成功吗 我的老是依赖不上

**Comment by gsnhear** [comment]
可以依赖成功，你是什么错误

**Comment by yulinwoniu666** [comment]
一直是Error:(22, 13) Failed to resolve: cn.jcvd:jiaozivideoplayer:6.0.0
Show in File 这个库看着挺好用的 前面集成那个GSYvideoplayer也还可以 不过没这个星星多也有2K多 但是这个编译不了 不知道什么鬼 我Gradle用的3.3AS2.3.3 加上MAVEN仓库也不行

**Comment by yulinwoniu666** [comment]
回去用家里的电脑试试 你是通过Buildle依赖的还是导入的jar

**Comment by gsnhear** [comment]
我是直接 build 里compile的。

**Comment by lipangit** [comment]
导入不成功的主要原因是build环境的问题，库保持着google发布的stable版本

**Comment by yulinwoniu666** [comment]
其他的项目我能鞥呢导入成功啊 很少碰到导入不了的情况 我的编译环境没问题啊 导入其他的都没问题的

**Comment by yulinwoniu666** [comment]
Error:(22, 13) Failed to resolve: cn.jcvd:jiaozivideoplayer:6.0.0
Show in File

**Comment by lipangit** [comment]
@yulinwoniu666 l新建个项目 ，然后引入cn.jcvd:jiaozivideoplayer:6.0.0 试试

**Comment by yulinwoniu666** [comment]
还是不行，我家里的电脑也不行 只有这个库依赖不上 其他百分之八十的项目都能依赖上，我是AS2.3.3Gradle3.3的编译环境 ，你的环境是怎样的

**Comment by lipangit** [comment]
拼错了  cn.jzvd:jiaozivideoplayer:6.0.0
