### ISSUE TITLE
5.8.1全屏后底部seekbar和progressbar进度不动

### ISSUE THREAD

**Issue by liaoxuanwei** [lipangit/JiaoZiVideoPlayer#1228]
5.8.1全屏后底部seekbar和progressbar进度不动，点击屏幕layout_bottom消失后，再点击seekbar和progress才会随播放进度儿变化
另外在依赖 compile 'cn.jcvd:jiaozivideoplayer:6.0.0'时报could found cn.jcvd:jiaozivideoplayer:6.0.0
改成 cn.jzvd:jiaozivideoplayer:6.0.0才可以

**Comment by lipangit** [comment]
这是个bug，进度条更新不及时

多谢提醒  怪我了

**Comment by ningwy** [comment]
请问这个问题修复了吗~

**Comment by lipangit** [comment]
已经修复
