### ISSUE TITLE
封装是否太过了？

### ISSUE THREAD

**Issue by benniaobuguai** [lipangit/JiaoZiVideoPlayer#1229]
我只需要一个单纯的播放视频组件，控件里面怎么还要关注ActionBar, Toolbar的显示隐藏，这应该属于业务层级的事情吧？

**Comment by lipangit** [comment]
这个库的目的是5个步骤就能得到和头条一样的播放效果，如果你的actionbar和toolbar与头条的效果不一样是需要关注一下的

**Comment by benniaobuguai** [comment]
哦哦，理解了。如果是一个通用的组件库，个人建议还是适当改造，在业务层，再封装实现头条一样的效果。对其他开发者使用也理友好。

**Comment by lipangit** [comment]
actionbar和toolbar这个develop分支已经修改

**Comment by benniaobuguai** [comment]
棒棒哒
