### ISSUE TITLE
播放进度的保存

### ISSUE THREAD

**Issue by lipangit** [lipangit/JiaoZiVideoPlayer#1230]
![image](https://user-images.githubusercontent.com/2038071/30311240-e672792c-97c6-11e7-8e77-8998fab27385.png)

true保存播放进度，false不保存播放进度

**Comment by tsubasa-kun** [comment]
如果是用依赖的方式，这个状态好像改不了

**Comment by lipangit** [comment]
截图看看你是怎么用的

**Comment by a342216937** [comment]
这状态你是改不了 但是你可以播放之前 把SharedPreferences删了  这个SP:
SharedPreferences spn = context.getSharedPreferences("JZVD_PROGRESS",
                Context.MODE_PRIVATE);
