### ISSUE TITLE
[Core Media Video]MP4格式视频播放不了

### ISSUE THREAD

**Issue by fetchingly** [lipangit/JiaoZiVideoPlayer#1231]
在视频文件信息：
音频: AAC 44100Hz 立体声 96Kbps [Core Media Audio (eng)]
视频: MPEG4 Video (H264) 202x360 31.08fps [Core Media Video]
的MP4格式视频不能播放；

音频: AAC 44100Hz 立体声 125Kbps [Core Media Audio]
视频: MPEG4 Video (H264) 480x272 30.00fps [Core Media Video]
的MP4格式视频可以播放

**Comment by lipangit** [comment]
超出老臣解决范围，请用能播放的格式
