### ISSUE TITLE
调用JZVideoPlayer.releaseAllVideos();下次再点击播放后显示的时间和调用前的不同

### ISSUE THREAD

**Issue by ahaSweather** [lipangit/JiaoZiVideoPlayer#1233]
参照demo中的用法在viewPager切换时调用JZVideoPlayer.releaseAllVideos();，可当我再次点击这个视频时播放时，显示的时间大概比我调用切换前的时间快了将近10秒，我看demo里也是这种情况，想问下有什么办法解决吗

**Comment by lipangit** [comment]
这是保存播放进度，
![image](https://user-images.githubusercontent.com/2038071/30363979-db6d078a-9894-11e7-91b3-2b6843c8b85a.png)

设置成false，不保存播放进度
