### ISSUE TITLE
播放器播放错误 

### ISSUE THREAD

**Issue by ERICLIKESMILE** [lipangit/JiaoZiVideoPlayer#1236]
JieCaoVideoPlayer : onError 0 - 0 [956295007] 
这个错误是什么意思啊

**Comment by lipangit** [comment]
什么情况下发生的  能复现吗

**Comment by ERICLIKESMILE** [comment]
我是在Android TV中用到的.
当我用遥控器按下播放视频的时候 会出现播放失败的图标(jc_error-normal)
我抓取数据的时候 是有url的 然后再次点击播放 一直两次 就成功播放了
在我的log中显示的这个错误信息

**Comment by lipangit** [comment]
没见过0-0的错误，改库了吗

新建个项目用android.media.MediaPlayer 和TextureView在TV上试试
