### ISSUE TITLE
部分MP4视频不能播放例如：http://ot7pni7s5.bkt.clouddn.com/b6rp8i3np4rg04uki2eg0

### ISSUE THREAD

**Issue by fetchingly** [lipangit/JiaoZiVideoPlayer#1237]

**Comment by lipangit** [comment]
这个在浏览器打开识别成了文件，可能http请求头的问题

请统一成能播放的方式

**Comment by fetchingly** [comment]
文件下载下来，在手机中是可以用手机的视频播放器播放的，而且一些其它第三方视频播放器也可以播放

**Comment by lipangit** [comment]
咱们这用android.media.MediaPlayer播放视频  对http头可能有要求，不能让人家满足你的链接，你的链接应该满足android.media.MediaPlayer

**Comment by saurylip** [comment]
同遇到了这个问题,公司用的是七牛云的存储,视频是拿手机录制的,链接: http://oqwr6xnsg.bkt.clouddn.com/1534bfa4-68bd-4fc9-a0ac-022ed47d19c8
请问具体该怎么统一?

**Comment by lipangit** [comment]
亲测能播就是有点卡  @saurylip

**Comment by saurylip** [comment]
我这边版本还在5.8.1 卡在某一帧不动了就  您用的是最新版本是吗?

**Comment by lipangit** [comment]
6.0.1 可以正常播放， 我觉得这服务器好像有问题，卡住了应该是网络卡主了

**Comment by saurylip** [comment]
ios那边没问题 其他视频也没问题,我升级到6.0.1试试吧,麻烦啦

**Comment by saurylip** [comment]
经过测试.只有三星(s6)手机存在这个问题,oppo vivo 华为都正常播放

**Comment by lipangit** [comment]
怎么样解决了吗
