### ISSUE TITLE
how to disable message while playing video through mobile data ?

### ISSUE THREAD

**Issue by ShantiRanjanDas** [lipangit/JiaoZiVideoPlayer#1240]
Currently when I want to play a video from mobile data is shows a message "You are currently using the mobile network, the player will continue to consume traffic." Then two buttons below it.

Please specify how to disable this message. Or change it to as I want

**Comment by lipangit** [comment]
extends JZVideoPlayerStandard 
Override
showWifiDialog(){
    //super.showWifiDialog();
}

**Comment by ShantiRanjanDas** [comment]
Is there any other way other then extending

**Comment by DevObs1** [comment]
Hello lipangit,
Is it possible to add a function to disable this dialog?
The class I use already uses the extends, you can not add the one you mentioned.

Thanks in advance for your responsiveness.

**Comment by lipangit** [comment]
@ShantiRanjanDas Must extending before change anything

**Comment by lipangit** [comment]
//super.showWifiDialog();

annotation super function, will not show the dialog

**Comment by pratikbutani** [comment]
Anyone got the solution?

**Comment by pratikbutani** [comment]
I found the solution after extracting and understanding whole code of library.

You just have to make variable **WIFI_TIP_DIALOG_SHOWED=_TRUE_**, It will never display dialog of WiFi settings.

public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        // Make it TRUE.... 
        JZVideoPlayer.WIFI_TIP_DIALOG_SHOWED = true;
    }
}

**Comment by lipangit** [comment]
@pratikbutani  yes you are right

**Comment by pratikbutani** [comment]
Thank you. Keep Supporting... You can close this issue now.

**Comment by pratikbutani** [comment]
> // Make it TRUE.... 
>         JZVideoPlayer.WIFI_TIP_DIALOG_SHOWED = true;

As per updated new version, you can use as below:

                ```
                // Make it TRUE.... 
		JzvdStd.WIFI_TIP_DIALOG_SHOWED = true;
```

**Comment by lipangit** [comment]
Yes thank you @pratikbutani
