### ISSUE TITLE
全屏界面单独使用JZVideoPlayerStandard，点击全屏播放，再取消全屏播放出现了ActionBar，怎么处理

### ISSUE THREAD

**Issue by leiyun1993** [lipangit/JiaoZiVideoPlayer#1241]
如题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/30482851-442eeedc-9a57-11e7-8d1f-6cf245f36c7f.png)


断点一下这个函数，看看什么时候触发的

**Comment by luoyexk** [comment]
在AndroidMenifest里，acitvity标签里增加一个主题，android:theme="@style/Theme.AppCompat.Light.NoActionBar" ，这样全屏切回来后就不会再出现actionbar

**Comment by lipangit** [comment]
怎么样 解决了吗
