### ISSUE TITLE
如何获取当前帧的画面？

### ISSUE THREAD

**Issue by xiexucheng** [lipangit/JiaoZiVideoPlayer#1242]
如题

**Comment by lipangit** [comment]
textureView.getImage() 具体名字忘了，可以从textureView中取得

**Comment by xiexucheng** [comment]
@lipangit JZMediaManager.textureView.getBitmap() 却是空的

**Comment by lipangit** [comment]
播放的时候，试试别的函数，就是这个思路，亲测有效的
