### ISSUE TITLE
请问如何主动调用重播？

### ISSUE THREAD

**Issue by dongliwu520** [lipangit/JiaoZiVideoPlayer#1244]
jcVideoPlayer.startButton.performClick(); 调用的是暂停和播放，请问如何调用重播呢？ 视频有缓存后每次都是从上次记录的地方开始播放，很难受。  还有怎么获取当前帧的画面呢？ 我看了继承的是TextureView，可以用TextureView.getBitmap(); 但是我拿到的bitmap是空的的，请问是怎么回事呢？比较急, 还望能说明一下。谢谢。

**Comment by lipangit** [comment]
调startVideo()函数可以重播

SAVE_PROGRESS=false 不记录播放位置

在播放的时候调用JZMediaManager.textureView.getBitmap()，刚才又亲测没有问题
