### ISSUE TITLE
进度更新指定时间 暂停事件监控不到，我怎么处理？

### ISSUE THREAD

**Issue by wh121** [lipangit/JiaoZiVideoPlayer#1248]
@Override
    public void setProgressAndText(int progress, int position, int duration) {
        super.setProgressAndText(progress, position, duration);
        //activity.progress(position);
        if (position > 30000) {
            Log.e("whwh", "视频超过30秒》》》》" + position);
            onStatePause();
        }
    }

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard 复写onStatePause函数监听暂停，或者复写onClick函数监听暂停的点击事件

**Comment by wh121** [comment]
已经复写了
 @Override
    public void onStatePause() {
        super.onStatePause();
    }
播放时 只是显示一个暂停的按钮

**Comment by wh121** [comment]
并没有暂停的效果

**Comment by lipangit** [comment]
要暂停的效果做什么

**Comment by lipangit** [comment]
别用onStatePause这个函数去暂停视频，startButton.performClick()用这个暂停视频

**Comment by wh121** [comment]
没有用，刚才我查看了 JCVideoPlayer
使用
JCMediaManager.instance().mediaPlayer.pause();
 onStatePause();

**Comment by lipangit** [comment]
用户点击暂停按钮会暂停视频对不对，startButton.performClick()这函数模拟用户点击为什么不能暂停视频呢
