### ISSUE TITLE
如何做到一个activity中同时播放两个视频

### ISSUE THREAD

**Issue by hqAnd** [lipangit/JiaoZiVideoPlayer#1249]
亲爱的楼主，以前用你的控件播放一个视频非常好，有于需求有所变动需要一个页面同时播放两个视频，但是咱们的播放器只能同时播放一个视频，如何处理，谢谢！！！

**Comment by lipangit** [comment]
需要改动特别大！，视频控件可以初始化多个，但是播放器引擎是单例，你得改这部分

**Comment by TestSmirk** [comment]
那一个播放器 两个TextureView 怎么播放呢.楼主知道吗

**Comment by lipangit** [comment]
@TestSmirk 一个播放器只能setSurface到一个textureView上，不知道怎么能两个TexTureView

**Comment by TestSmirk** [comment]
请问楼主知道 两个TextureView   两个 player 画面同步吗. 如果不能,请问有什么同步的方法吗.

**Comment by lipangit** [comment]
不知道
