### ISSUE TITLE
请问这个全屏播放完怎么回到初始样子然后再显示reply呢?

### ISSUE THREAD

**Issue by Marlborn** [lipangit/JiaoZiVideoPlayer#1252]
首先感谢开源功能这么好的库哈.
问下,现在全屏播放完后是直接关掉了,我想把它设置到刚开始的样子,然后显示按钮reply,请问怎么做呢?

**Comment by lipangit** [comment]
就是说不关闭全屏是不是

**Comment by Marlborn** [comment]
是的 请问怎么做呢?

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写onAutoComplete函数，屏蔽父类super.onAutoComplete()，然后参照父类写自己的逻辑

**Comment by Marlborn** [comment]
哦哦 我是在demo里看的 是这个onAutoCompletion();  3ks
