### ISSUE TITLE
关于列表中视频全屏的问题

### ISSUE THREAD

**Issue by RxYuki** [lipangit/JiaoZiVideoPlayer#1256]
打开list中的视频时,想实现根据宽高比确定打开是横屏还是竖屏,请问下如何实现?
JZVideoPlayerStandard.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
这个只能在点击之前设置方向,而且设置是全局的,列表中不停滑动这个值不停的改变,无法确定点击进入全屏时的方向

**Comment by RxYuki** [comment]
后来重写了fullscreenButton的点击事件,把源码中关于fullscreenButton的代码全部copy了一份出来实现了,请问下有其他法子吗,或者作者考虑封装一下这个

**Comment by lipangit** [comment]
这个变量是假定在整个程序中全屏的方向是一样的，满足你的这个你这么做是个不错的方法。

想实现代码也不多，使用不常见，暂不考虑封装。
