### ISSUE TITLE
关于使用流程的一个小空指针BUG

### ISSUE THREAD

**Issue by hjgang** [lipangit/JiaoZiVideoPlayer#1257]
如果进来之后没有马上给控件赋值，然后点击了控件上不是按钮的位置，然后就null指针了
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.LinkedHashMap.size()' on a null
解决方案是（前两个是发布者改的）
1.在源码初始化的时候 初始化一下LinkedHashMap urlMap这个参数
2.源码269行调用urlMap的时候 做个非空判断
3.使用时，调用控件时先setUp一下 初始化

**Comment by lipangit** [comment]
请用新版，已经解决
