### ISSUE TITLE
进入全屏时进度条无法自动更新

### ISSUE THREAD

**Issue by ningwy** [lipangit/JiaoZiVideoPlayer#1258]
是这样子的，我的是列表视频，播放之后点击全屏按钮进入全屏，但是进度条无法自动更新，需要触摸一下屏幕把控制面板唤出来之后才可以

**Comment by ningwy** [comment]
请问这是 bug 吗？还是我接入的姿势不对

**Comment by lipangit** [comment]
6.0.1已经修复
