### ISSUE TITLE
设置Home键暂停，返回继续播放会崩溃

### ISSUE THREAD

**Issue by ningwy** [lipangit/JiaoZiVideoPlayer#1259]
添加这个设置之后，如果视频播放完毕，之后再点击home键，此时会调用 MediaPlayer 的pause 方法，由于视频已经播放完毕，故会导致activity无法pause而闪退

**Comment by lipangit** [comment]
是的，感谢你的反馈，这就修改之

**Comment by lipangit** [comment]
修改完毕 参照feature/CodeOptimitation分支

**Comment by ningwy** [comment]
哇，作者这么快就回复修复了，点赞
