### ISSUE TITLE
实现监听是否全屏播放的功能，出现fullScreenListener为空的情况

### ISSUE THREAD

**Issue by zz379** [lipangit/JiaoZiVideoPlayer#1260]
代码如下：

    @Override
    public void startWindowFullscreen() {
        super.startWindowFullscreen();
        // 进入全屏
        if (fullScreenListener != null) {
            fullScreenListener.isFullScreen(true);
        }
    }

    @Override
    public void startWindowTiny() {
        super.startWindowTiny();
        // 退出全屏
        if (fullScreenListener != null) {
            fullScreenListener.isFullScreen(false);
        }
    }

    private FullScreenListener fullScreenListener;

    public void setFullScreenListener(FullScreenListener fullScreenListener) {
        this.fullScreenListener = fullScreenListener;
    }

    public interface FullScreenListener {
        public void isFullScreen(boolean isFullScreen);
    }

**Comment by zz379** [comment]
出现的问题是：startWindowTiny() 方法中 fullScreenListener 为空，无法执行回调方法！
但是在startWindowFullscreen() 方法中 fullScreenListener 是可以正常调用的

**Comment by lipangit** [comment]
全屏和非全屏不是一个实例，请务必继承JZVideoPlayerStandard复写进入全屏函数，取得全屏事件

**Comment by zz379** [comment]
我使用的还是5.8.1 版本， 继承的是 JCVideoPlayerStandard ，然后复写了这两个方法。请问我升级一下library 就可以解决这个问题吗？

**Comment by lipangit** [comment]
是的，参照新版的demo的MyJZVideoPlayerStandard里面有好多方法

**Comment by zz379** [comment]
嗯嗯，好的，多谢了，大神！
