### ISSUE TITLE
盒子中使用问题

### ISSUE THREAD

**Issue by daiwuzhou** [lipangit/JiaoZiVideoPlayer#1261]
之前使用的时候是用的3.1使用是正常的，现在到6.0播放的时候有声音，没有画面，感觉是前面有一层挡住了。是和主题什么的有关吗？

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/1205  是这里说的问题吗

**Comment by daiwuzhou** [comment]
在手机上都是正常的，但是在盒子就用不了，你说这三个问题方式我都试了，没有变化，主要就是我按下后退键之后，感觉视频画面出现一下再退出，所以我才感觉是前面遮了一层。代码的Demo也出现这样的问题，之前的版本没有这个问题。

**Comment by lipangit** [comment]
下一步试试用单纯的textureView和MediaPlayer是否能在盒子上播视频

**Comment by lipangit** [comment]
因为代码逻辑是一样的，遮了一层不大可能

**Comment by iQuick** [comment]
这个问题有解决吗，我也遇到了。
jc ===>  3.6.3
盒子  ===> 小米3

**Comment by lipangit** [comment]
@iQuick 试试用单纯的textureView和MediaPlayer是否能在盒子上播视频  这个试过吗

**Comment by lipangit** [comment]
怎么样了 解决了吗
