### ISSUE TITLE
急求解答：三星手机切换清晰度有问题

### ISSUE THREAD

**Issue by junmei520** [lipangit/JiaoZiVideoPlayer#1262]
切换清新度后，三星手机清晰度不变，例如从240切到600，三星的加载一段时间后还是240，清晰度无变化，其他手机切换清晰度都无问题。希望尽快给个解答，谢谢！

**Comment by lipangit** [comment]
切换清晰度的本质是切换url，断点试试url是否改变

**Comment by lipangit** [comment]
这是代码逻辑的问题，本应和机型无关

**Comment by junmei520** [comment]
JCMediaManager.CURRENT_PLAYING_URL是已经变为了目的地址的url了，但是debug发现走了JCMediaManager类中的 mediaPlayer.setOnErrorListener(JCMediaManager.this)，
接着走了：
 @Override
    public boolean onError(MediaPlayer mp, final int what, final int extra) {
        mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                    JCVideoPlayerManager.getCurrentJcvd().onError(what, extra);
                }
            }
        });
        return true;
    }

继续跟进去，走了JCVideoPlayer类中的：
public void onError(int what, int extra) {
        Log.e(TAG, "onError " + what + " - " + extra + " [" + this.hashCode() + "] ");
        if (what != 38 && what != -38 && extra != -38) {
            onStateError();
            if (isCurrentJcvd()) {
                JCMediaManager.instance().releaseMediaPlayer();
            }
        }
    }
其中日志显示：what=-38，extra=0
请问这个是什么意思？？？
急求，只有三星手机出现这个问题。

**Comment by junmei520** [comment]
JCMediaManager.CURRENT_PLAYING_URL是已经变为了目的地址的url了，
debug发现走JCMediaManager类中的 mediaPlayer.setOnErrorListener(JCMediaManager.this)，
接着走了：
@override
public boolean onError(MediaPlayer mp, final int what, final int extra) {
mainThreadHandler.post(new Runnable() {
@override
public void run() {
if (JCVideoPlayerManager.getCurrentJcvd() != null) {
JCVideoPlayerManager.getCurrentJcvd().onError(what, extra);
}
}
});
return true;
}

继续跟进去，走了JCVideoPlayer类中的：
public void onError(int what, int extra) {
Log.e(TAG, "onError " + what + " - " + extra + " [" + this.hashCode() + "] ");
if (what != 38 && what != -38 && extra != -38) {
onStateError();
if (isCurrentJcvd()) {
JCMediaManager.instance().releaseMediaPlayer();
}
}
}
其中日志显示：what=-38，extra=0
说明onError没有做任何操作，也就是没有错的意思吗？
请问，那我还应该从哪里考虑问题所在？

**Comment by junmei520** [comment]
在JCVideoPlayer类的：
 public void onError(int what, int extra) {
        Log.e(TAG, "onError " + what + " - " + extra + " [" + this.hashCode() + "] ");
        if (what != 38 && what != -38 && extra != -38) {
            onStateError();
            if (isCurrentJcvd()) {
                JCMediaManager.instance().releaseMediaPlayer();
            }
        }
    }

和JCMediaManager的：
 @Override
    public boolean onError(MediaPlayer mp, final int what, final int extra) {
        mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JCVideoPlayerManager.getCurrentJcvd() != null) {
                    JCVideoPlayerManager.getCurrentJcvd().onError(what, extra);
                }
            }
        });
        return true;
    }
死循环的走
请问可以知道这是什么原因吗？
一直是what=-38，extra=0

**Comment by junmei520** [comment]
发现一个现象，三星手机，切换清晰度，流是m3u8格式的，只能从最高清晰度切到最低清晰度，其他情况都不行，而且切换时长特别长，你们看看能不能解决一下吗

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写onError函数，写自己的error处理。

**Comment by lipangit** [comment]
也可以注释掉super.onError()，屏蔽父类的处理

**Comment by junmei520** [comment]
按您的方法进行重写了onError，并注释掉了super.onError()，
但是还是同样的问题：三星手机，切换m3u8的流，只能从最高清晰度直接切到最低清晰度，其他情况都切不了，一直停留在最低清晰度，切不到其他清晰度，亲身边有三星手机吗，可以帮忙看一下吗？辛苦啦
因为其他手机都没问题，就只有三星的出现这个问题，麻烦亲帮忙看一下，万分感谢！

**Comment by lipangit** [comment]
没有三星手机，切换清晰度的本质是切换url，你在三星手机上试试，在demo里频繁切换视频，是否有报错的情况

**Comment by junmei520** [comment]
直接拿节操的demo传入3个清晰度的视频url地址，同一个demo运行在其他机型上，切换清晰度一切都正常，就是三星手机切换清晰度一直处于加载状态，很长时间后又回到最低清晰度，只有三星手机切换不了，知道本质是切换url，可是确实是只有三星手机有问题

**Comment by junmei520** [comment]
还有，请问-38的错到底是什么意思，什么情况下会产生-38？

**Comment by lipangit** [comment]
android.media.MediaPlayer里查不到

**Comment by junmei520** [comment]
发现三星手机时，多次走了onStatePreparingChangingUrl（）方法，当走第2次是时this.currentUrlMapIndex 又被置为了0，
我临时的解决办法时，在点击清晰度的监听改为(注：我切换的是直播流)
：   OnClickListener mQualityListener = new OnClickListener() {
public void onClick(View v) {
                    loadingProgressBar.setVisibility(VISIBLE);
                    startButton.setVisibility(INVISIBLE);
                    int index = (int) v.getTag();
                    Log.e("TAG33", "切换清晰度 : "+index);
                    currentUrlMapIndex=index;
                    String currentkey = JCUtils.getKeyFromLinkedMap(urlMap, index);
                  String currentUrl= (String) urlMap.get(currentkey);
                    Log.e("TAG33", "currentUrl="+currentUrl);
                    currentState = CURRENT_STATE_PREPARING_CHANGING_URL;
                    seekToInAdvance = 0;
//                    JCMediaManager.CURRENT_PLAYING_URL = JCUtils.getCurrentUrlFromMap(urlMap, this.currentUrlMapIndex);
                    JCMediaManager.CURRENT_PLAYING_URL =currentUrl;
                    JCMediaManager.CURRENT_PLING_LOOP = loop;
                    JCMediaManager.MAP_HEADER_DATA = headData;
                    JCMediaManager.instance().prepare();
.....其他不变

然后写一个自定义类继承JCVideoPlayer
重写
 @Override
    public void onStatePreparingChangingUrl(int urlMapIndex, int seekToInAdvance) {
//        super.onStatePreparingChangingUrl(urlMapIndex, seekToInAdvance);
    }

这样三星手机的切换m3u8格式的清晰度问题解决了，而且很快，
但是有个后遗症，其他手机虽然切换清晰度也可以成功，但是加载时间特别长。

还肯请大神在有三星手机时测试一下，
毕竟我不是专业开发播放器的，而且其实这个问题我并没有完全根除，
希望大神可以彻底解决一下这个问题。
真的和手机有关，不知道是不是因为三星手机的分辨率原因还是什么的.
真的拜托您了。

**Comment by lipangit** [comment]
兄弟，帮我断点一下你没修改的时候两次调用onStatePreparingChangingUrl，分别是哪里，应该只有一次呀，就是点击切换清晰度的时候，另一次是哪里
