### ISSUE TITLE
Can't stream with big size of video

### ISSUE THREAD

**Issue by piseysen** [lipangit/JiaoZiVideoPlayer#1266]
Example: http://khmovies.s3.amazonaws.com/%E1%9E%9A%E1%9E%BF%E1%9E%84%20%E1%9E%9F%E1%9F%92%E1%9E%94%E1%9F%82%E1%9E%80%E1%9E%82%E1%9E%84%E1%9F%8B.MP4

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/30963502-3f8f7f48-a413-11e7-9514-224d3d27960e.png)

I think something wrong with internet or server,Big size of video is ok in theory.
