### ISSUE TITLE
没找到屏蔽手势Api

### ISSUE THREAD

**Issue by vihuela** [lipangit/JiaoZiVideoPlayer#1267]
看到了onTouch的逻辑，默认提供mChangePosition =true 及在全屏时手势滑动进度有效，但是是否可以提供手动控制mChangePosition的Api
还有另外一个问题。。为什么全屏之后View会再次初始化。。。

**Comment by lipangit** [comment]
没有api 复写onTouch函数，然后参照父类写自己的逻辑

全屏前后是两个实例

**Comment by vihuela** [comment]
get it

**Comment by lipangit** [comment]
辛苦
