### ISSUE TITLE
有没有办法，在播放器层面提高视频加载的速度，不要点击了播放按钮后缓存好一会才开始播放？

### ISSUE THREAD

**Issue by zhangshaobo87** [lipangit/JiaoZiVideoPlayer#1269]
有没有办法，在播放器层面提高视频加载的速度，不要点击了播放按钮后缓存好一会才开始播放？

**Comment by lipangit** [comment]
对于中小公司而言，没法优化android.media.MediaPlayer，用cdn加速服务可以加快速度。
大公司都是在ijkplayer或者ffmpeg上修改的

**Comment by zhangshaobo87** [comment]
谢谢
