### ISSUE TITLE
Is Streaming video have any cache ?

### ISSUE THREAD

**Issue by riteshmahajan47** [lipangit/JiaoZiVideoPlayer#1270]
when tap on ""reply" button video  starts again streaming, even it's already buffered.

When video buffered and tap on buffered seek-bar video again streaming.

**Comment by riteshmahajan47** [comment]
Ok, but what for buffered seekbar ? If user tap over buffered seekbar that means video already buffered and no need o stream again but video not playing and again streaming. same for reply button.

**Comment by lipangit** [comment]
There may be a relationship with the phone.It will not streaming after streaming once in many phone above android5.0
