### ISSUE TITLE
Play video from local file

### ISSUE THREAD

**Issue by kennybuc** [lipangit/JiaoZiVideoPlayer#1271]
@lipangit 

I've integrated this library to my app and it's playing the video from url very nicely.
The problem is that I don't find any option to play the video from local file which I've downloaded from the url. The video file can be saved to internal or external storage. I want to play this video file using this library.
I have seen several issues related to playing video from local file but I didn't find the solution.

Can you please let me know how I can play the video from local file?
I like this library and it would be appreciated if you provide me the solution.

Thanks!

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31023215-c3d81812-a500-11e7-8437-648837c8d220.png)

It will solve your problem. 
Have a nice day.
