### ISSUE TITLE
ViewPager嵌套视频播放器始终会记住之前的进度播放

### ISSUE THREAD

**Issue by sunkeding** [lipangit/JiaoZiVideoPlayer#1275]
退出当前页面或者退出当前APP，下次进入Viewpager页面会默认记住之前的播放进度，希望是下次进来是播放视频从0s开始的。

**Comment by lipangit** [comment]
http://weibo.com/tv/v/FogTl6ymb?fid=1034:a2cad5217ab35856e8c173fc5984fedc

这个视频有答案。
![2b1c1bae-ba46-4000-be18-305e42c84cf0](https://user-images.githubusercontent.com/2038071/31331524-3385fa28-ad15-11e7-934b-1a53ce27bdef.png)

**Comment by lipangit** [comment]
这个变量改成false不记录播放位置
