### ISSUE TITLE
点击全屏播放，之前赋值的值，全部变为Null,自定义组件也全部重新布局

### ISSUE THREAD

**Issue by xie438305665** [lipangit/JiaoZiVideoPlayer#1280]

**Comment by xie438305665** [comment]
!
![dyi r2cz2t kvw7pq5 ep](https://user-images.githubusercontent.com/19592766/31374951-94621260-add2-11e7-958f-a31f251a5012.png)

**Comment by lipangit** [comment]
用setUp的Objects，这个可以传递
