### ISSUE TITLE
关于是否是wifi播放的问题

### ISSUE THREAD

**Issue by JackMask** [lipangit/JiaoZiVideoPlayer#1282]
怎么才能去掉自己带的dialog,我需要在设置里面手动设置这个开关

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard复写onShowWIfiDialog，可以屏蔽这个方法

**Comment by JackMask** [comment]
那如何禁用播放呢？大神，如果你能出个api就好了，这样就能根据api来做，期待出api

**Comment by lipangit** [comment]
复写onShowWIfiDialog函数的时候屏蔽父类的
//super.onShowWifiDialog
这样走到这个方法的时候对话框就不显示了

你是想调用一个函数，实现这个功能是吧，这个库本质上没有api，都是通过继承JZVideoPlayerStandard，复写函数来实现功能

**Comment by JackMask** [comment]
嗯啊，我就是这样做的，刚才通过研究，基本解决了这个问题

**Comment by JackMask** [comment]
感谢大神
