### ISSUE TITLE
您好大神 亮度调节还是无法解决 

### ISSUE THREAD

**Issue by 18667366881** [lipangit/JiaoZiVideoPlayer#1284]
您好大神 亮度调节还是无法解决  在多层在你原viewpage and listview 的最外面加一层Activity  亮度调整无效

 我的层级是 TabActivity（第一层选项卡一共有4个子的选项卡HOMEActivity DemoActivity GoodsActivity MeActivity） 有问题的是 HomeActivity + Fragment(循环添加了10个Fragment + ViewPager + RecyclerView.Adapter )（选项卡一个） QQ 674483879 谢谢大神帮忙

**Comment by lipangit** [comment]
无法解决是什么意思，是全屏的手势亮度调节亮度不变吗

**Comment by 18667366881** [comment]
嗯 是的  全屏华东亮度 数值变化  实际亮度不变

**Comment by lipangit** [comment]
这个能不能抽象出一个demo给我调试一下，没遇到过这种情况
