### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by chaopengTan** [lipangit/JiaoZiVideoPlayer#1285]
请问这个问题如何处理？

![im4 t gm8kg 9 ms zhil](https://user-images.githubusercontent.com/12883454/31417888-0990c5e4-ae65-11e7-910e-47fe704e3a78.png)

**Comment by lipangit** [comment]
在报错之前是否调用releaseAllVideos，在正确的时候调用releaseAllVideos应该能解决这个问题

**Comment by chaopengTan** [comment]
没有，就是正常的播放，然后就闪退了

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31423995-77971126-ae1d-11e7-875c-64ae21bfc1e4.png)

这块代码是怎么加的

**Comment by chaopengTan** [comment]
我不太明白你的意思 ，抱歉

**Comment by lipangit** [comment]
这个不是strict mode检测吗，如果不加检测的代码是没有这个的

**Comment by chaopengTan** [comment]
抱歉，把这个忘记了，取消掉检测模式确实没问题了
