### ISSUE TITLE
关于重播

### ISSUE THREAD

**Issue by 932236581** [lipangit/JiaoZiVideoPlayer#1286]
你好大神。 我这边 重新播放 还是需要加载  不能立马播放  不知道有没有这个问题呢。

**Comment by lipangit** [comment]
有一个loop变量，设为true就会循环播放

**Comment by 932236581** [comment]
什么变量吗？ JZMediaManager.CURRENT_PLING_LOOP = true; 是这个吗？   貌似不行。    我点了重播 还是 需要重新加载这个视频的。。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31443901-4231aad0-ae60-11e7-84e1-676026a09a88.png)

这个

**Comment by ZxxWaHa** [comment]
你好，没有找到你说的这个方法，是:6.2.2版本。是修改方法名了吗？

**Comment by lipangit** [comment]
新版本在这里

![image](https://user-images.githubusercontent.com/2038071/34068683-9d8c95ae-e27a-11e7-9683-1d7169821d84.png)
