### ISSUE TITLE
如果要实现视频的短时间缓存，该怎么做呢？  不要同一个视频  看了 之后再点击播放 还要重新加载

### ISSUE THREAD

**Issue by zhangshaobo87** [lipangit/JiaoZiVideoPlayer#1288]
有思路么

**Comment by lipangit** [comment]
根据不同的安卓版本自带缓存，实测6.0的16M以下的会缓存，4.*的手机应该没有缓存

**Comment by jmhjmh** [comment]
非加不可的话可以尝试使用https://github.com/danikula/AndroidVideoCache这个看看

**Comment by lipangit** [comment]
这个项目我也调试过，在各种情况下效果一般，可以自己集成到自己的项目中，demo就不推荐了

**Comment by jmhjmh** [comment]
嗯！主要是MediaPlayer抓不到缓冲流，只能通过这种本地代理的方式抓取流，我也试了试，效果一般，网速不稳定的话很容易缓冲失败

**Comment by zhangshaobo87** [comment]
我试试，谢谢2位！
