### ISSUE TITLE
怎么隐藏进度条样式、设置时间字体的大小

### ISSUE THREAD

**Issue by zhiqiangli520210** [lipangit/JiaoZiVideoPlayer#1289]
如题

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写setUp函数，设置字体大小。复写onState函数设置各个状态的进度条样式

**Comment by zhiqiangli520210** [comment]
JZVideoPlayerStandard在哪里依赖的呢？我是这么搞的compile 'cn.jzvd:jiaozivideoplayer:6.0.2'

**Comment by lipangit** [comment]
对，这个包里就有JZVideoPlayerStandard
