### ISSUE TITLE
二次播放m3u8文件报错

### ISSUE THREAD

**Issue by bupt2017** [lipangit/JiaoZiVideoPlayer#1290]
把直播源地址m3u8文件放进去，刚装app的时候可以播放成功，退出app后再点击就不会播放了

**Comment by lipangit** [comment]
新建个项目，用android.media.MediaPlayer和textureView测试，找出问题出在哪， 然后我在项目里改

**Comment by guochaochao** [comment]
我刚遇到这个问题，新加载和onpause的时候把原地址的播放进度去掉就可以了，JZVideoPlayer.clearSavedProgress(context,"http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8");
