### ISSUE TITLE
App Crashes on android 4.2.2 when FullScreen button is clicked

### ISSUE THREAD

**Issue by marothiatechs** [lipangit/JiaoZiVideoPlayer#1291]
I am using this library in a recyclerView in android 4.2.2
Video is playing fine but app crashes as soon as I click on the full screen button. Please help me solve this issue .. My app is in production with this library.

**Comment by lipangit** [comment]
show the log

**Comment by jmhjmh** [comment]
in the AndroidManifest.xml. add  android:configChanges="orientation|screenSize|keyboardHidden"

**Comment by lipangit** [comment]
Maybe

**Comment by lipangit** [comment]
@jmhjmh 对这个感兴趣吗
![image](https://user-images.githubusercontent.com/2038071/31677670-3097d68e-b331-11e7-8c41-29890d570c70.png)

**Comment by jmhjmh** [comment]
@lipangit 我在你的群里
