### ISSUE TITLE
在列表中点击播放一直转圈，不能播放

### ISSUE THREAD

**Issue by ostaro28** [lipangit/JiaoZiVideoPlayer#1293]

**Comment by ostaro28** [comment]
http://sjdb.hljnews.cn:8080/img/picture/20171016/f2fced06-8fd0-4634-ae0a-ddb0fd690cc1.mp4

**Comment by lipangit** [comment]
八成是服务器的问题，因为在chrome中需要点击开始才能播放

尝试办法：
![image](https://user-images.githubusercontent.com/2038071/31615195-753e46b2-b24e-11e7-93d1-bc71c2468c07.png)

对比demo中链接的header，让Server端尝试改一下

**Comment by ostaro28** [comment]
这个视频在谷歌和火狐打开没有需要点击啊  进去就开始播放了啊

**Comment by ostaro28** [comment]
而且 之前也是可以的   突然一下不可以   而且网络良好的

**Comment by ostaro28** [comment]
而且之前的版本是可以播放的  是近期才发现 一直在转圈  在网络情况良好下也是一直在加载

**Comment by lipangit** [comment]
新建个项目试试用android.media.MediaPlayer和textureView能否正常播放

以前哪个版本能播放
