### ISSUE TITLE
请问播放网络视频出现“三角形里面有一个感叹号”的图片代表什么？

### ISSUE THREAD

**Issue by zhjingb** [lipangit/JiaoZiVideoPlayer#1296]
6.0.2版本，WiFi状态下且网络良好，部分手机播放视频到中后段是会出现“三角形里面有一个感叹号”的图片，点击屏幕会重头开始播放，能知道什么原因吗？

**Comment by zhjingb** [comment]
打Log提示为onError1-1004

**Comment by lipangit** [comment]
1004是io问题

新建项目用android.media.MediaPlayer和textureView试试是否有这个问题

**Comment by zhjingb** [comment]
@lipangit 谢谢大神回复，我昨天测试发现使用5.2.1的demo播放视频是不会出现这种情况的，5.3开始往上的版本都有这种情况项目着急上线的情况下先使用以前的版本了，以后在看一下具体什么问题

**Comment by zhjingb** [comment]
@lipangit 用MediaPlayer和textureView播放也会中断，
http://ekingcar.oss-cn-beijing.aliyuncs.com/video/10/201710160001.mp4
请问这是跟视频有关吗

**Comment by lipangit** [comment]
刚才测试了这个链接，暂未发现异常，我觉得这个问题不影响发版，但是原因还要继续探索。

**Comment by zhjingb** [comment]
目前是在三星测试机和部分用户的华为机出现这个问题，像是因为预加载了39%，播放到39%不能继续加载了，所以停止播放了。
我在之前issues里面搜索到也有人出现了-1004，他使用了ijk之后可以正常播放，我用他的demo在三星测试机上测试也可以正常播放了

**Comment by lipangit** [comment]
这个问题应该能解决，我觉得视频播放适配最好的还是系统自带的android.media.MediaPlayer对于我们中小公司而言。

**Comment by zhjingb** [comment]
@lipangit 恩恩，因为有用户反馈，所以用的是5.2.1版本的，5.2.1版本使用的是mediaplayer，暂时没还发现有这个问题

**Comment by Destiny01** [comment]
我也有这个问题在华为手机上用这个http://www.tianshengdiyi.com/upload/app/banner.mp4链接会出现三角图标

**Comment by zhjingb** [comment]
@Destiny01 我们是有好几个华为的手机是有这种问题

**Comment by zhjingb** [comment]
@Destiny01 我没有华为的测试机，没将mediaplayer换成ijk之前三星测试机播放我们的视频有的会出问题，将mediaplayer换成ijk之后的demo，用三星手机测试你的这个视频可以播放完的，不会中断

**Comment by lipangit** [comment]
三星手机有点坑了，系统的播放器直接播放视频有问题

**Comment by laughmaker** [comment]
这个问题，目前在我们app里出现也很频繁，尤其是在7.0以上的系统里。有很多用户提到了这个问题。自己测试也能复现，最后断点找进去，就是mediaplayer里的-1004

**Comment by lipangit** [comment]
新建项目，用android.media.MediaPlayer和textureView播放视频是否会中途中断？

**Comment by LegendBMKill** [comment]
E/MediaPlayer: error (1, -1004)
D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel *)] : [1134] callback app listenerNotNull=1, send=1
D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel *)] : [1138] callback application
E/MediaPlayer: Error (1,-1004)
I/MediaPlayer: [HSM] stayAwake false uid: 10383, pid: 5598


我的华为手机也有这个问题

**Comment by LegendBMKill** [comment]
用android.media.MediaPlayer和textureView播放视频  同样报1004的错误  中断播放

**Comment by lipangit** [comment]
恩，这就有点坑了。

**Comment by HolickABC** [comment]
请问有什么解决办法吗？三星s8也会

**Comment by zhjingb** [comment]
@HolickABC  可以把项目里面的MediaPlayer换成ijk，可以试一下，我换过是可以的

**Comment by HolickABC** [comment]
@zhjingb
我换ijk不行   用新版本把

**Comment by zhjingb** [comment]
@HolickABC 我用6.1.2测试还是存在问题的啊，你用新版可以了吗？

**Comment by HolickABC** [comment]
@zhjingb 不可以  应该是我iOS同事的问题   这个视频是iOS处理过的

**Comment by zhjingb** [comment]
@HolickABC 噢噢，找到原因就好

**Comment by zhangshaobo87** [comment]
你们找到解决方案了吗

**Comment by zhjingb** [comment]
@zhangshaobo87 可以把项目里面的MediaPlayer换成ijk，我们的项目是可以的，你可以试一下，或者把视频连接发给我我帮你试一下

**Comment by zhangshaobo87** [comment]
@zhjingb 怎么换  把源代码下下来 自己修改吗？

**Comment by zhjingb** [comment]
@zhangshaobo87 恩，把代码中用到MediaPlayer的地方换成ijk，直接替换就可以

**Comment by zhangshaobo87** [comment]
@zhjingb 好的，谢谢你 我去试试

**Comment by lipangit** [comment]
@zhangshaobo87 新版本一行代码替换ijkplayer

**Comment by zhangshaobo87** [comment]
@lipangit  我看到你的版本更新说明了，我昨天也集成了最新版，但是 有好几个地方报错，然后再群里问了，他们都说要自己把源码下下来自己修改，我只好又换回旧版了，比如说那个广播，一直报错说没有反注册，但是看了你那个广播是私有的

**Comment by zhangshaobo87** [comment]
旧版本没这个问题

**Comment by zhangshaobo87** [comment]
@lipangit  旧版本没这个问题呢

**Comment by zhangshaobo87** [comment]
@lipangit  我把你刚写的代码看了下  重新更新到最新版本了  换成ijkplayer  现在可以了 非常感谢！

**Comment by lipangit** [comment]
好
