### ISSUE TITLE
全屏的时候背景变成透明的了，求解，不知道是不是Activity的theme的问题

### ISSUE THREAD

**Issue by HeYongRui** [lipangit/JiaoZiVideoPlayer#1297]

**Comment by lipangit** [comment]
JZVideoPlayerStandard继承的RelativeLayout，试试设置这个的背景是否能解决问题

**Comment by HeYongRui** [comment]
JZVideoPlayerStandard继承的是JZVideoPlayer，JZVideoPlayer继承的是FrameLayout，试过setBackgroundColor无效果

**Comment by lipangit** [comment]
对比一下demo，actiity是不是透明的？

设置JZVideoPlayerStandard的背景颜色不生效吗

**Comment by HeYongRui** [comment]
试过了所有的配置都没用，最后发现是换肤框架的问题，加了换肤框架（Android-skin-support），这边就透明了，但是不加就不能换肤，好坑爹啊，阿里百川反馈也是加了换肤就不行，头痛...

**Comment by lipangit** [comment]
加油，么么哒
