### ISSUE TITLE
播放视频地址相同时候有问题

### ISSUE THREAD

**Issue by JameChen** [lipangit/JiaoZiVideoPlayer#1298]
播放视频地址相同时候滑动时候播放会有混乱问题

**Comment by jmhjmh** [comment]
好像这个是已知问题，等作者看看吧

**Comment by JameChen** [comment]
还有我怎么监听播放状态回调项目怎么没有暴露接口给我们

**Comment by jmhjmh** [comment]
你可以在onAutoCompletion自己写个回调处理。具体你看看源码JZMediaManager里面播放完成会回调onAutoCompletion

**Comment by JameChen** [comment]
那不是要改源码吗

**Comment by jmhjmh** [comment]
是的。默认作者应该是没提供相关的接口

**Comment by lipangit** [comment]
播放地址相同只要不在一个activity也是可以的，如果一个列表一个activity有相同的url就要修改源码了
