### ISSUE TITLE
画面还没加载，声音先播放了

### ISSUE THREAD

**Issue by ChenJunXu** [lipangit/JiaoZiVideoPlayer#1300]
我这边有部分视频，画面还没加载，声音先播放了。
现在导致原本总时长为 9s 的视频，播放了声音后，视频才开始加载。导致播放进度出现了十多秒，比总时长还长。
有什么办法让两者同步吗？

**Comment by jmhjmh** [comment]
你的视频是多音轨？

**Comment by ChenJunXu** [comment]
不是。后面发现是视频本身的问题
