### ISSUE TITLE
Auto Play

### ISSUE THREAD

**Issue by piseysen** [lipangit/JiaoZiVideoPlayer#1301]
I wanna use auto play video after ON_AUTO_COMPLETE. I have issue with layout not update, it's still show retry while next video playing. I hope you will tell the key to deal it. Thanks

**Comment by jmhjmh** [comment]
Look at the demo MyJZVideoPlayerStandard ,onStateAutoComplete is play complete.  use jzVideoPlayer.startButton.performClick()   play next video

**Comment by piseysen** [comment]
Thanks, It's Ok but it block UI and show retry label

**Comment by jmhjmh** [comment]
the video format is mp4?  because video engine is MediaPlayer  ,maybe not support the video format ,
look the onError int what, int extra  is what ，  Also can replace video engine, eg ijkplayer

**Comment by piseysen** [comment]
mp4

**Comment by lipangit** [comment]
How is it going
