### ISSUE TITLE
在WebView里面 在播放视频的时候调用 offsetTopAndBottom 会冲突 , 导致offsetTopAndBottom无效 , VideoView不会 ,不知道为什么

### ISSUE THREAD

**Issue by lll-01** [lipangit/JiaoZiVideoPlayer#1305]

**Comment by lll-01** [comment]
检查了一下 , 发现是由于视频播放进度改变的时候设置
 currentTimeTextView.setText(JZUtils.stringForTime(position))
由于TextView 的宽度不固定 , 导致每次setText() 都会 requestLayout , 导致webView的父布局的 onLayout被调用 , 由于onLayout 自定义了 , 使得出现了卡顿

如果我没有搞错的话 ...
建议固定TextView 的宽度 ...

**Comment by lipangit** [comment]
是ui布局的问题吗？
什么效果，看看截图？

**Comment by lll-01** [comment]
类似一个下拉刷新的动效 , 下划的过程中动态的offsetTopAndBottom , 然后这个时候视频正在网页里面播放 ,由于TextView 的宽度不固定 , 导致每次setText() 导致 onLayout 调用 . 导致  offsetTopAndBottom() 和 onLayout() 冲突了 ,  

问题原因是我的自定义ViewGroup 兼容性不太好 , 但是为了更方便简单的解决问题  , 我还是下载项目源码 , 将布局文件里面的 TextView 宽度固定了 , 然后就解决问题了

**Comment by lipangit** [comment]
解决了就好
