### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by 547555857** [lipangit/JiaoZiVideoPlayer#1306]
当视频正在加载过程中，我跳转界面了 ，视频缓冲完毕了 会自动播放，但是我界面跳转了，
问 如何暂停缓冲或者 当前视频的播放周期如何能跟这activity走， 当activity进入stop或者onDestroy。视频也相应的暂停或者销毁

**Comment by jmhjmh** [comment]
看demo。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31890434-b8201fbc-b7c8-11e7-80ce-6889330b0df2.png)

这个加了吗

@jmhjmh 告诉人家"看demo"和没说一样

**Comment by jmhjmh** [comment]
@lipangit 😂这就尴尬了。看来还得有图有真相

**Comment by lipangit** [comment]
😂 小问题
