### ISSUE TITLE
rtsp播放摄像头问题

### ISSUE THREAD

**Issue by bifan-wei** [lipangit/JiaoZiVideoPlayer#1307]
同一个rstp播放地址播放摄像头流，一个手机4.2可以播放，其他三个手机都播放失败了，大概是什么问题，地址应该没问题，电脑上播也可以

**Comment by lipangit** [comment]
直播流可以把播放引擎换成ijkplayer，这个支持更好一些，系统的MediaPlayer和安卓的版本有关系，有的安卓版本支持的不好，有的手机就没问题
