### ISSUE TITLE
从全屏切回非全屏，屏幕点击事件失效

### ISSUE THREAD

**Issue by XuQK** [lipangit/JiaoZiVideoPlayer#1308]
在NestedScrollView里面嵌套的VideoPlayer，播放是全屏，然后再退出全屏，整个NestedScrollView里面就对点击没反应了，NestedScrollView上方的自定义View点击也没反应，NestedScrollView下方的LinearLayout可以点击。

**Comment by lipangit** [comment]
这时候视频是正常播放的吗

**Comment by XuQK** [comment]
是的

**Comment by XuQK** [comment]
6.0.0，android版本6.0，手机Nexus5。
本来想用6.1.0_preview，显示和annotationProcessor冲突，就降了一个版本。

**Comment by lipangit** [comment]
断点一下jZVideoPlayer里的onTOuch函数，看看进没进来

**Comment by XuQK** [comment]
目前测试情况：
刚开始播放的非全屏情况点击播放器范围：走onTouch
全屏后点击播放器范围：不走onTouch
退出全屏后：点击任何地方都不走onTouch

**Comment by lipangit** [comment]
不走onTouch，说明没点击到控件上，怎么回事，好像不是控件的问题了

**Comment by lipangit** [comment]
这样哥们，你新建个项目单独用NestedScrollView和JZVideoPlayerStandard，看看是不是NestedScrollView的问题

**Comment by XuQK** [comment]
明天测，测试app都写好了，路由器突然趴窝尼玛(ーー゛)

Nathen <notifications@github.com> 于 2017年10月23日周一 22:06写道：

**Comment by XuQK** [comment]
测试了，没问题，看来是我这边的问题了。。。

**Comment by lipangit** [comment]
么么哒

**Comment by XuQK** [comment]
发现问题所在了，是因为根布局是一个继承了LinearLayout的设置了软键盘状态监听的布局，就是跟这个布局冲突，应该是这个播放器的全屏方法里面有某些设置和监听布局大小变化的东西起冲突了，能提供点思路吗

**Comment by XuQK** [comment]
啊，换了种监听方法，不再使用该设置了布局大小监听器的根布局了，直接在Acitivty里监听RootView和根布局的高度差来实现监听软键盘显隐了，问题完美解决。只是还是不知道那个自定义的监听布局变化大小变化的布局到底是哪里设置不对了

**Comment by lipangit** [comment]
这种问题就谁遇到谁解决了，我就不调试了
