### ISSUE TITLE
how set current video position ?

### ISSUE THREAD

**Issue by wanderson7** [lipangit/JiaoZiVideoPlayer#1310]
I wanted to start the video in a specific position (progress), how can I do this?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31922938-87c3de1a-b83d-11e7-9ac0-8fe4aa6a51f4.png)

set this params after setUp

**Comment by wanderson7** [comment]
<img width="701" alt="captura de tela 2017-10-24 as 09 48 54" src="https://user-images.githubusercontent.com/17430567/31941519-e4c66c5a-b8a0-11e7-977a-99216ab411a3.png">

I did it that way and it did not work? Do you have an example?

**Comment by wanderson7** [comment]
I'm using cn.jzvd:jiaozivideoplayer:6.0.2

**Comment by wanderson7** [comment]
Thanks for listening.
Congratulations

**Comment by lipangit** [comment]
Congratulations for what, My goal is to solve your problem
