### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kahlidabuhayea** [lipangit/JiaoZiVideoPlayer#1312]
Failed to resolve: cn.jzvd:jiaozivideoplayer:6.1.0_preview

**Comment by lipangit** [comment]
This is a [preview version](https://github.com/lipangit/JiaoZiVideoPlayer/releases/tag/6.1.0_preview)
Development work has not yet completed，You can download [demo](https://github.com/lipangit/JiaoZiVideoPlayer/releases/download/6.1.0_preview/jiaozivideoplayer-6.1.0_preview.apk) to test scroll in list, I will fix these bugs I found, next week will complete.
