### ISSUE TITLE
全屏字幕

### ISSUE THREAD

**Issue by fengchuiyeluo** [lipangit/JiaoZiVideoPlayer#1313]
自己加了本地字幕显示逻辑，但全屏的时候不生效，请问这个要如何修改

**Comment by lipangit** [comment]
因为全屏和非全屏不是一个实例，你那边具体是什么逻辑添加的字幕，我帮你想想解决办法

**Comment by fengchuiyeluo** [comment]
解析本地srt文件进行显示
private Runnable srtRunnable = new Runnable() {
        @Override
        public void run() {
            if (lstSrt.size() == 0) {
                return;
            }
            int currentPosition = CustomJZVideoPlayer.this.getCurrentPositionWhenPlaying();
            for (int i = 0; i < lstSrt.size(); i++) {
                SRT srt = (SRT) lstSrt.get(i);
                if (currentPosition >= srt.getBeginTime() && currentPosition < srt.getEndTime()) {
                    txtSrt.setText(srt.getSrtBody());
                    break;
                }
            }
            txtSrt.postDelayed(srtRunnable, 500);
        }
    };

这是一个简单的runnable，测试了是两个实例，所以考虑下复制JCVideoPlayer和JCVideoPlayerStandard这两个源码出来或使用module的形式修改，时机大概参考progress（除了显示、隐藏），你觉得这种方式可行不，有没有更简洁的方式呢？感谢

**Comment by fengchuiyeluo** [comment]
今天也尝试了使用你旧版本里的exoplayer版本，因为exoplayer可以加载字幕，这种方式可行不

**Comment by lipangit** [comment]
可能你现在的目标是在启动全屏的时候启动这个runnable，可以复写setUp中启动，也可以复写setProgressAndText函数

**Comment by fengchuiyeluo** [comment]
方向想错了，问题就出在非同一个实例身上，感谢
