### ISSUE TITLE
请问如何自定义播放按钮事件

### ISSUE THREAD

**Issue by fg2q1q3q** [lipangit/JiaoZiVideoPlayer#1314]
你好，请问如何自定义播放按钮事件（比如我的视频可能是付费的，用户点击播放时先判断是否为付费观看），另外还有一个问题：点击全屏之后如何默认为强制横屏

**Comment by lipangit** [comment]
参考demo的SMallChangeUiActivity，可以自定义简单的控件和事件，也可以看我的微博有自定义事件和自定义功能的视频教程 http://weibo.com/2342820395/profile?topnav=1&wvr=6&is_all=1

**Comment by fg2q1q3q** [comment]
那点击全屏之后如何默认强制横屏而且继续全屏前的播放进度呢，我是带详情一类的播放器

**Comment by lipangit** [comment]
点击全屏之后如何默认强制横屏而且继续全屏前的播放进度，这个问题请看微博中的“过一遍demo”里面讲解orientationActivity的时候讲了这个问题
