### ISSUE TITLE
How to localize language of player in my project ?

### ISSUE THREAD

**Issue by alzozov** [lipangit/JiaoZiVideoPlayer#1315]
How make player use other custom language rather then english ?
Do I need to build project from source for this ?

**Comment by lipangit** [comment]
Do not need to change source code, just new string.xml like this
![image](https://user-images.githubusercontent.com/2038071/31963334-e56f0c3c-b8c5-11e7-90e5-d3f906d199c2.png)

**Comment by alzozov** [comment]
thanks, and if i am using gradle import ?

**Comment by lipangit** [comment]
new folder in your res folder, example: res/values-bra/string.xml

**Comment by alzozov** [comment]
works great! thank U
