### ISSUE TITLE
现在的是点击全屏进入竖屏的全屏，请问点击全屏怎样进入横屏怎么设置？

### ISSUE THREAD

**Issue by MrLi123456** [lipangit/JiaoZiVideoPlayer#1316]
现在的是点击全屏进入竖屏的全屏，请问点击全屏怎样进入横屏怎么设置？

**Comment by lipangit** [comment]
参考demo的orientationActivity，也可以看我的微博，有视频教程 http://weibo.com/2342820395/profile?topnav=1&wvr=6
