### ISSUE TITLE
播放未下载完成的视频文件会报错

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [lipangit/JiaoZiVideoPlayer#1317]
![cs101_171025_150100](https://user-images.githubusercontent.com/19187129/31984794-5554a014-b995-11e7-90c6-3a24265b4592.jpg)

后台执行了文件下载, 同时点击视频控件进行播放就会抛出异常.

**Comment by Guangxingtianxia** [comment]
什么异常？

**Comment by lipangit** [comment]
是不是在未setUp的情况下开始播放的视频，用新版，这个问题已经解决了，不会有空指针了。

**Comment by Android-AwesomeRoy** [comment]
@lipangit  已经setup了. logger里有看到. 但是这个文件还在下载中, 并且加载的是本地文件播放. 才会抛出这个异常.

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard拦截一下onClick函数

@Override
public void onClick(View v) {
    //你的拦截代码的判断，如果什么什么为空就return

    super.onClick();//通过你拦截之后再走正常的逻辑
}
