### ISSUE TITLE
Can we write an English version of README.MD

### ISSUE THREAD

**Issue by qymspace1** [lipangit/JiaoZiVideoPlayer#1319]
This library is quite popular, it would be nice to have the official docs in english

**Comment by lipangit** [comment]
I think the formal documents should be written in english, but It is difficult for me to write readme, write wiki in English is not posible.

Can you help me to translate, if you know more about JZVD writing docs is better.

**Comment by qymspace1** [comment]
Yes, I can help translate the main documentation to english where I can. How can I help? As per my knownledge of JZVD I have implemented a player in my app not sure if that is enough

**Comment by lipangit** [comment]
First you can translate the readme make readme in native english, then push a pull request.

**Comment by lipangit** [comment]
Hello  do you have time

**Comment by qymspace** [comment]
Hello, I have gone through the english Readme.md and corrected the grammar. I have been very busy off late with school but soon, I will look deep into the player and write a proper documentation in English

**Comment by qymspace** [comment]
I have created a pull request for the minor changes

**Comment by lipangit** [comment]
Tired, there are problems at any time to communicate

**Comment by qymspace** [comment]
Yes, there are conflicts. I will look into them

**Comment by lipangit** [comment]
the pr is closed, your commit has been commit to develop by my hand
