### ISSUE TITLE
能不能自定义超时时间啊

### ISSUE THREAD

**Issue by wf08314110101** [lipangit/JiaoZiVideoPlayer#1322]
比如说我做了个播放列表，当第一个视频播放完成时我关掉网络，我setUp下一条并start，界面开始转圈35秒左右OnError回调才会回来，我能不能自定义这个时间啊

**Comment by lipangit** [comment]
不应该吧，MediaPlayer是单例的，第二个视频在启动的时候会release MediaPlayer，他们是同一个mediaPlayer
你说的这个问题能复现吗

**Comment by wf08314110101** [comment]
是我描述的不清楚，其实就是当我关闭网络时执行下面这段代码时，界面会进入转圈等待界面，大约35秒左右OnError回调才会执行
public void next() {
        curIndex++;

        if (curIndex >= videoModels.size()) {
            if (!isCircle) {
                return;
            }
            curIndex = 0;
        }

        // "http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4"
        VideoModel model = videoModels.get(curIndex);
        if (model == null) {
            return;
        }
        myPlayer.setUp(convertUrl(getFullPath(model.videoName))
                , myPlayer.currentScreen, model.videoTitle);
        myPlayer.startButton.performClick();
    }

**Comment by lipangit** [comment]
好像无法自定义超时时间，你可以研究一下android.media.MediaPlayer有没有这个api
