### ISSUE TITLE
缩略图以及全屏播放标题栏问题

### ISSUE THREAD

**Issue by ZhySir** [lipangit/JiaoZiVideoPlayer#1323]
如题，
求教缩略图如何撑满播放器？
直接依赖的工程，如何来解决全屏播放标题栏占一半的问题？

**Comment by lipangit** [comment]
1.设置imageView的属性

2.继承JZVideoPlayerStandard，复写getLayoutId函数，修改自己的layout布局

**Comment by ZhySir** [comment]
那老哥，播放器能否设置圆角？

**Comment by lipangit** [comment]
不知道，你可以尝试给缩略图、textureView、jzvd设置圆角
