### ISSUE TITLE
如何取消全屏时竖屏播放

### ISSUE THREAD

**Issue by danniu1314** [lipangit/JiaoZiVideoPlayer#1324]
1.如何取消全屏时竖屏播放
2.重力感应横竖屏时，横竖屏切换直接横屏全屏播放，竖屏就恢复到原来的位置播放。目前没找到在哪去修改这个地方，请帮忙解答下。

**Comment by lipangit** [comment]
1.参考orientationActvitiy

2.没明白什么意思，你是说切换横竖屏的时候，会改变播放进度？

**Comment by danniu1314** [comment]
目前在首页重力感应横屏的时候不会有反应，我已经设置manifest.xml中mainacitvity的android:configChanges="orientation|keyboard|locale|screenSize|layoutDirection"，但是如果重力感应放于横屏时不能做到满屏。而且在手机竖直放置时，必须点击旋转按钮才放大全屏，但是手机处于竖直时全屏不是横屏显示，依然是竖屏显示。我的想法就是老式的，在原始状态重力感应到横屏时就直接全屏横屏播放，感应到竖屏时就恢复小屏幕回到原始位置。

**Comment by danniu1314** [comment]
OrientationActivity这个只是旋转了屏幕，视频画面并没有全屏

**Comment by lipangit** [comment]
OrientationActivity展示了如何修改全屏前和全屏后的屏幕方向

你的需求是什么，还是没看懂，你的需求demo里有没有

**Comment by danniu1314** [comment]
全屏的时候，demo中会根据重力感应会出现全屏的竖屏，我想取消这个，只保留全屏的横屏。目前已经搞定。目前最新demo中API这个页面我看实现的是视频开始播放的时候手机横放可以横屏全屏，但是竖立时依然是全屏只是画面跟着回到竖立，但是回不到原始位置没退出全屏。我只想转动手机要么全屏要么默认位置。这个我去哪里改呢？谢谢

**Comment by lipangit** [comment]
明白了，就是说自动进入全屏的时候，在手机检测到竖直方向要自动退出全屏，而不是进入竖屏的全屏

参考下面的方法，可以在检测到竖屏的时候退出全屏
![image](https://user-images.githubusercontent.com/2038071/32131928-58a9baec-bb7f-11e7-9204-5231d10aa4a8.png)

**Comment by 793383996** [comment]
不能点击默认横屏吗？点击全屏还出现横屏的全屏？

**Comment by 793383996** [comment]
兄弟，你这播放器效果是可以，配置和代码感觉乱的一匹，像这些播放完成回调，点击全屏是否开启重力感应应该在初始化控件的时候设置进去的，你没用过网络访问框架吗？可以参考他们的设计，你这功能是很多，我觉得你应该把小窗口分出一个分支自定义播放器，虽然你功能都实现了，代码和架构看起来很乱

**Comment by lipangit** [comment]
务必先继承JZVideoPlayerStandard，然后自定义播放器，拒绝setListener这种回调。

其他功能的设置用全局变量设置。

**Comment by lipangit** [comment]
希望你能融入我的思想

**Comment by lipangit** [comment]
@793383996 全屏默认横屏，demo有例子

**Comment by 793383996** [comment]
好的，谢谢

**Comment by 793383996** [comment]
http://www.apkbus.com/thread-275935-1-1.html

**Comment by 793383996** [comment]
https://juejin.im/entry/59c105fbf265da065d2b6a85
