### ISSUE TITLE
能够统计观看时长吗，快进的不算。

### ISSUE THREAD

**Issue by lmdiloveu** [lipangit/JiaoZiVideoPlayer#1325]
视频教学项目要求用户必需看够指定时长，才能完成学时！
请问大概要怎么做？

**Comment by lipangit** [comment]
可以实现

继承JZVideoPlayerStandard，复写setProgressAndText函数，这个函数可以取得播放进度。

你可以复写setProgressAndText函数中，累加时间。

复写onComplete函数(表示停止或者播放其他视频)和onAutoComplete函数(表示自动播放完成)，记录下累加的时间

**Comment by lmdiloveu** [comment]
谢谢回复，我尝试下，要是上线了，把代码分享出来

**Comment by lipangit** [comment]
么么哒

**Comment by seraphzxz87** [comment]
> 谢谢回复，我尝试下，要是上线了，把代码分享出来

你好，请问实现该功能了吗？

**Comment by lipangit** [comment]
继承jzvdstd复写onProgress函数，记录累加播放时长，这个函数在正常播放的时候每秒会被调用好几次。



---原始邮件---
发件人: "seraphzxz87"<notifications@github.com&gt;
发送时间: 2020年3月15日(周日) 晚上7:56
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 能够统计观看时长吗，快进的不算。 (#1325)




  
谢谢回复，我尝试下，要是上线了，把代码分享出来
  
你好，请问实现该功能了吗？
