### ISSUE TITLE
提的建议，pr我这边同步的时候太慢了，加一行代码

### ISSUE THREAD

**Issue by danniu1314** [lipangit/JiaoZiVideoPlayer#1326]
在JZVideoPlayer中的startWindowFullscreen()中添加一句jzVideoPlayer.setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                                                | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY | View.SYSTEM_UI_FLAG_FULLSCREEN);
加入后，华为手机和有虚拟键的手机全屏时可隐藏虚拟键
![image](https://user-images.githubusercontent.com/15703913/32099235-14cd9858-bb42-11e7-80c3-2f24fa5088da.png)

**Comment by lipangit** [comment]
这是进入全屏的操作，退出全屏需要做什么吗

**Comment by danniu1314** [comment]
不用，我测试了，退出全屏恢复正常虚拟键

**Comment by lipangit** [comment]
已经添加

**Comment by kiss377052** [comment]
> 不用，我测试了，退出全屏恢复正常虚拟键

老哥 我这边华为的带虚拟键 返回的时候虚拟键没了 退出全屏得处理的呀

**Comment by lipangit** [comment]
@danniu1314 兄弟，在吗 这块蒙圈了 需要帮助setSystemUiVisibility 这个函数。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/53686719-b9d13e80-3d65-11e9-8a83-6ce6b11d91a3.png)

https://www.cnblogs.com/zhengxt/p/3508485.html  这里面退出沉浸式的时候出现了这种问题，怎么办
![image](https://user-images.githubusercontent.com/2038071/53686726-d53c4980-3d65-11e9-884e-546409e9ffd9.png)

用的这个
