### ISSUE TITLE
能不能 设置 播放速度

### ISSUE THREAD

**Issue by ltpostbox** [lipangit/JiaoZiVideoPlayer#1328]

**Comment by lipangit** [comment]
可以，android.media.MediaPlayer.getPlaybackParams()可以设置速率，但是可能需要5.0以上才支持(具体的版本忘了)

**Comment by ltpostbox** [comment]
6.0以上才支持的  但是我们目前使用的是5.1版本的，好想哭...

**Comment by lipangit** [comment]
这是目前的现状

**Comment by ltpostbox** [comment]
哎...我只能再继续查查
