### ISSUE TITLE
播放器加载缩略图不显示

### ISSUE THREAD

**Issue by Orangeliubaocheng** [lipangit/JiaoZiVideoPlayer#1332]
mVideoView.thumbImageView.setImageURI(Uri.parse("http://192.168.31.37:8080/upload/avatar/1507862246371.jpg"));

方法名字和readme中介绍使用的方法不一样啊,我的demo里面只能用上面的方法才能放网络地址,而介绍里面的方法是setImage,而且demo中点不出这个方法.总之,上面的代码无法显示缩略图.

**Comment by lipangit** [comment]
参考MainActivity

**Comment by DuYB** [comment]
jcv.thumbImageView就是ImageVi对象，自己利用图片加载工具实现。比如            GlideUtil.setGlideDefaultView(mContext, trainArticleBean.getCoverUrl(), jcv.thumbImageView);
