### ISSUE TITLE
playing video from inputStream

### ISSUE THREAD

**Issue by ghost** [lipangit/JiaoZiVideoPlayer#1337]
can i play video directly from inputStream?

**Comment by lipangit** [comment]
can not play video without protocol？

you can use hls or rtsp protocol

**Comment by backListed** [comment]
But how?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/32326254-28257342-c00d-11e7-92ad-c4172bd45be6.png)

you should make server first
