### ISSUE TITLE
How to hide progress bar in full screen ?

### ISSUE THREAD

**Issue by Sarun1001** [lipangit/JiaoZiVideoPlayer#1338]
I want to hide the small progress bar at the bottom in full-screen mode

**Comment by lipangit** [comment]
extends jzvideoPlayerStandard
@Override
public void setAllControlsVisiblity(){
    invisible the progress bar, the bottom progress bar will never be seen
}

**Comment by Sarun1001** [comment]
Thanks. one more question, sorry for asking too many questions I cant understand the tutorials in Chinese.
How to change progress bar position, I want to change it from bottom to top or just below or on the video, like in the older versions

**Comment by lipangit** [comment]
extends jzvideoPlayerStandard
@override
getLayoutId（）{
  return your layout id, you can put the progress bar from bottom to top in this layout.
}

**Comment by Hardtack1** [comment]
To hide bottomProgressBar completely, in addition to setAllControlsVisiblity() as @lipangit said,
bottomProgressBar.setVisibility(View.VISIBLE) needs to be commented out in dissmissControlView(). Otherwise, the bottomProgressBar will be shown again after a few seconds (after dismissControlView).
