### ISSUE TITLE
播放地址无效Toast

### ISSUE THREAD

**Issue by 547555857** [lipangit/JiaoZiVideoPlayer#1340]
地址没问题 正常播放状态  但是一直弹出播放地址无效  debug 只执行了一次setup 方法 并没有多次执行这个方法

**Comment by lipangit** [comment]
播放地址无效是这行代码判断，debug的时候进入setUp之后，这部分代码是怎么走，鼠标指向变量，看看哪个变量是空
```java
    public void setUp(LinkedHashMap urlMap, int defaultUrlMapIndex, int screen, Object... objects) {
        if (this.urlMap != null && !TextUtils.isEmpty(JZUtils.getCurrentUrlFromMap(urlMap, currentUrlMapIndex)) &&
                TextUtils.equals(JZUtils.getCurrentUrlFromMap(this.urlMap, currentUrlMapIndex), JZUtils.getCurrentUrlFromMap(urlMap, currentUrlMapIndex))) {
            return;
        }
```

**Comment by 547555857** [comment]
debug 发现并不是执行setup 报出播放地址无效  是执行startVideo 这个方法报出的，我是继承JCVideoPlayerStandard 得自定义的video  重写了
   @Override
    public void startVideo() {
        is_Playing = true;
        super.startVideo();
    }
方法 我用的是5.7版本

**Comment by 547555857** [comment]
视频正在播放一直出现 播放地址无效 视频是正常播放的

**Comment by lipangit** [comment]
弹出Toast的代码，是哪个逻辑调用的，这个断点出结果了吗

**Comment by 547555857** [comment]
sorry，我点重新播放  视频也是正常播放的  但是还是会不断的出现播放地址无效， 点击重新播放这个按钮我没有任何我的逻辑 都是走的video的逻辑，所以我觉得  是不是video 我哪里设置的不正确？ 有没有某个设置，导致的这个？

**Comment by 547555857** [comment]
兄弟  是我逻辑错误  我有服务一直在请求数据 适配数据， 耽误你时间了 问题找到了，谢谢
