### ISSUE TITLE
只有视频没有声音，地址在浏览器上播放是有声音的

### ISSUE THREAD

**Issue by yichenweimei** [lipangit/JiaoZiVideoPlayer#1341]
地址:http://vodrzliknfx.vod.126.net/vodrzliknfx/b26d2b69-8e36-4e79-9209-0b98a62e4c2e.mp4

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/32432835-ebb78d46-c313-11e7-9cb4-0e0c4e193197.png)


这个视频是用手机合成的吗，可能声音相关的参数安卓里不支持，截图中左边是你的，截图右边是demo里的视频，对比一下区别，再做修改

**Comment by yichenweimei** [comment]
这个视频是ios那边合成的，这边播放没有声音。但是5.0以下的有声音，5.0以上无声音

**Comment by lipangit** [comment]
咱们应该迎合MediaPlayer，用它能播放的格式
