### ISSUE TITLE
获取视频时长

### ISSUE THREAD

**Issue by RookieTree** [lipangit/JiaoZiVideoPlayer#1342]
有些视频获取不到时长，总时长显示00:00，但是进度条直接到顶，不能拖动 只能一点点播放，如何解决啊 大佬

**Comment by lipangit** [comment]
因为进度条的长度是0，拖动时的进度所有都会是0，所以不能拖动，我还没遇到过获取不到市场的视频，能发个链接看看嘛

**Comment by RookieTree** [comment]
http://voduye1x8hg.nosdn.127.net/0-193273482304257-mix.flv  
是不是这个链接有问题啊？

**Comment by lipangit** [comment]
请格式化视频到支持的格式

https://developer.android.com/guide/topics/media/media-formats.html
