### ISSUE TITLE
关于状态栏意外跳出的问题；；

### ISSUE THREAD

**Issue by RXlung** [lipangit/JiaoZiVideoPlayer#1344]
环境：activity嵌套ftagment，fragment中播放视频；本来全屏，但点击播放后状态栏蹦达出来了；真是意外之喜！

**Comment by 50kg** [comment]
在setContentView之前添加这个falgs
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);//设置成全屏模式

之后重写

@Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        //判断是否有焦点
        if (hasFocus && Build.VERSION.SDK_INT >= 19) {
            View decorView = getWindow().getDecorView();
            decorView.setSystemUiVisibility(
                    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                            | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                            | View.SYSTEM_UI_FLAG_FULLSCREEN
                            | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
            );

        }
    }

可解决全屏播放视频隐藏状态栏，操作后状态栏又显示的问题

**Comment by lipangit** [comment]
JZVideoPlayer下的这两个变量可以控制全屏前后的状态栏是否隐藏

public static boolean ACTION_BAR_EXIST = true;
public static boolean TOOL_BAR_EXIST = true;
