### ISSUE TITLE
Api设计问题

### ISSUE THREAD

**Issue by artzok** [lipangit/JiaoZiVideoPlayer#1345]
说实话，我觉得本项目的 api 设计的很烂，为什么使用反射创建 JZVideoPlayerStandard 呢？该类连个进度 (状态) 监听的接口都没有，还要通过继承实现相应接口！好吧，就通过继承吧，结果是通过继承实现接口回调发现无法拿到实例，那怎么设置接口实例呢？顺便提一点，源码写的真够乱的！虽说开源是做贡献呢，可我真的忍不住想吐槽你的贡献！

**Comment by lipangit** [comment]
通过继承自定义播放器无疑是最正确的，代码乱的问题，我已经多次专门修改源码的层次了，还在努力
