### ISSUE TITLE
视频在RecyclerView条目中播放，点击全屏后 重力感应切换横屏时 闪退

### ISSUE THREAD

**Issue by YmsStu** [lipangit/JiaoZiVideoPlayer#1346]
1-07 15:14:10.415 2064-4068/? E/AudioService: No RCC entry present to update
11-07 15:14:10.415 2425-2425/? E/RemoteController: Cannot set synchronization mode on an unregistered RemoteController
11-07 15:14:10.999 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.798 508-2289/? E/AudioFlinger: open /proc/524/cmdline error
11-07 15:14:11.799 508-803/? E/AudioFlinger: open /proc/524/cmdline error
11-07 15:14:11.835 508-508/? E/AudioFlinger: open /proc/524/cmdline error
11-07 15:14:11.993 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.994 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.994 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.995 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.996 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.997 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.997 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.998 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.999 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:11.999 539-3404/? E/PPDaemon: void ScreenRefresher::ProcessRefreshWork(): pthread_cond_timedwait failed. err: Success
11-07 15:14:12.223 2064-3894/? E/AudioService: No RCC entry present to update
11-07 15:14:12.223 2425-2425/? E/RemoteController: Cannot set synchronization mode on an unregistered RemoteController

**Comment by lipangit** [comment]
从log上看不出有效的信息，log好像不是错误的信息

**Comment by YmsStu** [comment]
这是闪退时的所有的log

**Comment by YmsStu** [comment]
这是在RecyclerView条目中点击播放时产生的log：
E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
 E/JiaoZiVideoPlayer: startProgressTimer:

**Comment by lipangit** [comment]
这几条log应该不会闪退，你找找有没error或者exception之类的内容

**Comment by moonlove95** [comment]
manifest有配置好吗

**Comment by YmsStu** [comment]
manifest配置好了。闪退时候 除了上面的log  没有其他的log产生了

**Comment by lipangit** [comment]
老铁，清空log，闪退一下，然后把所有log都复制过来吧，
