### ISSUE TITLE
请问如何添加是否在WIFI情况下的判断？

### ISSUE THREAD

**Issue by swt930** [lipangit/JiaoZiVideoPlayer#1347]
源码里没有了点击事件，请问如何添加是否在WIFI情况下的判断？

**Comment by lipangit** [comment]
点击开始按钮会判断网络状态，你想要什么点击事件

**Comment by swt930** [comment]
4G网络情况下  点击播放  只有一个提示弹窗  怎么设置每次点击播放都弹出4G的提示

**Comment by lipangit** [comment]
JZVideoPlayer.WIFI_TIP_DIALOG_SHOWED  每次弹出对话框之后把这个变量设置成false，下次还会弹出对话框
