### ISSUE TITLE
mulitholder 在recyclerview中小窗口播放  播放器所在的item 播放器不能设置间距

### ISSUE THREAD

**Issue by yk963307153** [lipangit/JiaoZiVideoPlayer#1348]
<cn.jzvd.JZVideoPlayerStandard
        android:id="@+id/jzvideo_player"
        android:layout_width="match_parent"
        android:layout_height="180dp"
        android:layout_marginLeft="@dimen/common_margin_left_34px"
        android:layout_marginRight="@dimen/common_margin_left_34px" />

设置下边两句间距的代码 之后， 列表中不能小窗口播放。

**Comment by lipangit** [comment]
可以啊老铁，我在直播，你可以来看看，刚才测试了，可以进入小窗播放，不受影响，没测试之前我觉得也不应该有影响
