### ISSUE TITLE
recycycleview自动集成了小窗播放了么？如何去掉列表右下角的小窗视频呢？

### ISSUE THREAD

**Issue by gaoshan12312** [lipangit/JiaoZiVideoPlayer#1349]

**Comment by lipangit** [comment]
参照demo中listView按钮进入的recycleViewActivity这是不会进入小窗播放的

**Comment by gaoshan12312** [comment]
demo我有试的。listview里面通过按钮进入demo也是有右下角的小窗口播放的。也没见有代码添加这个功能。真是自动集成上的话，有什么api方法取消掉呢？

**Comment by lipangit** [comment]
demo中ActivityListViewRecyclerView.java

        recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzvd = view.findViewById(R.id.videoplayer);
                if (jzvd != null && jzvd.getCurrentUrl().equals(JZMediaManager.CURRENT_PLAYING_URL)) {
                    JZVideoPlayer.releaseAllVideos();//这行是重点
                }
            }
        });

**Comment by lipangit** [comment]
新版demo

**Comment by gaoshan12312** [comment]
ok，谢谢了。还有一个问题，在偷偷摸摸用你demo里面的视频资源测试开发了几天之后。今天被公司iOS开发的女同事发现了，她现在看我的眼神让我很扎心。

**Comment by lipangit** [comment]
拿她当哥们就好了
