### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by zvingwsy** [lipangit/JiaoZiVideoPlayer#1350]
在模拟器上不能播放 ，用手机可以了。设置和代码完全和quick start 中的一样。
封面显示不知道为啥？是图片有什么特殊的要求吗？（用的网络图片可以直接在地址栏打开的）

**Comment by zvingwsy** [comment]
设置的封面无效

**Comment by lipangit** [comment]
能具体说一下你是怎么设置的吗，这些信息无法定位问题和错误

**Comment by lipangit** [comment]
不要在模拟器中测试，模拟器却东西
