### ISSUE TITLE
Auto play like facebook.

### ISSUE THREAD

**Issue by shiv71** [lipangit/JiaoZiVideoPlayer#1351]
It is possible auto play video like facebook in this library.

**Comment by lipangit** [comment]
Is this your question?

Or you have achieved。

**Comment by gokrish6670** [comment]
is it possible to auto play in this library @lipangit

**Comment by lipangit** [comment]
There is no ready-made function, you can continue to complete this function on the basis of this

**Comment by gokrish6670** [comment]
yeah i did my own.... and its working too

**Comment by lipangit** [comment]
Could you share with me, I am searching more effect of video player
