### ISSUE TITLE
关于播放m3u8二次播放失败的解决方案

### ISSUE THREAD

**Issue by guochaochao** [lipangit/JiaoZiVideoPlayer#1352]
我刚遇到这个问题，新加载和onpause的时候把原地址的播放进度去掉就可以了。 简单说就是保证在播放时这个视频没有进度记录就可以了
我的代码示例：
 protected void initView() {
        JZVideoPlayer.clearSavedProgress(context,"http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8");
        videoplayer.setUp("http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8",  JZVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");
    }

 @Override
    protected void onPause() {
        super.onPause();
        JZVideoPlayer.releaseAllVideos();
        JZVideoPlayer.clearSavedProgress(context,"http://live.hkstv.hk.lxdns.com/live/hks/playlist.m3u8");
    }

**Comment by lipangit** [comment]
就是说m3u8的播放记录的时候就会播放失败是吗

**Comment by guochaochao** [comment]
可以这样说，只要保存了当前进度就会播放失败

**Comment by lipangit** [comment]
@guochaochao 
![image](https://user-images.githubusercontent.com/2038071/33128317-fba3c660-cfc6-11e7-81bd-9b95438ec95e.png)

可以尝试一下这个方法
