### ISSUE TITLE
请问如何获取点击事件？在点击事件的时候进行一些操作？

### ISSUE THREAD

**Issue by swt930** [lipangit/JiaoZiVideoPlayer#1353]
我们有个需求，需要上传视频浏览量，在点击播放或者监听到视频播放的时候调一个接口，请问怎么获取点击事件？或者监听到视频在播放？我的视频是在listview里

**Comment by lipangit** [comment]
继承JZVideoPlayertstandard，复写onClick函数，所有按钮的点击事件都走这里，复写onTouch函数，能监听到全屏后的手势。
