### ISSUE TITLE
JIAOZiVideoPlayer 播放raw视频问题

### ISSUE THREAD

**Issue by XXP1228** [lipangit/JiaoZiVideoPlayer#1356]
String path="android.resource://"+getPackageName()+"/"+R.raw.video;
        Uri uri = Uri.parse(path);
        JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.video);
        jzVideoPlayerStandard.setUp(uri.toString(), JZVideoPlayerStandard.SCREEN_STATE_ON, "xiuxiu");
根据之前的issue，这种方式播放不出来了，大家可以帮忙看看嘛

**Comment by lipangit** [comment]
可以放到assert文件夹下，在MediaPlayer的setDataSource的时候传入context参数

也可以参照demo的apiActivity复制到SD卡上再播放

**Comment by lipangit** [comment]
参考新版demo，通过自定义mediaPlayer实现传context参数
