### ISSUE TITLE
Unable to replay video

### ISSUE THREAD

**Issue by rameshkec85** [lipangit/JiaoZiVideoPlayer#1357]
11-12 10:46:28.592 9464-9525/cn.jzvd.demo E/MediaPlayer: error (1, -2147483648)
11-12 10:46:28.593 9464-9504/cn.jzvd.demo E/MediaPlayer: Error (1,-2147483648)
11-12 10:46:28.593 9464-9464/cn.jzvd.demo E/JiaoZiVideoPlayer: onError 1 - -2147483648 [251305444]

**Comment by lipangit** [comment]
Could you show me your video url?
