### ISSUE TITLE
怎么播放MP3文件

### ISSUE THREAD

**Issue by keaitao0321** [lipangit/JiaoZiVideoPlayer#1359]
我播放MP3文件,部分不了,点击没反应

**Comment by lipangit** [comment]
点击之后至少会进入prepareing状态，会有loading的显示。

需要更多的描述和log，现在没法确定原因。

**Comment by keaitao0321** [comment]
解决了,但是我只想用这个播放器来播放mp3文件,希望得到音频总长度和控制播放进度,改怎修改UI

**Comment by lipangit** [comment]
在没播放的时候是无法得到音频总长的，控制播放进度是什么意思

**Comment by keaitao0321** [comment]
我想自定义UI

**Comment by lipangit** [comment]
继承JZVideoPLayerstandard 参考demo smallChangeUiactivity
