### ISSUE TITLE
关于自定义UI和点击事件的一些问题。

### ISSUE THREAD

**Issue by EchoKoreyoshi** [lipangit/JiaoZiVideoPlayer#1360]
想做一下视频列表，没播放的时候UI上要在标题下面显示播放次数，右下角显示视屏总时长，播放完毕重播下面要有分享到各个平台的图标。还有全屏的时候隐藏一些图标；还有就是各个button的点击事件，比如点击开始 弹出toast 之类的；我是需要 extends JZVideoPlayerStandard重写里面的方法：
public int getLayoutId() {
        return XXXXXXXXX;//这个是自己想要的布局，要自己写好xml还是。。。。。？
    }
那拿到各个按钮的点击事件是哪个方法，具体怎么做- -、我刚自学android不久就来请教一下

**Comment by lipangit** [comment]
1.getLayoutId这个布局就是自定义的布局，自己写比较麻烦，先把库的标准布局的内容复制出来，然后在此基础上修改，例如你的修改是添加显示播放次数的控件，显示视频总时长控件，分享图标这三个控件。

2.各个按钮的点击事件，复写onClick函数，所有的点击事件都会走这个函数，复写onTouch函数，手势操作会回调这个函数。

每天都有直播，可以来直播间提问，讲明白为止。

**Comment by EchoKoreyoshi** [comment]
把库的标准布局的内容复制出来，不需要的控件给隐藏，然后加一些自己想要的控件？是不是删掉了编译会报错- -、

**Comment by lipangit** [comment]
标准布局的控件不能删除 ，只能隐藏，删除会报错。

**Comment by EchoKoreyoshi** [comment]
@Override
    public void setUp(String url, int screen, Object... objects) {
        super.setUp(url, screen, objects);
        //是否为全屏
        if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
            mLlBatteryTime.setVisibility(View.INVISIBLE);
            mTvVideoTotalTime.setVisibility(View.INVISIBLE);
            mTvPlayCount.setVisibility(View.INVISIBLE);
        } else {
            mTvVideoTotalTime.setVisibility(View.VISIBLE);
            mTvPlayCount.setVisibility(View.VISIBLE);
        }
    }
Override这个方法设置没用。。。还有那个OnClick( ):
     @Override
    public void onClick(View v) {
        super.onClick(v);
        switch (v.getId()){
            case R.id.start:
                ToastUtils.showShort("点击开始按钮!");
                break;
        }
  ｝
这个这样写 只要点击中间的按钮不管是 开始 重播  暂停  都会弹出toast

**Comment by lipangit** [comment]
在判断按钮的点击之后，然后判断当前的播放状态，如果是normal就toast

**Comment by EchoKoreyoshi** [comment]
大神。。点击开始播放按钮，视频直接进入全屏播放，并且 上下或者左右滑动的时候播放下一个视频，这样子感觉好难呀，我需要做些什么 T_T

**Comment by lipangit** [comment]
开始播放之后进入全屏播放，这是列表看不见的，怎么会滑动列表

**Comment by EchoKoreyoshi** [comment]
在recyclerview视频列表里面，点击开始按钮视频开始播放，这个时候我要调用接口去记录播放历史和次数 接口又要 一个用户ID和视频ID两个参数传过去，我在adapter里面对开始按钮设置点击监听之后会跟播放器里面的OnClick方法冲突，这个时候我要怎么去解决，不会在播放器的OnClick方法里面直接请求接口吧？那样的话完全不行啊，请大牛指点一下！

**Comment by lipangit** [comment]
点击开始按钮用线程请求你的接口不行吗？  开始播放必须要等到接口返回数据才能开始吗

**Comment by EchoKoreyoshi** [comment]
播放器 现在默认的是全屏播放完之后直接退出全屏  不要让他退出 这个是哪个方法  我找了好一会儿 都没搞定  点拨我一下O.O

**Comment by lipangit** [comment]
旧版本参考JZVideoPlayerStandardAutoCompleteAfterFullscreen，全屏之后播放完成不退出全屏

新版这个demo落下了，明天改好，周末再发一个正式版本
