### ISSUE TITLE
视频第二次无法播放

### ISSUE THREAD

**Issue by zwping** [lipangit/JiaoZiVideoPlayer#1364]
http://dtznpic.oss-cn-shenzhen.aliyuncs.com/video/1-1510749480989video_1510749326796.mp4

这个视频链接使用jiaozi播放第二次无法播放，使用其余github上面的播放器即可无限次播放
eg：GSYVideoPlayer、NiceVieoPlayer

**Comment by lipangit** [comment]
好的，我研究研究

**Comment by zwping** [comment]
请问有结果吗？我这已经在准备预方案了，都已经用习惯jiecao了(╥╯^╰╥)

**Comment by lipangit** [comment]
别急，今天的工作刚刚开始，咱们这个库就是用android.media.MediaPlayer播放的视频，你可以新建一个项目单纯用这个播放试试，一会我试试，你提出的这个问题可能确实是一个隐患

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/32934845-498ba096-cba8-11e7-8add-62c53c0e75a6.png)

哥们，这个问题如图解决，至于为什么还不知道

**Comment by lipangit** [comment]
本周末发一个解决bug的版本

**Comment by zwping** [comment]
ok，谢谢，我这先本地化试试
