### ISSUE TITLE
Player orientation issue

### ISSUE THREAD

**Issue by backListed** [lipangit/JiaoZiVideoPlayer#1366]
Video playing in fullscreen landscape but after returned to activity, the activity cannot change its orientation when rotating device

   ` public void onConfigurationChanged(Configuration newConfig) {
          super.onConfigurationChanged(newConfig);

          int orientation = newConfig.orientation;

        if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
           player= JCVideoPlayerManager.getCurrentJcvd();
            if (player!=null){
           //getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                player.autoFullscreen(1);
            }
        } else {
           
            if (player!=null){
            //getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
                player.autoQuitFullscreen();
            }
        }
    }`

**Comment by lipangit** [comment]
See demo ActivityApiOrientation.java

this activity show you how to change orientation.

**Comment by backListed** [comment]
It not helps....
In that there is fixed landscape and nothing else
I want , when user plays a video from landscape orientation i need full screen... And back to normal when in portrait mode.... 
My method works. But when coming back to portrait then it not going to landscape anymore....

**Comment by lipangit** [comment]
Do you understandard these two params means in ActivityApiOrientation.java

![image](https://user-images.githubusercontent.com/2038071/32899043-cba6d084-cb24-11e7-8093-10ff7debda33.png)

**Comment by backListed** [comment]
Nop

**Comment by backListed** [comment]
It worked when both SCREEN_ORIENTATION_SENSOR for both portrait and landscape

**Comment by lipangit** [comment]
The problem is solved, but the common solution is to use two variables in the screenshot.
