### ISSUE TITLE
JZUtils中的getWindow和setRequestedOrientation两个方法，为什么需要区分Activity还是AppCompatActivity？

### ISSUE THREAD

**Issue by unclechen** [lipangit/JiaoZiVideoPlayer#1369]
AppcompatActivity不就是继承的FragmentActivity->Activity吗？

**Comment by lipangit** [comment]
因为AppCompatActivity 状态栏隐藏的时候有动画，比较好看，推荐

但是也要兼容不继承AppCompatActivity 的情况
