### ISSUE TITLE
能否显示视频的加载进度？

### ISSUE THREAD

**Issue by jinyneu** [lipangit/JiaoZiVideoPlayer#1370]

**Comment by lipangit** [comment]
暂时不能显示loading时候的网络请求的速度，下个版本添加ijkplayer等其他引擎的支持，可以根据自己的需要选择。

**Comment by mflk007** [comment]
业务需要显示加载时候的网络请求速度，怎么实现呢？ 或者具体哪个版本可以加入这个功能？@lipangit
