### ISSUE TITLE
Video could not played in recyclerview

### ISSUE THREAD

**Issue by ArslanKathia** [lipangit/JiaoZiVideoPlayer#1371]
its gives the following error i mention the log below 

> Process: com.juice.smc, PID: 27152
>                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
>                                                                    at cn.jzvd.JZVideoPlayer.startVideo(JZVideoPlayer.java:545)
>                                                                    at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:277)
>                                                                    at android.view.View.performClick(View.java:5702)
>                                                                    at android.view.View$PerformClick.run(View.java:22546)
>                                                                    at android.os.Handler.handleCallback(Handler.java:739)
>                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                    at android.os.Looper.loop(Looper.java:158)
>                                                                    at android.app.ActivityThread.main(ActivityThread.java:7237)
>                                                                    at java.lang.reflect.Method.invoke(Native Method)
>                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>                                                                    at > > >com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

I am using the latest version of this library and old version but it gives the same error?

**Comment by lipangit** [comment]
Did you change the code in library?

Break point this function maybe somewhere call this methods when crash in bad timing.
![image](https://user-images.githubusercontent.com/2038071/33069441-8814c000-ceef-11e7-8b75-361e362a262c.png)

**Comment by chen188669** [comment]
how do we solve this
