### ISSUE TITLE
当播放错误的时候如何显示错误信息

### ISSUE THREAD

**Issue by fg2q1q3q** [lipangit/JiaoZiVideoPlayer#1372]
你好，求教，当视频播放中途出错的时候，如何显示错误信息告知用户。另外有用户反映视频加载过慢，请问有优化的空间或者能在播放之前展示加载进度吗

**Comment by lipangit** [comment]
1.回调onError函数会取得错误信息，根据自己的情况展示给用户

2.android.media.MediaPlayer是系统的播放引擎，暂无相关配置和优化空间，下个版本可以自定义播放引擎，可以根据自己的情况选择播放引擎

**Comment by fg2q1q3q** [comment]
你好，onError中都是些errorcode，不够直观，也不清楚什么含义，请问在哪能知道这些错误码的具体意思

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/33127324-01e180f2-cfc3-11e7-9bce-7871fe9adde6.png)
详见文档
