### ISSUE TITLE
I need to modify dialogs

### ISSUE THREAD

**Issue by P4uman** [lipangit/JiaoZiVideoPlayer#1375]
Hi! first of all thanks a lot for your library is quite usefull!
I would like to modify the messages when you have no wifi connected or even don't show them. How may I do that?

**Comment by P4uman** [comment]
Oh and i have noticed that in spanish your message shows a negative button with says "PRAR" it would be "PARAR" or even better "CANCELAR"

**Comment by lipangit** [comment]
1.extends JZVideoPlayerStandard{
    @Override
    showWifiDialog(){
      //super.showWifiDialog(); this can Intercept dialog
     here to custom your  dialog
    }
}

2. I will change the wrong word in spanish thank you
