### ISSUE TITLE
为何视频不能播放

### ISSUE THREAD

**Issue by fg2q1q3q** [lipangit/JiaoZiVideoPlayer#1377]
http://txc-media.oss-cn-hangzhou.aliyuncs.com/txc-media/20171122121725126-7677.MP4
这是我的视频地址，其他视频都正常，但是这个视频播放不出来，也不显示错误提示
onError 1 - -2147483648

**Comment by lipangit** [comment]
确实有问题，第一次能播放，再播放就不行了，还在调试

**Comment by lipangit** [comment]
哥们，这个问题一时半会找不到原因，我觉得应该是视频本身的问题引发了MediaPlayer的bug

**Comment by fg2q1q3q** [comment]
好的，辛苦了，可能mediaplayer还是不够强大，我试了试IJKplayer可以播放

**Comment by lipangit** [comment]
可以自定义播放引擎，可以集成ijkplayer，develop分支，本周末发测试版本
