### ISSUE TITLE
视频播放完成的监听方法 

### ISSUE THREAD

**Issue by lizi0588** [lipangit/JiaoZiVideoPlayer#1383]
视频播放完成的监听方法，有吗？

**Comment by itfengan** [comment]
继承  JZVideoPlayerStandard，重写onStateAutoComplete方法
@Override
    public void onStateAutoComplete() {
        //todo
        super.onStateAutoComplete();
    }

**Comment by lipangit** [comment]
是的  todo也可以放到super的下面
