### ISSUE TITLE
recyclerview 里报错怎么解决呀

### ISSUE THREAD

**Issue by chen188669** [lipangit/JiaoZiVideoPlayer#1384]
![e9 0ll7 6lrx31ef s4e h3](https://user-images.githubusercontent.com/31298181/33156650-c3707106-d036-11e7-9c95-b3b4c95f9de7.png)

**Comment by lipangit** [comment]
改库了吗

**Comment by chen188669** [comment]
没有改呀  直接依赖上去就这样   在activity里是可以的  在recyclerview就不行了

**Comment by lipangit** [comment]
仔细对比demo的recycleview的用法，肯定是什么地方忘加了

**Comment by chen188669** [comment]
该加的都加了  recyclerview是在viewpager里面的  这个有没有影响

**Comment by lipangit** [comment]
没影响

新建一个项目，单独用最简单的recycleview和viewpager测试，看看
