### ISSUE TITLE
api 16 的播放不了

### ISSUE THREAD

**Issue by itfengan** [lipangit/JiaoZiVideoPlayer#1385]
/JiaoZiVideoPlayer: onError 1 - -2147483648 [-1346579776] 
这个最低兼容到什么版本啊

**Comment by lipangit** [comment]
什么手机什么型号，这个手机播放demo的连接能播吗

**Comment by itfengan** [comment]
你好,没有在真机测试过4.1版本,在模拟器上测试4.1版本是无法播放,demo也播放不了

**Comment by lipangit** [comment]
模拟器无法测试，有的模拟器却东西，请务必全部使用真机，真机上的问题才是需要关注的

**Comment by itfengan** [comment]
好的,谢谢!
