### ISSUE TITLE
播放长视频时，播放几分钟就出错了 JiaoZiVideoPlayer: onError 1 - -1004 [65915962]  必出现的

### ISSUE THREAD

**Issue by ZYZFlash** [lipangit/JiaoZiVideoPlayer#1386]

**Comment by lipangit** [comment]
url发过来试试， 什么手机什么安卓版本 1004是io错误

**Comment by ZYZFlash** [comment]
地址：http://sandcolleges.zero2ipo.com.cn/vc-talk-video/1509002986426.mp4 
0出现手机 华为p9 Android7.0 、 小米note2 Android6.0.1

**Comment by lipangit** [comment]
这视频chrome中无图像，请用常规的mp4编码

**Comment by wlmxj** [comment]
哥们，解决了吗？我这个mp4有图像，也播放过程中出现JiaoZiVideoPlayer: onError 1 - -1004

**Comment by ZYZFlash** [comment]
将mediapalyer 换成 IjkMediaplayer 就行了 ， 注意需要编译过得 ijkplayer才行 ，要不然有声音没图像，

**Comment by lipangit** [comment]
好解决了就好，新版可以自定义播放引擎，不需要手动改库了

**Comment by zhangshaobo87** [comment]
怎么替换呢

**Comment by zhangshaobo87** [comment]
@ZYZFlash 请问怎么替换

**Comment by lipangit** [comment]
@zhangshaobo87 看新版demo，一行代码替换ijkplayer

**Comment by ZYZFlash** [comment]
饺子最新版，已经解决了播放出错的问题  ，你可以集成最新版的
