### ISSUE TITLE
可以用来播放第三方的SDK吗

### ISSUE THREAD

**Issue by Im-LJie** [lipangit/JiaoZiVideoPlayer#1388]
比如播放乐视云、阿里云上的视频，播放参数并不是url
意思就是使用阿里的播放SDK，用咱们的播放器。能不能实现

**Comment by Im-LJie** [comment]
有木有人

**Comment by lipangit** [comment]
可以自定义类似android.media.MediaPlayer的播放引擎，有android.media.MediaPlayer类似的接口就可以

**Comment by Im-LJie** [comment]
有MediaPlayer。需要设置surface。怎么获取到这个surface

**Comment by Im-LJie** [comment]
老表，能大概说说下怎么用阿里的播放引擎，也就是类似你说的MediaPlayer。在JZVideoPlayerStandard中播放吗？

**Comment by lipangit** [comment]
参考demo中cn.jzvd.demo.CustomMediaPlayer包，自定义播放引擎
