### ISSUE TITLE
视频比较大时，拖动进度条后没有显示 loading

### ISSUE THREAD

**Issue by ChenJunXu** [lipangit/JiaoZiVideoPlayer#1389]
视频大概四五十分钟。
开始播放后，往后面移动，并没有显示loading，等 6、7 秒后播放正常。
请问为什么没显示 loading ？如果自己加判断，需要在哪里添加呢？

**Comment by lipangit** [comment]
根据多家视频app的想过loading已经被取消了，页面更干净，更舒服。

如果加的话复写onInfo函数，开始loading的时候显示，loading完成隐藏

**Comment by ChenJunXu** [comment]
哥们，试过了不行呀~
视频比较大的时候才会出现这个问题，往后拖动（未加载）的地方，页面不动，也没有 loading

**Comment by ChenJunXu** [comment]
打印了 onInfo，也没回调

**Comment by ChenJunXu** [comment]
我这个是 m3u8 的直播链接，是不是这个原因呢？麻烦看看，感激~~

**Comment by lipangit** [comment]
哥们 参照6.0以前的版本，找到loading的控件，原封不动把这部分的代码复制过来就好了

**Comment by ChenJunXu** [comment]
哥们，不行啊~找了 5.8.1 版本运行也没有 loading。网络不好的情况下，需要等上十来秒页面才会继续播放。

**Comment by lipangit** [comment]
loading的那个旋转的控件没有？
