### ISSUE TITLE
关于播放中点击返回导致ProgressTimerTask没有被及时置空

### ISSUE THREAD

**Issue by luoyexk** [lipangit/JiaoZiVideoPlayer#1390]
playView.setUp(linkedHashMap, 0, JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN);后，点击返回按钮，这个时候虽然退出了播放，但后台的ProgressTimerTask没有被及时停止置空，导致不断抛出被捕获的异常。
发生方式，
1、在Activity中设置全屏
JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
        JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;

`    @Override
    public void onBackPressed() {
        if (JZVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }`

    `@Override
    protected void onPause() {
        super.onPause();
        JZVideoPlayer.releaseAllVideos();
    }`
2、播放
3、点击返回按键，此时退出到了全屏待播放界面，并且界面处于暂停状态，点击暂停，奔溃。

返回抛出的异常
`System.err: java.lang.IllegalStateException
System.err:     at android.media.MediaPlayer.getDuration(Native Method)
System.err:     at cn.jzvd.JZVideoPlayer.getDuration(JZVideoPlayer.java:861)
System.err:     at cn.jzvd.JZVideoPlayer$ProgressTimerTask$1.run(JZVideoPlayer.java:1156)
System.err:     at android.os.Handler.handleCallback(Handler.java:743)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5426)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
JiaoZiVideoPlayer: setProgressAndText: progress=0 position=0 duration=0`

奔溃：

` FATAL EXCEPTION: main
 Process: com.zwl9517hotmail.demoplaymedia, PID: 14879
 java.lang.IllegalStateException
     at android.media.MediaPlayer._pause(Native Method)
     at android.media.MediaPlayer.pause(MediaPlayer.java:1440)
     at cn.jzvd.JZVideoPlayer.onClick(JZVideoPlayer.java:392)
     at cn.jzvd.JZVideoPlayerStandard.onClick(JZVideoPlayerStandard.java:262)
     at android.view.View.performClick(View.java:5204)
     at android.view.View$PerformClick.run(View.java:21170)
     at android.os.Handler.handleCallback(Handler.java:743)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5426)                                                                                      
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)`

**Comment by luoyexk** [comment]
在onBackPressed前关闭计时器就解决了       JZVideoPlayerManager.getCurrentJzvd().cancelProgressTimer();

**Comment by wodx521** [comment]
这个解决办法需要把代码添加到哪里,新手求教

**Comment by luoyexk** [comment]
@wodx521  

@Override
public void onBackPressed() {
    cancelTimer();
    JZVideoPlayer.backPress();
    super.onBackPressed();
}

@Override
protected void onPause() {
    super.onPause();
    cancelTimer();
    JZVideoPlayer.releaseAllVideos();
}

private void cancelTimer() {
    try {
        JZVideoPlayerManager.getCurrentJzvd().cancelProgressTimer();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

**Comment by lipangit** [comment]
@luoyexk 哥们 releaseAllVideos里调用了onComplete函数，onComplete函数调用了cancelProgressTime，这么做真的效果不一样吗

**Comment by luoyexk** [comment]
我重写了播放器类

`public class JZVideoPlayerAutoPlay extends JZVideoPlayerStandard {

    private boolean repeat;// 是否需要循环

    public JZVideoPlayerAutoPlay(Context context) {
        super(context);
    }

    @Override
    public void onAutoCompletion() {
        Log.e("tag", "JZVideoPlayerAutoPlay : onAutoCompletion + ");
        int size = urlMap.size();
        int nextIndex = currentUrlMapIndex + 1;
        if (nextIndex < size) {
            // 播放结束时，切换到下一条视频
            onStatePreparingChangingUrl(nextIndex, 0/*跳转到第0秒*/);//参照切换清晰度切换url,调用这个函数可以随时切换url
        } else {
            // 当所有视频播放结束后，判断是否需要重复
            if (repeat) {
                onStatePreparingChangingUrl(0/*从第0个开始播放*/, 0);
            } else {
                // 无法实现重播
//                super.onAutoCompletion();
//                onCompletion();
                // 实现手动点击重播
                currentUrlMapIndex = 0;
                cancelProgressTimer();
                onStateAutoComplete();

            }
        }
    }

    @Override
    public void onCompletion() {
        Log.e("tag", "JZVideoPlayerAutoPlay : onCompletion + ");
    }

    @Override
    public void onClick(View v) {
        retryTextView.setVisibility(GONE);
        super.onClick(v);
    }

    public void setRepeat(boolean repeat) {
        this.repeat = repeat;
    }
}`

**Comment by lipangit** [comment]
//```
把斜杠去掉，把代码写到这里，这样可以看到格式化之后的代码了
//```

**Comment by luoyexk** [comment]
```
public class JZVideoPlayerAutoPlay extends JZVideoPlayerStandard {
    // 是否需要循环
    private boolean repeat;

    public JZVideoPlayerAutoPlay(Context context) {
        super(context);
    }

    @Override
    public void onAutoCompletion() {
        Log.e("tag", "JZVideoPlayerAutoPlay : onAutoCompletion + ");
        int size = urlMap.size();
        int nextIndex = currentUrlMapIndex + 1;
        if (nextIndex < size) {
            // 播放结束时，切换到下一条视频
            onStatePreparingChangingUrl(nextIndex, 0/*跳转到第0秒*/);//参照切换清晰度切换url,调用这个函数可以随时切换url
        } else {
            // 当所有视频播放结束后，判断是否需要重复
            if (repeat) {
                onStatePreparingChangingUrl(0/*从第0个开始播放*/, 0);
            } else {
                // 无法实现重播
               // super.onAutoCompletion();
               //  onCompletion();
                // 实现手动点击重播
                currentUrlMapIndex = 0;
                cancelProgressTimer();
                onStateAutoComplete();

            }
        }
    }

    @Override
    public void onCompletion() {
        Log.e("tag", "JZVideoPlayerAutoPlay : onCompletion + ");
    }

    @Override
    public void onClick(View v) {
        retryTextView.setVisibility(GONE);
        super.onClick(v);
    }

    public void setRepeat(boolean repeat) {
        this.repeat = repeat;
    }
}
```

大概是这样吧，格式化怎么不按md格式套路出牌啊

**Comment by lipangit** [comment]
@luoyexk 哥们，你的用法非常正确，教课书一般的继承JZVideoPlayerStandard

**Comment by lipangit** [comment]
onStateAutoComplete 中已经调用了cancelProgressTimer函数，最近没发现timer相关的内存泄露，UERACTIon的泄露比较严重
