### ISSUE TITLE
播放器放在recycler view头部 未播放状态 滑动列表能进入小窗吗

### ISSUE THREAD

**Issue by lufangjun** [lipangit/JiaoZiVideoPlayer#1391]

**Comment by lipangit** [comment]
也可以，但是修改的地方比较多

第一步：复写startWindowTiny函数，把播放状态的判断去掉，可以在非播放状态进入小窗
第二步：修改小窗状态的ui，显示播放按钮，在小窗状态开始播放

**Comment by lufangjun** [comment]
按照你说的时可以实现，但是点击退出小窗的时候 怎么让头部的播放器接着播放呢

**Comment by lipangit** [comment]
如果小窗是从头部播放器进去的，退出小窗会自动回到头部播放器

**Comment by lufangjun** [comment]
但是在小窗里面点播放，点击back_tiny的时候JZVideoPlayerManager.getFirstFloor()就是空了

**Comment by lipangit** [comment]
小窗是怎么进来的

有其他操作吗，把firtfloor清空了

**Comment by lufangjun** [comment]
videoPlayer.startWindowTiny 进去的，没有其他操作。

**Comment by lipangit** [comment]
调用startWindowTiny 函数之后又什么操作吗，可以断点一下firstFloor=null的地方，参考apiActivity里进入小窗按钮

**Comment by lufangjun** [comment]
没有对播放器做任何操作，demo里面的是大窗没播放不会弹出小窗

**Comment by lipangit** [comment]
apiActivity里有一个非列表里的视频控件，那个展示了startWindowTiny的用法。

**Comment by lipangit** [comment]
直播的时候来看看吧，问题包解决
