### ISSUE TITLE
关于在播放器上添加自己的布局  滑动不消失的问题

### ISSUE THREAD

**Issue by moujunqiang** [lipangit/JiaoZiVideoPlayer#1396]
在播放器上面添加一个自己的布局，布局显示出来了，但是滑动隐藏之后 布局还是不消失。想问下大神 这个布局重置 应该重写哪个方法进行实现

**Comment by lipangit** [comment]
参照demo的MyJZVideoPlayerStandard，里面有多个onState... 在各个状态下分别修改你的控件

**Comment by moujunqiang** [comment]
这个能具体说一下嘛

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/33312925-2b3bd7b8-d464-11e7-800a-ecc947b6d0be.png)

参考图片，比如播放状态是显示的，其他状态不显示，那么不仅要在播放状态显示控件，其他状态也要隐藏控件

**Comment by moujunqiang** [comment]
我是重写了wifinotify方法  在里面显示了一个布局   然后重写这几个状态方法进行隐藏  ，不管用。。。。。。

**Comment by lipangit** [comment]
怎么会呢。。你看布局里所有的控件，都是在这些方法中控制显示和隐藏的
