### ISSUE TITLE
loader not hide

### ISSUE THREAD

**Issue by marwa1994** [lipangit/JiaoZiVideoPlayer#1399]
when the video is playing the loader still load and it is not hiding  and i can(t stop the video

**Comment by lipangit** [comment]
What is loader? can you explain more

**Comment by marwa1994** [comment]
the progress when the video start playing

**Comment by lipangit** [comment]
Did you change the code in library?

Does it happened in demo?

What is your code?

**Comment by marwa1994** [comment]
no i write a cuustom code 
videoPlayer.setUp(path, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");
and this is my custom code in videoplayer

public class AppCompatVideoPlayer extends JCVideoPlayerStandard {

    public static final String VIDEO_CLICK = "video";
    public ToggleButton muteButton;
    public ToggleButton fullScreenButton;
    private ImageView shareButton;
    private ImageView stopButton;
    private GestureDetector gestureDetector;
    private String currentUrl;
    private int volume_level;

    public AppCompatVideoPlayer(Context context) {
        super(context);
        initDefaultSetting(context, null);
    }

    public AppCompatVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
        initDefaultSetting(context, attrs);
    }

    public void initDefaultSetting(@NonNull Context context, @NonNull AttributeSet attrs) {
        this.fullscreenButton.setVisibility(View.VISIBLE);
        this.muteButton.setVisibility(View.VISIBLE);
        this.progressBar.setVisibility(View.GONE);
        this.currentTimeTextView.setVisibility(View.GONE);
        this.totalTimeTextView.setVisibility(View.GONE);
        this.bottomContainer.setVisibility(View.GONE);
        this.backButton.setVisibility(View.GONE);
        this.cancelDismissControlViewTimer();
        this.updateStartImage();
        initiGestureDetector(context);
    }


    @Override
    public void setUp(String url, int screen, Object... objects) {

        this.currentUrl = url;
        muteButton.setVisibility(View.VISIBLE);
        fullScreenButton.setVisibility(View.VISIBLE);
        int askedScreen = screen;
        screen = SCREEN_WINDOW_FULLSCREEN;
        super.setUp(url, screen, objects);


        if (objects.length == 0) return;
        if (askedScreen == SCREEN_WINDOW_FULLSCREEN) {
            this.bottomContainer.setVisibility(View.VISIBLE);
            muteButton.setVisibility(View.GONE);
            fullScreenButton.setVisibility(View.GONE);
            shareButton.setVisibility(VISIBLE);
            this.bottomContainer.setBackgroundColor(getResources().getColor(R.color.black_overlay));
            this.topContainer.setBackgroundColor(getResources().getColor(R.color.black_overlay));

        } else if (askedScreen == SCREEN_LAYOUT_NORMAL
                || askedScreen == SCREEN_LAYOUT_LIST) {
            this.bottomContainer.setVisibility(View.GONE);
            muteButton.setVisibility(View.VISIBLE);
            fullScreenButton.setVisibility(View.VISIBLE);
            shareButton.setVisibility(GONE);
            this.bottomContainer.setBackgroundColor(Color.TRANSPARENT);
            this.topContainer.setBackgroundColor(Color.TRANSPARENT);
        }
        this.topContainer.setBackgroundColor(Color.TRANSPARENT);
        fullscreenButton.setVisibility(View.GONE);
        updateStartImage();


    }

    @Override
    public void init(Context context) {
        super.init(context);
        muteButton = (ToggleButton) findViewById(R.id.muteButton);
        fullScreenButton = (ToggleButton) findViewById(R.id.fullScreenButton);
        shareButton = (ImageView) findViewById(R.id.share);
        startButton = (ImageView) findViewById(R.id.start);
        //startButton.setImageDrawable(getResources().getDrawable(R.drawable.ic_play_publication_single));
        shareButton.setOnClickListener(this);
       /* startButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                performClick();
            }
        });*/

        fullScreenButton.setOnClickListener(new OnClickListener() {
            @Override
            //On click function
            public void onClick(View view) {
                NavigationUtils.openFullScreenWithUrl(context, currentUrl, true);
            }
        });
        muteButton.setChecked(true);
        muteButton.setOnCheckedChangeListener((buttonView, isChecked) -> {
            if (isChecked) {
                //mute
                Logger.wtf("Appcompat", "videoPlayer mute click");
                volume_level = mAudioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
                mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC, 0, 0);
            } else {
                //unmute
                if (volume_level == 0)
                    volume_level = mAudioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC);
                mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC, volume_level, 0);
            }
        });

    }


    @Override
    public void onClick(View v) {
        int id = v.getId();
        if (id == R.id.back) {
            backPress();
            ((Activity) getContext()).finish();
        } else if (id == fm.jiecao.jcvideoplayer_lib.R.id.surface_container)
            Logger.e("error", " wat");
        else
            super.onClick(v);

    }

    private void initiGestureDetector(Context context) {

        gestureDetector = new GestureDetector(context, new GestureDetector.SimpleOnGestureListener() {
            //here is the method for double tap
            @Override
            public boolean onDoubleTap(MotionEvent e) {

                //your action here for double tap e.g.
                Logger.d("OnDoubleTapListener", "onDoubleTap");
          /*      Log.d(TAG, "toFullscreenActivity [" + this.hashCode() + "] ");
                onEvent(JCUserAction.ON_ENTER_FULLSCREEN);
                startWindowFullscreen();*/
                //NavigationUtils.openFullScreenWithUrl(context, currentUrl, true);


                return true;
            }

            @Override
            public void onLongPress(MotionEvent e) {
                super.onLongPress(e);

            }

            @Override
            public boolean onDoubleTapEvent(MotionEvent e) {
                return true;
            }

            @Override
            public boolean onDown(MotionEvent e) {
                return true;
            }

            @Override
            public boolean onSingleTapUp(MotionEvent e) {


                return super.onSingleTapUp(e);

            }
        });
    }

    @Override
    public int getLayoutId() {
        return R.layout.jc_layout_custom;
    }



    @Override
    public boolean onTouch(View v, MotionEvent event) {
        gestureDetector.onTouchEvent(event);

        int id = v.getId();
        if (id == fm.jiecao.jcvideoplayer_lib.R.id.surface_container) {
            Logger.wtf("eventaction", "" + event.getAction());
            switch (event.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    return false;
                case MotionEvent.ACTION_MOVE:
                    return false;
                case MotionEvent.ACTION_UP:
                    break;
            }
        }
        return super.onTouch(v, event);
    }


}
 please help me

**Comment by lipangit** [comment]
Overrite these functions, in these each all functions control your views.

![image](https://user-images.githubusercontent.com/2038071/33384722-cbcfecde-d561-11e7-9271-3a594c2af918.png)

**Comment by marwa1994** [comment]
thnks and if i want to hide the progressbar i just write progressbar.setvisivibility(View.gone);

**Comment by lipangit** [comment]
if you want to hide the progressbar in statePreparing write gone in onStatePreparing is not enough.

You must set visible or invisible in every setState... function
