### ISSUE TITLE
滑动进度条或者点击某处进度条放开会卡顿，这时再点击播放按钮应用崩溃，最新版的

### ISSUE THREAD

**Issue by tiefeiniu** [lipangit/JiaoZiVideoPlayer#1400]

**Comment by tiefeiniu** [comment]
JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.videoplayer);
        jzVideoPlayerStandard.setUp("http://jzvd.nathen.cn/c6e3dc12a1154626b3476d9bf3bd7266/6b56c5f0dc31428083757a45764763b0-5287d2089db37e62345123a1be272f8b.mp4"
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "饺子闭眼睛");
//        jzVideoPlayerStandard.thumbImageView.setImage("http://p.qpic.cn/videoyun/0/2449_43b6f696980311e59ed467f22794e792_1/640");
        Glide.with(MainActivity.this).load("http://a4.att.hudong.com/05/71/01300000057455120185716259013.jpg").into(jzVideoPlayerStandard.thumb

**Comment by lipangit** [comment]
demo有这问题吗？改库了吗？
这个效果第一次听说

**Comment by tiefeiniu** [comment]
没改库啊，按照文档来得

**Comment by lipangit** [comment]
卡顿是什么现象，录个小视频发到群里看看吧

崩溃log是什么

**Comment by lipangit** [comment]
怎么样了
