### ISSUE TITLE
recyclerview里视频播放后暂停，滑动会出现小窗

### ISSUE THREAD

**Issue by lufangjun** [lipangit/JiaoZiVideoPlayer#1401]
版本6.1.2
debug看到是调用了setUp方法里的startWindowTiny();

if (isCurrentJZVD() && !urlMap.containsValue(JZMediaManager.CURRENT_PLAYING_URL)) {
            startWindowTiny();
        }

**Comment by lipangit** [comment]
用新版，暂停的时候不可能进入小窗，小窗还没有播放按钮，进入小窗之后不能开始播放啊

**Comment by moujunqiang** [comment]
这个问题解决了吗 我这边是两个视频快速切换播放然后滑动会出现小窗

**Comment by lipangit** [comment]
@moujunqiang 能录个小视频看看吗，或者放到群里，可能是很严重的问题

**Comment by lufangjun** [comment]
你邮箱发送不过去啊，总是退信





在 2017-12-01 23:19:59，"Nathen" <notifications@github.com> 写道：


@moujunqiang 能录个小视频看看吗，或者放到群里，可能是很严重的问题
