### ISSUE TITLE
是否可以获取当前是否有视频在播放

### ISSUE THREAD

**Issue by chaopengTan** [lipangit/JiaoZiVideoPlayer#1402]
如题，获取当前任意界面是否有视频在播放

**Comment by lipangit** [comment]
currentState表示播放状态
有如下状态
![image](https://user-images.githubusercontent.com/2038071/33443427-7fca24c2-d632-11e7-954a-f557bb5f1e84.png)

**Comment by chaopengTan** [comment]
好的，谢谢。
