### ISSUE TITLE
播放出错

### ISSUE THREAD

**Issue by moujunqiang** [lipangit/JiaoZiVideoPlayer#1404]
MediaPlayer: error (1, -19)
MediaPlayer: error (1, -38)
视频列表有两个视频  点击播放第一个视频后点击第二个 然后再播放第一个偶尔会出现这个问题。作者碰到过吗

**Comment by tanzhixue** [comment]
播放状态出错了这个是

**Comment by moujunqiang** [comment]
什么原因导致的呢

**Comment by lipangit** [comment]
-19已经屏蔽掉了，不影响正常播放，请试试新版本

**Comment by lipangit** [comment]
遇到过，周一发版之前的测试遇到的，见没影响播放就屏蔽掉了
