### ISSUE TITLE
textureViewContainer 设置GONE的问题

### ISSUE THREAD

**Issue by tanzhixue** [lipangit/JiaoZiVideoPlayer#1405]
设置GONE 或者不在屏幕显示的时候 就不能播放？

**Comment by lipangit** [comment]
能不能播放主要看textureView的surface是否生成，朋友其实不用纠结这个

把你的使用场景和功能目标说一下，帮你想想解决办法

**Comment by tanzhixue** [comment]
我这边需求是播放音频或者视频  播放音频的时候界面要完全改掉。如果把textureView干调就播放不了了目前，这个怎么做？

**Comment by lipangit** [comment]
参考demo的自定义播放器ui，添加控件覆盖到jzvd上，旧的控件不能删除，会破坏原来的逻辑
