### ISSUE TITLE
Client closed connection before receiving entire response

### ISSUE THREAD

**Issue by jrbu59** [lipangit/JiaoZiVideoPlayer#1406]
播放一个大视频，比如 http://video.yimutian.com/misc/5a1e35cfe938e8732a984e18486d9647.mp4

Response包会断掉，抓包报错 “Client closed connection before receiving entire response”。

![1512027707722](https://user-images.githubusercontent.com/6781917/33419512-654a68cc-d570-11e7-9e42-4bd12e7c18ea.jpg)

**Comment by lipangit** [comment]
在手机里有什么症状吗

**Comment by jrbu59** [comment]
客户端表现

表面上看，先会加载(转圈)一下，然后卡顿一次，再次加载，开始播放，屏幕上还会浮一个暂停按钮。
我截屏录了个视频  http://v.youku.com/v_show/id_XMzI0NDYyMTIxMg==.html?x=&sharefrom=android&sharekey=126ad650b238581a0e97eacc6a8e1c543

抓包会看到 
第一个包，下载未完全及关闭，报错“Client closed connection before receiving entire response”。
第二个包，会206，断点下载，但客户端启始位置跟第一个包的结束位置不相符，下载会失败。
第三个包，表现同第一个包
第四个包，表现同第二个包
第五个包，从初始位置重新下载，到结束，正常。

虽然最终表现能完整播放，但启动播放时的体验，包下载的浪费还是存在优化空间。

**Comment by lipangit** [comment]
咱们这项目做的是ui和播放器的管理，具体播放器是怎么请求网络的怎么解码的并不知道。如果针对大项目还不行可以考虑一行代码替换成ijkplayer播放器引擎
