### ISSUE TITLE
播放视频时崩溃 请问怎么解决

### ISSUE THREAD

**Issue by hudafei1225** [lipangit/JiaoZiVideoPlayer#1407]
IJKMEDIA    Option ijkinject-opaque not found.
libc              Fatal signal 11 (SIGSEGV), code 2, fault addr 0xd8704997 in tid 9030 (Thread-1328)

**Comment by lipangit** [comment]
能复现吗，ijkplayer相关的可以到ijkplayer的项目里提问，上述log可能超出老臣解决范围
