### ISSUE TITLE
MIUI 9.1 Android 7.0 读取缓存异常

### ISSUE THREAD

**Issue by ZengJH** [lipangit/JiaoZiVideoPlayer#1408]
第一次播放正常
第二次播放错误提示（有可能是Android 7.0 新的文件读取权限体系导致）
![11111111](https://user-images.githubusercontent.com/5819040/33421963-e259dc3e-d5ee-11e7-8d50-969136d72ee6.png)

**Comment by lipangit** [comment]
对对，很有可能，有什么办法修改吗

但是记得我的安卓6.0红米note4测试的时候不是每次都能复现

**Comment by ZengJH** [comment]
@lipangit MediaPlayer内置逻辑不知道怎么处理的，EMUI5 同样也是Android7.0但是没有发现这个问题。简单处理的话，看看能不能关闭MediaPlayer读取缓存功能，不然就只能换播放器了。

**Comment by lipangit** [comment]
JZVideoPlayer.save_progress=false不保存每次的播放进度

android.media.MediaPlayer的缓存不知道怎么配置

**Comment by lipangit** [comment]
解决了吗
