### ISSUE TITLE
第一次点击全屏的时候,会崩掉.第二次点会正常全屏.

### ISSUE THREAD

**Issue by heigoo** [lipangit/JiaoZiVideoPlayer#1409]
E/BufferQueueProducer: [SurfaceTexture-0-8627-7] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-8627-7] dequeueBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-8627-7] connect: BufferQueue has been abandoned

Log日志打印这些.
第一次点击全屏的时候,会崩掉.第二次点会正常全屏.

**Comment by lipangit** [comment]
demo有这个问题吗，什么安卓版本，应该还有其他log

**Comment by heigoo** [comment]
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaPlayer.getDuration(Native Method)
W/System.err:     at cn.jzvd.d.g(JZMediaSystem.java:80)
W/System.err:     at cn.jzvd.c.e(JZMediaManager.java:72)
W/System.err:     at cn.jzvd.JZVideoPlayer.getDuration(JZVideoPlayer.java:917)
\W/System.err:     at cn.jzvd.JZVideoPlayer$b$1.run(JZVideoPlayer.java:1147)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

其他的log 都是正常的log. demo 没有,集成到我的项目里就出现了.(项目集成了友盟和腾讯IM)

**Comment by lipangit** [comment]
mediaPlayer被release的时候getDuration可能会报错，但是全屏的时候MediaPlayer不应该被release，断点一下mediaPlayer.release吧，看看是不是有地方把MediaPlayer release了

**Comment by heigoo** [comment]
@Override
//    public void onPause() {
//        super.onPause();
//        JZVideoPlayer.releaseAllVideos();
//    }

注掉这,就正常了....

**Comment by lipangit** [comment]
这样做退出页面视频还在播放

**Comment by xiaoxing1992** [comment]
是的  我也会出现了这种情况    楼主解决了吗
