### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by zhangshaobo87** [lipangit/JiaoZiVideoPlayer#1411]
1、在播放失败时候，点击重试 和 播放按钮 一起显示，是不是应该只显示点击重试按钮，隐藏播放按钮呢，感觉更合理些呢。应该是在JZVideoPlayerStandard的changeUiToError() 方法中设置的；
2、在缩略图和播放按钮的点击事件中，判断当前不是wifi连接会弹出提示框，但是没有判断当前有没有网络连接呀。我把网络关了，点击播放还是提示的当前用的是移动流量，实际上这个时候是没有网络的。

**Comment by lipangit** [comment]
试试新版本有没有这个问题cn.jzvd:jiaozivideoplayer:6.2.0_preview
这个版本的error ui 改成和头条一样的了

**Comment by 401885064** [comment]
哈哈，今天我也发现了第二个问题，还是没有区分处理   ------->   版本6.2.3

再提一个小建议:  showWifiDialog中参数action 应该区分start和retry  现在用的都是JZUserAction.ON_CLICK_START_ICON  我在做自定义UI时发现这里区分不了状态，囧！------->   版本6.2.3

**Comment by lipangit** [comment]
1.没有网络应该怎么提示，还要在没有网络判断是否播放本地

2.好的，区分star和retry的action

**Comment by lipangit** [comment]
不对 ，兄弟 @401885064 ON_CLICK_START_ERROR 这个就是retry，

![image](https://user-images.githubusercontent.com/2038071/34068743-cb83d3b8-e27b-11e7-83d8-febe60e62903.png)

**Comment by 401885064** [comment]
说的是  **showWifiDialog中参数action** 应该区分start和retry
