### ISSUE TITLE
播放rtsp摄像头，怎么切换硬解软解来播放？

### ISSUE THREAD

**Issue by tpnet** [lipangit/JiaoZiVideoPlayer#1412]
默认用的系统的MediaPlayer就是硬解， 用ijkPlayer就是软解， 是这样子吗？

**Comment by lipangit** [comment]
不是，必须硬解码，否则textureView不工作

**Comment by tpnet** [comment]
你好，是这样子的，，硬解和软解是这样子理解的吗：

 - 硬解，用自带播放器播放，android中的MeidaPlayer
 - 软解，使用音视频解码库，比如FFmpeg，

然后ijkPlayer就是基于FFMpeg的，然后在你的demo中， 点击CustomMediaPlayer里面的CHANGE TO IJKPLAYER切换为ijkPlyer，这时候不就是输入软解了吗？  我理解有问题吗，百思不得解

**Comment by tpnet** [comment]
@lipangit

**Comment by lipangit** [comment]
用ijkplayer也不能关闭硬解  至于ffmpeg是否就是软解我也在学习

**Comment by tpnet** [comment]
您说的硬解 ，是指硬件加速吧？ 

我说的是解码呢， 硬解是利用gpu。。。软解是利用cpu，例如ffmpeg  ，，/大哭

**Comment by Greathfs** [comment]
ijk支持硬解和软解切换 ijk硬解用的exoplayer中硬解 ,下面是设置
 ((IjkMediaPlayer) mMediaPlayer).setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER,
                            "mediacodec", 1);

**Comment by tpnet** [comment]
设置了，但是播放不了，画面变成了灰色。 @Greathfs

**Comment by lipangit** [comment]
解决了吗

**Comment by lipangit** [comment]
什么需求
