### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by marwa1994** [lipangit/JiaoZiVideoPlayer#1414]
i create a Custom VideoPlayer by extending JZVideoPlayerStandard i put it in my layout and i put this methods in my activity
@Override
```
public void onBackPressed() {
    if (JZVideoPlayer.backPress()) {
        return;
    }
    super.onBackPressed();
}
@Override
protected void onPause() {
    super.onPause();
    JZVideoPlayer.releaseAllVideos();
}
```
but always i get this error
**AndroidRuntime: FATAL EXCEPTION: JiaoZiVideoPlayer
                                                              Process: com.symane.btm, PID: 2820
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.release()' on a null object reference
                                                                  at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:151)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)**

**Comment by lipangit** [comment]
yes this is bug thank you to tell me

because this function not go into,I will fix it today you can set MediaPlayerInterface by hand
![image](https://user-images.githubusercontent.com/2038071/33522482-b9c2aca6-d828-11e7-8e17-76beb1e8bd90.png)

**Comment by marwa1994** [comment]
i try to create interface manually like you said but i got the same error

**Comment by lipangit** [comment]
fixed on 318c39b

**Comment by lipangit** [comment]
I am releasing new version now

**Comment by marwa1994** [comment]
when i'am trying to add the new version to my app i got this error *


Error:(218, 13) Failed to resolve: cn.jzvd:jiaozivideoplayer:6.2.1

**Comment by lipangit** [comment]
Yesterday maven warehouse can not upload many attempts, just upload success, can be used within 2 hours

**Comment by marwa1994** [comment]
ok thnx :)
