### ISSUE TITLE
最新版本 6.2.1 无法正常build？

### ISSUE THREAD

**Issue by alitong** [lipangit/JiaoZiVideoPlayer#1415]
Warning:The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Error:(195, 13) Failed to resolve: cn.jzvd:jiaozivideoplayer:6.2.1

**Comment by lipangit** [comment]
昨天maven仓库多次尝试无法上传，刚才才上传成功，2小时以内可以使用
