### ISSUE TITLE
刚开始时竖屏播放,播放器只是占界面的一小部分,点击播放器进行播放,这个点击事件怎么监听啊?希望各位大神有知道的可以解答一下,不胜感激.

### ISSUE THREAD

**Issue by lilyBeijing** [lipangit/JiaoZiVideoPlayer#1416]

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard 复写onClick函数，可以监听到播放器各种点击事件，复写onTouch函数可以监听到全屏后手势操作

**Comment by lilyBeijing** [comment]
大神,关于点击全屏按钮全屏播放后的状态栏是怎么设置的呢?我现在是在activity中放了一个高度是200dp的播放器,状态栏用的是透明的状态栏然后覆盖了一个纯色的view,点击全屏播放的时候这个纯色的view还是在界面上能看见,请问这个纯色的view的状态栏在全屏状态下怎么消除啊?求帮助啊,ps:我用的是很早之前的那个版本,引入的依赖是 compile 'fm.jiecao:jiecaovideoplayer:5.7'

**Comment by lipangit** [comment]
状态栏相关的设置就是显示和隐藏，没有其他的。只能设置这四中情况，全屏时候是显示或者隐藏，非全屏的时候是显示或者隐藏，没有其他的。

通过如下两个变量设置
![image](https://user-images.githubusercontent.com/2038071/33555620-0f554c32-d93c-11e7-8c63-d00698eabeda.png)
