### ISSUE TITLE
JZVideoPlayer.goOnPlayOnPause();报IllegalStateException

### ISSUE THREAD

**Issue by MorganGeng** [lipangit/JiaoZiVideoPlayer#1419]
在Activity中的onResume中调用了JZVideoPlayer.goOnPlayOnResume();onPause中调用了JZVideoPlayer.goOnPlayOnPause();此时,当因为网络等一些原因导致视频播放失败的情况下,直接响应onPause()的行为会导致应用崩溃.demo中可重现.

**Comment by lipangit** [comment]
如果做返回界面继续播放的功能，参考apiActivity

**Comment by MorganGeng** [comment]
是参照ActivityApi写的,正常播放的时候功能是ok的,但是点击播放如果播放失败了,就会出现我描述的问题,而且在下载的demo上也是会出现的.简单测试方法就是点击播放之前把网络关掉,点击播放后直接home键,必现

**Comment by lipangit** [comment]
好的，我研究一下

**Comment by lipangit** [comment]
fix on 038be5d7d97b809c43e1456297331d7d47055e73 今天发版

**Comment by wsty** [comment]
6.2.7发现此问题，出现机型：三星c7

**Comment by lipangit** [comment]
@wsty log是什么 有啥思路吗

**Comment by wsty** [comment]
@lipangit 
[jiaozilog.txt](https://github.com/lipangit/JiaoZiVideoPlayer/files/1836359/jiaozilog.txt)

**Comment by lipangit** [comment]
MediaPlayer不能pasue，多半是因为此时MediaPlayer是release的，断点一下，或者log，确认在pause之前是否MediaPlayer被release了

**Comment by wsty** [comment]
场景：页面A->页面A,同时finish掉自己,onResume中执行goOnPlayOnResume, onPause中执行goOnPlayOnPause, onDestroy中执行release,跳转的瞬间按home返回到桌面就会出现这个异常

**Comment by lipangit** [comment]
你是说在finish的过程中按home键，我试了半天，做不到这个操作，能录个小视频看看吗

**Comment by qinxianyuzou** [comment]
> 你是说在finish的过程中按home键，我试了半天，做不到这个操作，能录个小视频看看吗

7.0.4也出现这个问题，log提示下面这段代码中，CURRENT_JZVD.mediaInterface.pause();这一行为空。我是在recycleview播放的视频，但是有可能并没有视频在播放，然后home就会崩
`public static void goOnPlayOnPause() {
        if (CURRENT_JZVD != null) {
            if (CURRENT_JZVD.state == Jzvd.STATE_AUTO_COMPLETE ||
                    CURRENT_JZVD.state == Jzvd.STATE_NORMAL ||
                    CURRENT_JZVD.state == Jzvd.STATE_ERROR) {
                Jzvd.resetAllVideos();
            } else {
                ON_PLAY_PAUSE_TMP_STATE = CURRENT_JZVD.state;
                CURRENT_JZVD.onStatePause();
                CURRENT_JZVD.mediaInterface.pause();
            }
        }
    }`

**Comment by lipangit** [comment]
嗯
