### ISSUE TITLE
我重新设置onAudioFocusChangeListener 在全屏播放后，第一次点击播放 会触发 AudioManager.AUDIOFOCUS_LOSS_TRANSIENT

### ISSUE THREAD

**Issue by chapliny** [lipangit/JiaoZiVideoPlayer#1421]
这里设置
`
 case JZUserAction.ON_CLICK_RESUME:
                    
Log.i("USER_EVENT", "ON_CLICK_RESUME" + " title is : " + (objects.length == 0 ? "" : objects[0]) + " url is : " + url + " screen is : " + screen);
//                    if (mVideoPlayer.currentScreen != SCREEN_WINDOW_NORMAL) {
                        AudioManager mAudioManager = (AudioManager) mActivity.getSystemService(Context.AUDIO_SERVICE);
                        mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
//                    }
                    break;
`
即时我在pause的时候 去除 调用abandonAudioFocus 也不行，
且问题只在全屏后第一次，小屏是好的

**Comment by lipangit** [comment]
为什么这么设置，库里什么地方没满足你的需求。

切换全屏应该和焦点无关

**Comment by chapliny** [comment]
是因为我还有音频 播放香瓜你的内容，所以要切换

**Comment by chapliny** [comment]
点击音频播放后，暂停视频播放

**Comment by chapliny** [comment]
不好意思上面写错了

**Comment by lipangit** [comment]
你的需求是什么，能描述一下吗，为什么写这些代码

**Comment by chapliny** [comment]
一个界面里有音频 和视频，需要实现点击音频 视频播放暂停，点击视频继续播放，音频暂停。

**Comment by lipangit** [comment]
如果视频和音频都是在一个项目里，这里不建议发出系统的消息，直接操作音频暂停可能效果更好一些。

**Comment by chapliny** [comment]
嗯，这个也是可以的，谢谢。
