### ISSUE TITLE
recyclerView中使用Tiny窗口布局，item布局问题

### ISSUE THREAD

**Issue by lurenman** [lipangit/JiaoZiVideoPlayer#1425]
在recyclerView中使用Tiny窗口，在adapter Item布局中如果给JZVideoPlayerStandard多添加一个父布局，例如cardView等，就不会有Tiny窗口的效果

**Comment by lipangit** [comment]
断点一下onscroll的监听是否正常

**Comment by lipangit** [comment]
解决了吗
