### ISSUE TITLE
如何取消保存进度这个功能和强制全屏播放？

### ISSUE THREAD

**Issue by jwzywanasnli** [lipangit/JiaoZiVideoPlayer#1427]
我的项目没有小屏播放，点击视频连接直接进入全屏即可，较为简单。所以我用的方法是
JZVideoPlayerStandard.startFullscreen(getActivity(), JZVideoPlayerStandard.class,“xxxxxx.mp4”, "视频标题");

现在遇到两个问题
1.我希望每次进入视频都从头播放，不需要保存视频的进度。

2.我的APP是竖屏使用，目前当进入全屏播放时，也会竖屏播放，上下黑边，中间是个小视频，然后需要把手机横过来，才能通过重力感应切换到横屏全屏铺满的状态。这样比较麻烦。有什么办法能一进来就强制横屏铺满播放么？？？

期待大神大大的解答，拜谢。

**Comment by lipangit** [comment]
1.JZVideoPlayer.saveProgress=false

2.黑边问题参考demo的rotationAndSizeActvitiy(具体的名字忘记了)
