### ISSUE TITLE
FFSource getSize failed

### ISSUE THREAD

**Issue by Mardan123** [lipangit/JiaoZiVideoPlayer#1428]
您好，集成进去出现这样的问题，不知是我们url有误或者是别的isssue,iOS那边倒是正常,浏览器上也是正常。
url = https://munber.club/mPlatform/public/uploads/courseInfo/18/20171123/20171123175610.mp4
谢谢！

**Comment by Mardan123** [comment]
您好，集成进去出现这样的问题，不知是我们url有误或者是别的isssue,iOS那边倒是正常,浏览器上也是正常。
url = https://munber.club/mPlatform/public/uploads/courseInfo/18/20171114/20171114113422.mp4
谢谢！

**Comment by lipangit** [comment]
参考设置取消https验证试试 https://github.com/lipangit/JieCaoVideoPlayer/issues/655

**Comment by lipangit** [comment]
解决了吗
