### ISSUE TITLE
你好，请问为什么在一个ListView里，同一个视频点击前面的则后面的也跟着一起播放了？

### ISSUE THREAD

**Issue by safei37** [lipangit/JiaoZiVideoPlayer#1433]
如题，记得以前有见过这个问题，但是当时没有遇到就没有留意，现在这个问题好像找不到了，所以还请在告知一下，麻烦了。

**Comment by lipangit** [comment]
是不是他们的url相同，不允许url相同

**Comment by safei37** [comment]
是的。。。这个没办法了吗

**Comment by safei37** [comment]
我在VideoListAdapter里的getView修改：
if(! isPlay[position]){  //利用isPlay控制可否播放
            Picasso.with(convertView.getContext())
                    .load(videoThumbs[position])
                    .into(viewHolder.jzVideoPlayer.thumbImageView);
        }else{
            viewHolder.jzVideoPlayer.setUp(
                    videoUrls[position], JZVideoPlayer.SCREEN_WINDOW_LIST,
                    videoTitles[position]);
            Picasso.with(convertView.getContext())
                    .load(videoThumbs[position])
                    .into(viewHolder.jzVideoPlayer.thumbImageView);
        }
结果是前面6个item没有问题，第7个item（isPlay为false）开始就窜了，视频也窜标题也窜，窜的都是isPlay为false的item，这是怎么回事？如何修改才能达成我的目的，即用isPlay控制一些视频能播放一些不能播放

**Comment by lipangit** [comment]
isPlay是什么判断？
这段代码想要什么效果，你想要什么需求。

如果列表中url有一样的话，需要修改的东西特别多

**Comment by safei37** [comment]
现在不管url是否一样这个问题了：）
isPlay是用来判定是否播放的，如果为flase，则把
viewHolder.jzVideoPlayer.setUp(
videoUrls[position], JZVideoPlayer.SCREEN_WINDOW_LIST,
videoTitles[position]);
这段代码删去以实现不播放视频。。。。。。只保留Picasso。
结果就出现了上面的问题

**Comment by lipangit** [comment]
你的需求是什么，demo有吗，我还没弄明白你的修改是什么含义
