### ISSUE TITLE
compile 'cn.jzvd:jiaozivideoplayer:6.2.2'导入失败..  6.2.1可以

### ISSUE THREAD

**Issue by CXJean** [lipangit/JiaoZiVideoPlayer#1434]
[]
![a](https://user-images.githubusercontent.com/31038291/33793752-9f14f6f0-dcf8-11e7-98aa-eb65f27ad7d0.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/33793808-a30fc81a-dcf9-11e7-826b-6e84478ae16c.png)

上传不成功，特别卡，明天之前再试
