### ISSUE TITLE
当播放地址为空字符串时一直在加载

### ISSUE THREAD

**Issue by GirlFriendNotFind** [lipangit/JiaoZiVideoPlayer#1436]
请问下当播放地址为空字符串""时一直在加载，不进错误回调，因为直接用服务端返回的播放地址，如果为null直接报错，处理成空字符串不进错误回调，好像错误回调的监听很不方便，没找到类似setOnErrorListener的方法？

**Comment by GirlFriendNotFind** [comment]
播放地址为空通过在onClick里面判断解决了，但还是没找到类似setOnErrorListener的方法监听播放错误的各种状态(#^.^#)。。。。

**Comment by lipangit** [comment]
复写onError函数可以取得MediaPlayer的错误回调
