### ISSUE TITLE
关于设置隐藏视频界面

### ISSUE THREAD

**Issue by luoyou592** [lipangit/JiaoZiVideoPlayer#1437]
cn.jzvd.JZVideoPlayerStandard可以使该控件隐藏吗？有时个人主页是没有视频我得替换图片显示，所以想请问如何设置隐藏

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，参照demo的MyJZVideoPlayerStandard，复写相关函数，在各个状态中分别设置ui
