### ISSUE TITLE
视频暂停问题

### ISSUE THREAD

**Issue by SuperKung** [lipangit/JiaoZiVideoPlayer#1439]
使用 JZMediaManager.pause();方法暂停视频之后，视频确实暂停了，但是按钮还是播放状态，想要继续播放需要先按一下播放按钮变成暂停状态，然后再按一次才能继续播放

**Comment by lipangit** [comment]
这个只是暂停了MediaPlayer，ui并没有变化
可以jzvd.startButton.perfomClick()，模拟用户点击去暂停视频
