### ISSUE TITLE
如何重播视频

### ISSUE THREAD

**Issue by wodx521** [lipangit/JiaoZiVideoPlayer#1440]
1.使用
jzPlayer.setUp(weikeurl, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "热学复习指南");设置播放视频,配置文件中配置了横屏,点击了新链接播放视频会自动跳转到竖屏,我在newintent方法中添加了横屏的代码,出现点击后出现横竖屏切换情况,如何在点击新链接后还是横屏播放
2.在视频播放完后出现重播按钮,点击重播,同样会出现切换到竖屏的问题,就算是横屏也无法自动切回到横屏,如何设置自动重播且不会自动切回竖屏,(平板开发,应用是横屏的)

**Comment by lipangit** [comment]
参考demo的orientationActivity，分别设置全屏前和全屏后的屏幕方向。
