### ISSUE TITLE
How to catch event Control View dismiss

### ISSUE THREAD

**Issue by dungnguyendotme** [lipangit/JiaoZiVideoPlayer#1442]
How to catch event Control View dismiss.
I want to hide navigation bar (...) when the control view dismisses. 
Please help me. Thanks

**Comment by lipangit** [comment]
```
extends JZVideoPlayerStandard{
   @Override 
    onCLickUiToggleToClear(){
   }
}
```

**Comment by dungnguyendotme** [comment]
Can you describe more clearly? Thanks

**Comment by lipangit** [comment]
Override this function onCLickUiToggleToClear()  , you can catch control view visiblity event.

then you can do your work in that function.
