### ISSUE TITLE
1004，是什么错误

### ISSUE THREAD

**Issue by ZxxWaHa** [lipangit/JiaoZiVideoPlayer#1445]
1.你好，1004是什么错误
2.屏幕状态原本是横屏，点击全屏，然后缩小。变成了竖屏播放，请问可以在那里设置一下呢？

**Comment by lipangit** [comment]
1.io错误，这个的原因可能很多样
2.参考demo的orientationActivity，这个的例子是修改全屏前和全屏后的屏幕方向
