### ISSUE TITLE
加载视频时会先显示一下“视频加载失败，请点击重试”视图

### ISSUE THREAD

**Issue by ZHJ-30** [lipangit/JiaoZiVideoPlayer#1446]
在进入播放页加载视频时，会先出现如题所述视图，然后才出现进度条，正常加载视频。请问可能是什么原因呢？

**Comment by lipangit** [comment]
demo有这个问题吗？ 你做了什么修改吗

**Comment by ZHJ-30** [comment]
也没做什么修改呀，都是按照readme的步骤做的。
播放方法（JZVideoPlayerStandard mVideoPlayer）：
mVideoPlayer.setUp(url, JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, "测试视频");
mVideoPlayer.startButton.performClick();

**Comment by lipangit** [comment]
用法没有问题

demo有这个显示的bug吗

**Comment by ZHJ-30** [comment]
我的播放页面还有个webview，本来是加载视频时隐藏webview的。现在参照demo的ActivityWebView的做法不会出现上述问题了。但还是不明白怎么解决的，webview对JZVideoPlayerStandard 有什么影响吗

**Comment by lipangit** [comment]
他们应该互不相干的

1.标题的问题解决了吗
2.webView的你说的是什么问题？

**Comment by ZHJ-30** [comment]
我的问题就只有开始加载时先出现“视频加载失败，请点击重试”视图问题。
一开始的做法是参照demo的ActivityApi做的，会出现问题；
由于我的activity是有webview的，然后我看到demo也有个ActivityWebView，参照这个类做就没有问题了。
所以想知道是不是webview对JZVideoPlayerStandard有影响。
谢谢你的耐心回复！！

**Comment by lipangit** [comment]
问题解决了就好
