### ISSUE TITLE
一个空指针问题

### ISSUE THREAD

**Issue by artzok** [lipangit/JiaoZiVideoPlayer#1448]
java.lang.NullPointerException
Attempt to read from null array

1 cn.jzvd.JZUtils.java.lang.Object getCurrentFromDataSource(java.lang.Object[],int)(JZUtils.java:152)
--
2 cn.jzvd.JZVideoPlayerStandard.void onClick(android.view.View)(JZVideoPlayerStandard.java:336)
3 android.view.View.performClick(View.java:5317)
4 android.view.View$PerformClick.run(View.java:21648)
5 android.os.Handler.handleCallback(Handler.java:815)
6 android.os.Handler.dispatchMessage(Handler.java:104)
7 android.os.Looper.loop(Looper.java:207)
8 android.app.ActivityThread.main(ActivityThread.java:5932)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
11 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:816)

**Comment by lipangit** [comment]
传参数setUp有什么问题吧

**Comment by mmmlee** [comment]
我也遇到这样的问题，一直报空指针

**Comment by mmmlee** [comment]
JZUtils是添加本地视频的吗？

**Comment by lipangit** [comment]
传的什么参数，哪个变量是urll
