### ISSUE TITLE
Can't your support for the subtitle?

### ISSUE THREAD

**Issue by anhbinhvodanh** [lipangit/JiaoZiVideoPlayer#145]
Thank you again for this library. It helps me very much.

**Comment by lipangit** [comment]
Sorry recently played Overwatch addicted, to keep you waiting, nor how the library update.

What is subtitle , do you have demo about subtitle, I should learn it first.

**Comment by anhbinhvodanh** [comment]
Oh, there's nothing to apologize @@. You did a good library already.
[https://en.wikipedia.org/wiki/Subtitle_(captioning)](url)
Thank for your help.

**Comment by Hitexroid** [comment]
i need to read and show subtitle on video

please add this  feature

**Comment by lipangit** [comment]
Yes , this is a useful feature , I am researching other fullscreen function now, this feature has been delay.

**Comment by Hitexroid** [comment]
Thank you so much 
Your video player is amazing.

but remain subtitle support

**Comment by anhbinhvodanh** [comment]
Has any information on this feature yet?
As I know, this feature has been on ExoPlayer.
Can you implement it?

**Comment by lipangit** [comment]
Exoplayer is already in this project.

**Comment by anhbinhvodanh** [comment]
Yes, i know. But we can use it now?

**Comment by anhbinhvodanh** [comment]
Here is the example for using subtitle in exoplayer:
https://github.com/bluemix/CinemanaPlayer
Hope you implement it soon.
Thank so much.

**Comment by lipangit** [comment]
@anhbinhvodanh  I will study it as soon as possible, and you can pull request with subtitle.
