### ISSUE TITLE
直接全屏播放时,弹出是否使用流量窗口时选择不用流量时,播放页面无法消失.

### ISSUE THREAD

**Issue by xudongjian233** [lipangit/JiaoZiVideoPlayer#1450]
已自行解决,解决方案大概描述一下以供参考.
声明一个布尔值flag默认值为true,在是否使用流量dialog选择否或取消时,给flag赋值false,在backPress的时候判断flag,如果为true让播放页面消失,并给flag赋值true.backPress中加的代码
        if (FLAG_NO_4G) {
            JZVideoPlayerManager.setFirstFloor(mJZVideoPlayer);
            quitFullscreenOrTinyWindow();
            FLAG_NO_4G = false;
            return true;
        }
ps:直接写quitFullscreenOrTinyWindow();的话会报JZVideoPlayerManager的getFirstFloor方法空指针,所以在前一行我加了setFirstFloor.
mJZVideoPlayer为startFullscreen方法里生成的JZVideoPlayer对象

**Comment by lipangit** [comment]
已经修复，忘了是什么时候
