### ISSUE TITLE
it is not loading video when i use in dragpannel.

### ISSUE THREAD

**Issue by kongxiangjia305** [lipangit/JiaoZiVideoPlayer#1452]
<com.github.pedrovgs.DraggableView
                xmlns:draggable_view="http://schemas.android.com/apk/res-auto"
                android:id="@+id/draggable_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                draggable_view:bottom_view_id="@+id/recycler_view"
                draggable_view:top_view_id="@+id/jz_video"
                draggable_view:top_view_margin_bottom="@dimen/margin_bottom"
                draggable_view:top_view_margin_right="@dimen/top_fragment_margin"
                draggable_view:top_view_x_scale_factor="@dimen/x_scale_factor"
                draggable_view:top_view_y_scale_factor="@dimen/y_scale_factor">

                

                <android.support.v7.widget.RecyclerView
                    android:id="@+id/recycler_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_below="@+id/jz_video"
                    android:background="@color/white"
                    app:layout_behavior="@string/appbar_scrolling_view_behavior" />

               
                        <com.lightwater.youtu.CustomView.MyJZVideoPlayerStandard
                            android:id="@+id/jz_video"
                            android:visibility="gone"
                            android:layout_width="match_parent"
                            android:layout_height="200dp"
                            android:background="@color/black" />

            </com.github.pedrovgs.DraggableView>

**Comment by lipangit** [comment]
Do you mean you click startButton, the video will not play?

Em I think you can Remove complicated decoration, just simple draggableView -> MyJZVideoPlayerStandard  to find out the problem
