### ISSUE TITLE
音频焦点问题和视频播放中切换播放视频问题

### ISSUE THREAD

**Issue by ZHJ-30** [lipangit/JiaoZiVideoPlayer#1454]
1. 在播放视频的时候进行语音对话，语音合成播放时，视频会暂停播放，但对应暂停状态按钮没有出现，视频仍是播放视图。

2. 失去音频焦点时能不能不做处理，由我自己进行视频播放控制。

3. 在视频播放中，选择播放另一个视频该如何实现？直接setUp(otherUrl, ...)会显示“视频加载失败，请重试”视图，无法播放。

**Comment by lipangit** [comment]
1.已经修复，是个bug
2.失去音频焦点是什么意思？是有其他app的声音打断jzvd的意思吗
3.参考demo apiActivity的修改清晰度的代码

**Comment by ZHJ-30** [comment]
问题都已解决，谢谢解惑
