### ISSUE TITLE
这个视频播放五秒就会卡在那，拖拽下进度条才能播放

### ISSUE THREAD

**Issue by gangqihong** [lipangit/JiaoZiVideoPlayer#1458]
http://zygs.fzmt.com.cn:18400/glaf/upload/20171215/20171215153606942.mp4

**Comment by lipangit** [comment]
我试试

**Comment by lipangit** [comment]
我觉得服务器特别慢，应该是网速的问题

**Comment by 401885064** [comment]
网页打开也这样    显然是服务器问题或是视频有问题  跟JiaoZiVideoPlayer无关
