### ISSUE TITLE
视频播放异常

### ISSUE THREAD

**Issue by 867588763** [lipangit/JiaoZiVideoPlayer#1460]
地址：
http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/bpd005101i01_5a2d4cdab7ae6842173495jj7rxwxsiu.mp4

日志如下

12-15 16:47:42.600 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onStateNormal  [213416975] 
12-15 16:47:42.602 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onClick start [213416975] 
12-15 16:47:42.602 8699-8699/org.zlms.lms D/JieCaoVideoPlayer: startVideo [213416975] 
12-15 16:47:42.603 8699-8699/org.zlms.lms D/JieCaoVideoPlayer: addTextureView [213416975] 
12-15 16:47:42.605 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onStatePreparing  [213416975] 
                                                               
                                                               [ 12-15 16:47:42.605  8699: 8699 I/         ]
12-15 16:47:42.652 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onSurfaceTextureAvailable [64018651] 
12-15 16:47:43.667 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onSurfaceTextureSizeChanged [64018651] 
12-15 16:47:44.288 8699-8699/org.zlms.lms E/JieCaoVideoPlayer: onError 1 - -2147483648 [213416975] 
12-15 16:47:44.288 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onStateError  [213416975] 
12-15 16:47:44.362 8699-8699/org.zlms.lms D/JieCaoVideoPlayer: releaseAllVideos
12-15 16:47:44.362 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onCompletion  [213416975] 
12-15 16:47:44.362 8699-8699/org.zlms.lms I/JieCaoVideoPlayer: onStateNormal  [213416975] 
12-15 16:47:44.646 8699-8699/org.zlms.lms D/JieCaoVideoPlayer: releaseAllVideos

**Comment by lipangit** [comment]
兄弟，你现在是什么版本，不是jiecao了 改成jiaozi了，升级一下先

**Comment by 867588763** [comment]
最新版也不行
地址：http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/bpd005101i01_5a2d4cdab7ae6842173495jj7rxwxsiu.mp4

下面是日志
12-15 17:31:03.177 27696-27731/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
12-15 17:31:03.203 27696-27733/? I/Adreno: QUALCOMM build                   : 4bec611, Icdeec648e3
                                           Build Date                       : 08/01/17
                                           OpenGL ES Shader Compiler Version: XE031.14.00.04
                                           Local Branch                     : 
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
12-15 17:31:03.204 27696-27733/? I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
12-15 17:31:03.206 27696-27733/? I/OpenGLRenderer: Initialized EGL, version 1.4
12-15 17:31:03.206 27696-27733/? D/OpenGLRenderer: Swap behavior 1
12-15 17:31:05.138 27696-27696/? I/JiaoZiVideoPlayer: onClick start [246690428] 
12-15 17:31:05.139 27696-27696/? D/JiaoZiVideoPlayer: startVideo [246690428] 
12-15 17:31:05.139 27696-27696/? D/JiaoZiVideoPlayer: addTextureView [246690428] 
12-15 17:31:05.141 27696-27696/? I/JiaoZiVideoPlayer: onStatePreparing  [246690428] 
12-15 17:31:05.142 27696-27696/? I/USER_EVENT: ON_CLICK_START_ICON title is : 饺子快长大 url is : http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/bpd005101i01_5a2d4cdab7ae6842173495jj7rxwxsiu.mp4 screen is : 0
12-15 17:31:05.153 27696-27696/? I/JZResizeTextureView: onMeasure  [62897506] 
12-15 17:31:05.153 27696-27696/? I/JZResizeTextureView: onMeasure  [62897506] 
12-15 17:31:05.156 27696-27696/? I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [246690428] 
12-15 17:31:05.158 27696-27727/? E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-15 17:31:05.158 27696-27727/? E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-15 17:31:05.161 27696-27727/? W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-15 17:31:05.166 27696-27727/? W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-15 17:31:05.958 27696-27796/cn.jzvd.demo W/MediaHTTPConnection: readAt 12271271 / 32768 => java.net.ProtocolException
12-15 17:31:06.626 27696-27796/cn.jzvd.demo W/MediaHTTPConnection: readAt 12271271 / 32768 => java.net.ProtocolException
12-15 17:31:06.631 27696-27796/cn.jzvd.demo E/MediaPlayer: error (1, -2147483648)
12-15 17:31:06.632 27696-27727/cn.jzvd.demo E/MediaPlayer: Error (1,-2147483648)
12-15 17:31:06.632 27696-27696/cn.jzvd.demo E/JiaoZiVideoPlayer: onError 1 - -2147483648 [246690428] 
12-15 17:31:06.632 27696-27696/cn.jzvd.demo I/JiaoZiVideoPlayer: onStateError  [246690428] 
12-15 17:31:07.711 27696-27696/cn.jzvd.demo D/JiaoZiVideoPlayer: addTextureView [246690428] 
12-15 17:31:07.711 27696-27696/cn.jzvd.demo I/JiaoZiVideoPlayer: onStatePreparing  [246690428] 
12-15 17:31:07.712 27696-27696/cn.jzvd.demo I/USER_EVENT: ON_CLICK_START_ERROR title is : 饺子快长大 url is : http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/bpd005101i01_5a2d4cdab7ae6842173495jj7rxwxsiu.mp4 screen is : 0
12-15 17:31:07.723 27696-27696/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [119331813] 
12-15 17:31:07.723 27696-27696/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [119331813] 
12-15 17:31:07.724 27696-27696/cn.jzvd.demo I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [246690428] 
12-15 17:31:07.726 27696-27727/cn.jzvd.demo E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-15 17:31:07.726 27696-27727/cn.jzvd.demo E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-15 17:31:07.726 27696-27727/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-15 17:31:07.728 27696-27727/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-15 17:31:08.479 27696-27709/cn.jzvd.demo W/MediaHTTPConnection: readAt 12271271 / 32768 => java.net.ProtocolException
12-15 17:31:09.125 27696-27709/cn.jzvd.demo W/MediaHTTPConnection: readAt 12271271 / 32768 => java.net.ProtocolException
12-15 17:31:09.129 27696-27709/cn.jzvd.demo E/MediaPlayer: error (1, -2147483648)
12-15 17:31:09.130 27696-27727/cn.jzvd.demo E/MediaPlayer: Error (1,-2147483648)
12-15 17:31:09.130 27696-27696/cn.jzvd.demo E/JiaoZiVideoPlayer: onError 1 - -2147483648 [246690428] 
12-15 17:31:09.130 27696-27696/cn.jzvd.demo I/JiaoZiVideoPlayer: onStateError  [246690428]

**Comment by 867588763** [comment]
上面的地址服务器删除了
下面这个地址播放也是异常
http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/bls025101i04_5a2d48f9c649c494741256cmpvujriag.mp4

**Comment by lipangit** [comment]
老铁 下面的文件也不存在

**Comment by 867588763** [comment]
现在这个视频能播放了，但是不能拖动，一拖动就播放失败

http://scau.jingjichang.com.cn/lms_data/huanong/storage/media/fms/BPD005101I01___5a339c8f2429c306648290k52eu74fnk.mp4

**Comment by 867588763** [comment]
我怀疑是视频文件的问题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34139440-c4d790d2-e4af-11e7-9ef1-922e7efc98b5.png)

拖动进度时出现如下log，1004是io问题，服务器感觉不对，直接用tomcat放到文件夹里都能正常播放
