### ISSUE TITLE
在播放视频的时候使用Viewdraphelper拖动控件时，由于一直刷新UI，导致拖动不了，怎么解决？

### ISSUE THREAD

**Issue by monkeywiiu** [lipangit/JiaoZiVideoPlayer#1462]

**Comment by lipangit** [comment]
刷新ui 是什么意思，是不是事件被jzvd拦截了？可以到ViewDragHelper项目中问问

**Comment by monkeywiiu** [comment]
我自定义了一个可拖动的悬浮按钮，播放视频拖动会自动回到原来位置。 好像是播放视频会刷新进度条的锅

**Comment by lipangit** [comment]
可以抽象一个直接能运行的项目出来，把代码发给我，给你调试一下

**Comment by monkeywiiu** [comment]
https://github.com/monkeywiiu/videotest 我希望播放视频时那个悬浮按钮可自由拖动，谢谢大佬指点

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34079398-ee9691a0-e367-11e7-91f2-c0bad0b5193f.png)
![image](https://user-images.githubusercontent.com/2038071/34079400-f34a9d68-e367-11e7-9545-3eafcd356539.png)

**Comment by lipangit** [comment]
经过测试发现，只要他们不嵌套就不会互相影响，但是效果有问题

至于为什么你可以断点设置按钮的位置的代码

**Comment by monkeywiiu** [comment]
又测试了一下，发现底部的进度条不动的时候能正常拖动，应该和getcurrentposition这个方法有关

**Comment by lipangit** [comment]
怎么改的我试试，还用那个项目

**Comment by monkeywiiu** [comment]
不嵌套布局，然后再把snakebuttonlayout的事件分发代码改了一下，就能实现效果了，没改jiaozivideoplayer。之前那个项目不小心删了，有git了一个https://github.com/monkeywiiu/videotest

**Comment by monkeywiiu** [comment]
![qq 20171218191723](https://user-images.githubusercontent.com/26477834/34103575-283b8cb0-e428-11e7-8a72-399b0b5aa228.png)

**Comment by lipangit** [comment]
能解决就好了，我就不试了

另外建议你在build.gradle引入jzvd，别直接引入代码，这样咱们这个库升级的时候会很麻烦
