### ISSUE TITLE
点击后一直在加载

### ISSUE THREAD

**Issue by Wkingforever** [lipangit/JiaoZiVideoPlayer#1464]
我集成了Rong Cloud sdk 在聊天室，重写了listview中的item ，在点击后一直在加载，显示一个圈圈在转动， 就是没有播放， 打印了融云的log 显示如下：
I/JiaoZiVideoPlayer(26509): onClick start [911738301]
D/JiaoZiVideoPlayer(26509): startVideo [911738301]
D/JiaoZiVideoPlayer(26509): addTextureView [911738301]
I/JiaoZiVideoPlayer(26509): onStatePreparing  [911738301]
I/JiaoZiVideoPlayer(26509): onSurfaceTextureAvailable [911738301]

**Comment by lipangit** [comment]
onSurfaceTextureAvailable 的下一步就是new mediaPlayer，断点MediaPlayer是否启动？网络是不是有问题，总之问题应该出在MediaPlayer上

**Comment by lipangit** [comment]
应该还有log 看看有没有error之类的log

**Comment by Wkingforever** [comment]
I/MediaFocusControl( 2218):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@286929dacn.jzvd.JZVideoPlayer$1@38236e0b
I/MediaFocusControl( 2218):  AudioFocus  requestAudioFocus() from android.media.AudioManager@12653f44cn.jzvd.JZVideoPlayer$1@38236e0b req=2flags=0x0
E/MediaPlayer-JNI(30109): QCMediaPlayer mediaplayer NOT present
W/MediaPlayer(30109): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
W/System.err(30109):    at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:44)
W/System.err(30109):    at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:145)
W/System.err(30109):    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1086)
W/System.err(30109):    at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1060)
W/MediaPlayer(30109): setScreenOnWhilePlaying(true) is ineffective for Surface
W/ActivityManager( 2218): Scheduling restart of crashed service com.mephone.fonts/com.turtle.mediadown.parse.MonitorService in 1000ms
I/ActivityManager( 2218): Start proc 3295:com.mephone.fonts/u0a76 for service com.mephone.fonts/com.turtle.mediadown.parse.MonitorService
Media 似乎没有被启动i起来，这是为什么

**Comment by lipangit** [comment]
url是什么

**Comment by Wkingforever** [comment]
http://test.0511mzone.com/upload/2017-12-16/upload_1602456718.mp4

**Comment by lipangit** [comment]
查看权限加了吗，我刚才测试没有问题
