### ISSUE TITLE
小米手机使用seekToInAdvance出现错乱

### ISSUE THREAD

**Issue by AwinHe** [lipangit/JiaoZiVideoPlayer#1466]
小米手机使用seekToInAdvance设置开始播放视频的时间，这个时间和视频时间对不上，会出现多几百毫秒和少几百毫秒播放视频的情况，目前我用小米Note3和红米Note3测试都有这个问题，用魅族华为oppo都没有这个问题

**Comment by lipangit** [comment]
是的，确实有这个问题并且暂时解决不了，在短视频上会出现这个问题，暂时没办法解决，一直保持关注。

**Comment by maxiaoxu2017** [comment]
这个问题现在还有

**Comment by lipangit** [comment]
这是视频关键帧的问题，普通的seekTo进度也会出现进度往前的状况

**Comment by AnYuer** [comment]
跪求解决这个问题，我现在也是遇到这个问题，完全不能正常统计时长。seekto时间往前推了十几秒。跪求帮忙解决这个问题

**Comment by lipangit** [comment]
这个问题是视频的通病，微博也是这样，一个10秒的视频，seekTo到8秒，他会从0秒或者2秒开始播放。
