### ISSUE TITLE
这个库不支持缓冲视频吗

### ISSUE THREAD

**Issue by 1130381752** [lipangit/JiaoZiVideoPlayer#1467]
如题，这个库不支持缓冲视频吗

**Comment by lipangit** [comment]
视频缓存和播放器引擎有直接关系，android.media.MediaPlayer是系统的播放器，它对缓存的支持和安卓版本有关系，没有api配置。ijkplayer是ffmpeg blibli的播放器引擎，可以查看他的文档。

**Comment by 1130381752** [comment]
好的，谢谢答复
