### ISSUE TITLE
Recycler频繁增加新内容后崩溃

### ISSUE THREAD

**Issue by blankcw** [lipangit/JiaoZiVideoPlayer#1468]
`E/ActivityThread: Activity com.blankcw.example.neihan.MainActivity has leaked IntentReceiver cn.jzvd.JZVideoPlayerStandard$1@2a6b5ae that was originally registered here. Are you missing a call to unregisterReceiver()?
`
添加了下拉刷新和上拉加载功能后，从网络获取视频源，上拉到底部后新增入更多数据，加载到200左右的videoplayer后崩溃，是否需要对较早声明的数据源videoplayer进行unregisterReceiver?

**Comment by lipangit** [comment]
jzvd的哪个部分需要回收吗？研究一下jzvd里的哪个东西出了问题，这就是个普通的layout，没有回收的概念吧

**Comment by 401885064** [comment]
@blankcw 说的是battertReceiver部分吧     这个确实会在setup时候注册  难道一直没收到广播导致没有释放资源？   @lipangit

**Comment by lipangit** [comment]
这块的逻辑是注册一次广播，收到广播的信息之后马上就会注销广播，可能同一时间注册的多了会出问题，现在修改了吗，可以分享一下你的方案吗？这确实是个问题

**Comment by 401885064** [comment]
@lipangit   我直接屏蔽掉这部分代码  因为不用这部分功能    哈哈哈哈

**Comment by lipangit** [comment]
屏蔽掉是省事的，我正在研究它的内存的使用的问题，这个问题应该修改的
