### ISSUE TITLE
你好  邮件没有回复成功，只能在这里沟通了

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1471]
其实就是这种  我想点击播放按钮 发送  已经观看请求  根据position获取字段id  但是获取的position确是   1.。22 33这种   mVideoPlay.setUp(mList.get(position).getNewsurl().trim(), JZVideoPlayer.SCREEN_LAYOUT_LIST,）这种类型应该没关系吧？按钮是否点击我是通过这个进行处理的？应该没问题是吧？
JZVideoPlayer.setJzUserAction(new JZUserActionStandard() {

        @Override
        public void onEvent(int type, String url, int screen, Object... objects) {
            switch (type) {
                case JZUserAction.ON_CLICK_START_ICON:
default:

**Comment by guoyongxing** [comment]
可以做个类是天猫商品搜索时预加载的功能吗？什么意思？

**Comment by lipangit** [comment]
position必须是listView中item的position，否则列表滑动会有问题

setJzUserAction这个你说的是什么意思？他们是一个问题吗

**Comment by guoyongxing** [comment]
就是我要监听  播放啊  所以我就用setJzUserAction这个静态方法    case JZUserAction.ON_CLICK_START_ICON:这个方法不是播放按钮点击了  我在这里面根据position获取数据的

**Comment by lipangit** [comment]
这个只是给埋点统计用的不能写播放器相关的逻辑，如果想取得播放开始的事件，可以参照下图

![image](https://user-images.githubusercontent.com/2038071/34139636-b9f469be-e4b0-11e7-81f7-fa0fc864b135.png)

**Comment by guoyongxing** [comment]
这个我之前  注意到了  可是这个和adapter能挂上么？我希望  点击播放按钮  获取我点击的位置啊？onStartNormarl和那个onClick应该没用是吧？

**Comment by guoyongxing** [comment]
OK  问题解决了

**Comment by guoyongxing** [comment]
那个 怎么能和adapter中的数据挂上呢？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34161704-691b1bee-e50c-11e7-9bd9-6ac2aeae1d8b.png)

这样设置怎么会跑偏呢

**Comment by guoyongxing** [comment]
我用的是6.1.1这个版本    JZVideoPlayer.SCREEN_LAYOUT_LIST 应该没问题吧？
  JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;  //横向
                        newsVideoViewHolder.mVideoPlay.setUp(mList.get(position).getNewsurl().trim(), JZVideoPlayer.SCREEN_LAYOUT_LIST, mList.get(position).getNewstitle().trim());
                        newsVideoViewHolder.mVideoPlay.positionInList=position;
我之前没有把最后一行赋值给position  我想再点击播放按钮时  获取对应的Position  可是再哪里面获取监听呢？

**Comment by guoyongxing** [comment]
比如说 我想点击item  发送个点击请求  
![image](https://user-images.githubusercontent.com/16640088/34188865-82784ac8-e573-11e7-9504-b523c6ab27db.png)
这个点击事件包括  imageView缩略图的点击 和播放按钮的点击么？那么 再getView方法中  根据position获取的数据怎么能通过点击事件回调到activity中呢？

**Comment by lipangit** [comment]
1.所有控件，当然包括，if(i==控件id）{相应id的事件}

2.setUp函数中最后一个参数是objects，把参数传到jzvd里面来，然后在jzvd中写自己的逻辑

**Comment by guoyongxing** [comment]
newsVideoViewHolder.mVideoPlay.setUp(mList.get(position).getNewsurl().trim(), JZVideoPlayer.SCREEN_WINDOW_LIST, mList.get(position).getNewstitle().trim(),position);
我最后一个参数  可以这样写是吧 ？title和position  那么我在jzvd怎么获取传递过来的数据呢？

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，里面的objects变量就是你传进来的变量

**Comment by guoyongxing** [comment]
![image](https://user-images.githubusercontent.com/16640088/34193635-b4505308-e58f-11e7-8629-eebb6e6b105a.png)
是的 可是这个继承JZVideoPlayerStandard的类中 在哪怎么获取object

**Comment by guoyongxing** [comment]
ok  ok  之前不知道  setup中那个object[]还有这个作用  我之前只是纳闷 为甚用这个类型    刚才 我以为是通过getxxxx获取object[]  结果get一堆 没有   无意间打个object[]   获取到了    明白了明白了 这就可以走通了。

**Comment by guoyongxing** [comment]
完美解决了
