### ISSUE TITLE
WindowTiny开启全屏播放后的问题

### ISSUE THREAD

**Issue by blank-space** [lipangit/JiaoZiVideoPlayer#1474]
1. 我在Activity中设置的是横屏，但是在小窗口点击全屏播放，或被强制转为竖屏播放
2.想再点击返回键或缩小按钮的时候回到小窗口，但是被直接关闭了

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34139488-0f3154ce-e4b0-11e7-8203-31ba45a06f10.png)

1.这两个变量ko控制全屏前和全屏后的屏幕方向，全局变量随时修改切换的时候随时生效


2.从小窗进入全屏的我还没试过，现在jzvd的跳转只支持两层，普通窗口、小窗、全屏如果想随意跳转的话可能需要修改这里
![image](https://user-images.githubusercontent.com/2038071/34139559-66219942-e4b0-11e7-82c9-afbf14621ab6.png)
