### ISSUE TITLE
在使用小米4,安卓版本4.4时候出现error (1, -2147483648),不能播放直接视频加载失败

### ISSUE THREAD

**Issue by smc703** [lipangit/JiaoZiVideoPlayer#1476]
2-19 18:04:22.584 16121-16121/smc.com.myapplication I/JZResizeTextureView: onMeasure  [1125391120] 
12-19 18:04:22.584 16121-16121/smc.com.myapplication I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [1123214504] 
12-19 18:04:22.584 16121-16138/smc.com.myapplication E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
12-19 18:04:22.584 16121-16138/smc.com.myapplication W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-19 18:04:22.594 16121-16138/smc.com.myapplication W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-19 18:04:22.894 16121-16133/smc.com.myapplication E/MediaPlayer: error (1, -2147483648)
12-19 18:04:22.894 16121-16138/smc.com.myapplication E/MediaPlayer: Error (1,-2147483648)
12-19 18:04:22.894 16121-16121/smc.com.myapplication E/JiaoZiVideoPlayer: onError 1 - -2147483648 [1123214504] 
12-19 18:04:22.894 16121-16121/smc.com.myapplication I/JiaoZiVideoPlayer: onStateError  [1123214504]

**Comment by lipangit** [comment]
地址发来看看，我试试

**Comment by smc703** [comment]
http://tongzhuo-live-save.oss-cn-shanghai.aliyuncs.com/flv/2017-12-12/tongzhuomic01/f8f5f71ab61bd5ce2695e864470a24_studentvideopc_1591190_1513067546/2017-12-12-16%3A32%3A28_2017-12-12-17%3A25%3A05.flv
主要是在小米4,安卓版本4.4上,我这边其他的机型基本没问题

**Comment by smc703** [comment]
http://tongzhuo-live-save.oss-cn-shanghai.aliyuncs.com/flv/2017-12-12/tongzhuomic01/f8f5f71ab61bd5ce2695e864470a24_studentvideopc_1591190_1513067546/2017-12-12-16%3A32%3A28_2017-12-12-17%3A25%3A05.flv
主要是在小米4,安卓版本4.4上,我这边其他的机型基本没问题

**Comment by smc703** [comment]
oppor9s安卓版本6.0.1也出现了

**Comment by lipangit** [comment]
https://developer.android.com/guide/topics/media/media-formats.html
系统的播放器引擎不支持flv

你可以一键切换播放器引擎

**Comment by iHaiderAli** [comment]
Video is still not playing in KitKat version. can you help me here how to fix this issue 
E/MediaPlayer: error (1, -2147483648) 

This url is in mp4 format and video is playing on all the version except KitKat.
http://player.vimeo.com/external/173760795.sd.mp4?s=df90b9144f4cdaabb80111c611043fe210cfe723&profile_id=164&oauth2_token_id=941618064

**Comment by lipangit** [comment]
This url is redirect url, maybe android4.4 not support redirect

**Comment by iHaiderAli** [comment]
Video view is playing from this url but JZVP not playing so may the issue is with videoplayer, if you can diagnose this problem, i'll be very thankful to you.

**Comment by lipangit** [comment]
This url can not play in videoView, what did you do?

this url can not play by ijkplayer, you should change the video server.
