### ISSUE TITLE
播放本地视频文件偶尔会发生视频卡住并一直输出log的情况.

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [lipangit/JiaoZiVideoPlayer#1478]
![5qy sh 73n8c0jko1q 0d](https://user-images.githubusercontent.com/19187129/34197259-99c11098-e5a0-11e7-8412-2f56c0613807.png)
输出的log见上图.
使用版本是 6.2.3, 发生在 Android4.4版本下, 播放本地的MP4视频文件. 直接卡在了视频某一帧数, 反复抖动.

**Comment by lipangit** [comment]
保持关注，应该是这个安卓版本的MediaPlayer有bug吧

**Comment by Android-AwesomeRoy** [comment]
@lipangit  关于这个问题, 我尝试把 `SAVE_PROGRESS` 设置为 `false` 似乎没有再发生过了.

**Comment by lipangit** [comment]
这是个bug，就是说在开始播放的时候seek进度会出问题，还需要调试调试
