### ISSUE TITLE
从第三方软件返回播放界面的时候，出现黑屏

### ISSUE THREAD

**Issue by Ocesdi** [lipangit/JiaoZiVideoPlayer#1479]
楼主你好，在我的播放器界面里添加了视频详情信息，信息里涉及到一些超链接，进入第三方平台的。当我从第三方平台返回的时候的，我的播放界面出现黑屏。这个问题该怎么处理呢？请楼主给予帮助，谢谢。

**Comment by lipangit** [comment]
进入第三方平台应该进入了activity的onPause的方法

参考demo的activityApi，进入其他页面之后返回可以继续播放

**Comment by Ocesdi** [comment]
问题已解决！非常感谢！

2017-12-21 7:21 GMT+01:00 Nathen <notifications@github.com>:
