### ISSUE TITLE
进度条的问题

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1480]
可以让水平填充满么  有的 能水平充满 有的不能  这个和视频源有关系是么？另外  当网络缓慢时  怎么让进度条显示呢？

**Comment by lipangit** [comment]
水平填满是什么意思，你的需求是什么，demo不能满足你需求的地方是什么

如果想修改ui的话参考demo的ActvityApiSmallChangeUI，修改ui

**Comment by guoyongxing** [comment]
![120261568272434117](https://user-images.githubusercontent.com/16640088/34243382-73cb7106-e65b-11e7-834f-bdb7aa0de32e.jpg)
就是这种情况   左右还有一部分没有填满？另外当视频正在缓冲的时候能让圆形进度条显示  ？

**Comment by guoyongxing** [comment]
看着像宽高比  不够似的   我试了  4:3 和16:9  也水平填充不满  应该是宽高比不够是吧？

**Comment by lipangit** [comment]
这个截图中看不出有什么问题，进度条宽度如果填满了和时间的textview不是连上了吗？

这个ui和今日头条的ui一模一样，布局、颜色、按钮图片，都是从他们的apk里复制出来的，请放心使用

**Comment by guoyongxing** [comment]
对不起  是我说错了   我说的哪个是圆形进度条  当已经播放一段时间了   由于 网络缓慢的原因  需要显示一个圆形进度条  在那转  当正常播放  圆形进度条消失了   有点像加载动画类似的！

**Comment by guoyongxing** [comment]
还有一个  就是  在横屏的时候  我点击返回键 和底下右下角的那个按键  崩溃了   错误定位在  backpress()那了 if (JZVideoPlayerManager.getSecondFloor() != null) {
//            CLICK_QUIT_FULLSCREEN_TIME = System.currentTimeMillis();
//            if (JZUtils.dataSourceObjectsContainsUri(JZVideoPlayerManager.getFirstFloor().dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
//                JZVideoPlayer jzVideoPlayer = JZVideoPlayerManager.getSecondFloor();
//                jzVideoPlayer.onEvent(jzVideoPlayer.currentScreen == JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN ?
//                        JZUserAction.ON_QUIT_FULLSCREEN :
//                        JZUserAction.ON_QUIT_TINYSCREEN);
//                JZVideoPlayerManager.getFirstFloor().playOnThisJzvd();
//            } else {
            JZVideoPlayerManager.getFirstFloor().playOnThisJzvd();
                quitFullscreenOrTinyWindow();
//            }
            return true;
        }


因为出错了  我就将那个注释了  应该是在第二个if那里空了？

**Comment by lipangit** [comment]
崩溃的log是什么

**Comment by guoyongxing** [comment]
当已经播放一段时间了 由于 网络缓慢的原因 需要显示一个圆形进度条 在那转 当正常播放 圆形进度条消失了 有点像加载动画类似的！

**Comment by lipangit** [comment]
这是旧版本吧，新版已经把播放中的loading状态去掉了。

你的问题是什么？哪块不正常，能截个图吗或者录个小视频，这个事我还没搞懂

**Comment by guoyongxing** [comment]
我用的6.2.3  版本  因为现在修改其他的bug  那个log日志  明后天 我在测试一下吧？就是他在播放的时候  由于网络缓慢  我想让它显示圆形旋转进度条   当缓冲完毕后那个进度条消失？就像腾讯视频那种效果似的

**Comment by guoyongxing** [comment]
本来想截图了  可是网络不给力   不知道我说清楚了没有？

**Comment by lipangit** [comment]
老哥，真没说清楚，腾讯视频的什么样，有截图吗

截图或者录视频的目的就是两个，说清楚什么样的效果不要，什么样的效果要

**Comment by guoyongxing** [comment]
sorry  是我没有说清楚
![image](https://user-images.githubusercontent.com/16640088/34294030-b2b31f18-e741-11e7-9c29-2a74650dffef.png)
您看  我说的就是中间的那个圆形进度条？

**Comment by lipangit** [comment]
这个进度条在最近的版本已经被干掉了，目的是优化用户的体验

如果想加的话可以参考旧的版本，把这个部分原封不动拷贝过来，几行代码的问题，逻辑没变化

**Comment by guoyongxing** [comment]
就是我还想用6.2.3这个版本的   然后我还想圆形加进度条的话  我将那个类拿过来啊？进度条那个版本是5.7那个？

**Comment by lipangit** [comment]
具体哪个版本改的忘记了，找个旧版本搜索这里，参照修改即可
![image](https://user-images.githubusercontent.com/2038071/34902568-3481cd3c-f859-11e7-858e-f7f0b8a64221.png)

**Comment by lipangit** [comment]
不建议修改源码，建议继承jzvideoplayerstandard，复写父类函数即可

**Comment by guoyongxing** [comment]
复写父类那个方法啊？应该不是onInfo这个吧？

**Comment by guoyongxing** [comment]
![image](https://user-images.githubusercontent.com/16640088/34905546-bf2a5224-f895-11e7-8f3b-9ef32a6195c3.png)
![image](https://user-images.githubusercontent.com/16640088/34905573-977e41ee-f896-11e7-865a-fb8dc6fe6f79.png)

这里面的常量是修改了么？

**Comment by guoyongxing** [comment]
![image](https://user-images.githubusercontent.com/16640088/34905576-a8b6f4ce-f896-11e7-8732-c01c920230e5.png)
这个常量是修改了么？找不到啊 有些

**Comment by guoyongxing** [comment]
那个我看  这些方法和类都没有  我就找了个版本   缺啥补啥的  感觉有几个变量和方法都干掉了

**Comment by lipangit** [comment]
逻辑不用变，把他们加回来就好了
