### ISSUE TITLE
recyclerview里问题

### ISSUE THREAD

**Issue by chen188669** [lipangit/JiaoZiVideoPlayer#1481]
在recyclerview里  jzvd.dataSourceObjects 和JZMediaManager.getCurrentDataSource() 报空 
java.lang.NullPointerException: Attempt to read from null array   这个怎么解决呢

**Comment by lipangit** [comment]
参考demo

你的代码是怎么写的

**Comment by tknyl1314** [comment]
遇到了同样的问题

**Comment by lipangit** [comment]
需要提供更多信息，什么操作，setUp是怎么写的等
