### ISSUE TITLE
卡顿问题

### ISSUE THREAD

**Issue by jihan513** [lipangit/JiaoZiVideoPlayer#1482]
你好 我现在是一个fragment里嵌套4个fragment+viewpager，视频列表recyclerview在其中一个fragment上面，我添加两个视频进recyclerview的时候没问题，但是当我添加到四个的时候，recyclerview滑动就会 一卡一卡的，一开始我以为只是reycyclerview会卡而已，但是当我滑动viewpager切换到其他fragemnt的时候也会一卡一卡的 请问这是什么原因

**Comment by jihan513** [comment]
我原来是这样setimage的：
holder.jzVideoPlayerStandard.thumbImageView.setImageResource(mDatas.get(position).getImage());
然后看了您的demo试了一下用glide：
Glide.with(activity)
                .load(mDatas.get(position).getImage())
                .into(holder.jzVideoPlayerStandard.thumbImageView);
发现不会卡顿了，请问这是为什么呢

**Comment by jihan513** [comment]
不好意思，还有一个问题想请教一下，就是小窗播放的问题，demo里是滑动到下一个item看不到正在播放的item的时候就会出现小窗，但是我要滑动好多个item后才会出现小窗，请问这是什么问题，我是这样设置的：
mRecyclerview.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
                JZVideoPlayer.onChildViewAttachedToWindow(view,R.id.video_recyclerview);
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer.onChildViewDetachedFromWindow(view);
            }
        });
望指教，谢谢

**Comment by lipangit** [comment]
1.图片加载的问题，setImageResource这个是同步的，picasso是异步的

2.参考的demo的listView的activity，参考demo 的写法，咱们没有JZVideoPlayer.onChildViewDetachedFromWindow这种写法

**Comment by jihan513** [comment]
明白了 谢谢你的解答
