### ISSUE TITLE
播放的时候，能加缓存么

### ISSUE THREAD

**Issue by zhengfei** [lipangit/JiaoZiVideoPlayer#1485]
每次重播的时候，又得重新去服务器上拉一次流

**Comment by lipangit** [comment]
如果使用android.media.MediaPlayer，缓存和安卓的系统版本有关系，6.0以上16M以下的视频亲测是永久缓存，也可以一键切换播放器引擎

**Comment by zhengfei** [comment]
谢谢回复，现在这个开源框架还支持其他引擎么

**Comment by lipangit** [comment]
现在写好的只有ijkplayer和系统的播放器，其他播放引擎要自己实现了
