### ISSUE TITLE
怎么去掉列表右下角的小屏播放窗口

### ISSUE THREAD

**Issue by zou-xian-liang** [lipangit/JiaoZiVideoPlayer#1486]
麻烦知道的帮忙回答下，急急急

**Comment by lipangit** [comment]
如果按照demo 的写法，默认是没有小屏播放的，参考demo的对应界面的对应功能就好了

**Comment by wuxiaojun123** [comment]
能否代码设置不要小屏播放，因为我在recyclerview中的滑动事件里是使用的jzvd.startButton.performClick();所以想手动去掉小屏播放。(为什么不用你们的releaseAllVideos呢，因为产品要暂停不要释放)
