### ISSUE TITLE
华为4.4.2的手机 Mete7不能全屏播放

### ISSUE THREAD

**Issue by keaitao0321** [lipangit/JiaoZiVideoPlayer#1488]
华为4.4.2的手机 Mete7不能全屏播放,全屏的时候顶部有状态栏

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34287759-472b94ea-e724-11e7-9e55-dedfa551c556.png)
修改这个变量试试

**Comment by keaitao0321** [comment]
还是不行,是我设置的主题的问题吗?
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:windowAnimationStyle">@style/ActivityAnimFade</item>
        <item name="android:fitsSystemWindows">true</item>

    </style>

**Comment by lipangit** [comment]
1.先确定什么样的代码能隐藏掉你的状态栏。
2.把它放到项目里，替换旧的隐藏状态栏的代码
