### ISSUE TITLE
为什么播放这个视频会花屏

### ISSUE THREAD

**Issue by leiduowang** [lipangit/JiaoZiVideoPlayer#1489]
"http://datapository.oss-cn-shanghai.aliyuncs.com/goods/2d437a14-b3b1-42f8-8a39-54b9f29e9ca3.mp4”

**Comment by lipangit** [comment]
亲测，没发现什么问题，红米note4 安卓6.0

**Comment by leiduowang** [comment]
我这边的手机是中兴，6.0出现的花屏问题

**Comment by lipangit** [comment]
截图看看，绿色的吗

**Comment by haiguihuang** [comment]
我这边运行demo有几个视频也是花屏的，播放时从列表进入全屏时候就会出现。手机华为P7，版本4.4.2 
![2b157bfc8600583e740fd578a45922ba](https://user-images.githubusercontent.com/18528188/34293979-8e52829e-e741-11e7-8376-2c9832792ea5.jpg)

**Comment by leiduowang** [comment]
@lipangit - 对的,就是绿色的，
![20171222175548](https://user-images.githubusercontent.com/20085306/34294020-ae03447a-e741-11e7-823a-fe53a0189298.png)

**Comment by lipangit** [comment]
上面那个是从秒拍客户端抓取的，这个视频格式应该是标准的，如果这个出现在我的公司，要么换视频源，要么扛着这个问题，问题不大，干就完了

如果实在抗不过去，可以考虑修改播放器引擎到ijkplayer

**Comment by leiduowang** [comment]
@lipangit 好的

**Comment by haiguihuang** [comment]
了解，谢谢
