### ISSUE TITLE
夜间模式下横屏播放闪退

### ISSUE THREAD

**Issue by hyandroid** [lipangit/JiaoZiVideoPlayer#1492]
夜间模式下AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES );
全屏播放后，横屏退出了

**Comment by hyandroid** [comment]
因为横屏时重新执行了生命周期，所以刷新退出了，这个怎么解决，不设置夜间模式就没问题。

**Comment by hyandroid** [comment]
解决了设置uiMode

**Comment by lipangit** [comment]
闪退的log是什么？

**Comment by hyandroid** [comment]
不是闪退，是activity重新执行了生命周期，回到了原来的页面

**Comment by lipangit** [comment]
是不是执行了setUp函数或者onPause函数，可以在调用setUp和onPause之前判断是否是第一次，是否是夜间模式

**Comment by t617** [comment]
在manifest设置Activity的android:configChanges="orientation|keyboardHidden"时，切屏不会重新调用各个生命周期，只会执行onConfigurationChanged方法

**Comment by lipangit** [comment]
咱这项目不用onConfigurationChanged判断，@t617你的具体什么问题

**Comment by t617** [comment]
用那个声明可以解决了与上一位同是横屏的时候重新调用生命周期回到原始的页面的问题了

**Comment by HLMODRIC** [comment]
android:configChanges="orientation|screenSize|**uiMode**|keyboardHidden"

**Comment by lipangit** [comment]
很老的问题了，大家看看，这样能解决吗，还在吗
