### ISSUE TITLE
全屏状态下，getCurrentPositionWhenPlaying() 方法，获取播放时长无效。是0。

### ISSUE THREAD

**Issue by Koterwong** [lipangit/JiaoZiVideoPlayer#1494]
已知全屏状态下，JZPVideolayer的不是同一个。
请问，有没有其他方式获取播放时长呢。

我这边是在做一个试看的功能，试看30s，即不能继续播放。

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写相应的函数取得相应的状态和事件，然后写自己的逻辑

全屏和非全屏不是一个实例，必须通过继承的方式写自己的逻辑

**Comment by lucazin** [comment]
english please ?
