### ISSUE TITLE
surfaceTexture must not be null

### ISSUE THREAD

**Issue by yanlianhanlin** [lipangit/JiaoZiVideoPlayer#1495]
java.lang.IllegalArgumentException: surfaceTexture must not be null
                      at android.view.Surface.<init>(Surface.java:124)
                      at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:149)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.os.HandlerThread.run(HandlerThread.java:61)

报这个错误，应该怎么解决啊

**Comment by lipangit** [comment]
什么情况下遇到的这个问题，改库了吗

**Comment by yanlianhanlin** [comment]
我是继承JZVideoPlayerStandard，监听视频播放完之后重新放入新的链接播放出现的这个问题，不是一直出现，有的时候会出现这个问题，每次更新链接都是这样更新的，是哪个地方用的不对吗？
 videoplayer.setUp(videoList.get(videoIndex-1),0, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "");
        JZVideoPlayer.setVideoImageDisplayType(JZVideoPlayer.VIDEO_IMAGE_DISPLAY_TYPE_FILL_PARENT);
        videoplayer.startVideo();

**Comment by lipangit** [comment]
不是继承的JZVideoPlayerStandard吗，怎么会有videoplayer变量。

更换播放链接，参考demo的apiActivity更换清晰度功能，更换清晰度本质上就是更换播放链接

**Comment by yanlianhanlin** [comment]
更换清晰度，那个怎么使用呢，按照demo的方式写，会播放一个视频结束后接着播放另一个视频嘛？

**Comment by lipangit** [comment]
不会

复写onComplete函数监听播放结束，然后调用onStatePreparingChangingUrl（）函数切换视频源

**Comment by yanlianhanlin** [comment]
按照你说的方式使用之后，在视频播放完成后切换视频源，出现重播进度，一直无法播放下一个视频，应该如何解决？

**Comment by lipangit** [comment]
重播进度 是什么意思？

onStatePreparingChangingUrl()这个函数调用之后是怎样的效果？

**Comment by yanlianhanlin** [comment]
出现一个progressbar  写着重播，一直加载没有内容播放

**Comment by lipangit** [comment]
这个有问题了，progressbar和重播不会同时提示的。

什么版本，有bug的截图吗

**Comment by yanlianhanlin** [comment]
版本6.2.3 
![screenshot_2018-01-05-12-35-02_com lm jidinghe](https://user-images.githubusercontent.com/9565630/34595724-18f0605a-f215-11e7-86a9-ae62b11fbda0.png)

**Comment by yanlianhanlin** [comment]
版本6.2.3
![qq 20180105124015](https://user-images.githubusercontent.com/9565630/34595805-ccb388e2-f215-11e7-89d8-69a729354190.png)

**Comment by lipangit** [comment]
能复现吗，断点一下当前的state是什么，这个ui理论上是不可能的，咱们都是根据状态去控制控件的

**Comment by yanlianhanlin** [comment]
你说的是这个吗？
![qq 20180105141542](https://user-images.githubusercontent.com/9565630/34597677-27bcc214-f223-11e7-8329-210ec548d41c.png)

**Comment by yanlianhanlin** [comment]
我是自定义了一个JZVideo类
public class JZVideo extends JZVideoPlayerStandard{
    public interface JZVideoListener{
        void StateAutoComplete();
    }
    private JZVideoListener JZVideoListener;


    public void setJZVideoListener(JZVideo.JZVideoListener JZVideoListener) {
        this.JZVideoListener = JZVideoListener;
    }

    public JZVideo(Context context, AttributeSet attrs) {
        super(context, attrs);
    }


    /**进入视频自动播放完成状态*/
    @Override
    public void onStateAutoComplete() {
        super.onStateAutoComplete();
//        this.startVideo();
        JZVideoListener.StateAutoComplete();
    }
在activity中监听当播放完之后切换视频源播放
 private JZVideo.JZVideoListener videoListener = new JZVideo.JZVideoListener() {
        @Override
        public void StateAutoComplete() {
            if(videoIndex != map.size()-1){
                ++videoIndex;
            }else if(videoIndex == map.size()-1){
                videoIndex = 0;
            }
            videoplayer.onStatePreparingChangingUrl(videoIndex,0);
        }
    };
这么写有问题吗？是不是我用的方式不对？

**Comment by lipangit** [comment]
兄弟，能否抽象一个项目出来，放到github上，我给你弄

**Comment by yanlianhanlin** [comment]
老铁 我已经上传了 你测试下吧，谢谢
https://github.com/yanlianhanlin/JZdemo.git

**Comment by lipangit** [comment]
哥们，给你yan'ji研究了一下但是没弄完，当前是这样，你可以预览一下。
[src.zip](https://github.com/lipangit/JiaoZiVideoPlayer/files/1606614/src.zip)

明天继续给你研究，这个播放下一集的功能将来会放到demo中
