### ISSUE TITLE
代码洁癖---->JZVideoPlayer中的mHandler不需要定义

### ISSUE THREAD

**Issue by 401885064** [lipangit/JiaoZiVideoPlayer#1499]
JZVideoPlayer中代码：

  mHandler.post(new Runnable() {
                    @Override
                    public void run() {
                        long position = getCurrentPositionWhenPlaying();
                        long duration = getDuration();
                        int progress = (int) (position * 100 / (duration == 0 ? 1 : duration));
                        setProgressAndText(progress, position, duration);
                    }
                });

View中是可以直接post：
post(new Runnable() {
                    @Override
                    public void run() {
                        long position = getCurrentPositionWhenPlaying();
                        long duration = getDuration();
                        int progress = (int) (position * 100 / (duration == 0 ? 1 : duration));
                        setProgressAndText(progress, position, duration);
                    }
                });

**Comment by lipangit** [comment]
非常有道理，已经修复
