### ISSUE TITLE
quickStart播放不了不了

### ISSUE THREAD

**Issue by LoHiaufung** [lipangit/JiaoZiVideoPlayer#1500]
按照quickStart写的。
SDK API 23
AS 2.6
跑起来一直在加载，永远不播放。视频源就是quickStart给的，我用浏览器是可以打开的。

**Comment by LoHiaufung** [comment]
就一个小圈圈一直在转，就没有然后了

**Comment by LoHiaufung** [comment]
12-27 05:50:06.506 16301-16351/com.example.lohiaufung.myapplication W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-27 05:50:06.507 16301-16351/com.example.lohiaufung.myapplication E/MediaPlayer: Unable to create media player
12-27 05:50:06.507 16301-16351/com.example.lohiaufung.myapplication W/System.err: java.lang.reflect.InvocationTargetException
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:44)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:145)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:148)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err: Caused by: java.io.IOException: setDataSource failed.: status=0x80000000
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.media.MediaPlayer.nativeSetDataSource(Native Method)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1085)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1074)
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/System.err: 	... 6 more
12-27 05:50:06.508 16301-16351/com.example.lohiaufung.myapplication W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by lipangit** [comment]
网络权限没写吧

**Comment by LoHiaufung** [comment]
写了的。写了网络访问那个

**Comment by LoHiaufung** [comment]
翻一番日志，还有大量这种东西：
12-27 21:31:00.115 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5152)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.115 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.115 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.115 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.115 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.115 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5152)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.125 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.125 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5152)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.125 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.125 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.125 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.125 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5186)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.135 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5186)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.135 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err: java.io.FileNotFoundException: icon_mapping
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:316)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:290)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.imagecache.IconCache.getDefaultIconResourceName(IconCache.java:459)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.Workspace.updateCalendarIconBitmap(Workspace.java:5186)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.Launcher.bindCalendarUpdated(Launcher.java:6775)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.LauncherModel$11.run(LauncherModel.java:1018)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.launcher.DeferredHandler$Impl.handleMessage(DeferredHandler.java:47)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
12-27 21:31:00.135 1522-1522/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5336)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
12-27 21:31:00.135 1522-1522/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
12-27 21:31:00.135 1522-1522/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
12-27 21:31:00.135 1522-1522/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by LoHiaufung** [comment]
对了，上述情况下我把 

jzVideoPlayerStandard.thumbImageView.setImage("http://p.qpic.cn/videoyun/0/2449_43b6f696980311e59ed467f22794e792_1/640");

注释掉了,因为不存在SetImage这个方法

**Comment by lipangit** [comment]
把项目发来吧我给你试试，或者上传到github

**Comment by LoHiaufung** [comment]
https://github.com/LoHiaufung/android_HW
里面exo文件夹就是

**Comment by LoHiaufung** [comment]
你有跑出类似的问题吗？等着期末项目用

**Comment by lipangit** [comment]
兄弟，能新建一个项目吗，无法只下载exo文件夹，整个项目太大了，每秒6K需要一天时间下载

**Comment by LoHiaufung** [comment]
老哥，这有个只下载文件夹的工具。http://kinolien.github.io/gitzip/。
或者留你邮箱，我扔过去。

**Comment by lipangit** [comment]
老铁你把网络权限写错xml的节点了
![image](https://user-images.githubusercontent.com/2038071/34414173-b38136ec-ec22-11e7-81df-3100fd758126.png)

**Comment by lipangit** [comment]
改到上面就好了，播放没有问题

**Comment by LoHiaufung** [comment]
天！真的可以，谢谢老哥
