### ISSUE TITLE
不点全屏播放的情况下，怎么样让视频填充满播放器播放呢！

### ISSUE THREAD

**Issue by EchoKoreyoshi** [lipangit/JiaoZiVideoPlayer#1502]
就是 视频资源由竖屏拍摄的 有的是横屏拍的，竖屏资源视频的话，点击播放直接类是全屏一样 播放填满整个屏幕，横屏视频资源，点击播放在视频宽填充屏幕的宽的时候就可以，播放高度就不用管，就像快手 一样的播放模式，希望帮我解答解答

**Comment by lipangit** [comment]
参考demo的smallChangeUiActivity，里面有修改控件高宽的例子，前提是在视频播放之前就要知道视频的高宽

**Comment by EchoKoreyoshi** [comment]
谢谢  我看看 有啥疑问我再来

**Comment by EchoKoreyoshi** [comment]
`jzVideoPlayerStandard.widthRatio = 1;
 jzVideoPlayerStandard.heightRatio = 1;`
这两个参数是设置播放器的宽高？还是？如果视频资源的width=height的话 用上面的代码是刚好能让视频填满播放器播放的
比如我有个视频：width：144  height：240  这就是width<height所谓的竖屏资源
我怎么设置 jzVideoPlayerStandard.widthRatio 和 jzVideoPlayerStandard.heightRatio 才能让这个视频像全屏播放一样呢？

**Comment by lipangit** [comment]
这两个变量设置的是宽高比例

像全屏一样播放试试这样
1.把手机屏幕的宽高比例设置到widthRatio 和heightRatio
2.参照ActivityApiRotationVideoSize，把视频居中剪切

**Comment by mmmlee** [comment]
还是设置不了适应屏幕啊，按照你的方法

**Comment by lipangit** [comment]
当前遇到什么问题

**Comment by mmmlee** [comment]
视频的宽高不能填充播放器，在recyclerview列表里面播放的时候

**Comment by lipangit** [comment]
ActivityApiRotationVideoSize 这个是视频剪裁的例子

**Comment by gaibianziji043** [comment]
解决了吗
