### ISSUE TITLE
java.net.ProtocolException

### ISSUE THREAD

**Issue by Kharlos** [lipangit/JiaoZiVideoPlayer#1504]
well im try using this library to load video from url im using this in my activity 

            `JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.videoplayer);
            jzVideoPlayerStandard.setUp(url
                    , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "Objects");`

`    <cn.jzvd.JZVideoPlayerStandard
        android:id="@+id/videoplayer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>`

`   @Override
    public void onBackPressed() {
        if (JZVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }
    @Override
    protected void onPause() {
        super.onPause();
        JZVideoPlayer.releaseAllVideos();
    }`

but it trow this errror

12-27 14:18:08.147 24793-24939/pe.com.peruapps.proyecta W/System.err: java.net.ProtocolException
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:291)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:324)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.media.MediaHTTPConnection.native_readAt(Native Method)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.media.MediaHTTPConnection.readAt(MediaHTTPConnection.java:313)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:72)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/System.err:     at android.os.Binder.execTransact(Binder.java:461)
12-27 14:18:08.154 24793-24939/pe.com.peruapps.proyecta W/MediaHTTPConnection: readAt 14201843 / 32768 => java.net.ProtocolException

**Comment by lipangit** [comment]
Maybe the internet is bad, did you add internet permission

**Comment by Kharlos** [comment]
Yes i added internet permission and the internet is ok any another idea?

**Comment by lipangit** [comment]
can you show me your url I will test it
