### ISSUE TITLE
小米note ，小米5无法播放视频

### ISSUE THREAD

**Issue by MoMask** [lipangit/JiaoZiVideoPlayer#1505]
12-28 14:19:22.628 6486-6486/lhj.com.pbc I/JiaoZiVideoPlayer: onClick start [128778330] 
12-28 14:19:22.630 6486-6486/lhj.com.pbc D/JiaoZiVideoPlayer: startVideo [128778330] 
12-28 14:19:22.631 6486-6486/lhj.com.pbc D/JiaoZiVideoPlayer: addTextureView [128778330] 
12-28 14:19:22.634 6486-6486/lhj.com.pbc I/JiaoZiVideoPlayer: onStatePreparing  [128778330] 
12-28 14:19:22.636 6486-6486/lhj.com.pbc I/JZResizeTextureView: onMeasure  [16135178] 
12-28 14:19:22.636 6486-6486/lhj.com.pbc I/JZResizeTextureView: onMeasure  [16135178] 
12-28 14:19:22.640 6486-6491/lhj.com.pbc I/art: Do partial code cache collection, code=124KB, data=123KB
12-28 14:19:22.640 6486-6491/lhj.com.pbc I/art: After code cache collection, code=123KB, data=122KB
12-28 14:19:22.640 6486-6491/lhj.com.pbc I/art: Increasing code cache capacity to 512KB
12-28 14:19:22.641 6486-6486/lhj.com.pbc I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [128778330] 
12-28 14:19:22.653 6486-6832/lhj.com.pbc E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
12-28 14:19:22.654 6486-6832/lhj.com.pbc E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-28 14:19:22.654 6486-6832/lhj.com.pbc E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
12-28 14:19:22.654 6486-6832/lhj.com.pbc E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
12-28 14:19:22.687 6486-6832/lhj.com.pbc W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-28 14:19:22.712 6486-6832/lhj.com.pbc W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-28 14:19:23.657 6486-6498/lhj.com.pbc W/IMediaDeathNotifier: media server died
12-28 14:19:23.657 6486-6498/lhj.com.pbc E/MediaPlayer: error (100, 0)
12-28 14:19:23.658 6486-6832/lhj.com.pbc E/MediaPlayer: Error (100,0)
12-28 14:19:23.660 6486-6486/lhj.com.pbc E/JiaoZiVideoPlayer: onError 100 - 0 [128778330] 
12-28 14:19:23.661 6486-6486/lhj.com.pbc I/JiaoZiVideoPlayer: onStateError  [128778330]

**Comment by lipangit** [comment]
media server died

这个问题容易复现吗

**Comment by lovelyYakir** [comment]
目前只要是小米的手机全部无法播放。但是其他手机正常使用。如何切换播放引擎？

**Comment by lipangit** [comment]
切换播放引擎参考ActivityApiCustomMediaPlayer
