### ISSUE TITLE
关于视频缓冲问题

### ISSUE THREAD

**Issue by PerryWong** [lipangit/JiaoZiVideoPlayer#1507]
如何监听视频是否处于缓冲状态,视频在拖动进度条后若是在缓存区外,会卡主,等到加载后再继续播放,而这期间并未出现缓冲提示,如何加入缓冲提示

**Comment by lipangit** [comment]
是的，seek进度的时候loading状态被干掉了，这块会继续优化的

如果想要原来的，可以参考以前的版本手动改回来

**Comment by huangjingqiang** [comment]
请问有seek方法？ @lipangit

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/1480 相同的问题

如果不行可以参照修改
