### ISSUE TITLE
加载网络视频特别慢，而且每次都要缓冲好像

### ISSUE THREAD

**Issue by king19910525** [lipangit/JiaoZiVideoPlayer#1508]

**Comment by lipangit** [comment]
这个和安卓的版本有关系，如果想要和安卓版本无关，可以引入videoplayercache库，或者一行代码切换到ijkplayer

**Comment by jackerjin** [comment]
> videoplayercache库
能说说怎么用吗，或者怎么切换到ijkplayer

**Comment by lipangit** [comment]
video cache  看这里https://github.com/danikula/AndroidVideoCache

一行代码切换播放内核到ijkplayer，参考demo的customMediaPlayer
