### ISSUE TITLE
使用移动网络时,提示当前正在使用移动网络,点击停止播放,返回键失效

### ISSUE THREAD

**Issue by weiwenhuaming01** [lipangit/JiaoZiVideoPlayer#1509]
在我使用移动网络,全屏播放的时候,提示您当前正在使用移动网络,继续播放将消耗流量,点击停止播放按钮,此时返回键失效

**Comment by weiwenhuaming01** [comment]
查看代码,返回键的判断逻辑中 JZVideoPlayerManager.getSecondFloor() 和JZVideoPlayerManager.getFirstFloor() ,在此时都等于null,因此最后走了false, @lipangit

**Comment by lipangit** [comment]
亲测并没有你说的问题

![image](https://user-images.githubusercontent.com/2038071/34435910-02c9137e-eccc-11e7-8a6f-2e0af0c1622e.png)

停止播放按钮只是把dialog关闭，没有别的动作

**Comment by lipangit** [comment]
之前还有其他操作吗

**Comment by weiwenhuaming01** [comment]
用demo运行也是一样的,@lipangit,你可以尝试一下,用移动网络打开Direct play,选择fullscreen,选择停止播放,再点击饺子辛苦了旁边的返回箭头,是失效的

**Comment by weiwenhuaming01** [comment]
@lipangit,是标题旁边的返回箭头,不是手机自带的返回键

**Comment by lipangit** [comment]
是的，确实有这个问题，下版本会修改，感谢你的反馈

**Comment by lipangit** [comment]
已经修复，点击停止播放之后，退出全屏界面

**Comment by weiwenhuaming01** [comment]
@lipangit  是修复了moudle依赖,complie还没有更新?

**Comment by lipangit** [comment]
对 发版要等到周末，咱不能说改点啥就发版，改点啥就发版，乱套了

**Comment by weiwenhuaming01** [comment]
@lipangit  好的,谢谢
