### ISSUE TITLE
Genymotion 三星s2 模拟机型 视频都播放不了

### ISSUE THREAD

**Issue by Ocesdi** [lipangit/JiaoZiVideoPlayer#1510]
楼主，你好：
视频播放器 在Genymotion 三星s2 的模拟器当中都播放不了，地址链接是正常，其他机型可以播放。
请问这是什么问题导致的，该如何解决？急需，谢谢！

截图： https://gyazo.com/7448d5178d68a0c2df9c1a8d23bca974

**Comment by lipangit** [comment]
请用真机测试，模拟器播放不了可能是因为缺东西，不在适配的范围

新建一个项目单纯用textureView和mediaPlayer应该也播放不了
