### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by m5314** [lipangit/JiaoZiVideoPlayer#1511]
public class MediaHandler extends Handler {
        public MediaHandler(Looper looper) {
            super(looper);
        }

        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            switch (msg.what) {
                case HANDLER_PREPARE:
                    currentVideoWidth = 0;
                    currentVideoHeight = 0;
                    jzMediaInterface.prepare();
                    if (surface != null) {
                        surface.release();
                    }
                    surface = new Surface(savedSurfaceTexture);
                    jzMediaInterface.setSurface(surface);
                    break;
                case HANDLER_RELEASE:
                    jzMediaInterface.release();
                    break;
            }
        }
    }

JZMediamanager类里这个handler会报空指针
java.lang.IllegalArgumentException: surfaceTexture must not be null
	at android.view.Surface.<init>(Surface.java:136)
	at cn.jzvd.b$a.handleMessage(SourceFile:149)
请问是什么问题？

**Comment by m5314** [comment]
是列表播放滚动时出现的，估计是onScrollReleaseAllVideos方法调用太频繁，上面代码又是异步，release的时候会不会把handler的回调先清掉？

**Comment by lipangit** [comment]
手上操作是怎样的？什么情况下出的这个问题

清空handler是个办法

**Comment by m5314** [comment]
我是监听列表滚动，然后播放第一个完整显示在屏幕的item的视频，滚动时调用的onScrollReleaseAllVideos释放视频。偶尔滑动列表就会出现这个问题

**Comment by lipangit** [comment]
恩，已经列入工作计划

**Comment by mmmlee** [comment]
ava.lang.NullPointerException: Attempt to read from null array
                                                                              at cn.jzvd.JZUtils.dataSourceObjectsContainsUri(JZUtils.java:172)

recyclerview 列表播放的时候 为什么会报空指针啊

**Comment by m5314** [comment]
这个我也遇到过，我是因为没有setup的情况下调用了release

**Comment by mmmlee** [comment]
你也是JZUtils报空指针吗

**Comment by m5314** [comment]
是的

**Comment by mmmlee** [comment]
怎么解决的呢 我是recyclerview嵌套recyclerview，在第一个recyclerview里面的holder里面做的监听，第二个recyclerview里面的holder里面才有播放视频的逻辑

**Comment by mmmlee** [comment]
JieCaoVideoPlayer 支持列表滑动的时候自动播放吗，不是全屏，就是在列表中滑动到的时候自动播放

**Comment by m5314** [comment]
没找到demo中有，我是自己实现的

**Comment by mmmlee** [comment]
能发下代码吗

**Comment by m5314** [comment]
写在项目里的代码不能拿出来，你也可以参考源码中onScrollAutoTiny方法，原理差不多，改下也可以了

**Comment by mmmlee** [comment]
好的，谢谢
