### ISSUE TITLE
如何让视频进行预加载

### ISSUE THREAD

**Issue by YFogRain** [lipangit/JiaoZiVideoPlayer#1512]
怎么让视频在刚加载页面的时候去加载，然后加载完成后，我需要播放的时候在进行播放？？

**Comment by lipangit** [comment]
这个可以实现但是需要很多的修改

mediaPlayer.prepareAsync() 会准备视频，但是不会播放，mediaPlayer.start()才会播放，暂时库还不支持，需要自己深入修改
