### ISSUE TITLE
请问，此播放SDK支持MOV格式么

### ISSUE THREAD

**Issue by onecoders** [lipangit/JiaoZiVideoPlayer#1513]
如题

**Comment by lipangit** [comment]
播放的视频格式取决于播放器引擎 系统的播放器引擎 支持的格式如下 https://developer.android.com/guide/appendix/media-formats.html，没找到mov相关的

你可以一键切换成ijkplayer播放器引擎。

**Comment by longkehuawei** [comment]
怎么切换
