### ISSUE TITLE
点击重播时屏幕自动旋转失效

### ISSUE THREAD

**Issue by xutengsheng** [lipangit/JiaoZiVideoPlayer#1516]
1.首次进来播放,屏幕自动旋转有效;
2.播放完毕后点击重播,自动旋转就失效了,就变为竖屏播放了;
3.使用的api为:setUp(proxyUrl, JZVideoPlayer.SCREEN_WINDOW_NORMAL, "");

请问大神是怎么回事?

**Comment by lipangit** [comment]
亲测，点击重播之后进入全屏屏幕还能自动旋转

有其他地方的修改吗，他们应该是不相干的

**Comment by xutengsheng** [comment]
大神,是这样的:
1.我在Activity布局就是一个JZVideoPlayerStandard,宽高都是match_parent;
2.使用setUp(proxyUrl, JZVideoPlayer.SCREEN_WINDOW_NORMAL, "")设置视频,右下角的全屏隐藏了(本来界面就这一个全屏播放器,所以右下角的全屏就隐藏了);
3.通过自动旋转来控制横竖屏,第一次进来可以自动旋转,播放完成后点击重播,自动旋转就失效;

**Comment by lipangit** [comment]
如果需要直接进入全屏播放参考demo的ActivityDirectPlay，直接进入全屏。

你说的这个屏幕旋转的问题本质上是这两个变量控制，你可以断点研究一下他们的变化，什么时候变化了
![image](https://user-images.githubusercontent.com/2038071/34730565-b6ad0d24-f59a-11e7-87fc-16ec57016983.png)

**Comment by xutengsheng** [comment]
行,我再研究下,谢谢大神
