### ISSUE TITLE
使用地铁wifi无法播放视频

### ISSUE THREAD

**Issue by bethebest** [lipangit/JiaoZiVideoPlayer#1519]
mVideoplayer.setUp(videourl, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, title);
 mVideoplayer.startVideo();
使用示例代码在公司使用wifi可以播放，但是在链接地铁wifi无法播放

**Comment by lipangit** [comment]
确认是wifi吗，流量使用的提醒对话框出来了吗？

当时能看log吗，什么log

**Comment by bethebest** [comment]
确定是wifi，我的4G是关掉的，今日头条的视频是可以看的，在地铁上看不到log

**Comment by lipangit** [comment]
老铁这。。
