### ISSUE TITLE
 java.lang.IllegalArgumentException · surfaceTexture must not be null

### ISSUE THREAD

**Issue by techGay** [lipangit/JiaoZiVideoPlayer#1521]
后台回传日志：
java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:123)
        at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:149)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)

生命周期情况：
  | Error Occurred  0s before |  
-- | -- | --
  | JiaoZiVideoPlayerActivity  10s before | ActivityLifecycleon  Stop()
  | JiaoZiVideoPlayerActivity  10s before | ActivityLifecycle   onSaveInstanceState()
  | JiaoZiVideoPlayerActivity  11s before | ActivityLifecycle  onPause()
  | MainActivity  21s before | ActivityLifecycle   onStop()
  | MainActivity  21s before | ActivityLifecycle   onSaveInstanceState()
  | JiaoZiVideoPlayerActivity  22s before | ActivityLifecycle   onResume()
  | JiaoZiVideoPlayerActivity  22s before | ActivityLifecycle  onStart()
  | JiaoZiVideoPlayerActivity  22s before | ActivityLifecycle   onCreate()
  | MainActivity  22s before | ActivityLifecycle  onPause()
  | JiaoZiVideoPlayerActivity   22s before | ActivityLifecycle  onDestroy()
  | JiaoZiVideoPlayerActivity   22s before | ActivityLifecycle onStop()
  ............

设备信息：
manufacturer   nubia
model  NX510J
networkAccess  wifi
orientation  portrait
osName  android
osVersion  4.4.2
screenDensity  1.5
screenResolution 1280x720

JiaoZiVideoPlayerActivity 代码：

    @Override
    public void onBackPressed() {
        if (JZVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }

    @Override
    protected void onPause() {
        super.onPause();
        JZVideoPlayer.releaseAllVideos();
    }
用户在多次主界面（仅列表显示信息）和播放界面来回之后切换报如上错误，目前仅发现此用户有此种情况

**Comment by lipangit** [comment]
这估计是在add textureView的时候还没来得及生成surface，出现的nullpoint bug，正在研究修改

**Comment by easyandroid** [comment]
+1 压力测试出现了这个bug:  java.lang.IllegalArgumentException: surfaceTexture must not be null

**Comment by lipangit** [comment]
@easyandroid 用的什么版本，记得尝试改过，判断空了

**Comment by easyandroid** [comment]
@lipangit  6.2.3

**Comment by easyandroid** [comment]
@lipangit  6.2.3

**Comment by lipangit** [comment]
断点一下surfaceTexture = null的地方，看看什么地方在不该给他设空的时候设了空

**Comment by hczmail** [comment]
6.4.1 也出现这个问题，如何解决？

**Comment by lipangit** [comment]
断点结果如何 @hczmail
