### ISSUE TITLE
startButton icon

### ISSUE THREAD

**Issue by marwa1994** [lipangit/JiaoZiVideoPlayer#1522]
i create a custom video player i want to change the icon of start button of the video i'm changing that in xml file and the init of the code but it 's not working van u help me ?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34666590-16bd8a46-f4a0-11e7-9d2c-9c0b8c8c8491.png)


return your xml id here

**Comment by marwa1994** [comment]
@Override
    public int getLayoutId() {
        
        return R.layout.jc_layout_custom;
    }
i'm doing that but i can't change the icon of start button it is still always the old one

**Comment by lipangit** [comment]
O ! I remember.
![image](https://user-images.githubusercontent.com/2038071/34680904-43baebb2-f4d5-11e7-8036-3757b7d9f7cf.png)

you should override updateStartImage function and set your startbutton icon in every state
