### ISSUE TITLE
Listview同时点击两个视频崩溃

### ISSUE THREAD

**Issue by yulonghuang** [lipangit/JiaoZiVideoPlayer#1523]
UncaughtException in Thread JiaoZiVideoPlayer
                                                       java.lang.IllegalArgumentException: surfaceTexture must not be null
                                                           at android.view.Surface.<init>(Surface.java:186)
                                                           at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:149)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:154)
                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
代码里没有同时点击的判断。。

容易复现吗

**Comment by yulonghuang** [comment]
您好。还是比较容易复现的。我这边修改了一个recycleview混合列表，然后两个同时点击就出现了崩溃。麻烦看一下。谢谢了。

**Comment by yulonghuang** [comment]
`package cn.jzvd.demo;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.squareup.picasso.Picasso;

import cn.jzvd.JZVideoPlayer;
import cn.jzvd.JZVideoPlayerStandard;

/**
 * Created by Nathen on 2017/11/1.
 */

public class ActivityTinyWindowRecycleViewMultiHolder extends AppCompatActivity {

    RecyclerView recyclerView;
    AdapterRecyclerView videoAdapter;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setDisplayShowTitleEnabled(true);
        getSupportActionBar().setDisplayUseLogoEnabled(false);
        getSupportActionBar().setTitle("RecycleViewMultiHolderTinyWindow");
        setContentView(R.layout.activity_recyclerview_content);

        recyclerView = findViewById(R.id.recyclerview);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        videoAdapter = new AdapterRecyclerView();
        recyclerView.setAdapter(videoAdapter);
        recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
                JZVideoPlayer.onChildViewAttachedToWindow(view, R.id.videoplayer);
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer.onChildViewDetachedFromWindow(view);
            }
        });

    }

    @Override
    protected void onPause() {
        super.onPause();
        JZVideoPlayer.releaseAllVideos();
    }

    @Override
    public void onBackPressed() {
        if (JZVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                finish();
                break;
        }
        return super.onOptionsItemSelected(item);
    }

    public class AdapterRecyclerView extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

        @Override
        public int getItemViewType(int position) {
            if (position == 4 || position == 7) {
                return 0;//非视频
            }
            return 1;//视频
        }

        @Override
        public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View view;
            if (viewType == 1) {
                view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_videoview, parent, false);
                return new VideoHolder(view);
            } else {
                view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_textview, parent, false);
                return new TextHolder(view);
            }
        }

        @Override
        public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
            if (position == 4 || position == 7) {
                TextHolder textHolder = (TextHolder) holder;
            } else {
                VideoHolder videoHolder = (VideoHolder) holder;
                videoHolder.jzVideoPlayer.setUp(
                        VideoConstant.videoUrls[0][position], JZVideoPlayer.SCREEN_WINDOW_LIST,
                        VideoConstant.videoTitles[0][position]);
                videoHolder.jzVideoPlayer.positionInList = position;
                Picasso.with(ActivityTinyWindowRecycleViewMultiHolder.this)
                        .load(VideoConstant.videoThumbs[0][position])
                        .into(videoHolder.jzVideoPlayer.thumbImageView);
            }
        }

        @Override
        public int getItemCount() {
            return 10;
        }

        class VideoHolder extends RecyclerView.ViewHolder {
            JZVideoPlayerStandard jzVideoPlayer;

            public VideoHolder(View itemView) {
                super(itemView);
                jzVideoPlayer = itemView.findViewById(R.id.videoplayer);
            }
        }

        class TextHolder extends RecyclerView.ViewHolder {
            TextView textView;

            public TextHolder(View itemView) {
                super(itemView);
                textView = itemView.findViewById(R.id.textview);
            }
        }
    }
}
`

**Comment by yulonghuang** [comment]
具体代码视频也已经发至您的邮箱了。谢谢。

**Comment by lipangit** [comment]
好

**Comment by yulonghuang** [comment]
哥。。。这个应该怎么修改呢。。

**Comment by yulonghuang** [comment]
可以给点思路吗？我这边项目要用的。。

**Comment by lipangit** [comment]
点击开始按钮->addViewSurfaceView->surfaceView会生成surface，就在addViewSurfaceView之后生成surface之前调用surface，这时候surface是空的

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/34731383-28c835a8-f59d-11e7-8638-b2cfc6780a8f.png)

像这样判断他俩是不是null就好，还没测试，请谨慎测试

**Comment by yulonghuang** [comment]
OK  谢谢哦

**Comment by lipangit** [comment]
昨天刚改好，可以参考，周日发版

**Comment by yulonghuang** [comment]
好的。麻烦您了。
