### ISSUE TITLE
延迟设置URL的问题

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#1525]
视频的URL需要网络获取，我想在用户点击后再调用setUp，初步的想法是捕捉onClick里的R.id.thumb的点击事件，但是如果不调用setUp设置url的话，视频会马上出现地址无效和重试的按钮，请问在什么地方可以让视频窗口不要主动去测试视频地址是否有效？

**Comment by lipangit** [comment]
复写onclick方法，拦截开始的点击，此时去请求url，请求url回来之后设置好数据开始播放视频

**Comment by kennir** [comment]
但是现在的情况是用户还没有点击开始，就出来 视频地址无效 和 重试按钮
不过我用ImageView自己做了一个开始按钮，当点击后取到地址后再把player显示出来，目前看下来都正常
