### ISSUE TITLE
项目源码里RecyclerView TinyWindow和ListView TinyWindow的列表里播放一个视频，然后上下滑动列表会有崩溃的问题

### ISSUE THREAD

**Issue by chenxiaozhen** [lipangit/JiaoZiVideoPlayer#1526]
![image](https://user-images.githubusercontent.com/11922359/34714003-ee968fa4-f562-11e7-8b37-105c583ba11c.png)

**Comment by lipangit** [comment]
是的这个问题很严重，我会尽快修复。

**Comment by lipangit** [comment]
感谢你的反馈

**Comment by kennir** [comment]
请问这个是sample本身代码的问题还是库的问题？ 如果是库的问题我先不引入tinywindow播放，谢谢

**Comment by lipangit** [comment]
已经解决，多谢反馈
