### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by weiwenhuaming01** [lipangit/JiaoZiVideoPlayer#1527]
全屏状态下,网络异常,显示标题栏以便可以点击退回之前的页面 ,我是这样改的
![image](https://user-images.githubusercontent.com/24544494/34712962-aa5dd49e-f55f-11e7-81e9-e33c96bd3fa9.png)

**Comment by weiwenhuaming01** [comment]
还有个问题问一下,滑动视频进度会播放滑动到进度的前面,对了,我设置的是ijkplayer

**Comment by weiwenhuaming01** [comment]
还有就是拖动进度条的时候没有转圈...

**Comment by lipangit** [comment]
1.这个改动很有必要，我会测试之后在之后的版本修改
2.对，进度跑偏的问题还没有很好的解决，从mediaPlayer中取得的进度就不是和滑动的进度一模一样的，你有什么办法吗
3.这个圈被干掉了，之后会考虑优化，在长时间没有加载的情况下才会显示，网络如果不卡，感觉它没有必要出现。
