### ISSUE TITLE
关于静音模式；

### ISSUE THREAD

**Issue by RXlung** [lipangit/JiaoZiVideoPlayer#1528]
首先感谢前辈，提供这么好的开源技术；感觉6.2.3有了很大的变化；
请问静音模式主要代码在哪，，  demo中放到哪了， 因为没找到(技术有点菜)， 问一下；

静音模式： 只静当前视频播放的声音，不影响系统其他声音；

**Comment by lipangit** [comment]
mediaPlayer.setVolum()方法应该可以静音，这个已经在计划之中，这块是自定义播放器的内容，可以参考demo的customMediaPlayer自定义播放器

**Comment by w0080626** [comment]
@RXlung 你的问题我有个解决方案 [#1549](https://github.com/lipangit/JiaoZiVideoPlayer/issues/1549)

**Comment by RXlung** [comment]
@w0080626    感谢

**Comment by lipangit** [comment]
demo已经有了一个例子，非全屏没有声音，全屏有声音
