### ISSUE TITLE
onStatePlaying();状态会回调两次

### ISSUE THREAD

**Issue by BuleB** [lipangit/JiaoZiVideoPlayer#1530]
#### onStatePlaying();状态会至少回调两次

- mediaPlayer 进入进入播放状态的时候会回调！
![image](https://user-images.githubusercontent.com/11595221/34767172-6ad8f0f0-f632-11e7-99a7-e8b098c4f4f1.png)
- 手动点击播放的时候也会调！
![image](https://user-images.githubusercontent.com/11595221/34767247-97c1c33a-f632-11e7-979c-c62890792c2a.png)

**Comment by lipangit** [comment]
一个是开始播放进入playing状态，一个是从暂停进入playing状态，具体是什么需求

**Comment by chenxi0203** [comment]
进入这个onStatePlaying()回调里面那怎么区分是从开始播放进入的playing还是从暂停后再进入的playing呢

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35423694-170e5262-028a-11e8-8399-c37fe4edcd08.png)
这个方法分辨不出来，只能在之前分辨，比如上图的点击就是暂停之后进入playing，这个onStatePlaying函数就是把当前状态设置成playing状态。

如果你想区分的话直接拦截resume的点击，或者拦截开始的点击
