### ISSUE TITLE
华为手机播放不了某些视频？

### ISSUE THREAD

**Issue by Destiny01** [lipangit/JiaoZiVideoPlayer#1532]
http://app.tianshengdiyi.com/upload/app/banner.mp4这个视频链接在华为荣耀4A手机上播放不了!

**Comment by lipangit** [comment]
LOG是什么，华为 nova 2s 正常播放

**Comment by ll418718** [comment]
楼主解决了吗

**Comment by lipangit** [comment]
怎么样了，随时沟通

**Comment by Destiny01** [comment]
视频源的问题，把视频帧数啥的调小一点就行了！

**Comment by Destiny01** [comment]
不是我调，就是做视频的人调小点，反正播放的都是自己服务器的视频

**Comment by lipangit** [comment]
对，就是想问做视频的如何调小帧数，这个帧数是每秒多少帧还是，还是什么关键帧
