### ISSUE TITLE
recyclerview列表播放，视频不可见时会修改Activity的主题

### ISSUE THREAD

**Issue by NFLeo** [lipangit/JiaoZiVideoPlayer#1539]

**Comment by lipangit** [comment]
咱们的代码和style没有任何关系。。 具体说说你的代码是怎么写的，或者其他你认为可能导致问题出现的地方

**Comment by NFLeo** [comment]
我项目使用的是Theme.AppCompat.Light.NoActionBar这种类型style， 
1、在视频列表播放时，播放item滑出可见区域时，界面顶部立马会多一个系统默认的标题栏，取消recycleview监听就不会出现标题栏。
2、点击重播的时候，也会出现标题栏

目前发现这两个地方触发

**Comment by NFLeo** [comment]
嗯，昨天看到了，已star，哈哈

**Comment by lipangit** [comment]
么么哒
