### ISSUE TITLE
4.4.2的系统视频播放黑屏

### ISSUE THREAD

**Issue by CleverSJX** [lipangit/JiaoZiVideoPlayer#1540]
4.4.2的系统视频播放黑屏, 系统自带播放播放器可以正常播放

**Comment by CleverSJX** [comment]
日志报错  Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering

01-13 09:49:44.708 2399-3761/com.longjing E/MediaPlayer: Should have subtitle controller already set
01-13 09:49:44.718 2399-2410/com.longjing E/MediaPlayer: error (1, -2147483648)
01-13 09:49:44.718 2399-3761/com.longjing E/MediaPlayer: Error (1,-2147483648)
01-13 09:49:44.728 2399-2399/com.longjing E/JiaoZiVideoPlayer: onError 1 - -2147483648 [-1639250264]

**Comment by CleverSJX** [comment]
视频链接 http://s.swao.cn/o_1c3n5oq2s1gcai5d1vm917hv1cps7.mp4  格式 h.264/avc  很普通的编码啊

**Comment by CleverSJX** [comment]
我在4.4.2的系统上 什么视频都播放不了

**Comment by lipangit** [comment]
新建个项目，单纯用textureView和MediaPlayer试试能播吗

**Comment by zengchao928** [comment]
哥们儿，怎么解决的，一模一样的啊 在原生上的都能播，用ijk播放是卡，然后exo还有system都有花屏的现象
