### ISSUE TITLE
Error only in emulator

### ISSUE THREAD

**Issue by MrDany** [lipangit/JiaoZiVideoPlayer#1541]
When i install APK in GenyMotion Emulator and AVD i get this error(Attached image). But on my cell phon i do not get this message! The Message is in chinese language. Thanks of chinese people.
![screenshot_1515829445](https://user-images.githubusercontent.com/21356342/34905859-d3b6793a-f876-11e7-93b3-3a39d771bfc9.png)
`Client not ready yet..Waiting for process to come online
Connected to process 1520 on device genymotion-google_galaxy_nexus___4_2_2___api_17___720x1280-192.168.142.101:5555
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/JiaoZiVideoPlayer: onClick start [1398328744] 
D/JiaoZiVideoPlayer: startVideo [1398328744] 
D/JiaoZiVideoPlayer: addTextureView [1398328744] 
I/JiaoZiVideoPlayer: onStatePreparing  [1398328744] 
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [1398328744] 
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
I/JiaoZiVideoPlayer: onVideoSizeChanged  [1398328744] 
E/JiaoZiVideoPlayer: onError 1 - -2147483648 [1398328744] 
I/JiaoZiVideoPlayer: onStateError  [1398328744] 
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JZResizeTextureView: onMeasure  [1398038332] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JiaoZiVideoPlayer: onTouch surfaceContainer actionDown [1398328744] 
I/JiaoZiVideoPlayer: onTouch surfaceContainer actionUp [1398328744] 
I/JiaoZiVideoPlayer: startProgressTimer:  [1398328744] 
D/JiaoZiVideoPlayer: addTextureView [1398328744] 
I/JiaoZiVideoPlayer: onStatePreparing  [1398328744] 
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [1398328744] 
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
I/JiaoZiVideoPlayer: onVideoSizeChanged  [1398328744] 
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
I/JZResizeTextureView: onMeasure  [1394564880] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 720]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 400]
E/JiaoZiVideoPlayer: onError 1 - -2147483648 [1398328744] 
I/JiaoZiVideoPlayer: onStateError  [1398328744] `

**Comment by lipangit** [comment]
do not test video in Emulator, in real phone please

**Comment by MrDany** [comment]
@lipangit thank you.
