### ISSUE TITLE
老铁 我只想使用播放器内核 用哪个类呢?

### ISSUE THREAD

**Issue by Greathfs** [lipangit/JiaoZiVideoPlayer#1547]
项目本身已经集成了播放器 包括 ijk exo vlc 等 ,统一的接口 控制界面都写好了 我现在就是想用咱们这个单纯的播放器, 不需要封装的播放器 这样我就能按我们项目中的接口统一封装了

**Comment by lipangit** [comment]
你项目里封装的ijk exo vlc的接口，要参考demo的自定义播放器来做，这块需要修改。

**Comment by Greathfs** [comment]
老铁 如果我不改我们的接口的话,我是不是就只能通过修改JZ源代码来实现这个需求了啊

**Comment by lipangit** [comment]
能解决问题就好，么么哒
