### ISSUE TITLE
关于问题描述总结，共10条！！

### ISSUE THREAD

**Issue by yangchong211** [lipangit/JiaoZiVideoPlayer#1550]
1.视频播放器全屏的时候，从竖直方向全屏切换到横向方法全屏，切换效果不太友好，建议添加锁定屏幕方向按钮！
2.华为手机mate8，当视频切换到横向全屏时，点击屏幕上的返回物理键，会显示导航栏。这个对于横向全屏展示不太好。
3.当手机是飞行模式时，点击播放视频，一直加载，应该显示加载失败或者提示没网吧。
4.在list页面(recyclerView)的视频，当上拉加载更多时，加载十几次会导致崩溃
5.进度条是跳动效果，能否平缓一点
6.当在一个页面滑动调节视频亮度时，然后停止播放，调到另一个页面播放视频，这个时候视频播放器亮度没有同步
7.缓冲这块，不知道缓冲了多少，进度条应该包括两部分，一个是播放进度，一个是缓冲进度，貌似大部分播放器都是这样的
8.对于切换视频清晰度，我看到代码案例是调用不同视频链接，所以切换清晰度后，又是重新开始播放，因为是不同的视频链接来源。就是不知道优酷，爱奇艺类似app怎么左右切换视频后还能接着原来的位置播放
9.感觉大神代码中注释好少，还有就是黄色警告实在太多了，不过大神封装思路和代码逻辑还是很牛的
10.模仿当前大神的思路和其他视频案例，我也封装了一款视频播放器，支持VIP视频播放权限设置，虽然有些bug，但是在持续更改中。以上这些只是我在阅读兄台代码时发现的问题，如果有不妥，请见谅，感谢大神。
我的开源项目地址：https://github.com/yangchong211/YCVideoPlayer

**Comment by lipangit** [comment]
意见非常在行

其中1 已经列入工作计划
2 3 4 8. 是bug，兄弟是如何修改的，希望能得到借鉴
5 这个在时间较短的视频里会出现，如何修改比较好
6 和头条是一样的
7 咱们有缓冲进度呀

**Comment by yangchong211** [comment]
好的，我也想想该怎么改，视频这块还得多多向大神学习！
