### ISSUE TITLE
有两个问题请教一下，都是关于列表视频的

### ISSUE THREAD

**Issue by YuxuanWoo** [lipangit/JiaoZiVideoPlayer#1553]
1.某一个item的视频播放结束后如何自动播放下一个item的视频
2.如何清除视频播放进度的缓存，现在是一直有记录的，就算退出app过了两天再打开，还是接着上次的地方播放

**Comment by lipangit** [comment]
1.复写onAutoComplete函数，取得播放完毕的监听，startVideo函数启动下一个视频的播放。大概流程是这样
2.JZVideoPlayer.clearSavedProgress() 清除缓存进度标志

**Comment by YuxuanWoo** [comment]
1.这样应该还是在这个item里播放的吧？如何让下一个item里的播放器播放？
2.这个方法我用过了，不起作用

**Comment by lipangit** [comment]
1. 可以在群里问问，应该有人实现过这个
2. 这是个bug，前天修复的，周日发版，key错误导致的
