### ISSUE TITLE
播放电视直播源的问题

### ISSUE THREAD

**Issue by ntrer** [lipangit/JiaoZiVideoPlayer#1555]
我播放直播源，第一次打开都正常，把当前的给暂停了播放其他的，然后再回来播放暂停的那个就无法播放了，我的链接：http://223.110.243.173/PLTV/3/224/3221225534/index.m3u8

报错：E/MediaPlayer: Error (-2147483648,0)
         E/MediaPlayer: Attempt to call getDuration in wrong state: mPlayer=0xc2040460,    mCurrentState=0
         E/MediaPlayer: error (-38, 0)

有时还报错：
E/PlaylistFetcher: failed to fetch .ts segment at url 'http://223.110.243.173/PLTV/3/224/3221225534/1516286818-1-1516146667.hls.ts

链接地址后缀/index.m3u8变成了/1516286818-1-1516146667.hls.ts

**Comment by ntrer** [comment]
看到了前面的两个外国人的提问，也就是说现在仍然对m3u8格式支持的不是很好吗

**Comment by ntrer** [comment]
我的上一个项目里用的是很早以前的版本jiecaoVideoPlayer，项目里也有播放直播源，那个就能很好的播放，这是为什么。

**Comment by lipangit** [comment]
jiecao用的哪个版本，是不是ijkplayer的版本

现在针对特殊的视频格式，可以一键切换播放引擎到ijkplayer

**Comment by ntrer** [comment]
额，那个项目我现在没有源代码，我也忘了是哪个版本了。。。
切换ijk是调用这句代码吗？
JZVideoPlayer.setMediaInterface(new JZMediaIjkplayer());

**Comment by lipangit** [comment]
对

**Comment by JamesGZM** [comment]
有解决这个问题吗
