### ISSUE TITLE
视频保存了进度，为什么还会重新播放

### ISSUE THREAD

**Issue by cbuemc** [lipangit/JiaoZiVideoPlayer#1556]
当前activity播放几秒后，返回上一界面，其中执行了JZVideoPlayer.releaseAllVideos()，再进入，重新播放时，会闪一下当前进度画面，然后就重新播放了，还有，saveProgress这个方法，是不是小于5000毫秒，就不保存？请问怎么解决进度保存的问题

**Comment by lipangit** [comment]
设计如此，5秒以内不保存进度，因为seekTo的时候有问题，如果非要保存进度到2s的话只能改库了
