### ISSUE TITLE
请教一下，这个支持播放mkv格式的视频么？支持本地播放？支持的话调用的是怎样调用？在线急啊！！！！

### ISSUE THREAD

**Issue by 1989David** [lipangit/JiaoZiVideoPlayer#1557]
请教一下，这个支持播放mkv格式的视频么？支持本地播放？支持的话调用的是怎样调用？我就没找到相关的类.支持4k的么？

**Comment by lipangit** [comment]
支持什么视频格式取决于用哪个播放器引擎，你可以一键切换到ijkplayer

支持本地的视频，demo有例子

**Comment by seaFeng** [comment]
怎么切换？

**Comment by lipangit** [comment]
@seaFeng 参考demo的ActivityApiCustomMediaPlayer
