### ISSUE TITLE
recycleview下滑的时候,视频小窗口不显示

### ISSUE THREAD

**Issue by RyomaFYx** [lipangit/JiaoZiVideoPlayer#1558]
![image](https://user-images.githubusercontent.com/20924164/35162710-201eef20-fd7f-11e7-93c8-a5a3a2a43a42.png)

![image](https://user-images.githubusercontent.com/20924164/35162773-4499a5ca-fd7f-11e7-9f2d-7bf5aba0bf87.png)
按照demo里写的，但是小窗口一直都不显示，不知道是啥原因，求大神指教！！十分感谢

**Comment by RyomaFYx** [comment]
视频已经播放了，放在页面的顶部banner ,往下拉的时候，小窗口不显示~~

**Comment by lipangit** [comment]
第一个图中断点那行后面的R.id.videoplayer，要改成你的item中视频空间的id

**Comment by RyomaFYx** [comment]
你好，我就是使用item中视频空间的id呢  @lipangit 
![image](https://user-images.githubusercontent.com/20924164/35180237-4a7f675a-fde7-11e7-9fbf-2b409d295a12.png)

**Comment by lipangit** [comment]
划出界面要断点onChildVidewDetachedFromWindow()，这个方法管滑出去，断点这里，看startWindowTiny是否进入，如果没进入，哪个if没通过

**Comment by RyomaFYx** [comment]
![image](https://user-images.githubusercontent.com/20924164/35202904-5b2adcf4-ff60-11e7-8660-06ef20a19047.png)

@lipangit 大神你好，我这边打了断点，是到了 if (((ViewGroup) view).indexOfChild(videoPlayer) != -1) ,这个方法没进去，再跟您说下我的布局，是recycleView第一个Item放了一个viewPager,然后viewpager里面放了两个fragment，然后第一个fragment放着您的视频视频控件，第二个fragment放着一些图片,这个布局是否有影响吗？请帮助一下好吗？谢谢！

**Comment by RyomaFYx** [comment]
好的，我抽象一下！您稍等

**Comment by RyomaFYx** [comment]
@lipangit  大神，我抽象好了，在我的github项目里 叫 JiaoZiVideoPlayerDemo 麻烦您看一下，十分感谢！！

**Comment by RyomaFYx** [comment]
大神,你看到了吗？~ @lipangit   我这边老板偏要加个小窗口播放的的功能，现在一直催着我，诶~~~

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35224824-49a0c62c-ffc1-11e7-8991-1804d333ef29.png)

现在的问题归结为无法判断划出或滑入的item是否包含视频，传的id可以是recycle item的id不一定非得是播放器的id，并且onChildViewDetachedFromWindow函数和onChildViewAttachedToWindow函数里面用的方法都是全局的可以复制出来单独使用

这个列表中视频固定在第一个item，更方便一些，只判断第一个item就好了

**Comment by RyomaFYx** [comment]
好的谢谢大神！感恩你的回答！ @lipangit
