### ISSUE TITLE
video缓存

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1564]
video缓存  这个不用导入依赖  直接就是缓存了是吧？

**Comment by guoyongxing** [comment]
我的如果是m3u8这种格式的  是不是就没有效果啊？

**Comment by lipangit** [comment]
1. 今天发新版的video缓存需要导入依赖才能缓存，安卓自带的缓存和安卓版本有关系

2. m3u8的问题测测先，我没试过

**Comment by guoyongxing** [comment]
那个m3u8好像是不行 那个m3u8文件 如果一开始断网 点击播放显示播放失败  这个是没问题的  当网络连接 在点击播放的时候  还是播放失败 cn.jzvd.demo E/JiaoZiVideoPlayer: onError 1 - -2147483648 [230832127] ？这个是缓存文件造成的？

**Comment by guoyongxing** [comment]
所以 我现在就是  判断是否是m3u8文件  如果是  就不用缓存了

**Comment by lipangit** [comment]
有办法就好

**Comment by FynnJason** [comment]
不缓存不是解决办法呀
