### ISSUE TITLE
有关自动重拨的问题

### ISSUE THREAD

**Issue by xlp-shawn** [lipangit/JiaoZiVideoPlayer#1565]
请问有播放结束的监听吗？这边想要在播放结束的时候自动重播

**Comment by lipangit** [comment]
looping=true自动重播

**Comment by xlp-shawn** [comment]
请问是在哪设置这个looping=true呢 是不是版本不一致 我这边没有这个属性，代码里设置页找不到这个api

![Uploading image.png…]()

**Comment by lipangit** [comment]
对对对，新版本改了，参考apiactivity，setUp的第一个参数
