### ISSUE TITLE
下载你的demo导入报错，请帮忙看下

### ISSUE THREAD

**Issue by mmmlee** [lipangit/JiaoZiVideoPlayer#1568]
Error:Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

**Comment by lipangit** [comment]
这种问题靠经验，慢慢研究老铁

**Comment by dongfangmingjia** [comment]
repository(url: "https://oss.sonatype.org/service/local/staging/deploy/maven2/") {
               authentication(userName: getProperty('ossrhUsername'),
                                 password: getProperty('ossrhPassword'))
           }

将这个注释掉即可

**Comment by lipangit** [comment]
么么哒 小可爱 @dongfangmingjia
