### ISSUE TITLE
进度条一直加载

### ISSUE THREAD

**Issue by chenxi0203** [lipangit/JiaoZiVideoPlayer#1571]
1:当连上的wif禁止访问这个在线视频地址时进度条一直加载，应该显示加载失败吧。
2:有些视频加载不出来的怎么设置加载失败的超时时间，有时候一分钟后才显示加载失败。

**Comment by lipangit** [comment]
1.这个是超时控制的
2.超时由播放器引擎控制，我也在找android.media.MediaPlayer怎么设置超时

**Comment by chenxi0203** [comment]
用的播放器引擎是ijk，mVideoPlayer.setMediaInterface(new MediaIjkplayer());
还有个问题，使用ijk作为播放器引擎时，偶尔会出现如下错误：
![image](https://user-images.githubusercontent.com/20221278/35366756-fed3cabc-01b5-11e8-843a-6e2d5a80a525.png)
想问下什么原因造成的，怎么解决，使用方式是拿到视频控件id后直接设置：mVideoPlayer.setMediaInterface(new MediaIjkplayer());

**Comment by lipangit** [comment]
怎么复现的，是不是直接操作MediaPlayer了
