### ISSUE TITLE
你好, 怎么实现一进来播放页面就开始播放,而不是点击播放按钮播放, 求速解决 ~  拜托了, 谢谢

### ISSUE THREAD

**Issue by OpenSourceMIUI** [lipangit/JiaoZiVideoPlayer#1572]

**Comment by lipangit** [comment]
调用jzvideoPlayerStandard.startButton.performClick() 吗，模拟用户点击开始播放，或者调用start Video（）函数，这个没有埋点事件。

如果着急的话可以在qq催我一下，github每天至少看一次

**Comment by OpenSourceMIUI** [comment]
谢谢      jzvideoPlayerStandard.startButton.performClick() 用这个方法实现了
