### ISSUE TITLE
Android studio 无法编译成功

### ISSUE THREAD

**Issue by seaFeng** [lipangit/JiaoZiVideoPlayer#1578]
![image](https://user-images.githubusercontent.com/19935751/35323787-b9a5f2bc-0129-11e8-8aaa-eda9c5c2f450.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35335794-75e59e10-0151-11e8-82df-7becb2364a34.png)

这个log记得见过，clean一下试试，这种问题只能多试，经验多了就好了
