### ISSUE TITLE
Enable landscape

### ISSUE THREAD

**Issue by LinkOut** [lipangit/JiaoZiVideoPlayer#1582]
Is it possibile to see video in landscaepe, only when it is full screen? (app i portrait only)

Thanks

**Comment by LinkOut** [comment]
Fixed this using: 
```

JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
```

**Comment by lipangit** [comment]
bravo

**Comment by LinkOut** [comment]
@lipangit Grazie 👍 Is there a way to setup something different to the "waiting to load" view? Because i am seeing chinese words and a low battery image... thanks

**Comment by lipangit** [comment]
language depends on the system language, if you have intrest you can add Italian in value.xml in pull request. but I think default language is English not chinese.

if want to make different ui , you can see ActivityApiUISmallChange, this will show you how to make custom ui.

**Comment by LinkOut** [comment]
![img](https://user-images.githubusercontent.com/4797287/35389291-6a311e7e-01d7-11e8-9e3e-06847dbcf852.jpg)

This is what i am talking about... this is shown for like 1 second before video loaded...

**Comment by lipangit** [comment]
you should call setUp() function, that image means current state is not been set

**Comment by LinkOut** [comment]
setUp(); is called after vimeo video fetching... This takes 1/2 seconds, in that period that image shows up... is there a way to remove it or not show?

**Comment by lipangit** [comment]
em, you need define a state called STATE_IDLE, in this state make ui before setUp,

**Comment by lipangit** [comment]
I think I will add this state in library.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35511163-dde3a254-0535-11e8-903a-7fa9bff8f614.png)


yes I remember, you can set this layout to define every view visible or invisible,

**Comment by digitalx-dev** [comment]
Ok so i need to override the getLayoutId? 

wha about this issue: 

![error](https://user-images.githubusercontent.com/19222118/36138135-7d182922-1098-11e8-93a8-791dd46197b9.jpg)

Thanks

**Comment by lipangit** [comment]
@digitalx-dev This image mean video in a wrong state, click to restart

**Comment by lipangit** [comment]
I will translate the words

**Comment by digitalx-dev** [comment]
I just want to know how to remove or customize the chinese views...

Thanks

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/commit/fee0ccd508521919825cbf9c231d9daf7d13dc1f
