### ISSUE TITLE
初始化的时候可以显示视频的第一帧吗

### ISSUE THREAD

**Issue by AwinHe** [lipangit/JiaoZiVideoPlayer#1584]
初始化的时候可以显示视频的第一帧吗

**Comment by lipangit** [comment]
成熟的方案都是分别保存视频和缩略图的。

**Comment by Guangxingtianxia** [comment]
成熟的方案？
什么意思？
现在有这个功能吗？

**Comment by lipangit** [comment]
@Guangxingtianxia 视频和缩略图要单独储存，不能只保存视频，然后缩略图从视频中取得

**Comment by scar1et** [comment]
服务端保存视频的时候直接从视频中获取缩略图分别保存，客户端请求数据时下来两个url，一个视频的一个缩略图的。

**Comment by lipangit** [comment]
是的

**Comment by EvilBT** [comment]
@AwinHe #1621
