### ISSUE TITLE
onStatePlaying()回调俩次

### ISSUE THREAD

**Issue by chenxi0203** [lipangit/JiaoZiVideoPlayer#1587]
onStatePlaying()在播放视频时会回调，在暂停播放后在继续播放时也会回调，想问下怎么判断是从Preparing后回调的还是从Pause后回调的。

**Comment by lipangit** [comment]
继承JZVideoPLayerStandard

复写onPrepared函数，是开始播放

复写onClick函数，监听开始按钮的点击，如果是暂停状态，就是pause的回掉，这个参考父类的onClick函数
