### ISSUE TITLE
暂停后快进再点击开始无法播放

### ISSUE THREAD

**Issue by wustor** [lipangit/JiaoZiVideoPlayer#1589]
当视频点击暂停之后，滑动进度条快进，然后再点击播放此时无法播放

**Comment by lipangit** [comment]
亲测，并不会，这种低级错误怎么会有呢，录个小视频看看

**Comment by wustor** [comment]
确实如此，视频链接http://211.152.60.252:8088/course/ABC/FB1/mv/FB1_1_1.mp4

**Comment by lipangit** [comment]
亲测也可以，就是有点慢，推荐使用第三方的cdn服务，可以变快

**Comment by wustor** [comment]
在网速比较慢的时候，没有出现的那个loading的圆形进度条，给人的感觉好像是没播放

**Comment by wustor** [comment]
还有就是可以用一个播放器进行同时播放网络跟本地视频吗，因为现在的需求是有缓存就读取缓存没有的话就直接读取网络资源，看了Demo，demo也无法播放本地视频

**Comment by lipangit** [comment]
demo里有播放本地视频的例子。

本身自带缓存功能，也可以引入第三方库videoplayercache，缓存视频，demo有例子

**Comment by lipangit** [comment]
视频一般都放到cdn上
