### ISSUE TITLE
大神，有没有办法在不播放视频的情况下(只有视频的网络地址),拿到视频的时长?  

### ISSUE THREAD

**Issue by zhangshaobo87** [lipangit/JiaoZiVideoPlayer#1590]
项目有上传视频 播放视频的功能,以前没有这个需求，所以上传的时候也没有将视频时长提交给服务器,现在版本更新,老板让显示视频时长,请问有啥办法吗

**Comment by lipangit** [comment]
在安卓中用MediaPlayer分别取得旧版的视频长度，然后在批量上传到服务器，这样视频就部分新版和旧版了，我认为
