### ISSUE TITLE
【建议】日后望能添加自定义的TextureView

### ISSUE THREAD

**Issue by 164738777** [lipangit/JiaoZiVideoPlayer#1592]
关于黑边问题，打算修改容器内视频的宽高，看了源码，貌似是在`JZResizeTextureView 里面的 onMeasure`修改的，打算自定义TextureView来修改onMeasure的方法，但是貌似好多地方都定死了用JZResizeTextureView

**Comment by lipangit** [comment]
黑边问题先参考demo的ActivityApiRotationVideoSize，试能不能解决

**Comment by 164738777** [comment]
Demo里面的ActivityApiRotationVideoSize是可以解决，但是有点极端？，，，因为需求只是打算适配视频的宽或者高，不在理想情况时候，任意一个按比例贴边即刻。Demo里面貌似只能都贴边？。。。

**Comment by lipangit** [comment]
复写onVideoSizeChanged函数，可以自行修改想要的视频高宽

**Comment by 164738777** [comment]
全屏旋转的时候，onVideoSizeChanged函数不被调用。。。

**Comment by lipangit** [comment]
现在只能在activity中监听全屏之后的旋转，然后调用textureView.requestLayout，启动onMeasure方法
