### ISSUE TITLE
android:screenOrientation="portrait" 为什么能横屏播放？

### ISSUE THREAD

**Issue by chenpdsu** [lipangit/JiaoZiVideoPlayer#1594]
android:screenOrientation="portrait"已设置
没有注册重力感应。为什么还能在全屏播放状态下进行横竖屏切换播放呢？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35509588-afac3fe6-052f-11e8-8239-2fb478237ce9.png)

这两个变量负责全屏前和全屏后的屏幕方向，结合orientationActivity，
