### ISSUE TITLE
关于怎么隐藏那个播放进度条和seekBar的问题

### ISSUE THREAD

**Issue by xlp-shawn** [lipangit/JiaoZiVideoPlayer#1595]
我浏览了相关的问题，可是还是不太理解父类中那些状态，可以说的稍微具体些吗？要改成什么状态才能隐藏播放进度条和seekBar

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35547344-78a4d5ec-05b3-11e8-9bcd-03379c5ffabc.png)

一共是这几种状态，第一步你要考虑的是seekBar在这几种状态下的显示与否，然后复写各个状态的函数，在各个状态下定义seekBar，复写函数参考demo的MyJZVideoPlayerStandard
