### ISSUE TITLE
在线mpg视频播放巨慢

### ISSUE THREAD

**Issue by weiwenhuaming01** [lipangit/JiaoZiVideoPlayer#1597]
使用原生大概要加载十几秒,切换使用ijkplayer播放不了

**Comment by weiwenhuaming01** [comment]
@lipangit

**Comment by weiwenhuaming01** [comment]
还有一个问题,原生的网络错误的监听回调是否过慢

**Comment by lipangit** [comment]
不就是mp4吗，研究一下格式话，是不是视频太大了，然后建议用cdn加速，放到第三方服务器上

**Comment by weiwenhuaming01** [comment]
@lipangit  
1.不是mp4,是.mpg格式加载很慢,换成MP4就很快
2.不切换播放引擎,如果没开网络,跳到网络异常的页面要等很久
3.就算没有开移动网络,只要之前开过,也会提示是否使用移动网络

**Comment by windfone** [comment]
加载mp4巨慢，得加载十几秒才能播放吧。换成ijkMediaPlayer 就很快，但是播放完 player 报空指针崩溃

**Comment by lipangit** [comment]
崩溃什么log解决了吗，速度取决于播放内核
