### ISSUE TITLE
列表自动播放用4G数据时反复提示是否播放问题

### ISSUE THREAD

**Issue by xuzh2017** [lipangit/JiaoZiVideoPlayer#1600]
每次视频加载进来WIFI_TIP_DIALOG_SHOWED都为false，点击取消后每个视频都要点击一次。。

**Comment by lipangit** [comment]
你觉得该怎么做，已经点了取消了，再开启下一个视频的时候你觉得该提示什么

**Comment by xuzh2017** [comment]
其实我本意是点击取消后在滑动其他视频不会提示是否播放了，意思就是用户不想用流量播放视频，因为列表还有不是视频的条目，也不会自动播放，就是显示需要点击播放的画面，现在想想这个需求确实很私人化

**Comment by lipangit** [comment]
第二次点击开始，什么也不提示，点击之后没反应吗

**Comment by lipangit** [comment]
需求是什么，然后遇到了什么问题，进群了吗，这个的描述有点看不懂
