### ISSUE TITLE
为什么我加载本地视频不能自动播放呢？

### ISSUE THREAD

**Issue by lihongwen1** [lipangit/JiaoZiVideoPlayer#1603]
JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.videoplayer);
        jzVideoPlayerStandard.setUp(preview_file_path, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, substring);

**Comment by lipangit** [comment]
自动播放是什么意思，你得点击开始按钮，或者代码启动播放

**Comment by lihongwen1** [comment]
加载本地的弄好了，现在我想播放本地音乐的时候显示图片，可以做到吗？ lihongwen 邮箱：lihongwen@sineva.com.cn 签名由 网易邮箱大师 定制 在2018年01月31日 12:13，Nathen 写道： 自动播放是什么意思，你得点击开始按钮，或者代码启动播放 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lipangit** [comment]
mp3 ，demo中添加了
