### ISSUE TITLE
视频详情页点击推荐视频重新setup有些视频加载失败

### ISSUE THREAD

**Issue by szd201208** [lipangit/JiaoZiVideoPlayer#1604]
在视频详情页下方有个推荐列表，当点击推荐当时候播放视频，重新setup,startvideo的时候有些视频可以播放，有些不能播放。

**Comment by upfind** [comment]
我也遇到同样的问题，还是播放的原来的视频。😭

**Comment by szd201208** [comment]
错误信息如下：
02-01 10:15:44.692 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
02-01 10:15:46.118 11819-11834/ E/BufferQueueProducer: [SurfaceTexture-0-11819-8] queueBuffer: BufferQueue has been abandoned
02-01 10:15:46.118 813-25310/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
02-01 10:15:46.118 813-25310/? E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
02-01 10:15:46.118 813-25310/? E/ACodec: signalError(omxError 0x80001001, internalError -19)
02-01 10:15:46.119 813-25309/? E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
02-01 10:15:46.119 813-25308/? E/NuPlayerDecoder: Decoder (video) reported error : 0xffffffed
02-01 10:15:46.119 813-25297/? E/NuPlayer: received error(0xffffffed) from video decoder, flushing(0), now shutting down
02-01 10:15:46.119 11819-11834/ E/MediaPlayer: error (1, -19)
02-01 10:15:46.119 11819-12076/ E/MediaPlayer: Error (1,-19)
02-01 10:15:46.120 813-25308/? E/NuPlayerDecoder: failed to flush OMX.qcom.video.decoder.avc (err=-38)
02-01 10:15:46.120 813-25297/? E/NuPlayer: received error(0xffffffda) from video decoder, flushing(2), now shutting down
02-01 10:15:46.120 11819-11834/ E/MediaPlayer: error (1, -38)
02-01 10:15:46.124 11819-12076/ E/MediaPlayer: Error (1,-38)
02-01 10:15:46.131 11819-11819/ E/JiaoZiVideoPlayer: onError 1 - -19 [116005009] 
02-01 10:15:46.131 11819-11819/ E/JiaoZiVideoPlayer: onError 1 - -38 [116005009] 
02-01 10:15:46.136 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf1726a30
02-01 10:15:46.137 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf1726950
02-01 10:15:46.138 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf1726870
02-01 10:15:46.138 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf17269c0
02-01 10:15:46.139 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf1726b10
02-01 10:15:46.140 813-25310/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf1726b80
02-01 10:15:46.151 11819-11875/ E/BufferQueueProducer: [SurfaceTexture-0-11819-8] connect: BufferQueue has been abandoned
02-01 10:15:46.152 804-20097/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:46.153 804-1635/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:46.158 804-20097/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:46.164 11819-12076/ E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
02-01 10:15:46.164 11819-12076/ E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
02-01 10:15:46.285 11819-11833/ E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                          java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
                                                              at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
                                                              at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
                                                              at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
                                                              at com.android.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:172)
                                                              at com.android.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:76)
                                                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:767)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
                                                              at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:211)
                                                              at android.media.MediaHTTPConnection.getMIMEType(MediaHTTPConnection.java:384)
                                                              at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:88)
                                                              at android.os.Binder.execTransact(Binder.java:565)
02-01 10:15:46.594 804-25319/? E/audio_hw_primary: disable_snd_device: spk_time=2517766, rcv_time=2535080.
02-01 10:15:47.271 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
02-01 10:15:47.931 810-11466/? E/OMXNodeInstance: setConfig(32a0235:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-01 10:15:47.931 810-11466/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
02-01 10:15:47.934 810-11466/? E/OMXNodeInstance: setConfig(32a0235:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
02-01 10:15:47.944 810-2681/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
02-01 10:15:47.944 810-2681/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
02-01 10:15:47.944 810-2681/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
02-01 10:15:47.947 810-810/? E/OMX-VDEC-1080P: Does not handle dataspace request
02-01 10:15:47.947 810-810/? E/OMXNodeInstance: getConfig(32a0234:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
02-01 10:15:47.973 804-2090/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:47.994 804-25351/? E/audio_hw_primary: out_set_volume: compress mute 0
02-01 10:15:47.995 804-25351/? E/audio_hw_primary: out_set_compr_volume:ctl for mixer cmd - Compress Playback 8 Volume, left 0.000000, right 0.000000
02-01 10:15:47.999 804-25351/? E/msm8974_platform: platform_check_backends_match: Invalid snd_device = 
02-01 10:15:48.012 810-18217/? E/OMX-VDEC-1080P: Does not handle dataspace request
02-01 10:15:48.013 810-18217/? E/OMXNodeInstance: getConfig(32a0234:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
02-01 10:15:48.049 810-1049/? E/OMX-VDEC-1080P: Does not handle dataspace request
02-01 10:15:48.050 810-1049/? E/OMXNodeInstance: getConfig(32a0234:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
02-01 10:15:48.052 804-25351/? E/audio_hw_dolby: audio_extn_dolby_ds2_set_endpoint: Dolby set endpint :0x2
02-01 10:15:48.054 804-25351/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
02-01 10:15:48.054 804-25351/? E/ACDB-LOADER: Error: ACDB AFE returned = -19
02-01 10:15:48.243 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
02-01 10:15:49.697 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
02-01 10:15:50.593 11819-11833/ E/BufferQueueProducer: [SurfaceTexture-0-11819-9] queueBuffer: BufferQueue has been abandoned
02-01 10:15:50.593 813-25342/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
02-01 10:15:50.593 813-25342/? E/ACodec: queueBuffer failed in onOutputBufferDrained: -19
02-01 10:15:50.594 813-25342/? E/ACodec: signalError(omxError 0x80001001, internalError -19)
02-01 10:15:50.594 813-25341/? E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
02-01 10:15:50.596 813-25340/? E/NuPlayerDecoder: Decoder (video) reported error : 0xffffffed
02-01 10:15:50.597 813-25330/? E/NuPlayer: received error(0xffffffed) from video decoder, flushing(0), now shutting down
02-01 10:15:50.598 813-25340/? E/NuPlayerDecoder: failed to flush OMX.qcom.video.decoder.avc (err=-38)
02-01 10:15:50.607 813-25330/? E/NuPlayer: received error(0xffffffda) from video decoder, flushing(2), now shutting down
02-01 10:15:50.625 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1d450
02-01 10:15:50.626 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1d4c0
02-01 10:15:50.628 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1dbc0
02-01 10:15:50.630 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1dc30
02-01 10:15:50.631 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1dca0
02-01 10:15:50.631 813-25342/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeff1dd10
02-01 10:15:50.647 11819-11834/ E/BufferQueueProducer: [SurfaceTexture-0-11819-9] connect: BufferQueue has been abandoned
02-01 10:15:50.651 804-2090/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:50.652 804-1635/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:50.713 804-2090/? E/AudioFlinger: open /proc/813/cmdline error
02-01 10:15:50.739 11819-12076/ E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
02-01 10:15:50.739 11819-12076/ E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
02-01 10:15:50.746 813-25360/? E/FileSource: Failed to open file ' http://p1o3tgdc2.bkt.clouddn.com/data/2018/01/08/1515383969801485'. (No such file or directory)
02-01 10:15:50.746 813-25360/? E/GenericSource: Failed to create data source!
02-01 10:15:50.747 11819-24880/ E/MediaPlayer: error (1, -2147483648)
02-01 10:15:50.748 11819-12076/ E/MediaPlayer: Error (1,-2147483648)
02-01 10:15:50.748 11819-11819/ E/JiaoZiVideoPlayer: onError 1 - -2147483648 [116005009] 
02-01 10:15:51.091 804-25351/? E/audio_hw_primary: disable_snd_device: spk_time=2517769, rcv_time=2535083.
02-01 10:15:52.277 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
02-01 10:15:54.702 645-2865/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]

**Comment by szd201208** [comment]
单独点击有问题的视频进入详情页是没有问题，可以正常播放的。

**Comment by szd201208** [comment]
找到原因了，是后台提供的链接有空格造成的。

**Comment by lipangit** [comment]
么么哒
