### ISSUE TITLE
横屏自动退出，没有日志

### ISSUE THREAD

**Issue by themass** [lipangit/JiaoZiVideoPlayer#1605]
<activity
            android:name=".ui.sound.VideoShowActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait" />
			
			
			<?xml version="1.0" encoding="utf-8"?>
<cn.jzvd.JZVideoPlayerStandard  xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/jz_video"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
	
	横屏 就自动退出，也没有崩溃日志。 哪里设置的有问题呢？

	  jzVideo.setUp(vo.actionUrl, JZVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, vo.title,header);
        jzVideo.headData = header;
        ImagePhotoLoad.loadCommonImg(this,vo.img,jzVideo.thumbImageView);
        JZVideoPlayer.setJzUserAction(new MyUserActionStandard());

**Comment by lipangit** [comment]
用法应该没有问题，demo也这样吗，manifest设置了吗
