### ISSUE TITLE
9:16的视频放到demo中的Recycleview列表中播放，点击全屏把手机横过来会闪退到列表，部分机型甚至会...

### ISSUE THREAD

**Issue by S-Co** [lipangit/JiaoZiVideoPlayer#1608]
部分机型甚至会崩溃。。。比如魅族 mx pro 6 plus

**Comment by lipangit** [comment]
log是什么，库什么版本

**Comment by Guangxingtianxia** [comment]
我的也会出现这种bug！

在recycleView 点击全屏按钮，手机横过来，就会crash！

**Comment by Guangxingtianxia** [comment]
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

android.widget.FrameLayout.layoutChildren(FrameLayout.java:591)

**Comment by lipangit** [comment]
哪个变量是空

**Comment by minitriangle** [comment]
我也遇到这个BUG, 列表播放，全屏-> 手机横过来 ->crash.
一次crash后重新打开正常。 一段时间后又这样

**Comment by minitriangle** [comment]
我的也这个错误
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
android.widget.FrameLayout.layoutChildren(FrameLayout.java:591)

**Comment by lipangit** [comment]
保持关注，改库了吗@minitriangle

**Comment by minitriangle** [comment]
@lipangit 嗯，继承 JZVideoPlayerStandard 改的，重写了wifi对话框，还有添加了改字体的一个方法，没有别的

**Comment by lipangit** [comment]
断点mediaplayer.release()，看看是不是横屏的时候有地方调它了

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35972153-a1fa1c22-0d0b-11e8-8188-3f20d119af1a.png)

**Comment by minitriangle** [comment]
@lipangit 确实调它了，然后crash，还没看完信息就消失了,  不过一次那样后就正常了，所以很难捕获了

**Comment by lipangit** [comment]
想抓住这种log别设置过滤filter，查看所有log，可以取得log

**Comment by minitriangle** [comment]
[http://img1001.pocoimg.cn/image/poco/works/10/2018/0215/13/15186723993504812_63579410_H960.jpg](url)
@lipangit

**Comment by lipangit** [comment]
是不是recycleview的最后一个item的全屏会闪退，这个问题已经修改

**Comment by S-Co** [comment]
你在网上随便找个9:16的视频源放到列表中去，就会出现找个问题，最新的也有。

**Comment by lipangit** [comment]
@S-Co 发个链接，找不到。。。 是最后一个item全屏闪退的问题吗
