### ISSUE TITLE
能否播放m3u8直播流吗？

### ISSUE THREAD

**Issue by kulong51** [lipangit/JiaoZiVideoPlayer#1610]
能否播放m3u8直播流吗？

**Comment by lipangit** [comment]
切换播放器引擎到ijkplayer或者exoplayer，参考demo

**Comment by lipangit** [comment]
m3u8 你需要式，理论上支持 https://developer.android.com/guide/topics/media/media-formats.html#sample

**Comment by kulong51** [comment]
非常感谢您的帮助
