### ISSUE TITLE
协议

### ISSUE THREAD

**Issue by linxizheng** [lipangit/JiaoZiVideoPlayer#1611]
支持rtmp协议吗？要做直播啊。

**Comment by lipangit** [comment]
切换播放器引擎到ijkplayer或者exoplayer，参考demo

**Comment by wdmxzfG** [comment]
播放RTMP 是这样改的么？
![2018-09-05 11 17 20](https://user-images.githubusercontent.com/30021754/45069144-a407f700-b0fd-11e8-946b-5bdfeca99a90.png)

**Comment by lipangit** [comment]
能不能播取决于播放器引擎是否支持
切换播放器引擎，参考demo的customMediaPlayer
