### ISSUE TITLE
使用ijk的内核，布局设为16:9，播放视频的时候会自动把9:16的视频横过来填满布局，麻烦问下该如何设置才能避免？

### ISSUE THREAD

**Issue by 562134391** [lipangit/JiaoZiVideoPlayer#1617]

**Comment by 562134391** [comment]
已经解决了
![image](https://user-images.githubusercontent.com/13347100/35837956-d324720a-0b23-11e8-86f2-1aaf1b0000b9.png)
播放器oninfo里调用

**Comment by 562134391** [comment]
或者在配置文件里设置成硬件解码，不过据说这样可能会黑屏或没声音
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);

**Comment by lipangit** [comment]
好 么么哒
