### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by JameChen** [lipangit/JiaoZiVideoPlayer#1619]
请问怎么缓存呀，怎么每次播放都有转圈圈好久，感觉每次都耗流量，能像微信那样缓存吗下次点不要网络也能播放的

**Comment by lipangit** [comment]
1.android.media.MediaPlayer有缓存机制，但是高级别的安卓版本才支持，6.0以上经过测试16M以下视频永久缓存
2.参考demo，引入第三方库缓存视频
3.用其他播放器引擎缓存视频，比如ijkplayer exoplayer
