### ISSUE TITLE
小疑惑

### ISSUE THREAD

**Issue by Chihiro23333** [lipangit/JiaoZiVideoPlayer#1620]
目前代码是管理了两个JZVideoPlayer,请问如何实现在全屏和非全屏切换时两边新加的自定义监听的统一.我例如我在自定义界面继承JZVideoPlayer时新加了几个boolean值变量(有默认值),再点击摸个部分的时候会变化,然后点击全屏的时候实际上是相当于new了一个JZVideoPlayer,新的JZVideoPlayer里面的boolean值是默认值.
请问是不是只有在全屏的时候对bollean值进行重新赋值一种解决办法.

**Comment by lipangit** [comment]
参考setUp的最后一个变量，objects[]数组，这个变量可以在全屏和非全屏间传递
