### ISSUE TITLE
无意间发现Glide有获取视频某帧的方法

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [lipangit/JiaoZiVideoPlayer#1621]
/**
     *       
               有个0- 到1秒的延迟
     * @param context        上下文
     * @param uri      视频地址
     * @param imageView   设置image
     * @param frameTimeMicros   获取某一时间帧
     */

    public static void loadVideoScreenshot(final Context context, String uri, ImageView imageView, long frameTimeMicros) {
        RequestOptions requestOptions = RequestOptions.frameOf(frameTimeMicros);
        requestOptions.set(FRAME_OPTION, MediaMetadataRetriever.OPTION_CLOSEST);
        requestOptions.transform(new BitmapTransformation() {
            @Override
            protected Bitmap transform(@NonNull BitmapPool pool, @NonNull Bitmap toTransform, int outWidth, int outHeight) {
                return toTransform;
            }
            @Override
            public void updateDiskCacheKey(MessageDigest messageDigest) {
                try {
                    messageDigest.update((context.getPackageName() + "RotateTransform").getBytes("utf-8"));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        Glide.with(context).load(uri).apply(requestOptions).into(imageView);
    }

 compile 'com.github.bumptech.glide:glide:4.0.0-RC1'  glide 版本
提供有需要的人

**Comment by lipangit** [comment]
笔芯，爱你 ^_^

**Comment by EchoKoreyoshi** [comment]
嗯

**Comment by lipangit** [comment]
再找找，不要灰心

**Comment by wj576038874** [comment]
预览画面  如何取视频  显示一个gif呢

**Comment by lipangit** [comment]
预览画面是什么意思

**Comment by Mrliuchuang** [comment]
你好 我的是华为的手机不显示缩略图需要怎么办

**Comment by lipangit** [comment]
需要更多信息。它就是张图片，与播放逻辑无关



---原始邮件---
发件人: "Mrliuchuang"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 晚上9:18
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 无意间发现Glide有获取视频某帧的方法 (#1621)




 
你好 我的是华为的手机不显示缩略图需要怎么办
