### ISSUE TITLE
在android8.0上 JZVideoPlayer.releaseAllVideos(); 这句代码导致应用崩溃

### ISSUE THREAD

**Issue by zhangshaobo87** [lipangit/JiaoZiVideoPlayer#1622]
Unable to pause activity {com.shanai.ppx/com.shanai.ppx.videoplay.VideoPlayActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation

网上的解决方案是说不能设置activity背景透明，但是我看了我自己的设置我根本没有设置背景透明,请问作者是不是播放器哪里做了设置了呢?

**Comment by lipangit** [comment]
库没有对style的任何设置，只是在8.0上有问题吗，其它安卓版本呢

**Comment by zhangshaobo87** [comment]
只在8.0有这个问题,其他都是OK的

**Comment by lipangit** [comment]
兄弟，手动调用这行函数，看能不能出问题，加个按钮，点一下就调一次，我觉得应该不是releaseAllVideos的问题

**Comment by zhangshaobo87** [comment]
好的，我试试看

**Comment by zhangshaobo87** [comment]
蛋疼 我自己测试复现不了,不知道线上咋崩滴，我先把这个close了

**Comment by XuQK** [comment]
这是8.0系统的一个bug，今天也碰到了，具体情况参见： https://zhuanlan.zhihu.com/p/32190223

**Comment by XuQK** [comment]
@lipangit 这个从上面我回复里的链接来看，是因为8.0的那个bug，因为我要用侧滑退出activity的库，故把当前activity的主题属性设置了`windowIsTranslucent=true`，然后在releaseAllVideos方法中又调用了`JZUtils.setRequestedOrientation(getContext(), NORMAL_ORIENTATION);`方法，所以导致崩溃。
是不是能想个办法绕过一下呢？比如检测到当前系统是8.0，且当前activity主题`windowIsTranslucent=true`就不执行`JZUtils.setRequestedOrientation(getContext(), NORMAL_ORIENTATION);`方法？

**Comment by lipangit** [comment]
这个8.0的时候全屏之后如何横屏

**Comment by lipangit** [comment]
现在问题找到了，有没有更系统的解决办法

**Comment by XuQK** [comment]
@lipangit 全屏横屏是没有问题的，只是退出当前`windowIsTranslucent=true`的activity的时候，`releaseAllVideos`方法里那次`setRequestedOrientation`方法调用会导致`java.lang.IllegalStateException: Only fullscreen activities can request orientation`异常导致崩溃。
这个弄个8.0的模拟器应该能100%复现。

我目前是在自定义播放器里重写`onCompletion()`方法，在`setRequestedOrientation`那里加个判断：
```java
int[] attr = new int[]{android.R.attr.windowIsTranslucent};
TypedArray typedArray = getContext().getTheme().obtainStyledAttributes(attr);
boolean isTranslucent = typedArray.getBoolean(0, false);

if (Build.VERSION.SDK_INT != Build.VERSION_CODES.O || !isTranslucent) {
    JZUtils.setRequestedOrientation(getContext(), NORMAL_ORIENTATION);
}
```

这样暂时是还没发现什么别的问题。我只能这样绕过了，至于解决它，已经超出我现阶段的能力范围了 ╮(╯▽╰)╭

**Comment by lipangit** [comment]
漂亮，绕过也是一种解决。
