### ISSUE TITLE
怎么直接全屏横屏播放

### ISSUE THREAD

**Issue by chenxi0203** [lipangit/JiaoZiVideoPlayer#1624]
如标题，基于demo：JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
JZVideoPlayerStandard.startFullscreen(this, JZVideoPlayerStandard.class, VideoConstant.videoUrlList[6], "饺子辛苦了");     这样横屏不行，只使用下面那句只能全屏竖屏播放，但是做点击事件触发全屏播放时像点击啦俩次，demo也有这个问题，而且这个不能跳转到我们定义的视频播放界面直接全屏吗？

**Comment by xuzh2017** [comment]
//    public static int FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR; //纵向全屏
    public static int FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;//横向全屏

**Comment by xuzh2017** [comment]
JZVideoPlayer里面配置

**Comment by lipangit** [comment]
直接全屏播放参考demo的ActivityDirectPlay

**Comment by chenxi0203** [comment]
demo 看啦，demo那种方式本身也有点问题，点击一下，响应啦俩个点击事件，会响俩次触发点击事件的声音。

**Comment by lipangit** [comment]
！！ 真的吗，我试试
