### ISSUE TITLE
java.lang.Object.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by kimnamcham** [lipangit/JiaoZiVideoPlayer#1626]
FATAL EXCEPTION: main
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                     at cn.jzvd.JZMediaManager.onSurfaceTextureAvailable(JZMediaManager.java:109)

When click video thumb if link error, it will crash

**Comment by lipangit** [comment]
did you change the library, does it hanppe in demo?

**Comment by kimnamcham** [comment]
No i don't change the library. It's on my project, when setup url has stream error

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/35972292-2c44498e-0d0c-11e8-9afa-21594cd5c6c8.png)

![image](https://user-images.githubusercontent.com/2038071/35972296-33cddc10-0d0c-11e8-94fe-15163bc749a3.png)

break point where savedSurfaceTexture = null, check when it goes on a wrong time

**Comment by kimnamcham** [comment]
I think must have check when curren jzvd null, if i use in recyclerview, when network slow, this issuse sometime happend

    @Override
    public void onSurfaceTextureAvailable(SurfaceTexture surfaceTexture, int i, int i1) {
        if(JZVideoPlayerManager.getCurrentJzvd() != null)
        {
            Log.i(TAG, "onSurfaceTextureAvailable [" + JZVideoPlayerManager.getCurrentJzvd().hashCode() + "] ");
            if (savedSurfaceTexture == null) {
                savedSurfaceTexture = surfaceTexture;
                prepare();
            } else {
                textureView.setSurfaceTexture(savedSurfaceTexture);
            }
        }
    }

**Comment by lipangit** [comment]
This function goes before prepare() MediaPlayer, It does not know the network situation.

![image](https://user-images.githubusercontent.com/2038071/36035542-269c4b62-0df2-11e8-9266-61df53f41691.png)
This line just begin to prepare video and connect the net work

**Comment by lipangit** [comment]
if the check is work, if the check will fix the issue, can you help to find out when the onSurfaceTextureAvailable function called again.
