### ISSUE TITLE
视频播放自动判断横竖屏问题

### ISSUE THREAD

**Issue by ym1808620172** [lipangit/JiaoZiVideoPlayer#1628]
建议添加一个判断视频是横屏拍摄还是竖屏拍摄的方法。不然横屏拍的视频全屏播放的时候有很多黑边

**Comment by ym1808620172** [comment]
列表播放器可以考虑和微博类似，不等比缩放，裁剪到中间一部分即可。要不然大黑边真的丑

**Comment by lipangit** [comment]
参考demo的ActivityApiRotationVideoSize，可以剪裁图像
