### ISSUE TITLE
wifi下可以正常播放视频，但是4G下进度条一直转圈，放不了

### ISSUE THREAD

**Issue by ymw2017** [lipangit/JiaoZiVideoPlayer#1630]
公司wifi可以播放app中的视频，4G下放饺子demo中的视频也可以，但是我用4G播放自己app的视频时进度条一直转圈，确认视频是好的，网页上也可以播放，我手机4G下看头条视频加载也很快，请教这是什么原因呢？

**Comment by lipangit** [comment]
这个问题确认一下是否在手机系统级别允许使用流量，因为在咱们这层就是给mediaplayer怼url，wifi和4g是没有区别的，如果还没解决可以把url发给我试试。
