### ISSUE TITLE
能否增加个2倍速度播放，感谢

### ISSUE THREAD

**Issue by MirrorFlower** [lipangit/JiaoZiVideoPlayer#1631]
能否增加个2倍或者多倍速度播放，感谢

**Comment by lipangit** [comment]
可以，参考android.media.MediaPlayer的setParam函数

**Comment by Chihiro23333** [comment]
将mediaplayer设置使用Iikplayer然后可以在播放时运用setSpeed方法调整播放速度

**Comment by lipangit** [comment]
对，更换播放器引擎也可以
