### ISSUE TITLE
demo报  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference

### ISSUE THREAD

**Issue by xuefeiyao** [lipangit/JiaoZiVideoPlayer#1632]
Api按钮进入再点击CUSTOM MEDIAPLAYER按钮进入下一个页面播放视频播放视频，然后点击视频下随便一个按钮闪退，报这个错

**Comment by lipangit** [comment]
CUSTOM MEDIAPLAYER 这块必须得改代码才能正常测试，这里就是告诉你如何一行代码修改MediaPlayer，ijkplayer不配这个界面的jzvd，他们不是配套的
