### ISSUE TITLE
/storage/emulated/0/tencent/MicroMsg/sns_ad_landingpages/adId_sight_e3ea04b36984294be8fdf7a9e14d13d1这是本地的微信短视频地址无法播放，进度条一直在转，/storage/emulated/0/DCIM/mabeijianxi/1518400573147/1518400573147.mp4这种是自己录制的短视频也是一样的不能播放，请问如何播放从本地选择的视频?

### ISSUE THREAD

**Issue by xuefeiyao** [lipangit/JiaoZiVideoPlayer#1634]

**Comment by xuefeiyao** [comment]
Intent it = new Intent(Intent.ACTION_GET_CONTENT,
                        MediaStore.Video.Media.EXTERNAL_CONTENT_URI);

                it.setDataAndType(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, "video/*");
                startActivityForResult(it, CHOOSE_CODE);
这是本地选择视频的代码
 private String getRealPathFromURI(Uri contentURI) {
        String result;
        Cursor cursor = getContentResolver().query(contentURI, null, null, null, null);
        if (cursor == null) { // Source is Dropbox or other similar local file path
            result = contentURI.getPath();
            Log.e("auth",contentURI.getEncodedPath());
        } else {
            cursor.moveToFirst();
            int idx = cursor.getColumnIndex(MediaStore.Images.Media.DATA);
            int type = cursor.getColumnIndex(MediaStore.Images.Media.MIME_TYPE);
            result = cursor.getString(idx);
            String mediaType = cursor.getString(type);
            Toast.makeText(this, "哈哈哈" + mediaType + "呃呃呃" + result, Toast.LENGTH_SHORT).show();
            cursor.close();
        }
        return result;
    }
这是获取本地url代码

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/36154490-9b6812a6-110c-11e8-88f9-537d7cb7665e.png)

播放本地视频的例子在这里

**Comment by lipangit** [comment]
这个就是路径的问题

**Comment by longhunpeter** [comment]
我也遇到同样的问题请问有解决吗

**Comment by lipangit** [comment]
只是路径问题，问问群里是否有其他朋友解决
