### ISSUE TITLE
when click tinyPreview move list to the position which that video was

### ISSUE THREAD

**Issue by Monster-king** [lipangit/JiaoZiVideoPlayer#1635]
I want to add feature that when click tiny preview, video list must return to the position of video which that tiny video was created. But if list was very far from that item which tiny video was, NullPointerException was occurring.

**Comment by Monster-king** [comment]
The problem was, when list position very far from video position, and it scrolls very fast, video view can't update its state and crashes.

**Comment by lipangit** [comment]
what is the log
