### ISSUE TITLE
Mute and unMute implementation

### ISSUE THREAD

**Issue by rajiniyadav** [lipangit/JiaoZiVideoPlayer#1636]
How to control mute and unmute like Face book video's handling once mute then all video's in recycler view playing mute only same vice versa ....please help us to achieve this

**Comment by lipangit** [comment]
the feature is not in demo, but you can see 饺子摇摆 in ActivityApiUISmallChange in demo, this show you NORMAL_SCREEN is mute and FULL_SCREEN is unmute
