### ISSUE TITLE
how set SCREEN_WINDOW_NORMAL again when full screen 

### ISSUE THREAD

**Issue by miaaad** [lipangit/JiaoZiVideoPlayer#1638]
i set this player in fragment and when player is full screen i click on backPressd then close my activity .

i dont want close activity  just  set screen_window _normal.

thanks for wonderful lib

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/36353155-8444ca5c-14fd-11e8-8e25-b09c2143e80d.png)

did you add these code?

**Comment by miaaad** [comment]
tanx bro you save me

**Comment by lipangit** [comment]
good
