### ISSUE TITLE
更换ijk问题 

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [lipangit/JiaoZiVideoPlayer#1639]
这里只是跟换播放引擎，是不是跟换了，jiaozi的逻辑不能用，所有逻辑都要写ijk的逻辑包括UI

**Comment by lipangit** [comment]
demo有ijkplayer 的例子，更换之后毫无影响，只需要修改一行代码，其他的都不用改

现在本质上jzvd只是一个接口，和什么播放器引擎已经拆分的非常独立了

**Comment by AOWOAO** [comment]
修改那一行代码切换ijk啊，WIKI里面也不写

**Comment by lipangit** [comment]
wiki需要再完善完善

看demo的ActivityApiCustomMediaPlayer

**Comment by ymw2017** [comment]
群主，我用这句话切换ijk还是会报错，   JZVideoPlayer.setMediaInterface(new JZMediaIjkplayer());
还需要引入其他什么吗？

**Comment by lipangit** [comment]
在gradle中引入ijkplayer的配置
