### ISSUE TITLE
Thumbnail does not display in fullscreen mode

### ISSUE THREAD

**Issue by Muriti** [lipangit/JiaoZiVideoPlayer#1641]
I found a problem that this library can not display thumbnail image in fullscreen mode. Can you help me resolve this problem? Thanks.

**Comment by lipangit** [comment]
This is a kind of custom JZVideoPlayer

Extends JZVideoPlayerStandard , override some function, and display thumbnail image when current_window == SCREEN_FULLSCREEN

**Comment by lipangit** [comment]
Can you understandard

**Comment by Muriti** [comment]
yes, I got it. Thank you.
