### ISSUE TITLE
华为荣耀8 点击视频不能播放

### ISSUE THREAD

**Issue by AmberWhiteSky** [lipangit/JiaoZiVideoPlayer#1642]
华为荣耀8
最新的饺子播放器
点击视频 不能播放。
视频地址：http://222.134.66.179/xdispatch/videoplay-hls.51livetech.com/recordings/z1.leju-live-2.EL0000079778/20170611110340--z1.leju-live-2.EL0000079778-278257.mp4
logcat
02-24 16:25:40.739 1232-1232/? I/TrafficMonitor: expired arrive. level:-1
02-24 16:25:40.739 1232-1232/? I/TrafficMonitor: during_ms:2002,period_ms:2000
02-24 16:25:40.739 1232-1232/? I/TrafficMonitor: count:435,rx_sum:0,tx_sum:0,rxBytes:0,during_ms:2002,rx_speed:0.0,tx_speed:0.0,rto:0.0
02-24 16:25:41.742 1232-1232/? I/TrafficMonitor: update:rxPkts:0,txPkts:0,rxBytes:0,txBytes:0
02-24 16:25:41.742 1232-1232/? I/TrafficMonitor: start expired. level:-1
02-24 16:25:41.742 1232-1232/? I/TrafficMonitor: gettimer:interval=2000
02-24 16:25:41.825 1599-1599/? I/NetworkSpeedManagerEx: mIsStop = false
02-24 16:25:41.827 1599-1599/? I/NetworkSpeedManagerEx: value=0.0speed = 0K/s
02-24 16:25:41.827 1599-1599/? I/NetworkSpeedView: /update(), speed=0K/s parent class:class com.android.systemui.statusbar.HwSystemIcons
02-24 16:25:41.856 1599-1599/? I/NetworkSpeedManagerEx: mIsStop = false
02-24 16:25:41.858 1599-1599/? I/NetworkSpeedManagerEx: value=0.0speed = 0K/s
02-24 16:25:41.858 1599-1599/? I/NetworkSpeedView: /update(), speed=0K/s parent class:class com.android.systemui.statusbar.HwSystemIcons
02-24 16:25:42.613 17697-17697/? I/SendBroadcastPermission: action:null, mPermissionType:0
02-24 16:25:43.307 20343-20343/com. I/JiaoZiVideoPlayer: onClick start [91823732] 
02-24 16:25:43.311 1232-1298/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10842/20343 clientId=android.media.AudioManager@4b1ba32cn.jzvd.JZVideoPlayer$1@b13b383 req=2 flags=0x0
02-24 16:25:43.313 20343-20343/com. I/JiaoZiVideoPlayer: onStatePreparing  [91823732] 
02-24 16:25:43.313 1842-1932/? I/AppManager: audio start play: com.
02-24 16:25:43.338 20343-20343/com. I/JiaoZiVideoPlayer: onCompletion  [91823732] 
02-24 16:25:43.338 20343-20343/com. I/JiaoZiVideoPlayer: onStateNormal  [91823732] 
02-24 16:25:43.339 20343-20343/com. I/AudioManager: abandonAudioFocus
02-24 16:25:43.340 1232-2041/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10842/20343 clientId=android.media.AudioManager@4b1ba32cn.jzvd.JZVideoPlayer$1@b13b383
02-24 16:25:43.743 1232-1232/? I/TrafficMonitor: update:rxPkts:0,txPkts:0,rxBytes:0,txBytes:0
02-24 16:25:43.743 1232-1232/? I/TrafficMonitor: start expired. level:-1
02-24 16:25:43.743 1232-1232/? I/TrafficMonitor: gettimer:interval=2000
02-24 16:25:44.575 1232-1232/? I/QosMonitor: queryRtt: rtt_type = 3
02-24 16:25:44.575 1232-1232/? I/WifiProJNI: ######### GET RTT:3 ########
02-24 16:25:44.575 1232-1445/? I/HuaweiWifiWatchdogStateMachine: spd good count:0, add sc:0.0, rate:1.0
02-24 16:25:44.575 1232-1443/? I/QosMonitor: postEventFromNative: msg=100,arg1=4,arg2=9
02-24 16:25:44.575 1232-1445/? I/HuaweiWifiWatchdogStateMachine: current mHighDataFlowRate = 1.0
02-24 16:25:44.575 1232-1443/? W/WifiProJNI: poll before: g_monitor_fd =250
02-24 16:25:44.575 1232-1445/? I/HuaweiWifiWatchdogStateMachine: POta txb txg rxg:0, 8, 0. Lr =0% Totpkt=8
02-24 16:25:44.575 1232-1232/? I/WifiProJNI: ######### CMD_QUERY_PKTS ########
02-24 16:25:44.576 1232-1443/? I/QosMonitor: postEventFromNative: msg=100,arg1=0,arg2=9
02-24 16:25:44.576 1232-1443/? W/WifiProJNI: poll before: g_monitor_fd =250
02-24 16:25:44.576 1232-1232/? I/MQoS: rtt=340,tcp_tx_pkts=259940,tcp_rx_pkts=302094
02-24 16:25:44.576 1232-3297/? I/MQoS: QOS_level:0(0),DataDisable;use level-0
02-24 16:25:44.578 1232-1445/? I/HuaweiWifiWatchdogStateMachine: PTcp RTT:0, rtt pkt=0, tcp_rx=0, tcp_tx=0, tcp_reTran=0, rtRate=0
02-24 16:25:44.830 1599-1599/? I/NetworkSpeedManagerEx: mIsStop = false
02-24 16:25:44.832 1599-1599/? I/NetworkSpeedManagerEx: value=0.0speed = 0K/s
02-24 16:25:44.832 1599-1599/? I/NetworkSpeedView: /update(), speed=0K/s parent class:class com.android.systemui.statusbar.HwSystemIcons
02-24 16:25:44.858 1599-1599/? I/NetworkSpeedManagerEx: mIsStop = false
02-24 16:25:44.861 1599-1599/? I/NetworkSpeedManagerEx: value=0.0speed = 0K/s
02-24 16:25:44.861 1599-1599/? I/NetworkSpeedView: /update(), speed=0K/s parent class:class com.android.systemui.statusbar.HwSystemIcons

**Comment by AmberWhiteSky** [comment]
点击视频之后的log日志

02-24 16:32:23.270 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onClick start [125352112] 
02-24 16:32:23.274 1232-1855/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10842/20343 clientId=android.media.AudioManager@4b1ba32cn.jzvd.JZVideoPlayer$1@b13b383 req=2 flags=0x0
02-24 16:32:23.276 1842-1932/? I/AppManager: audio start play: com.eju.mobile.leju.newoverseas
02-24 16:32:23.277 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onStatePreparing  [125352112] 
02-24 16:32:23.285 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onStateNormal  [57236657] 
02-24 16:32:23.290 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onCompletion  [125352112] 
02-24 16:32:23.290 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onStateNormal  [125352112] 
02-24 16:32:23.291 20343-20343/com.eju.mobile.leju.newoverseas I/AudioManager: abandonAudioFocus
02-24 16:32:23.292 1232-2417/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10842/20343 clientId=android.media.AudioManager@4b1ba32cn.jzvd.JZVideoPlayer$1@b13b383
02-24 16:32:23.297 20343-20343/com.eju.mobile.leju.newoverseas I/JiaoZiVideoPlayer: onStateNormal  [57236657]

**Comment by AmberWhiteSky** [comment]
华为手机 HUAWEI FRD-AL00

**Comment by lipangit** [comment]
你是阿智 ^_^

**Comment by AmberWhiteSky** [comment]
已经解决，是我自己的代码问题。大佬关闭这个iss吧。
