### ISSUE TITLE
发现同一个url第一次播放正常，第2次无法播放问题及导致此问题的原因之1

### ISSUE THREAD

**Issue by yangyaobo** [lipangit/JiaoZiVideoPlayer#1644]
问题：同一个url，第一次播放正常， 第2次播放一致在加载的状态，且一进播放界面就调用onCompletion()方法

导致的原因：第一次播放退出时(可以根据实际情况在onPause()或onDestroy()生命周期中)没有JZVideoPlayer.releaseAllVideos();方法释放视频， 导致重新进播放界面时。

**Comment by lipangit** [comment]
嗯 这是个大问题，怎么解决呢

**Comment by yanfulei** [comment]
应该是记录播放位置造成的，你可以尝试在url后面加上?uuid=xxxxx这种方式，就可以解决了

**Comment by safei37** [comment]
不是记录播放位置的问题，设置 JZVideoPlayer.SAVE_PROGRESS=false就不会记录播放位置了，但是仍然会出现题主说的这个情况，而且包括作者提供的视频url都会如此，不知道有人能解决这个问题吗

**Comment by safei37** [comment]
@lipangit

**Comment by yanfulei** [comment]
@safei37 我是这样临时解决的，在url后面加上?uuid=xxxxx这种方式。如果你急着用也可以试试

**Comment by safei37** [comment]
什么意思？可以说得详细点吗？还请不吝赐教~~~ @yanfulei

**Comment by safei37** [comment]
uuid=xxxxx，这里的xxxxx是随机数的意思吗？即每次读取url都不同？ @yanfulei

**Comment by yanfulei** [comment]
@safei37 是的，随机数。

**Comment by lipangit** [comment]
@safei37 啥情况？JZVideoPlayer.SAVE_PROGRESS=false 还会记录位置，在jzutil中断点记录位置的代码，哪里调用了

**Comment by lipangit** [comment]
@yangyaobo 你的项目是不用用picasso加载的图片

**Comment by safei37** [comment]
我也有点懵 @lipangit

**Comment by safei37** [comment]
我试了一下，用你的方法，但是不用随机数，随便乱编一个数字，也可以解决这个问题，就是这么神奇。。。 @yanfulei

**Comment by lipangit** [comment]
1.用picasso的项目在部分手机上无法第二次播放相同的视频，杀死都不行，只能卸载
2.在记录了视频的播放位置之后，第二次播放视频prepared视频时候seekTo，可能会因为缓存的影响，报错

不知道到@safei37 你说的是哪种情况

**Comment by Wing-Li** [comment]
这个问题现在还存在啊

**Comment by Wing-Li** [comment]
现在加了 ?time= 也不行了，第二次还是不能播放

**Comment by lipangit** [comment]
关闭保存播放进度功能，让每次启动都从0开始@Wing-Li 

Jzvd.saveProgress=false试试
