### ISSUE TITLE
Activity嵌套Fragment,Fragment中播放方向的问题

### ISSUE THREAD

**Issue by huanglai666** [lipangit/JiaoZiVideoPlayer#1647]
a Activity(landscape) 中嵌套了 b Fragment 在b中放置了控件, 播放完第一个视频 重新setup内容之后 播放第二个视频时 a Activity方向变为了竖直方向

**Comment by lipangit** [comment]
参考demo'的orientationActivity，修改屏幕方向，两个变量修改全屏前和全屏后的屏幕方向，你的这个不涉及全屏后。

变量随时修改，随时生效
