### ISSUE TITLE
可以修改UserAgent么

### ISSUE THREAD

**Issue by zengqingf** [lipangit/JiaoZiVideoPlayer#1648]

**Comment by lipangit** [comment]
可以，参考demo， 有header

**Comment by themass** [comment]
你好，我参考了所有demo没有header

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37407033-aa5d3d12-27d3-11e8-9380-bb07224f6689.png)

这个就是header

**Comment by 5en** [comment]
查看了你源码里的object s只有实现标题的作用，并没有设置Header的作用

**Comment by lipangit** [comment]
@5en 设置header看apiActivity in demo， setUp通过DataSource设置
