### ISSUE TITLE
电视视频直播源二次播放失败问题!

### ISSUE THREAD

**Issue by oztil** [lipangit/JiaoZiVideoPlayer#1649]
普通的m3u8播放正常！
这种    http://playback-livehyuwxjtv122qn.sobeycache.com/sobeylive/xjtv11.m3u8
 电视直播的 视频第一次进入可以播放，第二次就不能播放了。怎么解决呢！！

**Comment by prpr894** [comment]
同样的问题。

**Comment by lipangit** [comment]
新建的项目单纯用MediaPlayer和TextureView试试

**Comment by JamesGZM** [comment]
也有碰到这个问题 兄弟有方案吗

**Comment by lidev** [comment]
@JamesGZM 兄弟解决了吗？

**Comment by lidev** [comment]
@oztil @prpr894 请问解决了没？

**Comment by linlsyf** [comment]
我也遇到这种问题了，不知道怎么解决
