### ISSUE TITLE
OnePlus2手机 型号ONE A2001   版本H2OS V2.5.1 加载不出视频

### ISSUE THREAD

**Issue by zhongyuanwu** [lipangit/JiaoZiVideoPlayer#1652]
视频在其他手机能播放 在这个手机上加载不出
视频地址 http://app.worlduc.com/uploadfiles/video/3223777.flv
错误log：
03-02 11:27:46.146 17917-18178/com.worlduc.worlducwechat D/AppTracker: App Event: start
03-02 11:27:48.811 17917-17917/com.worlduc.worlducwechat I/JiaoZiVideoPlayer: onClick start [248012761] 
03-02 11:27:48.815 17917-17917/com.worlduc.worlducwechat D/JiaoZiVideoPlayer: startVideo [248012761] 
03-02 11:27:48.816 17917-17917/com.worlduc.worlducwechat D/JiaoZiVideoPlayer: addTextureView [248012761] 
03-02 11:27:48.825 17917-17917/com.worlduc.worlducwechat I/JiaoZiVideoPlayer: onStatePreparing  [248012761] 
03-02 11:27:48.834 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.835 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.835 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.836 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.836 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.837 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.837 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.838 17917-17917/com.worlduc.worlducwechat I/JZResizeTextureView: onMeasure  [12932324] 
03-02 11:27:48.854 17917-17917/com.worlduc.worlducwechat I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [248012761] 
03-02 11:27:48.856 17917-18030/com.worlduc.worlducwechat E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
03-02 11:27:48.856 17917-18030/com.worlduc.worlducwechat E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
03-02 11:27:48.856 17917-18030/com.worlduc.worlducwechat E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
03-02 11:27:48.856 17917-18030/com.worlduc.worlducwechat E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
03-02 11:27:48.857 17917-18030/com.worlduc.worlducwechat W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
03-02 11:27:48.866 17917-18030/com.worlduc.worlducwechat W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
03-02 11:27:48.869 17917-18021/com.worlduc.worlducwechat D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 6.0.1)
03-02 11:27:48.874 17917-18295/com.worlduc.worlducwechat D/MediaHTTPConnection: proxy null port 0
03-02 11:27:50.695 17917-17927/com.worlduc.worlducwechat E/MediaPlayer: error (1, -2147483648)
03-02 11:27:50.695 17917-18030/com.worlduc.worlducwechat E/MediaPlayer: Error (1,-2147483648)
03-02 11:27:50.695 17917-17917/com.worlduc.worlducwechat E/JiaoZiVideoPlayer: onError 1 - -2147483648 [248012761] 
03-02 11:27:50.695 17917-17917/com.worlduc.worlducwechat I/JiaoZiVideoPlayer: onStateError  [248012761]

**Comment by lipangit** [comment]
理论上不支持flv的 https://developer.android.com/guide/appendix/media-formats.html
