### ISSUE TITLE
how to add subtitle under the title ? 

### ISSUE THREAD

**Issue by ismailtosun** [lipangit/JiaoZiVideoPlayer#1658]

**Comment by lipangit** [comment]
I have no idea about this feature, do you have demo or effect to let me know what does it looks like

**Comment by ismailtosun** [comment]
other question, how to chance title view background color ?

**Comment by lipangit** [comment]
This is about custom JZVideoPlayer,  see smallChangeUiActivity in demo

make your layout.xml
