### ISSUE TITLE
Error playing movie after a few minutes

### ISSUE THREAD

**Issue by emami7495** [lipangit/JiaoZiVideoPlayer#1661]
Hi, When the movie is displayed in the Player, after a while, the show stops showing an error in the log, how can this error be fixed?

![image](https://user-images.githubusercontent.com/23563595/36945471-da20e624-1fc3-11e8-979a-89c4ae1ad9c5.png)

**Comment by lipangit** [comment]
maybe this is a problem of android.media.MediaPlayer

**Comment by emami7495** [comment]
@lipangit  In your opinion, how can this error be fixed?

**Comment by lipangit** [comment]
Does it have anything to do with the video itself? try other url does it also happen

**Comment by emami7495** [comment]
@lipangit I used IjkMediaPlayer and the error was fixed

**Comment by lipangit** [comment]
ok, fix it is ok. I think this is problem of android version difference.
