### ISSUE TITLE
在Activity中可以正常播放，放到fragment中就一直转圈，但是可以调startFullscreen播放，只是setUp不行

### ISSUE THREAD

**Issue by ngreedy** [lipangit/JiaoZiVideoPlayer#1663]
` video1.setUp("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "饺子快长大");
        JZVideoPlayer.setVideoImageDisplayType(JZVideoPlayer.VIDEO_IMAGE_DISPLAY_TYPE_FILL_PARENT);
        JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
        JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;

正常调用，没有自定义， AndroidManifest.xml中写的是fangment的activity

**Comment by ngreedy** [comment]
[](url)
![qq 20180305135040](https://user-images.githubusercontent.com/16276531/36959307-42a54ba2-2039-11e8-998e-30f1ebd12bc8.png)

**Comment by lipangit** [comment]
activity和Fragment应该没有区别，对比下demo的用法，你的代码是不是少什么

**Comment by ngreedy** [comment]
![qq 20180305152411](https://user-images.githubusercontent.com/16276531/36962132-3c45923c-2046-11e8-8b87-f061f9ff5b4f.png)

一直打这个日志，可能是什么问题啊

**Comment by lipangit** [comment]
问题解决了吗，怎么回事，能播放了吗
