### ISSUE TITLE
播放事件添加点击事件

### ISSUE THREAD

**Issue by zzg19901210** [lipangit/JiaoZiVideoPlayer#1664]
viewHolder.jcVideoPlayer.setUp(vodUserInfo.getPalyUrl()
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL,
                vodUserInfo.getTitle());

        viewHolder.jcVideoPlayer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onItemPlayListener.onItemPlayClick(position);
            }
        });

**Comment by lipangit** [comment]
新建类，继承JZVideoPlayerStandard，复写onclick函数，添加点击事件，不要用setOnClickListener的形式
