### ISSUE TITLE
检测到内存泄漏

### ISSUE THREAD

**Issue by cai784921129** [lipangit/JiaoZiVideoPlayer#1667]
版本号：6.2.7
![image](https://user-images.githubusercontent.com/20353284/37085362-d2da5878-222f-11e8-9f17-1c64825b5296.png)

**Comment by lipangit** [comment]
保持关注，想想办法

**Comment by o03150** [comment]
解决了没有

**Comment by lipangit** [comment]
没有，老臣时间精力有限，感兴趣可以一起研究

**Comment by Microhx** [comment]
这个泄漏是Android系统本身的一个bug，并非来自jzvd。。。来自InputManager内存泄漏

**Comment by lipangit** [comment]
有朋友帮忙修改过了，用applicationContext
