### ISSUE TITLE
这个地址播放不出来http://120.78.227.168:8080/baff-image/upload/video/IELTS-BS19-3.mp4

### ISSUE THREAD

**Issue by AwinHe** [lipangit/JiaoZiVideoPlayer#1668]
这个地址播放不出来http://120.78.227.168:8080/baff-image/upload/video/IELTS-BS19-3.mp4， 用ijk能播放出来，这个视频http://120.78.227.168:8080/baff-image/upload/video/%E6%9C%80%E7%B3%9F%E7%B3%95%E7%9A%84%E4%BA%8B%E6%83%85.mp4用ijk播放没有画面，用jz又有画面，问一下这个解决呢？

**Comment by lipangit** [comment]
新建项目，单纯用mediaPlayer和textureView能播吗

咱们就是往mediaPlayer中怼url，能播就能播，不能播就不能播
