### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by koushik16github** [lipangit/JiaoZiVideoPlayer#1674]
**My app language is English, but reply error is in Chinese language. So how can set default language with English.**

**Comment by lipangit** [comment]
Maybe this is a bug, language is always follow the phone system language, can you show me the screenshort I will fix it

**Comment by koushik16github** [comment]
It fixed with your new release. Thanks.

Thanks & Regards,

Koushik Debnath
Email: koushik1992rintu@gmail.com
Skype: koushik1991rock
Mobile: +919007898898 / +918013137504

**Comment by lipangit** [comment]
good
