### ISSUE TITLE
How to disable video cache?

### ISSUE THREAD

**Issue by emami7495** [lipangit/JiaoZiVideoPlayer#1675]
@lipangit  Hi , I think that video cache speed down player , when I deleted app cache and retry to play movie by player speed was better , how to disable video cache?

**Comment by enderkoca** [comment]
did you resolve your problem, i got same issue ?

**Comment by emami7495** [comment]
@enderkoca 
Unfortunately, not yet

**Comment by lipangit** [comment]
you can change from android.media.MediaPlayer to ijkplayer

**Comment by emami7495** [comment]
@lipangit I use ijkplayer but I did not find a way to disable cache

**Comment by enderkoca** [comment]
@lipangit so  i use too ijkplayer ,but i could not find to  disable cache ,everytime video player playing where it left of

**Comment by lipangit** [comment]
@enderkoca JZVideoPlayer.SAVE_PROGRESS = false, this will make video play from start every time.

**Comment by enderkoca** [comment]
thanks a lot its working @lipangit
