### ISSUE TITLE
Can't play video in android 6.0

### ISSUE THREAD

**Issue by Muriti** [lipangit/JiaoZiVideoPlayer#1677]
I use this URL to play video, It works fine on android 7.0 but not work on android 6.0. 
Here is video url: http://www.drt.danang.vn/Uploads/Media/Video/THOI SU/NAM 2018/THANG 3/ts 11-3.mp4

**Comment by lipangit** [comment]
I can not open this url any where.

**Comment by Muriti** [comment]
Sorry, my mistake. I fixed it after encode url. Thank for your reply.
