### ISSUE TITLE
有些mp4格式加载不出来

### ISSUE THREAD

**Issue by zhoufengcqfj** [lipangit/JiaoZiVideoPlayer#1684]
同样是MP4格式的视频，有些mp4格式加载不出来，换成ijk播放器也不行，有些mp4格式加载不出来，视频链接http://vod.topvid.tv/mp4_vod/67f509aab16cd2160d39331eded5d7c3.mp4

**Comment by lipangit** [comment]
这个视频chrome中无法播放，请用最常规的视频格式
