### ISSUE TITLE
E/JiaoZiVideoPlayer: onError 1 - -2147483648 [3650284] 

### ISSUE THREAD

**Issue by chnouman** [lipangit/JiaoZiVideoPlayer#1685]
Unable to play video it says Video loading failed.
Click to try again.

**Comment by chnouman** [comment]
it is playing your video perfectly but for my videos it gives error.
my video url is https://firebasestorage.googleapis.com/v0/b/viralvideos-61246.appspot.com/o/videos%2F27525639_421036104980257_6056710787160866816_n.mp4?alt=media&token=9284ead5-2fe2-4223-8623-9b9bb8858c11

**Comment by chnouman** [comment]
Yes i do.

**Comment by lipangit** [comment]
remove all picasso in the project , it will confict with mediaplayer

**Comment by lipangit** [comment]
I do not believe first, but now I believe.

**Comment by chnouman** [comment]
ok it's working fine now actually i was using picaso because it can fetch thumbnail of image from video link now for fetching thumbnail what can i do?

**Comment by lipangit** [comment]
I do not know T_T

**Comment by trungtrangtreo** [comment]
thanks lipangit

**Comment by lipangit** [comment]
Yes he is right,

**Comment by powerpoint45** [comment]
It looks like the latest version of Picasso 2.71828 no longer conflicts with the player. Just updated to it and no longer have the problem.

**Comment by lipangit** [comment]
Ok if you want.
