### ISSUE TITLE
为什么在fragment（视屏正在播放）切换时候，在setUserVisibleHint调用 JZVideoPlayer.releaseAllVideos();，在切换回来虽然视屏暂停了，但是点击继续播放，还是接着刚才的进度播放

### ISSUE THREAD

**Issue by wolf8088521** [lipangit/JiaoZiVideoPlayer#1689]
@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        Log.e("setUserVisibleHint","onPause"+isVisibleToUser);
        if (isVisibleToUser==false){
            if (JZVideoPlayer.backPress()) {
                return;
            }
            JZVideoPlayer.releaseAllVideos();
        }
    }

**Comment by lipangit** [comment]
JZVideoPlayer.releaseAllVideos() 这个会重置全部视频，如果代码走到这里，它的作用应该是毋庸置疑的

确定setUserVisibleHint这个函数的效果是否如自己所想
