### ISSUE TITLE
横屏播放视频，全屏后点击返回，Activity被修改为竖屏

### ISSUE THREAD

**Issue by JeremyLeeL** [lipangit/JiaoZiVideoPlayer#1691]
请问在视频全屏播放退出全屏的时候有做修改屏幕方向的操作吗，我的Activity都设置了screenOrientation为landscape，但是退出全屏后，Activity的方向被修改为竖屏了

**Comment by JeremyLeeL** [comment]
我看源码中playOnThisJzvd方法调用了clearFloatScreen，设置屏幕方向为NORMAL_ORIENTATION(对应ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)，也就是说，这里的normal就是竖屏，我没有把源码拷过来改了，在退出全屏的时候屏幕方向发生变化，回调onConfigurationChanged方法里面加了一句代码：
JZUtils.setRequestedOrientation(this, ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE)
取巧了

**Comment by lipangit** [comment]
问题解决了吗

**Comment by JeremyLeeL** [comment]
解决了，这样设置之后就不会被默认修改为竖屏了，建议提供退出全屏修改屏幕方向的方法，因为Android平板默认是横屏的
