### ISSUE TITLE
保存进度的key

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#1692]
是否可以增加一个保存和读取进度的回调用来改变默认的行为，因为我现在每次返回的视频的URL都是动态的，导致无法恢复播放的进度

**Comment by lipangit** [comment]
因为现在是全局函数管这个事，你觉得怎么改方便一些

**Comment by kennir** [comment]
加一个delegate?

**Comment by kennir** [comment]
加一个生成key的delegate？

```
interface ProgressKeyGenerator {
  virtual String getKey();
}
```

这样用户自己继承一个自定义的规则 
```
class MyProgressKey extends ProgressKeyGenerator {
 private String gid;
  MyProgressKey(String gid) {
    this.gid = gid;
  }
  
 @override
  String getKey() { return this.gid; }
}
```

最后再播放前用设置给全局
```
JZVideoPlayerStandard.setProgressKeyGenerator(new MyProgressKey("abcdefg"))
```

**Comment by lipangit** [comment]
你的真实的url是怎么获得的，是可以通过当前的url算出来的是吗

**Comment by kennir** [comment]
不是，需要通过视频的ID去网站请求，网站会下发一个动态的URL，每一次都会变化，而且播放后一定时间就失效了，所以我想用视频的ID作为Key来保存

**Comment by lipangit** [comment]
恩，这个问题我想想，最晚明晚回复你

**Comment by lipangit** [comment]
目标是通过最简单通俗的办法，找出系统的解决方案。

**Comment by kennir** [comment]
太感谢了

我现在用了其他的一个方案，因为重播的需求时间的间隔一般比较短，我缓冲了获取的url用来重播，这样就是同一个url作为key了，如果时间长播放失败就再说了 = =#

**Comment by lipangit** [comment]
不好意思，忘记了 = =# 这个也可以，我想的是能通过复写jzvd的函数来做

**Comment by kennir** [comment]
嗯，我的解决方案治标不治本，时间长点url就失效了，最好还是有一个可以自定义key的方案，或者把保存读取的接口开放出来可以自己写具体实现

**Comment by XuQK** [comment]
刚好也碰到了这个问题，我们URL是在点击播放时进行加密再设置给播放器的。翻了会源码，在自定义的播放器中重写了'onCompletion()'方法和'onStatePrepared()'方法，将里面的'saveProgress()'和'getSavedProgress()'的url设置成加密前的url即可，也可以将url替换成ID等别的标识视频的字符串。

**Comment by lipangit** [comment]
@XuQK   解决就好，么么哒
