### ISSUE TITLE
怎么 动态设置全屏的横竖屏

### ISSUE THREAD

**Issue by zhoufengcqfj** [lipangit/JiaoZiVideoPlayer#1693]
在列表中播放视频，然后点击全屏按钮，根据视频的宽高比动态设置全屏的横竖屏，怎么实现

**Comment by lipangit** [comment]
这个需要修改逻辑了。

点击全屏按钮之后，根据宽高判断是横屏还是竖屏。

![image](https://user-images.githubusercontent.com/2038071/37410309-4bb03f6e-27db-11e8-8eb2-95f9f20492a9.png)
这是视频的高宽

![image](https://user-images.githubusercontent.com/2038071/37410339-5dbcd4c4-27db-11e8-8c03-17202471b51c.png)
这控制屏幕方向

**Comment by msrlin** [comment]
这个需要重写这个类吗

**Comment by lipangit** [comment]
需要
