### ISSUE TITLE
video not play if not make it to tiny window

### ISSUE THREAD

**Issue by IZeIke** [lipangit/JiaoZiVideoPlayer#1694]
I try in recyclerview
when I click to play, It just loading but not play video
but when I scroll down, video become to tiny window and video play instantly
how to fix this

this is my code in onBindViewHolder

`viewHolder.video.setUp(video_url,JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL,"");           Glide.with(viewHolder.video.getContext()).load(picture_url).into(((ViewHolder2)holder).video.thumbImageView);`

**Comment by IZeIke** [comment]
ok , solved by fix height 200dp on videoplayer
at first I use wrap_content

**Comment by lipangit** [comment]
good
