### ISSUE TITLE
视频无法加载或播放

### ISSUE THREAD

**Issue by chengh2016** [lipangit/JiaoZiVideoPlayer#1696]
此视频有的机型无法加载，或加载出无法播放，小米note可以加载播放，换用其他播放器也能播放 加急谢谢
http://sdisk.wachoo.com/res/items/15682-jialin.mp4

**Comment by lipangit** [comment]
你说的是不是第二次播放不行，你用的picasso吗

**Comment by chengh2016** [comment]
不是，用的ImageLoader有影响吗？这个地址放到demo里也是无法加载或者无法播放

**Comment by lipangit** [comment]
记得Imageloader在列表滑动退出小窗的时候会闪烁，所以干掉了

**Comment by lipangit** [comment]
这种不好说，咱们就是往mediaPlayer里怼url
