### ISSUE TITLE
进度条拖动跳跃很严重

### ISSUE THREAD

**Issue by XuQK** [lipangit/JiaoZiVideoPlayer#1699]
这些问题都在demo里能出现的。
http://cmsapi.zhenhao.com.cn:8081/wlyyupload/common/2018-03-13/EL1520905175913.mp4
这个视频，进度条不管怎么拖，都只会跳到开头，中间，接近结尾的三个点，哪个近跳哪个。
官方demo的recyclerview的第一个视频也有这个问题，拖动到21s-31s之间，只能就近跳到这两个点。
这是视频关键帧过少的原因吗？有没有办法解决呢？

**Comment by lipangit** [comment]
是的以前我也意识到这个问题，但是不知道怎么解决，可以帮忙研究一下

**Comment by XuQK** [comment]
应该是这个关键帧过少的原因，上面的视频我用ffmpeg处理了下，每秒都加个关键帧，就很平滑了。
ijkplayer应该有对应处理的方法，具体可以看这个项目，第6点：https://www.jianshu.com/p/220b00d00deb

我得先换这个播放器去试试了，项目催得紧，暂时没办法深入研究了:)

**Comment by XuQK** [comment]
试了下，换用ijkplayer，设置`ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);`就可以了。不用换播放器了，哈哈

**Comment by lipangit** [comment]
参考demo可以一行代码切换到ijkplayer播放引擎

**Comment by XuQK** [comment]
是参考的demo切换的，切换过后，在demo里的`JZMediaIjkplayer`的`prepare()`方法里加上上面那行就行了。
没什么问题了这个issue就关掉吧~这一点可以加到wiki FAQ~
