### ISSUE TITLE
关于播放器放入自定义ViewGroup的测量和布局问题

### ISSUE THREAD

**Issue by o03150** [lipangit/JiaoZiVideoPlayer#1701]
请问:
        为什么我把播放器放入自定义ViewGroup,只要点击播放,onMeasure和onLayout就一直持续被调用,不断测量布局,影响性能啊

**Comment by lipangit** [comment]
所有控件都这样吧，你有什么其他想法吗

**Comment by o03150** [comment]
所有都这样？测量布局不是布局尺寸位置不改变，就不会调用这两个方法吗？这个视频控件每一帧都会触发重新布局？

**Comment by lipangit** [comment]
这个有啥办法吗

**Comment by o03150** [comment]
大佬,我也没法啊,我在onLayout做个测试,设置个条件,达到一定次数后return,视频还是正常播放的,但是播放完再点击播放,添加渲染层,此时触发不了测量和布局的方法

**Comment by lipangit** [comment]
我觉的这个优先级比较低，保持关注，有了灵感再说

**Comment by lipangit** [comment]
@o03150 能看看你怎么改的代码吗
