### ISSUE TITLE
Demo回退页面问题（recyleview）

### ISSUE THREAD

**Issue by 371784711** [lipangit/JiaoZiVideoPlayer#1702]
Q:
1.Demo:ActivityListViewRecyclerView 
2.版本：最新版
3.问题描述：将此Demo实现像Viewpager的滑动效果------使用如下代码
PagerSnapHelper snapHelper = new PagerSnapHelper();
snapHelper.attachToRecyclerView(recyleview);

并将Item的布局全屏化，运行后确实可以达到预期效果，但是如果做如下操作：
（1）运行后点开ActivityListViewRecyclerView，点击播放一个视频，后上下快速滑动，有高几率出现直接白屏一下回退上一页
（2）麻烦帮忙测试看看，谢谢了

**Comment by lipangit** [comment]
进群，录个小视频看看吧

**Comment by lipangit** [comment]
log是什么
