### ISSUE TITLE
切换到全屏时无法隐藏电池和时间   求助

### ISSUE THREAD

**Issue by huangyong0301** [lipangit/JiaoZiVideoPlayer#1703]
我看了一下源码  这样写并没有作用

``public class JZVideoPlayerStandardShowTitleAfterFullscreen extends JZVideoPlayerStandard {
    public JZVideoPlayerStandardShowTitleAfterFullscreen(Context context) {
        super(context);
    }

    public JZVideoPlayerStandardShowTitleAfterFullscreen(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void setUp(String url, int screen, Object... objects) {
        super.setUp(url, screen, objects);

        titleTextView.setVisibility(View.GONE);
        batteryLevel.setVisibility(View.GONE);
        videoCurrentTime.setVisibility(View.GONE);

    }

    @Override
    public void startWindowFullscreen() {
        super.startWindowFullscreen();
        batteryLevel.setVisibility(View.GONE);
        videoCurrentTime.setVisibility(View.GONE);
    }
}

**Comment by huangyong0301** [comment]
求助

**Comment by lipangit** [comment]
复写各个状态的函数，在各个状态中分别设置ui，否则会被其他状态覆盖

**Comment by zuoguozhen** [comment]
直接把battery_level和video_current_time这两个控件在xml中设为gone就可以了
