### ISSUE TITLE
release下不能播放视频

### ISSUE THREAD

**Issue by AmberWhiteSky** [lipangit/JiaoZiVideoPlayer#1705]
如题， debug模式下可以正常播放视屏。
但是在release模式下不能播放视频，一直转圈。
我排除了视频地址的问题 我吧正式数据的视频url 放到饺子demo中release 也可以播放。
然后我在项目中关闭混淆   minifyEnabled true 
然后在进行release 就可以播放了。
明天试试加混淆之后看看能不能正常播放。

**Comment by pys200603027** [comment]
看下播放器是报错了，发下log

**Comment by lipangit** [comment]
是不是用的ijkplayer？

**Comment by yalarc** [comment]
#ijkplayer 混淆配置
-keep class tv.danmaku.ijk.media.player.** {*;}
-keep class tv.danmaku.ijk.media.player.IjkMediaPlayer{*;}
-keep class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi{*;}

**Comment by lipangit** [comment]
对 ijkplayer需要混淆

**Comment by lipangit** [comment]
这个问题可能不是这么简单，兄弟
