### ISSUE TITLE
Fullscreen on portrait 

### ISSUE THREAD

**Issue by nemdaz** [lipangit/JiaoZiVideoPlayer#1706]
When press icon for fullscreen (portrait) the top section show no correct  background.
See the image.
![screenshot_20180318-170642](https://user-images.githubusercontent.com/6315069/37571916-69a6f67c-2ad1-11e8-9ee7-16f45503af25.png)

**Comment by lipangit** [comment]
yes this is bug

**Comment by lipangit** [comment]
whitch version

**Comment by nemdaz** [comment]
current branch develop

**Comment by lipangit** [comment]
fixing

**Comment by lipangit** [comment]
fixed
