### ISSUE TITLE
I cant play this video http://resources.amazwing.com/Content/14032018/636566442343896150.mp4.Its strucking the player.

### ISSUE THREAD

**Issue by Rafiqgithub** [lipangit/JiaoZiVideoPlayer#1707]

**Comment by lipangit** [comment]
something wrong with the video url

**Comment by Rafiqgithub** [comment]
I found out its due to video codec.current video codec format is H.264 (High Profile) and videos which are playing (H.264 (Constrained Baseline Profile)) how can I resolve this any help?

**Comment by lipangit** [comment]
this is out of my control

**Comment by Rafiqgithub** [comment]
Can you please tell me steps to cache videos before playing videos in the list.I don't want users to wait for buffering to play video.

**Comment by lipangit** [comment]
android.media.MediaPlayer has no api to control, it is all default by the android system
