### ISSUE TITLE
Cannot play video on Samsung Galaxy J1 model

### ISSUE THREAD

**Issue by dinhtrungvn92** [lipangit/JiaoZiVideoPlayer#1708]
JZ works normally with other models, but with J1, when click to Play button, loading progress get VISIBLE, and still stay on it, video was not playing.
Please give me suggestion, or this case is Exception of JZ.
Best Regards.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37641608-686754b6-2c55-11e8-962b-f289b8e4e491.png)

see this in demo

**Comment by dinhtrungvn92** [comment]
@lipangit Thanks for response. But it's didn't work. JZVD demo work correctly, but my app was not. Just occurred on Galaxy J1.

**Comment by lipangit** [comment]
show me the url I will try
