### ISSUE TITLE
快进 快退的时候，有问题

### ISSUE THREAD

**Issue by 522436301** [lipangit/JiaoZiVideoPlayer#1709]

**Comment by 522436301** [comment]
JZVideoPlayer 这个方法onStatePrepared   的seekToInAdvance 等于0，条件不成立，导致调用了long position = JZUtils.getSavedProgress......保存的进度，导致快退或快进有问题

**Comment by lipangit** [comment]
具体现象是什么

**Comment by lipangit** [comment]
seekToInAdvance这个在视频刚开始的时候才会判断，和快进快退没关系吧

**Comment by 522436301** [comment]
seekToInAdvance 第一次赋值了，没有问题，之后又把它赋为0了。
快退或者快进的时候 JZMediaSystem 这个类 调用了onInfo方法 ，onInfo方法中调用了onPrepared方法，onPrepared
方法中onStatePrepared方法
if (seekToInAdvance != 0) {
    JZMediaManager.seekTo(seekToInAdvance, false);
    seekToInAdvance = 0;
} else {
    long position = JZUtils.getSavedProgress(getContext(), JZUtils.getCurrentFromDataSource(dataSourceObjects, currentUrlMapIndex));
    if (position != 0) {
        JZMediaManager.seekTo(position, false);
    }
}
seekToInAdvance 等于0了吧，就走了下面的代码。就会回到缓存进度，播放。
情景再现:先第一次看视频，默认保存缓存进度，看一会退出，再次进来观看，再点击快进或者快退，就出问题了，我打印了seekToInAdvance 这个值，就是0.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37696569-a5c4bf66-2d12-11e8-8ca9-a89359898eac.png)

更新即可

**Comment by QQzs** [comment]
限制高度后，不能快进快退啊，只有点击全屏后才能快进快退

**Comment by lipangit** [comment]
@QQzs 具体说说

**Comment by JunWeiAndroid** [comment]
> 限制高度后，不能快进快退啊，只有点击全屏后才能快进快退

onTouch改写一下

**Comment by lipangit** [comment]
解决了吗
