### ISSUE TITLE
有个问题,视频时长太短,播放会提前结束

### ISSUE THREAD

**Issue by o03150** [lipangit/JiaoZiVideoPlayer#1710]
播放一个4秒的视频,实际就播放了两三秒,没有播放全就停了

**Comment by lipangit** [comment]
这个是播放器引擎的关系，播放的效果和用其他东西播放的效果一样吗

**Comment by o03150** [comment]
我切换成ijk,就可以正常播放了,手机是7.0系统谷歌neuxs5x.
但还是有些问题:
问题1:初始化过程有点慢,一般还两三秒这样子,
问题2:缓冲的进度条没有充满这个进度条,视频长不容易看出来,但是视频短最后一截未充满就很明显了

**Comment by lipangit** [comment]
你可以到ijkplayer项目里提问

**Comment by lipangit** [comment]
超出老臣解决范围
