### ISSUE TITLE
目前有 手机左横屏，全屏后左横屏，手机右横屏，全屏后右横屏的功能吗

### ISSUE THREAD

**Issue by linfeizheng** [lipangit/JiaoZiVideoPlayer#1711]
现在是手机不管左横右横，全屏方向都是左横

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37641348-5c0fd2e8-2c54-11e8-82e0-3e6c63f87c40.png)

通过这两个变量控制
