### ISSUE TITLE
用切换视频高清度的方式实现视频列表循环播放出现的问题

### ISSUE THREAD

**Issue by yanlianhanlin** [lipangit/JiaoZiVideoPlayer#1712]
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaPlayer.getDuration(Native Method)
W/System.err:     at cn.jzvd.JZMediaSystem.getDuration(JZMediaSystem.java:84)
W/System.err:     at cn.jzvd.JZMediaManager.getDuration(JZMediaManager.java:74)
W/System.err:     at cn.jzvd.JZVideoPlayer.getDuration(JZVideoPlayer.java:925)
W/System.err:     at cn.jzvd.JZVideoPlayer$ProgressTimerTask$1.run(JZVideoPlayer.java:1158)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5072)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)

刚开始运行没有问题，时间长了就会出现这个异常，请问是因为什么导致的这个错误

**Comment by lipangit** [comment]
保持关注，把getDuration try catch住还不行吗

**Comment by yanlianhanlin** [comment]
在哪个地方try catch 啊

**Comment by lipangit** [comment]
兄弟，怎么样了
