### ISSUE TITLE
VideoPlayerStandard with cookie

### ISSUE THREAD

**Issue by PascalTang** [lipangit/JiaoZiVideoPlayer#1715]
你好 我現在希望能在setUp的時候
夾帶cookie
請問要怎麼做

**Comment by PascalTang** [comment]
implementation 'cn.jzvd:jiaozivideoplayer:6.2.7'

**Comment by PascalTang** [comment]
Map<String, String> headers = new HashMap<>();
        headers.put("Cookie", "jwt=" + "token");

        mVideoplayer.setUp(videoId.toString()
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, headers);

這樣放那個cookie會直接變title

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/37696961-018a625e-2d15-11e8-83a9-9e4aa7ace6fa.png)

参考这个

**Comment by PascalTang** [comment]
你好 我夾好了
那請問要 如何print出player的http request？包含所夾的header
我想看有沒有夾成功
感謝

**Comment by lipangit** [comment]
么么哒，加油
