### ISSUE TITLE
切换成七牛的播放器，SeekTo失效

### ISSUE THREAD

**Issue by zhoufengcqfj** [lipangit/JiaoZiVideoPlayer#1719]
为什么切换成七牛的播放器，seekBar拖动后，还是从原来位置播放，希望楼主大大帮忙解决下

**Comment by lipangit** [comment]
断点seekTo，看看是否调用七牛的播放器的seekTo函数了。

可以把你七牛的代码分享出来，放到demo里给大家参考。
