### ISSUE TITLE
It only plays the sound and the video keeps loading.

### ISSUE THREAD

**Issue by nemdaz** [lipangit/JiaoZiVideoPlayer#1720]
It only plays the sound and the video keeps loading.

Test on:
- Android API 16 (minSdkVersion)
- Current develop branch

**Comment by lipangit** [comment]
show me the log, and show me the url

**Comment by nemdaz** [comment]
Samsung GT-I8190L - Android 4.1.2 API 16

URL in Log
==============

03-23 10:34:22.210 30069-30070/com.app.master D/dalvikvm: GC_CONCURRENT freed 1541K, 10% free 26843K/29639K, paused 17ms+21ms, total 120ms
03-23 10:34:22.631 30069-30069/com.app.master D/webviewglue: nativeDestroy view: 0x5fd98f98
03-23 10:34:24.483 30069-30069/com.app.master D/JiaoZiVideoPlayer: startVideo [1127327384] 
03-23 10:34:24.483 30069-30069/com.app.master D/JiaoZiVideoPlayer: addTextureView [1127327384] 
03-23 10:34:24.513 30069-30069/com.app.master I/JiaoZiVideoPlayer: onStatePreparing  [1127327384] 
03-23 10:34:24.513 30069-30069/com.app.master D/ProgressBar: setProgress = 0
03-23 10:34:24.513 30069-30069/com.app.master D/ProgressBar: setProgress = 0, fromUser = false
03-23 10:34:24.513 30069-30069/com.app.master D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
03-23 10:34:24.523 30069-30069/com.app.master D/ProgressBar: setProgress = 0
03-23 10:34:24.523 30069-30069/com.app.master D/ProgressBar: setProgress = 0, fromUser = false
03-23 10:34:24.523 30069-30069/com.app.master D/ProgressBar: mProgress = 0mIndeterminate = false, mMin = 0, mMax = 100
03-23 10:34:24.553 30069-30069/com.app.master I/JZResizeTextureView: onMeasure  [1130686960] 
03-23 10:34:24.563 30069-30069/com.app.master I/JZResizeTextureView: onMeasure  [1130686960] 
03-23 10:34:24.593 30069-30069/com.app.master I/libblt_hw: Library opened (handle = 0, fd = 112)
03-23 10:34:24.593 30069-30069/com.app.master I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [1127327384] 
03-23 10:34:24.613 30069-30373/com.app.master W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
03-23 10:34:24.623 30069-30373/com.app.master I/MediaPlayer: path is null
03-23 10:34:24.643 30069-30373/com.app.master D/MediaPlayer: setDataSource IOException happend : 
                                                                          java.io.FileNotFoundException: No content provider: https://jkanime.net/stream/jkmedia/5b1c4806a2590de997910d5a6e7100fe/4f501d26373b56e0fe0351c1a6154bd4/1/3d3268e5a2aa528850833da2d8887a8b/
                                                                              at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:710)
                                                                              at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:614)
                                                                              at android.media.MediaPlayer.setDataSource(MediaPlayer.java:929)
                                                                              at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:65)
                                                                              at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:60)
03-23 10:34:24.643 30069-30373/com.app.master D/MediaPlayer: Couldn't open file on client side, trying server side
03-23 10:34:24.683 30069-30373/com.app.master W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
03-23 10:34:35.844 30069-30069/com.app.master I/JiaoZiVideoPlayer: onVideoSizeChanged  [1127327384] 
03-23 10:34:35.854 30069-30373/com.app.master I/MediaPlayer: sendBroadcast android.media.IMediaPlayer.videoexist
03-23 10:34:35.924 30069-30069/com.app.master I/JZResizeTextureView: onMeasure  [1130686960] 
03-23 10:34:35.934 30069-30069/com.app.master I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 480]
03-23 10:34:35.934 30069-30069/com.app.master I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 300]
03-23 10:34:35.954 30069-30069/com.app.master I/JZResizeTextureView: onMeasure  [1130686960] 
03-23 10:34:35.954 30069-30069/com.app.master I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 480]
03-23 10:34:35.954 30069-30069/com.app.master I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 300]

**Comment by lipangit** [comment]
Something wrong with the url, I do not know. you can change to ijkplayer to play the video, see customMediaPlayer activity in demo
