### ISSUE TITLE
快进或者快退 崩溃 报的错误是mp 是空？我切换的ijk

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1721]
快进或者快退 崩溃 报的错误是mp 是空？我切换的ijk

**Comment by lipangit** [comment]
demo有这问题吗，修改什么了吗

**Comment by guoyongxing** [comment]
我切换到ijk  就是一行代码的时候  报的错误seekTo那里  还是他的那个类库源代码  我是马上要播放完毕  快退

**Comment by lipangit** [comment]
看看哪里把mp设为空了，查一下

是否在播放中切换播放器引擎，这是不行的

把log贴出来，录个小视频看看，具体什么样子
