### ISSUE TITLE
第一次全屏播放的问题

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#1722]
在recyclerview里播放后第一次点击全屏会出来这样的情况，之后再播放全屏就正常了，请问可能会是什么原因？ 部分机型上会出现

![70711521564427_ pic](https://user-images.githubusercontent.com/876410/37812104-27b48010-2e99-11e8-989a-1363b5aa7549.jpg)

**Comment by lipangit** [comment]
把开发者里显示布局边界打开，看看啥毛病

**Comment by kennir** [comment]
好，我试试看

**Comment by kennir** [comment]
更新到最新的版本发现这个问题已经没有了，close 吧

**Comment by lipangit** [comment]
新版并没有对这方面做出修改，可能有未知的事情
