### ISSUE TITLE
decrease live stream delay 

### ISSUE THREAD

**Issue by abdlkdrisiktan** [lipangit/JiaoZiVideoPlayer#1723]
Hi
My stream is real time and I also testing, when I using Vlc Media Player and live broadcast is really synchronous 
I'm trying this code and I want to decrease live stream delay 
2-3 sec delay between android and live broadcast  

 JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.videoplayer);
jzVideoPlayerStandard.setBufferProgress(0);
jzVideoPlayerStandard.setUp("rtsp://mobiversitewowza.westeurope.cloudapp.azure.com:554/videochat/1"
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "SAMPLE");

How can I do that ?

**Comment by lipangit** [comment]
You can one line code to change to ijkplayer, see demo customMediaPlayerActivity
