### ISSUE TITLE
AutoPlayVideo ? 

### ISSUE THREAD

**Issue by lucazin** [lipangit/JiaoZiVideoPlayer#1725]
PropagandaVideo_async.get().setUp(UrlVideo, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, TextoVideo.toString());
                                                    GlideFunction.LoadImage(activity.get(), ThumbVideo, PropagandaVideo_async.get().thumbImageView);
                                                    PropagandaVideo_async.get().startButton.setVisibility(View.INVISIBLE);
                                                    PropagandaVideo_async.get().loop = true;
                                                    PropagandaVideo_async.get().performClick();

I'm trying with this code, but the video is not playing 
can someone help me ?

**Comment by lucazin** [comment]
i fixed! 

PropagandaVideo_async.get().loop = true;
  PropagandaVideo_async.get().startButton.performClick();

tnks all

**Comment by lucazin** [comment]
i fixed!

PropagandaVideo_async.get().loop = true;
PropagandaVideo_async.get().startButton.performClick();

tnks all

**Comment by lipangit** [comment]
Good!

**Comment by mohamedebrahim96** [comment]
![erwrwerwe](https://user-images.githubusercontent.com/16405013/38472431-5dd61034-3b80-11e8-92dc-383f68b6dce2.JPG)

**Comment by lipangit** [comment]
download new version demo, and search loop

**Comment by lucazin** [comment]
PropagandaVideo_async.get().loop = true;   not work anymore  when update version

**Comment by lipangit** [comment]
see new version of demo
