### ISSUE TITLE
视频方向问题

### ISSUE THREAD

**Issue by Biekangdong** [lipangit/JiaoZiVideoPlayer#1726]
有些视频是竖屏拍的，它会自动转成横屏咋办。这是视频地址http://xichuan.bojuwang.com/public/upload/video/20180308/d3fcc8d67c99d33267f58cf48864f605.mp4

**Comment by lipangit** [comment]
无法播放此视频源，不知为何  华为nova2s

**Comment by Biekangdong** [comment]
换成JZMediaIjkplayer可以播放。不过JZMediaIjkplayer方向会出现问题，用mediaplayer没问题

**Comment by lipangit** [comment]
可以复写onVideoSize函数，修改方向，不过这种方法应该不推荐

**Comment by WangkeqiangS** [comment]
请问最后是怎么解决的？
