### ISSUE TITLE
OOM崩溃

### ISSUE THREAD

**Issue by mflk007** [lipangit/JiaoZiVideoPlayer#1730]
机型：小米3
cn.jzvd:jiaozivideoplayer:6.2.8

03-26 13:45:03.680: D/dalvikvm(16208): GC_BEFORE_OOM freed 88K, 2% free 129341K/131068K, paused 34ms, total 34ms
03-26 13:45:03.680: E/dalvikvm-heap(16208): Out of memory on a 466576-byte allocation.
03-26 13:45:03.680: I/dalvikvm(16208): "main" prio=5 tid=1 RUNNABLE
03-26 13:45:03.680: I/dalvikvm(16208):   | group="main" sCount=0 dsCount=0 obj=0x4179ce58 self=0x416bc8c0
03-26 13:45:03.680: I/dalvikvm(16208):   | sysTid=16208 nice=0 sched=0/0 cgrp=apps handle=1074614612
03-26 13:45:03.680: I/dalvikvm(16208):   | state=R schedstat=( 3362014711 1309597930 9860 ) utm=269 stm=67 core=3
03-26 13:45:03.680: I/dalvikvm(16208):   at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:601)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:434)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.content.res.Resources.createFromResourceStream(Resources.java:2513)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.content.res.Resources.loadDrawable(Resources.java:2165)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.content.res.Resources.loadDrawable(Resources.java:2072)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.View.<init>(View.java:3562)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.View.<init>(View.java:3492)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.ViewGroup.<init>(ViewGroup.java:464)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.widget.RelativeLayout.<init>(RelativeLayout.java:236)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Constructor.constructNative(Native Method)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.createView(LayoutInflater.java:597)
03-26 13:45:03.680: I/dalvikvm(16208):   at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:672)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.View.inflate(View.java:17504)
03-26 13:45:03.680: I/dalvikvm(16208):   at cn.jzvd.JZVideoPlayer.init(JZVideoPlayer.java:361)
03-26 13:45:03.680: I/dalvikvm(16208):   at cn.jzvd.JZVideoPlayerStandard.init(JZVideoPlayerStandard.java:97)
03-26 13:45:03.680: I/dalvikvm(16208):   at cn.jzvd.JZVideoPlayer.<init>(JZVideoPlayer.java:137)
03-26 13:45:03.680: I/dalvikvm(16208):   at cn.jzvd.JZVideoPlayerStandard.<init>(JZVideoPlayerStandard.java:92)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Constructor.constructNative(Native Method)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.createView(LayoutInflater.java:597)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
03-26 13:45:03.680: I/dalvikvm(16208):   at com.zcy.ghost.vivideo.base.BaseActivity.onCreate(BaseActivity.java:42)
03-26 13:45:03.680: I/dalvikvm(16208):   at com.zcy.ghost.vivideo.base.BaseMvpActivity.onCreate(BaseMvpActivity.java:31)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.Activity.performCreate(Activity.java:5249)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2165)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.ActivityThread.access$900(ActivityThread.java:141)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.os.Handler.dispatchMessage(Handler.java:102)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.os.Looper.loop(Looper.java:136)
03-26 13:45:03.680: I/dalvikvm(16208):   at android.app.ActivityThread.main(ActivityThread.java:5072)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Method.invokeNative(Native Method)
03-26 13:45:03.680: I/dalvikvm(16208):   at java.lang.reflect.Method.invoke(Method.java:515)
03-26 13:45:03.680: I/dalvikvm(16208):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-26 13:45:03.680: I/dalvikvm(16208):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
03-26 13:45:03.680: I/dalvikvm(16208):   at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
有什么线索吗，这好像还不是缩略图oom，加载布局的时候出的问题
