### ISSUE TITLE
播放本地视频时会自动停止

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [lipangit/JiaoZiVideoPlayer#1732]
![default](https://user-images.githubusercontent.com/19187129/37893624-35ca7c6e-310e-11e8-8d72-4673dfa6384e.png)
上图是报错信息, 并不会导致程序停止, 但是视频停止播放了. 而且不会走跟视频相关的生命周期.

**Comment by lipangit** [comment]
断点一下onError函数，断点一下MediaPlayer的release函数，getDuration多数会在MediaPlayer已经release的时候报错
