### ISSUE TITLE
关于一建切换七牛播放器的崩溃

### ISSUE THREAD

**Issue by zxc7601151** [lipangit/JiaoZiVideoPlayer#1733]
![Uploading image.png…]()

**Comment by zxc7601151** [comment]
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x79f494edf0 in tid 31577 (om.topvid.video)
                                                        
                                                        [ 03-26 16:45:41.440   430:  430 W/         ]
                                                        debuggerd: handling request: pid=31577 uid=10595 gid=10595 tid=31577

**Comment by zxc7601151** [comment]
就这些日志，bug的复现是在tablayout嵌套fragment，然后每个fragment里面是一个recyclerview，recyclerview的每个item都有一个播放器，然后快速切换fragment崩溃

**Comment by lipangit** [comment]
切换fragment的时候release videos了吗，参考demo有fragment viewpager的用法
