### ISSUE TITLE
读取视频失败，禁音逻辑导致的疑问

### ISSUE THREAD

**Issue by RXlung** [lipangit/JiaoZiVideoPlayer#1735]
从sd卡读取视频， 可能存在读取失败，在onerror方法中 重新调用了startvideo方法，
 @Override
    public void onError(int what, int extra) {
        super.onError(what, extra);
        MyLog.e(TAG, "android.media.MediaPlayer回调的onError" + what + "--extra:" + extra);
        startVideo();//重调播放
    }
来实现失败的话自动重新加载视频，   在onStatePlaying 做了静音逻辑的处理，   
@Override
    public void onStatePlaying() {
        super.onStatePlaying();
        if (current_state != 5) {
            goOnPlayOnPause();   //直接进入暂停状态
        }
        current_state = 5;
      JZMediaManager.instance().mediaPlayer.setVolume(0.0f, 0.0f);
        }
        MyLog.e(TAG, "preparing之后进入播放状态");
        MyLog.e(TAG, "模拟暂停了" + current_state + "状态");
    }
    问题：如果读取正常很顺没事，，如果失败自动再加载，会报setVolume(静音)的异常，  这种错误的原因会是什么导致呢？？      猜测 按说在stateplay中禁音，视频应该正常加载了，去静音很合适啊，却出现了问题；  感谢回答的前辈

**Comment by lipangit** [comment]
解决了吗

**Comment by RXlung** [comment]
暂时没有

**Comment by RXlung** [comment]
查看c++层，，好像mp为空 调用setvolume的时候出现的此异常 @lipangit 
android_media_MediaPlayer_setVolume(JNIEnv *env, jobject thiz, jfloat leftVolume, jfloat rightVolume)
{
    ALOGV("setVolume: left %f  right %f", (float) leftVolume, (float) rightVolume);
    sp<MediaPlayer> mp = getMediaPlayer(env, thiz);
    if (mp == NULL ) {
       jniThrowException(env, "java/lang/IllegalStateException", NULL);
        return;
    }
   process_media_player_call( env, thiz, mp->setVolume((float) leftVolume, (float) rightVolume), NULL, NULL );
}

**Comment by lipangit** [comment]
断点所有meidaplayer.release()的地方，看看有没有蹊跷

**Comment by RXlung** [comment]
@lipangit   
补充  bug的出现是我快速切换视频的时候，因为左侧是listview  右侧是视频  快速点击listview的item切换视频，出现这两个bug 静音和暂停
哈哈，，我又来提交bug了，项目紧急那个静音bug还预留着，没解决  又发现了新的，如上复写的onStatePlaying()   里面执行了暂停goOnPlayOnPause(); //直接进入暂停状态     这个暂停方法里面会报非法异常  
如下：
 java.lang.IllegalStateException
                                                                      at android.media.MediaPlayer._pause(Native Method)
                                                                      at android.media.MediaPlayer.pause(MediaPlayer.java:1542)
                                                                      at cn.jzvd.JZVideoPlayer.goOnPlayOnPause(JZVideoPlayer.java:289)
                                                                      at cn.jucheng.heart.view.widget.JZVideoPlayerStandard.onStatePlaying(JZVideoPlayerStandard.java:317)
                                                                      at cn.jzvd.JZVideoPlayer.onInfo(JZVideoPlayer.java:657)

**Comment by lipangit** [comment]
保持关注，有点复杂

**Comment by RXlung** [comment]
项目需求解决，以上所有的问题 在onStatePlaying() 调用暂停，静音 都可能非法异常（随机性），猜测原因是media实例的问题，项目结束有待研究！
项目解决 只要求上来直接禁音，所以在源码里初始化media的时候加上setVolume(0.0f, 0.0f);  就好了，这个当初没想到，笨死，哈哈，耽误不少时间，
经验：在build中依赖三方 无法满足需求 可尝试下载源码依赖

**Comment by lipangit** [comment]
没问题，解决了就好，感谢你的分享

**Comment by MorganGeng** [comment]
@lipangit   
上面提到的设置静音会报`IllegalStateException`的问题,我也遇到了,我的情景是在播放错误后,去切换静音状态就会报错.查看代码之后发现是在JZVideoPlayer的onError方法中有这样处理:
`
            if (isCurrentPlay()) {
                JZMediaManager.instance().releaseMediaPlayer();
            }

`
而这个时候,isCurrentPlay()判断是true的,所以在此时MediaPlayer被release掉了,这就是上面 @RXlung 提到setvolume报错的原因.希望可以考虑优化这个逻辑.

**Comment by lipangit** [comment]
解决了就好
