### ISSUE TITLE
Video Player onError

### ISSUE THREAD

**Issue by rajiniyadav** [lipangit/JiaoZiVideoPlayer#1737]
I am getting onError frequently, able to view first time if auto complete video while tap replay getting video failed to load  click retry issue, especially Android Nougat version mobile please let me know how to resolve this.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38035265-9be495f6-32d6-11e8-9ba9-62be0262fffd.png)

What error code? some error code does not affect playback. 
Did you go into onStateError() function?

**Comment by rajiniyadav** [comment]
getting  **# onError 1 - -2147483648 [3650284]** also i am using picasso in my project , it's happening only nougat version mobiles other mobiles are working fine.

**Comment by lipangit** [comment]
I think you should remove all picasso in your project, my huawei nova 2s also have this problem, android 6.0

**Comment by lipangit** [comment]
do not need progurd .  if   you  use ijkplayer, see ijkplayer progurd rule
