### ISSUE TITLE
Message: Unknown MediaEventType(6)

### ISSUE THREAD

**Issue by hanligong** [lipangit/JiaoZiVideoPlayer#1738]
进度条在走 声音也在播放  就是视频不动
D/MediaPlayer: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
D/MediaPlayer: Message: MEDIA_BUFFERING_UPDATE(3), ext1=100, ext2=0x0
D/MediaPlayer: Message: MEDIA_BUFFERING_UPDATE(3), ext1=100, ext2=0x0
D/MediaPlayer: Message: MEDIA_BUFFERING_UPDATE(3), ext1=100, ext2=0x0

**Comment by lipangit** [comment]
url 发来试试

**Comment by hanligong** [comment]
我使用的是demo的URL   当我activity pause的时候  在回来  继续播放会出现这个情况  目前发现好像是SurfaceTexture的问题  不知你有何建议

**Comment by lipangit** [comment]
用法不对吧，你是要回来之后继续播放吗，demo有例子

**Comment by hanligong** [comment]
对  是要回来之后继续播放  能否告知是哪个例子呢

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38087920-96ca8b0a-338c-11e8-9107-d99760d93b93.png)

**Comment by hanligong** [comment]
按上面的方法  视频播放的现象同上  进度条在走 声音也在播放 视频画面不动

**Comment by hanligong** [comment]
6.0及以下手机都会出现这个现象   使用保存进度 进度条又会闪 继续播放  大部分手机又会有上面的问题  请问有没有其他的解决方案呢

**Comment by lipangit** [comment]
进度条闪是什么意思？能不能录个小视频看看，是进度条被设置可见和不可见了吗
