### ISSUE TITLE
progress 急

### ISSUE THREAD

**Issue by hanligong** [lipangit/JiaoZiVideoPlayer#1740]
mediaPlayer 保存进度后  再继续播放 视频后退了几秒 进度条会闪一下 怎么回事

**Comment by lipangit** [comment]
seekTo的时候不准确，比如seekTo到10秒，他会跳转到9.1秒，比如，所以会闪

**Comment by hanligong** [comment]
请问 可以准确的定位位置播放吗   比如seekTo到10秒 就从10秒开始播放呢  还是说由于视频的关键帧决定的  没有办法修复

**Comment by lipangit** [comment]
暂时不知道如何修复
