### ISSUE TITLE
demo中视频横竖屏切换有bug

### ISSUE THREAD

**Issue by szd201208** [lipangit/JiaoZiVideoPlayer#1741]
不知道作者有没有注意到，在demo里点击api-orientation，进入横竖屏切换页面时，点击横屏，有时候会横屏，有时候会竖屏。

**Comment by szd201208** [comment]
[https://img.hecaijing.com/development/picts/20180328/f0602384c2e13bd8cd34051604dba370.jpg](url)全屏显示的时候，有时候videoview下面的其他布局也会显示，会导致页面退出。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38035953-2633c0c8-32d8-11e8-94f9-05c52fff05bd.png)

这里已经严格限制了，非全屏是竖屏，全屏是横屏，有其他线索吗，改代码了吗，我自己没遇到过，其他人也没人提起过。

设置屏幕方向的代码会失败吗 你用的demo版本是多少
