### ISSUE TITLE
Videos take too long to start

### ISSUE THREAD

**Issue by smoan22** [lipangit/JiaoZiVideoPlayer#1747]
Very good library with just one problem and big one and that is it takes 60-70 seconds to start an online video even if it's a 2-3 secs video. How do i fix this. How do i fix it with code. Thank you

**Comment by lipangit** [comment]
android.media.MediaPlayer maybe takes a lot of time to load your url, you can on line code to change to ijkplayer, see demo.

**Comment by smoan22** [comment]
demo where?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38174589-19dcce64-3602-11e8-8c9a-de4ad58a8494.png)
