### ISSUE TITLE
use multiple videos Simultaneous in viewpager and save state

### ISSUE THREAD

**Issue by moeintav** [lipangit/JiaoZiVideoPlayer#1750]
Hi thank you for your library. I want to use multiple videos in view pager and save states in it how I am do it. sorry for bad english

**Comment by lipangit** [comment]
I know your mean.
If you want to play multiple videos at the same time , you should change the foundation design of the code, it is complex.

What do you mean "save states". you can overwrite onState... function   to get the state event.
![image](https://user-images.githubusercontent.com/2038071/38374209-b4c58198-3925-11e8-9ddc-4db68a028104.png)
