### ISSUE TITLE
如何把自定义播放器类的数据带到全屏中去？

### ISSUE THREAD

**Issue by scar1et** [lipangit/JiaoZiVideoPlayer#1751]
我打断点看，播放器在非全屏状态是有我设置好的数据的，但是切到全屏，数据就变成null了

**Comment by yangfeng1994** [comment]
我也遇到了这种问题，切换全屏时，重新走了构造方法，数据不会重新有的。

**Comment by lipangit** [comment]
把新传进度去的数据放到setUp的最后一个参数ojects[]数组中，这个可以全屏非全屏见传递
