### ISSUE TITLE
屏幕旋转时，闪退

### ISSUE THREAD

**Issue by zhenqinrui** [lipangit/JiaoZiVideoPlayer#1758]
屏幕旋转时闪退了，报的错了mediaplay.getduration illgestateexception，Activity配置了属性了  android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"，这是什么问题？

**Comment by TrueloveSomeGIRl** [comment]
这是 获取时长的问题 你视频时间是多少

**Comment by lipangit** [comment]
这个按照demo做应该就没问题，配置了这个属性也不行吗

**Comment by zhenqinrui** [comment]
找到问题了，是主题有问题，我们的activity主题是NoActionbar的，就会奔溃，播放器里面需要用Actionbar的操作吧，导致了奔溃，以后能否支持？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38533747-4cd6b828-3cad-11e8-86d2-38897c6aa221.png)

做了判断了，这是一个问题，log是什么，需要解决
