### ISSUE TITLE
setJzUserAction为什么要用静态？

### ISSUE THREAD

**Issue by zhenqinrui** [lipangit/JiaoZiVideoPlayer#1760]
你好，我想问下JZVideoPlayer中的setJzUserAction 这个方法，是否改为非静态会更好，应该一个项目有时候有多个播放器，设置了静态事件后，比如在里面做统计，这时候就会把不同业务的都统计进来了，是不符合的，改为成员变量就可以了，属于对象的

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/38533079-3d6055d2-3caa-11e8-8905-25215c44bef0.png)

这几个变量来自setUp函数，可以通过最后一个objects来区分这个事件是来自具体那个播放器

**Comment by zhenqinrui** [comment]
哦，这样那也可以

**Comment by lipangit** [comment]
jzvd 验证
