### ISSUE TITLE
短视频地址无法播放，进度条一直在转，但就是不播放视频

### ISSUE THREAD

**Issue by wangjiand** [lipangit/JiaoZiVideoPlayer#1762]
# 短视频地址无法播放，进度条一直在转，但就是不播放视频
 holder.jzVideoPlayer.setUp(
                       “https://cxvideo.oss-cn-hangzhou.aliyuncs.com/1160851523178394_272x480.mp4”, JZVideoPlayer.SCREEN_WINDOW_LIST,
  "");

**Comment by lipangit** [comment]
亲测能播
