### ISSUE TITLE
有自定义的ActionBar,横竖屏切换出来后，覆盖了原来的ActionBar

### ISSUE THREAD

**Issue by yijiehello** [lipangit/JiaoZiVideoPlayer#1770]
使用了hideSupportActionBar()只能解决全屏-横屏出来的，全屏-竖屏模式出来不行，哪位大神指教下

**Comment by yijiehello** [comment]
恩，全屏退出的时候ActionBar会显示，但不是我自定义的样式，感觉是播放器控制的ActionBar遮盖自定义的，我在屏幕切屏的方法里面调用了JZVideoPlayer隐藏ActionBar方法没有生效。

**Comment by lipangit** [comment]
你的actionBar如何隐藏，把它替换库里隐藏ActionBar的代码
