### ISSUE TITLE
拖动进度条后，加载中的转圈动画怎么才能显示出来？

### ISSUE THREAD

**Issue by scar1et** [lipangit/JiaoZiVideoPlayer#1771]
现在没有这个动画以后在网络不太稳定的地方播放体验非常差

**Comment by scar1et** [comment]
加载的时候没有进onStatePreparing方法

**Comment by lipangit** [comment]
对，参考旧版本，把控制loadingProgress的代码复制回来

**Comment by scar1et** [comment]
@guoyongxing @lipangit 我看看，谢谢
