### ISSUE TITLE
1，-1004

### ISSUE THREAD

**Issue by andy19910618** [lipangit/JiaoZiVideoPlayer#1774]
视频播放一段时间就报错，看了很多，但是没有找到解决办法，请问大佬这个有解决办法没有？

**Comment by lipangit** [comment]
这个问题不好说，可能和视频源有关系，1004是io问题，可以一行代码切换到ijkplayer试试

**Comment by andy19910618** [comment]
切换到ijkplayer 无法播放https 然后改成http 后 视频又没有图像，只有声音了，这个问题有人遇到过没？

**Comment by lipangit** [comment]
ijkplayer播放https视频需要重新配置编译ijkplayer
