### ISSUE TITLE
快进然后锁屏，快进提示框无法消失 

### ISSUE THREAD

**Issue by easyandroid** [lipangit/JiaoZiVideoPlayer#1781]
![gor2 c f 0 ql wfquw7d g](https://user-images.githubusercontent.com/5576002/38868168-c11f03fe-4278-11e8-8f5e-0f0874f29f17.jpg)
快进然后锁屏，快进提示框无法消失

**Comment by lipangit** [comment]
我会尽快修改，你可以提交pr来修改

**Comment by lipangit** [comment]
已经修复

**Comment by easyandroid** [comment]
感谢饺子大佬，问一下有没有考虑添加屏幕横屏锁定按钮的功能哈，像视频网站那样横屏锁定。再次感谢饺子。
