### ISSUE TITLE
全屏下隐藏那个全屏按钮

### ISSUE THREAD

**Issue by JayChan95318** [lipangit/JiaoZiVideoPlayer#1782]
我看过demo里面的一进去就是全屏的，此时全屏按钮点了之后是退出，我想把全屏按钮隐藏起来，可是调用的JZVideoPlayerStandard.fullscreenButton,setVisivity(VIew.GONE)，但是没起到什么左右，所以求教一下要怎么实现

**Comment by lipangit** [comment]
这是自定义ui的部分，参考demo的MyJZVideoPlayerStandard，复写各个状态的函数，在各个状态中分别设置按钮的visibily or invisibily

**Comment by JayChan95318** [comment]
还是不行，复写了每个状态的函数，里面都把按钮隐藏了，可是还是显示，我都郁闷了，我看你源码里面都没有调用setVisibilit(View.visible) 为什么会这样？

**Comment by lipangit** [comment]
库里没有任何地方修改了fullscreenButton是否可见。
![image](https://user-images.githubusercontent.com/2038071/38910376-9dd4abf0-42fb-11e8-8a67-d4b3a2ee9fc4.png)

如上图全屏按钮就会消失，然后需要自己修改一下间距就好了

**Comment by JayChan95318** [comment]
试了，还是显示，我调用的是MyJZVideoPlayerStandard.startFullscreen();

**Comment by lipangit** [comment]
完整的代码截图看看，上面我的截图是亲测的没有问题
