### ISSUE TITLE
全屏修改亮度问题

### ISSUE THREAD

**Issue by HLMODRIC** [lipangit/JiaoZiVideoPlayer#1783]
全屏模式调节视频亮度，退出全屏时亮度为视频调节的亮度，系统的亮度调节也改不了亮度了，看了Demo，也有这个问题，只有有视频播放的activity生命周期结束后才能恢复系统全局亮度，但系统的亮度调节无论怎么修改，亮度也不变化了。
荣耀V9
8.0.0

**Comment by lipangit** [comment]
可以自定义，用你的代码替换修改亮度的代码。因为这部分代码是从头条中取得的，所以没必要修改。

**Comment by HLMODRIC** [comment]
多谢，下午试试！

**Comment by chenka321** [comment]
退出全屏 亮度无法回到系统亮度

**Comment by lipangit** [comment]
这个改的是app的亮度，你可以自定义复写onTouch函数，将修改亮度的代码替换成修改系统亮度。
