### ISSUE TITLE
什么时候出一个文章就是教我们手写list播放视频

### ISSUE THREAD

**Issue by qssq** [lipangit/JiaoZiVideoPlayer#1784]
实际上我想不用第三方的so库，想用系统自带的，如果你们有自带的封装的话，我可以考虑使用，但是我现在要从0开始解决recyclerview列表播放问题，

**Comment by lipangit** [comment]
默认的没有第三方so库，用的是android.media.MediaPlayer系统的播放器引擎。

列表播放的问题可以参考demo。

**Comment by qssq** [comment]
请问有具体切换为默认的么，似乎文档没有说

**Comment by lipangit** [comment]
什么也不做就没有ijkplayer

**Comment by qssq** [comment]
。有点蒙蔽，不太懂。 另外那个recyclerviewadapter找不到地址了
