### ISSUE TITLE
默认播放器不支持https

### ISSUE THREAD

**Issue by losefrank** [lipangit/JiaoZiVideoPlayer#1786]
请问如何配置可以支持https地址

**Comment by lipangit** [comment]
ijkplayer默认不支持https，这个需要重新编译打包ijkplayer

可以用默认的播放器android.media.MediaPlayer，可以播放https

**Comment by lipangit** [comment]
或者不验证https的身份

**Comment by losefrank** [comment]
谢谢，替换了别人编译好的ijkplayer的相关jar包就可以了。

**Comment by lipangit** [comment]
么么哒
