### ISSUE TITLE
有些手机能播,有些手机不能播

### ISSUE THREAD

**Issue by EvanEvil** [lipangit/JiaoZiVideoPlayer#1787]
播放地址:http:\/\/p2f58npc9.bkt.clouddn.com\/o_1cb8nhvli11j0mlr4p0q8q1fnea.mp4
测试:很多手机无法播放,有几个手机可以播放,
如魅族note6 无法播放,打印log日志:
04-18 16:43:25.938 30118-30118/com.juyanapp.czs D/JiaoZiVideoPlayer: startVideo [263318524] 
    addTextureView [263318524] 
04-18 16:43:25.944 30118-30118/com.juyanapp.czs D/STATUS_BAR_TINT: onWindowAttributesChanged
04-18 16:43:25.946 30118-30118/com.juyanapp.czs I/JiaoZiVideoPlayer: onStatePreparing  [263318524] 
04-18 16:43:25.947 30118-30118/com.juyanapp.czs I/JiaoZiVideoPlayer: onCompletion  [263318524] 
    onStateNormal  [263318524] 
04-18 16:43:25.949 30118-30118/com.juyanapp.czs D/STATUS_BAR_TINT: onWindowAttributesChanged
04-18 16:43:25.950 30118-30118/com.juyanapp.czs D/STATUS_BAR_TINT: onWindowAttributesChanged
04-18 16:43:25.952 30118-30118/com.juyanapp.czs D/JiaoZiVideoPlayer: startVideo [263318524] 
04-18 16:43:25.953 30118-30118/com.juyanapp.czs D/JiaoZiVideoPlayer: addTextureView [263318524] 
04-18 16:43:25.954 30118-30118/com.juyanapp.czs D/STATUS_BAR_TINT: onWindowAttributesChanged
04-18 16:43:25.954 30118-30118/com.juyanapp.czs I/JiaoZiVideoPlayer: onStatePreparing  [263318524] 
04-18 16:43:25.956 30118-30118/com.juyanapp.czs I/JZResizeTextureView: onMeasure  [233585567] 
    onMeasure  [233585567] 
    onMeasure  [233585567] 
    onMeasure  [233585567] 
04-18 16:43:25.965 30118-30118/com.juyanapp.czs I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [263318524] 
04-18 16:43:25.976 30118-31100/com.juyanapp.czs E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-18 16:43:25.976 30118-31100/com.juyanapp.czs E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-18 16:43:25.976 30118-31100/com.juyanapp.czs E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-18 16:43:25.976 30118-31100/com.juyanapp.czs E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-18 16:43:25.981 30118-31100/com.juyanapp.czs W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
04-18 16:43:25.987 30118-31100/com.juyanapp.czs W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
04-18 16:43:26.055 30118-31411/com.juyanapp.czs D/FlymeTrafficTracking: tag  (249) com.juyanapp.czs Binder:30118_4 uid 10237
04-18 16:43:26.769 30118-30202/com.juyanapp.czs D/FlymeTrafficTracking: untag(249) com.juyanapp.czs Okio Watchdog uid 10237 714ms
04-18 16:43:26.772 30118-4200/com.juyanapp.czs D/FlymeTrafficTracking: tag  (249) com.juyanapp.czs Binder:30118_5 uid 10237
04-18 16:43:26.987 30118-30130/com.juyanapp.czs D/FlymeTrafficTracking: untag(249) com.juyanapp.czs Binder:30118_1 uid 10237 215ms
04-18 16:43:27.092 30118-30131/com.juyanapp.czs D/FlymeTrafficTracking: tag  (249) com.juyanapp.czs Binder:30118_2 uid 10237
04-18 16:43:27.428 30118-30202/com.juyanapp.czs D/FlymeTrafficTracking: untag(249) com.juyanapp.czs Okio Watchdog uid 10237 336ms
04-18 16:43:27.432 30118-30131/com.juyanapp.czs D/FlymeTrafficTracking: tag  (252) com.juyanapp.czs Binder:30118_2 uid 10237
04-18 16:43:27.627 30118-30165/com.juyanapp.czs D/FlymeTrafficTracking: untag(252) com.juyanapp.czs Binder:30118_3 uid 10237 195ms
04-18 16:43:27.732 30118-30165/com.juyanapp.czs D/FlymeTrafficTracking: tag  (252) com.juyanapp.czs Binder:30118_3 uid 10237
04-18 16:43:28.069 30118-30202/com.juyanapp.czs D/FlymeTrafficTracking: untag(252) com.juyanapp.czs Okio Watchdog uid 10237 337ms
04-18 16:43:28.081 30118-4200/com.juyanapp.czs D/FlymeTrafficTracking: tag  (249) com.juyanapp.czs Binder:30118_5 uid 10237
04-18 16:43:28.389 30118-30130/com.juyanapp.czs D/FlymeTrafficTracking: untag(249) com.juyanapp.czs Binder:30118_1 uid 10237 309ms
04-18 16:43:28.405 30118-31100/com.juyanapp.czs D/MediaPlayer: setSubtitleAnchor in MediaPlayer
04-18 16:43:28.418 30118-30118/com.juyanapp.czs I/JiaoZiVideoPlayer: onVideoSizeChanged  [263318524] 
04-18 16:43:28.428 30118-30118/com.juyanapp.czs I/JZResizeTextureView: onMeasure  [233585567] 
04-18 16:43:28.429 30118-30118/com.juyanapp.czs I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
    heightMeasureSpec [MeasureSpec: EXACTLY 630]
    onMeasure  [233585567] 
    widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
    heightMeasureSpec [MeasureSpec: EXACTLY 630]
    onMeasure  [233585567] 
04-18 16:43:28.430 30118-30118/com.juyanapp.czs I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
    heightMeasureSpec [MeasureSpec: EXACTLY 630]
    onMeasure  [233585567] 
    widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
    heightMeasureSpec [MeasureSpec: EXACTLY 630]
04-18 16:43:28.498 30118-4200/com.juyanapp.czs D/FlymeTrafficTracking: tag  (249) com.juyanapp.czs Binder:30118_5 uid 10237

**Comment by EvanEvil** [comment]
上面那个是项目中打印的log,无法播放的时候,一直转圈,我又写了一个demo,全都不能播放,显示视频加载失败
打印log:
04-18 17:11:07.407 29291-29291/com.evan.qianniu.test I/JiaoZiVideoPlayer: onStateNormal  [251375508] 
04-18 17:11:07.442 29291-29291/com.evan.qianniu.test D/PhoneWindow: initNavigationBarColor color-526345,dark=true
04-18 17:11:07.717 29291-29291/com.evan.qianniu.test D/EvanLog:BaseActivity.onNetChange(Line:89): netState:1
04-18 17:11:07.813 29291-29333/com.evan.qianniu.test D/OpenGLRenderer: endAllActiveAnimators on 0xcd08bf80 (RippleDrawable) with handle 0xc2d3b1e0
04-18 17:11:11.511 29291-29291/com.evan.qianniu.test I/JiaoZiVideoPlayer: onClick start [251375508] 
04-18 17:11:11.512 29291-29291/com.evan.qianniu.test D/JiaoZiVideoPlayer: startVideo [251375508] 
    addTextureView [251375508] 
04-18 17:11:11.521 29291-29291/com.evan.qianniu.test D/STATUS_BAR_TINT: onWindowAttributesChanged
04-18 17:11:11.522 29291-29291/com.evan.qianniu.test I/JiaoZiVideoPlayer: onStatePreparing  [251375508] 
04-18 17:11:11.523 29291-29291/com.evan.qianniu.test I/JZResizeTextureView: onMeasure  [85076593] 
    onMeasure  [85076593] 
04-18 17:11:11.529 29291-29291/com.evan.qianniu.test I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [251375508] 
04-18 17:11:11.535 29291-29327/com.evan.qianniu.test E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-18 17:11:11.536 29291-29327/com.evan.qianniu.test E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-18 17:11:11.536 29291-29327/com.evan.qianniu.test E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-18 17:11:11.536 29291-29327/com.evan.qianniu.test E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-18 17:11:11.538 29291-29327/com.evan.qianniu.test W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
04-18 17:11:11.554 29291-29304/com.evan.qianniu.test E/MediaPlayer: error (1, -2147483648)
04-18 17:11:11.554 29291-29327/com.evan.qianniu.test W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
04-18 17:11:11.555 29291-29327/com.evan.qianniu.test E/MediaPlayer: Error (1,-2147483648)
04-18 17:11:11.555 29291-29291/com.evan.qianniu.test E/JiaoZiVideoPlayer: onError 1 - -2147483648 [251375508] 
04-18 17:11:11.555 29291-29291/com.evan.qianniu.test I/JiaoZiVideoPlayer: onStateError  [251375508]

**Comment by lipangit** [comment]
可以一行代码切换到ijkplayer

**Comment by lipangit** [comment]
亲测能播
