### ISSUE TITLE
Video loading taking more time

### ISSUE THREAD

**Issue by rajiniyadav** [lipangit/JiaoZiVideoPlayer#1789]
While click play button it takes more time steaming to play the video, can't play play like you-tube and face-book videos(level by level streaming) please help.

**Comment by lipangit** [comment]
it depends on video engine.  android.media.MediaPlayer is slow. you can change to ijkplayer by one line code.

**Comment by reverseAndroid** [comment]
@lipangit 你好，请问一下如果切换成ijkplayer，是否需要编译几个  .so库放进项目里？

**Comment by lipangit** [comment]
理论不需要，先试试再说
