### ISSUE TITLE
可以在dialog和DialogFragment进行播放和全屏切换吗

### ISSUE THREAD

**Issue by Lee-Jian** [lipangit/JiaoZiVideoPlayer#1790]

**Comment by lipangit** [comment]
可以

**Comment by kofihust** [comment]
在DialogFragment里切全屏，视频在Dialog的下层，Dialog在最上面，有什么解决办法吗？

**Comment by kofihust** [comment]
> 可以

在DialogFragment里切全屏，视频在Dialog的下层，Dialog在最上面，有什么解决办法吗？

**Comment by lipangit** [comment]
@kofihust 你这样尝试过吗，遇到了什么问题，什么现象
