### ISSUE TITLE
Crash app in onChildViewDetachedFromWindow mehthod

### ISSUE THREAD

**Issue by shiv71** [lipangit/JiaoZiVideoPlayer#1791]
**I have one activity in this activity i have add fragment and in this fragment i have recycleview.
 I am using this player in  recycleview.
My code that crash my app when i scroll the list, is here.**

 recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {

                JZVideoPlayer jzvd = view.findViewById(R.id.videoplayer);
                if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
                    JZVideoPlayer currentJzvd = JZVideoPlayerManager.getCurrentJzvd();
                    if (currentJzvd != null && currentJzvd.currentScreen != JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN) {
                        JZVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });

**Error code is here.**

  java.lang.NullPointerException: Attempt to read from null array
 at cn.jzvd.JZUtils.dataSourceObjectsContainsUri(JZUtils.java:168) at HomeFragment$1.onChildViewDetachedFromWindow(HomeFragment.java:164)
    at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7152)
    at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:794)

**Comment by lipangit** [comment]
whitch is null, check null  , you can change the code.

if(xxx !=null){

}

**Comment by LightProspect** [comment]
我也出现这样的错误，但是我没有看太懂你的回答

**Comment by lipangit** [comment]
@LightProspect 你看log是什么，然后分析里面哪个变量为空，然后断点看setUp进来的参数有什么问题

**Comment by LightProspect** [comment]
谢谢回复 已解决

**Comment by lipangit** [comment]
么么哒
