### ISSUE TITLE
4g全屏状态下，当检测到4G，点停止播放停留在全屏页面，不会退出，而且点标题前面的返回键没有反应

### ISSUE THREAD

**Issue by TracyEminem** [lipangit/JiaoZiVideoPlayer#1793]
标题的返回键只能在播放状态下才有作用，4G情况下，想返回，必须用4G播放，然后返回键才起作用。。。

**Comment by lipangit** [comment]
亲测，不管什么网络，不管是否暂停，都可以通过标题左边的返回按钮退出全屏。你能录个小视频吗，或者按步骤说一下如何复现

**Comment by TracyEminem** [comment]
我在饺子视频2群里放了一个视频，就是当我以4G状态进去全屏页面，弹出检测网络的dialog后，点标题左边的返回键就无法返回了，除非我点继续播放，视频一播放，这个返回又有效了，可以返回了。

**Comment by lipangit** [comment]
这个问题以前修复过了，才想起来，点击取消播放的时候会直接退出全屏。

**Comment by lipangit** [comment]
更新一下库
