### ISSUE TITLE
为什么重复设置播放源和标题，视频地址变了，而标题还是第一个视频的标题呢？

### ISSUE THREAD

**Issue by Andoridswordsman** [lipangit/JiaoZiVideoPlayer#1794]
为什么重复设置播放源和标题，视频地址变了，而标题还是第一个视频的标题呢？

**Comment by Andoridswordsman** [comment]
正常播放的时候标题变了，切换到全屏，发现是第一个视频的 标题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/39129317-ccb3175a-473c-11e8-9d56-71d974632246.png)

是的，这是退出全屏的函数，没有设置标题。 我想想这个问题。
你可以临时JZVideoPlayerManager.getFirstFloor().titleTextView设置标题
