### ISSUE TITLE
*simple question*   how to create this button?

### ISSUE THREAD

**Issue by mohamedebrahim96** [lipangit/JiaoZiVideoPlayer#1796]
![weqweqweq](https://user-images.githubusercontent.com/16405013/39097113-2535e366-4658-11e8-96a9-bd5e17150201.JPG)

**Comment by lipangit** [comment]
see demo custom jzvd, and see smallChangeUiActivity.java

**Comment by mohamedebrahim96** [comment]
the problem solved :heart_eyes::heart_eyes:
thanks for your answer :boom: :sparkles:
---------------------

**Comment by deryfath** [comment]
can I put it on top?
