### ISSUE TITLE
切换清晰度之后，进入播放状态，原形进度条不消失。

### ISSUE THREAD

**Issue by wangzixu5678** [lipangit/JiaoZiVideoPlayer#1797]
如题 再API界面 切换清晰度，进入播放状态 进度条依然显示，并且无法进行播放器控制。

**Comment by wangzixu5678** [comment]
找到了JZMediaSystem 里demo里面 判断if (currentDataSource.toString().toLowerCase().contains("mp3"))为false 导致 JZVideoPlayerManager.getCurrentJzvd().onPrepared()不被调用 ;

**Comment by lipangit** [comment]
是的，这是个bug，以前的修改带出的这个问题
