### ISSUE TITLE
视频全屏后再横屏闪退，是我还差什么没有配置吗？求解

### ISSUE THREAD

**Issue by ShuJianFeng91** [lipangit/JiaoZiVideoPlayer#1804]
打印出这个东西，没有别的错误打印
E/BufferQueueProducer: [SurfaceTexture-0-27762-0] cancelBuffer: BufferQueue has been abandoned

**Comment by ShuJianFeng91** [comment]
我下载了demo，运行后全屏再横屏，又能正常运行，配置只根据下面的Usage来弄的

**Comment by lipangit** [comment]
是不是maifest没配置
