### ISSUE TITLE
您好,视频未开始播放状态如何获取总时长,getDuration返回为0,在播放状态下获取正常

### ISSUE THREAD

**Issue by hellocl** [lipangit/JiaoZiVideoPlayer#1806]

**Comment by luoxiaojing** [comment]
播放状态下如何获取总时长？

**Comment by lipangit** [comment]
复写onVideoSize函数

**Comment by luoxiaojing** [comment]
是自定义MyJzvdstd 在这里写onvideosize？？ 可是我只找见了onVideoSizeChange的方法 版本是7.0.5
&nbsp;
还有一个问题是重新播放视频的时候出现了&nbsp; java.net.ProtocolException
这个链接放到demo中运行的很好&nbsp; 偶尔会出现重播的时候&nbsp; java.net.ProtocolException
我的放视频的地方是给recycview添加的头部中
重播的时候 再onerror中写relaseallVideos(), startVideo(); 还是会出现 java.net.ProtocolException 想问问怎么解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nathen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午4:51
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"我是一朵水莲花"<993268281@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 您好,视频未开始播放状态如何获取总时长,getDuration返回为0,在播放状态下获取正常 (#1806)




复写onVideoSize函数

**Comment by lipangit** [comment]
就是这个函数onVideoSizeChange。


播放错误是播放内核返回的错误，我们不能解决只能处理，遇到错误就进入错误state的ui，用户可以点击重播，目前觉得没必要做其他的事情。



---原始邮件---
发件人: "luoxiaojing"<notifications@github.com&gt;
发送时间: 2020年3月18日(周三) 上午10:03
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 您好,视频未开始播放状态如何获取总时长,getDuration返回为0,在播放状态下获取正常 (#1806)




 是自定义MyJzvdstd 在这里写onvideosize？？ 可是我只找见了onVideoSizeChange的方法 版本是7.0.5 
 &amp;nbsp; 
 还有一个问题是重新播放视频的时候出现了&amp;nbsp; java.net.ProtocolException 
 这个链接放到demo中运行的很好&amp;nbsp; 偶尔会出现重播的时候&amp;nbsp; java.net.ProtocolException 
 我的放视频的地方是给recycview添加的头部中 
 重播的时候 再onerror中写relaseallVideos(), startVideo(); 还是会出现 java.net.ProtocolException 想问问怎么解决 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Nathen"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月23日(星期天) 下午4:51 
 收件人:&amp;nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"我是一朵水莲花"<993268281@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [lipangit/JiaoZiVideoPlayer] 您好,视频未开始播放状态如何获取总时长,getDuration返回为0,在播放状态下获取正常 (#1806) 
 
 
 
 
 复写onVideoSize函数
