### ISSUE TITLE
Fullscreen Landscape video play getting crash

### ISSUE THREAD

**Issue by rajiniyadav** [lipangit/JiaoZiVideoPlayer#1811]
![selection_002](https://user-images.githubusercontent.com/4010984/39290890-bfbad858-494e-11e8-9278-c36876b38622.png)

While rotate the device on fullscreen video play getting issue, how to resolve this.

**Comment by lipangit** [comment]
break point at mediaPlayer.release(), it will be called at a wrong time.

**Comment by rajiniyadav** [comment]
Getting in some devices and some videos not for all videos

**Comment by lipangit** [comment]
I have seen the exception before, in listview fullscreen and landscape. It because landscape will call listview getView . 

This exception It's hard to understand that if you start from exception, you can't find the root cause.

**Comment by rajiniyadav** [comment]
Getting issues while rotate full screen video playing...
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
How to resolve it...tried with break point also

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/40587773-664889f2-6206-11e8-9bc9-795646efa013.png)


break point here, you can find it be called at a wrong time, fix it.

[ 'int android.view.View.getVisibility()' on a null object reference ] nothing about it

**Comment by rajiniyadav** [comment]
Finally...fixed the issue..thanks
