### ISSUE TITLE
可以设置缓存吗

### ISSUE THREAD

**Issue by JayChan95318** [lipangit/JiaoZiVideoPlayer#1812]
每次播放完成后重播感觉没缓存，都是重新请求网络，请问可以设置缓存吗？

**Comment by lipangit** [comment]
播放器引擎有api就可以设置，ijkplayer可以研究一下，但是android.media.MediaPlayer没有相关api

**Comment by JayChan95318** [comment]
切换成ijkplayer就能缓存吗
