### ISSUE TITLE
Activity中ViewPager有五个Fragment,Fragment中用RecycleView

### ISSUE THREAD

**Issue by superxsx** [lipangit/JiaoZiVideoPlayer#1813]
Activity中ViewPager有五个Fragment,Fragment中用RecycleView  在RecycleView中点击列表播放，全屏可以竖屏，但不能横屏 ，横屏会退出全屏播放 并且会调用Fragment的setUserVisibleHint 及
Log打印 E/BufferQueueProducer: [SurfaceTexture-0-16487-0] cancelBuffer: BufferQueue has been abandoned

版本  cn.jzvd:jiaozivideoplayer:6.2.9
activity设置

         <activity
            android:name=".ui.activity.SongSheetActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar"
             />

RecycleView监听
mRecyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
            }
            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzvd = view.findViewById(R.id.videoplayer);
                if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
                    JZVideoPlayer.releaseAllVideos();
                }
            }
        });

**Comment by lipangit** [comment]
你发的log应该不是导致错误的log

**Comment by superxsx** [comment]
不知道为什么 今天登上突然就可以了 没改配置什么的 。。。

**Comment by lipangit** [comment]
么么哒
