### ISSUE TITLE
Progress Bar move to 100% though it has complete 1%

### ISSUE THREAD

**Issue by avinashp2487** [lipangit/JiaoZiVideoPlayer#1816]
Hello,

I having issue with the player when I start the video the seekbar is showing me at the end(100%) and because of that in setOnSeekBarChangeListener the progress value is giving 100 after few seconds the video seekbar comes to it original position.

Please find the attached screen shot.

Thank you

![untitled-1](https://user-images.githubusercontent.com/38852197/39419377-3dfa9dee-4c7d-11e8-9540-e7c7a957d7f8.png)

**Comment by lipangit** [comment]
Does  it often happened?  

![image](https://user-images.githubusercontent.com/2038071/39479823-fe89c32a-4d98-11e8-9322-5208ca1abec1.png)

you can see the source code, they are the same value , you should break point and find out what are the two value is
