### ISSUE TITLE
OnComplete listener in Recyclerview

### ISSUE THREAD

**Issue by sonandur** [lipangit/JiaoZiVideoPlayer#1819]
Hi Lipangit, thanks for library. It is beneficial for many android developers.
I am using JZVideoPlayerStandard in Recyclerview, I need on complete video listener for this.
Please help me. I could not create class which extends JZVideoPlayer class as I am using Recyclerview.
Thanks.

**Comment by lipangit** [comment]
you should create class extends JZVideoPlayerStandard and override onComplete function, it will catch complete event.

**Comment by MickeyBadBad** [comment]
@sonandur , i think also override the showWifiDialog method in JZVideoPlayerStandard . make it do nothing will do .

**Comment by sonandur** [comment]
@lipangit If I extends JZVideoPlayerStandard class, video is playing but full screen is not working.
Please find the code I am using:
Here I am using class NativeVideoPlayer extends JZVideoPlayerStandard 

In Adapter

`NativeVideoPlayer nativePlayer = new NativeVideoPlayer(mContext,videoListener);
                    nativePlayer = (NativeVideoPlayer) mNativeVideoViewHolder.videoPlayer ;
                    nativePlayer.setUp(videoUrl,JZVideoPlayer.SCREEN_WINDOW_LIST,"");`

In ViewHolder class

` videoPlayer = (NativeVideoPlayer) itemView.findViewById(R.id.video_native_player);`

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/39579151-a151bfec-4f18-11e8-9a7f-c94f8de7f76f.png)
