### ISSUE TITLE
华为荣耀畅玩6   Android6.0 上无法播放视频 这个是什么原因呢

### ISSUE THREAD

**Issue by kris-liutao** [lipangit/JiaoZiVideoPlayer#1820]
@felipetorres

**Comment by lipangit** [comment]
应该和视频有关系，demo的链接能在这些手机上播吗

**Comment by x58548078** [comment]
楼主解决了吗，我也是这个问题

**Comment by centerzx** [comment]
![tim 20181119021531](https://user-images.githubusercontent.com/8621915/48676377-0fac1d00-eba1-11e8-83da-55aa0fa638a8.png)

**Comment by lipangit** [comment]
@centerzx demo的链接能在这些手机上播吗
