### ISSUE TITLE
ply vids in loop 

### ISSUE THREAD

**Issue by H1-N1** [lipangit/JiaoZiVideoPlayer#1821]
how to play vedio in loop and also is ther any speasil config for iptv url "ts" becaus the player is very slow and laguing !!!
also when a play vedio  only song i played!!!
this is a link if someone want to test : http://iptv.ndasat.com:88/live/550290029873347/550290029873347/1708.ts
thx

**Comment by H1-N1** [comment]
hi tnx for replay 
the problem is when  i play vedio only the song is played without video image!!!
a nother problem i face now .. see the image below

![screenshot_20180526-041411](https://user-images.githubusercontent.com/22596773/40572557-95a655c6-609e-11e8-961c-6009ed7c2565.png)

![Uploading Screenshot_20180526-041411.png…]()

**Comment by lipangit** [comment]
What's wrong?

**Comment by H1-N1** [comment]
this player is good but infortunaly not for iptv streaming 
black screan ,wating too long to play streamed tv , error c ant not play this video ...
thx

**Comment by lipangit** [comment]
you can change to ijkplayer in one line code.

**Comment by H1-N1** [comment]
can you plz show me how??

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/40718605-3e199126-6443-11e8-8fe7-dd12a7cfa702.png)
