### ISSUE TITLE
请问小屏播放的时候怎么放开滑动调整进度的功能？

### ISSUE THREAD

**Issue by ymw2017** [lipangit/JiaoZiVideoPlayer#1822]
现在全屏的时候可以滑动调整进度，请问非全屏的时候怎么放开滑动调整进度的功能呢？

**Comment by lipangit** [comment]
复写onToucn函数，复制父类的内容，删除是否全屏的判断即可。  本来是全屏和非全屏都能调整，单独屏蔽了非全屏。
