### ISSUE TITLE
昨天在谷歌手机上测试发现进度条进度一直是0，总进度也是0，我是用demo运行的，求解

### ISSUE THREAD

**Issue by ymw2017** [lipangit/JiaoZiVideoPlayer#1823]

**Comment by ymw2017** [comment]
谷歌手机系统版本是7.1.2
![560233962935785413](https://user-images.githubusercontent.com/24970365/39609859-a05df022-4f7e-11e8-9aa3-56a128feb147.jpg)

**Comment by lipangit** [comment]
链接发来看看

**Comment by lipangit** [comment]
它这个getDuration有问题，超出老臣解决范围。系统api有问题
