### ISSUE TITLE
recyclerview切换视屏的时候我们如何监听？

### ISSUE THREAD

**Issue by wuxiaojun123** [lipangit/JiaoZiVideoPlayer#1826]
请教一下，我是在Fragment里使用recyclerview，recyclerview嵌套的jiaoziVideoPlayer，我的需求是拿到每一个视屏看了多长时间，现在问题是用户切换视屏的时候不知道怎么监听事件?如何在用户播放一个视屏的时候再点击另外一个视屏我这边能监听到？自己尝试过onCompletion方法，但是发现这个方法会回调多次！

**Comment by wuxiaojun123** [comment]
onCompletion这个方法在加载更多的情况下又会触发一次。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/39630240-5ba5fe80-4fe1-11e8-9398-9b9051fa7a2d.png)


参考这个判断，这个是保存播放进度的。判断一下播放状态

**Comment by wuxiaojun123** [comment]
谢谢，在这个onCompletion方法里然后再根据currentState来判断是可以监听到视频切换的。

**Comment by lipangit** [comment]
ok 加油小宝贝
