### ISSUE TITLE
横屏的时候手势调音量和亮度有问题

### ISSUE THREAD

**Issue by youarenowhere** [lipangit/JiaoZiVideoPlayer#1828]
正常情况下，左侧手势调整亮度，右侧调整音量。
全屏后，在左侧靠近屏幕中间的部分，上下滑动会出现调整音量问题。
魅族note6

**Comment by lipangit** [comment]
这个左右的判断已经很精准了，你能截图看看吗，标一下

![image](https://user-images.githubusercontent.com/2038071/39630843-2ab9a13a-4fe3-11e8-873c-ebdc5d671e1c.png)

**Comment by youarenowhere** [comment]
http://p7qpzpt5r.bkt.clouddn.com/Android_2018_05_05_03_44_59_1_3955.mp4
看视频

正常情况下，左侧手势调整亮度，右侧调整音量。
全屏后，在左侧靠近屏幕中间的部分，上下滑动会出现调整音量问题。

**Comment by lipangit** [comment]
是的，这是个问题，因为全屏的时候首先进入竖屏的全屏，然后左侧的判断左侧会小很多

**Comment by lipangit** [comment]
现在无法区分全屏之后是横向的全屏还是竖向的全屏
