### ISSUE TITLE
fragment嵌套recyclerview，当视频正在加载中，然后立马切换fragment，当视频加载完成的时候，会自动播放，但是此时界面已经切换了。

### ISSUE THREAD

**Issue by wuxiaojun123** [lipangit/JiaoZiVideoPlayer#1829]
在fragment的onPause方法中已调用了releaseAllVideos()方法，但还是会出现这个bug。

**Comment by lipangit** [comment]
断点一下，releaseAllVideos，如果调了肯定不会播放的。

**Comment by lipangit** [comment]
断点一下releaseAllVideos，如果调了肯定不会播放的，或者是onPause的问题，在更直观的地方调用releaseAllVideos

**Comment by wuxiaojun123** [comment]
哥们，情况是这样的，我点击播放一个视屏，在它加载中的时候，立马往下滑动，我打断点跟踪了，确实调用了releaseAllVideos，是先调用的releaseAllVides方法，然后再调用的播放方法，看来在releaseAllVideos方法中要多加一个方法判断了，如果是加载中就应该立马置为正常状态。我先找找有什么解决办法

**Comment by lipangit** [comment]
好，逻辑问题

**Comment by wuxiaojun123** [comment]
大佬，我处理了一下这个问题，我是使用的标记，然后判断currentState是否为准备中，然后当准备完成开始播放的时候，判断是否releaseAllVideos过，然后再暂停这个视频，虽然能解决目前的问题，但是觉得不够优雅，是否有更好的解决方案呢？多指教！

**Comment by lipangit** [comment]
可以加qq语音聊

**Comment by wuxiaojun123** [comment]
我已经入2群了

**Comment by wuxiaojun123** [comment]
确实如你说的，fragment的onPause方法会有延迟效果，大家注意一定要在Activity的切换Fragment方法里去调用releaseAllVideos方法，切记！

**Comment by lipangit** [comment]
么么哒
