### ISSUE TITLE
全屏下UI控制问题

### ISSUE THREAD

**Issue by zhongyuanwu** [lipangit/JiaoZiVideoPlayer#1833]
源码中 startWindowFullscreen方法里 通过反射创建的是JZVideoPlayer对象 那么在自定义对象和JZVideoPlayerStandard对象中部分UI是不能控制的，只有JZVideoPlayer初始化的控件才能通过 JZVideoPlayerManager.getCurrentJzvd().XXX.setVisibility() 控制显示，怎么解决。

**Comment by lipangit** [comment]
自定义Ui参考demo的smallChangeUiActivity，继承JZVideoPlayerStandard再自定义UI

**Comment by zhongyuanwu** [comment]
已解决，setup方法问题，有两个，用setUp(Object[] dataSourceObjects, int defaultUrlMapIndex, int screen, Object... objects) 就好了

**Comment by lipangit** [comment]
么么哒
