### ISSUE TITLE
releaseAllVideos 之后状态栏出现

### ISSUE THREAD

**Issue by VVZ1991** [lipangit/JiaoZiVideoPlayer#1835]
本来app没有状态栏的。 但是两个具有视频播放功能的fragment关闭并切换导致了状态栏的显示。
![image](https://user-images.githubusercontent.com/8370996/39693268-0f87cff6-5216-11e8-84ce-bd1919afcd6a.png)
代码参照的ActivityOrientation...改的。请问该如何控制。

**Comment by VVZ1991** [comment]
Activity在使用Actionbar主题时 设置了Actionbar.hide。 视频播放结束后actionbar 重现.

 设置 JZVideoPlayer.ACTION_BAR_EXIST 的值   
 JZVideoPlayer.TOOL_BAR_EXIST 也是同理。


https://shimo.im/docs/xj5F85W1gqEEBXRJ


自问自答 没有好好看文档

**Comment by lipangit** [comment]
么么哒小宝贝
