### ISSUE TITLE
How to get current player state like current postion?

### ISSUE THREAD

**Issue by mdaslamHossin** [lipangit/JiaoZiVideoPlayer#1836]

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/39703504-d5acfa0c-523a-11e8-8d71-03ef57eb88dd.png)

catch state event. and you can also get mCurrentState to get state value

**Comment by mdaslamHossin** [comment]
Okay, I added this to my video view now I want to the listener for player current state how to use it? This not interface which I can implement in my activity

**Comment by lipangit** [comment]
see demo MyJZVideoPlayerStandard, and smallChangeUiActivity.  There is no listener,  you must extends JZVideolPlayerStandard first.
