### ISSUE TITLE
RecyclerView复杂布局 .addOnChildAttachStateChangeListener中  jzvd.dataSourceObjects为null

### ISSUE THREAD

**Issue by zimengfang** [lipangit/JiaoZiVideoPlayer#1842]
mRecyclerView.getRecyclerView().addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzvd = view.findViewById(R.id.video_view);// 把这个id替换成你自己的
                //  回收
                if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
                    if(JZVideoPlayerManager.getCurrentJzvd().currentScreen != JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN){
                        JZVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });

**Comment by lipangit** [comment]
参考新版demo，记得修改过，加了一个判断
