### ISSUE TITLE
Play Unicode url

### ISSUE THREAD

**Issue by sonshark** [lipangit/JiaoZiVideoPlayer#1844]
Can't play URLs with Unicode characters.

**Comment by lipangit** [comment]
yes，maybe android.media.MediaPlayer not support

**Comment by sonshark** [comment]
My solution is set Unicode character to be percent-encoded

**Comment by sonshark** [comment]
My solution:

String urlStr = "http://test.com/0007AC/ads/800x480 15sec h.264 Â Ơ.mp4";
URL url = new URL(urlStr);
URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), url.getPath(), url.getQuery(), url.getRef());
url = uri.toASCIIString();

**Comment by lipangit** [comment]
Perfect
