### ISSUE TITLE
調整時間

### ISSUE THREAD

**Issue by PascalTang** [lipangit/JiaoZiVideoPlayer#1856]
請問繼承了JZVideoPlayer之後

我要怎麼讓影片直接跳到我想播放的時間？

**Comment by lipangit** [comment]
建议继承JZVideoPlayerStandard，继承JZVideoPlayer没有ui.

跳转播放时间可以JZMediaManager.instance().mediaPlayer.seekTo();,也可以模拟点击进度条

**Comment by lipangit** [comment]
复写setProgressAndText函数
