### ISSUE TITLE
How can i play device local video.

### ISSUE THREAD

**Issue by shiv71** [lipangit/JiaoZiVideoPlayer#1858]
How can i play device local video.

**Comment by lipangit** [comment]
see Demo，
![image](https://user-images.githubusercontent.com/2038071/40129012-bce24040-5965-11e8-94b0-79906a846807.png)

**Comment by shiv71** [comment]
It's not working. My requirement is i have video URI and i want to play video form uri. How can i do this

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/40164698-d561843c-59ec-11e8-8b90-1887b2724ac5.png)

this function url is object,  you can put uri

**Comment by shiv71** [comment]
I am talking about android Uri Object not string url.
When i select video from gallery or record video from camera it return android Uri object so how can i play video from android Uri.

**Comment by shiv71** [comment]
LinkedHashMap map = new LinkedHashMap();
                    map.put("URL_KEY_DEFAULT", uri);
                    Object[] dataSourceObjects = new Object[1];
                    dataSourceObjects[0] = map;

              mJzVideoPlayerStandard.setUp(dataSourceObjects,0
                            , JZVideoPlayer.SCREEN_WINDOW_NORMAL, "");

**Comment by lipangit** [comment]
use the uri in android.media.MediaPlayer check if play

**Comment by shiv71** [comment]
I have done this thank for reply.
