### ISSUE TITLE
部分机型播放视频，隔几秒页面卡顿一下

### ISSUE THREAD

**Issue by ChenJunXu** [lipangit/JiaoZiVideoPlayer#1859]
你好，部分机型播放视频，隔几秒页面卡顿一下。使用的是 m3u8 格式的链接，底层使用 ijkplayer。

用户反馈卡顿的机型有：KIW-AL10、X6D。我通过测试平台，也发现会卡顿。

**Comment by ChenJunXu** [comment]
mp4 格式的也会有此问题

**Comment by lipangit** [comment]
卡顿问题要问ijkplayer播放器引擎了，这个问题超出老臣解决范围

**Comment by longkehuawei** [comment]
这个怎么解决呀

**Comment by lipangit** [comment]
换一个播放内核



---原始邮件---
发件人: "longkehuawei"<notifications@github.com&gt;
发送时间: 2020年3月25日(周三) 下午3:25
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 部分机型播放视频，隔几秒页面卡顿一下 (#1859)




 
这个怎么解决呀
