### ISSUE TITLE
自定义播放开始时间 结束时间

### ISSUE THREAD

**Issue by CatyVon** [lipangit/JiaoZiVideoPlayer#1860]
作者大大  我在项目里的视频播放都使用了你的这个播放组件  目前有一个需求是要根据用户的某些操作  播放视频的时候  可以自定义播放起始时间和结束时间  也就是只播放视频的一部分  而不是全部播放  咨询一下  是否有提供这种方法

**Comment by lipangit** [comment]
seekToInAdvance  这个变量控制开始的播放时间  复写setProgressAndText函数取得当前播放时间，是设置播放时间和进度条的，可以结束视频。
