### ISSUE TITLE
m3u8能边播放边缓存吗？或暂停等它一直缓存？

### ISSUE THREAD

**Issue by FynnJason** [lipangit/JiaoZiVideoPlayer#1861]
这个需求我相信困扰了千千万万的苦逼程序员。。。

**Comment by lipangit** [comment]
有遇到的吗，大家来看看

**Comment by YumikoAzu** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1097

**Comment by YumikoAzu** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1097

**Comment by lipangit** [comment]
@FynnJason 这个做出来吗 有后文吗
