### ISSUE TITLE
在非全屏模式下点击全屏按钮进入全屏模式如何能直接固定为横屏？

### ISSUE THREAD

**Issue by ootypoo** [lipangit/JiaoZiVideoPlayer#1862]
在非全屏模式下点击全屏按钮进入全屏模式如何能直接固定为横屏？不需要通过重力感应来切换横屏状态！

**Comment by jijinchao2014** [comment]
加上下面的代码就可以了：
JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;

**Comment by lipangit** [comment]
么么哒
