### ISSUE TITLE
在非全屏模式下点击全屏按钮进入全屏模式如何能直接固定为横屏？并且需要通过重力感应来切换横屏状态！

### ISSUE THREAD

**Issue by zhiyongshuangquan** [lipangit/JiaoZiVideoPlayer#1865]

**Comment by zhiyongshuangquan** [comment]
1：目前我运行你的demo，就是可以全屏和重力感应切换，但是有个竖屏效果:
2：设置属性后JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
重力感应无效
3：暂停播放时重力无效

**Comment by lipangit** [comment]
对

**Comment by lipangit** [comment]
先进入横屏的全屏，然后进入全屏之后再设置JZVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT，试试

**Comment by zhiyongshuangquan** [comment]
这样的话我需要监听到现在屏幕是横屏还是竖屏状态？

**Comment by ootypoo** [comment]
我表达有误，我就是要重力感应失效，点击全屏就直接横屏，不受重力感应的影响！

**Comment by lipangit** [comment]
demo 有例子 @ootypoo

**Comment by lipangit** [comment]
么么哒

**Comment by lipangit** [comment]
有道理，我给他记下来

**Comment by 455361051** [comment]
请问，在4g网络环境下，会出现黑屏，要怎么处理？
