### ISSUE TITLE
设置了控件tag,全屏显示获取为null,非全屏正常，点击事件两种状态都是正常的

### ISSUE THREAD

**Issue by yxyaxng** [lipangit/JiaoZiVideoPlayer#1869]
![tim 20180517163051_](https://user-images.githubusercontent.com/24906252/40166086-45f2ceb0-59f0-11e8-8eb1-339bbbf06a20.png)

**Comment by lipangit** [comment]
全屏和非全屏是两个实例，参考setUp的最后一个变量能在全屏和非全屏之间传递

**Comment by yxyaxng** [comment]
嗯，还有个问题，既然两个实例，全屏跟非全屏我有做控件的隐藏显示，请问怎么去同步呀

**Comment by lipangit** [comment]
控件的管理 完全和播放状态有关系，比如播放中什么样，暂停什么样，准备中什么样等。

**Comment by lipangit** [comment]
如果全屏和非全屏不一样的话，取得播放状态之后再区分全屏与否

**Comment by yxyaxng** [comment]
现在的问题是这样的，我在非全屏状态，我这设置这个控件状态是隐藏的，但是在全屏状态下，这个控件又显示出来了，既然是两个实例，怎么去获取全屏状态下的这个控件
![tim 20180519094851](https://user-images.githubusercontent.com/24906252/40263774-dd839e6c-5b49-11e8-9711-a27854710dee.png)

**Comment by lipangit** [comment]
复写setUp中函数修改他们的属性

**Comment by yxyaxng** [comment]
已解决，谢谢作者大大

**Comment by zhupengxiang** [comment]
什么意思  求解  这个setup怎么个用法
