### ISSUE TITLE
不完整url

### ISSUE THREAD

**Issue by mylhyl** [lipangit/JiaoZiVideoPlayer#1872]
丢入一个不完整的url后，一直在菊花等待，内部已经抛出异常，应该在catch中更新UI为播放错误。
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:44)
W/System.err:     at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:146)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
W/System.err:     at android.os.Looper.loop(Looper.java:207)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: Caused by: java.io.IOException: setDataSource failed.
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1121)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1095)
W/System.err: 	... 6 more
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by lipangit** [comment]
我试试

**Comment by lipangit** [comment]
随便一个url吗

**Comment by mylhyl** [comment]
我试的是没有http://
例如：/zentao/project-task-401.mp4
