### ISSUE TITLE
监听播放完成和进度  在全屏的时候 没有用了。

### ISSUE THREAD

**Issue by dxclass** [lipangit/JiaoZiVideoPlayer#1875]
具体的是 我在监听进度 几秒的时候弹出 dialog  小屏可以，全屏就没有效果了。
是dialog 的问题吗，因为dialog 依附在Activity  还是怎么做，
请大神给个意见

**Comment by dxclass** [comment]
知道问题所在了，setProgressAndText 这个方法是在走 没有问题
但是我监听这个方法:

    @Override
    public void setProgressAndText(int progress, long position, long duration) {
        super.setProgressAndText(progress, position, duration);
        Log.e("我在走——", progress+"");
        if(progressListener!=null){
            progressListener.progress(progress);
            progressListener.position(position);
            progressListener.duration(duration);
        }
    }

    public interface ProgressListener {
        void progress(int progress);

        void position(long position);

        void duration(long duration);
    }

    //自定义点击事件和长按事件
    private ProgressListener progressListener;

    public void setProgressListener(ProgressListener progressListener) {
        this.progressListener = progressListener;
    }

在全屏的时候没有用,这是为啥啊

**Comment by lipangit** [comment]
全屏和非全屏是两个实例，不要用setListener这种，继承JZvideoPlayerStandard，复写函数去做

**Comment by lipangit** [comment]
@zhangzzqq 兄弟 还有问题吗   复写startWindowTiny 或者复写setUp在里面 判断全屏
