### ISSUE TITLE
关于小窗播放的问题

### ISSUE THREAD

**Issue by dongfangmingjia** [lipangit/JiaoZiVideoPlayer#1876]
我在一个列表中加入播放器，列表快速滑动的过程中会在屏幕右下角出现一个小的播放窗口，怎么能在列表滑动过程中不出现播放窗口

**Comment by lipangit** [comment]
参考demo，有好几种列表

**Comment by dongfangmingjia** [comment]
我是想关闭小窗播放，有什么方法吗？

**Comment by lipangit** [comment]
调用backPress()函数，或者点击小窗左上角的X按钮

**Comment by dongfangmingjia** [comment]
我的意思是，在列表中用这个播放器，快速滑动的过程中会出现已经滑出屏幕的item会出现小窗播放，我不想要这个效果，应该怎么做

**Comment by yilylong** [comment]
是的，为什么不设置一个一键开启关闭的方法，需要给listview 设置onscrollview 然后调用JZVideoPlayer.onScrollReleaseAllVideos 方法呢

**Comment by lipangit** [comment]
@dongfangmingjia demo中有两个listView，一个是有小窗的，一个是没小窗的
