### ISSUE TITLE
JZMediaSystem.start IllegalStateException

### ISSUE THREAD

**Issue by PascalTang** [lipangit/JiaoZiVideoPlayer#1877]
第一個
Fatal Exception: java.lang.IllegalStateException
cn.jzvd.JZMediaSystem.start

android.media.MediaPlayer.seekTo (MediaPlayer.java)
arrow_right
cn.jzvd.JZMediaSystem.start (Unknown Source)
cn.jzvd.JZMediaManager.instance (Unknown Source)
cn.jzvd.JZVideoPlayer.onStopTrackingTouch (Unknown Source)
com.ilulutv.lulu.longfilm.player.CustomVideoPlayerStandard.onStopTrackingTouch (Unknown Source)
android.widget.SeekBar.onStopTrackingTouch (SeekBar.java:121)
android.widget.AbsSeekBar.onTouchEvent (AbsSeekBar.java:604)
android.view.View.dispatchTouchEvent (View.java:9323)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2557)
android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2255)
com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent (PhoneWindow.java:2403)
com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1737)
android.app.Activity.dispatchTouchEvent (Activity.java:2834)
android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (Unknown Source)
com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent (PhoneWindow.java:2364)
android.view.View.dispatchPointerEvent (View.java:9543)
android.view.ViewRootImpl$ViewPostImeInputStage.qiku_processPointerEvent (ViewRootImpl.java:4267)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4120)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3663)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3716)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3682)
android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:3808)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3690)
android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:3865)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3663)
android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3716)
android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3682)
android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3690)
android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3663)
android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:5973)
android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:5947)
android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:5908)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:6076)
android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:323)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5518)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:755)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:645)

第二個
Fatal Exception: java.lang.IllegalStateException 
cn.jzvd.JZMediaSystem.pause

android.media.MediaPlayer._pause (MediaPlayer.java)
android.media.MediaPlayer.pause (MediaPlayer.java:1249)
arrow_right
cn.jzvd.JZMediaSystem.pause (Unknown Source)
cn.jzvd.JZMediaManager.pause (Unknown Source)
cn.jzvd.JZVideoPlayer.onClick (Unknown Source)
com.ilulutv.lulu.longfilm.player.CustomVideoPlayerStandard.onClick (Unknown Source)
android.view.View.performClick (View.java:5689)
android.view.View$PerformClick.run (View.java:22554)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6285)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:939)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:829)

麻煩協助～～

**Comment by lipangit** [comment]
是操作MediaPlayer的时候报错，很有可能MediaPlayer已经被release了。

断点MediaPlayer的release，看看是不是在不应该被调用的时候调用了

**Comment by PascalTang** [comment]
除了onPause以外
我在切換影片時
會先        
JZVideoPlayer.releaseAllVideos();
再
mVideoplayer.setUp(videoId.toString()
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, objects);
這樣行為會有問題嗎？

**Comment by PascalTang** [comment]
等於是我切換影片 JZVideoPlayer.releaseAllVideos(); -> mVideoplayer.setUp(videoId.toString()
                , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, objects); ->

**Comment by lipangit** [comment]
你的三行代码的顺序没问题，IllegalStateException导致这个问题是MediaPlayer的release在不应该被调用的时候调用了，你应该断点JZMediaManager的releaseMediaPlayer函数
