### ISSUE TITLE
点击开始播放，偶然不会走JZUserAction.ON_CLICK_START_ICON

### ISSUE THREAD

**Issue by chsimon99** [lipangit/JiaoZiVideoPlayer#1881]
点击开始按钮的时候，有的时候不会走JZUserAction.ON_CLICK_START_ICON这个事件，我看源码，在JZVideoPlayer的449行，onEvent(JZUserAction.ON_CLICK_START_ICON);在startVideo();之后，是不是调整一下位置就行了？

**Comment by lipangit** [comment]
偶然不会走是什么意思，demo有这问题吗，可能有点奇怪

**Comment by chsimon99** [comment]
我昨天仔细看了下源码，其实在点击开始按钮的layout里面，你在最外层有一个image view，这样我点击开始图标外的其他部位就会走这个imageview的点击事件，在这个点击事件中，JZVideoPlayerStandard类中268行和269行，先走的onEvent后startVideo，这样会导致走onevent时isCurrentPlay()为false，不能发送onEvent事件。这样视频开始播放了，但case JZUserActionStandard.ON_CLICK_START_THUMB:收不到事件，希望您修改一下源码。

**Comment by lipangit** [comment]
感谢你的反馈，我仔细研究一下

**Comment by lipangit** [comment]
这个部分本质上在设置currentPlay之前就调用了ON_CLICK_START_THUMB事件，导致收不到此事件。

所以说这几天我研究一下onEvent函数中的isCurrentPlay()的返回都是什么样的，再做修改。

**Comment by lipangit** [comment]
这个以前修改过了好像

**Comment by lipangit** [comment]
已经修复
