### ISSUE TITLE
续播问题

### ISSUE THREAD

**Issue by chiq0201** [lipangit/JiaoZiVideoPlayer#1887]
我想问一个问题 我用过seekToInAdvance设置了进度 然后调用哪个方法进行播放？调用startVideo()的话 进度就失效了

**Comment by lipangit** [comment]
断点一下源码，
![image](https://user-images.githubusercontent.com/2038071/40586061-744f15ba-61ee-11e8-95f4-39868a3d6e6e.png)
这里，看看是zenm怎么走的
