### ISSUE TITLE
视频高度问题

### ISSUE THREAD

**Issue by hyandroid** [lipangit/JiaoZiVideoPlayer#1888]
开启全屏，然后横屏之后，返回到原来ListView，视频高度变大，出现黑边。不横屏直接返回高度是没问题的。
这个是什么原因呢。

**Comment by lipangit** [comment]
看看效果，录视频或者接几个图

**Comment by hyandroid** [comment]
[Screenrecorder-2018-05-28-12-47-16-556.zip](https://github.com/lipangit/JiaoZiVideoPlayer/files/2043643/Screenrecorder-2018-05-28-12-47-16-556.zip)
这是录频，你看下，开启全屏直接返回没问题，一旦横屏之后再返回，就会这样。

**Comment by lipangit** [comment]
你自己对宽高设置了吗，把url放demo里有这问题吗

**Comment by hyandroid** [comment]
我视频高度是根据屏幕宽度和视频比例动态计算的，然后设置的。我刚检查了下，全屏横屏的时候也调用了adapter中计算高度的代码，所以返回之后的高度就是横屏时候视频的高度。   
jzVideoPlayer.getLayoutParams().height = post.getVideoHeight() * (Utils.getScreenWidth(context) - Utils.dip2px(context, 30)) / post.getVideoWidth();

listview中出现的，recycleView中就不会有这情况，横屏不会计算高度。

**Comment by hyandroid** [comment]
因为我是必须动态计算的，不然会有少量黑边。那我其实可以处理，横屏的时候忽略掉计算代码。  就是反馈一下这个问题。

**Comment by lipangit** [comment]
黑边的处理参考demo的ActivityApiRotationVideoSize。

问题解决了就好。
