### ISSUE TITLE
小窗口问题

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1890]
当在recycleView列表中开启小窗口视频后，我退出recycleView列表界面我也想要保持小窗口的播放状态，甚至我切换到app的其它界面也需要保持小窗口的播放状态，这个怎么做？YOUTOBE app是这样的

**Comment by lipangit** [comment]
这个能做，你需要全面了解一下库是怎么运作的。切换activity和小窗不冲突
