### ISSUE TITLE
这个怎么可以支持rmvb格式的视屏

### ISSUE THREAD

**Issue by xpjone** [lipangit/JiaoZiVideoPlayer#1893]

**Comment by lipangit** [comment]
一行代码切换播放器引擎到ijkplayer

**Comment by wangcheng24** [comment]
怎么切换?代码怎么设置

**Comment by wenzheqiang** [comment]
怎么切换呢， @lipangit

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43563167-5b7dc18c-9653-11e8-8f48-0f76de528bf3.png)
