### ISSUE TITLE
全屏自定义按钮监听问题

### ISSUE THREAD

**Issue by nwx546250** [lipangit/JiaoZiVideoPlayer#1897]
1.继承JZVideoPlayerStandard 类
2.重写
public int getLayoutId()
public void init(Context context)

    @Override
    public void onClick(View v) {
        super.onClick(v);
        switch (v.getId()){
            case R.id.tv_play_next_one:
                if (onPlayClickListener !=null){
                    startButton.setVisibility(GONE);
                    onPlayClickListener.playNextOne();
                }
                break;
        }
    }

全屏的时候 onPlayClickListene为null 
小屏是不为null
这个怎么解决

**Comment by nwx546250** [comment]
解决了  重载 public void setUp(Object[] dataSourceObjects, int defaultUrlMapIndex, int screen, Object... objects)
在objects 中获取，第一个objects[0]第一个是标题，objects[n]后面的就是我们传递给全屏的参数

**Comment by lipangit** [comment]
么么哒

**Comment by zhupengxiang** [comment]
这个objects怎么用 是不是自定义里面的属性都通过它传递
