### ISSUE TITLE
Finished wiki translation

### ISSUE THREAD

**Issue by felipetorres** [lipangit/JiaoZiVideoPlayer#1900]
Hello,

I've been finished to translating wiki to English. I don't have permission to commit in this repo, so I  forked the wiki repo [here](https://github.com/felipetorres/VideoPlayer-Wiki) and committed my work. 

I removed some really old pages, but I didn't know what to do with "Common problems" section, because it seems that all problems were already solved. So, can you update this section and merge my repo in wiki?

**Comment by lipangit** [comment]
ok I will put the url in Main page of the project

**Comment by felipetorres** [comment]
No, try to merge my fork in your wiki (even with copy/paste)... Otherwise rhe _sidebar.md urls won't work.

**Comment by lipangit** [comment]
invite you to collaborators

**Comment by felipetorres** [comment]
Thank you very much! Can you review the translated wiki in my repo (mainly the pages removed)? I'll merge them when you agree. ;)

**Comment by lipangit** [comment]
WIki you can merge in anytime, Do not need my agree, but the code need my check.

**Comment by felipetorres** [comment]
Done. \o/
