### ISSUE TITLE
请问,如何获取视频加载状态(获取是否加载完成了)

### ISSUE THREAD

**Issue by lidapeng3818** [lipangit/JiaoZiVideoPlayer#1903]
如题现在想获取视频是否加载完成的状况,因为现在出现视频在加载的时候点击下面列表切换播放连接会出现ANR.下面是点击调用的方法.   Glide.with(this).load(URLIV).diskCacheStrategy(DiskCacheStrategy.RESULT)
                .crossFade().centerCrop().into(jzVideoPlayerStandard.thumbImageView);
        jzVideoPlayerStandard.setUp(URLvideo, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL);
        //开始播放
        jzVideoPlayerStandard.startVideo();
在加载的时候点击几次就出ANR,而且每次进来这个页面onCreate里面调用这个方法会出现明显的黑屏一会.我写了 mHandlerplay.postDelayed();来解决这个问题不知道还有没有更加完美的解决办法.

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写onPrepared函数，取得加载完成状态
