### ISSUE TITLE
[Question] - Show Controllers

### ISSUE THREAD

**Issue by TurKurT656** [lipangit/JiaoZiVideoPlayer#1904]
Hi and thnx for this great lib
When i play an audio file, the controllers (seekbar and play/pause) not showing. how can i force enable them

**Comment by lipangit** [comment]
upgrade the lib to 6.2.10

**Comment by TurKurT656** [comment]
im on 6.2.10

**Comment by lipangit** [comment]
I will check it

**Comment by TurKurT656** [comment]
i found the problem, if the audio is mpga format, it doesnt know when music starts. but in mp3 format we dont have this problem.
and can we persist a thumbImage on audio format? because its ugly when playing audio

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/40819935-2e153b6a-6590-11e8-823e-37a2eac8d15c.png)


you can add 'mp3' string in your mpga url

**Comment by TurKurT656** [comment]
Thnx, and what about persistance thumb image on audio files?

**Comment by lipangit** [comment]
see smallChangeUiActivity in demo,  invisible thumb in every stat
