### ISSUE TITLE
SeekTo()方法定位到指定的毫秒数播放，会跳帧的问题。

### ISSUE THREAD

**Issue by payneHwang** [lipangit/JiaoZiVideoPlayer#1906]
MediaManager.instance().mediaPlayer.seekTo(startMilles);定位到startMilles指定毫秒数播放时，比如是2000毫秒之后播放，播放器会跳转到0，然后在进行播放；无法准确定位播放，求解答（项目需要准确进行定位播放，谢谢了）

**Comment by lipangit** [comment]
这个和视频的关键帧有关系，听说他只会跳转到关键帧

**Comment by yalarc** [comment]
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
关于seekto不准的问题，ijkMediaPlayer可以用上边这个配置处理一下，实测可用！！！

**Comment by lipangit** [comment]
very good 兄弟
