### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by YanXiaosa5** [lipangit/JiaoZiVideoPlayer#1910]
点击视频,一直加载转圈圈,无法播放

**Comment by max8888888** [comment]
我的也是，但是log上只有这几行信息：
I/JiaoZiVideoPlayer: onClick start [962202857] 
D/JiaoZiVideoPlayer: startVideo [962202857] 
D/JiaoZiVideoPlayer: addTextureView [962202857] 
W/TextureView: A TextureView or a subclass can only be used with hardware acceleration enabled.
I/JiaoZiVideoPlayer: onStatePreparing  [962202857]

**Comment by max8888888** [comment]
加上硬件加速的权限之后，就能播放了

**Comment by lipangit** [comment]
嗯，硬件急速必须开启，否则textureview不工作

**Comment by max8888888** [comment]
了解！

**Comment by lipangit** [comment]
么么哒 小可爱

**Comment by fff4** [comment]
搞了半天 才发现是这个问题
