### ISSUE TITLE
播放一直转圈，无法播放

### ISSUE THREAD

**Issue by MiniFrog** [lipangit/JiaoZiVideoPlayer#1916]
播放本地视频文件的时候，mJzVideoPlayerStandard.setUp这个方法的第一个参数String Uri有时候需要在绝对地址前加"file://"，而不是像demo ActivityApi.java line82 里面一样直接使用地址 Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"

也就是说要把参数改成“file://” + Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"才能正常播放，否则一只转圈。

我的target API为26

**Comment by lipangit** [comment]
好的，感谢你的提醒
