### ISSUE TITLE
你好，请教下，为什么我的rtsp流不能用？

### ISSUE THREAD

**Issue by wjy591416** [lipangit/JiaoZiVideoPlayer#1917]
rtsp://admin:admin@192.168.2.180:10554/udp/av0_0 vlc中是能正常播放的，但是在jz中无法播放

**Comment by lipangit** [comment]
切换播放器引擎试试，参考demo的customMediaPlayer

**Comment by wjy591416** [comment]
貌似是解码器的问题发自我的iPhone------------------ 原始邮件 ------------------发件人: Nathen  <notifications@github.com>发送时间: 2018年6月6日 16:41收件人: lipangit/JiaoZiVideoPlayer <JiaoZiVideoPlayer@noreply.github.com>抄送: wjy591416 <wujianye88@gmail.com>, Author <author@noreply.github.com>主题: 回复：[lipangit/JiaoZiVideoPlayer] 你好，请教下，为什么我的rtsp流不能用？ (#1917)切换播放器引擎试试，参考demo的customMediaPlayer

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/lipangit/JiaoZiVideoPlayer/issues/1917#issuecomment-394990610","url":"https://github.com/lipangit/JiaoZiVideoPlayer/issues/1917#issuecomment-394990610","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lipangit/JiaoZiVideoPlayer","title":"lipangit/JiaoZiVideoPlayer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lipangit/JiaoZiVideoPlayer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lipangit in #1917: 切换播放器引擎试试，参考demo的customMediaPlayer"}],"action":{"name":"View Issue","url":"https://github.com/lipangit/JiaoZiVideoPlayer/issues/1917#issuecomment-394990610"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [lipangit/JiaoZiVideoPlayer] 你好，请教下，为什么我的rtsp流不能用？ (#1917)",
"sections": [
{
"text": "",
"activityTitle": "**Nathen**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lipangit",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lipangit/JiaoZiVideoPlayer\",\n\"issueId\": 1917,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"lipangit/JiaoZiVideoPlayer\",\n\"issueId\": 1917\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lipangit/JiaoZiVideoPlayer/issues/1917#issuecomment-394990610"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341934181\n}"
}
],
"themeColor": "26292E"
}

**Comment by wjy591416** [comment]
请教，我切换成ijkplayer，ijkplayer也重新编译，支持我的rtsp流，但是一直卡在第一帧，无声音，这个需要从什么地方入手？

**Comment by lipangit** [comment]
新建个项目，单纯的用你编译的ijkplayer，试试是不是有这个问题
