### ISSUE TITLE
视频和音频切换播问题

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JiaoZiVideoPlayer#1918]
我将饺子播放器集成到我的音乐播放器项目中，我开始播视频是好的，然后我去播一首歌曲，然后再点击播放视频就不能播放了，断点显示视频是处于CURRENT_STATE_PREPARING状态，可是点击开始播按钮没反应

**Comment by StevenNick88** [comment]
我猜想是播放音频时 切换音频焦点的时候视频暂停了  但是播放状态未改变

**Comment by StevenNick88** [comment]
我知道原因了，播放音频我使用的是系统的MediaPlayer ，播放视频我使用的是JZMediaIjkplayer，在切换播放视频的时候音频的MediaPlayer在工作中， 这个时候想要播放JZMediaIjkplayer没用是吧？

**Comment by StevenNick88** [comment]
是否应该在开始播放视频的时候判断release掉系统的MediaPlayer，我该怎么修改代码合适呢？

**Comment by StevenNick88** [comment]
我刚试了视频不使用JZMediaIjkplayer，用系统的MediaPlayer也有这个问题，之前的JicaoVideoPlayer没有这个问题啊

**Comment by StevenNick88** [comment]
?

**Comment by lipangit** [comment]
一行代码设置播放器引擎是随时设置随时生效，在切换的过程中有什么问题

**Comment by lipangit** [comment]
切换播放器是时候先releaseAllvideos()

**Comment by StevenNick88** [comment]
不是一行代码设置播放器引擎有问题，你没看清我的问题，我的问题是：我将饺子播放器集成到我的音乐播放器项目中，我开始播视频是好的，然后我去播一首歌曲，然后再点击播放视频就不能播放了。

**Comment by lipangit** [comment]
这中间不是切换播放器引擎了吗

**Comment by lipangit** [comment]
qq说

**Comment by StevenNick88** [comment]
已经给你发QQ了

**Comment by lipangit** [comment]
哪个是你，直接把issue链接发过来

**Comment by lipangit** [comment]
怎么样了兄弟，后来咱们讨论这个问题了吗
