### ISSUE TITLE
我把这个视频放在平板上，平板接的是网线也提示用的是移动流量，能把这个去掉吗？

### ISSUE THREAD

**Issue by Ronrey100** [lipangit/JiaoZiVideoPlayer#1919]
网络这块的提示，能否交由业务层去控制，不需要去修改源码？我看针对这个问题，提了很多Bug，但是在实际使用还会有些情况没法考虑到，比如有线网络的平板。所以，这个功能可以尽量由业务层去做吧

**Comment by lipangit** [comment]
可以 继承jzvideolplayerStandard，复写showDialog函数，屏蔽父类的逻辑即可

**Comment by Ronrey100** [comment]
OK，谢谢

**Comment by lipangit** [comment]
么么哒
