### ISSUE TITLE
Mov格式播放不了

### ISSUE THREAD

**Issue by kofkoy123** [lipangit/JiaoZiVideoPlayer#1920]
该播放器不支持mov格式吗??

**Comment by lipangit** [comment]
支持的视频格式取决于播放器引擎，android.media.MediaPlayer不支持mov格式，你可以切换到ijkplayer支持

**Comment by o199666** [comment]
怎么切换？

**Comment by longkehuawei** [comment]
怎么切换呀

**Comment by lipangit** [comment]
setup中传参数



---原始邮件---
发件人: "longkehuawei"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 中午11:24
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] Mov格式播放不了 (#1920)




 
怎么切换呀
