### ISSUE TITLE
播放音频的直播流

### ISSUE THREAD

**Issue by wqjuser** [lipangit/JiaoZiVideoPlayer#1921]
播放音频直播流的时候因为没有画面，现在显示的是蓝屏，可不可以添加一个方法设置当前播放为音频流网址的时候加一个自定义界面

**Comment by lipangit** [comment]
可以，把缩略图显示出来，参考demo的smallchangeActivity

**Comment by LuXGang** [comment]
播放音频直播流的时候，声音有，但是一直有个加载圈

**Comment by lipangit** [comment]
url中要带有mp3字样

**Comment by lipangit** [comment]
哎呦，这个不知道，如果路径上不包含mp3字符串的话

**Comment by reverseAndroid** [comment]
@lipangit 现在的问题是在本地路径上添加的MP3直接播不了。。。。求大佬解答

**Comment by lipangit** [comment]
什么现象，直接用android.media.MediaPlayer能否播放路径上的MP3

**Comment by reverseAndroid** [comment]
@lipangit 如果播放的音频地址是手机本地地址的话，只有MP3格式是正常的，其他的格式虽然能播放出声音，但是界面确实一直显示加载圈，无法进行快进快退暂停等操作，只能退出这个页面，并且退出后重新进入播放，依旧如此。

**Comment by reverseAndroid** [comment]
@lipangit 我觉得你没明白我的意思，我现在是播放服务器的URL，我加上“MP3”字样，可以播放，但是现在是我下载到本地，播放本地的音频文件，这个时候是地址，并不是URL，这时候我加上“MP3”字样并没有用，我想问的是播放本地的音频文件，怎么才能正常播放，不让他的加载框一直转。

**Comment by lipangit** [comment]
这个时候加载框一直转的时候有声音吗

**Comment by reverseAndroid** [comment]
@lipangit 有声音，很正常，就是不能暂停，快进快退，只能按返回键退出，整个页面就是个加载框，声音一直正常播

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/44459866-ad915980-a63d-11e8-80c1-0fb2d6e2b56e.png)


这里判断了路径带有mp3字样之后才会进入播放状态，否则一直是准备的状态（加载框一直转）

**Comment by reverseAndroid** [comment]
@lipangit 你说的播放状态是什么？可以正常听到音乐，但是无法进行快进快退这样叫不叫播放状态，另外请问手机本地路径的音频文件，怎么在加上“MP3”字样下正常播放。

**Comment by lipangit** [comment]
这个播放状态是准备中状态，
![image](https://user-images.githubusercontent.com/2038071/44502800-ccd3c980-a6c5-11e8-85cd-52ffe894cd28.png)
