### ISSUE TITLE
怎么实现 缓冲时候加载进度条啊？

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1922]

**Comment by lipangit** [comment]
你说的是播放的时候拖动进度条时的加载loading标志吧，参考旧版本

**Comment by guoyongxing** [comment]
旧版本  不是在OnInfo方法里面么？  可是 用最新版的  发现  不走OnInfo了啊？

**Comment by lipangit** [comment]
你只关注开始seekTo和seekTo完成，这两个点，分别显示和隐藏loading进度条

**Comment by qiaoguoqiang** [comment]
为什么播放的时候我点击进度条的某一个点，视频不会继续播放，我看到是在缓存的，但是视频就是不播放，出现的概率很大

**Comment by lipangit** [comment]
缓存可能有偏差，  @qiaoguoqiang 兄弟 有什么新发现吗
