### ISSUE TITLE
在竖屏的情况下 能重力感应么？我想竖屏半屏播放 重力感应横屏 之后在切回竖屏？

### ISSUE THREAD

**Issue by guoyongxing** [lipangit/JiaoZiVideoPlayer#1924]

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/41139733-1f7c36ee-6b1c-11e8-804f-f1492b4cc5d4.png)

可以修改成这类的重力感应类型，半瓶播放时什么意思，是自己的代码能控制吗
