### ISSUE TITLE
从ActivityDirectPlay点击fullscreen按钮直接进入全屏播放，怎么实现播放完之后继续停留在全屏播放界面呀

### ISSUE THREAD

**Issue by AndyYw** [lipangit/JiaoZiVideoPlayer#1925]

**Comment by lipangit** [comment]
demo有例子，smallChangeApiActivity里面有

**Comment by AndyYw** [comment]
大佬,我想随便点击一个按钮是全屏效果，然后全屏播放完之后，停留在全屏播放页面,意思是 JZVideoPlayerStandard.startFullscreen和JZVideoPlayerStandardAutoCompleteAfterFullscreen结合在一起怎么弄啊

**Comment by AndyYw** [comment]
大佬,我想随便点击一个按钮是全屏效果，然后全屏播放完之后，停留在全屏播放页面,意思是 JZVideoPlayerStandard.startFullscreen和JZVideoPlayerStandardAutoCompleteAfterFullscreen结合在一起怎么弄啊@lipangit
