### ISSUE TITLE
When error occurred , I want to play another URL. How can i do this ?  

### ISSUE THREAD

**Issue by mdaslamHossin** [lipangit/JiaoZiVideoPlayer#1928]
I can.t get any listener for update the playing URL after the error occurred is there any suggestion?

**Comment by lipangit** [comment]
It is the same with change clarity, see apiActivity,

**Comment by mdaslamHossin** [comment]
Now I am doing this 
@Override
    public boolean onError(IMediaPlayer iMediaPlayer, final int what, final int extra) {

        if (currentDataSource != null && currentDataSource.toString().toLowerCase().contains("https") && !isRetried) {
            isRetried = true;
            final Uri uri = Uri.parse(currentDataSource.toString());
            if (uri.getScheme().equalsIgnoreCase("https")) {
                currentDataSource = currentDataSource.toString().replaceFirst("https", "http");
                url = currentDataSource.toString();
            }
            JZMediaManager.instance().mainThreadHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    if (JZVideoPlayerManager.getCurrentJzvd() != null && url != null) {
                        try {
                            JZVideoPlayer.releaseAllVideos();
                            JZVideoPlayerManager.getCurrentJzvd().setUp(url
                                    , JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, video.getTitle() + "");
                            JZVideoPlayer.SAVE_PROGRESS = false;
                            JZVideoPlayerManager.getCurrentJzvd().startVideo();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }
                }
            },1000);
        } else {
            JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
                @Override
                public void run() {
                    if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                        JZVideoPlayerManager.getCurrentJzvd().onError(what, extra);
                    }
                }
            });
        }
        return true;
    }

**Comment by lipangit** [comment]
ok

**Comment by mdaslamHossin** [comment]
Is there any problem with performance?

**Comment by lipangit** [comment]
no problem with performance
