### ISSUE TITLE
使用默认的播放方式大概在3分钟的时候会播放失败

### ISSUE THREAD

**Issue by zhoux122333** [lipangit/JiaoZiVideoPlayer#1930]
视频播放过程中不点击它，让它自己播放，大概在3分钟左右的时候会变成“加载失败，点击重试”的样子，视频源没有问题，貌似是6.2.10才有的问题，我换成6.2.9没有这个问题

**Comment by zhoux122333** [comment]
好吧，6.2.9也有这种问题，测试机红米手机，安卓7.0，但是在8.0的三星上面好像没这个问题，有点晕了

**Comment by lipangit** [comment]
新建项目，用MediaPlayer试试，这应该是播放器引擎的问题

**Comment by zhoux122333** [comment]
嗯，谢谢，我换成ijk就没这个问题了
