### ISSUE TITLE
如何修改JZVideoPlayerStandard.startFullscreen() 标题显示一行？

### ISSUE THREAD

**Issue by qzw631486894** [lipangit/JiaoZiVideoPlayer#1933]
JZVideoPlayerStandard.startFullscreen(this, JZVideoPlayerStandard.class, "http://oss.meiyanskin.com/video_information/20180412/hmYG8Rshf2.mp4", textView);

当textView字符串文字太多，默认的title显示的是两行，怎么将其改为一行？

**Comment by lipangit** [comment]
继承JZvideoPlaeyrStandard，在自己的布局中设置Title这个textView的属性
