### ISSUE TITLE
how to config auto play + fullcreen + loop configuration? please help me. Thank you

### ISSUE THREAD

**Issue by bachvx** [lipangit/JiaoZiVideoPlayer#1936]
how to config auto play + fullcreen + loop configuration? please help me. Thank you

**Comment by lipangit** [comment]
auto play  jzvd.startButton.performClick()  to start video
fullscreen jzvd.fullscreenButton.performClick() to fullscreen
loop 
![image](https://user-images.githubusercontent.com/2038071/42033417-63317810-7b0f-11e8-9e7b-60aa9f713015.png)

**Comment by deryfath** [comment]
When loop change to true, just one video that loop not entire video on map variable,  how to auto play entire video inside map linkhashmap?

**Comment by lipangit** [comment]
Your need is not loop.   that is change clarity essentially

**Comment by lipangit** [comment]
see smallChangeUIActivity  in demo
