### ISSUE TITLE
封装播放器出现UI问题

### ISSUE THREAD

**Issue by MeowStone** [lipangit/JiaoZiVideoPlayer#1937]
1、封装了一个view，包含有JZVideoPlayerStandard
2、通过点击activity上的button，将封装的view添加至decorview上层，至此，播放器上看不到返回键了；
3、点击播放器上的全屏，视频移至中央，原位置会留下播放按钮，点击视频会重载

**Comment by lipangit** [comment]
返回键在全屏的时候才会显示

点击全屏按钮，进入全屏，原位置的控件应该是看不见的，看见了 那还叫全屏吗

**Comment by MeowStone** [comment]
@lipangit 我把videoview放进framelayout，现象：
1、全屏没有返回键；
2、全屏出现两个播放按钮，原先位置一个和切换成全屏挪到中央一个；
3、右下角的 fullscreenbtn 不显示了，设置了 View.visible也看不到

**Comment by lipangit** [comment]
兄弟 哪个videoView，是安卓提供的库吗
