### ISSUE TITLE
设置夜间模式点击全屏，全屏闪了 退到正常状态，无法实现夜间全屏。

### ISSUE THREAD

**Issue by easyandroid** [lipangit/JiaoZiVideoPlayer#1938]
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);

**Comment by lipangit** [comment]
log是什么

**Comment by easyandroid** [comment]
6-13 16:09:45.826 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: ThreadedRenderer.create() translucent=false
06-13 16:09:45.828 21450-21450/cn.jzvd.demo D/InputTransport: Input channel constructed: fd=78
06-13 16:09:45.829 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: setView = DecorView@105739f[ActivityApi] touchMode=true
06-13 16:09:45.832 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: dispatchAttachedToWindow
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: message received msg=6, ext1=0, ext2=0
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: unrecognized message: (6, 0, 0)
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: callback application
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: back from callback
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: message received msg=200, ext1=702, ext2=0
06-13 16:09:45.846 21450-21485/cn.jzvd.demo W/MediaPlayer: info/warning (702, 0)
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: callback application
06-13 16:09:45.846 21450-21485/cn.jzvd.demo V/MediaPlayer: back from callback
06-13 16:09:45.846 21450-21466/cn.jzvd.demo V/MediaPlayer-JNI: getCurrentPosition: 11167 (msec)
06-13 16:09:45.846 21450-21466/cn.jzvd.demo V/MediaPlayer-JNI: getCurrentPosition: 11167 (msec)
06-13 16:09:45.857 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1920,1080] result=0x27 surface={isValid=true -922718208} surfaceGenerationChanged=true
06-13 16:09:45.859 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: mHardwareRenderer.initialize() mSurface={isValid=true -922718208} hwInitialized=true
06-13 16:09:45.860 21450-21467/cn.jzvd.demo D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1920x1080]-format:1
06-13 16:09:45.864 21450-21450/cn.jzvd.demo D/ScrollView:  onsize change changed 
06-13 16:09:45.866 21450-21450/cn.jzvd.demo V/MediaPlayer-JNI: getCurrentPosition: 11188 (msec)
06-13 16:09:45.866 21450-21450/cn.jzvd.demo V/MediaPlayer: getDuration_l
06-13 16:09:45.867 21450-21450/cn.jzvd.demo V/MediaPlayer-JNI: getDuration: 60094 (msec)
06-13 16:09:45.867 21450-21450/cn.jzvd.demo E/ViewRootImpl: sendUserActionEvent() mView == null
06-13 16:09:45.890 21450-21450/cn.jzvd.demo D/JiaoZiVideoPlayer: onInfo what - 702 extra - 0
06-13 16:09:45.890 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: MSG_RESIZED_REPORT: ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=2
06-13 16:09:45.890 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: MSG_WINDOW_FOCUS_CHANGED 1
06-13 16:09:45.890 21450-21450/cn.jzvd.demo D/ViewRootImpl@4a8393e[ActivityApi]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -922718208}
06-13 16:09:45.891 21450-21450/cn.jzvd.demo V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@2ce6de4 nm : cn.jzvd.demo ic=null
06-13 16:09:45.891 21450-21450/cn.jzvd.demo I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus    
在demo里面 ActivityMain 设置AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES); 点击API 按钮播放视频然后横屏。

**Comment by easyandroid** [comment]
已经解决，Activity 配置android:configChanges="orientation|screenSize|keyboardHidden|uiMode" 设置AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);  不会退了 。

**Comment by lipangit** [comment]
么么哒
