### ISSUE TITLE
切换播放源的问题

### ISSUE THREAD

**Issue by GonySue** [lipangit/JiaoZiVideoPlayer#1943]
按照qiuckStart接入，setup设置一个播放源，然后重新setup设置另一个播放源过后，原视频会弹出视频播放小窗显示在右下角，请问怎么取消呢？

**Comment by GonySue** [comment]
我就是想切换播放源之后不弹出小窗，但是没找到相关方法

**Comment by GonySue** [comment]
很粗暴的调用了一下backpress方法解决了，但是不知道会不会有什么影响

**Comment by lipangit** [comment]
切换视频源参考切换清晰度，小窗不应该出现的

**Comment by superAndroidMan** [comment]
我也出现了，好像是当前播放的dataSourceObjects跟setup的dataSourceObjects不一致才会出现小窗的？

**Comment by lipangit** [comment]
@superAndroidMan demo里有小窗的列表也有不出小窗的列表，配置不一样

**Comment by github2013j** [comment]
@lipangit   1、的确会出现这种情况，我的应用场景如图：只有一个播放器，下方有一个列表（列表数据会根据筛选结果改变，支持上拉刷新，下拉加载）。我的初始化代码是
 ```
 jzVideoPlayerStandard.setUp(mList.get(0).getVedioUrl(),
                        JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL,
                        "");
```
当我点击下方列表的时候重新setup，切换播放器的url，这个时候会出现小窗，目前我的解决方式是屏蔽源码中类JZVideoPlayer中的setup方法中的逻辑：startWindowTiny，见截图。想请教下这种处理方式是否妥当？
2、针对于上述应用场景，鉴于列表数据不固定，当我点击下方列表的时候切换播放器的url，重新setup，请教下是否还有其他较好的处理方式？感谢大佬
![default](https://user-images.githubusercontent.com/6291941/43830693-80ec0876-9b34-11e8-840e-10124e308211.jpg)
![default](https://user-images.githubusercontent.com/6291941/43830696-81ef9260-9b34-11e8-83d8-303d7aea28bf.jpg)

**Comment by lipangit** [comment]
没研究过这个功能，能解决就好，需求是无限的，咱们提供个通用的东西就很满足了，实现全部功能不现实。

**Comment by AndroidJohnsonWang** [comment]
遇到同样问题，切换播放URL，会自动弹出window

**Comment by lipangit** [comment]
参考demo，是不是有的设置漏掉了,少写了几行代码 @AndroidJohnsonWang

**Comment by lipangit** [comment]
切换视频源的本质和切换清晰度是一样，参考在demo中ApiActivity

**Comment by lipangit** [comment]
不要调用setUp

**Comment by github2013j** [comment]
@AndroidJohnsonWang   在我上面的应用场景下，用的方法也是多次setup，的确会弹出window，所以屏蔽了源码中的逻辑
