### ISSUE TITLE
6.0版本(包括6.0)的手机长视频无法完整播放,请教一下是什么原因.

### ISSUE THREAD

**Issue by github-yyy** [lipangit/JiaoZiVideoPlayer#1946]
播2-3分钟的视频都没有问题,但是播放10分钟的视频,在播放到3分钟左右的时候,就会置为播放完成状态.
我观察过,长视频,缓冲条不会往前走,或者走几次就不会走了,然后进度播放到缓冲条末端的时候视频就会变成播放完成的状态.
不是视频的原因,多个视频都测试过了.
debug,走了onError方法,错误码 1 1004

请问您这个问题有解决方法么?

**Comment by lipangit** [comment]
这是播放器引擎的问题，超出项目解决范围
