### ISSUE TITLE
https问题

### ISSUE THREAD

**Issue by AndyYw** [lipangit/JiaoZiVideoPlayer#1947]
06-21 11:29:35.198 32496-32563/cn.jzvd.demo I/MediaPlayer: setDataSource(https://stwebapp001sh.blob.core.chinacloudapi.cn/publishedvideo/67970ed1-e5fd-4b73-b80e-00546b76666d.mp4)
06-21 11:29:35.199 496-1771/? I/MediaPlayerService: setDataSource(https://stwebapp001sh.blob.core.chinacloudapi.cn/publishedvideo/67970ed1-e5fd-4b73-b80e-00546b76666d.mp4)
06-21 11:29:35.201 32496-32563/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
06-21 11:29:35.671 496-32724/? I/FFMPEGExtractor: FFMPEG doesn't support https and rtsp protocol.
06-21 11:29:35.678 496-32724/? W/MediaExtractor: creating media extractor in calling process
06-21 11:29:35.678 496-32724/? I/MediaExtractor: extractor created in uid: 1013 (media)

**Comment by AndyYw** [comment]
大佬，这个很急呀。马上要上线了,用这个确不支持Https.

**Comment by AndyYw** [comment]
看了之前的issue忽略证书也播放不了呀

**Comment by lipangit** [comment]
你用的是ijkplayer播放器引擎吧，这个要重新编译ijkplayer的

**Comment by AndyYw** [comment]
我用的mediaplayer,这个支持么。支持https必须要用ijkplayer么？
