### ISSUE TITLE
https视频 一开始播放不了 等5 6分钟才能播放

### ISSUE THREAD

**Issue by yang0range** [lipangit/JiaoZiVideoPlayer#1948]
如题 https的视频 一开始一直转圈 不能播放 等过了 5 6分钟才能播放 
https://1253934854.vod2.myqcloud.com/399e1aebvodgzp1253934854/dff9b44d7447398156764010817/M6Y0tIFiAU0A.mp4
怎么回事？

**Comment by lipangit** [comment]
这是播放器引擎的问题，超出老臣解决范围
