### ISSUE TITLE
使用移动网络不能取消"您当前正在使用移动网络，继续播放将消耗流量"提醒

### ISSUE THREAD

**Issue by M-Dragon** [lipangit/JiaoZiVideoPlayer#1951]
不使用showWifiDialo弹窗，移动网络状态，第一次播放视频会有弹窗提醒"您当前正在使用移动网络，继续播放将消耗流量"，点击继续播放，此后播放任何视频不再有提示，请问如何把第一次的提醒也去掉呢？谢谢！

**Comment by lipangit** [comment]
复写showWifiDialog函数，屏蔽父类逻辑即可

**Comment by M-Dragon** [comment]
非常感谢，我是直接使用的播放器类没有继承，JCVideoPlayer.WIFI_TIP_DIALOG_SHOWED = true;也获得了同样的效果。

**Comment by lipangit** [comment]
对对，这个代码的意思已经显示过了不再重复提示

**Comment by 18702953620** [comment]
仅复写showWifiDialog，会导致流量下 无法播放
 if (!jzDataSource.getCurrentUrl().toString().startsWith("file") && !
                        jzDataSource.getCurrentUrl().toString().startsWith("/") &&
                        !JZUtils.isWifiConnected(getContext()) && !WIFI_TIP_DIALOG_SHOWED) {
                    showWifiDialog();
                    return;
                }

**Comment by lipangit** [comment]
@18702953620 什么意思，能仔细说说吗

**Comment by 18702953620** [comment]
传递一个网络视频，流量状态下，这个判断的3个条件都满足，然后这里就return了，然后就点击播放按钮没反应了。改变WIFI_TIP_DIALOG_SHOWED这个为true 是在showWifiDialog这个方法里，所以，除了复写showWifiDialog还得把这个设置为true
