### ISSUE TITLE
JiaoZiVideoPlayer logo proposal

### ISSUE THREAD

**Issue by hawk28** [lipangit/JiaoZiVideoPlayer#1952]
Hello, I am a graphic designer. I contribute to open source softwares by designing logos. Do you want me to design a logo for jJiaoZiVideoPlayer?. I will wait for feedback. Have a nice day!

**Comment by lipangit** [comment]
Yes I want

**Comment by lipangit** [comment]
U are a good man

**Comment by hawk28** [comment]
OK. 2 days, 3 days later the logo is ready

**Comment by lipangit** [comment]
Thank you every much

**Comment by hawk28** [comment]
D**id you like it? which one did you like? Is there a place you want to change?**

![logo 1](https://user-images.githubusercontent.com/38923402/41820040-e4efd12e-77d3-11e8-9f60-6774e8a9890a.png)
![logo 2](https://user-images.githubusercontent.com/38923402/41820041-e515e5bc-77d3-11e8-8f11-b71a76ac8737.png)
![logo 3](https://user-images.githubusercontent.com/38923402/41820042-e53873a2-77d3-11e8-92de-e6d0505b6337.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/41856786-852d7f34-78c8-11e8-877b-86acc7d8bd09.png)

**Comment by lipangit** [comment]
I think the circular icons suitable for icons, it looks good on the phone desktop.

What do you think of my unprofessional idea

**Comment by hawk28** [comment]
I'm not a full professional. 2. Do you like the logo?

**Comment by hawk28** [comment]
I can make an album if you like the second and third logo.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/41912507-840a545a-7982-11e8-81a1-390223519bee.png)

This is demo run on phone screenshot, and make the icon 
![image](https://user-images.githubusercontent.com/2038071/41912941-bfd07d8e-7982-11e8-8a18-ec8831fc071f.png)
 in that color,

**Comment by lipangit** [comment]
Just give me the source file ps or sketch.  Cut the icon and export the icon shoud not trouble you.

**Comment by lipangit** [comment]
What can I do for you, Do you have blog, I can show it here.
![image](https://user-images.githubusercontent.com/2038071/41914215-f3415812-7984-11e8-8d0e-59be43e81465.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/41914241-0778b532-7985-11e8-95ce-264cf7a85c04.png)

AND if you have time you can design the banner in the main page of the github

**Comment by hawk28** [comment]
Okay, I will send you the editable file.(ai)
I will design a banner and i will update the readme file.

Which one do you prefer? Please select. I will also send png variations.
![1](https://user-images.githubusercontent.com/38923402/41915606-c9288346-795e-11e8-8298-cbf7481e0e17.png)

**Comment by lipangit** [comment]
the circular icon in this color 
![image](https://user-images.githubusercontent.com/2038071/41966209-1f511df0-7a31-11e8-86a9-3b120f5b28fb.png)

**Comment by hawk28** [comment]
i sent a pr
https://github.com/lipangit/JiaoZiVideoPlayer/pull/1965

**Comment by hawk28** [comment]
Do you confirm :)

**Comment by lipangit** [comment]
Yes very good

**Comment by hawk28** [comment]
I look forward to your approval :)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/42031960-9edd73b4-7b0a-11e8-885d-c18eaa576b2b.png)
perfect

**Comment by lipangit** [comment]
![one colour horizontol](https://user-images.githubusercontent.com/2038071/42032336-d86e4d96-7b0b-11e8-885f-d1fe387a83d9.png)

save picture for main page

**Comment by hawk28** [comment]
Oo good :) I just wait for the pull requests to confirm :)

**Comment by hawk28** [comment]
Save picture
