### ISSUE TITLE
全屏状态下横屏会退出全屏并停止播放

### ISSUE THREAD

**Issue by Dragons-yu** [lipangit/JiaoZiVideoPlayer#1954]
代码是从DEMO里面复制过来的，复制的ActivityApi，删除了部分无关代码
`package com.hyl.jzplayer;

import android.hardware.Sensor;
import android.hardware.SensorManager;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.app.AppCompatDelegate;
import android.view.MenuItem;

import com.hyl.jzplayer.entity.Node;

import cn.jzvd.JZVideoPlayer;
import cn.jzvd.JZVideoPlayerStandard;

/**
 * Created by Kernel on 2018/6/24.
 */

public class PlayerActivity extends AppCompatActivity {
    JZVideoPlayerStandard mJzVideoPlayerStandard;
    JZVideoPlayer.JZAutoFullscreenListener mSensorEventListener;
    SensorManager mSensorManager;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);

        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);

        ActionBar ab = getSupportActionBar();
        if (ab == null) {
            return;
        }
        ab.setDisplayHomeAsUpEnabled(true);
        ab.setDisplayShowHomeEnabled(true);
        ab.setDisplayShowTitleEnabled(true);
        ab.setDisplayUseLogoEnabled(false);

        Bundle it = getIntent().getExtras();
        if (it == null) {
            return;
        }
        Node node = (Node) it.get("node");
        if (node == null) {
            return;
        }

        mJzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.jz_video);
        mJzVideoPlayerStandard.setUp(node.getUrl(),
                JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, node.getName());

        mSensorManager = (SensorManager) getSystemService(SENSOR_SERVICE);
        mSensorEventListener = new JZVideoPlayer.JZAutoFullscreenListener();
    }

    @Override
    protected void onResume() {
        super.onResume();
        Sensor accelerometerSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);
        mSensorManager.registerListener(mSensorEventListener, accelerometerSensor, SensorManager.SENSOR_DELAY_NORMAL);
        //home back
        JZVideoPlayer.goOnPlayOnResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        mSensorManager.unregisterListener(mSensorEventListener);
        JZVideoPlayer.clearSavedProgress(this, null);
        //home back
        JZVideoPlayer.goOnPlayOnPause();
    }

    @Override
    public void onBackPressed() {
        if (JZVideoPlayer.backPress()) {
            return;
        }
        super.onBackPressed();
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                finish();
                break;
        }
        return super.onOptionsItemSelected(item);
    }
}
`

**Comment by lipangit** [comment]
log是什么

**Comment by Dragons-yu** [comment]
06-25 22:39:52.989 27676-27676/com.hyl.jzplayer I/JiaoZiVideoPlayer: onStatePause  [218280304] 
06-25 22:39:52.989 27676-27676/com.hyl.jzplayer I/JiaoZiVideoPlayer: startProgressTimer:  [218280304] 
06-25 22:39:52.997 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [+]r_hnd(0x7f74a9a240), client(55), share_fd(101)
06-25 22:39:53.009 27676-27723/com.hyl.jzplayer I/GLConsumer: [SurfaceTexture-0-27676-0] detachFromContext
06-25 22:39:53.009 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]hnd(0x7f7c4d36a0), client(55), share_fd(86)
06-25 22:39:53.010 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]hnd(0x7f7c4d34c0), client(55), share_fd(94)
06-25 22:39:53.010 27676-27723/com.hyl.jzplayer I/GPUAUX: ~GPUAUXContext:64: destory: 0x7f5083f160
06-25 22:39:53.010 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]hnd(0x7f7c4d1a80), client(55), share_fd(99)
06-25 22:39:53.019 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]r_hnd(0x7f7c4d1760), client(55), share_fd(68)
06-25 22:39:53.020 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]r_hnd(0x7f7c4d1620), client(55), share_fd(72)
06-25 22:39:53.021 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]r_hnd(0x7f7c4d1940), client(55), share_fd(74)
06-25 22:39:53.021 27676-27723/com.hyl.jzplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f74a9a240
06-25 22:39:53.022 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [-]r_hnd(0x7f74a9a240), client(55), share_fd(101)
06-25 22:39:53.110 27676-27676/com.hyl.jzplayer I/JiaoZiVideoPlayer: onStateNormal  [245862259] 
06-25 22:39:53.119 27676-27676/com.hyl.jzplayer I/JiaoZiVideoPlayer: onStatePlaying  [218280304] 
06-25 22:39:53.119 27676-27676/com.hyl.jzplayer I/JiaoZiVideoPlayer: startProgressTimer:  [218280304] 
06-25 22:39:53.148 27676-27723/com.hyl.jzplayer W/libEGL: [ANDROID_RECORDABLE] format: 1
06-25 22:39:53.194 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [+]r_hnd(0x7f7c4d1940), client(55), share_fd(73)
06-25 22:39:53.202 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [+]r_hnd(0x7f7c4d1620), client(55), share_fd(86)
06-25 22:39:53.216 27676-27723/com.hyl.jzplayer I/[MALI][Gralloc]: [+]r_hnd(0x7f7c4d1760), client(55), share_fd(89)
就这些了，我也不知道哪些有用
06-25 22:39:53.021 27676-27723/com.hyl.jzplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f74a9a240
这行是红色的

**Comment by lipangit** [comment]
这里没有error的信息。

**Comment by lipangit** [comment]
建议你先把demo 下载下来跑通，然后修改demo的apiActivity成你想要的效果。

**Comment by lipangit** [comment]
另外看一眼Manifest的配置是不是漏掉了
