### ISSUE TITLE
6.0以下AudioManager会泄露

### ISSUE THREAD

**Issue by zerofield** [lipangit/JiaoZiVideoPlayer#1955]
6.0以下jzviedoplayer 中 this.mAudioManager = (AudioManager)this.getContext().getSystemService("audio"); 会导致AudioManager持有Activity，导致泄漏

https://issuetracker.google.com/issues/37024105
https://android-review.googlesource.com/c/platform/frameworks/base/+/140481/1

**Comment by lipangit** [comment]
兄弟对这个问题的理解如此深入，不妨帮忙想想解决办法，老臣不擅长这个问题。
