### ISSUE TITLE
视频进度条拖动问题

### ISSUE THREAD

**Issue by shiwukuanghun** [lipangit/JiaoZiVideoPlayer#1956]
某些视频会出现拖动进度的问题，比如一个15秒的视频，我拖到3秒，它就从头开始播放，我拖动到13秒，它就从10秒开始播放，但是有些视频就不会出现这种情况，有人说是视频帧的问题，请问这种问题该怎么解决

**Comment by lipangit** [comment]
对，我也是听说，这是视频关键帧的问题，你可以研究一下然后分享出来
