### ISSUE TITLE
3.3视频左右有黑边，怎么去除视频左右黑边

### ISSUE THREAD

**Issue by ShrioQW** [lipangit/JiaoZiVideoPlayer#1958]
项目用的是3.3 ，高是定死的，视频左右会有黑边，请问能去除黑边吗？

**Comment by lipangit** [comment]
参考demo的changesize，有视频多种视频拉伸的方法

**Comment by CQBOBOZHU** [comment]
@lipangit   我在cn.jzvd:jiaozivideoplayer:6.2.12  在并没有找到Jzvd类
