### ISSUE TITLE
调用JZVideoPlayer.releaseAllVideos();  崩溃

### ISSUE THREAD

**Issue by max8888888** [lipangit/JiaoZiVideoPlayer#1959]
在listView的header中添加了一个视频播放器，然后在退出的时候，在onPause里调用JZVideoPlayer.releaseAllVideos();  就卡死了。  我看了log发生了崩溃异常，具体如下：
# EXCEPTION STACK:
 java.lang.NoClassDefFoundError:Failed resolution of: Landroid/support/v7/view/ContextThemeWrapper;
                                                              cn.jzvd.JZUtils.getAppCompActivity(JZUtils.java:82)
                                                              ......
                                                              cause by:
                                                              java.lang.ClassNotFoundException:Didn't find class "android.support.v7.view.ContextThemeWrapper" on path: DexPathList[[zip file "/data/app/com.youmingxing-1/base.apk"],nativeLibraryDirectories=[/data/app/com.youmingxing-1/lib/arm, /vendor/lib, /system/lib]]
                                                              dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                              java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                              java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                              cn.jzvd.JZUtils.getAppCompActivity(JZUtils.java:82)
                                                              cn.jzvd.JZVideoPlayer.showSupportActionBar(JZVideoPlayer.java:221)
                                                              cn.jzvd.JZVideoPlayer.clearFullscreenLayout(JZVideoPlayer.java:835)
                                                              cn.jzvd.JZVideoPlayer.onCompletion(JZVideoPlayer.java:776)
                                                              cn.jzvd.JZVideoPlayerStandard.onCompletion(JZVideoPlayerStandard.java:806)
                                                              cn.jzvd.JZVideoPlayerManager.completeAll(JZVideoPlayerManager.java:42)
                                                              cn.jzvd.JZVideoPlayer.releaseAllVideos(JZVideoPlayer.java:143)
                                                              com.youmingxing.activity.ContentDetailActivity$21.run(ContentDetailActivity.java:1216)
                                                              android.os.Handler.handleCallback(Handler.java:815)
                                                              android.os.Handler.dispatchMessage(Handler.java:104)
                                                              android.os.Looper.loop(Looper.java:194)
                                                              android.app.ActivityThread.main(ActivityThread.java:5546)
                                                              java.lang.reflect.Method.invoke(Native Method)
                                                              java.lang.reflect.Method.invoke(Method.java:372)
                                                              com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                              com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

请问，我该怎么修改这个问题呢？

**Comment by lipangit** [comment]
研究一下这里，你的activity是什么activity
![image](https://user-images.githubusercontent.com/2038071/41911819-49c44b9a-7980-11e8-9bec-e652a7c76a74.png)
