### ISSUE TITLE
横竖屏的问题

### ISSUE THREAD

**Issue by AndyYw** [lipangit/JiaoZiVideoPlayer#1960]
大佬，我用as编译时直接全屏播放没问题。。但用打包工具打出apk横竖屏就会出现界面横屏了，但不是播放界面，还是原来的界面

**Comment by lipangit** [comment]
能截图说明吗

**Comment by AndyYw** [comment]
try {
            Constructor<JZVideoPlayer> constructor = _class.getConstructor(Context.class);
            final JZVideoPlayer jzVideoPlayer = constructor.newInstance(context);
            jzVideoPlayer.setId(R.id.jz_fullscreen_id);
            FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            vp.addView(jzVideoPlayer, lp);
            jzVideoPlayer.setUp(dataSourceObjects, defaultUrlMapIndex, JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, objects);
            CLICK_QUIT_FULLSCREEN_TIME = System.currentTimeMillis();
            jzVideoPlayer.startButton.performClick();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
这里走到反射的异常里去了。as编译的时候是好的，用jenkins打出来的包不行。这是什么原因呢

**Comment by AndyYw** [comment]
找到问题了，混淆和反射冲突了。。

**Comment by lipangit** [comment]
ok

**Comment by dongfangmingjia** [comment]
请问这个怎么解决的，能发一下混淆代码吗？

**Comment by lipangit** [comment]
如果不引入ijkplayer的话，项目本身不需要混淆代码
