### ISSUE TITLE
切换播放源，能否无感知的切换，只刷新播放的url

### ISSUE THREAD

**Issue by abc20899** [lipangit/JiaoZiVideoPlayer#1962]

**Comment by lipangit** [comment]
这个问题我想过，但是仔细想来实现起来非常复杂，。

首先用户不知道什么时候切换播放源，比如切换清晰度的时候，一个10分钟的视频除了把所有的清晰度都完整的缓存出来之外，才能做到任何地方都能切换清晰度并感知不到，目测断定是个伪需求，没有意义。

**Comment by ruiilxiaobai** [comment]
缓存后加载时间好久啊
