### ISSUE TITLE
How can i use JiaoZiVideoPlayer to use ExoPlayer engine ?

### ISSUE THREAD

**Issue by debjitk** [lipangit/JiaoZiVideoPlayer#1964]
How can i use JiaoZiVideoPlayer to use ExoPlayer engine ? How is JiaoZiVideoPlayer different from ExoPlayer ?

**Comment by lipangit** [comment]
see demo customVideoplayer

**Comment by omidraha** [comment]
What's the current way to  change JiaoZiVideoPlayer to use ExoPlayer engine ? 
There is no `customVideoplayer` on the demo.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48599943-ddce6700-e9a4-11e8-807d-cba10077ba36.png)

in this activity
