### ISSUE TITLE
如何实现循环播放 Loop

### ISSUE THREAD

**Issue by bboyyi1990** [lipangit/JiaoZiVideoPlayer#1966]
请问如何实现循环播放？没有提供方法的话如何拓展实现，能给个方向吗

**Comment by bboyyi1990** [comment]
<img width="848" alt="2018-06-27 21 28 18" src="https://user-images.githubusercontent.com/17938284/41977057-0cac05be-7a51-11e8-8bd6-0d9b99032d22.png">
在项目主的指导下 ，找到了解决方案，希望有同样需求的同志，顺利解决

**Comment by lipangit** [comment]
么么哒 小可爱
