### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference cn.jzvd.JZMediaManager.onSurfaceTextureAvailable(JZMediaManager.java:109)

### ISSUE THREAD

**Issue by TracyEminem** [lipangit/JiaoZiVideoPlayer#1969]
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
cn.jzvd.JZMediaManager.onSurfaceTextureAvailable(JZMediaManager.java:109)

暂时只在五台设备上发现了这个问题，android版本号都是5.1.1和6.0.1

1 cn.jzvd.JZMediaManager.onSurfaceTextureAvailable(JZMediaManager.java:109)
2 android.view.TextureView.getHardwareLayer(TextureView.java:370)
3 android.view.View.updateDisplayListIfDirty(View.java:14202)
4 android.view.View.getDisplayList(View.java:14247)
5 android.view.View.draw(View.java:15031)
6 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
7 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
8 android.view.View.updateDisplayListIfDirty(View.java:14220)
9 android.view.View.getDisplayList(View.java:14247)
10 android.view.View.draw(View.java:15031)
11 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
12 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
13 android.view.View.draw(View.java:15306)
14 android.view.View.updateDisplayListIfDirty(View.java:14225)
15 android.view.View.getDisplayList(View.java:14247)
16 android.view.View.draw(View.java:15031)
17 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
18 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
19 android.view.View.updateDisplayListIfDirty(View.java:14220)
20 android.view.View.getDisplayList(View.java:14247)
21 android.view.View.draw(View.java:15031)
22 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
23 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
24 android.view.View.updateDisplayListIfDirty(View.java:14220)
25 android.view.View.getDisplayList(View.java:14247)
26 android.view.View.draw(View.java:15031)
27 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
28 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
29 android.view.View.updateDisplayListIfDirty(View.java:14220)
30 android.view.View.getDisplayList(View.java:14247)
31 android.view.View.draw(View.java:15031)
32 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
33 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
34 android.view.View.updateDisplayListIfDirty(View.java:14220)
35 android.view.View.getDisplayList(View.java:14247)
36 android.view.View.draw(View.java:15031)
37 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
38 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
39 android.view.View.draw(View.java:15306)
40 android.widget.FrameLayout.draw(FrameLayout.java:598)
41 android.support.v4.widget.NestedScrollView.draw(NestedScrollView.java:1768)
42 android.view.View.updateDisplayListIfDirty(View.java:14225)
43 android.view.View.getDisplayList(View.java:14247)
44 android.view.View.draw(View.java:15031)
45 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
46 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
47 android.view.View.updateDisplayListIfDirty(View.java:14220)
48 android.view.View.getDisplayList(View.java:14247)
49 android.view.View.draw(View.java:15031)
50 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
51 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
52 android.view.View.updateDisplayListIfDirty(View.java:14220)
53 android.view.View.getDisplayList(View.java:14247)
54 android.view.View.draw(View.java:15031)
55 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
56 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
57 android.view.View.updateDisplayListIfDirty(View.java:14220)
58 android.view.View.getDisplayList(View.java:14247)
59 android.view.View.draw(View.java:15031)
60 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
61 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
62 android.view.View.updateDisplayListIfDirty(View.java:14220)
63 android.view.View.getDisplayList(View.java:14247)
64 android.view.View.draw(View.java:15031)
65 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
66 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
67 android.view.View.updateDisplayListIfDirty(View.java:14220)
68 android.view.View.getDisplayList(View.java:14247)
69 android.view.View.draw(View.java:15031)
70 android.view.ViewGroup.drawChild(ViewGroup.java:3414)
71 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3205)
72 android.view.View.draw(View.java:15306)
73 android.widget.FrameLayout.draw(FrameLayout.java:598)
74 com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2671)
75 android.view.View.updateDisplayListIfDirty(View.java:14225)
76 android.view.View.getDisplayList(View.java:14247)
77 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:291)
78 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:297)
79 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:349)
80 android.view.ViewRootImpl.draw(ViewRootImpl.java:2653)
81 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2425)
82 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2048)
83 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
84 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
85 android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
86 android.view.Choreographer.doCallbacks(Choreographer.java:612)
87 android.view.Choreographer.doFrame(Choreographer.java:581)
88 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
89 android.os.Handler.handleCallback(Handler.java:739)
90 android.os.Handler.dispatchMessage(Handler.java:95)
91 android.os.Looper.loop(Looper.java:135)
92 android.app.ActivityThread.main(ActivityThread.java:5593)
93 java.lang.reflect.Method.invoke(Native Method)
94 java.lang.reflect.Method.invoke(Method.java:372)
95 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
96 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by TracyEminem** [comment]
Error during detachFromGLContext (see logcat for details)
android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:195)

还有一个类似的错误，不知道是不是jiaozivideoplayer造成的

**Comment by lipangit** [comment]
已经修复，周日发版，及时更新
![image](https://user-images.githubusercontent.com/2038071/42017438-a93868ba-7ae1-11e8-974b-69d475f3710b.png)

这个问题，在开始时播放视频的时候，在surfaceView开始生成和生成之间releaseVideos了，然后出发当前jzvd为空，感谢你的反馈。

**Comment by TracyEminem** [comment]
抱歉，问一下，下面这个error也是这个问题引起的吗？

Error during detachFromGLContext (see logcat for details)
android.graphics.SurfaceTexture.detachFromGLContext(SurfaceTexture.java:195)

**Comment by TracyEminem** [comment]
我没有自定义播放器，但我在releaseAllVideos()方法前，调用了JZMediaManager.textureView = null;，不知道这个是不是造成这个问题的原因？

**Comment by lipangit** [comment]
releaseAllVideos里会把textureView置空，好像重复了，不需要这样

**Comment by TracyEminem** [comment]
6.2.11 是你说的这周日要更新的最新版本吗？

**Comment by TracyEminem** [comment]
![2018-07-01 11 37 41](https://user-images.githubusercontent.com/16361918/42130846-3cacafc8-7d23-11e8-8054-8d88b0ee7dd0.png)

我试着引用6.2.11，这边报错了

**Comment by lipangit** [comment]
再试试

**Comment by lipangit** [comment]
刚弄了个6.2.12，之前网络好像有点问题，解析不到域名

**Comment by TracyEminem** [comment]
已经可以了，感谢
