### ISSUE TITLE
couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by wujianwei121** [lipangit/JiaoZiVideoPlayer#1970]
我下载demo运行没有问题   到自己项目就报这个错误    compile 'cn.jzvd:jiaozivideoplayer:6.2.10'
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.8.8'
    all32Compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    all32Compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
    all32Compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'

    all64Compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    all64Compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
    all64Compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.8'
    all64Compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
    all64Compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.8'  而且我都补全了   还是不行

**Comment by lipangit** [comment]
这是引入库的问题，超出老臣解决范围，到ijkplayer项目中提问

**Comment by xiaojintongxue** [comment]
解决此问题方法：第一删除 mips mips64的jni包  第二加入splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'armeabi'
            universalApk false
        }
    }  即可解决

**Comment by cuixiaolong133** [comment]
> 解决此问题方法：第一删除 mips mips64的jni包 第二加入splits {
> abi {
> enable true
> reset()
> include 'x86', 'x86_64', 'armeabi-v7a', 'armeabi'
> universalApk false
> }
> } 即可解决

app 目录下 buildgradle 引用，完美解决

**Comment by lipangit** [comment]
@cuixiaolong133 完美老铁
