### ISSUE TITLE
how i can play a video openload? 

### ISSUE THREAD

**Issue by gianpaul** [lipangit/JiaoZiVideoPlayer#1972]
hi , i have its url https://openload.co/f/60Ds4LN_hoA/1_-_Thinking_Like_a_Programmer.mp4%22# , how i can play it ?

**Comment by lipangit** [comment]
You should get the url of mp4

**Comment by gianpaul** [comment]
can u help me ? how i can get the url of mp4
 its link  https://openload.co/f/60Ds4LN_hoA/1_-_Thinking_Like_a_Programmer.mp4%22#

**Comment by lipangit** [comment]
Beyond my ability
