### ISSUE TITLE
 java.lang.IllegalStateException 视频暂停的时候

### ISSUE THREAD

**Issue by uty3714** [lipangit/JiaoZiVideoPlayer#1973]
1、NativeVideoDetailActivity里的onPause  2234行
` @Override
    protected void onPause() {
        super.onPause();
        isPopRewardDialog = false;
        isPlayPause = true;
        if(mCustomVideoPlayer != null) {
            JZVideoPlayer.goOnPlayOnPause();
       }
    }
`
几率性报 类型异常
Caused by: java.lang.IllegalStateException
	at android.media.MediaPlayer._pause(Native Method)
	at android.media.MediaPlayer.pause(MediaPlayer.java:1592)
	at cn.jzvd.c.pause(SourceFile:54)
	at cn.jzvd.b.pause(SourceFile:82)
	at cn.jzvd.g.goOnPlayOnPause(SourceFile:275)
	at com.xx.xxx.activity.NativeVideoDetailActivity.onPause(SourceFile:2234)

logcat : 

06-29 11:01:43.717 I/JZCustomVideo(18021): getLayoutId: 加载xml布局
--
518 | 06-29 11:01:43.797 I/VideoDetailActivity(18021): initView: 视频地址 url = http://myvod.weiyicloud.com/aaa07f7af4374568a06dc088d6a37630/626419b641c044a8965a1e5f20fda3ab-fb735d4babae84cfc4ea2cdeef92e924-ld.mp4
519 | 06-29 11:01:43.807 I/KKKKKK  (18021): init: Max = 100
520 | 06-29 11:01:43.807 I/VideoDetailActivity(18021): -->startPlayVideo: url = http://myvod.weiyicloud.com/aaa07f7af4374568a06dc088d6a37630/626419b641c044a8965a1e5f20fda3ab-fb735d4babae84cfc4ea2cdeef92e924-ld.mp4
521 | 06-29 11:01:43.807 D/JiaoZiVideoPlayer(18021): releaseAllVideos
522 | 06-29 11:01:43.807 I/JiaoZiVideoPlayer(18021): onStateNormal  [276845148]
523 | 06-29 11:01:43.807 I/JZCustomVideo(18021): setAllControlsVisiblity: 设置view显示 = 0
524 | 06-29 11:01:43.817 D/JiaoZiVideoPlayer(18021): startVideo [276845148]
525 | 06-29 11:01:43.817 D/JiaoZiVideoPlayer(18021): addTextureView [276845148]
526 | 06-29 11:01:43.817 I/JiaoZiVideoPlayer(18021): onStatePreparing  [276845148]
527 | 06-29 11:01:43.817 I/JZCustomVideo(18021): setAllControlsVisiblity: 设置view显示 = 4
528 | 06-29 11:01:43.817 I/JZCustomVideo(18021): startVideo: 开始播放
529 | 06-29 11:01:43.847 E/TAG     (18021): still foreground
530 | 06-29 11:01:43.847 E/TAG     (18021): still foreground
531 | 06-29 11:01:43.857 I/JiaoZiVideoPlayer(18021): onStatePause  [276845148]
532 | 06-29 11:01:43.857 I/JiaoZiVideoPlayer(18021): startProgressTimer:  [276845148]
533 | 06-29 11:01:43.867 I/JZCustomVideo(18021): setAllControlsVisiblity: 设置view显示 = 0
534 | 06-29 11:01:43.867 I/JZCustomVideo(18021): onStatePause: 暂停视频并进入暂停
535 | 06-29 11:01:43.867 I/VideoDetailActivity(18021): onClick: 暂停播放
536 | 06-29 11:01:43.867 D/AndroidRuntime(18021): Shutting down VM

**Comment by lipangit** [comment]
这个log表示在releaseVideo之后调用meidaplayer的暂停

**Comment by uty3714** [comment]
调用的是 goOnPlayOnPause 好像没释放

**Comment by lipangit** [comment]
兄弟怎么样了

**Comment by lifeidroid** [comment]
@lipangit 请问一下这个问题怎么解决呢

**Comment by lipangit** [comment]
这都去年的问题了，新版还有吗
