### ISSUE TITLE
需要循环播放2个视频，一个视频播放完了咋设置播放另一个？

### ISSUE THREAD

**Issue by xsy2015** [lipangit/JiaoZiVideoPlayer#1974]
需要循环播放2个视频，一个视频播放完了咋设置播放另一个？

**Comment by xsy2015** [comment]
播放完之后设置
jcv_player.setUp(）
jcv_player.startVideo()
不能播放，还需要在点击下屏幕才能播放

**Comment by lipangit** [comment]
这个属于自定义播放器，首先继承jzvideoPlayerStandard，然后复写onAutoComplete函数取得播放完成的事件
