### ISSUE TITLE
java.lang.RuntimeException: setDataSource failed: status = 0x80000000

### ISSUE THREAD

**Issue by x58548078** [lipangit/JiaoZiVideoPlayer#1976]
华为手机 8.0
视频播放不出来，其他是手机如小米可以播放
报错:java.lang.RuntimeException: setDataSource failed: status = 0x80000000

**Comment by x58548078** [comment]
点击播放后打印日志:
E/JiaoZiVideoPlayer: onError 1 - -2147483648 [251595027]

**Comment by lipangit** [comment]
这应该是MediaPlayer的问题，新建项目用android.media.MediaPlayer试试
