### ISSUE TITLE
请问可以实现后台播放功能吗？

### ISSUE THREAD

**Issue by XuQK** [lipangit/JiaoZiVideoPlayer#1980]
类似B站那样的后台播放

**Comment by lipangit** [comment]
需要自定义，没有现成的

**Comment by XuQK** [comment]
现在碰到了个问题，视频进入后台播放，home键回到桌面后，通过通知栏切换视频源，要等回到app了它才生效，也就是说通过player的setup()方法设置视频源，要等当前activity resume后才会执行。
这个要怎么弄我就完全没头绪了，难道要把这个视频写到service里面去吗？怎么写我也是一头雾水，求大佬指条明路。。。

**Comment by lipangit** [comment]
在通知栏切换视频源是什么意思，切换完没在页面中如何播放呀

**Comment by XuQK** [comment]
就是类似音乐播放器那种，在通知栏可以选择上一个，下一个这样的功能，目前我写的是通知栏发送广播，在视频activity接收这个广播，然后调用player的setup方法，然后就出现了这种情况，就好像被阻塞了一样，要activity resume线程才通。。。
您这库可以不通过布局里的player这个view，直接通过player核心来设置和播放视频吗，也就是说不更新当前textureview，直接切换视频源，可以吗，可以的话，可以指点一下怎么操作吗。。。弄了一天了，快被弄死了☹

**Comment by lipangit** [comment]
兄弟，在通知栏中控制视频，是想在看不见图像的情况下后台控制视频吗

**Comment by XuQK** [comment]
对的，就像B站的那样

**Comment by XuQK** [comment]
折腾了一天，应该算是搞定了，你看看我这样弄有没有什么隐患

**Comment by lipangit** [comment]
一天搞定还是蛮快的

**Comment by XuQK** [comment]
@maxiaoxu2017 https://github.com/lipangit/JiaoZiVideoPlayer/pull/2198 这个pr里有我修改实现的示例

**Comment by maxiaoxu2017** [comment]
@XuQK 好的，非常感谢!

**Comment by lipangit** [comment]
参考这个 https://github.com/lipangit/JiaoZiVideoPlayer/pull/2198
