### ISSUE TITLE
Change color of the bottom red progress bar

### ISSUE THREAD

**Issue by anonym2** [lipangit/JiaoZiVideoPlayer#1982]
Hi I want set the bottom progress bar with the blue color how can I do it Sir ?

**Comment by lipangit** [comment]
Of course.
This is custom Mediaplayer feature.

Extends JZVideoPlayerStandard Override getLayout(), return Your xml, change the progressbar in your xml. 

See SmallChangeActivity in demo.

**Comment by anonym2** [comment]
Oh thanks you Sir for reply I'll try it
