### ISSUE TITLE
播放视频是MediaPlayer报错handleMessage msg:(100, 1, -2147479551)

### ISSUE THREAD

**Issue by 879032828** [lipangit/JiaoZiVideoPlayer#1984]
视频链接为：http://ar.video.1scrn.cn/syt2.mp4
饺子播放器版本为：6.2.1
手机型号：oppo R9tm
手机Android版本：5.1
手机系统版本：ColorOS V3.0.0

以下为log信息：
07-04 10:44:38.558 7750-7750/? I/art: Late-enabling -Xcheck:jni
07-04 10:44:38.719 7750-7750/cn.jzvd.demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-04 10:44:38.731 7750-7750/cn.jzvd.demo E/Process: android_os_Process_getProcessNameByPid pid is 7750
07-04 10:44:38.731 7750-7750/cn.jzvd.demo E/Process: android_os_Process_getProcessNameByPid value is cn.jzvd.demo
07-04 10:44:38.830 7750-7750/cn.jzvd.demo D/ProgressBar: setMax, old = 100, new = 100, backtrace = android.widget.AbsSeekBar.setMax:350 android.widget.ProgressBar.<init>:300 android.widget.AbsSeekBar.<init>:99 android.widget.SeekBar.<init>:87 android.widget.SeekBar.<init>:83 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......I. 0,0-0,0 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:38.830 7750-7750/cn.jzvd.demo D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 android.widget.ProgressBar.<init>:302 android.widget.AbsSeekBar.<init>:99 android.widget.SeekBar.<init>:87 android.widget.SeekBar.<init>:83 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......I. 0,0-0,0 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:38.831 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.<init>:304 android.widget.AbsSeekBar.<init>:99 android.widget.SeekBar.<init>:87 android.widget.SeekBar.<init>:83 android.support.v7.widget.AppCompatSeekBar.<init>:46 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......I. 0,0-0,0 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:38.856 7750-7750/cn.jzvd.demo D/ProgressBar: setMax, old = 100, new = 100, backtrace = android.widget.ProgressBar.<init>:300 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{1acf3aec V.ED.... ........ 0,0-0,0 #7f0b0093 app:id/bottom_progress}
07-04 10:44:38.857 7750-7750/cn.jzvd.demo D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 android.widget.ProgressBar.<init>:302 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 , this = android.widget.ProgressBar{1acf3aec V.ED.... ........ 0,0-0,0 #7f0b0093 app:id/bottom_progress}
07-04 10:44:38.857 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.<init>:304 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{1acf3aec V.ED.... ........ 0,0-0,0 #7f0b0093 app:id/bottom_progress}
07-04 10:44:38.878 7750-7750/cn.jzvd.demo D/ProgressBar: setMax, old = 100, new = 100, backtrace = android.widget.ProgressBar.<init>:300 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{3b09dc9e I.ED.... ........ 0,0-0,0 #7f0b009a app:id/loading}
07-04 10:44:38.878 7750-7750/cn.jzvd.demo D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 android.widget.ProgressBar.<init>:302 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 , this = android.widget.ProgressBar{3b09dc9e I.ED.... ........ 0,0-0,0 #7f0b009a app:id/loading}
07-04 10:44:38.879 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.<init>:304 android.widget.ProgressBar.<init>:262 android.widget.ProgressBar.<init>:258 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{3b09dc9e I.ED.... ........ 0,0-0,0 #7f0b009a app:id/loading}
07-04 10:44:38.915 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onStateNormal  [967620237] 
07-04 10:44:38.923 7750-7750/cn.jzvd.demo W/SettingsInterface: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-04 10:44:38.925 7750-7750/cn.jzvd.demo D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@2209647,provider,holder.Provider:android.content.ContentProviderProxy@1793ce74
07-04 10:44:38.935 7750-7750/cn.jzvd.demo V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{2216ef30 I.E..... R.....ID 0,0-0,0}
07-04 10:44:38.945 7750-7798/cn.jzvd.demo I/System.out: open:http://jzvd-pic.nathen.cn/jzvd-pic/1bb2ebbe-140d-4e2e-abd2-9e7e564f71ac.png
07-04 10:44:38.945 7750-7798/cn.jzvd.demo D/PerfServiceWrapper: Reflection Init
07-04 10:44:38.946 7750-7798/cn.jzvd.demo I/System.out: sLuckyMoneyUrl = wx.gtimg.com/hongbao/
07-04 10:44:38.947 7750-7798/cn.jzvd.demo I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
07-04 10:44:38.947 7750-7798/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=jzvd-pic.nathen.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:38.948 7750-7798/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=jzvd-pic.nathen.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
07-04 10:44:38.959 7750-7750/cn.jzvd.demo D/OpenGLRenderer: Dumper init 4 threads <0xf4971620>
07-04 10:44:38.960 7750-7750/cn.jzvd.demo D/OpenGLRenderer: <cn.jzvd.demo> is running.
07-04 10:44:38.961 7750-7801/cn.jzvd.demo D/OpenGLRenderer: initialize DisplayEventReceiver 0xf4adb980
07-04 10:44:38.962 7750-7801/cn.jzvd.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-04 10:44:38.963 7750-7750/cn.jzvd.demo D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{1cbea522 cn.jzvd.demo/cn.jzvd.demo.ActivityMain,ident = 0}
07-04 10:44:38.976 7750-7750/cn.jzvd.demo V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{1cbea522 cn.jzvd.demo/cn.jzvd.demo.ActivityMain,ident = 0}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{2216ef30 V.E..... R.....ID 0,0-0,0}
07-04 10:44:39.006 7750-7798/cn.jzvd.demo D/libc-netbsd: getaddrinfo: jzvd-pic.nathen.cn get result from proxy >>
07-04 10:44:39.006 7750-7798/cn.jzvd.demo I/System.out: [CDS]rx timeout:20000
07-04 10:44:39.007 7750-7798/cn.jzvd.demo I/System.out: [socket][0] connection jzvd-pic.nathen.cn/121.9.212.221:80;LocalPort=52067(15000)
07-04 10:44:39.007 7750-7798/cn.jzvd.demo I/System.out: [CDS]connect[jzvd-pic.nathen.cn/121.9.212.221:80] tm:15
07-04 10:44:39.008 7750-7798/cn.jzvd.demo D/Posix: [Posix_connect Debug]Process cn.jzvd.demo :80 
07-04 10:44:39.014 7750-7798/cn.jzvd.demo I/System.out: [socket][/192.168.1.141:52067] connected
07-04 10:44:39.015 7750-7798/cn.jzvd.demo I/System.out: [CDS]SO_SND_TIMEOUT:0
07-04 10:44:39.015 7750-7798/cn.jzvd.demo I/System.out: [OkHttp] sendRequest>>
07-04 10:44:39.015 7750-7798/cn.jzvd.demo I/System.out: [OkHttp] sendRequest<<
07-04 10:44:39.024 7750-7801/cn.jzvd.demo D/OpenGLRenderer: CanvasContext() 0xf4897700 initialize 0xf49c8508
07-04 10:44:39.024 7750-7801/cn.jzvd.demo D/MALI: eglInitialize:1479: [+]
07-04 10:44:39.027 7750-7801/cn.jzvd.demo E/GED: Failed to get GED Log Buf, err(0)
07-04 10:44:39.027 7750-7801/cn.jzvd.demo D/MALI: eglInitialize:1850: [-]
                                                  
                                                  [ 07-04 10:44:39.027  7750: 7801 I/         ]
                                                  elapse(include ctx switch):3227 (ms), eglInitialize
07-04 10:44:39.028 7750-7801/cn.jzvd.demo I/OpenGLRenderer: Initialized EGL, version 1.4
07-04 10:44:39.028 7750-7801/cn.jzvd.demo D/MALI: eglCreateContext:206: [MALI] eglCreateContext display 0xf4a78f00, share context 0x0 here.
07-04 10:44:39.036 7750-7801/cn.jzvd.demo D/MALI: gles_context_new:248: Create GLES ctx 0xe0003008 successfully
07-04 10:44:39.036 7750-7801/cn.jzvd.demo D/MALI: eglCreateContext:543: [MALI] eglCreateContext end. Created context 0xf4b8ed28 here.
07-04 10:44:39.036 7750-7801/cn.jzvd.demo D/OpenGLRenderer: Created EGL context (0xf4974850)
07-04 10:44:39.037 7750-7801/cn.jzvd.demo I/OpenGLRenderer: Get enable program binary service property (1)
07-04 10:44:39.037 7750-7801/cn.jzvd.demo I/OpenGLRenderer: Initializing program atlas...
07-04 10:44:39.037 7750-7801/cn.jzvd.demo D/ProgramBinary/Service: BpProgramBinaryService.getFileDescriptor
07-04 10:44:39.037 7750-7801/cn.jzvd.demo D/ProgramBinary/Service: BpProgramBinaryService.getProgramMapLen
07-04 10:44:39.037 7750-7801/cn.jzvd.demo D/ProgramBinary/Service: BpProgramBinaryService.getProgramMapArray
07-04 10:44:39.037 7750-7801/cn.jzvd.demo D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryLen
07-04 10:44:39.038 7750-7801/cn.jzvd.demo I/OpenGLRenderer: Program binary detail: Binary length is 169984, program map length is 152.
07-04 10:44:39.038 7750-7801/cn.jzvd.demo I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 57, and path is /dev/ashmem�8�	�T�?��F�q1A���?�i[A�.
07-04 10:44:39.038 7750-7801/cn.jzvd.demo I/OpenGLRenderer: No need to use file discriptor anymore, close fd(57).
07-04 10:44:39.038 7750-7801/cn.jzvd.demo D/OpenGLRenderer: TaskManager() 0xf4b5f2e0, cpu = 8, thread = 4
07-04 10:44:39.038 7750-7801/cn.jzvd.demo D/OpenGLRenderer: Initializing program cache from 0x0, size = -1
07-04 10:44:39.039 7750-7801/cn.jzvd.demo D/OpenGLRenderer: Enabling debug mode 0
07-04 10:44:39.039 7750-7801/cn.jzvd.demo D/Surface: Surface::connect(this=0xf49c8500,api=1)
07-04 10:44:39.040 7750-7801/cn.jzvd.demo D/mali_winsys: new_window_surface returns 0x3000
07-04 10:44:39.040 7750-7801/cn.jzvd.demo D/Surface: Surface::allocateBuffers(this=0xf49c8500)
07-04 10:44:39.064 7750-7801/cn.jzvd.demo D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask1 (7816)
07-04 10:44:39.065 7750-7801/cn.jzvd.demo D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask2 (7817)
07-04 10:44:39.065 7750-7801/cn.jzvd.demo D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask3 (7818)
07-04 10:44:39.065 7750-7801/cn.jzvd.demo D/OpenGLRenderer: [TaskMgr] Running thread hwuiTask4 (7819)
07-04 10:44:39.082 7750-7801/cn.jzvd.demo W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 11721
07-04 10:44:39.088 7750-7801/cn.jzvd.demo D/OpenGLRenderer: ProgramCache save to disk, size = 5
07-04 10:44:39.141 7750-7750/cn.jzvd.demo V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
07-04 10:44:39.141 7750-7750/cn.jzvd.demo V/InputMethodManager: START INPUT: com.android.internal.policy.impl.PhoneWindow$DecorView{2216ef30 V.E..... R....... 0,0-1080,1920} ic=null tba=android.view.inputmethod.EditorInfo@3c127f15 controlFlags=#104
07-04 10:44:39.144 7750-7771/cn.jzvd.demo D/InputMethodManager: receive service's setActive call, active:true
07-04 10:44:39.145 7750-7750/cn.jzvd.demo I/InputMethodManager: handleMessage: MSG_SET_ACTIVE true, was false
07-04 10:44:51.491 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onClick start [967620237] 
07-04 10:44:51.495 7750-7750/cn.jzvd.demo D/JiaoZiVideoPlayer: startVideo [967620237] 
07-04 10:44:51.500 7750-7750/cn.jzvd.demo D/JiaoZiVideoPlayer: addTextureView [967620237] 
07-04 10:44:51.511 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onStatePreparing  [967620237] 
07-04 10:44:51.511 7750-7750/cn.jzvd.demo D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 cn.jzvd.JZVideoPlayer.resetProgressAndTime:897 cn.jzvd.JZVideoPlayerStandard.resetProgressAndTime:487 cn.jzvd.JZVideoPlayer.onStatePreparing:658 cn.jzvd.JZVideoPlayerStandard.onStatePreparing:181 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......ID 148,28-816,121 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:51.512 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = cn.jzvd.JZVideoPlayer.resetProgressAndTime:898 cn.jzvd.JZVideoPlayerStandard.resetProgressAndTime:487 cn.jzvd.JZVideoPlayer.onStatePreparing:658 cn.jzvd.JZVideoPlayerStandard.onStatePreparing:181 cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard.onStatePreparing:64 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......ID 148,28-816,121 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:51.513 7750-7750/cn.jzvd.demo D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1311 cn.jzvd.JZVideoPlayerStandard.resetProgressAndTime:488 cn.jzvd.JZVideoPlayer.onStatePreparing:658 cn.jzvd.JZVideoPlayerStandard.onStatePreparing:181 cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard.onStatePreparing:64 , this = android.widget.ProgressBar{1acf3aec I.ED.... ......I. 0,595-1080,600 #7f0b0093 app:id/bottom_progress}
07-04 10:44:51.513 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = cn.jzvd.JZVideoPlayerStandard.resetProgressAndTime:489 cn.jzvd.JZVideoPlayer.onStatePreparing:658 cn.jzvd.JZVideoPlayerStandard.onStatePreparing:181 cn.jzvd.demo.CustomView.MyJZVideoPlayerStandard.onStatePreparing:64 cn.jzvd.JZVideoPlayer.startVideo:609 , this = android.widget.ProgressBar{1acf3aec I.ED.... ......I. 0,595-1080,600 #7f0b0093 app:id/bottom_progress}
07-04 10:44:51.515 7750-7750/cn.jzvd.demo I/USER_EVENT: ON_CLICK_START_ICON title is : 饺子快长大 url is : http://ar.video.1scrn.cn/syt2.mp4 screen is : 0
07-04 10:44:51.517 7750-7750/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [19462033] 
07-04 10:44:51.517 7750-7750/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [19462033] 
07-04 10:44:51.526 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [967620237] 
07-04 10:44:51.527 7750-7801/cn.jzvd.demo I/GLConsumer: [unnamed-7750-0] attachToContext
07-04 10:44:51.534 7750-7794/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-04 10:44:51.544 7750-7794/cn.jzvd.demo D/MediaPlayer: Don't notify duration to cn.jzvd.demo!
07-04 10:44:51.544 7750-7794/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
07-04 10:44:51.554 7750-7771/cn.jzvd.demo D/MediaHTTPConnection: disconnect finish
07-04 10:44:51.556 7750-7773/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:51.558 7750-7773/cn.jzvd.demo I/System.out: open:http://ar.video.1scrn.cn/syt2.mp4
07-04 10:44:51.559 7750-7773/cn.jzvd.demo I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
07-04 10:44:51.559 7750-7773/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:51.560 7750-7773/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
07-04 10:44:51.586 7750-7773/cn.jzvd.demo D/libc-netbsd: getaddrinfo: ar.video.1scrn.cn get result from proxy >>
07-04 10:44:51.587 7750-7773/cn.jzvd.demo I/System.out: [CDS]rx timeout:60000
07-04 10:44:51.587 7750-7773/cn.jzvd.demo I/System.out: [socket][1] connection ar.video.1scrn.cn/183.2.192.189:80;LocalPort=52653(0)
07-04 10:44:51.587 7750-7773/cn.jzvd.demo I/System.out: [CDS]connect[ar.video.1scrn.cn/183.2.192.189:80] tm:90
07-04 10:44:51.588 7750-7773/cn.jzvd.demo D/Posix: [Posix_connect Debug]Process cn.jzvd.demo :80 
07-04 10:44:51.601 7750-7773/cn.jzvd.demo I/System.out: [socket][/192.168.1.141:52653] connected
07-04 10:44:51.601 7750-7773/cn.jzvd.demo I/System.out: [CDS]SO_SND_TIMEOUT:60000
07-04 10:44:51.601 7750-7773/cn.jzvd.demo I/System.out: [OkHttp] sendRequest>>
07-04 10:44:51.602 7750-7773/cn.jzvd.demo I/System.out: [OkHttp] sendRequest<<
07-04 10:44:51.658 7750-7773/cn.jzvd.demo D/MediaHTTPConnection: mTotalSize=18588668
07-04 10:44:52.317 7750-7773/cn.jzvd.demo D/MediaHTTPConnection: teardownConnection
07-04 10:44:52.318 7750-7773/cn.jzvd.demo I/System.out: [CDS]close[52653]
07-04 10:44:52.318 7750-7773/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:52.319 7750-7773/cn.jzvd.demo I/System.out: open:http://ar.video.1scrn.cn/syt2.mp4
07-04 10:44:52.321 7750-7773/cn.jzvd.demo I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
07-04 10:44:52.321 7750-7773/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:52.321 7750-7773/cn.jzvd.demo I/System.out: [CDS]rx timeout:60000
07-04 10:44:52.322 7750-7773/cn.jzvd.demo I/System.out: [socket][2] connection ar.video.1scrn.cn/183.2.192.189:80;LocalPort=58285(0)
07-04 10:44:52.322 7750-7773/cn.jzvd.demo I/System.out: [CDS]connect[ar.video.1scrn.cn/183.2.192.189:80] tm:90
07-04 10:44:52.322 7750-7773/cn.jzvd.demo D/Posix: [Posix_connect Debug]Process cn.jzvd.demo :80 
07-04 10:44:52.524 7750-7773/cn.jzvd.demo I/System.out: [socket][/192.168.1.141:58285] connected
07-04 10:44:52.524 7750-7773/cn.jzvd.demo I/System.out: [CDS]SO_SND_TIMEOUT:60000
07-04 10:44:52.524 7750-7773/cn.jzvd.demo I/System.out: [OkHttp] sendRequest>>
07-04 10:44:52.525 7750-7773/cn.jzvd.demo I/System.out: [OkHttp] sendRequest<<
07-04 10:44:52.915 7750-7856/cn.jzvd.demo I/System.out: Close in OkHttp
07-04 10:44:52.915 7750-7856/cn.jzvd.demo I/System.out: [CDS]close[58285]
07-04 10:44:52.968 7750-7794/cn.jzvd.demo D/MediaPlayer: handleMessage msg:(5, 2160, 3840)
07-04 10:44:52.968 7750-7794/cn.jzvd.demo D/MediaPlayer: handleMessage msg:(3, 100, 0)
07-04 10:44:52.968 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onVideoSizeChanged  [967620237] 
07-04 10:44:52.968 7750-7794/cn.jzvd.demo D/MediaPlayer: handleMessage msg:(1, 0, 0)
07-04 10:44:52.968 7750-7794/cn.jzvd.demo E/MediaPlayer: Should have subtitle controller already set
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [19462033] 
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 600]
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: onMeasure  [19462033] 
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1080]
07-04 10:44:52.977 7750-7750/cn.jzvd.demo I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 600]
07-04 10:44:52.982 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 100, max = 100, backtrace = cn.jzvd.JZVideoPlayer.setBufferProgress:893 cn.jzvd.JZVideoPlayerStandard.setBufferProgress:481 cn.jzvd.JZMediaSystem$3.run:126 android.os.Handler.handleCallback:815 android.os.Handler.dispatchMessage:104 , this = android.support.v7.widget.AppCompatSeekBar{3bbeecb VFED.... ......ID 148,28-816,121 #7f0b0090 app:id/bottom_seek_progress}
07-04 10:44:52.982 7750-7750/cn.jzvd.demo D/ProgressBar: setSecondaryProgress, old = 0, new = 100, max = 100, backtrace = cn.jzvd.JZVideoPlayerStandard.setBufferProgress:482 cn.jzvd.JZMediaSystem$3.run:126 android.os.Handler.handleCallback:815 android.os.Handler.dispatchMessage:104 android.os.Looper.loop:210 , this = android.widget.ProgressBar{1acf3aec I.ED.... ......I. 0,595-1080,600 #7f0b0093 app:id/bottom_progress}
07-04 10:44:53.017 7750-7771/cn.jzvd.demo D/MediaHTTPConnection: teardownConnection
07-04 10:44:53.017 7750-7771/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:53.018 7750-7771/cn.jzvd.demo I/System.out: open:http://ar.video.1scrn.cn/syt2.mp4
07-04 10:44:53.019 7750-7771/cn.jzvd.demo I/System.out: [CDS][DNS] getAllByNameImpl netId = 0
07-04 10:44:53.019 7750-7771/cn.jzvd.demo D/libc-netbsd: [getaddrinfo]: mtk hostname=ar.video.1scrn.cn; servname=(null); cache_mode=(null), netid=0; mark=0; app_uid=10096; ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
07-04 10:44:53.020 7750-7771/cn.jzvd.demo I/System.out: [CDS]rx timeout:60000
07-04 10:44:53.020 7750-7771/cn.jzvd.demo I/System.out: [socket][3] connection ar.video.1scrn.cn/183.2.192.189:80;LocalPort=50327(0)
07-04 10:44:53.020 7750-7771/cn.jzvd.demo I/System.out: [CDS]connect[ar.video.1scrn.cn/183.2.192.189:80] tm:90
07-04 10:44:53.021 7750-7771/cn.jzvd.demo D/Posix: [Posix_connect Debug]Process cn.jzvd.demo :80 
07-04 10:44:53.029 7750-7771/cn.jzvd.demo I/System.out: [socket][/192.168.1.141:50327] connected
07-04 10:44:53.029 7750-7771/cn.jzvd.demo I/System.out: [CDS]SO_SND_TIMEOUT:60000
07-04 10:44:53.029 7750-7771/cn.jzvd.demo I/System.out: [OkHttp] sendRequest>>
07-04 10:44:53.031 7750-7771/cn.jzvd.demo I/System.out: [OkHttp] sendRequest<<
07-04 10:44:53.753 7750-7856/cn.jzvd.demo E/MediaPlayer: error (1, -2147479551)
07-04 10:44:53.753 7750-7794/cn.jzvd.demo D/MediaPlayer: handleMessage msg:(100, 1, -2147479551)
07-04 10:44:53.753 7750-7794/cn.jzvd.demo E/MediaPlayer: Error (1,-2147479551)
07-04 10:44:53.754 7750-7750/cn.jzvd.demo E/JiaoZiVideoPlayer: onError 1 - -2147479551 [967620237] 
07-04 10:44:53.755 7750-7750/cn.jzvd.demo I/JiaoZiVideoPlayer: onStateError  [967620237] 
07-04 10:44:53.756 7750-7794/cn.jzvd.demo D/MediaHTTPConnection: teardownConnection
07-04 10:44:53.756 7750-7794/cn.jzvd.demo I/System.out: [CDS]close[50327]
07-04 10:44:53.757 7750-7794/cn.jzvd.demo D/MediaHTTPConnection: disconnect finish

**Comment by lipangit** [comment]
网络有问题
