### ISSUE TITLE
播放错误那个UI 怎么自定义

### ISSUE THREAD

**Issue by yezhengdong520** [lipangit/JiaoZiVideoPlayer#1985]

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard，复写onStateError函数取得error状态，然后自定义error的ui

**Comment by yezhengdong520** [comment]
为什么我用手机流量不能播放视频，而wifi才可以视频播放啊，是哪里需要设置吗

**Comment by yezhengdong520** [comment]
用手机流量视频不能播放，但是wifi可以播放视频
