### ISSUE TITLE
Video dynamic height issue

### ISSUE THREAD

**Issue by koushik16github** [lipangit/JiaoZiVideoPlayer#1987]
How I can set dynamic video height, please help. Don't want fixed height.

**Comment by koushik16github** [comment]
I want to resize the video height in recyclerview, how is it possible?

**Comment by lipangit** [comment]
the controller height  or the videoImage height?

**Comment by koushik16github** [comment]
no I mean to say JZVideoPlayerStandard height, which is fixed 200dp

**Comment by koushik16github** [comment]
yes its in xml height 200dp, but I want to set wrap content, and height will be set as per video height.

**Comment by lipangit** [comment]
screenshort show me the effect.

**Comment by koushik16github** [comment]
![screenshot_20180707-120713](https://user-images.githubusercontent.com/17313492/42407765-3861f9f8-81df-11e8-814e-be53e652aa01.png)
![screenshot_20180707-121301](https://user-images.githubusercontent.com/17313492/42407766-38989f26-81df-11e8-8613-a855f9120101.png)

Right now the video height is 250dp, 1st video is in landscape, so its showing black strip top and bottom. 2nd video is in portrait, so its showing black strip on left and right side. but I want to show the as per the video height, no black strip no fixed height, no crop or fill parent screen, like as facebook, so is it possible?

**Comment by lipangit** [comment]
You can calculate the controller height and set the height in the code.

**Comment by lipangit** [comment]
You should try , Demo do not have the feature.

**Comment by animeshchat** [comment]
@koushik16github @lipangit - 
I also want to set the height of the video height dynamically instead of hardcoding to 250dp in xml. Did you find a solution for this?

**Comment by lipangit** [comment]
In XML height=wrapcontent. set the height  in your code.------------------ 原始邮件 ------------------
发件人: "animeshchat"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 晚上10:29
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>;
抄送: "Nathen"<1066666651@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [lipangit/JiaoZiVideoPlayer] Video dynamic height issue (#1987)



@koushik16github @lipangit -
 I also want to set the height of the video height dynamically instead of hardcoding to 250dp in xml. Did you find a solution for this?
 
&mdash;

**Comment by dyutibarma** [comment]
@lipangit - The video player (and thumbnail) heights and widths cannot be reassigned in code. Only the height/width ratios can be edited.
Can you please give me an example of how to do this?

thank you for your response.

**Comment by animeshchat** [comment]
@lipangit - The video player (and thumbnail) heights and widths cannot be reassigned in code. Only the height/width ratios can be edited.
Can you please give me an example of how to do this?

thank you for your response

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/57767523-28eeea00-773c-11e9-9e3d-355de3e07a0b.png)

**Comment by animeshchat** [comment]
@lipangit - thank you so much.
This solution assumes that I have the height of the video. Since the video is not downloaded, I do not know the height.  
Is there anything I can do if I do not know the height of the video in advance?

**Comment by lipangit** [comment]
Server get the video height, and give you.

**Comment by animeshchat** [comment]
ok, thank you so much for your help.
