### ISSUE TITLE
在刚初始化的时候调用release()方法会有个空指针

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#1991]
`public void release() {
        if(JZUtils.getCurrentFromDataSource(dataSourceObjects,currentUrlMapIndex).equals(JZMediaManager.getCurrentDataSource()) &&
                (System.currentTimeMillis() - CLICK_QUIT_FULLSCREEN_TIME) > FULL_SCREEN_NORMAL_DELAY) {
            //在非全屏的情况下只能backPress()
            if (JZVideoPlayerManager.getSecondFloor() != null &&
                    JZVideoPlayerManager.getSecondFloor().currentScreen == SCREEN_WINDOW_FULLSCREEN) {//点击全屏
            } else if (JZVideoPlayerManager.getSecondFloor() == null && JZVideoPlayerManager.getFirstFloor() != null &&
                    JZVideoPlayerManager.getFirstFloor().currentScreen == SCREEN_WINDOW_FULLSCREEN) {//直接全屏
            } else {
                Log.d(TAG, "releaseMediaPlayer [" + this.hashCode() + "]");
                releaseAllVideos();
            }
        }
    }`

在未设置播放数据源时候 调用release() 这句代码会有空指针的情况 
`JZUtils.getCurrentFromDataSource(dataSourceObjects, currentUrlMapIndex)`
UncaughtException detected: java.lang.NullPointerException: Attempt to read from null array

**Comment by lipangit** [comment]
调用JZVideoPlayer.releaseAllVideos()
