### ISSUE TITLE
在RecyclerVIew里嵌套JiaoziVideoPlayer，滑动到不可见位置，声音依然有，而且滑回来之后不受控制。

### ISSUE THREAD

**Issue by wangzixu5678** [lipangit/JiaoZiVideoPlayer#1995]
在RecyclerVIew里嵌套JiaoziVideoPlayer，滑动到不可见位置，声音依然有，而且滑回来之后不受控制。
点击暂停也没有效果~~请大佬指示~~

/**
 * Created by wzx on 2018/4/24.  
 */
********************自定义阿里云播放引擎****************************

public class JZMediaAliyun extends JZMediaInterface implements IAliyunVodPlayer.OnPreparedListener, IAliyunVodPlayer.OnErrorListener, IAliyunVodPlayer.OnCompletionListener, IAliyunVodPlayer.OnBufferingUpdateListener, IAliyunVodPlayer.OnSeekCompleteListener, IAliyunVodPlayer.OnVideoSizeChangedListener, IAliyunVodPlayer.OnInfoListener {
    private AliyunVodPlayer mAliyunVodPlayer;
    private Context mContext;

    public JZMediaAliyun(Context context) {
        mContext = context;
    }

    @Override
    public void start() {
        if (mAliyunVodPlayer!=null){
            mAliyunVodPlayer.start();
        }
    }

    @Override
    public void prepare() {
        mAliyunVodPlayer = new AliyunVodPlayer(mContext);
        mAliyunVodPlayer.setOnPreparedListener(this);
        mAliyunVodPlayer.setOnErrorListener(this);
        mAliyunVodPlayer.setOnCompletionListener(this);
        mAliyunVodPlayer.setOnBufferingUpdateListener(this);
        mAliyunVodPlayer.setOnSeekCompleteListener(this);
        mAliyunVodPlayer.setOnVideoSizeChangedListener(this);
        mAliyunVodPlayer.setOnInfoListener(this);
        mAliyunVodPlayer.enableNativeLog();

        /**
         *  0  AccessKeyId
         *  1  AccessKeySecret
         *  2  Expiration
         *  3  SecurityToken
         *  4  VideoId
         */
        String[] split = currentDataSource.toString().split(",");
        AliyunVidSts mVidSts = new AliyunVidSts();
        mVidSts.setAcId(split[0]);
        mVidSts.setAkSceret(split[1]);
        mVidSts.setSecurityToken(split[2]);
        mVidSts.setVid(split[3]);
        mAliyunVodPlayer.prepareAsync(mVidSts);
    }

    @Override
    public void pause() {
        if (mAliyunVodPlayer!=null){
            mAliyunVodPlayer.pause();
        }
    }

    @Override
    public boolean isPlaying() {
        return mAliyunVodPlayer.isPlaying();
    }

    @Override
    public void seekTo(long time) {
        mAliyunVodPlayer.seekTo((int) time);
    }

    @Override
    public void release() {
        if (mAliyunVodPlayer != null)
            mAliyunVodPlayer.release();
    }

    @Override
    public long getCurrentPosition() {
        if (mAliyunVodPlayer != null) {
            return mAliyunVodPlayer.getCurrentPosition();
        } else {
            return 0;
        }

    }

    @Override
    public long getDuration() {
        if (mAliyunVodPlayer!=null){
            return mAliyunVodPlayer.getDuration();
        }else{
            return 0;
        }

    }

    @Override
    public void setSurface(Surface surface) {
        mAliyunVodPlayer.setSurface(surface);
    }

    @Override
    public void setVolume(float leftVolume, float rightVolume) {
        mAliyunVodPlayer.setVolume((int) leftVolume);

    }

    @Override
    public void onPrepared() {
        mAliyunVodPlayer.start();
        if (currentDataSource.toString().toLowerCase().contains("mp3")) {
            JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
                @Override
                public void run() {
                    if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                        JZVideoPlayerManager.getCurrentJzvd().onPrepared();
                    }
                }
            });
        }
    }

    @Override
    public void onError(final int i, final int i1, String s) {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onError(i, i1);

                }
            }
        });
    }

    @Override
    public void onCompletion() {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onAutoCompletion();
                }
            }
        });
    }

    @Override
    public void onBufferingUpdate(final int i) {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().setBufferProgress(i);
                }
            }
        });
    }

    @Override
    public void onSeekComplete() {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onSeekComplete();
                }
            }
        });
    }

    @Override
    public void onVideoSizeChanged(int i, int i1) {
        JZMediaManager.instance().currentVideoWidth = i;
        JZMediaManager.instance().currentVideoHeight = i1;
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onVideoSizeChanged();
                }
            }
        });
    }

    @Override
    public void onInfo(final int i, final int i1) {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    if (i == MediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) {
                        JZVideoPlayerManager.getCurrentJzvd().onPrepared();
                    } else {
                        JZVideoPlayerManager.getCurrentJzvd().onInfo(i, i1);
                    }
                }
            }
        });
    }
}

Recyclerview监听
************************************************************************
mFmHomeRv.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
                JZVideoPlayer.onChildViewAttachedToWindow(view,R.id.video_play);
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer.onChildViewDetachedFromWindow(view);
            }
        });

*****************************RecyclerAdapter里的内容*****************************
 case MultipleItem.TYPE6:
                MyJZVideoPlayerStandard videoPlayer = (MyJZVideoPlayerStandard) helper.getView(R.id.video_play);

                StartBean startBean = item.getStartBean();
                if (startBean == null) {
                    return;
                }
                VideoSTSBean videoSTSBean = item.getVideoSTSBean();
                if (videoSTSBean == null) {
                    return;
                }
                String videoUrl = getVideoUrl(videoSTSBean, startBean.getAdMessage().getAdInfo());
                JZVideoPlayer.setMediaInterface(new JZMediaAliyun(mContext));
                Glide.with(mContext).load(startBean.getAdMessage().getVideoCoverUrl()).into                    (videoPlayer.thumbImageView);
                videoPlayer.setUp(videoUrl, MyJZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "");

**Comment by xiaoanzi** [comment]
RecyclerVIew 的 item 被回收了，自己可以处理一下。

**Comment by lipangit** [comment]
列表滑动的问题和这个没关系，和item回收有关系，是不是新版的lib吗@wangzixu5678
