### ISSUE TITLE
升级后无法播放

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#1996]
遇到个问题 项目之前使用的是5.5.4版本，只要升级到高于此版本 ，以前的列表里面视频就无法播放点击后一直转圈，日志如下：
I/JieCaoVideoPlayer: onStateNormal  [19791457] 
 I/JieCaoVideoPlayer: onCompletion  [212941020] 
 I/JieCaoVideoPlayer: onStateNormal  [212941020] 
 D/JieCaoVideoPlayer: startVideo [154177891] 
    addTextureView [154177891] 
 I/JieCaoVideoPlayer: onStatePreparing  [154177891] 

开启了硬件加速也不行。

在5.5.4的基础上继承JCVideoPlayerStandard 想自定义自己的UI 结果 在inflate的时候一直重复循环调用 init()方法 导致卡死：

`public class CustomUIJCPlayer extends JCVideoPlayerStandard {
    
    public CustomUIJCPlayer(Context context) {
        super(context);
    }

    public CustomUIJCPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public int getLayoutId() {
        return R.layout.layout_kingv_videoplay;
    }

    @Override
    public void init(Context context) {
        super.init(context);
    }

    @Override
    public boolean onTouch(View v, MotionEvent event) {
        return super.onTouch(v, event);
    }

    @Override
    public void startVideo() {
        super.startVideo();
    }

    @Override
    public void onInfo(int what, int extra) {
        super.onInfo(what, extra);
    }

    @Override
    public void onError(int what, int extra) {
        super.onError(what, extra);
    }

    @Override
    public void startWindowFullscreen() {
        super.startWindowFullscreen();
    }

    @Override
    public void startWindowTiny() {
        super.startWindowTiny();
    }
}
`

**Comment by lipangit** [comment]
么么哒
