### ISSUE TITLE
I LOST QUALITY VIDEO WITH MY OWN 4G  

### ISSUE THREAD

**Issue by gianpaul** [lipangit/JiaoZiVideoPlayer#1997]
hi, thanks for jiaozivideo is the best player!

now i have a problem : 

I have this video http://69.197.138.190/db/dbs/Dbs-01.mp4 

when I play the video with wifi it's all right, now when I play the video with my 4g internet, the quality goes down, could you help me?

its code i use : 
String url = "http://69.197.138.190/db/dbs/Dbs-01.mp4 ";
final JZVideoPlayerStandard jzVideoPlayerStandard = (JZVideoPlayerStandard) findViewById(R.id.videoplayer);
        jzVideoPlayerStandard.setUp(URL, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL);

**Comment by lipangit** [comment]
"the quality goes down"  what is it mean?

**Comment by lipangit** [comment]
your code is right

**Comment by gianpaul** [comment]
when I use the wifi, I see the quality of the normal video, but when I use the 4g of my cellular internet service the quality automatically the quality of the video goes down I do not know why this happens

**Comment by lipangit** [comment]
Illogical, show me the screenshort
