### ISSUE TITLE
Resume video  specific seconds

### ISSUE THREAD

**Issue by lucazin** [lipangit/JiaoZiVideoPlayer#2000]
Hi!  i pause the video em 34 seconds.. 
when i back to activity i would resume in the same 34 seconds not restart the video..

how can i do that ?
thanks!!!

**Comment by lipangit** [comment]
use new version,It can resume in the same 34 seconds.

**Comment by lucazin** [comment]
Thanks i got it!

**Comment by lipangit** [comment]
good

**Comment by Saeed-Pooyanfar** [comment]
@lipangit Hi, i don't like this feature, how can i disable it?

**Comment by lipangit** [comment]
Jzvd.save_progress=false
