### ISSUE TITLE
Resolution selection (HLS Video)

### ISSUE THREAD

**Issue by ahmadarif** [lipangit/JiaoZiVideoPlayer#2002]
How to add option for select the video resolution like youtube player?

**Comment by lipangit** [comment]
show me the screenshort, what effect

**Comment by ahmadarif** [comment]
I want to play m3u8 video with many resolution using this library, is this lib automate show the video resolution list in the player?
Like this library (Angular Lib for video player) https://videogular.github.io/videogular2/

**Comment by lipangit** [comment]
I can not unstardand your need.

Can you show me the screenshort?

**Comment by ROYALRandhawa** [comment]
I also have same query, here is screenshot of what I need
![screenshot_7](https://user-images.githubusercontent.com/33171648/43798926-a4872c6a-9aa9-11e8-9548-5f534270a168.png)

I have different urls for all qualities but how I merge them for showing in one player
Example:
SD = "http:// ......SD quality url......."
HD = "http://......HD quality url......."
FHD = "http://......FHD quality url......."

how I add them all in one player and show a quality selector and if someone switch quality, player start buffering from respective url
LIKE: If currently player is playing "SD" video and then I click on "HD" then player starts loading "HD video url" from same _SEEK POSITION_

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43816868-65882284-9b09-11e8-909a-e6136fb78bc2.png)

see apiacapiactivity in demo, Does it meet your requirements?

**Comment by ROYALRandhawa** [comment]
thanks, this is exactly what I want
But a little query more, I want this Quality Selector to show in **SCREEN_WINDOW_NORMAL** also.... for now it is only visible when Player switch to **SCREEN_WINDOW_FULLSCREEN**

 I want to show this in **SCREEN_WINDOW_NORMAL** also

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43903752-aef6ba86-9c1f-11e8-9c32-6ca00fdce4ff.png)


try to shield the logic

**Comment by ROYALRandhawa** [comment]
thanks for your help

**Comment by MohammadB72** [comment]
> ![image](https://user-images.githubusercontent.com/2038071/43816868-65882284-9b09-11e8-909a-e6136fb78bc2.png)
> 
> see apiacapiactivity in demo, Does it meet your requirements?

where is it? i can't find it in demo :(

**Comment by MohammadB72** [comment]
> ![image](https://user-images.githubusercontent.com/2038071/43816868-65882284-9b09-11e8-909a-e6136fb78bc2.png)
> 
> see apiacapiactivity in demo, Does it meet your requirements?

it don't work correctly after changing quality

**Comment by lipangit** [comment]
yes it has bug now

**Comment by anitavaghasiya** [comment]
I want to set multiple of video how to set i don't
Please help me.

**Comment by anitavaghasiya** [comment]
How to set quality of videos like auto,1080,720,like this
Please help me

**Comment by IdleJatt** [comment]
I had made it... quiet easy ::

```
private void setupPlayer() {
        LinkedHashMap map = new LinkedHashMap();
        map.put("240p", "http://__240p__url__");
        map.put("360p", "http://__360p__url__");
        map.put("480p", "http://__480p__url__");

        JZDataSource jzDataSource = new JZDataSource(map, "Title Of Video");
        jzDataSource.looping = true;
        jzDataSource.currentUrlIndex = "2"; // default qualityIndex [2=480p]
        jzDataSource.headerMap.put("key", "value"); //header
        viewPlayer.setUp(jzDataSource
                , JzvdStd.SCREEN_WINDOW_NORMAL);

        Glide.with(this)
                .load("http://__thumbnail__url__")
                .apply(new RequestOptions().placeholder(R.drawable.spinner))
                .into(viewPlayer.thumbImageView);

        mSensorManager = (SensorManager) getSystemService(SENSOR_SERVICE);
        mSensorEventListener = new Jzvd.JZAutoFullscreenListener();

        Jzvd.setVideoImageDisplayType(Jzvd.VIDEO_IMAGE_DISPLAY_TYPE_ORIGINAL);
    }
```
