### ISSUE TITLE
在Fragment中，当视频高度大于宽度的时候，全屏播放会把整个界面旋转

### ISSUE THREAD

**Issue by yuan7016** [lipangit/JiaoZiVideoPlayer#2003]
在Fragment中使用，并参考ActivityApiOrientation做了配置，点击全屏按钮直接横屏播放，当视频宽度大于高度时候播放没问题，但是当视频高度大于宽度的时候，点击全屏会把整个界面旋转（我把jz_layout_standard.xml布局中的根布局中的android:background="@android:color/black" 去掉就可以看到界面上其他控件。加上这个android:background="@android:color/black" 黑色背景后，就看不到了其他控件了。）

**Comment by lipangit** [comment]
全屏的时候的效果和视频的高宽有关系吗？能否截图说明

**Comment by zhiwo** [comment]
我也遇到了就是在Fragment recycleview嵌套中，如果视频全屏缩放回去时就会切换屏幕了

**Comment by lipangit** [comment]
能否录视频阐述发生的情况
