### ISSUE TITLE
有没有人遇到过长时间进行视频轮播，画面会卡住的问题？

### ISSUE THREAD

**Issue by heroDaYo** [lipangit/JiaoZiVideoPlayer#2004]
公司有需求要求多视频24小时轮播，这边写好之后播放几个小时会出现画面卡住的情况，播放的状态卡在onStatePlaying，换了一个设备也有这个现象。Demo里的重复播放不满足需求，没有验证。视频是本地的视频，不是网络上的。

**Comment by lipangit** [comment]
onStatePlaying说明没进入error状态

**Comment by lipangit** [comment]
卡的时候有声音吗

**Comment by heroDaYo** [comment]
没有声音。

**Comment by lipangit** [comment]
视频什么样，可以用ijkplayer试试。

**Comment by lipangit** [comment]
一行代码切换ijkplayer

**Comment by heroDaYo** [comment]
视频就是几段10多秒到1分钟的视频，mp4格式的。我换成ijk跑一下试试

**Comment by lipangit** [comment]
怎么样了
