### ISSUE TITLE
视频放一会儿，卡住不能播放，必须重新进入才能播放

### ISSUE THREAD

**Issue by x58548078** [lipangit/JiaoZiVideoPlayer#2007]
都是比较长的视频会出现这个问题
onInfo what - 804 extra - -1004
或者
onInfo what - 805 extra - -19
 onInfo what - 805 extra - -38

请问该如何解决

**Comment by lipangit** [comment]
可能是系统播放器的缺陷，这是随着安卓系统的版本走的，可能在个别手机上有缺陷。

**Comment by lipangit** [comment]
可以一行代码切换到ijkplayer
