### ISSUE TITLE
8.0无法播放视频，一直转圈。

### ISSUE THREAD

**Issue by hsxiaochou** [lipangit/JiaoZiVideoPlayer#2009]
8.0无法播放视频。一直黑，一直转圈。

**Comment by lipangit** [comment]
log是什么，网络权限加了吗

**Comment by hsxiaochou** [comment]
我直接写了一个demo是没问题的。正常的。但放在项目里就不正常了。看了一下log。执行到JZResizeTextureView: onMeasure，后面就没有sedata等操作了。。不知道原因是什么。。求告知啊。。

**Comment by lipangit** [comment]
对比demo中的代码和readme的集成步骤，对比一下代码的细节。

**Comment by wmpscc** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by lipangit** [comment]
demo会吗

**Comment by wmpscc** [comment]
@lipangit 自己写的demo可以就正常，集成到项目里就一直转圈，现在解决了。感谢 @hsxiaochou ，加了android：hardwareAccelerated="true"正常了

**Comment by lipangit** [comment]
good
