### ISSUE TITLE
Change Message No Url

### ISSUE THREAD

**Issue by lucazin** [lipangit/JiaoZiVideoPlayer#2011]
if (urlMap == null || TextUtils.isEmpty(JZUtils.getCurrentUrlFromMap(urlMap, currentUrlMapIndex))) {
                Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();

how to change this message ? 

override this ?

**Comment by lipangit** [comment]
yes override onClick() function,

**Comment by lipangit** [comment]
or can you create a new R.stirng.no_url to cover R.string.no_url in to your project
