### ISSUE TITLE
我想播放纯音频,界面和播放视频一样就可以了,但是开始播放后还是一直转圈,不显示暂停按钮和进度条,有没有办法设置?

### ISSUE THREAD

**Issue by tangyanghai** [lipangit/JiaoZiVideoPlayer#2013]

**Comment by lipangit** [comment]
参考https://github.com/lipangit/JiaoZiVideoPlayer/blob/develop/app/src/main/java/cn/jzvd/demo/CustomView/JZVideoPlayerStandardMp3.java  develop分支上最新

**Comment by lipangit** [comment]
“ 不显示暂停按钮和进度条”  在它的基础上在各个状态中隐藏控件即可
