### ISSUE TITLE
viewpager+tablayout recycleview点击item播放全屏的时候，竖屏没问题，横屏会报错。自动返回停止播放。

### ISSUE THREAD

**Issue by yuwoquan** [lipangit/JiaoZiVideoPlayer#2014]
报错信息

I/JZResizeTextureView: onMeasure  [26920096] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1920]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1080]
I/JZResizeTextureView: onMeasure  [26920096] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 1920]
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 1080]
I/JiaoZiVideoPlayer: onStateNormal  [30240357] 
D/JiaoZiVideoPlayer: releaseAllVideos
I/JiaoZiVideoPlayer: onCompletion  [81346300] 
I/JiaoZiVideoPlayer: saveProgress: 70620
I/JiaoZiVideoPlayer: onStateNormal  [81346300] 
I/JiaoZiVideoPlayer: onCompletion  [243792905] 
I/JiaoZiVideoPlayer: onStateNormal  [243792905] 
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] cancelBuffer: BufferQueue has been abandoned
I/JiaoZiVideoPlayer: onStateNormal  [215012889] 
I/JiaoZiVideoPlayer: onStateNormal  [152973137] 
E/BufferQueueProducer: [SurfaceTexture-0-14851-0] connect: BufferQueue has been abandoned
D/JiaoZiVideoPlayer: releaseAllVideos
I/art: Do full code cache collection, code=102KB, data=125KB
I/art: After code cache collection, code=78KB, data=82KB

已经在播放的activity设置了
  <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme" />

在adpater写法
  holder.jzVideo.setUp(data.get(position).getVideoUrl(),holder.jzVideo.SCREEN_WINDOW_LIST,"");

测试的手机是小米5S Android 7.0

**Comment by lipangit** [comment]
断点releaseAllVideos，log显示在不应该调用这个的时候调用了releaseAllVideos

**Comment by yuwoquan** [comment]
定位到错误。点击全屏的时候触发了
 /**
     * 监听滚动
     * @param viewHolder
     * @param adapterPosition
     */
    @Override
    public void onCurrentItemChanged(@Nullable DscrollAdapter.ViewHolder viewHolder, int adapterPosition) {
        //viewHolder will never be null, because we never remove items from adapter's list
        if (viewHolder != null) {
            viewHolder.setOverlayColor(currentOverlayColor);
            JZVideoPlayer.releaseAllVideos();
        }
    }

我还是不太了解为什么全屏会触发到itemchanged

**Comment by lipangit** [comment]
别在这里调releaseAllVideos，只要item是正常复用的，lib会自动停掉播放
