### ISSUE TITLE
在demo的recycleview 列表点击播放，红色的底部进度条没有更新；

### ISSUE THREAD

**Issue by easyandroid** [lipangit/JiaoZiVideoPlayer#2015]
![bug1](https://user-images.githubusercontent.com/5576002/43247046-22aeab68-90e6-11e8-8d32-a3c58e4a5499.png)
![bug2](https://user-images.githubusercontent.com/5576002/43247048-23aab23c-90e6-11e8-91f8-9c36f88c0de8.png)
 点击红色框播放（item不是全部可见情况） ，然后滑动绿色框的进度条没有更新。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43263762-c3e5eb38-9116-11e8-8920-5e46ebb1ccb9.png)

断点一下zhe'li这里，看看是否正常工作

**Comment by easyandroid** [comment]
滑动上来的时候 调用了setUp() ->onStateNormal()-->cancelProgressTimer()- mProgressTimerTask.cancel(); canle 线程里面有影响吗？

**Comment by lipangit** [comment]
调用setUp的jzvd是否是当前正在播放的jzvd

**Comment by lipangit** [comment]
如果是，视频会被release，停止播放。如果不是，就没有影响

**Comment by easyandroid** [comment]
onBufferingUpdate 没有调用，调用setup 是recycleview滑动 加载了一个新item。这样就会取消播放进度。当前视频还在播放，没有release。

**Comment by easyandroid** [comment]
目前采用了另外的思路实现`private void initRecycleScroll() {
        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
            }

            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                switch (newState) {
                    case RecyclerView.SCROLL_STATE_IDLE:
                        updateProgress(recyclerView);
                        break;
                    case RecyclerView.SCROLL_STATE_DRAGGING:
                        break;
                    case RecyclerView.SCROLL_STATE_SETTLING:
                        break;
                }
            }
        });
    }

    private void updateProgress(RecyclerView view) {
        RecyclerView.LayoutManager layoutManager = view.getLayoutManager();
        int firstVisibleItem = ((LinearLayoutManager) layoutManager).findFirstVisibleItemPosition();
        int lastVisibleItem = ((LinearLayoutManager) layoutManager).findLastVisibleItemPosition();
        int visibleCount = lastVisibleItem - firstVisibleItem;
        JZVideoPlayerStandard jzVideoPlayerStandard;
        for (int i = 0; i < visibleCount; i++) {
            if (layoutManager.getChildAt(i) != null && layoutManager.getChildAt(i).findViewById(R.id.video_player) != null) {
                jzVideoPlayerStandard = layoutManager.getChildAt(i).findViewById(R.id.video_player);
                if (jzVideoPlayerStandard.currentState == JZVideoPlayerStandard.CURRENT_STATE_PLAYING) {
                    jzVideoPlayerStandard.startProgressTimer();
                    break;
                }
            }
        }
    }` 滚动的时候监听当前可见的区域是否有播放视频，调用 jzVideoPlayerStandard.startProgressTimer();

**Comment by easyandroid** [comment]
`  private void initRecycleScroll() {
        recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
            }

            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                switch (newState) {
                    case RecyclerView.SCROLL_STATE_IDLE:
                        updateProgress(recyclerView);
                        break;
                    case RecyclerView.SCROLL_STATE_DRAGGING:
                        break;
                    case RecyclerView.SCROLL_STATE_SETTLING:
                        break;
                }
            }
        });
    }

    private void updateProgress(RecyclerView view) {
        RecyclerView.LayoutManager layoutManager = view.getLayoutManager();
        int firstVisibleItem = ((LinearLayoutManager) layoutManager).findFirstVisibleItemPosition();
        int lastVisibleItem = ((LinearLayoutManager) layoutManager).findLastVisibleItemPosition();
        int visibleCount = lastVisibleItem - firstVisibleItem;
        JZVideoPlayerStandard jzVideoPlayerStandard;
        for (int i = 0; i < visibleCount; i++) {
            if (layoutManager.getChildAt(i) != null && layoutManager.getChildAt(i).findViewById(R.id.video_player) != null) {
                jzVideoPlayerStandard = layoutManager.getChildAt(i).findViewById(R.id.video_player);
                if (jzVideoPlayerStandard.currentState == JZVideoPlayerStandard.CURRENT_STATE_PLAYING) {
                    jzVideoPlayerStandard.startProgressTimer();
                    break;
                }
            }
        }
    }`

**Comment by lipangit** [comment]
解决了就好，就怕有暗病
