### ISSUE TITLE
切换播放器后，部分视频画面卡住

### ISSUE THREAD

**Issue by shuaimango** [lipangit/JiaoZiVideoPlayer#2016]
用默认播放器实现上下滑动列表视频自动播放（videoPlayerStandard1.startButton.performClick();）没问题；
但因为部分机型的系统播放器适配问题，切换JZVideoPlayer.setMediaInterface(new JZMediaIjkplayer());后，会出现部分视频卡住，不会自动播放。

**Comment by lipangit** [comment]
这个performClick就是手动点击开始对吧，如果卡主的话手点也会卡主，你试试手点是什么效果

**Comment by shuaimango** [comment]
补充一下：视频是直播的播放链接，flv格式。例如http://hdl.moreshowlives.com/live/14642269.flv

**Comment by shuaimango** [comment]
07-27 20:37:13.932 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onClick start [60327539] 
    onStatePause  [60327539] 
    startProgressTimer:  [60327539] 
07-27 20:37:23.464 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onClick start [60327539] 
    onStatePlaying  [60327539] 
    startProgressTimer:  [60327539] 
上面是先点击暂停按钮，再点击播放按钮的日志。然而一直卡住不播放

**Comment by shuaimango** [comment]
貌似第一次滑到时都能正常播放，然后再次滑到这个位置时，重新播放就会卡住。  是原生播放器和ijkplayer的差异引起的，还是JZMediaIjkplayer实现重新播放时的细节没处理好？

**Comment by shuaimango** [comment]
是不是ijkplayer播放引擎seekTo导致的问题，没能继续播放下去

**Comment by shuaimango** [comment]
再次滑到某个视频的日志：07-27 20:59:54.941 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onClick start [53639476] 
07-27 20:59:54.949 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onStatePreparing  [53639476] 
07-27 20:59:54.968 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onSurfaceTextureAvailable [53639476] 
07-27 20:59:55.250 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onVideoSizeChanged  [53639476] 
07-27 20:59:55.250 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onVideoSizeChanged  [53639476] 
07-27 20:59:55.288 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onVideoSizeChanged  [53639476] 
07-27 20:59:55.341 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onVideoSizeChanged  [53639476] 
07-27 20:59:55.350 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onVideoSizeChanged  [53639476] 
    onPrepared  [53639476] 
07-27 20:59:55.351 4573-4573/com.zxd.moxiu.live I/JiaoZiVideoPlayer: onStatePlaying  [53639476] 
    startProgressTimer:  [53639476]

**Comment by lipangit** [comment]
第一次滑到此处用原生播放器引擎，第二次滑到此处用ijkplayer？

**Comment by lipangit** [comment]
明白了，这个问题对于jzvd而言就是开始播放，release的问题，和列表滑动无直接关系。
