### ISSUE TITLE
Video Complete Callback

### ISSUE THREAD

**Issue by pawanpandey17** [lipangit/JiaoZiVideoPlayer#2020]
Is there any callback for completion of video playback.

**Comment by lipangit** [comment]
Extends JZVideoPlayerStandard 
Override 
public void onAutoComplete(){
}

**Comment by deryfath** [comment]
I have been extends JZVideoPlayerStandard in my code, but I cant find onAutoComplete function implementation, Is there any function what I miss to implement in my class activity?
Thank you so much

**Comment by pawanpandey17** [comment]
Extends JZVideoPlayerStandard
Override
public void onAutoComplete(){
}

**Comment by deryfath** [comment]
already extend but not found onAutoComplete
![untitled](https://user-images.githubusercontent.com/22788667/43872475-0a744c76-9bac-11e8-9551-dea531c22074.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43903568-544a912a-9c1f-11e8-875a-d2592206c9cf.png)
