### ISSUE TITLE
关于全屏的问题。

### ISSUE THREAD

**Issue by yuwoquan** [lipangit/JiaoZiVideoPlayer#2022]
recycleview的item点击全屏后。点击返回按钮。不是回到item播放。但仍在不可见状态下播放着。仅仅有声音，但是item的播放器显示未播放状态。
打印消息仅有
07-30 16:58:22.414 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: backPress
07-30 16:58:22.414 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: playOnThisJzvd  [120614816] 
07-30 16:58:22.419 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: onStatePlaying  [120614816] 
07-30 16:58:22.419 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: startProgressTimer:  [120614816] 
07-30 16:58:22.420 12025-12025/com.example.westernjourney D/JiaoZiVideoPlayer: addTextureView [120614816] 
07-30 16:58:22.460 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: onStateNormal  [77378436] 
07-30 16:58:22.491 12025-12025/com.example.westernjourney I/JiaoZiVideoPlayer: onStateNormal  [178581276]

**Comment by lipangit** [comment]
什么库版本
