### ISSUE TITLE
首页点击全屏后，底部返回按钮冲突

### ISSUE THREAD

**Issue by zht392204992** [lipangit/JiaoZiVideoPlayer#2023]
首页fragment可以正常播放视频，点击全屏按钮时，由于我MainActivity中onkeydown 会判断再次点击返回桌面，此时我再点击底部返回按键时，会调用onkeydown返回桌面，而不是关闭当前全屏页面回到首页。全屏时顶部返回键可以正常返回

**Comment by lipangit** [comment]
可以继承JZVideoPlayerStandard，复写onClick和onTouch函数，屏蔽某些库里的操作
