### ISSUE TITLE
怎么播放raw里面的MP4

### ISSUE THREAD

**Issue by o199666** [lipangit/JiaoZiVideoPlayer#2024]

**Comment by XJX-yb** [comment]
> demo有例子，就是怼url哪个url的问题

能说的清楚点吗?

**Comment by XJX-yb** [comment]
> 兄弟，先把demo的各个界面和各个按钮都点一次，这过分吗，会看到一个播放MP3的例子。

没问题 只是你这个‘怼url哪个url’没看清而已
