### ISSUE TITLE
视频播放完毕UI重写问题

### ISSUE THREAD

**Issue by 912189652** [lipangit/JiaoZiVideoPlayer#2025]
依赖的饺子库，能否重写JZVideoPlayerStandard.updateStartImage()中CURRENT_STATE_AUTO_COMPLETE的UI方式，不显示重播按钮，直接显示如刚加载时的播放按钮。

**Comment by 912189652** [comment]
感谢大神，仔细看自定义UI重写方法就可以很方便，另外还有个问题，红米手机还有1+5T手机会出现播放到中间出现加载失败的情况，请问有这样的问题吗

**Comment by lipangit** [comment]
这是和播放器引擎有关系，新建一个项目单纯用MediaPlayer和Textureview试试会不会中途失败

**Comment by 912189652** [comment]
使用JZdemo测试，MediaPlayer测试都会在同样的地方出现无法播放，1+5T手机必现，其他手机很顺畅，同样的资源

**Comment by 912189652** [comment]
把服务器上的mp4格式换成名m3u8就可以了

**Comment by lipangit** [comment]
这个。。播放器引擎的问题
