### ISSUE TITLE
Setup with content URI "content://..."

### ISSUE THREAD

**Issue by VitaliyShuba** [lipangit/JiaoZiVideoPlayer#2027]
Hello. I am really sorry, maybe I am duplicating old issues.
I am using **JZVideoPlayerStandard** with default setUp:

```java
    mVideoPlayer.setUp(videoUrl, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, name != null ?name : "");
    mVideoPlayer.startButton.performClick();
```
I want use this player with Android **content uri** like "content://..." but it is not working. Can't find something about this in wiki.
I will appreciate any help with this.

Again sorry for duplicating.

**Comment by lipangit** [comment]
check android.media.MediaPlayer api， I put the uri into android.mediaMediaPlayer
