### ISSUE TITLE
全局播放

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2028]
假如有个这样的需求，在页面A 播放一个音频， 退出页面A 继续播放音频，不调用ReleaseAllVideo()可以实现，有没有可能再次进入页面A 继续播放这个音频。也就是说可以拿到还在播放的那个player对象设置给页面A的player对象吗？我的意思就像 windowtiny 播放时候一样的无缝切换效果。而不是从新setup（）。

**Comment by yilylong** [comment]
更正下 是其他地方调用了ReleaseAllVideo()，导致的播放暂停。这样做是可以续播的

**Comment by lipangit** [comment]
首先ReleaseAllVideo表示已经把所有资源全部release了，只能重新加载。如果说续播的话，库本身可以记录播放器的位置

**Comment by yilylong** [comment]
恩，明白 库本身可以记录音视频进度 然后续保。我的意思是退出后继续在后台播放，进入A页面再恢复之前的UI状态。目前按照上面做法已经实现。

**Comment by lipangit** [comment]
ok，解决就好

**Comment by yilylong** [comment]
请问下 无缝衔接的问题。按照我上面的需求，将player不释放保存起来。重新进入页面后拿到player再通过addView（player）的方式添加到界面上。这样可以实现无缝衔接的播放，因为本质是同一个player对象没有变化也没有停止播放。但是这样会导致出现一些其他问题：
1、点击全屏无效，UI变成显示封面的停止状态，但实际在继续播放。
2、小窗windowTiny无效

我看全屏和小窗貌似也是 新建了一个player对象,拿到当前的资源和状态设置给新建的player然后添加到界面。如下代码开启全屏


` jzVideoPlayer.setUp(dataSourceObjects, currentUrlMapIndex, 

            JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, objects);

            jzVideoPlayer.setState(currentState);

            jzVideoPlayer.addTextureView();

            JZVideoPlayerManager.setSecondFloor(jzVideoPlayer);

            JZUtils.setRequestedOrientation(getContext(), FULLSCREEN_ORIENTATION);
            onStateNormal();
            jzVideoPlayer.progressBar.setSecondaryProgress(progressBar.getSecondaryProgress());
            jzVideoPlayer.startProgressTimer();
            CLICK_QUIT_FULLSCREEN_TIME = System.currentTimeMillis();`

这样就实现了无缝衔接的播放。有两个问题：
1、这里是怎么停止前面那个player的播放的呢？
2、然后并没有调用播放的方法是怎么开始衔接播放的呢？ 

我是否能借鉴这种方式解决我的问题呢？

**Comment by yilylong** [comment]
貌似找到原因了：首次进入页面A 创建的player保存下来，第二次进去A页面复用。player里面的context对象还是第一次创建时候的context。跟后面进入页面后的Activity不是同一个对象。导致在全屏和小窗等方面出现问题。
解决方法：
在页面复写startWindowFullscreen（）方法这样创建全屏的播放器就在当前页面下了。
在退出全屏的时候还有问题，JZplayer 里面的clearFloatScreen（）里面因为context对象还是第一次的context对象，所以找不到secondplayer就没有remove掉，返回竖窗播放时候调用addTextTureView() 会导致重复添加错误
所以要结合自己的业务想办法在调用 backpress（）方法前，调用clearFloatScreen（），而且这个方法也要在页面复写；
