### ISSUE TITLE
fullscreen button

### ISSUE THREAD

**Issue by unosbaghaie** [lipangit/JiaoZiVideoPlayer#2030]
hey

in portrait activity fullscreen button does't appear. but when touching the right bottom corner of player it gets fullscreen

any help to show it ?

**Comment by lipangit** [comment]
fullscreen button always show, did you change the source code. or screenshort

**Comment by unosbaghaie** [comment]
No, I didn't change source code.  there is  no fullscreen button but when I click there it got fullscreen. 

![screenshot1](https://user-images.githubusercontent.com/14114058/43632243-c92f6e20-971a-11e8-9331-c7e3b86db5c3.png)

**Comment by lipangit** [comment]
The effect is wrong, please follow the readme and MainActivity in demo

**Comment by lipangit** [comment]
usage is wrong

**Comment by unosbaghaie** [comment]
I couldn't find demo source code. Could you share its link here?
