### ISSUE TITLE
播放点击事件

### ISSUE THREAD

**Issue by ZhySir** [lipangit/JiaoZiVideoPlayer#2031]
recyclerview列表页 每个item都是播放器 + 1个布局
我想问下关于播放点击事件 点击播放怎么隐藏这个布局
我继承了JZVideoPlayerStandard 重写了onClick事件 然后如何去处理?

**Comment by Wing-Li** [comment]
没看懂描述

**Comment by lipangit** [comment]
首先要把这个布局放到播放器的布局里，让它成为播放器的一部分。
在继承的JZVideoPlayerStandard中findVIewById到这个布局，然后在onClick中隐藏它。
