### ISSUE TITLE
循环播放怎么设置.mediaPlayer.setLooping((boolean) dataSourceObjects[1]); =true了,不好使

### ISSUE THREAD

**Issue by majunm** [lipangit/JiaoZiVideoPlayer#2032]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
看新版本的demo，在ApiActivity里

**Comment by qinchaia** [comment]
@lipangit  同样的问题，使用的最新的6.2.12版本，大佬求助啊
`LinkedHashMap map = new LinkedHashMap();
 map.put(JZVideoPlayer.URL_KEY_DEFAULT, Api.HOST+videoSource);
Object[] objects = new Object[2];
objects[0] = map;
objects[1] = true;
jcvideo.setUp(objects, 0, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, "");`

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43772420-9abc30b6-9a74-11e8-81b3-cbf4f120ed5b.png)

这个设置之后不好使吗

**Comment by qinchaia** [comment]
@lipangit 不起作用啊大神，照着ActivityApi里面的写法设置的，播放完之后就出现了重播的按钮，没能循环播放。
只有这一个设置  是否循环播放的地方吗？还需要设置其他地方吗？

**Comment by lipangit** [comment]
兄得，亲测管用啊，demo中刚测

**Comment by qinchaia** [comment]
@lipangit 请问手机型号和系统会有影响吗？能加QQ请教下吗大神？

**Comment by lipangit** [comment]
可以加qq。你直接运行demo试试

**Comment by qinchaia** [comment]
@lipangit  好像是手机系统的问题，同样的代码，在魅族3S、魅族4Pro、三星note4、小米6上面都可以正常循环播放，但是华为荣耀7上面不行，这下尴尬了；；；求助啊大神

**Comment by lipangit** [comment]
修改播放器引擎超出老臣解决范围，可以切换播放器引擎

**Comment by lipangit** [comment]
good
