### ISSUE TITLE
在列表播放的时候退出不返回列表播放直接   JZVideoPlayer.releaseAllVideos()没反应

### ISSUE THREAD

**Issue by yuwoquan** [lipangit/JiaoZiVideoPlayer#2036]
JZVideoPlayerStandard.setJzUserAction(new JZUserAction() {
                @Override
                public void onEvent(int type, Object url, int screen, Object... objects) {
                    if (type==8){
                        JZVideoPlayer.releaseAllVideos();
                    }
                }
            });
我执行下列这段代码不能释放到视频。请问是我操作的方法不对吗

**Comment by lipangit** [comment]
setJzUserAction 专门为埋点数据统计用的，其他逻辑不能写到这里。

在列表播放的时候退出不返回列表播放  这句话什么意思 ，可以截图或者小视频说明
