### ISSUE TITLE
全屏状态下如何播放下一个

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2038]
**需求描述
全屏状态下怎么播放下一个视屏。
看到有几个issues都有提到，可是好像都没有具体的解决办法。
已经重写了onAutoCompletion（）方法，屏蔽了全屏播放结束后退出全屏，然后在
onStateAutoComplete（）方法里面调用setUp()方法设置了数据，再调用startButton.peformClick()方法触发播放，可是一触发就退出了全屏。
还有一个是监听wifi的断开和连接，现在是在activity里面监听，写的地方比较分散，想看看您这边有什么好的建议。

**Comment by lipangit** [comment]
播放下一集参考demo的apiActivity中切换清晰度的函数，全屏可以用。

能把监听wifi的代码截图发来看看，看看放在哪好。

**Comment by zzh12138** [comment]
![qq 20180808095033](https://user-images.githubusercontent.com/16078807/43811715-83500c5a-9af0-11e8-8028-cf8293e93db8.png)
这里因为链接跟断开链接会触发多次，所以加了个标志位去判断

**Comment by lipangit** [comment]
监听的话如果做会做一个全局函数，在activity中注册广播，这个在View中没法注册。

**Comment by zzh12138** [comment]
嗯嗯，监听现在我就是这样做的。那个我这里需求是这样的，有一个视频列表(recyclerView)，点击全屏播放，全屏播放完的时候，会自动播放recyclerView的下一个视频，退出全屏的时候recyclerView需要滚到对应的item,继续播放原来的视频。现在全屏播放下一个和滚动已经实现了，可是退出全屏的时候不能继续播放。我觉得问题就出在FIRST_FLOOR_JZVD这里，播放完第一个视频，播放到第二个视频的时FIRST_FLOOR_JZVD没有切换到对应item的JZVideoPlayer，想问问看这个是可以实现的吗。具体的效果就是腾讯新闻的视频列表效果。

**Comment by lipangit** [comment]
兄弟，这个滚动的问题有坑。

普通状态下url A是firstfloor，点击全屏进入secondfloor 同样是url A ，然后在全屏状态下切换url，firstFloor里还是url A，这是从secondFloor 退出到firstFloor时他们的url 不一样，会调用releaseAllVIdeos。

所以说你再修改全屏时候的修改sec的url的同时修改firstFloor的url，JZVideoPlayerManager.FIRST_FLOOR_JZVD的相关信息，这样从sec退出到first的时候url才会一样。

**Comment by lipangit** [comment]
@zzh12138 兄弟能把你做的放到demo里吗，我整理一下给别人参考

**Comment by zzh12138** [comment]
https://www.jianshu.com/p/4e21ecc90da6 博客 
https://github.com/zzh12138/JZVideoDemo demo
@lipangit

**Comment by lipangit** [comment]
很不错，想在首页推荐他。
