### ISSUE TITLE
Can we load subtitles?

### ISSUE THREAD

**Issue by Tobibur** [lipangit/JiaoZiVideoPlayer#2040]
**需求描述
I want to load .srt subtitle files in my video
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
Does android.media.MediaPlayer have the interface?

**Comment by Tobibur** [comment]
Sorry, I've not implemented it yet. But docs says it has right?

**Comment by lipangit** [comment]
android.media.MediaPlayer support subtitle you can extends JZVideoPlayerStandard to achieve this function
