### ISSUE TITLE
有个关于播放器的小疑问

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2042]
为什么全屏，小窗播放要保存2个播放器的实例呢，不能把播放器从父view中remove出来，然后直接add到需要的容器里面吗。个人感觉这样耗费的内存会更小。不这样设计的理由是什么呢，是不是又什么原因所以放弃这样做，改为保存2个实例呢。

**Comment by lipangit** [comment]
小窗和全屏是同理。

当时设计的时候你说的也有考虑，你说的那种内存和现在差不多，为什么用现在的只能说是直觉，在判断播放状态和当前屏幕的时候代码方便。

**Comment by zzh12138** [comment]
好的，谢啦
