### ISSUE TITLE
客製化ts檔 header

### ISSUE THREAD

**Issue by PascalTang** [lipangit/JiaoZiVideoPlayer#2044]
**需求描述
本來是url裡面 把m3u8檔直接餵給播放器就能實現

但現在 我們要在m3u8裡面的ts檔 請求時加上客製化的header

請問我要如何實作？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/43938939-25cd27e8-9c99-11e8-99f6-38b12fcfc741.png)


兄得，你说的是这个header吗

**Comment by PascalTang** [comment]
不是 這是m3u8的
我想要的是在m3u8裡面的ts檔附加

**Comment by lipangit** [comment]
超出老臣解决范围，我问问群里其他人

**Comment by PascalTang** [comment]
謝了哥
