### ISSUE TITLE
android P

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2046]
android P版本虚拟机，播放器全屏后，屏幕下方的点击事件，seekbar的拖动事件都很难，甚至无法触发。

**Comment by lipangit** [comment]
保持关注，这种基础控件应该不会有这种低级问题，是虚拟键盘挡住了吗

**Comment by zzh12138** [comment]
![ezgif-4-550afbbdf2](https://user-images.githubusercontent.com/16078807/44009645-de359f3e-9edf-11e8-9ad5-5d69de024c6c.gif)
这是gif图。
另外还有个关于全屏的问题。就是我现在有一个监听视频播放完毕播放下一个视频的接口，然后切换全屏的时候，因为是2个播放器实例，所以这个接口就为Null，不会触发我的方法了。现在我只能把JZVideoPlayer整个拷下来，在里面增加这个接口，然后在全屏和退出全屏的时候将这个接口的值在2个播放器里面进行切换。想问问看，有没有什么办法可以在不改JZVideoPlayer的情况下，在全屏也实现我的接口呢。我感觉这个需求还是挺常见的。

**Comment by lipangit** [comment]
继承JZVideoPlayerStandard,然后复写OnAutoComplete函数，取得自动播放完成的事件，然后判断currentScreen==Fullscreen 判断屏幕类型全屏、普通或者小窗。

**Comment by zzh12138** [comment]
这么做就有点麻烦，需要写个静态方法来做，而不是通过接口回调。另外，android P那个问题有解决办法么

**Comment by lipangit** [comment]
应该是有东西挡着，不可能无缘无故无法操作控件
