### ISSUE TITLE
连续播放的问题

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2048]
为了实现自动连续播放在onStateAutoComplate 里面 重新setUp（）下一条的资源然后播放，但是如果现在又手动的点击上一条，上一条资源并不会重新开始从头播放（记住了播放进度上次已经播放完成）而是直接调用了onStateAutoComplate 所以又跳到了下一条。
但是如果我不在onStateAutoComplate 里面设置播放下一条，在播放完成后手动点击是会重新从头播放的。是我哪里操作有问题吗？

**Comment by lipangit** [comment]
播放上一条的时候是不是从saveProgress记录的位置开始播放的，断点一下查查

**Comment by yilylong** [comment]
突然在另一个Issues 里面看到 说要在onStateAutoComplate回调里面延时下才播放下一条，试了下果然可以解决问题。不清楚什么原因。

**Comment by lipangit** [comment]
因为onStateAutoComplate里面调用了MediaPlayer 的release，调用这个的时候是在message队列中，应该和这个有关系

**Comment by yilylong** [comment]
哦 那应该是消息发送有时间差。不知道你们官方以后会不会把自动连播的功能考虑进去呢

**Comment by lipangit** [comment]
会考虑，正在酝酿

**Comment by pokerfaceCmy** [comment]
请问现在支持了自动连播吗

**Comment by lipangit** [comment]
头疼开发不过来了
