### ISSUE TITLE
RecyclerView下滑动进度条很容易变成拖动ViewPager

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#2050]
我们的应用结构如下
ViewPager 
  |---> RecyclerView

当在列表里播放时，点击视频显示进度条，拖动进度条的时候（已经拖动的情况下）很容易变成拖动ViewPager，请问有办法修改吗？

谢谢

**Comment by kennir** [comment]
我测试一下demo，谢谢

**Comment by kennir** [comment]
DEMO确实不会，有点奇怪

**Comment by lipangit** [comment]
你是如何自定义的

**Comment by kennir** [comment]
确认是recycleview下的emptyview的锅，我们的视频组件正常，🙏支持

**Comment by lipangit** [comment]
么么哒小可爱
