### ISSUE TITLE
Binary XML file line #8: Binary XML file line #8: Error inflating class top.jimmry.yvideo.jzvideoplayer.HVideoPlayer

### ISSUE THREAD

**Issue by yjjstc2017** [lipangit/JiaoZiVideoPlayer#2052]
**什么jzvd版本
'cn.jzvd:jiaozivideoplayer:6.2.12'
**是否和安卓版本有关系，什么版本
无安卓版本关系
**是否和特定品牌的手机机型有关系，什么机型
无机型关系
**相关log是什么
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class top.jimmry.yvideo.jzvideoplayer.HVideoPlayer
    Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class top.jimmry.yvideo.jzvideoplayer.HVideoPlayer
    Caused by: java.lang.reflect.InvocationTargetException
**复现流程
自定义一个View继承JZVideoPlayerStandard 然后生成两个构造方法public HVideoPlayer(Context context)和public HVideoPlayer(Context context, AttributeSet attrs) 然后重写getLayoutId方法返回自己的资源布局运行就会出错
**最好有截图或者视频说明情况
![qq 20180815140007](https://user-images.githubusercontent.com/30979387/44133693-ace15e72-a093-11e8-95fc-c32904e38e32.jpg)
![qq 20180815140022](https://user-images.githubusercontent.com/30979387/44133694-af0ca936-a093-11e8-813d-d4c64258053e.jpg)
![qq 20180815140036](https://user-images.githubusercontent.com/30979387/44133695-af6a10ee-a093-11e8-87bb-0e1a805d3f45.jpg)
![qq 20180815140245](https://user-images.githubusercontent.com/30979387/44133737-eb4e9846-a093-11e8-82c9-5fddf5415774.jpg)

**Comment by lipangit** [comment]
自定义的jz_layout_y这个文件的控件和代码中取得的控件有冲突。

**Comment by yjjstc2017** [comment]
可是我用老版本 'cn.jzvd:jiaozivideoplayer:6.1.2'同样的代码就可以正常运行

**Comment by lipangit** [comment]
更新版本的时候，自己自定义的xml的代码也要一起更新

**Comment by yjjstc2017** [comment]
谢谢大神，我没注意这个问题...尴尬了
