### ISSUE TITLE
视频缓冲时，返回按钮显示

### ISSUE THREAD

**Issue by kofihust** [lipangit/JiaoZiVideoPlayer#2053]
有时网络不好，视频缓冲很长时间，topContainer隐藏了，除了物理返回键用户不能返回退出

**Comment by lipangit** [comment]
录小视频看看效果

**Comment by kofihust** [comment]
![normal_state_buffer](https://user-images.githubusercontent.com/9524120/44242789-35223700-a1fe-11e8-9d74-26fdcc723274.gif)

**Comment by lipangit** [comment]
咱们的ui是模仿头条的ui，头条在loading的时候title是压根不会出现的，这时候想后退按手机的后退键不可以吗

**Comment by kofihust** [comment]
是可以用物理返回键，但是现在使用手机的趋势少用物理返回键了，安卓和iosUI设计统一，都在界面上加了返回按钮

**Comment by lipangit** [comment]
你可以继承JZVideoPlayerStandard，复写这两个函数（具体的你测试一下）
![image](https://user-images.githubusercontent.com/2038071/44310953-99691480-a411-11e8-912e-1436e951dccb.png)
这个是让title消失的函数，判断preparing状态下，不隐藏title隐藏其他函数即可
