### ISSUE TITLE
类似抖音的，列表滑动自动播放，条目滑出屏幕自动停止

### ISSUE THREAD

**Issue by 3kqing** [lipangit/JiaoZiVideoPlayer#2054]
**需求描述
类似抖音的，列表滑动自动播放，条目滑出屏幕自动停止
**其他app是否实现
https://github.com/CarGuo/GSYVideoPlayer 这个库貌似有实现
**截图或者小视频说明
参考抖音等

**Comment by yilylong** [comment]
有这个功能 看 demo

**Comment by 3kqing** [comment]
建议文档上说一下吧，我后来找到了，多谢！

**Comment by shenjiabing** [comment]
这个demo在哪里？

**Comment by lipangit** [comment]
github首页，有api下载，代码在develop分支。

**Comment by shenjiabing** [comment]
还是没有找到

**Comment by shenjiabing** [comment]
有没有 RecyclerView多布局的自动播放demo啊？

**Comment by lipangit** [comment]
这个研究了一半，没时间弄了

**Comment by shenjiabing** [comment]
> 这个研究了一半，没时间弄了

请问一下，那个抖音上下翻页的效果，在develop分支哪个类里面？我还是没有找到，

**Comment by lipangit** [comment]
listview  -   tiktok 。  @shenjiabing
