### ISSUE TITLE
listView 播放视频会多次触发onScroll方法

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2057]
**什么jzvd版本
最新版本
**是否和安卓版本有关系，什么版本
Nexus5X模拟器 API27
demo中ActivityListViewNormal，监听listView的滚动，在播放视频的时候，会不停地触发onScroll方法

**Comment by lipangit** [comment]
正常，真机也会不停触发onScroll

**Comment by lipangit** [comment]
这个是解决不了，用其他方法回避了，可能是布局的问题，你可以研究研究
