### ISSUE TITLE
SeekBar did not disable when playing rtsp stream video

### ISSUE THREAD

**Issue by fukemy** [lipangit/JiaoZiVideoPlayer#2058]
hello. That it the best library I found. When i play streaming rtsp link, I saw seekbar is enabling. When swipe seekbar it cause crash app. 

 Now i want to disable seekBar, can you provide my the way to do it?
 Many thanks.

**Comment by lipangit** [comment]
crash app what log

**Comment by fukemy** [comment]
sorry i forgot set config in AndroidManifest. Now it working
