### ISSUE TITLE
部分手机部分视频无法加载

### ISSUE THREAD

**Issue by ll418718** [lipangit/JiaoZiVideoPlayer#2060]
**jzvd版本：implementation 'cn.jzvd:jiaozivideoplayer:6.2.12'

**三星手机部分视频无法播放

![image](https://user-images.githubusercontent.com/21256291/44391427-697d5680-a562-11e8-82da-1f5a49409a03.png)

**Comment by lipangit** [comment]
这是android.media.MediaPlayer的问题

**Comment by imknown** [comment]
和这个一样 #1820 , 我用 正式版 Android 9 的手机 和 AVD 模拟器 都是这个错误. Android 9 之前的系统没问题.

**Comment by luyun181** [comment]
这个怎么办啊？
