### ISSUE TITLE
Pause video when change tab

### ISSUE THREAD

**Issue by nguyenhoangphuc96** [lipangit/JiaoZiVideoPlayer#2061]
**需求描述
How can I stop a video while surfing another tab?
**截图或者小视频说明
![screenshot_1534842233](https://user-images.githubusercontent.com/22586556/44392406-549dc480-a55c-11e8-8762-bac78188d1eb.png)
![screenshot_1534842237](https://user-images.githubusercontent.com/22586556/44392424-5cf5ff80-a55c-11e8-978f-f942976e109b.png)

**Comment by lipangit** [comment]
call JZVideoPlayer.releaseAllVideos(), 

see ActivityListViewFragmentViewPager in demo.
