### ISSUE TITLE
wmv用什么引擎可以播放，我用JZMediaSystem播放只有声音，画面一直在加载

### ISSUE THREAD

**Issue by JianHaoZhangHB** [lipangit/JiaoZiVideoPlayer#2062]
求解。。

**Comment by lipangit** [comment]
ijkplayer

**Comment by JianHaoZhangHB** [comment]
JZVideoPlayer.setMediaInterface(new JZMediaIjkplayer());
是这样吗？
但是我这里提示视频加载失败，是还要配置别的东西吗？
JZVideoPlayer.setMediaInterface(new JZMediaSystem());
用JZMediaSystem播放视频不会出现视频加载失败，但是只有声音，而且显示一直在加载。
拜谢🙏

**Comment by HmLifengfeng** [comment]
换成 JZMediaIjkplayer 同样的问题，只有声音，画面一直加载

**Comment by lipangit** [comment]
在chrome中也是只有声音没有图像

**Comment by JianHaoZhangHB** [comment]
> 在chrome中也是只有声音没有图像

http://zuoyeyuyin.youyitong365.com/test_mp4.mp4这个地址没有问题吧，我在爱奇艺万能播放器中通过添加URL播放，是可以的。但是在chorme中确实只有声音

**Comment by lipangit** [comment]
格式化一下视频源吧，编码解码取决于播放器引擎，换成exoplayer试试
