### ISSUE TITLE
视频连续播放遇到的bug

### ISSUE THREAD

**Issue by Wade-Cai** [lipangit/JiaoZiVideoPlayer#2063]
**什么jzvd版本
最新6.2.12
**相关log是什么
BufferQueueProducer: [SurfaceTexture-0-20106-6] cancelBuffer: BufferQueue has been abandoned
**复现流程
从视频列表点击一个视频播放，然后跳转进详情页，视频列表的视频release了，
详情页是另一个VideoPlayerStandard，开始播放，然后关闭详情页回到视频列表，点击任意一个视频都会出现这个问题，视频播放几秒钟后重置了，然后再次点击就可以继续播放了

**Comment by lipangit** [comment]
断点JZVideoPlayer.releaseAllvideos()，和
![image](https://user-images.githubusercontent.com/2038071/44458807-f0513280-a639-11e8-99bd-e14b40b23ed8.png)

看看什么时候视频被重置了

**Comment by HmLifengfeng** [comment]
这个问题怎么解的 @Wade-Cai
