### ISSUE TITLE
Recycleview横屏概率出错

### ISSUE THREAD

**Issue by kennir** [lipangit/JiaoZiVideoPlayer#2065]
在recycleview播放时点击全屏概率会发生屏幕没有完全占用的问题, 并不是一定会触发， 请问这可能会是什么原因？

![photo](https://user-images.githubusercontent.com/876410/44586366-10bbf100-a7e2-11e8-841f-18f466a3306b.jpg)

**Comment by lipangit** [comment]
demo 有这问题吗，   理论上列表的activity已经设置了无法横屏

**Comment by kennir** [comment]
这个问题不是必现，demo我没测出来，在oppo和小米上偶然会发生，这两个手机都是android 8

**Comment by lipangit** [comment]
demo在oppo和小米上会发生吗

**Comment by kennir** [comment]
DEMO的RecyclerView的例子好像无法横屏，API->Orientation那个例子我好像没有复现这个问题

**Comment by lipangit** [comment]
demo ListView-> recycleView  全屏之后可以横
