### ISSUE TITLE
我在RecyclerView列表中使用，快速滑动会出现播放器显示不完全的问题

### ISSUE THREAD

**Issue by shiwukuanghun** [lipangit/JiaoZiVideoPlayer#2066]
我在RecyclerView列表中使用，快速滑动会出现播放器显示不完全的问题，我不是用的默认的宽高，而是给播放器空间写了宽高，或者调用饺子的宽高比api设置，也试过是不是封面图片加载的问题，但是还是出现这个问题，就是滚动的时候，有些item上的播放器显示不完全，但是将这个item滑出屏幕再滑回来，就好了，不明白这是什么原因，麻烦大神解答下。点击视频是可以播放的，就是默认显示的不完全

**Comment by lipangit** [comment]
代码截图，效果截图、视频。这个应该是布局问题
