### ISSUE TITLE
goOnPlayOnResume问题

### ISSUE THREAD

**Issue by lihaodong** [lipangit/JiaoZiVideoPlayer#2068]
1.当正在播放，home键切换goOnPlayOnResume继续播放没问题；
当暂停播放，home键切换goOnPlayOnResume还会继续播放，请问这个问题如何解决可以当暂停的时候切换还处于暂停状态。

2.页面跳转播放问题，子页面播放返回，首页面处于暂停状态。如何可以做到与home键切换效果一样？

**Comment by lipangit** [comment]
1.已经修复 b542bbb  参考这个commit，着急的话可以自行修改，都是全局函数，复制即可。
2.页面跳转是什么需求，目前只要切换了activity就会release视频了。

**Comment by lipangit** [comment]
进入详情页的功能还在研究
