### ISSUE TITLE
Error raised 'ProtocolException: Unexpected status line' after Media Player API(MediaHTTPService)

### ISSUE THREAD

**Issue by imknown** [lipangit/JiaoZiVideoPlayer#2073]
https://github.com/google/volley/issues/208

This is a issue I reported for Google/Volley before... But no conclusion at last... I tried both JieCaoV5 and JiaoZiV6, and no luck.

**Comment by lipangit** [comment]
Beyond my ability

**Comment by imknown** [comment]
T_ T thx, and i will try to report this to AOSP issue track.
