### ISSUE TITLE
播放长视频切换到exo，播放过程中自动暂停

### ISSUE THREAD

**Issue by HmLifengfeng** [lipangit/JiaoZiVideoPlayer#2074]
system_mediaplayer引擎下，播放长视频的时候大部分手机总会自动暂停，后来在这里寻到答案切换到 exo，但是有用户反馈老是暂停，我又测试了几部手机，在HUAWEI G7-TL00 播放的时候自动暂停，截的error 
![error](https://user-images.githubusercontent.com/39474788/44840408-8ce78600-ac73-11e8-9182-c9a9699122ca.png)

**Comment by lipangit** [comment]
可以尝试到ijkplayer

**Comment by HmLifengfeng** [comment]
用的demo，换成 JZMediaIjkplayer ，只有声音，画面一直加载，http://zuoyeyuyin.youyitong365.com/test_mp4.mp4 这是我的视频地址

**Comment by HmLifengfeng** [comment]
我的这个bug 测试了好几天，找问题，发现 我注释掉 下边这2段代码，视频就不会暂停了，但是我又需要 这2句话实现的横竖屏的代码，我想我应该是放错位置了，然后我就理了一下代码，我进入页面，请求了后台接口，返回数据再执行，下边两句话+播放视频。然后点击页面列表中的任意一个视频，再执行下边2句话+播放视频。我觉着不对，然后把下边这2句横竖屏的代码拿出放到oncreate中执行。结果我的问题解决了。
Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;

**Comment by lipangit** [comment]
Good
