### ISSUE TITLE
 the video that the playing is shrinking when scroll the RecyclerView

### ISSUE THREAD

**Issue by mhkhajehpoor** [lipangit/JiaoZiVideoPlayer#2077]
When I scroll the RecyclerView, the video that the playing is shrinking, and as you can see in the figure below, the red part appears to the right of the page.
What if I want to disable this feature? What should I do?

Thank you for your help

![image](https://user-images.githubusercontent.com/38702413/44960501-174f1480-af16-11e8-89e1-9dcfdb90eeca.png)

**Comment by lipangit** [comment]
There are two recycleview in demo, one is smallwindow the other is no smallwindow.
