### ISSUE TITLE
recyclerView中Item显示不全

### ISSUE THREAD

**Issue by ZhySir** [lipangit/JiaoZiVideoPlayer#2078]
前提继承JZVideoPlayerStandard
recyclerView中Item点击播放 进入全屏 重力感应横屏
然后返回 recyclerView某个Item的播放器布局显示不全
![image](https://user-images.githubusercontent.com/20807613/44973522-67b68880-af8f-11e8-940f-762ecf422b40.png)

**Comment by shiwukuanghun** [comment]
你这是不是用的播放器的圆角方式设置圆角，如果是的话就别用这种，用CardView做圆角就不会出现这种情况了

**Comment by lipangit** [comment]
没研究过，咱们这个jzvd本质上是RelativeLayout，看一下布局里有什么坑

**Comment by ZhySir** [comment]
已经解决 正如楼上@shiwukuanghun 老哥所说 自己CardView做圆角就ok了
