### ISSUE TITLE
切换到ijkplayer，观看rtmp推流直播的时候偶尔会有卡顿现象

### ISSUE THREAD

**Issue by choys** [lipangit/JiaoZiVideoPlayer#2079]
用了Ijkplayer引擎来播放rtmp的直播视频，但是会有卡顿现象，也就是视频画面会停在那儿，过几秒钟接着开始播放，有时甚至会显示视频加载失败，这样就会导致直播延迟越来越厉害。Ijkplayer相关参数未做特殊设置，都是采用默认的。测试手机为小米note（android 6.0），vivo（android5 ，经常卡顿，有时甚至无法播放，必须退出才行重新进入）、华为mate10。

基本上同样的网络环境，ios客户端（直接用的ijkplayer播放器），可以很稳定的播放，延迟基本上在7s左右。

请问这可能是什么原因导致的？

**Comment by lipangit** [comment]
超出老臣解决范围，请到ijkplayer项目中提问

**Comment by coolluo** [comment]
> 用了Ijkplayer引擎来播放rtmp的直播视频，但是会有卡顿现象，也就是视频画面会停在那儿，过几秒钟接着开始播放，有时甚至会显示视频加载失败，这样就会导致直播延迟越来越厉害。Ijkplayer相关参数未做特殊设置，都是采用默认的。测试手机为小米note（android 6.0），vivo（android5 ，经常卡顿，有时甚至无法播放，必须退出才行重新进入）、华为mate10。
> 
> 基本上同样的网络环境，ios客户端（直接用的ijkplayer播放器），可以很稳定的播放，延迟基本上在7s左右。
> 
> 请问这可能是什么原因导致的？
老哥 切换为ijkplayer引擎就可以直接播放rtmp视频了吗

**Comment by lipangit** [comment]
播放器引擎的问题请到ijkplayer项目中提问，超出老臣解决范围。
