### ISSUE TITLE
In android Oreo and above unable to play videos

### ISSUE THREAD

**Issue by rajtechi** [lipangit/JiaoZiVideoPlayer#2082]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况
09-05 00:20:16.028 24186-24471/com.rs.wstatus E/MediaPlayerNative: Unable to create media player
09-05 00:20:17.197 1367-1915/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).

Its working fine till android 6.0

**Comment by rajtechi** [comment]
Tried playing local folder video and found error saying cannot create media
player for android oreo and above.

Regards,
Rajesh Lakkakula

**Comment by lipangit** [comment]
create a new project , try to use MediaPlayer and textureView, then play your url, will it happen?

**Comment by rajtechi** [comment]
Yeah its working fine with Mediaplayer and textureview

**Comment by lipangit** [comment]
Stay concerned
