### ISSUE TITLE
重复循环播放的时候能不能不让封面闪现一下并且不让那个缓冲条出来，因为我做了缓存的，觉得没必要出现

### ISSUE THREAD

**Issue by shiwukuanghun** [lipangit/JiaoZiVideoPlayer#2084]
重复循环播放的时候能不能不让封面闪现一下并且不让那个缓冲条出来，因为我用videoCache做了缓存的，觉得没必要出现那个缓冲条，这样就会无缝衔接了，而不会闪一下封面

**Comment by lipangit** [comment]
jzvd.looping=true 你是不是这么设置循环播放的

**Comment by shiwukuanghun** [comment]
不是，我是这样写的  
 @Override
    public void onAutoCompletion() {
        super.onAutoCompletion();
        startVideo();
    }

**Comment by shiwukuanghun** [comment]
刚才试了一下用loop的方法，只有用mediaPlayer才有效，用ijk就不行了

**Comment by lipangit** [comment]
ijkplayer应该也可以，看一下自定义的CustomIjkplayer，是否把looping变量设置进度

**Comment by shiwukuanghun** [comment]
我知道了，在JZMediaIjkplayer这个类中加上ijkMediaPlayer.setLooping(true);这行就可以无缝循环了

**Comment by lipangit** [comment]
ok
