### ISSUE TITLE
4G网络环境下，加载很慢，且加载出来后，卡着不动

### ISSUE THREAD

**Issue by 455361051** [lipangit/JiaoZiVideoPlayer#2086]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型
使用mi8测试
**相关log是什么

**复现流程
在4g下加载，点击播放按钮

**最好有截图或者视频说明情况
下面是加载的时候，网络使用情况，可以看出，在这期间，网络请求不活跃
![image](https://user-images.githubusercontent.com/14355208/45273611-0c801b00-b4e6-11e8-90ec-cf77fba68b83.png)

**Comment by dnzl123** [comment]
我也是这样，WiFi不卡，流量很卡。为什么播放其他app的视频用流量不会卡。这是视频的原因吗

**Comment by 455361051** [comment]
从网络使用情况上分析，应该不是视频本身的原因，哪位大神帮忙看看？

**Comment by lipangit** [comment]
保持关注老铁们
