### ISSUE TITLE
targetSdkVersion 28 does not work for 'http'

### ISSUE THREAD

**Issue by imknown** [lipangit/JiaoZiVideoPlayer#2088]
**Https** urls work well on `targetSdkVersion 28`. But it does not work for `http`.

Commit here:
https://github.com/lipangit/JiaoZiVideoPlayer/commit/4ce3377b90f46f4618ba7172b6a3d4edfce666e5#diff-39e7d8c00954e920b98e7636f0ac30b2R9

Error trace
```
2018-09-10 12:39:42.236 31471-31489/cn.jzvd.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2018-09-10 12:40:12.417 31471-31491/cn.jzvd.demo E/MediaPlayerNative: error (1, -2147483648)
2018-09-10 12:40:12.418 31471-31550/cn.jzvd.demo E/MediaPlayer: Error (1,-2147483648)
2018-09-10 12:40:12.419 31471-31471/cn.jzvd.demo E/JZVD: onError 1 - -2147483648 [209585138] 
2018-09-10 12:40:12.419 31471-31471/cn.jzvd.demo I/JZVD: onStateError  [209585138] 
2018-09-10 12:40:12.430 31471-31550/cn.jzvd.demo V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2018-09-10 12:40:12.430 31471-31550/cn.jzvd.demo V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

----

The sample video url is `http://jzvd.nathen.cn/c6e3dc12a1154626b3476d9bf3bd7266/6b56c5f0dc31428083757a45764763b0-5287d2089db37e62345123a1be272f8b.mp4`, and it is not secure.

So we need the `android:networkSecurityConfig="@xml/jz_network_security_config"` in the `AndroidManifest.xml` of the app module.

``` xml
<application
    android:name=".ApplicationDemo"
    android:allowBackup="false"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:networkSecurityConfig="@xml/jz_network_security_config"
    android:theme="@style/AppTheme">
    <!-- ... -->
</application>
```

See: https://developer.android.google.cn/training/articles/security-config
> The default configuration for apps targeting Android 9 (API level 28) and higher is as follows:
> ``` xml
> <base-config cleartextTrafficPermitted="false">
>     <trust-anchors>
>         <certificates src="system" />
>     </trust-anchors>
> </base-config>
> ```
> 
> The default configuration for apps targeting Android 7.0 (API level 24) to Android 8.1 (API level 27) is as follows:
> ``` xml
> <base-config cleartextTrafficPermitted="true">
>     <trust-anchors>
>         <certificates src="system" />
>     </trust-anchors>
> </base-config>
> ```
> 
> The default configuration for apps targeting Android 6.0 (API level 23) and lower is as follows:
> ``` xml
> <base-config cleartextTrafficPermitted="true">
>     <trust-anchors>
>         <certificates src="system" />
>         <certificates src="user" />
>     </trust-anchors>
> </base-config>
> ```

So, we may need one `/res/xml/jz_network_security_config.xml`:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
```

**Comment by lipangit** [comment]
You mean demo can not play on phone with api 28?

**Comment by 15characterlimi** [comment]
For reference, that plaintext traffic is blocked by default for apps targeting API version 28 is documented at:

https://developer.android.com/about/versions/pie/android-9.0-changes-28#framework-security-changes

> If your app targets Android 9 or higher, the isCleartextTrafficPermitted() method returns false by default. If your app needs to enable cleartext for specific domains, you must explicitly set cleartextTrafficPermitted to true for those domains in your app's Network Security Configuration.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/45346372-9b229400-b5db-11e8-9481-7eeb3f8d9197.png)

Is it right?
I do not have phone with api 28, you can help to test.

**Comment by lipangit** [comment]
@imknown Could you please make a pr, that very greatful

**Comment by dasendriadigitalmedia** [comment]
aaa
