### ISSUE TITLE
网络断开后复播的问题

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2089]
**什么jzvd版本
6.2.12
**复现流程
在播放过程中关掉网络，在播放完缓存后回调了OnStateError() 。然后再打开网络，点击播放按钮重新播放，这个时候因为回调了OnStateError() 本身已经执行了releaseMediaPlayer() 播放器状态为error. 所以重新setup资源播放。发现这个时候一直开卡在了preparing状态。

**Comment by lipangit** [comment]
OnStateError中重新播放视频，如果不切换url的话不要调用seUp，直接startVideo播放就好了
