### ISSUE TITLE
Not sure if this is a bug but i only speak english..sorry

### ISSUE THREAD

**Issue by flynnben123** [lipangit/JiaoZiVideoPlayer#2090]
I was wondering if there is a way to control the errors that come up on the VideoPlayerStandard, for example when there is no url it comes up with a toast that says "No url" but can i make it not come up with a toast?  Also is there a way to get rid of the battery icon on the videoplayer?

**Comment by lipangit** [comment]
No url because setUp(url...) ,the url is null. check it out.

If you wantn't not to see the toast, just extends jzvdStd, 
override 
showWifiDialog(){
//super.showWifiDialog(); 
}
