### ISSUE TITLE
seekbar显示时无法快进快退

### ISSUE THREAD

**Issue by yuanfangyan** [lipangit/JiaoZiVideoPlayer#2091]
**需求描述
我这边是实现一个在电视上播放的功能，按左右键可以实现快进快退。在的有个问题就是只要seekbar状态为显示状态时就无法快进快退。
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
快进快退是MediaPlayer的问题，和seekBar这个控件没关系啊，这个本质上是什么问题？

**Comment by yuanfangyan** [comment]
就是如果seekbar是显示状态调用seekto()就没用，如果是隐藏状态就没关系

**Comment by yuanfangyan** [comment]
因为是放在机顶盒上的，所以不能通过手势只能通过遥控器的左右按键

**Comment by lipangit** [comment]
你具体是如何调用seekTo的，代码截图看看

**Comment by yuanfangyan** [comment]
![image](https://user-images.githubusercontent.com/26668897/45397496-e50a8900-b672-11e8-9936-72862a5338bc.png)

**Comment by lipangit** [comment]
你调用的seekTo是正确的，在调用seekTo之前要判断当前的播放状态，判断mCurrentState这个变量。

seekTo的调用只和播放状态有关，和seekBar的显示无关
