### ISSUE TITLE
关于添加新控件的问题。。。

### ISSUE THREAD

**Issue by xuzh2017** [lipangit/JiaoZiVideoPlayer#2093]
大神，我想加个投屏按钮，但是全屏后想对这个按钮操作必须getsecondfioor才能拿到，JZVideoPlayerManager.getSecondFloor().castscreenButton像这样，
退出全屏后还要getfirstfloor才可以，这是怎么回事？

**Comment by lipangit** [comment]
投屏按钮的添加可以参考demo中的分享按钮。然后你说的floor的问题没听明白，先说你的需求吧，投屏按钮什么逻辑。

**Comment by xuzh2017** [comment]
比如播放器进度条是根据投屏的进度更新，全屏时需要
JZVideoPlayerManager.getSecondFloor().progressbar才能对progressbar操作
恢复全屏后需要
JZVideoPlayerManager.getfirstFloor().progressbar才能操作、

**Comment by lipangit** [comment]
是的，全屏和非全屏是两个不同的实例，分别在不同的floor，理论上全屏和非全屏不会同时被用户看到，按照你说的get方式可以去操作

**Comment by xuzh2017** [comment]
可是我看您的里面都是直接用的啊。。并没有用getfloor去拿控件，感觉控件是全屏和非全屏共享的。

**Comment by lipangit** [comment]
他们之间的数据和状态mState是可以搬运的，实例是不同的
