### ISSUE TITLE
新版本类名为什么要改成缩写呢？

### ISSUE THREAD

**Issue by 3kqing** [lipangit/JiaoZiVideoPlayer#2094]
新版本类名为什么要改成缩写呢？
还得好多地方要改动，这应该不是必要改动吧
完全体反而更容易理解
并且在发版说明里面也没有提到
感觉发版本很随意啊

**Comment by lipangit** [comment]
这个问题酝酿了很久了，感觉还是简写方便一些，更新日志我再更新一下，感谢你的提醒。
