### ISSUE TITLE
选择播放引擎时遇到的一些问题

### ISSUE THREAD

**Issue by bluebupang** [lipangit/JiaoZiVideoPlayer#2095]
hi,大佬好，我遇到了几个小问题，求解答
**问题描述
1、使用饺子播放器播放网络视频时，同一个视频链接，使用MediaPlayer 总是要比 ijkplayer 加载时间长。(这个现象是正常的么？)
2、使用ijkplayer 播放时，测试使用的使用链接会显示“视频加载失败”，而 使用MediaPlayer 却可以正常播放
测试视频连接：https://erp.vipstation.com.hk/images/IC/IC0002851/IC0002851_180419124311770_iOS.mp4
问题截图 ![_20180912155307](https://user-images.githubusercontent.com/15033191/45410499-6fb7ac00-b6a4-11e8-9d9b-9b6e28f4a6fc.png)

**Comment by lipangit** [comment]
1.正常，因为MediaPlayer要比ijk取得更多数据才会开始播放
2.播放失败log是什么
3.视频中是陀飞轮吗，什么牌子，太漂亮了

**Comment by bluebupang** [comment]
问题都了解了哈，第二个问题是因为ijkplayer不支持https导致的，已解决
视频中的表我也不太了解。。。随意找的视频
