### ISSUE TITLE
jzVideoPlayer.startButton设置了监听之后点击播放按钮没反应

### ISSUE THREAD

**Issue by 3kqing** [lipangit/JiaoZiVideoPlayer#2096]
**什么jzvd版本
6.3.1
设置了监听之后点击播放按钮没反应
//            jzVideoPlayer.startButton.setOnClickListener(new View.OnClickListener() {
//                @Override
//                public void onClick(View v) {
//                }
//            });

**Comment by lipangit** [comment]
继承jzvdstd，复写onclick函数，添加监听

**Comment by lipangit** [comment]
你这样做会覆盖原来的点击逻辑
