### ISSUE TITLE
JzvdStd高度设置为：wrap_content 就会卡在onMeasure 很长时间没反应，但是如果设定一个指定的高度，就不会有这个问题

### ISSUE THREAD

**Issue by to-explore-future** [lipangit/JiaoZiVideoPlayer#2097]
我在官方的demo中把高度 200dp 改成 wrap_content,就会出现我说的问题，开在 onMeasure 很长时间，我想这个是不是 sdk 在获取视频的宽高，各位大神，谁知道怎么回事？

**Comment by lipangit** [comment]
多长时间，有具体的数据和现象吗

**Comment by JebySun** [comment]
我也遇到这个问题了，根本不能播放，一直加载中。

**Comment by lipangit** [comment]
如何在demo中复现，我试试

**Comment by weitto** [comment]
这个问题怎么解决的？ 7.0.5 还是有这个问题
