### ISSUE TITLE
能否加个画中画(Picture-in-Picture Mode)的demo?

### ISSUE THREAD

**Issue by callmecaoye** [lipangit/JiaoZiVideoPlayer#2101]
**需求描述
在播放视频过程中 点击Home键 进入画中画模式并继续播放视频
**其他app是否实现
YouTube等
**截图或者小视频说明

**Comment by lipangit** [comment]
可以，感觉很有必要

**Comment by callmecaoye** [comment]
多谢 很期待 我自己实现后 player在画中画模式下只是部分显示 不知道怎么调整

**Comment by lipangit** [comment]
能提交个pr吗，怎么做的
