### ISSUE TITLE
ON_PLAY_PAUSE_TMP_STATE变量赋值问题

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2102]
**什么jzvd版本
最新版

**复现流程
现在我播放一个视频，然后调出分享，很自然得会调用goOnPlayOnPause()方法暂停播放，分享完后再onResume调用goOnPlayOnResume()继续播放，现在由于ON_PLAY_PAUSE_TMP_STATE，调用没法继续播放了。这个值个人感觉是不是应该放在startButton的触发暂停点击事件里面才赋值为CURRENT_STATE_PAUSE好点呢

**Comment by lipangit** [comment]
兄弟可以提交一个pr

**Comment by zzh12138** [comment]
就把ON_PLAY_PAUSE_TMP_STATE的赋值改在这就好了。感觉合理很多
![qq 20180926114311](https://user-images.githubusercontent.com/16078807/46056070-7e609180-c181-11e8-9b14-731630d3548d.png)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/46070250-df9f5980-c1af-11e8-9f55-4a39d77ec586.png)

你的代码是什么版本

**Comment by lipangit** [comment]
这是当前的内容，没找到你截图的部分

**Comment by zzh12138** [comment]
代码没截全，是放在JZVD的onClick()事件里，就是那个startbutton的点击事件。当用户手动点击暂停，才赋值。
![qq 20180927095958](https://user-images.githubusercontent.com/16078807/46119210-8d584a00-c23c-11e8-8dc7-50fe2cde2395.png)

**Comment by lipangit** [comment]
这块新版没有了，更新一下试试
