### ISSUE TITLE
android studio点击可以找到该类，运行的时候报错

### ISSUE THREAD

**Issue by asalin** [lipangit/JiaoZiVideoPlayer#2104]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
没有
**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.jzvd.JzvdStd" on path: DexPathList
**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
clean 一下

**Comment by lipangit** [comment]
应该是编译的问题
