### ISSUE TITLE
怎样将screen设置为SCREEN_WINDOW_NORMAL也能支持触摸呀

### ISSUE THREAD

**Issue by yuanfangyan** [lipangit/JiaoZiVideoPlayer#2106]
**需求描述
 videoPlay.setUp(url ,name, Jzvd.SCREEN_WINDOW_FULLSCREEN);这样设置也能支持触摸事件（快进快退，声音调节，亮暗调节）
**其他app是否实现

**截图或者小视频说明

**Comment by yuanfangyan** [comment]
当我SCREEN_WINDOW_FULLSCREEN设置为全屏时，需要按两次返回才能够退出播放页面。下次再进来播放时就没有从上次的播放记录开始放，而是从头开始放。所以我想知道有没有不设置全屏也能支持触屏

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/45582056-de327f00-b8db-11e8-962f-7c2a4fef59ae.png)

继承jzvdStd，复写onTouch函数，把父类的东西考出来，把这行删掉

**Comment by yuanfangyan** [comment]
好的，谢谢了
