### ISSUE TITLE
播放状态监听的回调在哪里呀

### ISSUE THREAD

**Issue by NPC2018** [lipangit/JiaoZiVideoPlayer#2107]
请问怎么监听播放状态呢？我现在没有找到这样的一个回调，谢谢
![image](https://user-images.githubusercontent.com/32322589/45588246-3b621b00-b944-11e8-84d7-606a7ac716c2.png)
我现在就是想在视频停止播放的时候取获取一下它的播放进度

**Comment by lipangit** [comment]
继承jzvdStd，复写onStatePause函数，取得暂停状态，在onStatePause函数中取得播放进度

**Comment by NPC2018** [comment]
> 继承jzvdStd，复写onStatePause函数，取得暂停状态，在onStatePause函数中取得播放进度

谢谢
