### ISSUE TITLE
横竖屏切换问题

### ISSUE THREAD

**Issue by bobcatkay** [lipangit/JiaoZiVideoPlayer#2108]
想要的效果：
旋转和点击全屏按钮都能切换竖屏和横向全屏。
[https://youtu.be/-mhMMD34Mzs]

我现在遇到的问题：
1.旋转后并不能切换全屏；
2.点击了全屏按钮后重力感应会失效。
[https://youtu.be/qPv3PwTqsVs]

配置代码：
`Jzvd.FULLSCREEN_ORIENTATION` = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
Jzvd.NORMAL_ORIENTATION` = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
<activity android:name=".activity.VideoPlayActivity"
                  android:configChanges="orientation|screenSize|keyboardHidden">
 </activity>`

**Comment by lipangit** [comment]
重力感应参考demo的APIActivity
