### ISSUE TITLE
在RecyclerView中有一定的概率会在右下角出现小窗口

### ISSUE THREAD

**Issue by shiwukuanghun** [lipangit/JiaoZiVideoPlayer#2109]
在RecyclerView列表中的时候，我并不是会出现小窗口的那种写法，但是有很小的几率会在滑动的时候突然在右下角出现播放的小窗口。代码是真样写的，照demo来的，只是trycatch了一下，为啥会出现这种情况
mRv.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                JZVideoPlayer jzvd = view.findViewById(R.id.jz_video_player);
                try {
                    if (jzvd != null && JZUtils.dataSourceObjectsContainsUri(jzvd.dataSourceObjects, JZMediaManager.getCurrentDataSource())) {
                        JZVideoPlayer currentJzvd = JZVideoPlayerManager.getCurrentJzvd();
                        if (currentJzvd != null && currentJzvd.currentScreen != JZVideoPlayer.SCREEN_WINDOW_FULLSCREEN) {
                            JZVideoPlayer.releaseAllVideos();
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

**Comment by lipangit** [comment]
demo会出这问题吗

**Comment by shiwukuanghun** [comment]
demo不会，demo数据量太少了，我的列表数据量很多，有分页，出现频率较低，目前我总共见过三次，不知道什么原因，我在想把下面那个方法中的super.startWindowTiny();给去掉会不会可以禁止它出现
@Override
    public void startWindowTiny() {
        super.startWindowTiny();
    }

**Comment by lipangit** [comment]
可以把demo的列表加多 再试试，担心有漏掉的代码，先确定这是个系统性问题还是引用的问题

**Comment by mkfcoffee** [comment]
我这项目中也出现这个 是数据量多的时候出现的

**Comment by lipangit** [comment]
兄弟，能改一下demo复现这个问题吗，我研究一下，否则我也不能调试其他的项目

**Comment by shiwukuanghun** [comment]
出现几率太小了，我写了快一个月了，才出现那么三四次，实在难以复现，但它又确实存在，我刚才在demo里试了重写startWindowTiny()，把super去掉，也可以不让它出现，但不知道这样会不会带来新的问题

**Comment by lipangit** [comment]
好的保持关注

**Comment by BCheney** [comment]
我也是在RecyclerView滑动时在右下角出现了小窗，显示一下，然后消失，概率不大

**Comment by lipangit** [comment]
保持关注老铁
