### ISSUE TITLE
隐藏进度栏的bug

### ISSUE THREAD

**Issue by xuanxws** [lipangit/JiaoZiVideoPlayer#2112]
public class MyJzVideoView extends JzvdStd {
    public MyJzVideoView(Context context) {
        super(context);
    }

    public MyJzVideoView(Context context, AttributeSet attrs) {
        super(context, attrs);
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToNormal() {
        super.changeUiToNormal();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToPlayingShow() {
        super.changeUiToPlayingShow();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);

    }

   @Override
    public void changeUiToPlayingClear() {
        super.changeUiToPlayingClear();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToPauseShow() {
        super.changeUiToPauseShow();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToPauseClear() {
        super.changeUiToPauseClear();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToPreparing() {
        super.changeUiToPreparing();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void changeUiToComplete() {
        super.changeUiToComplete();
        bottomContainer.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
    }

    @Override
    public void onStateAutoComplete() {
        super.onStateAutoComplete();
        Log.i("test","complete....");
        startVideo();
    }

}

当我这样设置隐藏了底部栏，但是本来可以点击屏幕自由切换startbutton可见与隐藏的时候，就失效了

**Comment by lipangit** [comment]
你的需求是什么

**Comment by xuanxws** [comment]
需求：隐藏播放界面的底部栏（包括时间框，进度条，全屏按钮）
问题：我用上述代码实现了隐藏，但是中间那个播放／暂停按钮，本来点击界面的时候可以自由切换（中间那个按钮，显示的时候，点击一下界面隐藏；隐藏的时候，点击一下显示），不隐藏底部栏的时候，这个是没问题，但是隐藏了底部栏就有问题了。

**Comment by lipangit** [comment]
播放状态play pause preparing 等状态都对应这clear 和 show， 你看demo的MyJzvdStd里面有这些函数，在这些函数中隐藏控件，只需要bottomContainer.setVisibility(GONE);就可以

**Comment by zwping** [comment]
bottomProgressBar被多个状态持有了，只需设置透明度等0可以实现隐藏效果

**Comment by lipangit** [comment]
嗯 是个办法
