### ISSUE TITLE
加载中的状态

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2115]
**需求描述
现在没有加载中的状态了吗，就是播到一半，网络差，数据流一直没来，这个时候希望有个进度条之类的显示出来，可是没有找到对应的状态。这个要怎么实现咧

**Comment by lipangit** [comment]
播放中的loading状态不显示loading圆圈了，你可以参照旧版本把他加回来

**Comment by zzh12138** [comment]
好的，我找找
