### ISSUE TITLE
您好，退出activity后怎么清除原来的进度？

### ISSUE THREAD

**Issue by choimroc** [lipangit/JiaoZiVideoPlayer#2117]
**需求描述
测试用的视频url都是用同一个，在一个activity播放了，退出这个activity后进入到另一个activity，此时另一个activity是断点续播，而不是重新播放，我想每个页面每次进入都重新播放要怎么实现呢？
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
Jzvd.SAVE_PROGRESS=false

**Comment by choimroc** [comment]
您好，这个是在哪里调用呢，我尝试在BaseApplication以及activity的onDestroy() 里面调用，均无效。

**Comment by lipangit** [comment]
随时调用随时生效，你现在需要清空保存的进度，或者卸载app重装
