### ISSUE TITLE
类似于抖音上下滑动切换视频

### ISSUE THREAD

**Issue by 921668753** [lipangit/JiaoZiVideoPlayer#2118]
**需求描述
类似于抖音上下滑动切换视频的，单个视频循环播放，视频播放完毕后，自动重新开始播放 
**其他app是否实现
是的。  https://github.com/yangxiansheng123/FFmpegPlayVideo
**截图或者小视频说明
https://github.com/yangxiansheng123/FFmpegPlayVideo/raw/master/down.gif

**Comment by lipangit** [comment]
1.上滑下滑本质上是列表的管理
2.单个循环播放参考demo的apiActivity，里面有looping的资历

**Comment by lipangit** [comment]
可以FFmpegPlayVideo在这个项目的列表逻辑中嵌入jzvd

**Comment by 921668753** [comment]
恩恩！好的！谢谢！

**Comment by 921668753** [comment]
怎样才能每次都从新开始播放啊！没有找到方法

**Comment by lipangit** [comment]
JZVD.SAVE_PROGRESS=false，  不记录播放位置，每次都重新播放

**Comment by 921668753** [comment]
好的，谢谢！
