### ISSUE TITLE
第一次点击播放按钮，就想让它切换到全屏的竖屏播放，怎么弄

### ISSUE THREAD

**Issue by lmdiloveu** [lipangit/JiaoZiVideoPlayer#2120]
**需求描述
第一次点击播放按钮，就想让它切换到全屏的竖屏播放，在点击全屏按钮，就是横屏的全屏播放
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
没点播放按钮的时候是什么样的？

你可以把添加点击播放按钮的事件，让点击播放按钮之后触发点击全屏按钮的事件，这样就可以做到点击播放按钮进入全屏。

屏幕方向的问题参考demo的orientationActivity，里面有变量可以控制全屏前和全屏后的屏幕方向，随时设置随时生效
