### ISSUE TITLE
activity lost fullscreen flag after rotation from fullscreen to normal?

### ISSUE THREAD

**Issue by fukemy** [lipangit/JiaoZiVideoPlayer#2122]
Hello. 
 I set the videoplayer screen is FullScreen like this:
```
 <activity
            android:name=".Screen.VideoScreen"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"
            android:theme="@style/ThemFullScreen"
            android:windowSoftInputMode="stateHidden" />
```
But when play video and toggle to fullscreen, toggle back -> the status bar appear. Can you help me what's kind of this problem?

i updated video here:
https://vimeo.com/user84971345/review/291469441/a798f718f1

May be you need to wait for a while to video appear in vimeo server. Thanks.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/45948506-d8027800-c02a-11e8-9af6-479916fdbaf8.png)

extends JzvdStd, override clearFloatScreen(){} function hide showSupportActionBar() funciton

showSupportActionBar it will make the status bar appear.

**Comment by fukemy** [comment]
woooooowww. THanks you for fast response. it work.
