### ISSUE TITLE
关于onStatePrepared（）函数疑问

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2123]
**什么jzvd版本
最新版，使用的是exoplayer。当我暂停，然后继续播放的时候，会触发onPlayerStateChanged方法，调用了
 JZVideoPlayerManager.getCurrentJzvd().onPrepared();然后就调用了onStatePrepared()方法，获取到我保存的进度，重新从保存的地方开始，这是什么引起的呢。只有exo会这样

**Comment by lipangit** [comment]
断点一下，看看onPlayerStateChanged进入了什么状态

**Comment by zzh12138** [comment]
断点过了 进了Player.STATE_READY，并且playWhenReady为true，所以才走了onPrepared()方法

**Comment by lipangit** [comment]
亲测，暂停继续播放，没啥问题

**Comment by lipangit** [comment]
你的问题demo有吗

**Comment by zzh12138** [comment]
demo中也有，拖动进度条快进后，暂停再开始，并且JZUtils.getSavedProgress不为0的时候就会有。我现在这里参考JZSystem改成这样了：
![qq 20180926113518](https://user-images.githubusercontent.com/16078807/46055829-5d4b7100-c180-11e8-8427-98937e6af36e.png)
因为我这里按照之前的版本加了个CURRENT_STATE_PLAYING_BUFFERING_START状态，所以多了状态。
还有就是 exoPlayer这里在onTimelineChanged这个方法这里调用onInfo是没有用的，跟media和ijk不同，加载中和拖动进度条快进并不会回调这个方法。现在我是在onPlayerStateChanged里面进行得监听：
![qq 20180926113830](https://user-images.githubusercontent.com/16078807/46055902-b74c3680-c180-11e8-8874-aae6019ad62a.png)

**Comment by lipangit** [comment]
能把你对exoplayer的优化提交上来吗

**Comment by zzh12138** [comment]
`
package com.nfdaily.nfplus.module.player;

import android.content.Context;
import android.net.Uri;
import android.os.Handler;
import android.util.Log;
import android.view.Surface;

import com.google.android.exoplayer2.C;
import com.google.android.exoplayer2.DefaultLoadControl;
import com.google.android.exoplayer2.DefaultRenderersFactory;
import com.google.android.exoplayer2.ExoPlaybackException;
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.LoadControl;
import com.google.android.exoplayer2.PlaybackParameters;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.RenderersFactory;
import com.google.android.exoplayer2.SimpleExoPlayer;
import com.google.android.exoplayer2.Timeline;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.TrackGroupArray;
import com.google.android.exoplayer2.source.hls.HlsMediaSource;
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection;
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector;
import com.google.android.exoplayer2.trackselection.TrackSelection;
import com.google.android.exoplayer2.trackselection.TrackSelectionArray;
import com.google.android.exoplayer2.trackselection.TrackSelector;
import com.google.android.exoplayer2.upstream.BandwidthMeter;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultAllocator;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory;
import com.google.android.exoplayer2.util.Util;
import com.google.android.exoplayer2.video.VideoListener;
import com.nfdaily.nfplus.R;


/**
 * Created by MinhDV on 5/3/18.
 */

public class JZExoPlayer extends JZMediaInterface implements Player.EventListener, VideoListener {
    private SimpleExoPlayer simpleExoPlayer;
    private Handler mainHandler;
    private Runnable callback;
    private String TAG = "JZExoPlayer";
    private MediaSource videoSource;
    private long previousSeek = 0;


    @Override
    public void start() {
        if (simpleExoPlayer != null) {
            simpleExoPlayer.setPlayWhenReady(true);
        }
    }

    @Override
    public void prepare() {
        Log.e(TAG, "prepare");
        try {
            mainHandler = new Handler();
            Context context = JZVideoPlayerManager.getCurrentJzvd().getContext();

            BandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory =
                    new AdaptiveTrackSelection.Factory(bandwidthMeter);
            TrackSelector trackSelector =
                    new DefaultTrackSelector(videoTrackSelectionFactory);

            LoadControl loadControl = new DefaultLoadControl(new DefaultAllocator(true, C.DEFAULT_BUFFER_SEGMENT_SIZE),
                    360000, 600000, 1000, 5000,
                    C.LENGTH_UNSET,
                    false);

            // 2. Create the player

            RenderersFactory renderersFactory = new DefaultRenderersFactory(context);
            simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(renderersFactory, trackSelector, loadControl);
            // Produces DataSource instances through which media data is loaded.
            DataSource.Factory dataSourceFactory = new DefaultDataSourceFactory(context,
                    Util.getUserAgent(context, context.getResources().getString(R.string.app_name)));

            String currUrl = currentDataSource.toString();
            if (currUrl.contains(".m3u8")) {
                videoSource = new HlsMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(Uri.parse(currUrl), mainHandler, null);
            } else {
                videoSource = new ExtractorMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(Uri.parse(currUrl));
            }
            simpleExoPlayer.addVideoListener(this);

            Log.e(TAG, "URL Link = " + currUrl);

            simpleExoPlayer.addListener(this);

            simpleExoPlayer.prepare(videoSource);
            simpleExoPlayer.setPlayWhenReady(true);
            simpleExoPlayer.setVolume(0f);
            callback = new onBufferingUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onVideoSizeChanged(int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio) {
        JZMediaManager.instance().currentVideoWidth = width;
        JZMediaManager.instance().currentVideoHeight = height;
        Log.d(TAG, "onVideoSizeChanged: " + width);
        Log.d(TAG, "onVideoSizeChanged: " + height);
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onVideoSizeChanged();
                }
            }
        });
    }

    @Override
    public void onRenderedFirstFrame() {
        Log.e(TAG, "onRenderedFirstFrame");
    }

    private class onBufferingUpdate implements Runnable {
        @Override
        public void run() {
            final int percent = simpleExoPlayer.getBufferedPercentage();
            JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
                @Override
                public void run() {
                    if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                        JZVideoPlayerManager.getCurrentJzvd().setBufferProgress(percent);
                    }
                }
            });
            if (percent < 100) {
                mainHandler.postDelayed(callback, 300);
            } else {
                mainHandler.removeCallbacks(callback);
            }
        }
    }

    @Override
    public void pause() {
        if (simpleExoPlayer != null) {
            simpleExoPlayer.setPlayWhenReady(false);
        }
    }

    @Override
    public boolean isPlaying() {
        return simpleExoPlayer.getPlayWhenReady();
    }

    @Override
    public void seekTo(long time) {
        if (time != previousSeek) {
            simpleExoPlayer.seekTo(time);
            previousSeek = time;
            JZVideoPlayerManager.getCurrentJzvd().seekToInAdvance = time;
        }
    }

    @Override
    public void release() {
        if (simpleExoPlayer != null) {
            simpleExoPlayer.release();
        }
        if (mainHandler != null)
            mainHandler.removeCallbacks(callback);
    }

    @Override
    public long getCurrentPosition() {
        if (simpleExoPlayer != null)
            return simpleExoPlayer.getCurrentPosition();
        else return 0;
    }

    @Override
    public long getDuration() {
        if (simpleExoPlayer != null)
            return simpleExoPlayer.getDuration();
        else return 0;
    }

    @Override
    public void setSurface(Surface surface) {
        if (simpleExoPlayer != null) {
            simpleExoPlayer.setVideoSurface(surface);
        }
    }

    @Override
    public void setVolume(float leftVolume, float rightVolume) {
        if (simpleExoPlayer != null) {
            simpleExoPlayer.setVolume(leftVolume);
            simpleExoPlayer.setVolume(rightVolume);
        }
    }

    @Override
    public void onTimelineChanged(final Timeline timeline, Object manifest, final int reason) {
        Log.e(TAG, "onTimelineChanged");
    }

    @Override
    public void onTracksChanged(TrackGroupArray trackGroups, TrackSelectionArray trackSelections) {

    }

    @Override
    public void onLoadingChanged(boolean isLoading) {
        Log.e(TAG, "onLoadingChanged" + isLoading);
    }

    @Override
    public void onPlayerStateChanged(final boolean playWhenReady, final int playbackState) {
        Log.e(TAG, "onPlayerStateChanged" + playbackState + "/ready=" + String.valueOf(playWhenReady));
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    switch (playbackState) {
                        case Player.STATE_IDLE: {
                        }
                        break;
                        case Player.STATE_BUFFERING: {
                            mainHandler.post(callback);
                            JZVideoPlayerManager.getCurrentJzvd().onStatePlaybackBufferingStart();
                        }
                        break;
                        case Player.STATE_READY: {
                            if (playWhenReady && (JZVideoPlayerManager.getCurrentJzvd().currentState == JZVideoPlayer.CURRENT_STATE_PREPARING
                            ||JZVideoPlayerManager.getCurrentJzvd().currentState == JZVideoPlayer.CURRENT_STATE_PREPARING_CHANGING_URL
                            ||JZVideoPlayerManager.getCurrentJzvd().currentState==JZVideoPlayer.CURRENT_STATE_PLAYING_BUFFERING_START)) {
                                JZVideoPlayerManager.getCurrentJzvd().onPrepared();
                            } else {
                            }
                        }
                        break;
                        case Player.STATE_ENDED: {
                            JZVideoPlayerManager.getCurrentJzvd().onAutoCompletion();
                        }
                        break;
                    }
                }
            }
        });
    }

    @Override
    public void onRepeatModeChanged(int repeatMode) {

    }

    @Override
    public void onShuffleModeEnabledChanged(boolean shuffleModeEnabled) {

    }

    @Override
    public void onPlayerError(ExoPlaybackException error) {
        Log.e(TAG, "onPlayerError" + error.toString());
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onError(1000, 1000);
                }
            }
        });
    }

    @Override
    public void onPositionDiscontinuity(int reason) {

    }

    @Override
    public void onPlaybackParametersChanged(PlaybackParameters playbackParameters) {

    }

    @Override
    public void onSeekProcessed() {
        JZMediaManager.instance().mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JZVideoPlayerManager.getCurrentJzvd() != null) {
                    JZVideoPlayerManager.getCurrentJzvd().onSeekComplete();
                }
            }
        });
    }

}
`
急着上线，只是做了简单的处理，可能还有点问题

**Comment by lipangit** [comment]
什么问题

**Comment by zzh12138** [comment]
exo调整好了麻烦通知我一下

**Comment by zzh12138** [comment]
发现有个地方写错了，应该这样才对
![qq 20181008095049](https://user-images.githubusercontent.com/16078807/46589726-ad5ef780-cadf-11e8-9a2b-1f669aabfbb2.png)

**Comment by imliujun** [comment]
exoplayer 2.9.0 版本，JZExoPlayer 播放视频的时候会打印如下日志：

 W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean

**Comment by lipangit** [comment]
出错的是在哪个thread
![image](https://user-images.githubusercontent.com/2038071/47331349-47ad6680-d6ae-11e8-8266-2c5a5fd271c1.png)

**Comment by omidraha** [comment]
When I run demo application, For `CHANGE To EXOPLAYER` section ,  I get this error:

`11-16 02:04:08.096 3525-3525/cn.jzvd.demo W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean`

**Comment by lipangit** [comment]
what is your code, can you show me your code?

**Comment by omidraha** [comment]
@lipangit 

I don't change any thing, I just clone the project.

To reproduce the error:

1. clone project

`git clone https://github.com/lipangit/JiaoZiVideoPlayer.git`

2. run the `app` on Android Emulator.
3. Click on `API` button.
4. Click on `CUSTOM MEDIAPLAYER`  button.
5. Click on `CHANGE To EXOPLAYER` button.
6. Play the video.
7. The video will be played, but at `Logcat`  this output print frequently:

```
11-16 02:04:08.096 3525-3525/cn.jzvd.demo W/SimpleExoPlayer: 
Player is accessed on the wrong thread. 
See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
```

**Comment by lipangit** [comment]
Yes , I just find it. How do you think about it, How to fix it.

**Comment by omidraha** [comment]
Is it solved? or just closed?

**Comment by lipangit** [comment]
not solved

**Comment by everfire130** [comment]
有进展吗?我使用最新版本的exo也出现了` Player is accessed on the wrong thread`的问题
```
W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1195)
        at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition(SimpleExoPlayer.java:1076)
        at com.hongbeibang.app.components.hbbvideo.JZExoPlayer.getCurrentPosition(JZExoPlayer.java:169)
        at cn.jzvd.JZMediaManager.getCurrentPosition(JZMediaManager.java:71)
        at cn.jzvd.Jzvd.getCurrentPositionWhenPlaying(Jzvd.java:931)
        at cn.jzvd.Jzvd$ProgressTimerTask.lambda$run$0(Jzvd.java:1182)
        at cn.jzvd.-$$Lambda$Jzvd$ProgressTimerTask$1zOf0X1AJWTfG4NszoBAvJB_9MM.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

应该是在非主线程访问SimpleExoPlayer实例的内容都会出现警告。上面的在ProgressTimerTask线程上访问SimpleExoPlayer实例的getCurrentPosition方法就报警告了。
自己使用测试也没有出现crash的问题，在生产环境上就有部分用户报`android.view.ViewRootImpl$CalledFromWrongThreadException`的crash

我是封装的RN组件，开始是用默认的MediaInterface，没有线程问题出现，但是容易出现播放到一半需要reload且reload不一定能继续观看的问题；后来使用exo的MediaInterface，播放问题有所改善，但是由于上面的问题crash率变高了。

**Comment by lipangit** [comment]
@everfire130 不知道怎么解决

**Comment by zzh12138** [comment]
@everfire130 是不是在别的线程修改了播放内核

**Comment by lipangit** [comment]
开始播放只在runOnUiThread中进行，其他地方都没有，

**Comment by omidraha** [comment]
请说英语 ;)

**Comment by lipangit** [comment]
@omidraha If you ask in English

**Comment by bitxiao** [comment]
> @everfire130 不知道怎么解决

 用mMediaHandler作post 就不会在包错了。
JZMediaManager.instance().mMediaHandler.post(() -> {
                    long position = getCurrentPositionWhenPlaying();
                    long duration = getDuration();
                    int progress = (int) (position * 100 / (duration == 0 ? 1 : duration));
                    post(() -> onProgress(progress, position, duration));

                });

**Comment by bitxiao** [comment]
> 有进展吗?我使用最新版本的exo也出现了` Player is accessed on the wrong thread`的问题
> 
> ```
> W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
>     java.lang.IllegalStateException
>         at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1195)
>         at com.google.android.exoplayer2.SimpleExoPlayer.getCurrentPosition(SimpleExoPlayer.java:1076)
>         at com.hongbeibang.app.components.hbbvideo.JZExoPlayer.getCurrentPosition(JZExoPlayer.java:169)
>         at cn.jzvd.JZMediaManager.getCurrentPosition(JZMediaManager.java:71)
>         at cn.jzvd.Jzvd.getCurrentPositionWhenPlaying(Jzvd.java:931)
>         at cn.jzvd.Jzvd$ProgressTimerTask.lambda$run$0(Jzvd.java:1182)
>         at cn.jzvd.-$$Lambda$Jzvd$ProgressTimerTask$1zOf0X1AJWTfG4NszoBAvJB_9MM.run(lambda)
>         at android.os.Handler.handleCallback(Handler.java:751)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:159)
>         at android.app.ActivityThread.main(ActivityThread.java:6385)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
> ```
> 
> 应该是在非主线程访问SimpleExoPlayer实例的内容都会出现警告。上面的在ProgressTimerTask线程上访问SimpleExoPlayer实例的getCurrentPosition方法就报警告了。
> 自己使用测试也没有出现crash的问题，在生产环境上就有部分用户报`android.view.ViewRootImpl$CalledFromWrongThreadException`的crash
> 
> 我是封装的RN组件，开始是用默认的MediaInterface，没有线程问题出现，但是容易出现播放到一半需要reload且reload不一定能继续观看的问题；后来使用exo的MediaInterface，播放问题有所改善，但是由于上面的问题crash率变高了。

在 ProgressTimerTask的run里面用 mMediaHandler 做post就不会报错了
JZMediaManager.instance().mMediaHandler.post(() -> {
long position = getCurrentPositionWhenPlaying();
long duration = getDuration();
int progress = (int) (position * 100 / (duration == 0 ? 1 : duration));
post(() -> onProgress(progress, position, duration));

            });

**Comment by lipangit** [comment]
因为结构的设计上操作播放内核在线程中，这样频繁操作视频的时候界面不会卡顿。

demo的exoplayer 为什么不会崩溃

**Comment by bitxiao** [comment]
在SimpleExoPlayer类里面有一个检查当前线程Looper是否和初始化SimpleExoPlayer的Looper为同一个实例。
private void verifyApplicationThread() {
        if (Looper.myLooper() != getApplicationLooper()) {
            Log.w(
                    TAG,
                    "Player is accessed on the wrong thread. See "
                            + "https://google.github.io/ExoPlayer/faqs.html#"
                            + "what-do-player-is-accessed-on-the-wrong-thread-warnings-mean",
                    hasNotifiedFullWrongThreadWarning ? null : new IllegalStateException());
            hasNotifiedFullWrongThreadWarning = true;
        }
    }
我在调式代码是发现ProgressTimerTask调用时Looper发生了改变。这里只是打印了一个警告，所以不会崩溃。在 https://exoplayer.dev/troubleshooting.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean 这个里面 要求在同一线程操作ExoPlayer 原文："ExoPlayer instances need to be accessed from a single thread only" 也就是用上面的函数做判断的。所以在使用exo做播放器内核的时候。所有操作播放器的地方都要用mMediaHandler做post操作，保证线程一致。
