### ISSUE TITLE
UPDATE_PROGRESS_TIMER

### ISSUE THREAD

**Issue by zzh12138** [lipangit/JiaoZiVideoPlayer#2124]
**什么jzvd版本
最新版
UPDATE_PROGRESS_TIMER 这个变量设置为静态是否不妥。
当我是一个视频列表的时候，第一条数据处于播放中，此时计时器已经启动。然后重新渲染了后面的数据，那么就会走到onStateNormal（）方法，也就会调用到cancelProgressTimer（），把UPDATE_PROGRESS_TIMER整个取消掉了，导致进度跟时间一直不更新。

**Comment by lipangit** [comment]
是的，这个问题是暗伤，一直没有更好的突破口。

整个过程是什么操作，demo如何复现

**Comment by zzh12138** [comment]
demo因为不是网络数据，所以不会出现。我这里因为第一条数据是从外面带进去的。然后播放第一条并请求后面的数据。有时候就是这么巧，数据在第一条视频播放开始后（即已经调用了onStatePlaying（）打开计时器）才回来，然后进行渲染。调用setUp，调用了onStateNormal（）方法，就取消了计时器了。现在只能先把静态去掉了。当初设置静态的初衷是什么呢

**Comment by lipangit** [comment]
当时设么做是想免除不必要的麻烦，这么做并不是解决直接的bug。

**Comment by lipangit** [comment]
已经把static去掉了

**Comment by zzh12138** [comment]
好的咧
