### ISSUE TITLE
网络不理想的情况下，视频缓冲时没有菊花转圈的提示？

### ISSUE THREAD

**Issue by deepfish123** [lipangit/JiaoZiVideoPlayer#2125]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by antimage2015** [comment]
“可以参考旧版本，复制几行代码加回来”，请问是在哪个版本呢？6.1.2都找了一下，没有找到相应的代码呢

**Comment by lipangit** [comment]
4.8
