### ISSUE TITLE
mov格式的不支持，无法播放

### ISSUE THREAD

**Issue by yangwenwu** [lipangit/JiaoZiVideoPlayer#2126]
**需求描述

**其他app是否实现

**截图或者小视频说明
以前的版本可以的，现在这个6.3.1版本不能播放，我留个地址给大佬测试：
http://1252065688.vod2.myqcloud.com/d7dc3e4avodgzp1252065688/06404cd05285890781760620863/seiWpgsSNVQA.mov

**Comment by yangwenwu** [comment]
嗯，多谢大佬。我换了exo 可以了。

**Comment by longkehuawei** [comment]
这个怎么解决呀
