### ISSUE TITLE
定时弹广告

### ISSUE THREAD

**Issue by kingyangcn** [lipangit/JiaoZiVideoPlayer#2129]
需要每隔半小时弹出广告，有想到在setProgressAndText方法里实现，使用position%1800_000==0判断弹广告的时机，但是由于该方法回调频率不可控可能导致广告不会弹出，请问有没有推荐的方法？

**Comment by kingyangcn** [comment]
由于setProgressAndText不是每隔一毫秒都会回调的，比如1799999的时候回调了，然后1800001的时候再回调，那么就不会触发弹广告

**Comment by kingyangcn** [comment]
是时间到了弹一次，关键是必须要position%1800000==0的时候才会触发，有的时候position会跳过1800000就不会触发

**Comment by lipangit** [comment]
你可以判断时间大于某个时间，然后加个变量设置个flag，保证只触发一次。

**Comment by kingyangcn** [comment]
好的，感谢解答。
