### ISSUE TITLE
Fragment+recyclerview 滑动到屏幕之外，视频无法停止播放

### ISSUE THREAD

**Issue by WangHongTaoAH** [lipangit/JiaoZiVideoPlayer#2130]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by WangHongTaoAH** [comment]
按照demo里的写法，无法停止播放，demo是在Activity+Fragment

**Comment by WangHongTaoAH** [comment]
> 是不是少了一行代码，这个在viewPager中的判断切换fragment的时候会调用jzvd.releaseAllVideos()

我检查了一下代码，问题应该是出在nestedscrollview嵌套recyclerview这块了，因为嵌套导致监听不到recyclerview滚动了，请问作者有好的解决方案吗

**Comment by lipangit** [comment]
监听的问题你把你那边的逻辑发给我，虽然和视频没什么关系，我也帮你研究研究

**Comment by WangHongTaoAH** [comment]
> 监听的问题你把你那边的逻辑发给我，虽然和视频没什么关系，我也帮你研究研究

目前是通过对 NestedScrollView 的监听，来对RecyclerView的数据操作
((ObservableScrollView)getActivity().findViewById(R.id.nestscroll)).setScrollViewListener(new ObservableScrollView.ScrollViewListener() {
            @Override
            public void onScrollChanged(ObservableScrollView scrollView, int x, int y, int oldx, int oldy) {
                Log.d(TAG, "onScrollChanged: "+y);
                Log.d(TAG, "onScrollChanged:oldy "+oldy);

                int currentPlayPosition = JZMediaManager.instance().positionInList;
                if (currentPlayPosition!=-1)
                {

                    if (y-oldy>0)
                    {
                        if (y>DensityUtil.dp2px(getContext(),(currentPlayPosition+1)*242)+1300)//页面除了recyclerview还有别的控件，把这些控件的高度算进距离
                        {
                            if (JzvdMgr.getCurrentJzvd().currentScreen != Jzvd.SCREEN_WINDOW_FULLSCREEN) {
                                Jzvd.releaseAllVideos();
                            }
                        }
                    }else {

                    }

                }


            }
        });

**Comment by lipangit** [comment]
能不能不用nestedscrollview，给recycleView添加header可不可以

**Comment by WangHongTaoAH** [comment]
> 能不能不用nestedscrollview，给recycleView添加header可不可以

谢谢，已经在尝试改成header了。

**Comment by WangHongTaoAH** [comment]
> 能不能不用nestedscrollview，给recycleView添加header
你好，感觉即使在网络良好的情况，加载时间也有点长，3~5s的样子
