### ISSUE TITLE
播放assets下的视频的问题

### ISSUE THREAD

**Issue by YuAmbrose** [lipangit/JiaoZiVideoPlayer#2134]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

 JZDataSource jzDataSource = null;
        try {
            jzDataSource = new JZDataSource(getAssets().openFd("Ultraman.mp4"));
            jzDataSource.title = "饺子快长大";
        } catch (IOException e) {
            e.printStackTrace();
        }
//        jzplayer.setUp(jzDataSource, JzvdStd.SCREEN_WINDOW_NORMAL);
        JzvdStd.startFullscreen(VideoActivity.this,JzvdStd.class,jzDataSource);
        Jzvd.setMediaInterface(new CustomMediaPlayerAssertFolder());

播放assets下的视频。如果是 JzvdStd.startFullscreen(VideoActivity.this,JzvdStd.class,jzDataSource);
会报错
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object cn.jzvd.JZDataSource.getCurrentUrl()' on a null object reference
                  at com.example.leojq.letu_discern.CustomMediaPlayerAssertFolder.prepare(CustomMediaPlayerAssertFolder.java:36)
                  at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:148)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:163)
                  at android.os.HandlerThread.run(HandlerThread.java:61)

如果是   jzplayer.setUp(jzDataSource, JzvdStd.SCREEN_WINDOW_NORMAL);。则没问题

**Comment by lipangit** [comment]
兄弟，播放asset之前要切换播放器引擎

**Comment by beiger** [comment]
一个页面既有asset，又有sd卡里的文件，这该怎么播放呢

**Comment by lipangit** [comment]
本质上就是路径的问题，只要播放内核识别正确的路径找到文件就可以，多尝试尝试吧

**Comment by woshihfh0123** [comment]
CustomMediaPlayerAssertFolder()为什么我没找到这个文件？

**Comment by lipangit** [comment]
从demo中复制

**Comment by SmallWinter** [comment]
@YuAmbrose 嗨，你解决了吗？ 我播放有声音无图像😂

**Comment by woshihfh0123** [comment]
啥？我的一直都有声音有图像啊。我用的原生播放内核




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xdchen"<notifications@github.com&gt;; 
发送时间: 2019年12月16日(星期一) 下午3:23
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 
抄送: "西门吹雪☆"<529395283@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 播放assets下的视频的问题 (#2134)




@YuAmbrose 嗨，你解决了吗？ 我播放有声音无图像😂

**Comment by SmallWinter** [comment]
@woshihfh0123 你的内核能给看一下吗？我是播放assets文件夹下视频，播放只有声音，视频元素一直黑屏转圈圈。（PS: 老大说的简单的视频播放器测试了也都正常，硬件加速也开了，同一台测试机）

**Comment by woshihfh0123** [comment]
我播放的是请求接口获取的视频url,没试过播放本地的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xdchen"<notifications@github.com&gt;; 
发送时间: 2019年12月16日(星期一) 下午3:33
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 
抄送: "西门吹雪☆"<529395283@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 播放assets下的视频的问题 (#2134)




@woshihfh0123 你的内核能给看一下吗？我是播放assets文件夹下视频，播放只有声音，视频元素一直黑屏转圈圈。（PS: 老大说的简单的视频播放器测试了也都正常，硬件加速也开了，同一台测试机）

**Comment by SmallWinter** [comment]
@woshihfh0123 你的内核播放器能截个图给看一下吗？
