### ISSUE TITLE
列表播放，视频长度在3分12秒左右时，播放器必卡死

### ISSUE THREAD

**Issue by JackFung2015** [lipangit/JiaoZiVideoPlayer#2135]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:6.3.1
**是否和安卓版本有关系，什么版本
android 8.0
**是否和特定品牌的手机机型有关系，什么机型
小米5
**相关log是什么
BufferQueue has been abandoned
**复现流程
在列表播放模式下，播放长度超过3分钟视频，总会卡死。demo中也存在这个情况。
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
url 发来看看，这种有可能是服务器的问题，是类似阿里云七牛托管的服务器吗

**Comment by JackFung2015** [comment]
> 
> 
> url 发来看看，这种有可能是服务器的问题，是类似阿里云七牛托管的服务器吗

http://jzvd.nathen.cn/8abcdf98ec6a418b945a70fe9dd6fc7f/5cb36416a23a4da8b15d3eaa5e19a1e6-5287d2089db37e62345123a1be272f8b.mp4

**Comment by lipangit** [comment]
demo中也会吗

**Comment by lipangit** [comment]
这是阿里云的托管的服务器应该没什么问题

**Comment by lipangit** [comment]
还有其他url有这问题吗

**Comment by JackFung2015** [comment]
> 
> 
> 还有其他url有这问题吗

从github上下载的源码demo中也有这个问题，demo中只有这一个视频长度超过了3分钟，其它视频播放时长都在一分钟左右都没问题

> 
> 
> 还有其他url有这问题吗

从github上下载的源码demo中也有这个问题，demo中只有这一个视频长度超过了3分钟，其它视频播放时长都在一分钟左右都没问题

**Comment by JackFung2015** [comment]
> 
> 
> 还有其他url有这问题吗

demo中点击listview-listviewfragment viewpager-中间的fragment最后一个视频播放时会卡死，下次再打开会从上次卡死的地方接着播放，而不是从片头播放。

**Comment by JackFung2015** [comment]
> 
> 
> 还有其他url有这问题吗

demo中点击listview-listviewfragment viewpager-中间的fragment最后一个视频播放时会卡死，下次再打开会从上次卡死的地方接着播放，而不是从片头播放。

**Comment by lipangit** [comment]
亲测 华为nova2s 安卓6.0 不会卡死，你可以切换到ijkplayer播放器引擎

**Comment by lipangit** [comment]
这种适配问题很难搞

**Comment by wyy0567** [comment]
> 亲测 华为nova2s 安卓6.0 不会卡死，你可以切换到ijkplayer播放器引擎

切换到ijkplayer播放器引擎，设置缓存为5M，之后出现这个问题

**Comment by lipangit** [comment]
@wyy0567 这个到ijkplayer项目里问，超出本项目解决范围

**Comment by wyy0567** [comment]
> @wyy0567 这个到ijkplayer项目里问，超出本项目解决范围

没切换之前就只能播放四分钟，就卡了，才切换的，用的是自己服务器的链接

**Comment by lipangit** [comment]
不清楚，咱们项目主要做播放的管理，接触不到视频的编码解码的问题
