### ISSUE TITLE
无法实现JZVD

### ISSUE THREAD

**Issue by prateek54** [lipangit/JiaoZiVideoPlayer#2136]
**需求描述
while implementing the JZVD Standard along with extending my App compact activity
i got this error
`getparent android.activity clashes with getparent in view attempting to use incompatible return type`
在实现JZVD标准和扩展我的Appcompact活动时遇到了这个错误
`getparent android.activity clashes with getparent in view attempting to use incompatible return type`
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
You should extends JzvdStd.

 see smallChangeUiActivity  in demo, it will show you how to custom jzvd

**Comment by prateek54** [comment]
Thanks for the response will surely do it that way 👍
