### ISSUE TITLE
Ok button in data alert box is not visible

### ISSUE THREAD

**Issue by ManoR88** [lipangit/JiaoZiVideoPlayer#2139]
Hi ,
When using mobile data, an alert box pops up saying mobile data is currently in use and so it asks for permission. During the alert box pop up, the Ok button is not visible. 
Please help

**Comment by lipangit** [comment]
show me the screenshort ("Ok button is not visible")  what it looks like

**Comment by ManoR88** [comment]
![screenshot_2018-10-08-09-08-57-016_clickyads com myinstaapp](https://user-images.githubusercontent.com/43945872/46615112-1d4b9d00-cb35-11e8-9495-18c87d03fa62.png)

When using mobile data, an alert box pops up saying mobile data is currently in use and so it asks for permission. For that OK or Cancel option buttons are not visible.

**Comment by lipangit** [comment]
OMG！！ the dialog is system dialog, I do not know why button invisible.

Does demo run on your phone fine?

**Comment by ManoR88** [comment]
Yea Works well and thank to you for this awesome dependency 💯 👍 

By any chance can you fix that :)

**Comment by lipangit** [comment]
I think your app is a custom style, this part will affect the display of the button, and has nothing to do with this library.

**Comment by ManoR88** [comment]
Wow you are correct 👍 I changed custom style color and it starts to display the button text..... You are true genius dude thank you very much :D

**Comment by ManoR88** [comment]
Hi dude, can you tell me how to stop that system dialog warning  while using mobile data plz......

**Comment by ManoR88** [comment]
Thank you very much 👍
