### ISSUE TITLE
How to open 2 players on one screen.

### ISSUE THREAD

**Issue by mdtuyen** [lipangit/JiaoZiVideoPlayer#2141]
On my screen there are 2 screens open 2 different videos.
Now when I open the first screen then open the second screen, the first screen is black and can not be opened again.

I want to: open the second screen, the first screen pause and continue to open the first screen, the second screen pause.

What should I do?

**Comment by lipangit** [comment]
in this structure , MediaPlayer is single task，  It can not play two video at the same time.

You should make a big change to play two video at same time

**Comment by mdtuyen** [comment]
Hi
At one point only one player was played, but I wanted to switch between the two players.

**Comment by lipangit** [comment]
You need deep customization。
