### ISSUE TITLE
进行直播

### ISSUE THREAD

**Issue by huanyuan** [lipangit/JiaoZiVideoPlayer#2142]
想播放直播源视频，但你这个播放器的界面我不需要，即手势操作我自己定义，要怎么弄啊

**Comment by lipangit** [comment]
继承jzvdStd，复写onTouch函数，屏蔽手势操作。

**Comment by lipangit** [comment]
设置布局的时候原来的控件不能在布局文件中删除，否则父类JzvdStd会findVIewById报错，不能删除，只能隐藏。

**Comment by 1768803156** [comment]
感觉得加个字段
直播时候不能把手势都屏蔽，只是屏蔽快进

**Comment by lipangit** [comment]
什么字段

**Comment by 1768803156** [comment]
在JZVideoPlayer 里我加了一个 mFullScreenChange 默认值是true，在onTouch方法里面case为MotionEvent.ACTION_MOVE下多加个判断

        // 全屏模式下的CURRENT_STATE_ERROR状态下,不响应进度拖动事件.
        // 否则会因为mediaplayer的状态非法导致App Crash
        if (mFullScreenChange && currentState != CURRENT_STATE_ERROR) {
                   mChangePosition = true;
                  mGestureDownPosition = getCurrentPositionWhenPlaying();
         }

这样在直播时候，改成mFullScreenChange 改成false，横屏状态就不能快进了

**Comment by lipangit** [comment]
好解决了就好。
