### ISSUE TITLE
how can i make video replay again after completion 

### ISSUE THREAD

**Issue by smileforandroid996** [lipangit/JiaoZiVideoPlayer#2143]
i want to make video play again after completion

**Comment by smileforandroid996** [comment]
where can i write this please ??

**Comment by HelloWorld-L** [comment]
> where can i write this please ??

extends JzvdStd

on your setUp function

like this:

public void setUp(String url, String title, int screen, boolean isLoop) {
        JZDataSource dataSource = new JZDataSource(url);

        dataSource.looping = isLoop;
        super.setUp(dataSource, screen);
}
