### ISSUE TITLE
视频后台单个循环播放

### ISSUE THREAD

**Issue by Aries10** [lipangit/JiaoZiVideoPlayer#2146]
**需求描述
我们需要实现视频后台播放，后台播放的时候是单个视频播，但是播放完当前视频后，再循环一遍就停了，这个问题应该怎么解决一下呢
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
你是设置looping=true实现循环的吗？

这个问题确认一下是MediaPlayer的问题还是，单独新建个项目用MediaPlayer在后台播放也会停止吗
