### ISSUE TITLE
视频播放到4分多钟后卡住

### ISSUE THREAD

**Issue by kuang2010** [lipangit/JiaoZiVideoPlayer#2147]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:6.3.1

**是否和安卓版本有关系，什么版本
与安卓版本无关，8.0

**是否和特定品牌的手机机型有关系，什么机型
与品牌的手机机型没有关系，米6

**相关log是什么
MediaPlayerNative: info/warning (804, -1004)

**复现流程
视频链接: http://112.253.22.157/17/z/z/y/u/zzyuasjwufnqerzvyxgkuigrkcatxr/hc.yinyuetai.com/D046015255134077DDB3ACA0D7E68D45.flv

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
建议用mp4格式

https://developer.android.com/guide/topics/media/media-formats
