### ISSUE TITLE
Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference

### ISSUE THREAD

**Issue by zxianwei** [lipangit/JiaoZiVideoPlayer#2152]
**什么jzvd版本
最新版本
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况
在fragment 点击会报错
  java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.startVideo(Jzvd.java:600)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:445)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:261)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:792)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by lipangit** [comment]
如何复现的，就是进来应用直接点开始就崩溃吗？
demo会出这个问题吗？demo中如何修改会复现这个问题

以我的经验
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
就是release MediaPlayer的时候会有，在release MediaPlayer的地方打断点在堆栈中看看什么地方不应该调用release却调用了。

**Comment by greadking** [comment]
> 如何复现的，就是进来应用直接点开始就崩溃吗？
> demo会出这个问题吗？demo中如何修改会复现这个问题
> 
> 以我的经验
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
> 就是release MediaPlayer的时候会有，在release MediaPlayer的地方打断点在堆栈中看看什么地方不应该调用release却调用了。

@lipangit 你好 lipangit 我也遇到了同样的问题 实在recycler item中有viewpage中有多个JzvdStd的时候会出现这个问题 我尝试跟随源码 发现 是在jzvd.java  602 行中 scanForActivity(getContext()) 报的错 但是我没有找到解决办法 希望可以得到你的帮助

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/49274051-f0bb5e00-f4b1-11e8-88c2-86140fc3aa9e.png)

给调用MediaPlayer的release的地方打断点，在操作列表和界面的过程中不应该release的时候release了会出现这种log。

**Comment by lipangit** [comment]
列表中你做了哪些改动

**Comment by greadking** [comment]
> 列表中你做了哪些改动

我只是使用了JzvdStd这个控件 放在item中 控制了部分控件(根据业务)隐藏起来  然后就是 .setUp(
                            list.get(position).getResourceUrl(),
                            "", JzvdStd.SCREEN_WINDOW_LIST);
                   // videoPlayer.positionInList = recyclerViewPosition;
                    Glide...........thumbImageView);  并没有做其他的改动

**Comment by lipangit** [comment]
控制了部分控件(根据业务)隐藏起来

这块是如何实现的，继承jzvdStd了吗

**Comment by greadking** [comment]
> 控制了部分控件(根据业务)隐藏起来
> 
> 这块是如何实现的，继承jzvdStd了吗

我是直接使用的JzvdStd 这个控件并没有 集成创建新的view  我是以外部依赖的形式 使用的JiaoZiVideoPlayer

**Comment by greadking** [comment]
@lipangit  你好  我自己写了一个dome [](https://github.com/greadking/TestJiaoZiVideoPlayer)，  在recyclerview放置了 viewpage，   在viewpage item中怎么控制 view划出屏幕时， 初始化播放，  mainactivity中  list add 1  是一个viewpage中有一个item  2 是两个。 麻烦您帮我 看一下 我不知道怎么解决了

**Comment by greadking** [comment]
https://github.com/greadking/TestVideoViewApp

**Comment by greadking** [comment]
> 兄弟，这个17年的项目，里面更新一下jzvd，这两年来jzvd改动较大。
抱歉 还是要打扰您一下我看了gitlog 看到 jzvd 时昨天 跟新的 我不知道您说的 要更新jzvd 要怎么操作 我现在是 重新down代码 以 外部依赖的方式引入项目中的

**Comment by greadking** [comment]
> 兄弟，这个17年的项目，里面更新一下jzvd，这两年来jzvd改动较大。

抱歉 还是要打扰您一下我看了gitlog 看到 jzvd 时昨天 跟新的 我不知道您说的 要更新jzvd 要怎么操作 我现在是 重新down代码 以 外部依赖的方式引入项目中的

**Comment by greadking** [comment]
> 在你的项目中引入最新的jzvd
感谢您的回答 我尝试了 master devclop 两个分支中的jzvd  没有解决问题   我再自己尝试看源码 解决吧 谢谢你了

**Comment by greadking** [comment]
> 在你的项目中引入最新的jzvd

感谢您的回答 我尝试了 master devclop 两个分支中的jzvd 没有解决问题 我再自己尝试看源码 解决吧 谢谢你了

**Comment by greadking** [comment]
@lipangit 最终 问题解决了 是因为我不够细心 犯得低级错误 在recyclerview的addOnChildAttachStateChangeListener 的时候 我没有去获取 item中的viewpage 的fragment 中的jzvd做播放控制  这里贴出来希望可以帮到 需要的人 再次感谢lipangit
