### ISSUE TITLE
设置播放时长的问题

### ISSUE THREAD

**Issue by linxizheng** [lipangit/JiaoZiVideoPlayer#2154]
一个视频只允许播放前十秒，请问如何设置？

**Comment by lipangit** [comment]
集成JzvdStd，复写onProgress函数，取得当前播放进度，如果大于10s，写你自己的逻辑

**Comment by linxizheng** [comment]
为什么我继承后没办法复写onProgress函数？

**Comment by linxizheng** [comment]
只有一个onProgressChange函数

**Comment by lipangit** [comment]
什么版本，旧版是onSetTextAndProgress 。。。  巴拉巴拉，搜一下
