### ISSUE TITLE
首页说明该更新了

### ISSUE THREAD

**Issue by max8888888** [lipangit/JiaoZiVideoPlayer#2157]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
**是否和特定品牌的手机机型有关系，什么机型
**相关log是什么
**复现流程
**最好有截图或者视频说明情况
都没关系

git首页播放例子的setUp方法用的是之前的。复制之后会出现错误。新版本的setUp的2、3参数调换了。有时间更新一下吧~
public void setUp(String url, String title, int screen) {}

**Comment by lipangit** [comment]
好的好的，感谢提醒，最近计划复杂，思路混乱，无从下手。
