### ISSUE TITLE
在安卓8.0上style中设置windowIsTranslucent为true时会崩溃

### ISSUE THREAD

**Issue by wuyuanqing527** [lipangit/JiaoZiVideoPlayer#2158]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
8.0
**是否和特定品牌的手机机型有关系，什么机型
无关
**相关log是什么
见截图
**复现流程
将应用背景设为透明
**最好有截图或者视频说明情况
因为要实现右滑返回等功能需要设置window背景为透明。

1.应用背景透明，清单文件中未设置方向时，如果调用Jzvd.releaseAllVideos();会崩溃
![image](https://user-images.githubusercontent.com/8141439/47794224-01fe3700-dd5b-11e8-97ba-09fe852a8b6e.png)
2.将demo背景改为透明，直接崩溃
![image](https://user-images.githubusercontent.com/8141439/47793802-13930f00-dd5a-11e8-91bc-8a6e2b1339c5.png)

**Comment by lipangit** [comment]
修改应用背景之后，setRequestOrientation函数时如何避免崩溃，现在就是这个问题

**Comment by lipangit** [comment]
修改背景的代码是什么样的
