### ISSUE TITLE
视频播放完成之后 点重试JZVD: onError 1 - -2147483648 [14971449] 

### ISSUE THREAD

**Issue by bobohackbutter** [lipangit/JiaoZiVideoPlayer#2159]
W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
W/MediaHTTPConnection: readAt 1893367 / 32768 => java.net.ProtocolException
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
E/JZVD: onError 1 - -2147483648 [74271758]

**Comment by lipangit** [comment]
demo有这问题吗，换个url有这问题吗

**Comment by bobohackbutter** [comment]
demo没这个问题，我是代码直接粘贴过来的 把google这个加进来就好用，不知道为什么 Jzvd.setMediaInterface(new JZExoPlayer());

**Comment by lipangit** [comment]
他是不是说exoplayer是google开发的
