### ISSUE TITLE
关闭了硬件加速后，点击播放一直在加载状态转圈。

### ISSUE THREAD

**Issue by chenyiyao** [lipangit/JiaoZiVideoPlayer#2160]
使用的是6.3.1版本

在manifest中 activity 添加以下属性
  <activity android:hardwareAccelerated="false" />

我是用的recycler列表，点击播放后一直都是在加载状态，也没什么提示。

**Comment by lipangit** [comment]
硬件加速不能关闭，否则textureView不工作
