### ISSUE TITLE
m3u8在线加密视频，安卓7.0无法播放显示播放失败，加急件，望给指点一下。

### ISSUE THREAD

**Issue by ddviper** [lipangit/JiaoZiVideoPlayer#2161]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
7.1
**是否和特定品牌的手机机型有关系，什么机型
无关联
**Bug说明
播放m3u8在线加密视频，安卓6.0播放没问题，安卓7.0无法播放显示播放失败。
我查了下好像是由于 Android 7.0 使用 BoringSSL 替换了 OpenSSL，一些依赖系统内建 OpenSSL 的程序在一些 7.0+ 的 ROM 里可能不能使用，m3u8采用的是AES128加密，有没有可能是AES调用就是OpenSSL库解密的。我把 libopenssl.so 加入至 jniLibs 目录。重新运行还是不行，请问大神有什么解决方案么。
![2018-11-01 18 56 27](https://user-images.githubusercontent.com/7856366/47847987-e00ebe00-de07-11e8-98f5-792b87dffad8.png)

**Comment by lipangit** [comment]
这种情况如果系统的播放器搞不定可以用ijkplayer
