### ISSUE TITLE
全屏状态下，调用setState()

### ISSUE THREAD

**Issue by ancienter** [lipangit/JiaoZiVideoPlayer#2162]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
没有
**是否和特定品牌的手机机型有关系，什么机型
没有
**相关log是什么
没有
**复现流程

**最好有截图或者视频说明情况
在非全屏模式下，调用下面方法可以终止播放，但是在全屏模式下，调用下面方法没有任何响应
jzvdExt.setState(JzvdExt.CURRENT_STATE_AUTO_COMPLETE);

**Comment by lipangit** [comment]
全屏和非全屏是两个实例，应该用JzvdManager.getcurrentJzvd(). setState(JzvdExt.CURRENT_STATE_AUTO_COMPLETE);; 来操作当前的播放器实例。

另外setState函数只是修改ui，还需要单独操作MediaPlayer。
