### ISSUE TITLE
VideoPlayer isn't working

### ISSUE THREAD

**Issue by meetn33b** [lipangit/JiaoZiVideoPlayer#2164]
Hello, I'm following the step-by-step guide provided in the library faq, however, the player does not play the video. It just indicates that it is loading but does not show the video. Is it necessary to configure more than the setup?

![2](https://user-images.githubusercontent.com/44716670/47947066-407b2980-def4-11e8-85f5-d3ed0e5ced85.png)
![1](https://user-images.githubusercontent.com/44716670/47947067-407b2980-def4-11e8-9bf6-c8570589e9e3.png)

**Comment by lipangit** [comment]
did you config it in androidmanifest.xml

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/47947613-fbd6a900-df5a-11e8-8524-76b631805f4b.png)

**Comment by meetn33b** [comment]
I can't believe that was just that. Thank you, sir.
