### ISSUE TITLE
全屏模式出现白条

### ISSUE THREAD

**Issue by ancienter** [lipangit/JiaoZiVideoPlayer#2165]
**什么jzvd版本
3.6.1
**是否和安卓版本有关系，什么版本
无
**是否和特定品牌的手机机型有关系，什么机型
荣耀8 Honor8（FRD-AL10）（EMUI8.0.0）（Andorid8.0.0）
![image](https://user-images.githubusercontent.com/36272003/47987754-5159b400-e11b-11e8-9ba5-e2a77a7b7a02.png)

**相关log是什么

**复现流程
从小屏模式，点击全屏按钮后全屏模式上方有白条，没有占满全屏
**最好有截图或者视频说明情况
![image](https://user-images.githubusercontent.com/36272003/47987806-74846380-e11b-11e8-98bf-a0d5d22bef77.png)

**Comment by lipangit** [comment]
这个白条应该是状态栏（还是什么栏）没完全隐藏，你看看这个特定的手机在调用横屏和全屏代码的时候是不是就这样，这个手机如何适配

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48243622-3d17fe80-e41c-11e8-816f-17f53021067e.png)

兄弟，单独试试这个函数，看看调用哪个函数能让白条消失

**Comment by cdcdec** [comment]
试了试这个函数  全屏时  
还是有个横白条

**Comment by lipangit** [comment]
@cdcdec 首先要找出来哪个行数能让你的横白条消失，然后把这行代码在适当的时候调用。

这是两步，你先研究第一步
