### ISSUE TITLE
如何实现点播放按钮，进行条件判断之后再播放。

### ISSUE THREAD

**Issue by ddviper** [lipangit/JiaoZiVideoPlayer#2166]
**需求描述
我们有一个视频列表播放需求，但是每次视频URL都需要经过接口获取再解密获得，是个耗时操作，我想在加载ListView的时候只显示缩略图，在点击播放的时候才去通过接口获取URL,现在我通过复写OnClick的方法拦截点击播放按钮，但是好像还是会调用父类的播放方法，一点击播放没有setup URL就会闪退。请问要实现这个功能有什么好的实现方案么
**其他app是否实现

**截图或者小视频说明

**Comment by ddviper** [comment]
其实我就是想通过复写子类拦截父类的点击事件，等处理完成我自己的业务逻辑之后再调用播放功能。

**Comment by lipangit** [comment]
复写onTouch函数之后，把父类的super.onTouch()放到你的逻辑之后，甚至是不调用，就没有父类的逻辑了
