### ISSUE TITLE
未setup设置url时，点击播放会崩溃，报null异常

### ISSUE THREAD

**Issue by VinPin** [lipangit/JiaoZiVideoPlayer#2169]
6.3.1版本，未设置url时点击缩略图或播放按钮时播放会崩溃，原因是jzDataSource为null
`
if (jzDataSource.urlsMap.isEmpty() || jzDataSource.getCurrentUrl() == null) {
                Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
                return;
            }
`
这段代码应该再增加对jzDataSource为null的判断，如：
`
if (jzDataSource == null || jzDataSource.urlsMap.isEmpty() || jzDataSource.getCurrentUrl() == null) {
                Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
                return;
            }
`

**Comment by lipangit** [comment]
feixed

**Comment by VinPin** [comment]
你还漏了个缩略图的点击中也要增加这个判断呀
if (i == R.id.thumb) {
            if (jzDataSource == null || jzDataSource.urlsMap.isEmpty() || jzDataSource.getCurrentUrl() == null) {
                Toast.makeText(getContext(), getResources().getString(R.string.no_url), Toast.LENGTH_SHORT).show();
                return;
            }
}

**Comment by lipangit** [comment]
没毛病老铁，这种小修改可以直接提交pr，非常方便
