### ISSUE TITLE
没有播放的情况下，点击全屏按钮会跳到竖屏的界面，并且没有自动播放

### ISSUE THREAD

**Issue by woshiyizhijiao** [lipangit/JiaoZiVideoPlayer#2171]
**需求描述

理想状态是 全屏横屏，自动播放

**截图或者小视频说明

我看这个地方是空的
![1541845354 1](https://user-images.githubusercontent.com/19473420/48300299-b7787980-e515-11e8-99b6-af902b54eb52.png)

**Comment by lipangit** [comment]
首先没播放的状态下全屏按钮被缩略图盖住了点不到。

如果非要这样做的话，可以继承onClick函数，然后在全屏按钮点击之后调用startVideo函数，开始播放

**Comment by woshiyizhijiao** [comment]
需求是需要刚开始把全屏按钮打开的
我试了两种方法都不是很理想
1：
       /**
         * 全屏播放
         */
        fullscreenButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                VideoCourseView.super.onClick(v);
                if (currentState == CURRENT_STATE_AUTO_COMPLETE)
                    return;
                if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
                    //quit fullscreen
                    backPress();
                } else {
                    JzvdStd.startFullscreen(getContext(), VideoCourseView.class, jzDataSource);
                }
            }
        });
这种方法播放之后，我如果点击返回键就把我之前的见面关闭掉了，应该是返回横屏继续播放的

2
        /**
         * 全屏播放
         */
        fullscreenButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
//                VideoCourseView.super.onClick(v);
                if (currentState == CURRENT_STATE_AUTO_COMPLETE)
                    return;
                if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
                    //quit fullscreen
                    backPress();
                } else {
                    Log.d(TAG, "toFullscreenActivity [" + this.hashCode() + "] ");
                    onEvent(JZUserAction.ON_ENTER_FULLSCREEN);
                    startWindowFullscreen();
                    startVideo();
                }
            }
        });
也是复写点击事件，最后添加startVideo();方法，这样进入全屏还是竖屏状态的，而且并没有播放

这两种情况我断点后发现
    View old = vp.findViewById(R.id.jz_fullscreen_id);
        if (old != null) {
            vp.removeView(old);
        }
走到这里old 都是空的

**Comment by lipangit** [comment]
先startVidew()开始播放，再点击全屏按钮，fullscreenButton.performClick();  这样就会在全屏播放了

**Comment by woshiyizhijiao** [comment]
if (currentState == CURRENT_STATE_AUTO_COMPLETE)
                    return;
                if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
                    //quit fullscreen
                    backPress();
                } else {
                    long currentPositionWhenPlaying = getCurrentPositionWhenPlaying();
                    if (currentPositionWhenPlaying == 0) {
                        startVideo();
                        startWindowFullscreen();
                    } else {
                        VideoCourseView.super.onClick(v);
                    }
                }

多谢，这种写法解决了
