### ISSUE TITLE
Video loading percentage 

### ISSUE THREAD

**Issue by ManoR88** [lipangit/JiaoZiVideoPlayer#2172]
Hello JiaoZiVideoPlayer creator how to show percentage of video loading at the time of starting in jzvd STD ? and after full video play finishes, how to perform a task ? kindly help me

**Comment by lipangit** [comment]
1.extends JzvdStd
2.Overrite onProgress() function

that function will show you the progress and total duration.

**Comment by ManoR88** [comment]
Hi again is there anyway to hide seekbar only plz :(

**Comment by lipangit** [comment]
1.extends JzvdStd
2. override  ...state function, hide or visiable the seekbar in every video state.

**Comment by ManoR88** [comment]
ok will try it... thank you lipangit 👍
