### ISSUE TITLE
关于全屏

### ISSUE THREAD

**Issue by manburenshenglu** [lipangit/JiaoZiVideoPlayer#2173]
**需求描述
我的需求是这样的：我想默认一进来就是横屏时的全屏效果如何实现

**其他app是否实现

**截图或者小视频说明
![image](https://user-images.githubusercontent.com/13146756/48353917-75913400-e6cb-11e8-8cc2-ff0ce244c03b.png)

**Comment by woshiyizhijiao** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/2171   可以参考下这个

**Comment by manburenshenglu** [comment]
谢谢楼主，非常感谢你写你的轮子！我已经自己实现了。我还有个问题：sdk中有没有设置循环播放的方法或者可以参考的代码在哪部分，需求就是播放完成后自动重新播放，而不要再点击重播按钮才能再次播放。

**Comment by lipangit** [comment]
循环播放搜索demo中looping字样

**Comment by manburenshenglu** [comment]
> 循环播放搜索demo中looping字样
感谢，已按照楼主的提示，实现想要的需求了！昨晚这个需求后，很想从头到尾拜读一下楼主写的代码，有很多思考方式值得我学习

**Comment by lipangit** [comment]
么么哒，准备转成kotlin
