### ISSUE TITLE
我照着demo中未播放状态，直接点全屏，点击播放，一直在转圈而且缩略图是不显示的

### ISSUE THREAD

**Issue by ypp0623** [lipangit/JiaoZiVideoPlayer#2174]
**需求描述

**其他app是否实现
![nqe9h1y m02 igz9 bhjo4](https://user-images.githubusercontent.com/30793756/48453263-9b165e80-e7ed-11e8-9799-222c86286441.png)

**截图或者小视频说明

**Comment by lipangit** [comment]
你的需求是什么

**Comment by ypp0623** [comment]
是在未播放的情况下，可以直接点击全屏播放，全屏播放完不退出，而且全屏的时候也要有缩略图显示

**Comment by lipangit** [comment]
解决了吗，进入全屏之前要调用startVideo开始播放，然后进入全屏，有问题qq问我
