### ISSUE TITLE
Video loading failed when using the mobile network

### ISSUE THREAD

**Issue by axel7083** [lipangit/JiaoZiVideoPlayer#2176]
Hello, I download and compile https://github.com/lipangit/JiaoZiVideoPlayer. I just change the video link, I setup to a source video.
When I'm using the wifi I don't have any problem, the video load properly. But when I'm using the mobile network, first I have a warning ( showWifiDialog(); ) and it display "Video loading failed".
I tried to remove the condition of calling showWifiDialog() by removing some lines, and the result is the same, I don't have the warning but the video stay in failed.

**Comment by lipangit** [comment]
What log when faild
