### ISSUE TITLE
点击播放的时候要准备好久才能播放，菊花转了有5到10秒，而同个视频在IOS上都是秒播的，请问这个要怎么优化

### ISSUE THREAD

**Issue by RoyBiao** [lipangit/JiaoZiVideoPlayer#2177]

**Comment by Tianmu19** [comment]
大兄弟，我也遇到这问题，查了资料是mediaplayer在4.4之上更改了底层，无法设置缓存时间，真是没办法。只能用ffmpeg等其他播放器

**Comment by lipangit** [comment]
播放的问题取决于播放器引擎，咱们项目本质做的是播放管理和ui，可以一行代码切换到ijkplayer或者exoplayer等其他播放器引擎。
