### ISSUE TITLE
我想播放器播放一个集合的视频，在全屏的状态下播放完了也不退出全屏，而是继续播放

### ISSUE THREAD

**Issue by AndroidSXK** [lipangit/JiaoZiVideoPlayer#2178]
**需求描述：
1.我想播放器播放一个集合的视频，
2.在全屏的状态下播放完了也不退出全屏，而是继续播放

**Comment by lipangit** [comment]
demo中有不退出全屏的例子，在smallChangeUIActivity中，复写onAutoComplete函数，这个函数在播放完成会回调，然后在这里播放下一个视频。

**Comment by ChristoferAlexander** [comment]
Could you provide an example how to use the class after you Override it ?

 I tried to use like: 

Jzvd.startFullscreen(getContext(),
                JzvdStdAutoCompleteAfterFullscreen.class,
                mVideo.getFilePath(),
                mVideo.getTitle());

and :

JzvdStdAutoCompleteAfterFullscreen.startFullscreen(getContext(),
                JzvdStdAutoCompleteAfterFullscreen.class,
                mVideo.getFilePath(),
                mVideo.getTitle());

But the video screen remains black. Thank you.

**Comment by lipangit** [comment]
Screen black,   Open Hardware Acceleration?

**Comment by zhangqifan1** [comment]
楼主全屏自动播放解决了么...
