### ISSUE TITLE
有木有志愿者优化一下按钮的点击事件的代码

### ISSUE THREAD

**Issue by lipangit** [lipangit/JiaoZiVideoPlayer#2181]
兄弟们，最近发现代码里的按钮比较多，设置起来比较麻烦，可以在布局文件中设置按钮的点击，这样更方便。要求以click开头，其他驼峰式。哪位小伙伴志愿者愿意改一下

![image](https://user-images.githubusercontent.com/2038071/48659791-4bf05800-ea91-11e8-9a4a-57d678bf4808.png)

**Comment by zhangshaobo87** [comment]
我改完了 但是提交不上去

**Comment by lipangit** [comment]
兄弟，这个改完了，不好意思忘关了，下回各种进展都在issue里体现
![image](https://user-images.githubusercontent.com/2038071/48882948-3e075200-ee58-11e8-9f3e-7841eeec9f38.png)


兄弟，加我qq，和微信，把你拉到开发者群里
