### ISSUE TITLE
全屏播放完不退出继续循环播放的话，不显示缩略图，会黑屏

### ISSUE THREAD

**Issue by ypp0623** [lipangit/JiaoZiVideoPlayer#2183]

**Comment by lipangit** [comment]
你的需求是什么。

做的过程中遇到哪些阻碍，比如不显示缩略图，你想在什么时候显示缩略图，但是无法实现

**Comment by ypp0623** [comment]
全屏循环播放，在每一次重新开始的时候要显示缩略图

**Comment by ypp0623** [comment]
希望能够在全屏循环播放的情况下，每一次从头开始播放的时候，显示缩略图，类似正常尺寸播放的那种，还有除了第一次，将加载的圆圈去掉

**Comment by lipangit** [comment]
这种需求本质上是控件的显示与否，这种纯UI的操作完全可以自己完成，继承JzvdStd，复写进入相应状态的函数，操作控件的是否显示
