### ISSUE TITLE
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/ZYL/.gradle/caches/transforms-1/files-1.1/jiaozivideoplayer-6.4.0.aar/59e5ae9eb97af9cfc870a67316fe8bdc/jars/classes.jar

### ISSUE THREAD

**Issue by zhangyinglong1993** [lipangit/JiaoZiVideoPlayer#2185]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by zhangyinglong1993** [comment]
6.4.0这个样子，6.3.1可以运行

**Comment by zhangshaobo87** [comment]
是的 ，我这也是一样 更新到6.4.0后编译过不了 今天找了一天的问题，还没解决，后来没办法又回退到6.3.1了。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48705011-09668100-ec33-11e8-850a-34e08c0bd5f8.png)

老铁亲测build通过

**Comment by zhangshaobo87** [comment]
我昨天下了你的Demo 运行是没有任何问题的，就是不知道为什么老项目里边由6.3.1 升级到 6.4.0会编译不过，报的错在百度搜很多人说是依赖库冲突，但是我检查了很久并没有发现哪里冲突，然后我将你的源码copy了一份放到项目里运行就可以编译过，所以很是郁闷。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48750843-3dd24f80-ecbc-11e8-9990-f8cd98aad7db.png)

试试加上这个

**Comment by zhangshaobo87** [comment]
加了这个报这个错
 Java 8 language support, as requested by 'android.enableD8.desugaring= true' in your gradle.properties file, is not supported when 'android.useDexArchive= false'.

然后我在gradle.properties里加上android.enableD8.desugaring= true 和 android.useDexArchive= true后再次编译就冒的问题了，以上亲测可用~！

**Comment by toureh** [comment]
Adding this to build.gradle solved it for me:
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
[Source](https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26)
