### ISSUE TITLE
播放高清视频，界面卡顿严重

### ISSUE THREAD

**Issue by kuang2010** [lipangit/JiaoZiVideoPlayer#2186]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:6.3.1

**是否和安卓版本有关系，什么版本
与安卓版本无关，8.0

**是否和特定品牌的手机机型有关系，什么机型
与品牌的手机机型没有关系，米6

**相关log是什么
无

**复现流程
视频链接：http://1258073054.vod2.myqcloud.com/14bd7d85vodcq1258073054/f52922b35285890783050746755/HQlXOyDcvL8A.mp4

**最好有截图或者视频说明情况
使用Jzvd.setMediaInterface(new CustomMediaPlayerAssertFolder());播放本地下载后的视频没问题，很流畅。
使用Jzvd.setMediaInterface(new JZMediaIjkplayer()); 或其他两个内核播放，界面卡顿严重。请大神帮忙看看该怎么优化下，非常感谢了.

**Comment by lipangit** [comment]
这个是切换播放器引擎，demo提供的现成的播放器引擎有三种，安卓系统的MediaPlayer，ijkplayer，exoplayer。
CustomMediaPlayerAssertFolder这个和JZMediaIjkplayer是一样的都是系统的MediaPlayer，界面卡顿严重具体是什么现象，可以录视频看看

**Comment by kuang2010** [comment]
界面卡顿严重就是点播放后没有进度，过10多分钟，又能播放2秒，然后又卡住。。。

录的视频：https://github.com/kuang2010/test_jzvideo1121/blob/master/test.mp4

**Comment by kuang2010** [comment]
多谢大神指点，视频确实需要格式化才行，Thanks♪(･ω･)ﾉ
