### ISSUE TITLE
倍速播放完成后重播应该继续之前的倍速

### ISSUE THREAD

**Issue by VinPin** [lipangit/JiaoZiVideoPlayer#2191]
**需求描述

**其他app是否实现

**截图或者小视频说明

你的demo里的JzvdStdSpeed，倍速播放完成后点击重播是默认的倍速，但是倍速按钮text仍然显示之后的倍速，这是个BUG。另外如果想重播继续之前的倍速播放，应该怎么修改合适呢？

**Comment by lipangit** [comment]
是的是的

**Comment by lipangit** [comment]
复写onPrepared 函数，视频准备完成将要播放的时候设置倍速
