### ISSUE TITLE
跳转到全屏的动画

### ISSUE THREAD

**Issue by 418788724** [lipangit/JiaoZiVideoPlayer#2195]
**我想从视频列表页切换全屏时如何添加动画呢？？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48877781-c9c0b480-ee3f-11e8-9ccc-c4fcbff0a7ab.png)

参考这个分支，但是动画不成熟，很生涩，所以未被采用，你有什么好的方法可以分享出来
