### ISSUE TITLE
使用默认的player播放，几百K的短视频播放没问题，但是2，3M的视频就播放不了，显示视频加载失败。

### ISSUE THREAD

**Issue by dvzhou** [lipangit/JiaoZiVideoPlayer#2197]
**什么jzvd版本
最新版
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
W/MediaHTTPConnection: readAt 3639927 / 32768 => java.net.ProtocolException
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
I/MediaPlayer: [HSM] stayAwake false uid: 10276, pid: 7106
E/JZVD: onError 1 - -2147483648 [38720139] 
**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
目测视频源的问题

**Comment by dvzhou** [comment]
恩，确实是视频源的问题，应该是http提交时有问题，谢谢大牛！
