### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by Biswangluo** [lipangit/JiaoZiVideoPlayer#2201]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
8.1
**是否和特定品牌的手机机型有关系，什么机型
红米6a
**相关log是什么
![qq 20181123094933](https://user-images.githubusercontent.com/2362450/48926085-9ea09880-ef05-11e8-881b-9667ccee01a5.png)

**复现流程
切换视频来回拖拽进度条 低概率OOM 视频内容 是高清视频 在1G以上
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48927556-bbdb6400-ef11-11e8-94a6-73eca0250f20.png)

是这行吗

**Comment by Biswangluo** [comment]
点进度条  切换进度条的时候 有概率OOM 就是这个地方

**Comment by lipangit** [comment]
兄弟，有啥进展吗

**Comment by Biswangluo** [comment]
JzvdStd cancelDismissControlViewTimer TimerTask 报了一个很离奇的OOM，网上说是部分华为机器线程数超出限制？ 但是cancel 之后线程就销毁了，所以一直困扰了很久了，近期更换Handler方案，通过Handler发送延迟消息 2.5秒后关闭控制View 还在线上观察中
