### ISSUE TITLE
视频分辨率是1920（宽）*3600（高），

### ISSUE THREAD

**Issue by hyandroid** [lipangit/JiaoZiVideoPlayer#2202]
视频分辨率是1920（宽）*3600（高），播放后视频被缩放了 ，宽高比例不对

**Comment by hyandroid** [comment]
长图是正常比例的

**Comment by hyandroid** [comment]
低分率 比如 （宽*高）720*1280的视频就没问题

**Comment by lipangit** [comment]
demo就是这样的吗？
你看demo的changeSizeActivity，里面有画面的比例。

**Comment by hyandroid** [comment]
demo也是这样的，没找到有changeSizeActivity这个啊，附上视频地址：http://lcfile.xichuangzhu.com/a2fa1920fab4c95581f2.mp4

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48977855-900cd980-f0dd-11e8-876b-cb414e22957f.png)

华为nova2s 正常播放 全屏也没问题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48977857-a4e96d00-f0dd-11e8-9cd2-5454d4b8a34f.png)


断点父类这个函数，看MediaPlayer返回的宽高对吗

**Comment by hyandroid** [comment]
我这里确实是这样，手机是小米6      Log.i("size",JZMediaManager.instance().currentVideoWidth+"=="+JZMediaManager.instance().currentVideoHeight);
打印得到的宽高是1920*1080


![screenshot_2018-11-26-10-41-42-074_cn jzvd demo](https://user-images.githubusercontent.com/11974245/48990158-4d441380-f168-11e8-85b3-daed32f7a447.png)

**Comment by hyandroid** [comment]
我用一加手机测试也是这样，是不是要设置什么参数，demo中的代码我没改过。

**Comment by lipangit** [comment]
下载最新的develop分支，demo中什么都不改动，只替换url，就会出刚才的问题？

**Comment by lipangit** [comment]
宽高应该是写反了

**Comment by hyandroid** [comment]
对，我就是下载最新的  ，然后替换url ,就会这样

**Comment by hyandroid** [comment]
怎么搞啊这个，有办法吗

**Comment by lipangit** [comment]
MediaPlayer返回的宽高是反的！！  你确定是在https://github.com/lipangit/JiaoZiVideoPlayer 下载的demo吗，以前没听过过这种情况

**Comment by hyandroid** [comment]
我又下了一遍demo， 还是这样啊。肯定不是宽高写反了，如果反了的话，别的视频也应该有问题，但是别的都正常。

**Comment by lipangit** [comment]
什么别的正常，别的视频在这个手机上宽高正常吗

**Comment by hyandroid** [comment]
是啊

**Comment by lipangit** [comment]
那就是视频的问题啊  老铁

**Comment by hyandroid** [comment]
你那手机怎么就没问题呢

**Comment by lipangit** [comment]
要么换个播放器内核试试
