### ISSUE TITLE
发现一个很严重的Bug;  使用 Demo 中的RecycleView 滑动的时候默认会关闭当前播放的条目视频；

### ISSUE THREAD

**Issue by combing520** [lipangit/JiaoZiVideoPlayer#2204]
**什么jzvd版本
6.4.0
**是否和安卓版本有关系，什么版本
Android 大于 4.0的版本
**是否和特定品牌的手机机型有关系，什么机型
么有
**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
滑动的时候默认会关闭当前播放的条目视频

兄弟，这句话什么意思，视频滑出屏幕是要关闭播放的，没错

**Comment by combing520** [comment]
嗯，如果是滑动出屏幕播放器关闭，没错的话，那滑动回来是否应该继续播放？ 不然的话，体验上是否会有点诡异； 用户滑出屏幕，当前视频没有播放了，然后滑动回来还要继续的点击， 如果重复这种操作几次的话，是不是很难受？

**Comment by lipangit** [comment]
你说的功能可以实现，咱们的列表和ui都是高仿头条的。
