### ISSUE TITLE
按照官方给出的方法，发现在我原有的项目里加载不了视频

### ISSUE THREAD

**Issue by w-g-b** [lipangit/JiaoZiVideoPlayer#2205]
**什么jzvd版本
6.4.0
**是否和安卓版本有关系，什么版本
测了几个版本都不行，我另外新建的工程则没有问题
**是否和特定品牌的手机机型有关系，什么机型
与机型无关
**相关log是什么
没有错误日志，只显示加载的圆圈，网络只有几k（我的网络没有问题，单独的项目可以正确加载显示）
**复现流程

**最好有截图或者视频说明情况

**Comment by w-g-b** [comment]
![image](https://user-images.githubusercontent.com/23725154/48966587-62595f00-f00f-11e8-855c-76f73ff8eb9e.png)

**Comment by lipangit** [comment]
网络权限加了吗？什么也没改，没理由无法播放呀

**Comment by w-g-b** [comment]
加了网络权限了，继承在我原来的项目里就直接在那里转圈，加不出来。
我另外新建项目测试的时候没有问题，不知道什么原因，也没有报错

**Comment by lipangit** [comment]
1.确认一下MediaPlayer是否启动

**Comment by lipangit** [comment]
MediaPlayer启动了 它的log很明显的

**Comment by w-g-b** [comment]
哦，可以了，开启硬件加速就好了！！！
感谢感谢

**Comment by w-g-b** [comment]
之前一直没留意看log，不知道哪里出问题
