### ISSUE TITLE
全屏下调用setup方法播放下一集视频，但播放的还是之前的视频

### ISSUE THREAD

**Issue by dongfangmingjia** [lipangit/JiaoZiVideoPlayer#2207]
**什么jzvd版本
6.2.10
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程
播放A视频点击全屏按钮进入全屏播放模式，A视频播放完成后（不退出全屏）自动播放B视频，调用setup将视频地址设置后，还是播放的A视频，请问这个该怎么解决
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
setUp只在初始化的时候调用一次，播放下一集视频本质就是切换url，调用changeUrl函数

**Comment by dongfangmingjia** [comment]
了解，谢谢

**Comment by zhangqifan1** [comment]
老哥,这个功能出来了么,,可不可以指点一哈子

**Comment by dongfangmingjia** [comment]
我的处理是在调用setUp方法的时候将视频列表、当前播放位置传过去，当播放完A之后在视频列表取下一个视频地址然后进行播放。
setUp(url: String?, screen: Int, vararg objects: Any?)这个方法里的第三个参数传视频列表和当前播放位置即可

**Comment by dongfangmingjia** [comment]
你可以把要请求的下一个URL的参数放到列表里传递过去

**Comment by zhangqifan1** [comment]
具体是哪些个方法啊....

**Comment by zhangqifan1** [comment]
我只是在onAutoComplete 里边做了 回调  重新changurl 但是 全屏 和 非全屏 不是一个实例~~~

**Comment by dongfangmingjia** [comment]
我没有用changurl，就是在onAutoComplete方法里面拿到下一个视频的id，然后请求接口返回视频URL然后再调用setUp方法将视频url设置进去进行播放的

**Comment by zhangqifan1** [comment]
大哥,加个QQ吧,我就这一个功能,没别的事,,,你加我也行,852780161
