### ISSUE TITLE
列表播放，分页刷新数据时，TextureView会被销毁，导致视频有声音，没有图像

### ISSUE THREAD

**Issue by kuang2010** [lipangit/JiaoZiVideoPlayer#2208]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:6.3.1

**是否和安卓版本有关系，什么版本
与安卓版本无关，8.0

**是否和特定品牌的手机机型有关系，什么机型
与品牌的手机机型没有关系，米6

**相关log是什么
onSurfaceTextureDestroyed(SurfaceTexture surfaceTexture) 被执行

**复现流程
项目用RecycleView 分页加载数据实现列表播放，使用的内核是ijkplayer，当加载完第二页的数据并调用notifyDataSetChanged()方法刷新页面，页面刷新后，在第一页可见的item里，播放的视频会出现有声音，没图像的问题。调试了JZMediaManager类，发现onSurfaceTextureDestroyed(SurfaceTexture surfaceTexture) 被执行了，估计是TextureView被销毁了。请教大神该如何解决这个问题呢

**最好有截图或者视频说明情况
暂无

**Comment by lipangit** [comment]
item滑动出屏幕的时候textureView会被销毁，item回来的时候需要重新添加textureView

**Comment by kuang2010** [comment]
嗯，主要是正在播放视频的那个item还没被滑动出屏幕，它的textureView就被销毁了。    我用的recycleview做了分页加载的功能，数据个数增加后调用notifyDataSetChanged()方法刷新页面总是导致正在播放视频的textureView被销毁。

**Comment by lipangit** [comment]
是的，notifyDataSetChanged这个函数会调用getView函数，会调用setUp函数，视频会被release

**Comment by kuang2010** [comment]
那请问大神，对于这种要做分页加载的列表视频该怎样优化一下代码，使调用getView函数时，不release掉正在播放的视频呢？求解...

**Comment by lipangit** [comment]
这个问题一直没解决，notifyData的时候必然要getView，这步拦截不了，你可以加一个标记，如果是notifyData的getView在100ms以内不调用jzvd的setUp，这样做可能可能会出现问题。也没想到有其他方法

**Comment by kuang2010** [comment]
好滴，多谢大神指导！也希望能早点解决这个问题哈

**Comment by lipangit** [comment]
你现在怎么解决的
