### ISSUE TITLE
Error: Invoke-customs are only supported starting with Android O (--min-api 26)

### ISSUE THREAD

**Issue by Android-Adam** [lipangit/JiaoZiVideoPlayer#2209]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
min api is 16 ， 这个log是在哪看到的

**Comment by lipangit** [comment]
是不是你的项目最低26呀，
![image](https://user-images.githubusercontent.com/2038071/49059708-13950a80-f245-11e8-952e-fafd893d7d5a.png)

然后还要加这个
