### ISSUE TITLE
各种空指针，写的那么不严谨吗？

### ISSUE THREAD

**Issue by awdvhil9** [lipangit/JiaoZiVideoPlayer#2212]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by zhangshaobo87** [comment]
没图没日志，你在说啥

**Comment by lipangit** [comment]
骚年你提的问题也不大严谨
