### ISSUE TITLE
只要引用这个包就出问题

### ISSUE THREAD

**Issue by Jay-YaoJie** [lipangit/JiaoZiVideoPlayer#2213]
问题如下
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.lang.UnsupportedOperationException (no error message)

我已经添加 了 multiDexEnabled true

![image](https://user-images.githubusercontent.com/18596432/49196698-dce6fd80-f3c6-11e8-9771-cf441cf64091.png)

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/2203  看一眼这个

**Comment by Jay-YaoJie** [comment]
https://blog.csdn.net/Jeff_YaoJie/article/details/84620567

**Comment by lipangit** [comment]
ok
