### ISSUE TITLE
全屏的一个 bug

### ISSUE THREAD

**Issue by ThugKd** [lipangit/JiaoZiVideoPlayer#2215]
** 什么jzvd版本
*6.4.0*
---

** 复现流程
demo中的orientation
1. 点击进去全屏
2. 返回正常模式
3. 点击home键回到桌面
4. 点击图标进入
5. 点击全屏按钮，实际上不是全屏
 ---

** 最好有截图或者视频说明情况
稳定重现

**Comment by lipangit** [comment]
是的，已经修复，屏幕方向的控制应该放到onResume中。d800460

**Comment by ThugKd** [comment]
好的 谢谢

**Comment by ThugKd** [comment]
建议有时间集成leakcanary解决一下内存泄漏问题吧  
描述一下我遇到的：

版本6.3.1
demo中的orientation全屏之后退出，会出现内存泄漏

**Comment by lipangit** [comment]
兄弟，你觉得这个Timer怎么处理好

**Comment by ThugKd** [comment]
兄弟，发现几个问题：
版本 6.4.0
1. **ActivityApiOrientation**中的**Jzvd.FULLSCREEN_ORIENTATION**变量的值设置错了

2.我找到全屏之后 **ProgressTimerTask**内存泄漏的原因了：在**onPause**中调用了**Jzvd.releaseAllVideos();**， 然后调用了**JzvdMgr.completeAll();** ，在**completeAll**中进行了判空，不为空才执行**complete()**。**But** 你在**playOnThisJzvd()**方法中调用了 **clearFloatScreen()**方法，而**clearFloarScreen()**方法**最后一行**你执行了 **JzvdMgr.setSecondFloor(null); ** 。。。 **So**你在退出**ActivityApiOrientation**执行的**JzvdMgr.completeAll();** 根本不会执行**SECOND_FLOOR_JZVD.onCompletion();** 。。。所以就导致了内存泄漏

**Comment by ThugKd** [comment]
所有全屏之后都会出现这个问题，比较严重，请尽快修复。thx！

**Comment by lipangit** [comment]
clearFloatScreen的时候  置空之前complete是不是能解决，试试最新的develop分支

**Comment by ThugKd** [comment]
是的，值置控之前执行complete就可以了

**Comment by ThugKd** [comment]
我看了一下由于JzvdMgr.setSecondFloor(null)这个导致SECOND_FLOOR_JZVD.onComplete()方未执行，导致了很多问题，像播放完之后，不能自动熄屏的问题也是。

**Comment by lipangit** [comment]
有什么修复的思路吗
