### ISSUE TITLE
UI控件始终显示

### ISSUE THREAD

**Issue by 418788724** [lipangit/JiaoZiVideoPlayer#2217]
**需求描述

我想实现一个是否静音的按钮，怎样让它在视频播放时始终显示，

**Comment by lipangit** [comment]
参考demo的smallChangeUiActivity，里面有一个非全屏静音全屏有声的例子，看了吗

**Comment by lipangit** [comment]
添加你的静音按钮，默认是全屏和非全屏都显示的

**Comment by 418788724** [comment]
我让这个按钮在非全屏时显示，但demo默认的是当我触碰屏幕播放时才显示，但是我想让这个按钮一直是显示的状态,不管是否播放

**Comment by 418788724** [comment]
我想让它是一直显示状态，而非触碰过后的短暂显示

**Comment by lipangit** [comment]
你看这个自定义的源码了吗，把全屏的判断去掉

**Comment by 418788724** [comment]
解决啦，感谢大佬
