### ISSUE TITLE
音调、音轨设置支持吗 ？

### ISSUE THREAD

**Issue by cydenghua** [lipangit/JiaoZiVideoPlayer#2224]
**需求描述
   播放ktv视频， 需要切换音调， 音轨， 不知道现在有没有支持？

**Comment by lipangit** [comment]
播放器内核有音调和音轨的api吗

**Comment by cydenghua** [comment]
> 播放器内核有音调和音轨的api吗

感谢， 可以了， 能拿到内核MediaPlayer， 我自己可以操作就好

**Comment by lipangit** [comment]
兄弟，怎么拿到，能告诉我吗

**Comment by cydenghua** [comment]
> 兄弟，怎么拿到，能告诉我吗

https://www.jianshu.com/p/4c187a09b838
这个文档里面有切换播放内核的说明。
Mediaplayer    Jzvd.setMediaInterface(new JZMediaSystem());
