### ISSUE TITLE
华为Mate 7， setSpeed 报NoSuchMethodError

### ISSUE THREAD

**Issue by YesLon** [lipangit/JiaoZiVideoPlayer#2226]
**什么jzvd版本
6.4.1
**是否和安卓版本有关系，什么版本
Android 5.1.1
**是否和特定品牌的手机机型有关系，什么机型
华为 MT7-TL0
**相关log是什么

**复现流程
API -> SMALL CHANGE UI -> Play Speed 点击倍速
**最好有截图或者视频说明情况
**修复代码
CustomMediaPlayerAssertFolder和
JZMediaSystem类中修改代码如下：
`
    @RequiresApi(api = Build.VERSION_CODES.M)
    @Override
    public void setSpeed(float speed) {
        if(Build.VERSION.SDK_INT >= 23) {
            PlaybackParams pp = mediaPlayer.getPlaybackParams();
            pp.setSpeed(speed);
            mediaPlayer.setPlaybackParams(pp);
        }
    }
`

**Comment by zhangshaobo87** [comment]
如果是用的是ijkplayer播放的话6.0以下是可以实现倍速播放的，所以这里最好要判断一下播放引擎吧

**Comment by lipangit** [comment]
判断完了，6.0一下不显示倍速按钮。
