### ISSUE TITLE
建议调整下setUp之前的UI

### ISSUE THREAD

**Issue by kingyangcn** [lipangit/JiaoZiVideoPlayer#2229]
一个小细节问题，由于布局文件里retry_layout是默认显示的，而大多数情况是网络请求之后才会setUp，导致没有setUp之前会显示retry_layout，建议修改下，，，，还有battery_time_layout，讲道理start_layout也不应该显示，因为还有没有setUp

**Comment by dary123** [comment]
你可以直接在源码layout文件夹下jz_layout_std.xml布局里将id为retry_layout的linearlayout设置为android:visibility="gone"就好了，因为在视频播放时ui会根据当前视频播放状态自动调整的，如果视频播放错误，retry_layout会设置成android:visibility="visable"显示出来

**Comment by kingyangcn** [comment]
> 你可以直接在源码layout文件夹下jz_layout_std.xml布局里将id为retry_layout的linearlayout设置为android:visibility="gone"就好了，因为在视频播放时ui会根据当前视频播放状态自动调整的，如果视频播放错误，retry_layout会设置成android:visibility="visable"显示出来

感谢回答，我知道可以直接重写getLayoutId自定义布局，不用改源码。这也算是个小bug影响用户体验，不是功能扩展，所以还是提醒下作者。我已提交PR

**Comment by lipangit** [comment]
好的，已经列入工作计划
