### ISSUE TITLE
APP切换IjkMediaPlayer引擎，“m3u8”格式的视频播放不了

### ISSUE THREAD

**Issue by ausboyue** [lipangit/JiaoZiVideoPlayer#2232]
**什么jzvd版本**
6.4.1

**是否和安卓版本有关系，什么版本**
无

**是否和特定品牌的手机机型有关系，什么机型**
无

**相关log是什么**
> W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
W/IJKMEDIA: https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
E/IJKMEDIA: https://xxx/playlist.m3u8: Protocol not found

**复现流程**
APP切换IjkMediaPlayer引擎，“m3u8”格式的视频播放不了，错误日志如上。但是默认的播放引擎是可以播放的。

**最好有截图或者视频说明情况**
界面出现加载失败UI提示

**Comment by lipangit** [comment]
是不提https不支持

**Comment by ausboyue** [comment]
你这边的库有相关的配置吗？还是说得自行编译IjkMediaPlayer支持https的so库？

**Comment by ausboyue** [comment]
> 是不提https不支持

你这边的库有相关的配置吗？还是说得自行编译IjkMediaPlayer支持https的so库？

**Comment by maxiaoxu2017** [comment]
@ausboyue ijkMediaPlayer默认不支持https的地址，需要自己编译支持https的so库。可以用https://github.com/1054353861/ijkplayer.So，我已经搭配用很长时间了。

**Comment by lipangit** [comment]
他说的对

**Comment by Marx-Hong** [comment]
这个问题在新版本有添加支持吗？还是要自己换
