### ISSUE TITLE
goOnPlayOnResume方法

### ISSUE THREAD

**Issue by CK875430315** [lipangit/JiaoZiVideoPlayer#2236]
6.3.1，在播放界面的onPause里调用JzvdStd.goOnPlayOnPause()，然后跳转到另一个activity，再返回播放界面，onResume里的goOnPlayOnResume方法的if (JzvdMgr.getCurrentJzvd() != null)不成立，导致再次播放失败

**Comment by lipangit** [comment]
断点一下，releaseAllVideos是否被调用

**Comment by CK875430315** [comment]
跳转到另一个activity的releaseAllVideos触发了，但不是我执行的，

**Comment by lipangit** [comment]
断点一下，能看到调用堆栈

**Comment by CK875430315** [comment]
找到了是另一个界面调用了，那个界面是一个列表里面有video，并在onChildViewDetachedFromWindow这方法里调用
