### ISSUE TITLE
自定义ui添加EditText无法获取焦点

### ISSUE THREAD

**Issue by jingzz1** [lipangit/JiaoZiVideoPlayer#2238]
**需求描述
 有个需求需要发射弹幕，于是自定义ui时，加了一个editText

就一个简单的editText，没其他代码
````
<EditText
            android:id="@+id/sendDanmaku"
            android:layout_width="150dp"
            android:layout_height="wrap_content" />
````

在操作的时候，点击该EditText输入时，该EditText会自动失去焦点，键盘也没有弹出来

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
亲测是有这个问题

**Comment by 1768803156** [comment]
去掉或更改android:descendantFocusability="blocksDescendants"

**Comment by lipangit** [comment]
这之前是为了修改item点击的问题，现在改成afterDescendants不知道有没有问题

现在这个issue的问题解决了额，可以正常使用edittext了
