### ISSUE TITLE
Recyclview item全屏返回后  Recyclview item布局变形

### ISSUE THREAD

**Issue by cdcdec** [lipangit/JiaoZiVideoPlayer#2244]
在RecyclerView  列表里面使用播放器，点击全屏按钮全屏后，再点击返回按钮，原RecyclerView的布局变形了？？

**Comment by lipangit** [comment]
截图

**Comment by cdcdec** [comment]
![screenshot_20181220-091923](https://user-images.githubusercontent.com/8176067/50257995-ac7c0780-0438-11e9-899c-e81917e000ed.png)
![Uploading Screenshot_20181220-092002.png…]()

**Comment by cdcdec** [comment]
Recyclview item全屏返回后 Recyclview item布局变形：返回后不是立即变形，而是切换下面的Tab后，再进入“发现”模块，2，3秒钟后 Recyclview item布局变形；如果不全屏播放，切换下面的tab不会引起变形

**Comment by lipangit** [comment]
jzvd本质上是一个relativelayout，你的jzvd是wrapcontent吗，这和播放没有关系，只是UI布局问题，建议你固定高度

**Comment by cdcdec** [comment]
找到原因了。用了这个库:com.bulong.rudeness:rudeness:latest.release@aar,高度是用pt为单位的固定值；可以都换成dp为单位，也可以通过：旋转屏幕之后适配失效
可以在onConfigurationChanged中调用 RudenessScreenHelper.resetDensity(getContext(), designWidth) 规避。    谢谢！！！！
