### ISSUE TITLE
6.4.1不支持android O以下版本么

### ISSUE THREAD

**Issue by duov** [lipangit/JiaoZiVideoPlayer#2246]
implementation 'cn.jzvd:jiaozivideoplayer:6.4.1'
之后提示最低支持Android O

**Comment by lipangit** [comment]
最低api16  4.1

**Comment by luoqiang108** [comment]
gradle中添加下面代码就好了
compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
