### ISSUE TITLE
横竖屏自动切换

### ISSUE THREAD

**Issue by chenxi0203** [lipangit/JiaoZiVideoPlayer#2257]
视频播放界面activity添加：android:screenOrientation="sensor" 横竖屏切换时能对应横竖屏播放，但是当播放完成后点击重播就一直只能竖屏了，重播做了什么初始化操作？怎么回到最初的状态？

**Comment by chenxi0203** [comment]
在正常播放模式（SCREEN_WINDOW_NORMAL）横竖屏切换

**Comment by chenxi0203** [comment]
已解决。

**Comment by lipangit** [comment]
ok
