### ISSUE TITLE
全屏自动下一集怎么实现,6.4.1版本

### ISSUE THREAD

**Issue by zhangqifan1** [lipangit/JiaoZiVideoPlayer#2260]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
逻辑是自动播放完成之后播放下一个url，根据这个逻辑你继承jzvdStd，然后有问题再问

**Comment by zhangqifan1** [comment]
大大你好。我是在onAutoCompletion 里边调用了changeurl 方法，正常屏幕可以，全屏的话就不走了 。。

**Comment by zhangqifan1** [comment]
代码是这样的 
 @Override
    public void onAutoCompletion() {
        if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
            onStateAutoComplete();//全屏不退出
            changeUrl();//全屏不可以
        } else {
            super.onAutoCompletion();
            changeUrl();//正常屏幕可以
        }
    }

**Comment by zhangqifan1** [comment]
看了很多issuse,也没看懂...

**Comment by lipangit** [comment]
你说全全屏的时候，自动播放完成不回调onAutoCompletion这个函数是吗

**Comment by zhangqifan1** [comment]
走这个函数，是全屏下调用changeurl的时候，不起作用，非全屏就可以，我看了别的大概是全屏非全屏是俩个实例。。。但是我不知道如何处理。。我就是实现，正常播放切换到全屏播放，播放完成接着播放下一个视频。

**Comment by zhangqifan1** [comment]
看了其他的issues 有处理是直接传url 集合的  ，但是我项目没法一下子全拿出来所有URL...

**Comment by lipangit** [comment]
兄弟，你看apiActivity里面有一个例子是切换清晰度的，切换清晰度的本质就是调用changeUrl，并且这个只能在全屏的时候调用，现在你在demo中测试一下那个例子，看看能不能解决你的问题

**Comment by zhangqifan1** [comment]
-_-!   试了很多了,没试出来 .大大我需要Demo........

**Comment by lipangit** [comment]
好的自动播放下一集，下个版本添加这个功能。

**Comment by hao896259037** [comment]
全屏的时候是一个新的实例，我修改了下Jzvd源码startWindowFullscreen方法中最后部分执行一下新加入的方法startWindowFullscreenAction（Jzvd jzvd） 然后再你的自定义jzvd类中重写startWindowFullscreenAction 就可以获取到实例
具体代码：
`public void startWindowFullscreen() {
            ...
            startWindowFullscreenAction(jzvd);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
public void startWindowFullscreenFocus(Jzvd jzvd) {
    }`
然后在你的自定义jzvd里重写新加入的方法startWindowFullscreenAction就可以获取到全屏的实例 去做一些你想要的操作

**Comment by lipangit** [comment]
路漫漫其修远兮
