### ISSUE TITLE
https视频不能播放一直转圈

### ISSUE THREAD

**Issue by 15194557922** [lipangit/JiaoZiVideoPlayer#2261]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by 15194557922** [comment]
https的视频链接不能播放一直在转圈

**Comment by 15194557922** [comment]
![image](https://user-images.githubusercontent.com/39287701/50752829-85239800-128a-11e9-925e-bbbf8bd8b0c0.png)

**Comment by lipangit** [comment]
你用的什么播放器引擎，链接发来看看或者发我邮箱。

咱们可以一键切换ijkplayer android.media.MediaPlayer exoplayer
