### ISSUE TITLE
全屏播放完，重播的时候能不能保持全屏播放

### ISSUE THREAD

**Issue by Marx-Hong** [lipangit/JiaoZiVideoPlayer#2266]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by Marx-Hong** [comment]
播放完不退出就出现了重播的按钮，点击重播按钮就会重置播放窗口，回到未点击全屏播放的播放状态

**Comment by lipangit** [comment]
解决了吗

**Comment by Marx-Hong** [comment]
看到源码在播放完成的方法里面调用了setRequestedOrientation方法设置当前窗口为竖屏

**Comment by Marx-Hong** [comment]
大佬，以后的版本能不能在播放失败时候自动切换播放引擎，然后重试。今天发现手机内的视频用内网分享的时候，ijk不能播，然后exo能播，默认的media就更多不能播的了

**Comment by lipangit** [comment]
切换播放器引擎的需求你得自己做。这种用坑补坑的做法不推荐。

**Comment by Marx-Hong** [comment]
播放音频没有进度更新，而且loading框一直在转。这个是还没实现，还是.......

**Comment by Marx-Hong** [comment]
发现问题了，因为测试时候用的是media和Ijk引擎的时候，而且音乐的地址没有带mp3和wav的字符，所以有些方法在onPrepared的重写的地方被拦截了，可以考虑播放的时候让用户自己设置播放的是视频还是音频

**Comment by lipangit** [comment]
好的，你说的很有道理。

**Comment by jiaxin11** [comment]
设置全屏，播放完后会自动退出全屏，需要修改JZVD中 quitFullscreenOrTinyWindow 方法。

**Comment by gucuncun** [comment]
全屏自动续播下一个视频，我发现在最新版本可以，但是视频全屏返回第一次返回到全横屏，再点一次页面直接退出了，我想实现全屏续播，返回时候直接全屏变成正常的，怎么来实现呢

**Comment by lipangit** [comment]
横屏全是竖屏的问题，参考demo的orientationActivity，里面有两个变量。看看是怎么修改的，然后看看父类是怎么使用这两个变量的。

**Comment by Marx-Hong** [comment]
最新的demo会崩溃，在custom mediapalyer 中只要先选用其他的内核播放，再用IJK的内核播放就会崩溃，空指针

**Comment by lipangit** [comment]
log什么样
