### ISSUE TITLE
点击全屏播放按钮跳转失败

### ISSUE THREAD

**Issue by dongfangmingjia** [lipangit/JiaoZiVideoPlayer#2273]
**什么jzvd版本
6.2.10
**是否和安卓版本有关系，什么版本
无
**是否和特定品牌的手机机型有关系，什么机型
无
**相关log是什么
java.lang.NoSuchMethodException: <init> [class android.content.Context]
但是我的自定义的播放器是复写了这个构造方法的
**复现流程

**最好有截图或者视频说明情况
用的是Android studio3.3

**Comment by dongfangmingjia** [comment]
我在每个自定义的View中都实现了
public JZVideoPlayer(Context context) {
        super(context);
        init(context);
    }

    public JZVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }
这两个方法，但是在跳转横屏的时候还是会在
Constructor<JZVideoPlayer> constructor = (Constructor<JZVideoPlayer>) JZVideoPlayer.this.getClass().getConstructor(Context.class);
处抛出没有此方法的异常

**Comment by lipangit** [comment]
更新一下库。说说你的需求是什么，一般需求接触不到这个函数

**Comment by dongfangmingjia** [comment]
我发现，这个问题的原因是因为升级as后混淆出了问题，在自定义view中要加入对构造函数的混淆策略，加上之后就没事了

**Comment by lipangit** [comment]
ok  怎么混淆的，我在demo里也加上

**Comment by cpappzoro** [comment]
> 
> 
> -keepclassmembers public class * extends android.view.View {
> void set*(**_); *** get_();
> public (android.content.Context);
> public (android.content.Context, android.util.AttributeSet);
> }

Expecting java type before '(' in line 22 of file 'E:\Get Sound\player_recycler\JiaoZiVideoPlayer-develop\JiaoZiVideoPlayer-develop\app\proguard-rules.pro'
Open File
