### ISSUE TITLE
初始化时，重试布局未隐藏。

### ISSUE THREAD

**Issue by MirkoWu** [lipangit/JiaoZiVideoPlayer#2275]
如果在xml布局里面写了jzvd，默认就是下面这个状态：
![image](https://user-images.githubusercontent.com/20485720/51455535-fc762300-1d84-11e9-8b28-6837bf71699a.png)
这样就导致了，activity那里设置播放Url如果不及时的话，会先出现上面的现象，然后等设置完才回复到正常的（一个播放按钮的）状态。

不知道大神是基于什么原因没有让 重试布局没隐藏，我看了不少人也都是有提这个现象，但是好像到现在还没改过来。所以还是建议一下，初始化状态，重试布局应该是要隐藏才好的吧，不然要等设置完url才能恢复正常，很尴尬。我目前是这样隐藏的：在设置url前调用：mVideo.mRetryLayout.setVisibility(View.GONE);  希望能给相同问题的同学一点帮助

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/51593727-d5a72080-1f2d-11e9-93e6-cb1012da2a4a.png)

兄弟更新一下，新版没有setUp的时候是这样的，一个朋友提交的

**Comment by MirkoWu** [comment]
我用的是6.4.1 ，应该是最新版本了吧，还是这样啊。

**Comment by lipangit** [comment]
哦兄弟，还没发新版，develop分支上修改的。下周一之前发版
