### ISSUE TITLE
4G流量下播放视频，视频长度1小时以上，就会卡一下，播一下，很卡顿

### ISSUE THREAD

**Issue by tiefeiniu** [lipangit/JiaoZiVideoPlayer#2276]
版本是6.4.1，使用JzvdStd 类播放

红米5 plue 

只要视频长度达到一小时以上，使用4G流量播放，就会卡顿，wifi下播放没有

**Comment by lipangit** [comment]
视频太大，网速跟不上，群里

**Comment by dary123** [comment]
可是用红米Note5自带浏览器打开视频播放的直链进行播放，就很流畅呀
