### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.seekTo(int)' on a null object reference

### ISSUE THREAD

**Issue by wuzhaohui026** [lipangit/JiaoZiVideoPlayer#2282]
**什么jzvd版本
6.3.1
**是否和安卓版本有关系，什么版本
Androd 9.0
**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.seekTo(int)' on a null object reference
**复现流程

**最好有截图或者视频说明情况
JZMediaManager.jzMediaManager.jzMediaInterface.seekTo(mVideoDetailJz.seekToInAdvance);
调用这个方法的时候出现这个问题

**Comment by lipangit** [comment]
必须要在正在播放的时候才能调用这个函数
