### ISSUE TITLE
全屏播放  缩略图不会显示

### ISSUE THREAD

**Issue by zhengxiangke** [lipangit/JiaoZiVideoPlayer#2289]
**需求描述
我需要全屏第一帧图片显示 现在是黑色的 然后在转圈 还有能不能根据手机方向自动切换横竖屏
**其他app是否实现

**截图或者小视频说明

    JzvdStdAutoCompleteAfterFullscreen jzvdStdAutoCompleteAfterFullscreen = new JzvdStdAutoCompleteAfterFullscreen(this);
    
        jzvdStdAutoCompleteAfterFullscreen.startFullscreen(this, JzvdStdAutoCompleteAfterFullscreen.class, "https://zl-pub.oss-cn-hangzhou.aliyuncs.com/upload/videos/201901/28/Android/35010501582524513100000000.mp4", "饺子辛苦了");
        Glide.with(this)
                .load(R.drawable.addbingci)
                .into(jzvdStdAutoCompleteAfterFullscreen.thumbImageView);

**Comment by lipangit** [comment]
1.第一帧图片需要自己保存下来放到服务器上

2.屏幕方向问题参考demo的orientationActivity
