### ISSUE TITLE
How to switch to Ijk player?

### ISSUE THREAD

**Issue by uzaysan** [lipangit/JiaoZiVideoPlayer#2295]
Hello. Im using your library and its great but i wanna switch player to Ijk player because videos loading slow. I adde3d Ijk player to my project with gradle. But ı can not use your example code:

https://user-images.githubusercontent.com/2038071/34048532-0a9d6132-e1ef-11e7-942d-8a2a3f88e7ef.png

And this codes doesnt show up to me

https://serving.photos.photobox.com/6754510450e2e62880f1c62f4934d560aaf759caecf6b555e080f2cd42f8b76b97936b0a.jpg

How can i switch to Ijk player?

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/52556529-caa62880-2e27-11e9-9690-7f155c59d824.png)

you should copy this class first from demo

**Comment by lipangit** [comment]
use it before click start button,  it can be called everywhere.

you can call it in startActivity onCreate.

**Comment by uzaysan** [comment]
Ijk player doesnt support https protocol can i use exoplayer?

**Comment by lipangit** [comment]
yes
