### ISSUE TITLE
视频没完全缓冲完，拖动进度条到没缓冲的位置就会出现视频加载失败

### ISSUE THREAD

**Issue by asalin** [lipangit/JiaoZiVideoPlayer#2299]

**Comment by lipangit** [comment]
什么log，亲测不会

**Comment by asalin** [comment]
![1zu6ik 9bqko sg zo0jx](https://user-images.githubusercontent.com/6972999/52923793-683bb380-3364-11e9-8d87-841c4716f2dd.png)

**Comment by asalin** [comment]
@lipangit  发现切换到IJKPLAYER才支持拖动到未缓存位置播放，mediaplayer会加载失败

**Comment by lipangit** [comment]
demo的哪个视频？ 什么手机？复现概率什么样

**Comment by asalin** [comment]
我用的是小米5，demo的视频应该都会，用direct play的全屏那个视频应该长，比较容易看出，概率100%

**Comment by lipangit** [comment]
1.别的手机有没有这样的情况
2.新建个项目用最简单的MediaPlayer和textureView试试在你的小米5上有没有这情况
3.尝试切换其他播放内核

**Comment by asalin** [comment]
嗯，换成exoplayer了。

**Comment by lipangit** [comment]
么么哒
