### ISSUE TITLE
为什么无法播放手机私有路径下的视频

### ISSUE THREAD

**Issue by luyanan123** [lipangit/JiaoZiVideoPlayer#2307]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
要么是权限不够，要么是路径不对

**Comment by luyanan123** [comment]
我试了一下原生的videoview可以播放，但是换上饺子以后无法播放，啥原因啊，权限给了，路径也对啊

**Comment by lipangit** [comment]
饺子本质上也用的系统MediaPlayer播放内核，也可以切换其他内核，怼正确的路径应该就能播，你的log是什么

**Comment by luyanan123** [comment]
W/System.err: java.lang.ClassCastException: java.lang.String cannot be cast to android.content.res.AssetFileDescriptor
02-21 15:13:19.344 27941-28177/txyz.example.beijingwudaoxueyuan_course W/System.err:     at txyz.example.beijingwudaoxueyuan_course.view_ui.activity.custommediaplayer.CustomMediaPlayerAssertFolder.prepare(CustomMediaPlayerAssertFolder.java:41)
02-21 15:13:19.344 27941-28177/txyz.example.beijingwudaoxueyuan_course W/System.err:     at cn.jzvd.JZMediaManager$MediaHandler.handleMessage(JZMediaManager.java:152)
02-21 15:13:19.344 27941-28177/txyz.example.beijingwudaoxueyuan_course W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:108)
02-21 15:13:19.344 27941-28177/txyz.example.beijingwudaoxueyuan_course W/System.err:     at android.os.Looper.loop(Looper.java:166)
02-21 15:13:19.344 27941-28177/txyz.example.beijingwudaoxueyuan_course W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/53152237-fbd4e480-35ef-11e9-816d-3efb46441572.png)

这个是重点

**Comment by luyanan123** [comment]
已经解决了，我之前一直在尝试切换播放引擎，然后我试了一下不切换，直接用原始的，就可以了
