### ISSUE TITLE
直播流追帧

### ISSUE THREAD

**Issue by Gtaiqin** [lipangit/JiaoZiVideoPlayer#2312]
请问播放直播流时  在网络卡的情况下  播一段时间后就会发现和实际直播流相差很长一段时间   这个视频追帧要怎样处理呢

**Comment by lipangit** [comment]
请查收qq

**Comment by Warlock1994** [comment]
我也有这个问题，怎么处理？

**Comment by lipangit** [comment]
播放内核不知道有没有追帧的api，手动调用函数去追帧，或者播放内核自动追帧

**Comment by yangwenwu** [comment]
我也是碰到这个问题了，直播暂停后，继续播放，就没法实时同步直播了

**Comment by Gtaiqin** [comment]
直播流推荐切到腾讯播放器吧

yangwenwu <notifications@github.com> 于2019年12月4日周三 上午11:09写道：

**Comment by yangwenwu** [comment]
@Gtaiqin  嗯，多谢 ，我好好考虑下

**Comment by yangwenwu** [comment]
@Gtaiqin  有一个解决办法，暂停之后，再次播放的时候重新拉取最新的直播流，可以解决这个同步的问题，挺好使的
