### ISSUE TITLE
exoplayer 设置jzDataSource.looping = true;不能循环播放，默认的mediaplayer可以

### ISSUE THREAD

**Issue by asalin** [lipangit/JiaoZiVideoPlayer#2313]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
你看一下JZExoplayer这个类，它的looping是否给exoplayer设置进去了，是否生效

**Comment by Buzzfease** [comment]
在你的exoPlayer里加上这些，demo里的exoPlayer好像是没有写
`Boolean isLoop = jzDataSource.looping;`
`if (isLoop){`
`    simpleExoPlayer.setRepeatMode(Player.REPEAT_MODE_ONE);`
`}else{`
`    simpleExoPlayer.setRepeatMode(Player.REPEAT_MODE_OFF);`
`}`

**Comment by lipangit** [comment]
是的，exoplayer没考虑这块，加上就好了

**Comment by faith-hb** [comment]
> 是的，exoplayer没考虑这块，加上就好了

那ijk呢？

**Comment by faith-hb** [comment]
ijk引擎的补上：ijkMediaPlayer.setLooping(jzvd.jzDataSource.looping);作者的库我也是醉了，漏东漏西的，demo还各种闪退，操

**Comment by lipangit** [comment]
exo已经添加了   哪里闪退  有log吗
