### ISSUE TITLE
请问两个视屏自动切换时黑屏怎么处理？

### ISSUE THREAD

**Issue by chen2991101** [lipangit/JiaoZiVideoPlayer#2317]
**需求描述
本地需要循环播放多个视屏，在每个广告视频播放完成事件后通过调用setup和startVideo方法播放下一个视屏
player.setUp("本地地址", "标题", Jzvd.SCREEN_WINDOW_NORMAL);
player.startVideo();
这样做会在切换过程中会黑一下，请问这种情况怎么处理？使用的是默认的MediaPlayer。

**其他app是否实现
之前自己编译的ijk没这个问题

**Comment by lipangit** [comment]
黑一下是什么样子，因为什么

**Comment by chen2991101** [comment]
像是每次都在销毁重新渲染视频造成的

**Comment by chen2991101** [comment]
想要无缝切换，但是现在切换视频的时候会闪一下

**Comment by chen2991101** [comment]
使用changeUrl实现了，谢谢

**Comment by lipangit** [comment]
ok
