### ISSUE TITLE
After play one first video, the player lock screen in portrait ( not auto lanscape anymore with other images or videos )

### ISSUE THREAD

**Issue by tranquoctrungcntt** [lipangit/JiaoZiVideoPlayer#2318]
After play one first video, the player lock screen in portrait ( not auto lanscape anymore with other images or videos ), I am still able to auto lanscape if i dont play any videos first.

**Comment by lipangit** [comment]
see orientationActivity, it show you how to control the screen direction

**Comment by tranquoctrungcntt** [comment]
dost not work in viewpager ( in my case ). thanks btw

**Comment by lipangit** [comment]
This has nothing to do with viewpager. viewpager is just a control like button. The real screen change is activity.

**Comment by tranquoctrungcntt** [comment]
@Override
        protected void onPause() {
        super.onPause();
        Jzvd.releaseAllVideos();
        Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;
        Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
    } 


      @Override
    protected void onResume() {
        super.onResume();
        Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
        Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
    }




=> this a the code i put into my activity.

**Comment by lipangit** [comment]
What do you need?   fullscreen is LANDSCAP, and normal is PORTRAIT?

**Comment by tranquoctrungcntt** [comment]
I have a viewpager, it contains both images and videos. I have been using your player to play video ( btw , your player is very good). The main problem is that when I play first video -it works well. But when I swipe to other videos or images. the screen orientation dost not auto landscape any more. I dont know why. can you help me. thanks

**Comment by lipangit** [comment]
I didn't know what the sliding viewpager has to do with the screen orientation. Can you record a small video to show me?

**Comment by tranquoctrungcntt** [comment]
tomorow i will send you a video. now is almost 11 pm

**Comment by tranquoctrungcntt** [comment]
this is the video. hope this help

Vào Th 6, 1 thg 3, 2019 vào lúc 22:02 Nathen <notifications@github.com>
đã viết:

**Comment by lipangit** [comment]
where is the video

**Comment by tranquoctrungcntt** [comment]
Github dose not allow to attach video. I send it via email. Please take a look

**Comment by tranquoctrungcntt** [comment]
if you can not see my video, please tell me. thanks

**Comment by lipangit** [comment]
I can not see your video  in  821537155@qq.com

**Comment by tranquoctrungcntt** [comment]
I will send it again

**Comment by tranquoctrungcntt** [comment]
did you receive my video.

**Comment by tranquoctrungcntt** [comment]
by the way, how to continuously play video without waitting to load from cache.thanks

**Comment by lipangit** [comment]
1. Your demand is to switch between horizontal and vertical screens under normal window？
2. The video screen is normal?
![image](https://user-images.githubusercontent.com/2038071/53826976-e6c76080-3fb4-11e9-9909-c2facacf9e90.png)
3. Your operation in video will not perform Activity's onPause and onResume.
4. In manifest you should set the activity screenOrientation.

**Comment by tranquoctrungcntt** [comment]
What am I suppose to do ? 

this is my code:

  

```
 videoView.setUp(link_media,"",Jzvd.SCREEN_WINDOW_NORMAL);

            Glide.with(context.getApplicationContext())
                   .load(link_thumb_media)
                    .apply(new RequestOptions().placeholder(circularProgressDrawable))
                    .into(videoView.thumbImageView);

```


 
```


```
@Override
    protected void onPause() {



               mSensorManager.unregisterListener(mSensorEventListener);
              Jzvd.clearSavedProgress(this, null);
              Jzvd.goOnPlayOnPause();       
       Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;       Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;       super.onPause();
   }
```



```


  ```
  @Override
    protected void onResume() {
        if (!arrayList_media.isEmpty()){

            Sensor accelerometerSensor = mSensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);
            mSensorManager.registerListener(mSensorEventListener, accelerometerSensor, SensorManager.SENSOR_DELAY_NORMAL);

                Jzvd.goOnPlayOnResume();


        }
        Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
        Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
        super.onResume();
    }

```

**Comment by tranquoctrungcntt** [comment]
thanks for all of these problem. I will close this issue.

**Comment by tranquoctrungcntt** [comment]
btw, I have done exactly what you said, but it seen dose not work at all. after play first video, I swipe to the second video and click play. the player force my activity  ( requestWindowFeature(Window.FEATURE_NO_TITLE),      getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
               WindowManager.LayoutParams.FLAG_FULLSCREEN); )  not full screen anymore and lock it in portrail mode.

**Comment by lipangit** [comment]
Your demand is only relationship with NORMAL_ORIENTATION  and Manifest.

**Comment by lipangit** [comment]
swipe the viewpager will not change the orientation.

**Comment by tranquoctrungcntt** [comment]
yep, it will not, but I dont talk about the viewpager. When I click play the second video (first video was ok), like I said, the player force my activity not fullscreen anymore. and lock it in portrail.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/53945795-59435800-40fd-11e9-921a-f8060ba40c7e.png)

try to change this variable,because start second video it will call the function

**Comment by tranquoctrungcntt** [comment]
I download the player vy grandle. How csn i edit it ?

**Comment by lipangit** [comment]
just edit JZVD.NORMAL_ORIENTATION

**Comment by tranquoctrungcntt** [comment]
what do you mean. Download zip -> edit -> import as a module ? right

**Comment by lipangit** [comment]
That is a variable

**Comment by tranquoctrungcntt** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/33772899/54082405-e8dc4700-4347-11e9-84d9-8e36725c23bc.png)

I have tried every single variable , but it dose not work. what should I put into this line ?

**Comment by lipangit** [comment]
bro
JZVD.NORMAL_ORIENTATION This is a global variable. You can modify it at any time before it is called. Your current problem is that when a video broadcast is playing another video, the onComplete function will be called. This function will call JZUtils. .setRequestedOrientation(getContext(), NORMAL_ORIENTATION); This will lock the screen, so you can see that the screen can't be rotated, so you can enter the activity when JZVD.NORMAL_ORIENTATION=ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED, or other variables under ActivityInfo, then you can feel gravity The screen is in the right direction.

The following Chinese is my native language to express my thoughts more clearly. I feel very shy about such a small problem that I haven't solved it for a few days. I can't send you a project or create a new project that can explain the current problem. I will change it for you. 

JZVD.NORMAL_ORIENTATION 这是全局变量，你可以在它被调用之前的任何时候修改它，你现在的问题是，一个视频播正在播放的时候播放另一个视频，那么会调用onComplete函数，这个函数会调用JZUtils.setRequestedOrientation(getContext(), NORMAL_ORIENTATION);这里会锁定屏幕，所以看到了屏幕不能旋转，所以你在进入这个activity的时候JZVD.NORMAL_ORIENTATION=ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED，或者其他ActivityInfo下面的变量，那么就可以重力感应屏幕方向了。

下面的中文是我的母语能更清楚的表达我的想法，这么小的问题几天还没有解决我感到很羞愧，实在不行你把项目发过来或者新建一个能说明当前问题的项目我给你改。

**Comment by tranquoctrungcntt** [comment]
sorry for all of this and thanks you

**Comment by tranquoctrungcntt** [comment]
I am not an english speaker too, so forgive me if I made mistakes
