### ISSUE TITLE
It crashes on click inside a recyclerview inside a fragment in a fragment pager

### ISSUE THREAD

**Issue by achalkias** [lipangit/JiaoZiVideoPlayer#2319]
Hi i used this library in my activity and it works perfectly.

But i am trying to use it inside a view in a recyclerview. But it does not work. i use the following code

```
 itemView.playerViewPost.setUp(post.video
                         ,""
                         , Jzvd.SCREEN_WINDOW_LIST)
```
But it crash when i click the play button.

It gives me the following error: 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.startVideo(Jzvd.java:601)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:446)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:263)
        at android.view.View.performClick(View.java:6199)
        at android.view.View$PerformClick.run(View.java:23647)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
And after i debug it a bit i found out it crash on this line in JZUtils.class
```
 public static AppCompatActivity getAppCompActivity(Context context) {
        if (context == null) return null;
        if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());  **//CRASH HER**
        }
        return null;
    }

```

**Comment by lipangit** [comment]
What is the difference between your recyclerview and demo's recyclerview?

**Comment by achalkias** [comment]
> What is the difference between your recyclerview and demo's recyclerview?

Hi, I have an activity that has a fragment pager and inside the first fragment i have a recyclerview with the posts. Now in the recyclerview. In the recyclerview adapter layout i have a JzvdStd player. It does not crash when the setUp is happening. But it crash when i click the play button.

I suspect it cannot find the activity because i use it from a fragment in a fragment pager?

**Comment by lipangit** [comment]
do you mean  getAppCompActivity() the function can not get real Activity's context

**Comment by achalkias** [comment]
> do you mean getAppCompActivity() the function can not get real Activity's context

Yes it crashes on this line 
return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());

**Comment by lipangit** [comment]
getAppCompActivity() this function did not fond in that log, how can sure it because it.

**Comment by achalkias** [comment]
> getAppCompActivity() this function did not fond in that log, how can sure it because it.

Ok my mistake i copied the wrong function. Sorry. This issue really got me.
The problem is here 
```
 public static Activity scanForActivity(Context context) {
        if (context == null) return null;

        if (context instanceof Activity) {
            return (Activity) context;
        } else if (context instanceof ContextWrapper) {
            return scanForActivity(((ContextWrapper) context).getBaseContext());
        }

        return null;
    }

```

It runs it one time it goes to 
`return scanForActivity(((ContextWrapper) context).getBaseContext());`
Then it calls it self and the next time it just returns null in the end 

So the final crash happens here in line 601 of Jzvd.class
`JZUtils.scanForActivity(getContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);`

Because the scanForActivity returns null and this is why it cannot find the window. I dont understand why. 

The weird thing is that it works outside the recyclerview. In a simple view in the same fragment

**Comment by achalkias** [comment]
Progress figured out what the issue was. So i as inflating the layout in the adapter like this 

```
val view = LayoutInflater.from(App.appContext).inflate(R.layout.layout_post, parent, false)
return ViewHolder(view)
```
Getting the context the application context as context to inflate the layout. So that was the issue because the context basically was not the activity context but the application context. This is why it could not convert it to activity and find the window.

So after i changed it to this code
```
val view = LayoutInflater.from(context).inflate(R.layout.layout_post, parent, false)
return ViewHolder(view)
```

Passing the activity context in the adapter. And now it works just fine.
So i close this. Hope this will help someone else. Thank you.

**Comment by lipangit** [comment]
Thank you very much
