### ISSUE TITLE
点了播放之后，用BottomSheetBehavior  弹出底部一个弹出框，如果弹出框设置了 layout_marginTop ，就会

### ISSUE THREAD

**Issue by dahai2070** [lipangit/JiaoZiVideoPlayer#2322]
我现在用了 BottomSheetBehavior 来控制一个底部弹出框，我给这个弹出框设置了一个 marginTop的时候,

`
...........................
<com.srbl.mytx.widget.CommentView
android:id="@+id/comment_view"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:layout_marginTop="70dp" //设置layout_marginTop
app:layout_behavior="@string/bottom_sheet_behavior" />

<com.srbl.mytx.widget.CommentBottomBar
    android:id="@+id/comment_bottom_bar"
    android:layout_width="match_parent"
    android:layout_height="45dp"
    android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>`

当我点了播放器，再弹出这个弹出框的时候，当弹出框弹出后，会往下回弹一个距离，距离就是我设置的 marginTop的值，等于说 弹出框距离屏幕顶端的距离就是 两个marginTop的距离了，
如果我打开页面，不点播放，只弹出 底部弹出框，就一切正常，像我这个情况，大概该从哪儿着手检查呢？

**Comment by lipangit** [comment]
能截图或者录像看看什么样吗，可以发我qq

**Comment by dahai2070** [comment]
你的QQ是   天堂的小帅哥  吗？

**Comment by dahai2070** [comment]
截图估计看不出来效果，录屏，之前找了一个录屏的软件，导出视频叫要收费，55555

**Comment by dahai2070** [comment]
现在我通过 “曲线救国”的方式解决问题了，我在 CommentView的布局里面，再设置一个marginTop高度70dp,效果实现了同样的效果。

**Comment by lipangit** [comment]
这么解决没问题
