### ISSUE TITLE
如何实现,全屏和竖屏两套布局

### ISSUE THREAD

**Issue by ZuccCircle** [lipangit/JiaoZiVideoPlayer#2325]
**需求描述
由于全屏的布局和竖屏时的布局差异性较大, 用 gone 和 visible 无法实现, 请问有没有好的方法设置两种布局?

**Comment by lipangit** [comment]
监听activity的屏幕变化，然后分别设置全屏和非全屏的布局。但是布局文件应该只有一个，没法做到播放中切换布局文件。
