### ISSUE TITLE
播放视频时添加headers或者cookie

### ISSUE THREAD

**Issue by ToxicR** [lipangit/JiaoZiVideoPlayer#2329]
**需求描述
在播放视频时需要添加headers或者cookie，请问应该使用哪个方法。我在使用以下方法之后并不生效：
**其他app是否实现

**截图或者小视频说明

**Comment by ToxicR** [comment]
map.put("高清", proxyUrl);
        map.put("标清", VideoConstant.videoUrls[0][6]);
        map.put("普清", VideoConstant.videoUrlList[0]);
        JZDataSource jzDataSource = new JZDataSource(map, "饺子不信");
        jzDataSource.looping = true;
        jzDataSource.currentUrlIndex = 2;
        jzDataSource.headerMap.put("key", "value");//header
        mJzvdStd.setUp(jzDataSource
                , JzvdStd.SCREEN_WINDOW_NORMAL);

**Comment by ToxicR** [comment]
已解决，切换成Med内核就支持上述方法

**Comment by ToxicR** [comment]
已解决，切换成Med内核就支持上述方法

**Comment by lipangit** [comment]
其他内核如果不起作用的话，可以通过自定义的MediaPlayer，在prepare之前把漏掉的设置补上
