### ISSUE TITLE
能不能预先缓存视频

### ISSUE THREAD

**Issue by cf0566** [lipangit/JiaoZiVideoPlayer#2348]
**需求描述
我这边需要就是一个列表播放视频，视频最好就是到了能直接播放而不需要在加载
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
这个要求可能有点高，可以用你自己编译的ijkplayer来提升首次加载的速度

**Comment by liweiGe** [comment]
这个感觉需要去研究下videocache,饺子只处理播放,这样缓存好就不需要走网络请求式的播放,可以加快点速度,但是要秒播的话就不是这么实现,最近正在搞这个播放优化,起播太慢,一般都要1,2秒的样子

**Comment by mzhkby** [comment]
@liweiGe 能够实现秒播吗？

**Comment by JunWeiAndroid** [comment]
> @liweiGe 能够实现秒播吗？

用videocache先缓存，可以秒播的

**Comment by xuzhiyong017** [comment]
在列表页使用一个播放器，切换Item 的时候只是把地址换了这样效率要高一些把，但是在这个JzvdStd上面不好改啊，大佬有解决办法吗。列表切换视频不release播放器

**Comment by lipangit** [comment]
速度和release没关系，视频加载快的是因为视频下载了10帧就开始播放，加载慢是因为视频下载了30帧开始播放，（帧数只是比喻，具体多少帧我不知道，需要深入研究）
