### ISSUE TITLE
normal模式下，点全屏，变成横屏全屏，再点退出全屏，怎么又变成竖屏全屏了？

### ISSUE THREAD

**Issue by hahaay1** [lipangit/JiaoZiVideoPlayer#2352]
normal模式下，点全屏，变成横屏全屏，再点退出全屏，怎么又变成竖屏全屏了？这是杂回事

**什么jzvd版本
最新版7.0-preview

手机：meizu 15 plus

thanks

**Comment by lipangit** [comment]
7.0-preview 还在测试阶段，感谢你的反馈，这个是在demo中的哪个activity下出现的bug

**Comment by yeaper** [comment]
我也遇到了，全屏点返回，切回竖屏，原来写死的200dp高度，自动变高了，fragment和activity的列表里都有这个问题

**Comment by lipangit** [comment]
要在布局中添加一个layout

![image](https://user-images.githubusercontent.com/2038071/54943070-72f0f600-4f6b-11e9-8094-b7c5d9c4af93.png)

**Comment by JamesGZM** [comment]
我也遇到了

**Comment by lipangit** [comment]
参考demo的activity_main.xml

**Comment by borneywpf** [comment]
> 参考demo的activity_main.xml

就是这样

**Comment by yeaper** [comment]
好的  谢谢

**Comment by lipangit** [comment]
新版是preview版本不建议放到生产环境使用
