### ISSUE TITLE
隐藏播放界面的底部栏（包括时间框，进度条，全屏按钮）

### ISSUE THREAD

**Issue by xiemobiao** [lipangit/JiaoZiVideoPlayer#2360]
7.0_preview版本,为什么这样设置JzvdStd.bottomContainer.setVisibility(View.GONE);隐藏底部栏不起作用

**Comment by lipangit** [comment]
你要继承jzvdStd，然后复写各个状态，在每个状态中分别设置它的显示或者隐藏。
