### ISSUE TITLE
更新7.0之后 全屏按键无法点击

### ISSUE THREAD

**Issue by Biswangluo** [lipangit/JiaoZiVideoPlayer#2361]
![device-2019-03-28-175141](https://user-images.githubusercontent.com/2362450/55148347-ffc1cc80-5182-11e9-8b16-67a4335ab8a7.png)

全屏之后 点击全屏按钮 没有反应 转到另外一侧就可以点击 后发现 发现界面没有给虚拟键 让出位置，导致点击失效。

**Comment by lipangit** [comment]
这个问题本质上是
![image](https://user-images.githubusercontent.com/2038071/55188557-a97e7900-51d6-11e9-9b5a-efdc7713885b.png)，但是我没调试清楚，兄弟能帮忙看看吗，你要是解决了送你JiaoZiToken

**Comment by Biswangluo** [comment]
这个问题 我找到了解决方案了[https://www.jianshu.com/p/557eac857afd](url) 
在JZUtils 加上同时隐藏状态栏和隐藏导航栏的代码就可以了

**Comment by Biswangluo** [comment]
在JZUtils下边加入了 下边加入了隐藏虚拟键代码解决了问题
`  if (!show) {
            int uiOptions =// View.SYSTEM_UI_FLAG_LAYOUT_STABLE|
                    0;

            uiOptions = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
            ;
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
                uiOptions |= View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
            }
            JZUtils.getWindow(context).getDecorView().setSystemUiVisibility(uiOptions);
        } else {
            int uiOptions = View.SYSTEM_UI_FLAG_VISIBLE;
            JZUtils.getWindow(context).getDecorView().setSystemUiVisibility(uiOptions);

        }`

**Comment by lipangit** [comment]
好的兄弟，我一会测试，更新demo

**Comment by lipangit** [comment]
兄弟，这个经过测试可以进入全屏强制隐藏虚拟按键，退出全屏显示虚拟按键，但是全屏的时候无法通过手势显示虚拟按键，全屏的时候虚拟按键无论如何都出不来，这是个问题。

能再研究研究吗，全屏的时候让虚拟按键在全屏的时候可以通过手势显示出来。

**Comment by lipangit** [comment]
兄弟你的修改非常完美，感谢你提供代码，给你3000JZT，https://github.com/lipangit/JZT

等过阵子记账转账的流程确定之后，我会找你，记得管我要

**Comment by lipangit** [comment]
加我微信  在群里吗
