### ISSUE TITLE
请问一下,我用的是最新的"7.0_preview"版本,设置封面图片,setImageResource可以,setImageURI和setImageBitmap为什么不行了?还有这个 Jzvd.releaseAllVideos();无法调用

### ISSUE THREAD

**Issue by roybill** [lipangit/JiaoZiVideoPlayer#2365]

**Comment by lipangit** [comment]
1.你可以取得imageView的变量，怎么设置图片根据你项目用什么图片框架自己设置
2.名字改成了resetAllVideos

**Comment by roybill** [comment]
@lipangit  谢谢,第二个可以了, 第一个问题,我这样拿到封面ImageView,然后设置还是不行,图片地址我这边确认是有的, 我打印出来看了,我用glide这样设置的:`    ImageView thumbImageView = jzvdStd.thumbImageView;
        Glide.with(this).load(cover).into(thumbImageView);//封面`

**Comment by roybill** [comment]
@lipangit   已经可以了,谢谢
