### ISSUE TITLE
Error When Clicking Full Screen Button

### ISSUE THREAD

**Issue by thatsenam** [lipangit/JiaoZiVideoPlayer#2369]
I am using player inside bottomsheet and when I am trying to fullscreen the player it's crushing with this detail. (Translate in Chiness: 
我正在底部使用播放器，当我试图全屏播放播放器时，它正在用这个细节粉碎。)

 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4066)
        at android.view.ViewGroup.addView(ViewGroup.java:3916)
        at android.view.ViewGroup.addView(ViewGroup.java:3888)
        at cn.jzvd.Jzvd.gotoScreenFullscreen(Jzvd.java:853)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:362)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:284)
        at android.view.View.performClick(View.java:4848)
        at android.view.View$PerformClick.run(View.java:20270)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5667)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

Please Let know if there is any fix.

**Comment by lipangit** [comment]
哪个版本，在什么情况下，demo有这问题吗

**Comment by thatsenam** [comment]
I am using the latest version and that is implementation 'cn.jzvd:jiaozivideoplayer:7.0_preview' @lipangit 
In Chiness [我使用的是最新版本 implementation 'cn.jzvd:jiaozivideoplayer:7.0_preview'  ]

Xml Code is `<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">


    <android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar"
        android:layout_width="match_parent"
        android:layout_height="@dimen/appbarLayoutHeight"
        android:theme="@style/WhiteTheme"
        app:elevation="2dp">

        <android.support.v7.widget.Toolbar
            android:id="@+id/accountToolbar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/appbarLayoutHeight"
            app:buttonGravity="bottom"
            app:layout_scrollFlags="scroll|enterAlways"
            app:navigationIcon="@mipmap/ic_launcher"
            app:title="@string/app_name" />


    </android.support.design.widget.AppBarLayout>


    <android.support.v4.view.ViewPager
        android:id="@+id/homeViewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />


    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/bottomSheetContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="60dp"
        app:elevation="10dp">

        <LinearLayout
            android:id="@+id/bottomSheet"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/colorWhite"
            android:orientation="vertical"
            app:cardElevation="20dp"
            app:layout_behavior="@string/bottom_sheet_behavior">

            <LinearLayout
                android:id="@+id/smallPlayerContainer"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:animateLayoutChanges="true"
                android:orientation="horizontal">

                <cn.jzvd.JzvdStd
                    android:id="@+id/player"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="start"
                    android:visibility="gone" />

                <com.halilibo.bettervideoplayer.BetterVideoPlayer
                    android:id="@+id/betterPlayer"
                    android:layout_width="match_parent"
                    android:layout_height="200dp"/>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:gravity="end"
                    android:orientation="horizontal">

                    <LinearLayout
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_vertical"
                        android:layout_marginLeft="10dp"
                        android:layout_marginStart="10dp"
                        android:layout_weight="1"
                        android:gravity="center"
                        android:orientation="vertical">

                        <TextView
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:text="title" />

                        <TextView
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:text="channel name" />
                    </LinearLayout>

                    <ImageView
                        android:id="@+id/pp"
                        android:layout_width="24dp"
                        android:layout_height="24dp"
                        android:layout_gravity="center|end"
                        android:layout_marginEnd="15dp"
                        android:layout_marginLeft="4dp"
                        android:layout_marginRight="10dp"
                        android:layout_marginStart="4dp"
                        android:orientation="vertical"
                        android:src="@drawable/ic_pause_black_24dp"
                        android:visibility="visible" />

                    <ImageView
                        android:id="@+id/dismisPlayer"
                        android:layout_width="24dp"
                        android:layout_height="24dp"
                        android:layout_gravity="center"
                        android:layout_marginEnd="15dp"
                        android:layout_marginLeft="4dp"
                        android:layout_marginRight="10dp"
                        android:layout_marginStart="4dp"
                        android:orientation="vertical"
                        android:src="@drawable/ic_close_black_24dp"
                        android:visibility="visible" />
                </LinearLayout>

            </LinearLayout>

            <android.support.v4.widget.NestedScrollView
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:text="@string/title" />

                    <android.support.v7.widget.RecyclerView
                        android:layout_width="match_parent"
                        android:layout_height="match_parent" />
                </LinearLayout>
            </android.support.v4.widget.NestedScrollView>


        </LinearLayout>
    </android.support.design.widget.CoordinatorLayout>

    <android.support.design.widget.BottomNavigationView
        android:id="@+id/bottomMenu"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:background="@color/colorWhite"
        android:theme="@style/BottomStyle"
        app:elevation="0dp"
        app:itemTextAppearanceActive="@style/ActiveBottomNav"
        app:itemTextAppearanceInactive="@style/InActiveBottomNav"
        app:labelVisibilityMode="labeled"

        app:menu="@menu/bottom_menu" />


</android.support.design.widget.CoordinatorLayout>`

**Comment by thatsenam** [comment]
@lipangit Please Reply

**Comment by sosasang** [comment]
我在Crash Log里有同样问题:
Fatal Exception: java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.
cn.jzvd.Jzvd.gotoScreenNormal (Jzvd.java:728)

**Comment by lipangit** [comment]
是不是改库了？demo有这问题吗？

**Comment by sosasang** [comment]
我这里crash rate大概也就0.2% 不知道如何复现.......

**Comment by lipangit** [comment]
保持关注

**Comment by dycdiaobao** [comment]
同样的问题

**Comment by LucasXu01** [comment]
same as up

**Comment by lipangit** [comment]
7.0有这问题吗

**Comment by happyHou** [comment]
i hava same question.+1
