### ISSUE TITLE
如何播放视频时同时播放背景音乐

### ISSUE THREAD

**Issue by MrLaibin** [lipangit/JiaoZiVideoPlayer#2372]
**需求描述
视频比较简单，需要增加背景音乐。为减少音视频合成，增加了背景音乐。
进入页面播放视频，当从网络获取到音乐并播放会导致视频停止播放。

**Comment by MrLaibin** [comment]
已解决

**Comment by lipangit** [comment]
么么哒

**Comment by HerbLiu** [comment]
请问怎么解决的？我用vlc播放没有抢焦点的问题，但是用饺子就会出现在录音时抢焦点的问题，到时候无法录音识别，也想实现同时播放。。可以分享下吗

**Comment by lipangit** [comment]
饺子在开始播放时会发送广播，把这广播屏蔽掉就好了



---原始邮件---
发件人: "Herb"<notifications@github.com&gt;
发送时间: 2020年11月13日(周五) 下午2:21
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 如何播放视频时同时播放背景音乐 (#2372)




 
请问怎么解决的？我用vlc播放没有抢焦点的问题，但是用饺子就会出现在录音时抢焦点的问题，到时候无法录音识别，也想实现同时播放。。可以分享下吗
