### ISSUE TITLE
静态缩略图的问题

### ISSUE THREAD

**Issue by a26145** [lipangit/JiaoZiVideoPlayer#2378]
**需求描述
      版本6.2.12
     问题： 如何放大缩略图
    产生： 使用demo 正常  放到项目里的 player 的静态缩略图 很小， 不知道如何放大 试了很多次 都没有放大。  使用demo中的 图片地址 也仅仅是放大了一点，  是width 不能放大   希望 大家帮助

**Comment by lipangit** [comment]
你能截图说明吗。
尝试设置imageview的scaleType，这个本质就是imageview的调试

**Comment by a26145** [comment]
image
![无标题_副本](https://user-images.githubusercontent.com/18445846/55916456-01799e80-5c1f-11e9-9ef0-2a1207ba9198.png)

这个是 图片与player 本身的宽度 不符，我没找到 在哪里设置scaleType 我看demo理 没有设置 我试着设置 都没起效果
