### ISSUE TITLE
detect video player is playing in fullscreen

### ISSUE THREAD

**Issue by fukemy** [lipangit/JiaoZiVideoPlayer#2396]
Hi. please help me to know player is fullscreen. I need to back to normal video screen when press backbutton
here is my code to check
```
 if (JZMediaManager.isPlaying() && jzVideoPlayerStandard.currentScreen == JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN){
            jzVideoPlayerStandard.tinyBackImageView.performClick();
        }
```

**Comment by fukemy** [comment]
when i debug, i found  jzVideoPlayerStandard.currentScreen == 0 (SCREEN_NORMAL) even i am playing in fullscreen mode

**Comment by lipangit** [comment]
How did you goto fullscreen mode.

Directly fullscreen or press fullscreen button?

**Comment by fukemy** [comment]
i press full screen button

**Comment by lipangit** [comment]
did you change sourcecode?   You said is  impossible

**Comment by lipangit** [comment]
fullscreen and normal screen is not the same instance。
jzVideoPlayerStandard is the Normal one.

**Comment by fukemy** [comment]
Hi. can you provide way to detect it, it spent a few hours to find the solution, but still can not solve it

**Comment by fukemy** [comment]
my jzVideoPlayerStandard instance is inflated from xml:

```
 <cn.jzvd.JZVideoPlayerStandard
                    android:id="@+id/videoplayer"
                    android:layout_width="match_parent"
                    android:background="@color/black"
                    android:visibility="invisible"
                    android:layout_height="200dp" />
```

**Comment by lipangit** [comment]
1.extends jzvdStd

2.JzvdManager.currentJzvd() to control the current jzvd

**Comment by fukemy** [comment]
thanks. It work
```
if (JZMediaManager.isPlaying() && JZVideoPlayerManager.getCurrentJzvd().currentScreen == JZVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN){
            jzVideoPlayerStandard.tinyBackImageView.performClick();
        }
```

**Comment by lipangit** [comment]
ok
