### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by lydlovexyz** [lipangit/JiaoZiVideoPlayer#2402]
**什么jzvd版本
643最新版

**是否和安卓版本有关系，什么版本
没关系

**是否和特定品牌的手机机型有关系，什么机型
没关系

**相关log是什么
04-24 11:55:33.767 3671-3671/? E/subsystem_ramdump: Unable to open /dev
04-24 11:55:33.767 3671-3671/? E/subsystem_ramdump: Failed to find pil ramdump
04-24 11:55:35.572 2879-3330/com.vice.bloodpressure E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-24 11:55:35.573 2879-3330/com.vice.bloodpressure E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-24 11:55:35.573 2879-3330/com.vice.bloodpressure E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
04-24 11:55:35.573 2879-3330/com.vice.bloodpressure E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
04-24 11:55:35.670 609-3679/? E/MM_OSAL: FileSource::FileSource
04-24 11:55:35.670 609-3679/? E/MM_OSAL: FileSource::FileSource m_bEveryThingOK 1
04-24 11:55:35.670 609-3679/? E/MM_OSAL: MM_File_Create failed .Efs Error No -1 , File Name /data/mmosal_logmask.cfg , Mode 0
04-24 11:55:35.670 609-3679/? E/MM_OSAL: Open or read fail on /data/mmosal_logmask.cfg. Possible permission denied issue. Looking for /data/misc/media/mmosal_logmask.cfg
04-24 11:55:35.671 609-3679/? E/MM_OSAL: MM_File_Create failed .Efs Error No -1 , File Name /data/misc/media/mmosal_logmask.cfg , Mode 0
04-24 11:55:35.710 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
04-24 11:55:35.710 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
04-24 11:55:35.711 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
04-24 11:55:35.798 609-3681/? E/NuCachedSource2: source returned error -1010, 0 retries left
04-24 11:55:35.799 609-3679/? E/MM_OSAL: Mpeg4File::mp4ParseStatus Failed to readFile @ 1011838, size 0
04-24 11:55:36.072 609-3681/? E/NuCachedSource2: source returned error -1010, 0 retries left
04-24 11:55:36.072 609-3679/? E/MM_OSAL: Mpeg4File::mp4ParseStatus Failed to readFile @ 1011838, size 0
04-24 11:55:36.085 609-3679/? E/MMParserExtractor:  FileSourceWrapper::New returned NULL 
04-24 11:55:36.086 609-3679/? E/MMParserExtractor: MMParserExtractor::countTracks readMetaData failed 
      
04-24 11:55:36.086 609-3679/? E/GenericSource: Failed to init from data source!
04-24 11:55:36.087 2879-2892/com.vice.bloodpressure E/MediaPlayer: error (1, -2147483648)
04-24 11:55:36.087 2879-3330/com.vice.bloodpressure E/MediaPlayer: Error (1,-2147483648)
04-24 11:55:36.087 2879-2879/com.vice.bloodpressure E/JZVD: onError 1 - -2147483648 [183724954] 
04-24 11:55:38.796 3682-3682/? E/subsystem_ramdump: Unable to open /dev
04-24 11:55:38.796 3682-3682/? E/subsystem_ramdump: Failed to find pil ramdump
04-24 11:55:40.711 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
04-24 11:55:40.711 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XT-CS] unknown deliver target [OS-Agent]
04-24 11:55:40.711 652-716/? E/QCALOG: [MessageQ] ProcessNewMessage: [XTWiFi-PE] unknown deliver target [OS-Agent]
04-24 11:55:43.827 3683-3683/? E/subsystem_ramdump: Unable to open /dev
04-24 11:55:43.827 3683-3683/? E/subsystem_ramdump: Failed to find pil ramdump
**复现流程

**最好有截图或者视频说明情况

**Comment by lydlovexyz** [comment]
测试用String url = "http://refile.huahansoft.com/filefoldername/worksvideo/mobile/201904/190408051437538467.mp4";

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/56655241-c9656780-66c4-11e9-8659-95fca20abce6.png)

我觉得这部分log应该是重点，和服务器沟通一下需不需要设置header等配置

**Comment by lydlovexyz** [comment]
切换到B站的内核就可以播放了
