### ISSUE TITLE
9.0系统下 读取视频缓慢

### ISSUE THREAD

**Issue by 836198048** [lipangit/JiaoZiVideoPlayer#2405]
相关问题:
同一个视频
9.0系统下 视频刚开始播放了几秒 然后一定要等到 进度条全部读取之后才会继续播放
而不是边缓存边播放
在8.0系统下不会出现这种情况(不知道8.0是不是缓存太快了 我没看到 类似在9.0那边看到的缓存进度条)

[什么jzvd版本]
demo的版本
**是否和安卓版本有关系，什么版本
目前测试和系统版本有关 9.0(小米8se)
8.0的小米6没出现这情况
之后用9.0的genymotion模拟器 也是一个情况

**最好有截图或者视频说明情况
8.0 不会卡
http://upload.ouliu.net/i/20190425090308sfe6o.jpeg
9.0 卡了 直到缓存条全部读取完成继续播放
http://upload.ouliu.net/i/201904250905599z50w.jpeg

**Comment by 836198048** [comment]
测试用视频地址:
http://xsa.fjsibu.com/data/upload/xsa/video/15/video_5cb9abc96e4cf.mp4

**Comment by lipangit** [comment]
每秒速度多少，这和服务器和视频本身有直接关系。 如果视频时间很短但是体积特别大，导致网速跟不上播放的速度------------------ 原始邮件 ------------------
发件人: "fanxi"<notifications@github.com>
发送时间: 2019年4月25日(星期四) 上午9:20
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [lipangit/JiaoZiVideoPlayer] 9.0系统下 读取视频缓慢 (#2405)



测试用视频地址:
 http://xsa.fjsibu.com/data/upload/xsa/video/15/video_5cb9abc96e4cf.mp4
 
&mdash;

**Comment by 836198048** [comment]
测试的视频地址我已经贴出来了, 同个视频 8.0的系统每次打开都很快, 9.0的每次打开都需要等
如果是视频本身的问题,应该8.0系统上也会发生一样的情况
我是直接用地址替换 最新的demo里面的视频地址 也会出现这个问题

**Comment by 836198048** [comment]
那个视频20秒 17mb

**Comment by AnYuer** [comment]
大神您好，我这边是一台 1+6 手机，没有外设的内存卡，然后视频播到50%以上一会会的时候，会直接报错，报错内容是：“没有内存卡读写权限：mp4ReadStatus VIDEO_FMT_FAILURE
2019-06-10 16:17:18.976 935-7809/? E/MM_OSAL: Mpeg4File::getSample FATAL starting at 24931544, size 3834
2019-06-10 16:17:18.976 935-30797/? E/MM_OSAL: Mpeg4File::mp4ReadStatus Failed to readFile
2019-06-10 16:17:18.976 935-30797/? E/MM_OSAL: Read File Error!”然后不继续播放了，卡在那个页面，请问该怎么处理？谢谢您。

**Comment by phoenix-appscore** [comment]
我在vimeo上的影片也是如此，測過Samsung S7edge、S8、S8+，Android 8以前都正常，Android 9就會有長短不一的卡住時間，直到全部讀取完才會播放。

**Comment by lipangit** [comment]
一行代码换播放内核 或者自定义播放内核

**Comment by phoenix-appscore** [comment]
目前測試的結果，切換成JZMediaExo可以解決此問題。非常感謝！

**Comment by lipangit** [comment]
么么哒
