### ISSUE TITLE
版本是5.5的，然后进度条拖动到1分钟的时候按暂停，然后再拖动到0:0的位置，当前的时间并没有恢复到0:0

### ISSUE THREAD

**Issue by yixiu30** [lipangit/JiaoZiVideoPlayer#2408]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
亲测可以恢复到0：0  更新一下版本。   

或者你录小视频看看效果

**Comment by yixiu30** [comment]
好的，非常感谢
