### ISSUE TITLE
播放本地视频第五个的时候程序会崩掉

### ISSUE THREAD

**Issue by x599904694** [lipangit/JiaoZiVideoPlayer#2409]
我用ViewPager+JiaoZiVideoPlayer做的一个视频轮播，视频在SD卡里面，轮播到第五个的时候，程序会崩掉。
错误信息是：queueBuffer: BufferQueue has been abandoned!

**Comment by x599904694** [comment]
版本是6.4.3

**Comment by lipangit** [comment]
这不是崩溃的bug，再找找

**Comment by x599904694** [comment]
每一次崩溃的时候就报这个错，别的没有了

**Comment by x599904694** [comment]
怎么切换播放引擎，我想换个引擎试试

**Comment by x599904694** [comment]
E/BufferQueueProducer: [unnamed-21329-6] cancelBuffer: BufferQueue has been abandoned
NativeWindowBuffer: Calling cancelBuffer on buffer 0x1b hanlde( 0xb851cd20 )

**Comment by lipangit** [comment]
参考demo的CustomMediaPlayer，setMediaInterface() 一行代码切换
