### ISSUE TITLE
建议将亮度、音量和进度调节代码进行封装，方便继承之后修改更简单

### ISSUE THREAD

**Issue by ToxicR** [lipangit/JiaoZiVideoPlayer#2418]
**需求描述
建议将亮度、音量和进度调节代码进行封装，方便继承之后修改更简单
**其他app是否实现
版本：6.4.1
**截图或者小视频说明
![QQ图片20190506113454](https://user-images.githubusercontent.com/19481920/57205737-32b57680-6ff3-11e9-9b5d-265101364fe5.png)

**Comment by lipangit** [comment]
嗯，是个不错的建议，有具体的思路吗，通过继承手势的函数，简单修改参数就能修改调节的逻辑

**Comment by ToxicR** [comment]
我是在项目需求中遇到在普通窗口（非全屏）的时候也需要有对亮度、音量和播放进度的调节。
但是看到源码中是只对全屏窗口的时候进行了支持，但是我又不想使用moudle依赖的方式，就只能复写OnTouch方法，然后判断普通窗口下执行和全屏窗口相同的逻辑（直接复制的项目源码），所以觉得这种写法有点丑陋。
但是看到大佬回复我的，让我感觉我的想法只是一部分，我个人的想法是这样的：1.可以将手势操作（目前只针对亮度、音量和播放控制）在视频哪种状态生效改为可配置，而不是只是在全屏状态生效；2.将相关调节的代码封装成函数，使用者自行判断onTuch及视频窗口状态来完成所需的需求；3.提供相关函数，使使用者可以对相关调节参数进行自定义（个人认为这种场景比较少，除非自己公司对这几种调节有严格规定）。

**Comment by SaberrrC** [comment]
非常赞同增加这个功能

**Comment by lipangit** [comment]
我也很赞同啊兄弟
