### ISSUE TITLE
7.0.1版本gradle下来 classes.jar是空的  

### ISSUE THREAD

**Issue by deboLing** [lipangit/JiaoZiVideoPlayer#2420]
**什么jzvd版本
7.0.1
**是否和安卓版本有关系，什么版本
和手机没有关系
**是否和特定品牌的手机机型有关系，什么机型
没有
**相关log是什么
没有
**复现流程
引用implementation 'cn.jzvd:jiaozivideoplayer:7.0.1'  找不到相关java类
**最好有截图或者视频说明情况

**Comment by 99helloworld** [comment]
同问

**Comment by DaLeiGe** [comment]
是的

**Comment by wangsanpiao** [comment]
我也是

**Comment by Power-Android** [comment]
me 吐

**Comment by junstyle** [comment]
好晕啊，害我调试了半天

**Comment by lipangit** [comment]
打包有问题，不知道为啥aar里面没有代码库

**Comment by LoverJoker** [comment]
群主啥时候修复下

**Comment by t7cutcdeeyx1** [comment]
顶一下

**Comment by lipangit** [comment]
7.0.1不要用了，仓库有问题， 7.0.2和7.0.1是一模一样的，目前最新是7.0.3
