### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ravig252525** [lipangit/JiaoZiVideoPlayer#2423]
How to Audios play in service  background

**Comment by lipangit** [comment]
This requirement requires a lot of changes. If there is no ui, it is best to do it from zero.

**Comment by ravig252525** [comment]
Without play button press I want to programmatically play

**Comment by lipangit** [comment]
You need to study this need yourself.

**Comment by lipangit** [comment]
It is about how to play mp3, it is a audios player.
