### ISSUE TITLE
改成ijkPlay播放rtmp视频流卡在第一帧

### ISSUE THREAD

**Issue by iwuq** [lipangit/JiaoZiVideoPlayer#2426]
改成ijkPlay播放rtmp视频流卡在第一帧，改流是只有视频没有音频的视频流；用其他的第三方ijkplayer可以正常播放

**Comment by lipangit** [comment]
饺子也是用的原封不动的ijkplayer 研究一下是不是饺子的代码影响播放了

**Comment by iwuq** [comment]
已解决，发现是饺子保存了进度导致的

**Comment by lipangit** [comment]
保存进度这个问题是rtmp通用的问题呢  还是饺子保存进度的方式不对

**Comment by iwuq** [comment]
我是后来卸载重装发现第一次能正常播放，之后再播就是卡在第一帧。后面把饺子保存进度改成false才正常

**Comment by lipangit** [comment]
在ijkplayer项目中用你的url，重播是否正常。

或者把你的url发给我我试试。

**Comment by iwuq** [comment]
重播没有测试，因为我不需要重播功能，url因为是公司的一个私有地址，无法公开，抱歉！

**Comment by lipangit** [comment]
把你的url放到ijkplayer的官方demo中，第一次播放是否正常，之后再播放是否正常？需要你测试一下这个。

如果之后再播放也不正常说明饺子保存进度的方式不对

如果你没时间，url可以qq发给我，测试研究用，相信公司可以理解，我以前还给别人调试过整个app，解决了他引用的饺子的问题。

**Comment by fylw** [comment]
升级7.0.5后ijkplay第一次能够播放，后面就一直卡着显示转圈的动画

**Comment by lipangit** [comment]
@fylw 更新一下自定义的播放内核

**Comment by yangwenwu** [comment]
@iwuq @lipangit  在哪里修改这个保存进度

**Comment by yangwenwu** [comment]
JZVideoPlayer.SAVE_PROGRESS = false; 应该是这个吧  @iwuq @lipangit

**Comment by lipangit** [comment]
@yangwenwu 是的
