### ISSUE TITLE
Null pointer exception when onViewRecycled method runs in adapter?

### ISSUE THREAD

**Issue by uzaysan** [lipangit/JiaoZiVideoPlayer#2427]
I wanna clear thumb image view when video view is recycled to avoid Out of Memory error.

This is my method:
```
@Override
    public void onViewRecycled(@NonNull ViewHolder holder) {
        super.onViewRecycled(holder);

        if(holder.videoplayerjz!=null){
            if (holder.videoplayerjz.thumbImageView != null) {
                if(holder.videoplayerjz.thumbImageView.getVisibility()==View.VISIBLE){
                    Glide.with(holder.itemView.getContext()).clear(holder.videoplayerjz.thumbImageView);
                    holder.videoplayerjz.thumbImageView.setImageDrawable(null);
                    holder.videoplayerjz.thumbImageView.setImageBitmap(null);
                }
            }
        }

        

    }
```

Even if I check if itn null or not still gives me Null pointer exception.

My recyclerview has 4 types of view:
Video is one of them.

This error only happens if populated layout doesnt have videoplayer.

**Comment by lipangit** [comment]
what log looks like

**Comment by uzaysan** [comment]
> what log looks like

I can't re-produce that error right now. But error happened 3 times in a row. If I ever face that error again i will post here.
