### ISSUE TITLE
6.2.12版本JZUserAction貌似有bug

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2428]
**什么jzvd版本
6.2.12
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

使用的是6.2.12 不知道最新版本有没有修复，没有测试  
发现在某个地方设置了JZUserAction后  JZUserAction就不会变更了releaseAllVideos貌似也没有release这个对象。 全局都是使用了这个对象。导致某些回调异常。进一步如果JZUserAction对象是activity 会不会导致activity不能回收而内存溢出？

**Comment by lipangit** [comment]
所以在7.0版本干掉他了，参考demo的MyJzvdStd，里面有事件的地方都有标记
