### ISSUE TITLE
ConstraintLayout不支持比列调节，wrap_content的效果和math_parent一样，不能根据视频大小调节控件大小

### ISSUE THREAD

**Issue by memoryjs** [lipangit/JiaoZiVideoPlayer#2429]
**什么jzvd版本
6.4.3

**是否和安卓版本有关系，什么版本
和安卓版本没关系

**是否和特定品牌的手机机型有关系，什么机型
没关系

**相关log是什么
100%复现

**复现流程
100%复现

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
这个本质上是布局Layout的问题，和视频播放没有关系，仔细研究ConstraintLayout或者更换它

**Comment by memoryjs** [comment]
我这是两个问题，ConstraintLayout不支持比例调节是一个问题
在其它layout下，wrap_content 和match_parent一样，这是第二个问题

**Comment by lipangit** [comment]
Jzvd的布局问题本质上和textview的布局并无区别，还是得多尝试。
