### ISSUE TITLE
播放Mp4的视频第一次需要等待很长的时间，其他的播放器不会

### ISSUE THREAD

**Issue by OfffLine** [lipangit/JiaoZiVideoPlayer#2430]
7.03版本
第一次播放需要加载很长时间，试过华为系统播放器以及其他的播放器播放速度很快
播放链接如下，
https://outin-3df62ba9542f11e9b54700163e1c94a4.oss-cn-shanghai.aliyuncs.com/sv/5ac7d1d0-16a61fbe236/5ac7d1d0-16a61fbe236.mp4?Expires=1558024189&OSSAccessKeyId=LTAItL9Co9nUDU5r&Signature=yvaIECapQTGjecDwo%2BPORQa7yZE%3D

**Comment by lipangit** [comment]
加载时长取决于播放器内核，默认饺子用系统的android.media.MediaPlayer。   播放快速的用什么播放内核？

**Comment by jmhjmh** [comment]
不建议用自带的，对系统版本什么的要求有点高

**Comment by OfffLine** [comment]
是的已经切换至EXOplayer效果好很多了，非常感谢

**Comment by Rose-YiTu** [comment]
请问一下具体是怎么切换为EXOplayer的呢，有没有类呢

**Comment by lipangit** [comment]
@Rose-YiTu  参考demo的customMediaPlayer

**Comment by seraphzxz87** [comment]
customMediaPlayer 在哪？具体是哪个类还是方法？

**Comment by lipangit** [comment]
取决于播放内核，可以一行代码切换到exoplayer&nbsp; 或者ijkplayer



---原始邮件---
发件人: "seraphzxz87"<notifications@github.com&gt;
发送时间: 2020年3月1日(周日) 下午4:30
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 播放Mp4的视频第一次需要等待很长的时间，其他的播放器不会 (#2430)



customMediaPlayer 在哪？具体是哪个类还是方法？
