### ISSUE TITLE
java.lang.NoSuchMethodException: <init> [class cn.jzvd.y]

### ISSUE THREAD

**Issue by nilsorathiya** [lipangit/JiaoZiVideoPlayer#2432]
I can't play video using v7.0.3...

Working fine with debug APK but When I am testing release APK then issue occurs...

> .xml

<cn.jzvd.JzvdStd
                    android:id="@+id/videoplayer"
                    android:layout_width="match_parent"
                    android:layout_height="220dp"
                    android:layout_gravity="center" />

`JzvdStd videoPlayer = (JzvdStd) findViewById(R.id.videoplayer);`
`videoPlayer.setUp("URL will goes here", "Title will goes Here", JzvdStd.SCREEN_NORMAL);`

> build.gradle(app)
`implementation 'cn.jzvd:jiaozivideoplayer:7.0.3'`

> Issue:
java.lang.NoSuchMethodException: <init> [class cn.jzvd.y]

**Comment by lipangit** [comment]
how did you reference the library, in gradle or aar

**Comment by nilsorathiya** [comment]
@lipangit I just updated my question, please take a look...

**Comment by lipangit** [comment]
the JzvdStd class do not need proguard. try this

![image](https://user-images.githubusercontent.com/2038071/57930294-2204da80-78e8-11e9-9e00-3c917eb6ef06.png)

**Comment by lipangit** [comment]
but the JzvdStd class do not need proguard.

**Comment by nilsorathiya** [comment]
It's perfect working with Debug APK & I don't think this line in proguard will work.
but let me try.

**Comment by lipangit** [comment]
What looks like in your xml

**Comment by lipangit** [comment]
<init> function  did not be proguard to other function name?

**Comment by nilsorathiya** [comment]
> What looks like in your xml

Please check my udpated Question, I have added My XML part.

**Comment by lipangit** [comment]
Demo project do not have this problem

**Comment by nilsorathiya** [comment]
Worked:

-keep public class cn.jzvd.JZMediaSystem {*; }

by adding this line, VideoPlayer is working fine.

**Comment by lipangit** [comment]
Good
