### ISSUE TITLE
缩略图暂时效果不能根据setVideoImageDisplayType的模式去自动变化么？

### ISSUE THREAD

**Issue by Yangwei0987** [lipangit/JiaoZiVideoPlayer#2437]
现在的情况是默认情况下缩率图会有黑边，视频播放我设置了JZVideoPlayer.VIDEO_IMAGE_DISPLAY_TYPE_FILL_SCROP
我设置scaleType的话，缩略图会有点拉伸，导致loading切换到播放状态过度有点生硬体验有点不太好。不设置缩率图背景又是黑的。
所以想请教下有没有什么办法去优化下这个体验。

**Comment by Yangwei0987** [comment]
还有一个问题是scaleType设置后，缩率图加载的话会是黑边缩率图--全屏缩率图--播放。就感觉很奇怪，是我设置的地方不对吗？

**Comment by lipangit** [comment]
截图看看什么样
