### ISSUE TITLE
全屏模式下，挖孔屏手机左上角的退出全屏键被摄像头遮挡，如何移动按钮位置？

### ISSUE THREAD

**Issue by jerry9433** [lipangit/JiaoZiVideoPlayer#2439]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
能拍照看看什么样，我没见过那种手机。

移动按钮非常简单，继承jzvdStd，复写getLayoutId函数，把库的xml布局复制到自己的项目里，然后随意修改按钮位置，无需修改任何java代码。
