### ISSUE TITLE
一开始设置的landscape模式，视频只占了界面的一部分，当点击全屏展示在退出全屏幕是时，界面上其他的控件都没了，就只有视频播放的；

### ISSUE THREAD

**Issue by zhangzhen92** [lipangit/JiaoZiVideoPlayer#2442]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/58642211-728c2700-832f-11e9-92b3-83fa49422314.png)
布局外面要包一层
