### ISSUE TITLE
JZMediaSystem mMediaHandler   以下地方没判空，遇到空指针

### ISSUE THREAD

**Issue by dahai2070** [lipangit/JiaoZiVideoPlayer#2450]
JZMediaSystem 以下地方没判空，遇到空指针

   @Override
    public void start() {
        if (mMediaHandler != null && mediaPlayer != null) {
            mMediaHandler.post(() -> mediaPlayer.start());
        }
    }

    @Override
    public void pause() {
        if (mMediaHandler != null && mediaPlayer != null) {
            mMediaHandler.post(() -> mediaPlayer.pause());
        }
    }

**Comment by lipangit** [comment]
能研究一下mediaplayer为什么是空吗，能从源头解决吗

**Comment by xwhPanda** [comment]
我也碰到这个问题了

**Comment by PoetGcc** [comment]
在列表中播放，遇到JZMediaSystem 中  mediaPlayer.prepareAsync();  这行报空，目前还不确定具体原因

**Comment by lipangit** [comment]
怎么样了，demo有这问题吗，mediaplayer开始就报空，这个好像很严重
