### ISSUE TITLE
继承倍数播放类，点击全屏应用卡死

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2452]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
需要更多信息

**Comment by hu374307261** [comment]
已解决，调用错了
