### ISSUE TITLE
横屏时播放文字正常，切换成竖屏是文字只显示三分之一

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2453]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
需要更多信息

**Comment by hu374307261** [comment]
播放文字的显示，在全屏时只显示了一部分，其余被遮盖了

**Comment by hu374307261** [comment]
播放文字太往下了，哪里可以控制播放文字的位子大佬？

**Comment by starrysky0** [comment]
> 播放文字太往下了，哪里可以控制播放文字的位子大佬？
是字幕么

**Comment by hu374307261** [comment]
是的，是字幕

**Comment by starrysky0** [comment]
> 是的，是字幕

是外挂字幕么

**Comment by hu374307261** [comment]
视频播放声音说话的字幕，进度条底部

**Comment by starrysky0** [comment]
> 视频播放声音说话的字幕，进度条底部

字幕格式是什么

**Comment by hu374307261** [comment]
播放器自己的，文字

**Comment by starrysky0** [comment]
> 播放器自己的，文字

能提供下视频么

**Comment by hu374307261** [comment]
https://alivideo.dd-img.com/8dcc6de6723f49b5b6a7981ab9d0239b/c844ff9e39074d4dace545ee14afff46-02d3d7bcf05914d8b26c09ba49b08d97-ld.mp4

**Comment by starrysky0** [comment]
> https://alivideo.dd-img.com/8dcc6de6723f49b5b6a7981ab9d0239b/c844ff9e39074d4dace545ee14afff46-02d3d7bcf05914d8b26c09ba49b08d97-ld.mp4

参考demo ActivityApiRotationVideoSize setVideoImageDisplayType  设置不同的type试试

**Comment by hu374307261** [comment]
好的，谢谢谢
