### ISSUE TITLE
我这集成了之后，播放flv的视频，只有在oppo和小米手机上能播放，其他手机上点播放按钮出现一个感叹号图标，这是什么原因呢

### ISSUE THREAD

**Issue by Rose-YiTu** [lipangit/JiaoZiVideoPlayer#2454]
**需求描述
视频地址：http://henan1.sport.push.opssee.com.cn/sport/ZK-000101.flv?auth_key=1560146341-0-0-5cf139acb1a0158a390f63d43b1d10ce
**其他app是否实现

**截图或者小视频说明

**Comment by starrysky0** [comment]
切换播放内核试试

**Comment by starrysky0** [comment]
视频地址无法访问

**Comment by Rose-YiTu** [comment]
这是一个直播地址，本身是没办法用浏览器打开的

**Comment by Rose-YiTu** [comment]
我试着切换成了ijkPlayer引擎，还是视频加载失败

**Comment by lipangit** [comment]
这是一个典型的播放内核不能播放视频的问题，咱们项目只能更换播放内核，你也可以定制播放内核，要么让播放内核去适应视频，要么让视频去适应播放内核。或者到相应的播放内核项目中提问，这种问题超出项目的解决范围。
