### ISSUE TITLE
如何实现exo静音

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2457]
**需求描述 使用EXO播放器，如何实现列表静音，

**其他app是否实现 

**截图或者小视频说明

**Comment by lipangit** [comment]
参考demo里有一个非全屏静音，全屏有声音的例子。

**Comment by hu374307261** [comment]
放入 exo播放器之后，调用setScreenNormal 静音无效，没有加入之前，可以无声

**Comment by lipangit** [comment]
就是说你在demo中把demo的静音例子设置成exoplayer，没有效果是吗？

**Comment by lipangit** [comment]
代码怎么写的，截图看看，症状什么样录像看看

**Comment by hu374307261** [comment]
@Override
    public void setScreenNormal() {
        super.setScreenNormal();
        backButton.setVisibility(INVISIBLE);
        clearView();
        if (mediaInterface != null)
            mediaInterface.setVolume(0f, 0f);
    }


 if (!TextUtils.equals("", commentItem.getAlitv_id()) && alitvUrl != null && alitvUrl.size() > 0) {
            helper.setGone(R.id.video_linear, true);
            JzvdStdVolumeAfterFullscreen jzvd = helper.getView(R.id.videoplayer);

            String url = alitvUrl.get(0).getUrl();
            jzvd.setUp(url, "", Jzvd.SCREEN_NORMAL, JZMediaExo.class);
            Jzvd.setVideoImageDisplayType(Jzvd.VIDEO_IMAGE_DISPLAY_TYPE_FILL_PARENT);
            jzvd.onClickFlag = true;
            jzvd.setScreenNormal();
            jzvd.setClickControlView(commentItem.getContentid());
            jzvd.setOnItemClickListener(new DDBOnItemClickListener() {
                @Override
                public void OnItemClick(long t) {
                    Intent intent = new Intent(mContext, VideoPlayerNewDetailActivity.class);
                    intent.putExtra(KeyConstant.INTENT_PLAT_ID_KEY, 5L);
                    intent.putExtra(KeyConstant.INTENT_ARTICLE_ID_KEY, t);
                    intent.putExtra(KeyConstant.INTENT_TAG_CURRENT_PLAYER_TYPE, "mainVideo");
                    intent.putExtra(KeyConstant.INTENT_TAG_CURRENT_PLAYER, jzvd.getCurrentPositionWhenPlaying());
                    mContext.startActivity(intent);
                }
            });
            ImageLoaderUtil.loadImage(mContext, commentItem.getImg_url(), jzvd.thumbImageView);
            jzvd.setItemAutoPlayClick(new DDBOnItemAutoPlay() {
                @Override
                public void OnItemAutoPlayClick() {
                    helper.setGone(R.id.item_article_big_img, false);
                    helper.setGone(R.id.item_article_big_video, false);
                }

                @Override
                public void OnItemPauseAutoPlayClick() {
                    jzvd.startButton.performClick();
                    helper.setGone(R.id.item_article_big_img, true);
                    helper.setGone(R.id.item_article_big_video, true);
                }
            });
        }

**Comment by lipangit** [comment]
setItemAutoPlayClick类似set的各种listener，不要这么做，第一步先继承JzvdStd，把这些listener的逻辑放到继承的类里。

**Comment by lipangit** [comment]
然后你看到demo中静音的例子了吗

**Comment by hu374307261** [comment]
都是在继承类里操作的。ActivityTinyWindowRecycleViewMultiHolder这个类吗

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/59333698-7a829880-8d2b-11e9-9830-89f1b61a4156.png)

ActivityApiUISmallChange这个页面看到了吗

**Comment by lipangit** [comment]
继承JzvdStd创建自己的Jzvd。  你看上图的自定义JzvdStd是怎么写

**Comment by hu374307261** [comment]
JzvdStdVolumeAfterFullscreen   用的这个类，用完还是有声音，if下面是adapter ,  上面是JzvdStdVolumeAfterFullscreen

**Comment by hu374307261** [comment]
JzvdStdVolumeAfterFullscreen   

 if (mediaInterface != null)
            mediaInterface.setVolume(0f, 0f);不走

**Comment by lipangit** [comment]
demo的JzvdStdVolumeAfterFullscreen有问题吗，什么都不改的情况下

解决了吗 怎么关了

**Comment by hu374307261** [comment]
没有但是默认的就可以不知道这是哪里原因，

**Comment by hu374307261** [comment]
没有但是默认的就可以不知道这是哪里原因，

**Comment by hu374307261** [comment]
UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.SimpleExoPlayer.setVolume(float)' on a null object reference
        at com.diandong.cn.jzvd.JZMediaExo.setVolume(JZMediaExo.java:176)

**Comment by hu374307261** [comment]
使用最暴力的方式直接设置无声可以！这种感觉太垃圾了，希望群主，看看怎么不走，方法调用，着急上线目前没时间研究

**Comment by hu374307261** [comment]
使用最暴力的方式直接设置无声可以！这种感觉太垃圾了，希望群主，看看怎么不走，方法调用，着急上线目前没时间研究

**Comment by zzspuck** [comment]
exo 没有调用onPrepared 这个方法所以demo中的换成exo控制声音就不行了

**Comment by Jiawei1994** [comment]
> 使用最暴力的方式直接设置无声可以！这种感觉太垃圾了，希望群主，看看怎么不走，方法调用，着急上线目前没时间研究
你好，请问你现在设置ExoPlayer 无法静音解决了吗？我现在也是实现强制静音。因为ExoPlayer没有调用onPrepared 方法
