### ISSUE TITLE
mediaplayer的setDataSource为什么要用反射的方式获取？

### ISSUE THREAD

**Issue by liming11** [lipangit/JiaoZiVideoPlayer#2458]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/59778563-4db12100-92e9-11e9-8cee-fff923deddf5.png)

这个函数不公开
