### ISSUE TITLE
详情回跳列表播放

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2462]
**需求描述  详情页跳转列表，拿到详情页时间设置上，却一直是从新播放，请问怎么设置呢？比如有什么Demo

**其他app是否实现  其他 主流都有详情列表回拨  今日头条 、汽车之家

**截图或者小视频说明

**Comment by lipangit** [comment]
详情页的问题正在做理论上已经研究完毕。找时间放到demo中

**Comment by hu374307261** [comment]
谢谢群主，希望能够找点放出demo，好有时间学习学习

**Comment by lipangit** [comment]
兄弟  今日头条从详情页退出到列表，直接就停止播放了。

**Comment by hu374307261** [comment]
有一个人用的饺子视频实现了，列表播放，进入详情继续播放，退出继续在列表播放，https://github.com/zzh12138/JZVideoDemo

**Comment by hu374307261** [comment]
能否研究下加进去，群主

**Comment by lipangit** [comment]
详情页理论上已经解决

**Comment by hu374307261** [comment]
怎么解决的呢？但是我跳转还是不好使呢
