### ISSUE TITLE
播放直播视频卡顿

### ISSUE THREAD

**Issue by jasonwang1991** [lipangit/JiaoZiVideoPlayer#2463]
**需求描述
播放正在直播的视频 过个半分钟就会出现卡顿（显示loading 有时候1-2秒 偶尔会直接卡死）
**其他app是否实现
ios播放没有任何卡顿效果
**截图或者小视频说明
![image](https://user-images.githubusercontent.com/23151366/59481912-fa7a4100-8e98-11e9-9d2b-20306aa5dccd.png)

**Comment by lipangit** [comment]
超出老臣解决范围，这是播放内核决定，可以自定义播放内核，可以一行代码切换播放内核。
