### ISSUE TITLE
视频播放

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2464]
**什么jzvd版本  最新版

**是否和安卓版本有关系，什么版本 7.0

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么  

**复现流程  

**最好有截图或者视频说明情况  视频播放在子fragment列表时播放一直在加载，子的同级fragment就播放很流畅

**Comment by lipangit** [comment]
demo有viewpager嵌套fragment嵌套listview的例子，一直加载和嵌套应该没啥关系的。log是什么

**Comment by hu374307261** [comment]
最初一开始是可以的，播放几次，就出现一直在加载当中

**Comment by hu374307261** [comment]
06-17 10:52:59.161 24746-24746/com.diandong.android.app I/JZVD: startVideo
06-17 10:52:59.182 24746-24746/com.diandong.android.app I/JZVD: onStateNormal  [6394657] 
06-17 10:52:59.183 24746-24746/com.diandong.android.app I/JZVD: onClick start [6394657] 
06-17 10:52:59.183 24746-24746/com.diandong.android.app D/JZVD: startVideo [6394657] 
06-17 10:52:59.183 24746-24746/com.diandong.android.app I/JZVD: reset  [92420130] 
    onStateNormal  [92420130] 
06-17 10:52:59.185 2309-4042/? I/MediaFocusControl: abandonAudioFocus() from uid/pid 10232/24746 clientId=android.media.AudioManager@80d52c3com.diandong.cn.jzvd.Jzvd$1@2b5d740
06-17 10:52:59.186 24746-24746/com.diandong.android.app D/JZVD: addTextureView [6394657] 
06-17 10:52:59.187 2309-4042/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10232/24746 clientId=android.media.AudioManager@80d52c3com.diandong.cn.jzvd.Jzvd$1@2b5d740 callingPack=com.diandong.android.app req=2 flags=0x0 sdk=27
06-17 10:52:59.189 24746-24746/com.diandong.android.app I/JZVD: onStatePreparing  [6394657] 
    startVideo
06-17 10:52:59.254 24746-24746/com.diandong.android.app I/JZVD: onClick start [228413042] 
06-17 10:52:59.254 24746-24746/com.diandong.android.app D/JZVD: startVideo [228413042] 
06-17 10:52:59.254 24746-24746/com.diandong.android.app I/JZVD: reset  [6394657] 
06-17 10:52:59.255 24746-24746/com.diandong.android.app I/JZVD: onStateNormal  [6394657] 
06-17 10:52:59.256 2309-4042/? I/MediaFocusControl: abandonAudioFocus() from uid/pid 10232/24746 clientId=android.media.AudioManager@80d52c3com.diandong.cn.jzvd.Jzvd$1@2b5d740
06-17 10:52:59.258 24746-24746/com.diandong.android.app D/JZVD: addTextureView [228413042] 
06-17 10:52:59.259 2309-4042/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10232/24746 clientId=android.media.AudioManager@80d52c3com.diandong.cn.jzvd.Jzvd$1@2b5d740 callingPack=com.diandong.android.app req=2 flags=0x0 sdk=27
06-17 10:52:59.262 24746-24746/com.diandong.android.app I/JZVD: onStatePreparing  [228413042] 
06-17 10:52:59.264 24746-24746/com.diandong.android.app I/JZVD: startVideo
06-17 10:53:00.941 24746-24746/com.diandong.android.app I/JZVD: onStateNormal  [2051009] 
06-17 10:53:00.978 24746-24746/com.diandong.android.app I/JZVD: onStateNormal  [251909819] 
06-17 10:53:01.013 24746-24746/com.diandong.android.app I/JZVD: onStateNormal  [17429797] 
06-17 10:53:01.022 24746-24746/com.diandong.android.app W/View: requestLayout() improperly called by com.diandong.cn.jzvd.JZTextureView{910d8b8 V.ED..... ......ID 0,0-970,0} during layout: running second layout pass

**Comment by hu374307261** [comment]
我的是vp 嵌套 fragment 然后，fragment  里 产品全套 fragment?就不好使了一直处于进度条加载状态？

**Comment by lipangit** [comment]
demo 有这问题吗？  demo 页游vp嵌套fragment的，  或者把你的情况在demo中复现一下。
