### ISSUE TITLE
手机横着的时候跳转页面自动旋转播放视频,UI会过大

### ISSUE THREAD

**Issue by duliduli** [lipangit/JiaoZiVideoPlayer#2467]
正常进入--正常
![image](https://user-images.githubusercontent.com/23184046/59730721-076eaa00-9276-11e9-9118-e6d614a8cd86.png)
 正常进入后重力感应切换横屏---正常
![image](https://user-images.githubusercontent.com/23184046/59730803-5ae0f800-9276-11e9-8d0e-b2525aa7a16e.png)
直接横着手机进入重力感应切换横屏--异常,,UI过大
![image](https://user-images.githubusercontent.com/23184046/59730752-20775b00-9276-11e9-9095-9805188e90b4.png)

**Comment by lipangit** [comment]
图三本质上还是普通屏幕不是全屏，设置当前activity不许横屏

**Comment by lipangit** [comment]
然后通过重力感应进入横屏
