### ISSUE TITLE
Jzvd.releaseAllVideos()

### ISSUE THREAD

**Issue by Born-alone** [lipangit/JiaoZiVideoPlayer#2473]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.0.4

![图片](https://user-images.githubusercontent.com/25575326/59893199-c231b000-940e-11e9-9421-a5f0af17a170.png)

想问一下 Jzvd.releaseAllVideos() 这个方法在哪里？

![图片](https://user-images.githubusercontent.com/25575326/59893378-56037c00-940f-11e9-8f5f-b90b22ff1f43.png)
 自己实现嘛

**Comment by lipangit** [comment]
resetAllVideos(), 这个函数，因为当时觉得release是释放的意思，reset是重置的意思，重置之后还能播放，释放之后无法播放。
