### ISSUE TITLE
如何代码创建一个饺子视频

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2476]
**需求描述 在Application 里初始化视频播放，添加在别的地方，实现整个应用只创建一个饺子视频对象，存入单利

**其他app是否实现 暂无

**截图或者小视频说明暂无

**Comment by lipangit** [comment]
饺子的JZVD本质上就是一个Layout，你可以添加到任何位置，setUp之后就可以播放，其他问题不用管，不需要初始化。

**Comment by hu374307261** [comment]
我需要封装一个单利播放器，实现唯一性，才能调用

**Comment by lipangit** [comment]
单例播放器是什么意思，你的需求是什么。

**Comment by hu374307261** [comment]
我的思路是，初始化一次播放器，放在单利里，一直就这一个播放器，需求是实现无缝切换，只需要添加移除饺子播放器的父类就可以

**Comment by lipangit** [comment]
参考进入全屏，进入全屏的本质就是布局的移动。 就是直接移动layout，remove layout， addview到其他layout。

**Comment by hu374307261** [comment]
添加到布局当中之后，点击横竖屏无效，视频暂停状态

**Comment by lipangit** [comment]
横竖屏是哪个按钮？

**Comment by hu374307261** [comment]
放大全屏， 小屏，我怎么才不依靠上下文横竖屏切换呢？

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/59973148-ade7e180-95cd-11e9-85bb-e2ca2547e4cd.png)

重点在这里

**Comment by hu374307261** [comment]
感谢群主，我终于开悟了，呜呜···

**Comment by lipangit** [comment]
看好你哦
