### ISSUE TITLE
请问这个框架是否支持.flv格式的视频播放

### ISSUE THREAD

**Issue by ygzm-lxh** [lipangit/JiaoZiVideoPlayer#2482]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
支持什么视频格式取决于使用什么播放器内核，咱们可以一行代码切换播放内核，常见的播放内核有android.media.MediaPlayer，ijkplayer，exoplayer，正在研究阿里的内核集成。

参考demo的orientationActivity切换播放内核
