### ISSUE TITLE
小米9录制的4k视频通过SiliCompressor这个压缩库压缩后播放不了

### ISSUE THREAD

**Issue by xiong5201314** [lipangit/JiaoZiVideoPlayer#2484]
**什么jzvd版本
JZVD的demo
**是否和安卓版本有关系，什么版本
应该和版本没关系，我小米6压缩后上传的视频可以播放
**是否和特定品牌的手机机型有关系，什么机型
小米9
**相关log是什么
好像没有log，压缩后的视频播放画面定格在第一帧，有声音，视频时长好像确定不了
**复现流程

**最好有截图或者视频说明情况
###

**Comment by lipangit** [comment]
能否播放取决于播放器内核，要么一行代码切换播放器内核，要么让你的视频适应播放器内核

**Comment by xiong5201314** [comment]
非常感谢！

**Comment by lipangit** [comment]
怎么解决的

**Comment by xiong5201314** [comment]
换成exo的播放器内核就好了，ijk和默认的都放不了。

**Comment by lipangit** [comment]
好的

**Comment by shuimuren** [comment]
http://player.youku.com/embed/XMzc4MjAzMTc4OA==  该连接为优酷的在线视频，无扩展名，无法播放

**Comment by XD-Z** [comment]
> 换成exo的播放器内核就好了，ijk和默认的都放不了。

怎么换播放器内核呢？麻烦指导下，谢谢

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/75276163-9b9b0300-5840-11ea-9a7e-c30d8753d027.png)
