### ISSUE TITLE
releaseAllVideos怎么没了呢？

### ISSUE THREAD

**Issue by 645148995** [lipangit/JiaoZiVideoPlayer#2486]
releaseAllVideos这个方法找不到了

**Comment by starrysky0** [comment]
Jzvd.releaseAllVideos();
Jzvd源码有这个方法的可以找的看下
  public static void releaseAllVideos() {
        Log.d(TAG, "releaseAllVideos");
        if (CURRENT_JZVD != null) {
            CURRENT_JZVD.reset();
            CURRENT_JZVD = null;
        }
    }

**Comment by lipangit** [comment]
resetAllVideos
