### ISSUE TITLE
视频文字有锯齿

### ISSUE THREAD

**Issue by Leezy01** [lipangit/JiaoZiVideoPlayer#2488]
同一个文件，用系统自带的视频播放器很丝滑，用这个播放器播放时文字有明显的锯齿。请问要怎么优化？

**Comment by starrysky0** [comment]
切换播放内核试试

**Comment by Leezy01** [comment]
三个引擎我都切换试过，效果一样

**Comment by lipangit** [comment]
能截图一下，丝滑是什么样  锯齿是什么样，我现在没有这个概念。

**Comment by Leezy01** [comment]
第一张是有锯齿的，第二张是没有锯齿的
![bad](https://user-images.githubusercontent.com/23165125/60331963-5c25c980-99c8-11e9-912a-fc8c38a4252a.png)
![good](https://user-images.githubusercontent.com/23165125/60331970-5e882380-99c8-11e9-8fbb-a3f4e3d2f5d3.png)

**Comment by lipangit** [comment]
这个。。 把url发给我试试吧

**Comment by Leezy01** [comment]
已经确定是渲染的问题，用SurfaceView显示正常

**Comment by lipangit** [comment]
surfaceview 在列表中有弊端， 根据自己的情况使用吧
