### ISSUE TITLE
onStatePreparing 方法停止不播放了，EXO播放器

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2490]
**什么jzvd版本 
7.0.4
**是否和安卓版本有关系，什么版本
无关
**是否和特定品牌的手机机型有关系，什么机型
无关、小米note
**相关log是什么
log显示未走 onStatePlaying 只走了，onStatePreparing 方法停止不播放了，EXO播放器
**复现流程
多次点击 当前视频初始化播放
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
demo有这个问题吗

**Comment by lipangit** [comment]
你做了哪些自定义了吗

**Comment by hu374307261** [comment]
倍数播放的那个demo，在列表实现播放，我这边监听，从发送url到onStatePreparing就停止了，不知道是不是列表组件的问题？

**Comment by hu374307261** [comment]
addview添加到别的地方，播放又可以继续走了，不知道群主对recyclerview研究过没，或者onStatePreparing 到 onStatePlaying 这中间怎么走的？

**Comment by lipangit** [comment]
我知道，前天在微信群解决了一个类似的问题。你用的哪个版本的jzvd，然后去用对应版本的jzMediaExo。

**Comment by hu374307261** [comment]
7.0.4

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/blob/v7.0.4/app/src/main/java/cn/jzvd/demo/CustomMedia/JZMediaExo.java

用这个
