### ISSUE TITLE
自动重播有一秒钟的加载时间卡顿显示了预览图

### ISSUE THREAD

**Issue by qinxianyuzou** [lipangit/JiaoZiVideoPlayer#2493]
**需求描述
按照文档在onAutoCompletion中调用startVideo方法实现自动重播，总是会有一秒左右的加载时间，然后闪一下预览图，有没有办法做到不显示预览图？我已经在onAutoCompletion方法里设置了thumbImageView隐藏，但是貌似没有效果。用的7.0.4

**其他app是否实现
参考朋友圈小视频自动重播

**Comment by lipangit** [comment]
类似下一集的功能吧

**Comment by qinxianyuzou** [comment]
> 类似下一集的功能吧

类似，不过就是播同一个视频，用startVideo这个方法来重播一定会卡顿一秒左右，即使是本地视频也会，后来我用了jzDataSource的looping属性来实现就没有这个问题。

**Comment by qinxianyuzou** [comment]
> 类似下一集的功能吧

您可以看看朋友圈的小视频，朋友圈的小视频就是自动重播的

**Comment by lipangit** [comment]
是的，相同视频自动重播就用looping
