### ISSUE TITLE
使用ijk内核播放rtmp推流， 第一次不能播放，是黑屏状态，但是可以看到视频时长，也可以拖动进度条。在播放窗口点击暂定后再点击播放就可以播放了。

### ISSUE THREAD

**Issue by orangevideoP** [lipangit/JiaoZiVideoPlayer#2495]
版本号：7.0.4

安卓8.0，安卓5.0

三星s8，oppoR17

**相关log是什么

使用ijk内核播放rtmp推流，
第一次不能播放，是黑屏状态，但是可以看到视频时长，也可以拖动进度条。在播放窗口点击暂定后再点击播放就可以播放了。
JiaoZiVideoPlayer的Demo不存在这个问题。但是我把demo里的依赖条件从本地的库更改成
    implementation 'cn.jzvd:jiaozivideoplayer:7.0.4'以后，就也会出现这个问题。

**Comment by LiuJiangc** [comment]
jzvdStd.setUp("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
                , "饺子快长大", JzvdStd.SCREEN_NORMAL, JZMediaIjk.class);   同黑屏，同问题

**Comment by lipangit** [comment]
你们用的哪个版本，去找对应版本的JzMediaIjk

**Comment by nanguaSky** [comment]
对照了JZMediaSystem 与 JZMediaIjk的代码发现
JZMediaSystem 中的 onPrepared 方法中有调用mediaPlayer.start();
而在JZMediaIjk 中 没有start操作, 只需要再 onPrepared 中调用 ijkPlayer的 start方法就好了

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/61021156-dd228f00-a3d2-11e9-982c-88482443b3df.png)

这里有对应版本的jzMediaIjk
