### ISSUE TITLE
ios拍摄的视频在三星手机上播放不了

### ISSUE THREAD

**Issue by llqidian** [lipangit/JiaoZiVideoPlayer#2497]
**什么jzvd版本
6.2.10
**是否和安卓版本有关系，什么版本
三台三星手机都不能播放
**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么
MediaPlayerNative: error (1, -2147483648)
MediaPlayer: Error (1,-2147483648)
JiaoZiVideoPlayer: onError 1 - -2147483648 [70423517] 
**复现流程
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
要么视频适应播放内核，要么换播放内核。
