### ISSUE TITLE
高度如何根据视频的比例进行自适应

### ISSUE THREAD

**Issue by xyj155** [lipangit/JiaoZiVideoPlayer#2500]
播放器在recycleview中实现列表播放，然后视频内容有横屏和竖屏的，但是高度写死以后，出现横屏的时候有黑边，竖屏的话是可以看的，有什么办法可以实现这个高度自适应，让横屏的黑边去掉。这个解决办法不能是吧背景颜色改成透明，因为那样子高度还是真实存在的

**Comment by lipangit** [comment]
在没播放的时候，jzvd的高宽本质上就是layout的高宽，可以随时修改。

在开始播放之后，继承jzvdStd，复写onVideoSize函数，取得当前视频的高宽，修改

**Comment by yixiu30** [comment]
public class JzVideo extends JzvdStd {

    public JzVideo (Context context) {

        super(context);

    }

    public JzVideo (Context context, AttributeSet attrs) {

        super(context, attrs);

    }

    @Override

    public void onVideoSizeChanged() {

//        super.onVideoSizeChanged();

        if (JZMediaManager.textureView !=null) {

            JZMediaManager.textureView.setVideoSize(textureViewContainer.getWidth(),textureViewContainer.getHeight());//视频大小与控件大小一致

        }
    }

}
楼主说的就像这样的

**Comment by lipangit** [comment]
完全正确！

**Comment by xyj155** [comment]
可是那布局里面的宽高咋设置，是写死吗。可是我按照上面的写法，还是会出现黑边

**Comment by lipangit** [comment]
这是拉伸图像让图像的高宽适配textureView的高宽。你的需求是移动图像，我不知道能不能移动

**Comment by xyj155** [comment]
还有一个就是我用glide加载视频第一帧，然后我设置圆角了以后就滑动有时候显示不全

**Comment by lipangit** [comment]
截图看一眼症状
