### ISSUE TITLE
RecyclerView中无法全屏播放

### ISSUE THREAD

**Issue by Eason-Zcx** [lipangit/JiaoZiVideoPlayer#2503]
**什么jzvd版本  ：7.0.4

**是否和安卓版本有关系，什么版本：无关

**是否和特定品牌的手机机型有关系，什么机型 ：无关

**相关log是什么

**复现流程 ：fragment中RecyclerView里竖屏情况下点击全屏按钮会使屏幕横屏,而不是视频全屏，在横屏情况下视频就会全屏

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
截图看看，你的点击全屏按钮之后什么样

**Comment by Eason-Zcx** [comment]
RecyclerView中播放
![46E07F8D444008F52635A6E261402F46](https://user-images.githubusercontent.com/17636795/60692462-b531b800-9f08-11e9-9ca4-f969785d3dca.png)
点全屏之后
![7E93AC1D5D77D266355F326441EE0F82](https://user-images.githubusercontent.com/17636795/60692464-b7941200-9f08-11e9-9ba8-add9a95a444c.png)

**Comment by Eason-Zcx** [comment]
已经解决了 是activity里面没有设置configChanges

**Comment by lipangit** [comment]
ok
