### ISSUE TITLE
当视频在加载中，切换页面，后台仍会播放

### ISSUE THREAD

**Issue by CCCCauchy** [lipangit/JiaoZiVideoPlayer#2504]
建议JzvdStd.goOnPlayOnPause()方法加上对Jzvd.STATE_PREPARING状态的判断

**Comment by starrysky0** [comment]
onPause时候可以加个销毁的方法

**Comment by lipangit** [comment]
@CCCCauchy  正确。 如果着急的话可以自己加上去，这是一个全局方法。

**Comment by easyandroid** [comment]
视频加载中 点击home键 调用JzvdStd.goOnPlayOnPause(); 无法暂停 后台播放了音频。

**Comment by lipangit** [comment]
demo是否有这个问题&nbsp; 试试



---原始邮件---
发件人: "easyandroid"<notifications@github.com&gt;
发送时间: 2020年6月8日(周一) 中午11:16
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 当视频在加载中，切换页面，后台仍会播放 (#2504)




 
视频加载中 点击home键 调用JzvdStd.goOnPlayOnPause(); 无法暂停 后台播放了音频。
