### ISSUE TITLE
全屏播放按返回键退出全屏的判断

### ISSUE THREAD

**Issue by nanguaSky** [lipangit/JiaoZiVideoPlayer#2505]
**什么jzvd版本
7.0.4
**是否和安卓版本有关系，什么版本
无
**是否和特定品牌的手机机型有关系，什么机型
无
**相关log是什么

**复现流程
进入视频详情页面，播放视频全屏模式，按返回键，直接推出了视频详情页面而不是先退出全屏视频播放页面  
override fun onBackPressed() {
        if(Jzvd.backPress()){
            return
        }
        super.onBackPressed()
    }
 这个方法有问题

**最好有截图或者视频说明情况

![image](https://user-images.githubusercontent.com/13417704/60753826-f1e5d800-a00a-11e9-9410-aebfbff4b11d.png)

**Comment by lipangit** [comment]
直接进入全屏模式，参考demo的directPlay Activity。
