### ISSUE TITLE
清晰度切换页面卡住

### ISSUE THREAD

**Issue by hu374307261** [lipangit/JiaoZiVideoPlayer#2507]
**什么jzvd版本
7.0.4
**是否和安卓版本有关系，什么版本
无关
**是否和特定品牌的手机机型有关系，什么机型
小米note
**相关log是什么
无
**复现流程
清晰度切换页面卡住当前帧，重新播放、未显示当前画面、有声音
**最好有截图或者视频说明情况

**Comment by yanchengdeng** [comment]
遇到同样问题，7.0.5 版本 必现

**Comment by yanchengdeng** [comment]
> **什么jzvd版本
> 7.0.4
> **是否和安卓版本有关系，什么版本
> 无关
> **是否和特定品牌的手机机型有关系，什么机型
> 小米note
> **相关log是什么
> 无
> **复现流程
> 清晰度切换页面卡住当前帧，重新播放、未显示当前画面、有声音
> **最好有截图或者视频说明情况

这个你是如何解决的，目前git 拉取的项目运行依然出现  切换视频卡住页面的现象

**Comment by yanchengdeng** [comment]
亲测可以
  public void changeUrl(int urlMapIndex, long seekToInAdvance) {
        state = STATE_PREPARING_CHANGING_URL;
        this.seekToInAdvance = seekToInAdvance;
        jzDataSource.currentUrlIndex = urlMapIndex;
//        mediaInterface.setSurface(null);
//        mediaInterface.release();
//        mediaInterface.prepare();
        //TODO 简单粗暴解决视频切换问题  卡顿
        startVideo();
    }

**Comment by lipangit** [comment]
@yanchengdeng 没毛病，兄弟  加我微信给你3000Jzt  https://github.com/Jzvd/JZT

**Comment by lipangit** [comment]
请你务必要加我微信

**Comment by lipangit** [comment]
有点小问题  startVideo之后 state是STATE_PREPARING不是STATE_PREPARING_CHANGING_URL
