### ISSUE TITLE
使用直接全屏播放api 的方法，第二次调用无法播放视频

### ISSUE THREAD

**Issue by nanguaSky** [lipangit/JiaoZiVideoPlayer#2508]
**什么jzvd版本
7.0.4版本

7.0.4的demo中也有此问题

**Comment by lipangit** [comment]
demo怎么复现这个问题

**Comment by nanguaSky** [comment]
点击direct play  点击  fullscreen  返回再点击 fullscreen

**Comment by huangzhuhua666** [comment]
同样发现这个问题

**Comment by zhouxiaocong** [comment]
同全屏引发的问题，QQ群7月8号聊天录了视频操作，可以看下

**Comment by lipangit** [comment]
是的，亲测有问题

**Comment by nanguaSky** [comment]
使用 startFullscreenDirectly 进入全屏的时候，退出时使调用了  clearFloatScreen，但是 JZMediaInterface.SAVED_SURFACE 没有被置空， 所以第二次使用这个方法再次进入全屏就无法放视频, 在  JZMediaInterface 的子类的 release方法中 加入   
JZMediaInterface.SAVED_SURFACE = null; 
就好了

**Comment by lipangit** [comment]
我觉得你的建议是非常完美的，已经修复这个问题
