### ISSUE TITLE
如何实现全屏填充模式下视图往上一点偏移

### ISSUE THREAD

**Issue by xaEHu** [lipangit/JiaoZiVideoPlayer#2514]
**需求描述
很多电影全屏并且选择填充的话，下方的字幕会被裁切掉一部分，而视频顶部却留了一条黑条，如何让其往上偏移一点，就是占满顶部的黑条，这样字幕也就能看得到了
**其他app是否实现
否
**截图或者小视频说明
![1562731112(1)](https://user-images.githubusercontent.com/46973471/60939417-2b1f9000-a30a-11e9-9a14-fda2a97410a4.jpg)

**Comment by lipangit** [comment]
参考demo的videoSizeActivity， 能拉伸压缩适配屏幕尺寸。

但是我不知道怎么移动图像。。兄弟你可以研究一下分享出来

**Comment by xaEHu** [comment]
> 参考demo的videoSizeActivity， 能拉伸压缩适配屏幕尺寸。
> 
> 但是我不知道怎么移动图像。。兄弟你可以研究一下分享出来

我重写了addTexturView方法，把layoutParams原本Center的Gravity改为Bottom，下方字幕就可以完全显示，不过上方裁切了黑条的高度取决于屏幕和视频源，有可能会裁切掉顶部一点，也有可能很完美的只裁切掉了黑条。感觉可以针对这个对齐方式给用户做微调。

![Screenshot_2019-07-11-18-39-08-212_com xaehu livehd](https://user-images.githubusercontent.com/46973471/61045607-c3eb0400-a40d-11e9-91d6-463273e34b32.png)

**Comment by lipangit** [comment]
其他比例的视频还要根据视频的高度单独设置

**Comment by xaEHu** [comment]
已研究出解决方案，可通过textureView.setTranslationY(float y)来调节这个全屏视图视频内容位置

**Comment by xaEHu** [comment]
> 其他比例的视频还要根据视频的高度单独设置

textureView.setTranslationY(float y)可实现全屏视频内容上下偏移调节，完美解决

**Comment by lipangit** [comment]
good

**Comment by xaEHu** [comment]
我自定义重写onTouch方法想要上下滑动调节声音的这个操作替换成调节这个视图的偏移，有这几个判断：v.getId() == R.id.surface_container&& event.getAction() == MotionEvent.ACTION_MOVE&& mChangeVolume，里面做调节，完了return true。但是实际调节就会出现第一下会有音量的变化，然后move才是预料中的效果。是什么原因导致还是会调节到音量的呢

**Comment by lipangit** [comment]
把这段删除，声音肯定b不会再有变化。
![image](https://user-images.githubusercontent.com/2038071/62143257-45092d00-b322-11e9-8f19-7827d13c40a5.png)
