### ISSUE TITLE
某些视频链接无法打开

### ISSUE THREAD

**Issue by liuninglxn** [lipangit/JiaoZiVideoPlayer#2515]
**需求描述
某些视频链接无法打开
**其他app是否实现
ExoPlayer可以打开（本项目的demo不行）
**截图或者小视频说明
![image](https://user-images.githubusercontent.com/25262415/61031279-c6d7fb80-a3f1-11e9-9cd8-c303c5077744.png)
![image](https://user-images.githubusercontent.com/25262415/61031286-cb041900-a3f1-11e9-861b-24f0cc407b77.png)

**Comment by lipangit** [comment]
一行代码切换到jzMediaExo内核

**Comment by liuninglxn** [comment]
试过，
jzvdStd.setUp("https://courseware.uuabc.com/courseware_centent_1561864858147"
                , "This is a title", JzvdStd.SCREEN_NORMAL, JZMediaExo.class);
不行

**Comment by liuninglxn** [comment]
@lipangit 
试过，
jzvdStd.setUp("https://courseware.uuabc.com/courseware_centent_1561864858147"
, "This is a title", JzvdStd.SCREEN_NORMAL, JZMediaExo.class);
不行，还是不能播放

**Comment by lipangit** [comment]
检查一下和能播的exoplayer使用的exoplayer版本是否一致，配置是否一样。

咱们项目不涉及编码解码，哪个播放内核能播，咱们就用哪个播放内核
