### ISSUE TITLE
Direct video play fullscreen only works one time

### ISSUE THREAD

**Issue by HazimSharif** [lipangit/JiaoZiVideoPlayer#2516]
Hello, 

I have integrated your library withing my project, and followed instructions, But i have a problem,
When i play video directly in full screen,  video works fine, then if i go back and try to play video again in full screen it just keeps loading, 

I also tried your demo apk, it has same problem.

to reproduce issue :
1- Open demo apk
2- Click DIRECT PLAY
3- Click FULLSCREEN
4- Video will start fine
5- Go back 
6- Click FULLSCREEN again
result : video will keep loading and will not start.

I appreciate your support to provide solution.

Thanks,

**Comment by lipangit** [comment]
yes it is bug

**Comment by nanguaSky** [comment]
add  
JZMediaInterface.SAVED_SURFACE = null;
to release  methon on JZMediaInterface subclass

**Comment by lipangit** [comment]
https://github.com/lipangit/JiaoZiVideoPlayer/issues/2508

fix
