### ISSUE TITLE
Exception from call site #16 bootstrap method

### ISSUE THREAD

**Issue by microragu** [lipangit/JiaoZiVideoPlayer#2519]
java.lang.BootstrapMethodError: Exception from call site #16 bootstrap method
        at cn.jzvd.JzvdStd.showWifiDialog(JzvdStd.java:338)

**Comment by luxutao** [comment]
我找到的解决方法是在build.gradle里添加下面这个
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by lipangit** [comment]
good
