### ISSUE TITLE
暂停播放的时候，没有释放音频焦点，导致其他app因为获取不到音频焦点无法播放

### ISSUE THREAD

**Issue by liming11** [lipangit/JiaoZiVideoPlayer#2521]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
今日头条的视频中暂停也不会释放音频焦点，去触发播放其他app里已经暂停的音乐。

如果你需要可以继承jzvdStd，复写onSTatePause函数，释放焦点
