### ISSUE TITLE
请问如何自动解析视频格式

### ISSUE THREAD

**Issue by gycold** [lipangit/JiaoZiVideoPlayer#2522]
后台返回的视频地址经过加密的，没有直接给出格式，在使用饺子播放的时候直接提示播放失败，但是使用其他网页播放器可以自动解析并播放，请问饺子提供的有这样的功能吗？

**Comment by lipangit** [comment]
取决于播放内核是否能播放，可以切换的内核有android.media.MediaPlayer、ijkplayer、exoplayer。饺子不管视频的加密解密编码解码，饺子负责ui负责操作播放内核。
