### ISSUE TITLE
播放本地视频，播不了

### ISSUE THREAD

**Issue by honeylife** [lipangit/JiaoZiVideoPlayer#2527]
**什么jzvd版本
7.0.5
**是否和安卓版本有关系，什么版本
 没有关系
**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程
demo里面的也播放不
**最好有截图或者视频说明情况

        JZDataSource jzDataSource = null;
        try {
            jzDataSource = new JZDataSource(getAssets().openFd("local_video.mp4"));
            jzDataSource.title = "饺子快长大";
        } catch (IOException e) {
            e.printStackTrace();
        }
        jzvdStd.setUp(jzDataSource, JzvdStd.SCREEN_NORMAL, JZMediaSystemAssertFolder.class);

//        jzvdStd.setUp("http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
//                , "饺子快长大", JzvdStd.SCREEN_NORMAL, new JZMediaIjk(jzvdStd));

        Glide.with(this)
                .load("http://jzvd-pic.nathen.cn/jzvd-pic/1bb2ebbe-140d-4e2e-abd2-9e7e564f71ac.png")
                .into(jzvdStd.thumbImageView);

这些代码写了，就是这样写的，播放不了。我要播放Assets下面的资源。

**Comment by Freedomhxb** [comment]
我也是本地不行，网络上可以

**Comment by Freedomhxb** [comment]
implementation 'cn.jzvd:jiaozivideoplayer:7.0.4' 换成这个就好了

**Comment by lipangit** [comment]
ok
