### ISSUE TITLE
 播几分钟后都会显示视频加载失败

### ISSUE THREAD

**Issue by AndroidKun** [lipangit/JiaoZiVideoPlayer#2529]
请问使用饺子视频播放器播放视频 播几分钟后都会显示视频加载失败 是怎么回事呢 日志输出是 onError 1 - -1004 [216283790]

**Comment by lhj1079947827** [comment]
对我的也是会出现这个问题，一开始以为是网络问题，但是这个问题网络很好也会出现，播放几分钟就显示视频加载失败，点击重新播放一直在那里转圈圈不会重新播放，除非退出当前界面重新进来才能正常播放。

**Comment by lipangit** [comment]
可能是因为服务器没设置断点续传功能，在服务器端配置，尽量使用阿里云七牛等现成的视频点播服务。

也可以在手机端配置，如果视频体积不大可以设置header，让服务器一口气把所有视频都传给你。
header.put("Content-Type","video/mp4");
header.put("Accept-Ranges","bytes");
header.put("Status","206");
header.put("Cache-control","no-cache");

**Comment by lipangit** [comment]
试一下，是否管用

**Comment by AndroidKun** [comment]
视频就是储存在阿里云上的

**Comment by AndroidKun** [comment]
看了一下是刚开始播放的时候会缓冲一小段视频，缓冲部分播放完后显示视频加载失败了，没有再缓冲加载后面的视频

**Comment by lipangit** [comment]
这个链接的代码管用吗？试过吗

**Comment by AndroidKun** [comment]
管用的 iOS上正常

**Comment by lipangit** [comment]
ok

**Comment by selfcreator** [comment]
@lipangit 请问这个header是哪里的？是`JZDataSource`的`headerMap`吗？还是哪个http request的header?

**Comment by lipangit** [comment]
是JZDataSource的headerMap
