### ISSUE TITLE
使用ExoPlayer内核，seekToInAdvance失效

### ISSUE THREAD

**Issue by zwping** [lipangit/JiaoZiVideoPlayer#2530]
#### 复现代码如图
![image](https://user-images.githubusercontent.com/26704739/61357345-a7861600-a8aa-11e9-8766-12e4b08b5a47.png)

**Comment by ToxicR** [comment]
我遇到了同样的问题，请问您解决了没

**Comment by lipangit** [comment]
解决了吧
