### ISSUE TITLE
关于播放本地视频的url格式

### ISSUE THREAD

**Issue by xaEHu** [lipangit/JiaoZiVideoPlayer#2531]
**需求描述
播放本地内存卡里的视频时，setUp参数的url是/storage/emulated/0/DCIM/xxx.mp4的格式吗？为何我的一直在转圈圈播放不了？

我看入门教程里说描述的播放本地视频的路径是以Environment.getExternalStorageDirectory().getAbsolutePath()开头，我输出这个String它确实是/storage/emulated/0，可是我选择的文件真实路径却不行，网络视频能播放，本地视频就一直转圈圈，是我给的路径不对吗？

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
这个需要多尝试，多找资料，就是路径的问题，把正确的路径怼给播放内核就能播放。

**Comment by uzaysan** [comment]
uri.toString() works for me

**Comment by lipangit** [comment]
@uzaysan good

**Comment by xaEHu** [comment]
我用uri.toString()也是在转圈圈……

**Comment by lipangit** [comment]
第一步，确保使用的播放器内核和播放器版本是对应的

第二步，确保传入正确的路径

**Comment by xaEHu** [comment]
我setUp的路径就直接填："/storage/emulated/0/DCIM/test.mp4"
点击播放有logcat这个提示：W/System.err: Caused by: java.io.FileNotFoundException: /storage/emulated/0/DCIM/test.mp4 (Permission denied)。
但是我输出new File("/storage/emulated/0/DCIM/test.mp4").exists()是true，文件是在的，播放器却找不到，所以我就很纠结这个路径是不是有规定类似于file://开头或者其他什么吗？
播放器内核用默认的和ijk的都试过了，播放器版本是7.0.4。

**Comment by xaEHu** [comment]
解决了……存储权限没开启的问题……我的天

**Comment by lipangit** [comment]
ok  加油老铁
