### ISSUE TITLE
全屏播放的时候怎么通过重力感应切换横竖屏

### ISSUE THREAD

**Issue by Eason-Zcx** [lipangit/JiaoZiVideoPlayer#2534]
**需求描述
现在只能横屏切换，竖屏的时候还是横屏播放状态
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
参考demo的orientationActivity

**Comment by Eason-Zcx** [comment]
参考demo中的orientationActivity没有效果
用demo跑也没有横竖屏切换
