### ISSUE TITLE
一个疑问，为什么包裹player的layout 高度设置成wrap_content 全屏播放返回就无法退出到原来的页面

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2535]
比如这样：
<LinearLayout
        android:id="@+id/jz_player_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent">

        <cn.jzvd.JzvdStd
            android:id="@+id/jz_player"
            android:layout_width="match_parent"
            android:layout_height="300dp" />

    </LinearLayout>
全屏播放无法退出全屏界面 只是在全屏界面里面将视频横竖切换了。设置成固定高度就正常了，这个坑 还研究了半天才解决。
![906f89ab93e936a791099723bbfac22](https://user-images.githubusercontent.com/5047329/61611661-f3f89980-ac8e-11e9-8866-71e803f264b0.jpg)

难道是 用了 ConstraintLayout的锅？

**Comment by lipangit** [comment]
解决了就好，需要在jzvd外面包一层layout
