### ISSUE TITLE
切换ijk播放内核，播放视屏一直处于刷新状态

### ISSUE THREAD

**Issue by hjt110** [lipangit/JiaoZiVideoPlayer#2536]
**什么jzvd版本
7.0.4和7.0.5
**复现流程
依赖v7.0.5版本，切换ijk内核，播放视屏（第一次会成功），然后退出这个视频的界面重新进入（没有退出App），重新播放视屏，发现视频一直处于那个刷新状态
**最好有截图或者视频说明情况
![8S(5HB~1S`A@QKIZFS77D{2](https://user-images.githubusercontent.com/23635529/61617291-fa8e0d80-ac9c-11e9-8c39-e7fe3e965e98.png)

以下是我发现的问题所在不知道对不对：
![CB 2LM~F9~F_$%__GD 7CMG](https://user-images.githubusercontent.com/23635529/61617116-a3883880-ac9c-11e9-97f4-bc816f9ad25a.png)
好像是因为JZMediaInterface.SAVED_SURFACE 没被设置为null导致无法触发TextureView.SurfaceTextureListener中的onSurfaceTextureAvailable（）的方法，所以在reset（）或JZMediaIjk.release()里添加JZMediaInterface.SAVED_SURFACE = null就可以了

**Comment by DaLeiGe** [comment]
我的也是，Google的内核也是，第一次能打开，第二次就一直在加载状态

**Comment by hjt110** [comment]
> 我的也是，Google的内核也是，第一次能打开，第二次就一直在加载状态

可以试下我上面的解决方法

**Comment by lipangit** [comment]
已经在最新develop里提交

**Comment by fengchuiyeluo** [comment]
感谢，以为是我项目代码的问题，排查了好久
