### ISSUE TITLE
使用exo内核 第一次视频播放正常 没有问题，但是第二次就完全不能播放

### ISSUE THREAD

**Issue by truesA** [lipangit/JiaoZiVideoPlayer#2537]
**什么jzvd版本
7,05
[**是否和安卓版本有关系，什么版本]()
8.0
**是否和特定品牌的手机机型有关系，什么机型
小米MIX2
**相关log是什么
没有log  正常的button star 第二次播放一直是加载中 
**复现流程
使用exo内核 第一次视频播放正常 没有问题，但是第二次就完全不能播放了，选择其他视频也是一样，使用默认的内核 没有问题，但是加载远没有exo快。
布局构成 viewpage+fragment  fragment + recyclerview  recycler + typeViewHolder 
**最好有截图或者视频说明情况

**Comment by hjt110** [comment]
![](http://www.1990tu.com/i/20190723095200tz7.png)
试下重写reset（）方法

**Comment by truesA** [comment]
@hjt110 可以了 谢谢大佬

**Comment by lipangit** [comment]
感谢你的分享

**Comment by pengbs** [comment]
@truesA 怎么解决的大兄弟？
