### ISSUE TITLE
关于exo引擎内存泄漏的解决办法

### ISSUE THREAD

**Issue by superzhangbao** [lipangit/JiaoZiVideoPlayer#2539]
**需求描述
使用exo引擎是发现存在内存泄漏情况，后发现JZExoPlayer类中使用的Context是JzvdMgr.getCurrentJzvd().getContext()，将此处改为applicationContext则无内存泄漏情况了
**其他app是否实现

[**截图或者小视频说明]
![image](https://user-images.githubusercontent.com/24392045/61783233-0400ac80-ae3a-11e9-8421-d4d5474e06f0.png)

**Comment by superzhangbao** [comment]
若有其他地方的泄漏，希望大家可以一起发现一起解决

**Comment by lipangit** [comment]
感谢你的分享
