### ISSUE TITLE
小视频正常播放，大视频加载不出来

### ISSUE THREAD

**Issue by lucky-you** [lipangit/JiaoZiVideoPlayer#2548]
**需求描述
集成最新版的播放器，小视频（13.3M）的可以正常加载，正常播放，但是大视频（>200M）就加载不出来，也播放不了。
**其他app是否实现

**截图或者小视频说明
小视频链接：https://flv2.bn.netease.com/videolib1/1811/26/OqJAZ893T/HD/OqJAZ893T-mobile.mp4
大视频链接：https://v8.yongjiu8.com/share/AtoOPxllbwrdhaP0

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/62141925-f8245700-b31f-11e9-9369-00ed6d96dc81.png)


大视频地址应该指向一个视频文件，这些内容MediaPlayer无法解析
