### ISSUE TITLE
试看1分钟如何实现

### ISSUE THREAD

**Issue by shuaimango** [lipangit/JiaoZiVideoPlayer#2559]
普通用户只能试看前1分钟的视频片段，怎么实现呢

**Comment by shuaimango** [comment]
![image](https://user-images.githubusercontent.com/7135788/62818470-2ef93900-bb7a-11e9-8ec7-879c4ba3fc15.png)

**Comment by lipangit** [comment]
对，在onProgress中取得用户的播放进度
