### ISSUE TITLE
极少部分机型出现水平方向为充满的情况

### ISSUE THREAD

**Issue by prookiee** [lipangit/JiaoZiVideoPlayer#2562]
**7.0.2

**部分安卓手机 目前华为 p10pro只有一台出现这个问题，但是模拟器基本上都会出现

出现问题的截图
![1565319505(1)](https://user-images.githubusercontent.com/20673827/62750992-a2287f80-ba94-11e9-8baf-bfe232f6aa89.jpg)

正常情况的截图
![image](https://user-images.githubusercontent.com/20673827/62751026-ca17e300-ba94-11e9-9a42-d7c4e3253baa.png)

正常情况下视频水平方向是充满屏幕的

**Comment by windfone** [comment]
你这个是从全屏状态再切换回来变成这样的吗

**Comment by prookiee** [comment]
不是的，没有切换横屏，正常竖屏播放就是这个样子

**Comment by prookiee** [comment]
> 你这个是从全屏状态再切换回来变成这样的吗

不是的，没有切换横屏，正常竖屏播放就是这个样子

**Comment by lipangit** [comment]
复写onVideoSizeChanged函数，看返回的宽度是否是屏幕宽度

**Comment by prookiee** [comment]
> 复写onVideoSizeChanged函数，看返回的宽度是否是屏幕宽度

已解决，是给播放器设置的高度不够，导致适配按比例缩放时水平方向无法撑满。

**Comment by prookiee** [comment]
> 复写onVideoSizeChanged函数，看返回的宽度是否是屏幕宽度

已解决，是给播放器设置的高度不够，导致视频按比例缩放时水平方向无法撑满。
