### ISSUE TITLE
真机跑demo，视频可以播放，但移植到自己项目里却播放不了，一直加载

### ISSUE THREAD

**Issue by RobinHq** [lipangit/JiaoZiVideoPlayer#2563]
**什么jzvd版本
7.0.5
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
log什么样，需要更多信息

**Comment by lipangit** [comment]
log什么样，做了哪些修改，需要更多信息

**Comment by XD-Z** [comment]
看看是否AndroidManifest 设置了 android:hardwareAccelerated="false"属性

**Comment by lipangit** [comment]
是的，不能关闭硬件加速，否则textureView不工作，默认就好
