### ISSUE TITLE
本地.ts视频播放,不同机型,有的能播放,有的不能

### ISSUE THREAD

**Issue by Likemockingbird** [lipangit/JiaoZiVideoPlayer#2567]
下载到本地的.ts文件,华为和vivo都能播放,但是小米,三星,oppo不能播放,有大神能给个思路吗?

**Comment by lipangit** [comment]
取决于播放器内核，常见的播放器内核有android.media.MediaPlayer，exoplayer，ijkplayer

**Comment by lipangit** [comment]
可以一行代码切换播放器内核

**Comment by XD-Z** [comment]
> 可以一行代码切换播放器内核

怎么弄呢？
