### ISSUE TITLE
如何退出视频播放页面继续播放音频

### ISSUE THREAD

**Issue by ymwm-lxl** [lipangit/JiaoZiVideoPlayer#2572]
**需求描述
我想要实现用户在视频播放页面如果退出，则继续播放音频，如果回到视频播放页面，则恢复视频播放

**其他app是否实现
得到

**截图或者小视频说明

**Comment by lipangit** [comment]
demo中有apiActivity，里面用到了goOnPlayOnResume函数，是不是你需要的

**Comment by ymwm-lxl** [comment]
> 演示中有apiActivity，里面用到了goOnPlayOnResume函数，是不是你需要的

这并不是我想要的，我想要在离开页面时能够获取到 音乐部分的播放播放引擎，以使我能够在外部能够连续播放且控制播放信息，如果回到播放页面能够将我之前获取到的播放器对象再归还给 jz播放器

**Comment by lipangit** [comment]
JzvdMgr.getCurrentJzvd 可以取得当前正在播放的jzvd
