### ISSUE TITLE
播放几秒后就卡顿，一段时间后又正常播放

### ISSUE THREAD

**Issue by daisywangyy** [lipangit/JiaoZiVideoPlayer#2574]
版本  7.0.4

34M的视频，不同的手机，播放到一部分，有的十几秒，有的几秒就会卡顿住，卡顿一段时间，有的长有的短又继续播放，后面的就播放正常了。  每次都是。 

视频地址：https://1256871193.vod2.myqcloud.com/ec64abd4vodsh1256871193/185be5c25285890793083160111/f0.mp4

**Comment by daisywangyy** [comment]
已解决

**Comment by jiangmw** [comment]
请问怎么解决的？我也出现这样的问题

**Comment by kilitoasuna** [comment]
我也出现了这个问题，比较棘手，现在还没有解决，请问您是怎么处理的呢，谢谢啦！

**Comment by longkehuawei** [comment]
怎么解决的，我也想问下
