### ISSUE TITLE
视频从normal切换到fullscreen到时候，为什么要clone一个jzvd？

### ISSUE THREAD

**Issue by rick210** [lipangit/JiaoZiVideoPlayer#2575]
视频从normal切换到fullscreen到时候，为什么要clone一个jzvd？

**Comment by lipangit** [comment]
你说的是哪个版本，新版本不再新建jzvd，全屏和非全屏是相同的事例

**Comment by jp0533** [comment]
GitHub上最新的版本7.0.5  Jzvd.java 类第722行 cloneAJzvd(viewGroup) 方法，你看下@lipangit

**Comment by lipangit** [comment]
因为在列表中，要有jzvd占位。
