### ISSUE TITLE
全屏无效并锁定横屏

### ISSUE THREAD

**Issue by LLXBH** [lipangit/JiaoZiVideoPlayer#2580]
**什么jzvd版本
7.0.5

调用 startFullscreenDirectly 进行全屏播放；
在 debug 情况下正常使用；
在 release 情况下会将 app 横屏，而且并没有播放视频；
排除发现，关闭混淆就不会出现该状况，将 demo 的 ActivityDirectPlay 放置到项目中的情况一样，但在 demo 中却无法触发该状况，是哪里没设置好吗？关闭混淆就不会有事

**Comment by lipangit** [comment]
就是混淆的问题，兄弟，你的混淆怎么配置的

**Comment by LLXBH** [comment]
> 就是混淆的问题，兄弟，你的混淆怎么配置的

![image](https://user-images.githubusercontent.com/34165598/68275111-be44b880-00a5-11ea-879e-c0aa46141956.png)
这样的，好像是以前百度看到的混淆

**Comment by HeartNeverDie** [comment]
我也遇到了这个问题 第一次点击全屏变为了横屏 横屏情况下第二次点击才成功全屏

**Comment by lipangit** [comment]
demo有这问题吗，你改了哪些内容
