### ISSUE TITLE
Unable to create media player

### ISSUE THREAD

**Issue by eyalmnm** [lipangit/JiaoZiVideoPlayer#2590]
When trying to run the video player with the example URL, [your sample url](http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4) got the following exception 
`E/MediaPlayerNative: Unable to create media player
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:92
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
W/System.err: Caused by: java.io.IOException: setDataSource failed.: status=0x80000000
W/System.err:     at android.media.MediaPlayer.nativeSetDataSource(Native Method)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1255)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1238)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1218)
W/System.err: 	... 5 more`

**Comment by lipangit** [comment]
somthing wrong with the domain name

**Comment by lipangit** [comment]
waite please

**Comment by mojizx** [comment]
你解决了嘛

**Comment by lipangit** [comment]
没有思路



---Original---
