### ISSUE TITLE
RecyclerView 点击item ，视频全屏播放后，返回到列表。 videoView高度发生变化。

### ISSUE THREAD

**Issue by Yexingshuai** [lipangit/JiaoZiVideoPlayer#2595]
最新的jzvd版本，RecyclerView 多条目展示 video，videoView高度写死200，点击全屏，再回来列表后，高度发生变化。滑动出去 才能恢复正常

**Comment by PoetGcc** [comment]
看看是不是硬件加速没有开导致的

**Comment by PoetGcc** [comment]
@Yexingshuai 看看是不是硬件加速没有开导致的

**Comment by Yexingshuai** [comment]
开了硬件加速。还是不行

**Comment by SUHONGJIN** [comment]
videoView外面加个LinearLayout就可以了。

**Comment by yilylong** [comment]
我也遇到
