### ISSUE TITLE
将长方形视频裁成正方形播放

### ISSUE THREAD

**Issue by whatisjava** [lipangit/JiaoZiVideoPlayer#2596]
**需求描述
如何实现将长方形视频正方形显示，也就是类似于图片设置scaleTyle=centerCrop后的样子，只裁剪出居中部分的视频播放
**其他app是否实现

**截图或者小视频说明
<img width="396" alt="图片" src="https://user-images.githubusercontent.com/366992/65006401-8dfa5c80-d935-11e9-9050-c66d09051f14.png">

**Comment by whatisjava** [comment]
目前设置的weightRadio 和heightRadio为1
重写了onVideoSizeChanged宽高一致后可以变为正方形，但是是把长边压缩成跟短边一样的长度了，视频画面也被压缩了，我想有没有办法不压缩，把长边多余的部分截掉不显示，只显示跟短边一样长的部分就行

**Comment by lipangit** [comment]
参考demo的RotationAndVideoSizeActivity，有这个功能。

**Comment by whatisjava** [comment]
好的，多谢
