### ISSUE TITLE
点击重播 播放无效、按钮状态就跳到normal状态再点击才能播放？

### ISSUE THREAD

**Issue by yangxu1210** [lipangit/JiaoZiVideoPlayer#2604]
**测试发现 6.x 和最新版本 都存在该问题**，正常的播放完毕后 出现重播 点击重播不能正常播放 而是闪了一下按钮icon被重置成了normal状态，这时再点击才能正常播放视频，想请问一下大家有遇到这个问题嘛？ 有什么好的解决方案和建议吗？

**Comment by lipangit** [comment]
目前demo没这情况，你做什么修改了吗
