### ISSUE TITLE
横屏与竖幕都显示左上角的返回按钮，点击切换与关闭

### ISSUE THREAD

**Issue by lzjin** [lipangit/JiaoZiVideoPlayer#2605]
横屏与竖幕都显示，左上角的返回按钮，全屏点击切换到竖幕，如果是竖幕时点击就关闭页面。
重写onClick中  case R.id.back:这里怎么修改？ backPress()这个是静态方法

**Comment by lipangit** [comment]
你的需求是什么。竖屏没有这个按钮，它只在全屏才有。

**Comment by lzjin** [comment]
竖屏也显示返回按钮，不然返回页面只能按back键。目前我是帧布局在左上角加的返回按钮，位置在有些机型有差异，希望源码能直接增加这个功能。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nathen"<notifications@github.com&gt;; 
发送时间: 2020年2月26日(星期三) 凌晨2:57
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 
抄送: "*闪电#—***"<857800301@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 横屏与竖幕都显示左上角的返回按钮，点击切换与关闭 (#2605)




你的需求是什么。竖屏没有这个按钮，它只在全屏才有。

**Comment by lipangit** [comment]
我觉得可以在demo中添加一个activity，单独显示这个功能，&nbsp; 加我微信&nbsp; 给你1000jzt&nbsp;&nbsp;
https://github.com/Jzvd/JZT


---原始邮件---
发件人: "lzj"<notifications@github.com&gt;
发送时间: 2020年2月26日(周三) 上午9:36
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 横屏与竖幕都显示左上角的返回按钮，点击切换与关闭 (#2605)


竖屏也显示返回按钮，不然返回页面只能按back键。目前我是帧布局在左上角加的返回按钮，位置在有些机型有差异，希望源码能直接增加这个功能。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Nathen"<notifications@github.com&amp;gt;;  
 发送时间: 2020年2月26日(星期三) 凌晨2:57 
 收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;gt;;  
 抄送: "*闪电#—***"<857800301@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [lipangit/JiaoZiVideoPlayer] 横屏与竖幕都显示左上角的返回按钮，点击切换与关闭 (#2605) 
 
 
 
 
 你的需求是什么。竖屏没有这个按钮，它只在全屏才有。
