### ISSUE TITLE
eventBus传递jzvdStd保持全局，其他activity中获取实例，无法控制播放暂停，releaseAllVideos可以

### ISSUE THREAD

**Issue by beartistic** [lipangit/JiaoZiVideoPlayer#2607]
**需求描述
eventBus传递jzvdStd保持全局，其他activity中获取实例，无法控制播放暂停，releaseAllVideos可以
**其他app是否实现
未知
**截图或者小视频说明
https://www.seeyou.store//shot.jpg

**Comment by lipangit** [comment]
怎么传递的，currentJzvd能用吗
