### ISSUE TITLE
在列表想要快速起播，列表页只保持一个播放器实例，切换视频的时候只是替换Url

### ISSUE THREAD

**Issue by xuzhiyong017** [lipangit/JiaoZiVideoPlayer#2610]
**需求描述
在列表想要快速起播，列表页之保持一个播放器实例，切换视频的时候只是替换Url
**其他app是否实现
抖音，火山
**截图或者小视频说明
能快速起播

**Comment by lipangit** [comment]
滑动列表的时候自动播放屏幕中间的视频，是不是这个功能
