### ISSUE TITLE
预览画面显示gif  取出视频的一些帧 生成一个GIF  显示出来

### ISSUE THREAD

**Issue by wj576038874** [lipangit/JiaoZiVideoPlayer#2612]
**需求描述

**其他app是否实现
小红书的发现页实现了的

**截图或者小视频说明

**Comment by wj576038874** [comment]
> **需求描述
> 
> **其他app是否实现
小红书 实现了的
> 
> **截图或者小视频说明

**Comment by lipangit** [comment]
么么哒，生成gif能解决吗
