### ISSUE TITLE
直接进入新页面全屏播放，然后返回到上一页，再获取屏幕的宽高的时候，出现这个问题：高度=屏幕的实际宽度，宽度=屏幕的实际的高度，请问怎么解决这个问题？

### ISSUE THREAD

**Issue by WarriorYu** [lipangit/JiaoZiVideoPlayer#2613]
获取屏幕宽高代码：

     DisplayMetrics dm = activity.getResources().getDisplayMetrics();

        int screenWidth = dm.widthPixels;
        int screenHeight = dm.heightPixels;
       

播放器代码：  

    override fun initViews() {
        val url = intent.getStringExtra("url")
        val title = intent.getStringExtra("title")
        val configuration: VideoDecryptConfiguration = VideoDecryptConfiguration()
        configuration.context = mContext
        configuration.needCrypt = false
        JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
        JCVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
        JCMediaManager.instance().setConfiguration(configuration)
        videoPlayer.setUp(url, JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, title)
        videoPlayer.loop = false
        videoPlayer.backButton.visibility = INVISIBLE
        videoPlayer.fullscreenButton.visibility = INVISIBLE
        videoPlayer.startButton.performClick()
    }

    override fun onDestroy() {
        super.onDestroy()
        JCVideoPlayer.releaseAllVideos()
    }

    override fun onPause() {
        super.onPause()
        if (videoPlayer != null) {
            try {
                if (JCMediaManager.instance().mediaPlayer.isPlaying) {
                    JCMediaManager.instance().mediaPlayer.pause()
                    videoPlayer.setUiWitStateAndScreen(JCVideoPlayer.CURRENT_STATE_PAUSE)
                    videoPlayer.changeUiToPauseShow()
                }
            } catch (e: IllegalStateException) {
                e.printStackTrace()
            }

        }
    }

**Comment by lipangit** [comment]
换一下就完了
