### ISSUE TITLE
我在一个页面的banner里点击图片，使用 JzvdStd.startFullscreen直接全屏播放，当在全屏播放的时候返回到页面

### ISSUE THREAD

**Issue by WarriorYu** [lipangit/JiaoZiVideoPlayer#2614]
我在一个页面的banner里点击图片，使用 JzvdStd.startFullscreen直接全屏播放，当在全屏播放的时候点击返回，并且立马下拉刷新请求新数据，第一次请求接口，会报400，第二次刷新就正常，这个问题只在小米8上能复现，在其他手机没问题。截图里是日志，在好几部手机都会报这个bug，但是只在小米8会导致请求接口报400。不使用直接全屏播放就没有问题，请问这是什么原因导致的？

![image](https://user-images.githubusercontent.com/16720902/66633665-ee7f6f80-ec3d-11e9-9d7a-e9f2b5706435.png)

**Comment by lipangit** [comment]
怎么样了
