### ISSUE TITLE
播放视频时，网络提醒dialog字体颜色

### ISSUE THREAD

**Issue by zhanghui2015** [lipangit/JiaoZiVideoPlayer#2615]
**需求描述
能够看到取消和确认按钮的字体
**其他app是否实现

**截图或者小视频说明
![微信图片_20191011205823](https://user-images.githubusercontent.com/14065130/66653124-e3dacf80-ec69-11e9-9ebd-437305ab5c2e.jpg)

**Comment by lipangit** [comment]
复写showWifidialog函数，自定义dialog
