### ISSUE TITLE
didn't call SDL_JNI_DetachThreadEnv() explicity

### ISSUE THREAD

**Issue by wydewy** [lipangit/JiaoZiVideoPlayer#2618]
**什么jzvd版本
7.0.5
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型
华为荣耀
**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
什么log，可能不是饺子的log
