### ISSUE TITLE
想问下，为何在JZMediaSystem 中单独使用MediaHandlerThread?有必要吗

### ISSUE THREAD

**Issue by PoetGcc** [lipangit/JiaoZiVideoPlayer#2619]
** 7.0.3

在列表中播放，极端情况下，在会JZMediaSystem 的prepare() 方法mediaPlayer.prepareAsync()会出现 ，空指针

我的需求是列表中只有一个在播放，在 RecyclerView 的 onViewDetachedFromWindow() 方法调用了，JzvdStd.reset()

因为觉得 mediaPlayer.prepareAsync() 本身就是异步行为，就想问问 MediaHandlerThread 的设计目的

**Comment by lipangit** [comment]
mediaplayer.release()是在主线程中运行，如果不使用MediaHandlerThread，两个视频交替频繁点击开始的时候，界面卡顿，无法接受的效果。

空指针 什么log，可以解决。
