### ISSUE TITLE
切换清晰度，SurfaceTexture报空

### ISSUE THREAD

**Issue by dzs-yaodi** [lipangit/JiaoZiVideoPlayer#2624]
**什么jzvd版本
7.0.5
**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况
![(3IBY_CG`J`3U %8JCH~TP](https://user-images.githubusercontent.com/33708030/67465040-fea04180-f676-11e9-9ee6-b32ab2c91850.png)

**Comment by dzs-yaodi** [comment]
JZMediaSystem.class ->prepare()

**Comment by lipangit** [comment]
还有这问题吗
