### ISSUE TITLE
显示首帧

### ISSUE THREAD

**Issue by XD-Z** [lipangit/JiaoZiVideoPlayer#2625]
demo中的首帧并不能加载，换了图片的链接也不行，想问大家的是能加载出来，还是不能，怎么解决的，感谢大佬指点

**Comment by lipangit** [comment]
什么意思，还有这个问题吗，具体什么东西不能加载，log是什么

**Comment by XD-Z** [comment]
找到问题原因了,图片大小尺寸有要求,换成要求格式之后能加载了
