### ISSUE TITLE
RecycleView 嵌套了HorizontalScrollView HorizontalScrollView左右滑动后出现滑动和点击播放异常

### ISSUE THREAD

**Issue by ToastYang** [lipangit/JiaoZiVideoPlayer#2627]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by ToastYang** [comment]
点击播放会将RecycleView自动滑动到HorizontalScrollView 所在的item  而且在播放状态下会一直滑动在那里

**Comment by lipangit** [comment]
怎么样了 解决了吗
