### ISSUE TITLE
快做完才发现实现不了列表跳到播放详情无缝播放，唉~快哭了。

### ISSUE THREAD

**Issue by SUHONGJIN** [lipangit/JiaoZiVideoPlayer#2628]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by MrZzhouWorld** [comment]
有没有找到解决办法

**Comment by SUHONGJIN** [comment]
没有，我现在只能进入详情重新播放




------------------ 原始邮件 ------------------
发件人: "MrZzhouWorld"<notifications@github.com>; 
发送时间: 2019年11月1日(星期五) 下午4:33
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com>; 
抄送: "JIN"<903502825@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 快做完才发现实现不了列表跳到播放详情无缝播放，唉~快哭了。 (#2628)




有没有找到解决办法

**Comment by BaiMingxu** [comment]
大佬，实现了么？我也遇到这个需求了呜呜

**Comment by hfyqsy** [comment]
换https://github.com/CarGuo/GSYVideoPlayer这个吧

**Comment by MrZzhouWorld** [comment]
这个也有问题


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: hfyqsy <notifications@github.com&gt;
发送时间: 2019年11月11日 18:07
收件人: lipangit/JiaoZiVideoPlayer <JiaoZiVideoPlayer@noreply.github.com&gt;
抄送: MrZzhouWorld <458205967@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[lipangit/JiaoZiVideoPlayer] 快做完才发现实现不了列表跳到播放详情无缝播放，唉~快哭了。 (#2628)




换https://github.com/CarGuo/GSYVideoPlayer这个吧

**Comment by Eaken** [comment]
> 换[https://github.com/CarGuo/GSYVideoPlayer这个吧](https://github.com/CarGuo/GSYVideoPlayer%E8%BF%99%E4%B8%AA%E5%90%A7)

这个只是用共享元素进入详情页能续播，但返回列表时怎么弄也不能无缝续播，我自己利用window层做了列表详情无缝续播，但是动画效果太差，不知道是不是全面屏的原因一给window层加控件就老是跳一下

**Comment by Harry66** [comment]
可以试下  列表跳详情的时候 把播放器带到详情页  返回列表的时候再带回来啊

**Comment by lipangit** [comment]
demo已经实现

**Comment by hellosuperX** [comment]
> demo已经实现

demo具体是那个。。。。

**Comment by lipangit** [comment]
搜索detail



---原始邮件---
发件人: "hellosuperX"<notifications@github.com&gt;
发送时间: 2020年6月23日(周二) 晚上10:57
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 快做完才发现实现不了列表跳到播放详情无缝播放，唉~快哭了。 (#2628)




  
demo已经实现
  
demo具体是那个。。。。
