### ISSUE TITLE
某些视频URL加载很慢（大约10秒）且播放不完整（播放了5秒左右就停止，视频有50多秒），以及API28以上视屏加载失败

### ISSUE THREAD

**Issue by Liujiyangliujiyang** [lipangit/JiaoZiVideoPlayer#2630]
您好，我在项目中用到了饺子播放器，使用demo中的视频url都可以正常的播放，加载速度也正常。但是在实际项目中使用的时候，发现有一个视频地址加载特别缓慢大约12秒（我已经开启了硬件加速），这个视频url是“https://cdn.couponworld.vip/e/I7dia9937k1376860546_xgWSRM.mp4”，而且这个视频播放到第五秒左右的时候就会卡顿住。项目中有多个视频播放，只有这一个视频出现这种情况。和手机型号应该没有关系。另外，app的build.gradle里面targetSdkVersion和compileSdkVersion为28时，所有视频都加载失败
![图片](https://user-images.githubusercontent.com/19546265/67838692-d3ad6600-fb2c-11e9-8273-d23e370663c9.png)

**Comment by windfone** [comment]
我切换exo 引擎播放 试了你这个url ，加载在2s 左右，可以正常播放完

**Comment by Liujiyangliujiyang** [comment]
> 
> 
> 我切换exo 引擎播放 试了你这个url ，加载在2s 左右，可以正常播放完

是的必须要换播放引擎，默认的播放引擎平常还好，碰到某些视频就不行了

**Comment by lipangit** [comment]
取决于播放内核
