### ISSUE TITLE
在NestedScrollView 播放一直卡在加载视频的状态

### ISSUE THREAD

**Issue by zhaohailongzhl** [lipangit/JiaoZiVideoPlayer#2632]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.0.5
**是否和安卓版本有关系，什么版本
9.0
**是否和特定品牌的手机机型有关系，什么机型
小米8
**相关log是什么
正常
**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
url发来试试吧
