### ISSUE TITLE
在听音乐情况下，示例demo中切换JZMediaSystem 播放视频无画面有声音且releaseAllVideos无效

### ISSUE THREAD

**Issue by groveswang123** [lipangit/JiaoZiVideoPlayer#2633]
**需求描述

**其他app是否实现

**截图或者小视频说明
在听音乐情况下，示例demo中切换JZMediaSystem 播放视频无画面有声音且releaseAllVideos无效

**Comment by lipangit** [comment]
播放音乐的情况下，切换JZMediaSystem，音乐应该立马停止
