### ISSUE TITLE
退出全屏后，播放器将整个屏幕占满了

### ISSUE THREAD

**Issue by lhxx225** [lipangit/JiaoZiVideoPlayer#2639]
版本：7.0.5

全屏前
![TIM图片20191108165703](https://user-images.githubusercontent.com/23518646/68463068-cee16400-0248-11ea-9d1c-c96244fa0c19.png)

退出全屏后
控件将整个屏幕占满了
![image](https://user-images.githubusercontent.com/23518646/68463124-efa9b980-0248-11ea-910e-9614510b18eb.png)

**Comment by lhxx225** [comment]
在外面加了个LinearLayout就好了

**Comment by cyixlq** [comment]
兄嘚，解决了吗？能否告知一下解决办法

**Comment by lhxx225** [comment]
在外面包裹一层LinearLayout，就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cyixlq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月13日(星期一) 中午1:33
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"@小※康"<745447462@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 退出全屏后，播放器将整个屏幕占满了 (#2639)




兄嘚，解决了吗？能否告知一下解决办法

**Comment by lipangit** [comment]
楼上正解
