### ISSUE TITLE
切换清晰度之后 再次点击全屏和小屏按钮 

### ISSUE THREAD

**Issue by 18311173445** [lipangit/JiaoZiVideoPlayer#2640]
**什么jzvd版本
'cn.jzvd:jiaozivideoplayer:7.0.5'
**是否和安卓版本有关系，什么版本
无
**是否和特定品牌的手机机型有关系，什么机型
无
**相关log是什么
无
**复现流程
设置清晰度之后 点击切换清晰度，再次点击全屏和小屏按钮 视屏不会继续播放  而是重新开始播放
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
这是bug  加我微信 给你1000Jzt
