### ISSUE TITLE
RecycleView中使用饺子播放器全屏播放切换回正常播放RecycleView其他内容会被清空

### ISSUE THREAD

**Issue by Flywhiter** [lipangit/JiaoZiVideoPlayer#2644]
RecycleView中使用饺子播放器全屏播放切换回正常播放RecycleView其他内容会被清空

经过调试测试发现全屏之后会将播放器父容器所有子view清空，所以为了修复这个bug需要将播放器单独放到一个部件里面，但是会增加recycleview层级

**Comment by lipangit** [comment]
在jzvd之外嵌套linearlayout
