### ISSUE TITLE
ProgressTimerTask内存泄漏

### ISSUE THREAD

**Issue by ZHBoy** [lipangit/JiaoZiVideoPlayer#2647]
**什么jzvd版本
7.0.5

**是否和安卓版本有关系，什么版本
没关系

**是否和特定品牌的手机机型有关系，什么机型
与机型无关

**相关log是什么

**复现流程
视频重复播放

[**最好有截图或者视频说明情况]
Jzvd$ProgressTimerTask.this$0

**Comment by lipangit** [comment]
是的，怎么解决，这个问题困扰多年
