### ISSUE TITLE
android Q适配可以用吗？

### ISSUE THREAD

**Issue by zhanglongand19** [lipangit/JiaoZiVideoPlayer#2648]
**需求描述
android Q适配可以用吗？JZMediaSystem 中使用了反射Class<MediaPlayer> clazz = MediaPlayer.class;
**其他app是否实现

**截图或者小视频说明

**Comment by zhanglongand19** [comment]
android Q适配可以用吗？JZMediaSystem 中使用了反射Class clazz = MediaPlayer.class;

**Comment by lipangit** [comment]
没有问题，有啥问题

**Comment by zhanglongand19** [comment]
可以用发自我的华为手机-------- 原始邮件 --------发件人： Nathen <notifications@github.com>日期： 2020年2月24日周一 11:23收件人： lipangit/JiaoZiVideoPlayer <JiaoZiVideoPlayer@noreply.github.com>抄送： zhanglong <17624056090@163.com>, Author <author@noreply.github.com>主    题： Re: [lipangit/JiaoZiVideoPlayer] android Q适配可以用吗？ (#2648)Closed #2648.
