### ISSUE TITLE
着急~~~使用TensorFlow的GPU进行运算，用饺子播放器播放会很卡顿

### ISSUE THREAD

**Issue by memoryjs** [lipangit/JiaoZiVideoPlayer#2655]
如题，使用了TensorFlow Lite来计算模型的数据，使用的是GPU版本，使用饺子播放器同时播放视频，会非常卡顿，怀疑是硬件加速共同占用GPU资源导致的，看作者说 不能关闭硬件加速，有没有办法解决该问题，着急

**Comment by memoryjs** [comment]
使用 原生的videoview 竟然不卡顿，泪崩，求救

**Comment by lipangit** [comment]
怎么解决了

**Comment by memoryjs** [comment]
把里面的播放控件由texture换成了 surfaceview

> 怎么解决了
