### ISSUE TITLE
7.0.5 listview列表的全屏播放问题

### ISSUE THREAD

**Issue by yilylong** [lipangit/JiaoZiVideoPlayer#2657]
升级到最新的7.0.5之后应该代码架构改动很大，本地出现很多问题。其中在listview列表播放时候点击全屏播放后，无法回退到原页面，只在全屏页面横竖切换视频，全屏状态下的返回按钮和title不显示了。跟了下代码貌似找到原因：

首先点击列表的某个item全屏播放调用gotoScreenFullscreen（）将该player的screen 设置成了fullscreen. 然后JZUtils.setRequestedOrientation(getContext(), FULLSCREEN_ORIENTATION);将activity设置成横屏。切换activity的屏幕方向就导致activity内容重绘 所以就回调了listview 的adapter 里面的getView() 方法。我们在getView方法有设置各个player.setUp()方法。问题来了，JzvdStd 的setup方法里面有将状态重置成normal状态。

  `public void setUp(JZDataSource jzDataSource, int screen, Class mediaInterfaceClass) {
        super.setUp(jzDataSource, screen, mediaInterfaceClass);
        titleTextView.setText(jzDataSource.title);
        setScreen(screen);
    }`

`@Override
    public void setScreenNormal() {
        super.setScreenNormal();
        fullscreenButton.setImageResource(R.drawable.jz_enlarge);
        backButton.setVisibility(View.GONE);
        tinyBackImageView.setVisibility(View.INVISIBLE);
        changeStartButtonSize((int) getResources().getDimension(R.dimen.jz_start_button_w_h_normal));
        batteryTimeLayout.setVisibility(View.GONE);
        clarity.setVisibility(View.GONE);
    }`

这样就导致backpress 状态判断异常，无法退出到原列表页面。
但是我跟了下demo 却没有这个问题？？

**Comment by lipangit** [comment]
解决了吗
