### ISSUE TITLE
选择清晰度过后，画面卡死，但是有声音

### ISSUE THREAD

**Issue by weeksRen** [lipangit/JiaoZiVideoPlayer#2658]
**什么jzvd版本--7.0.5

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程--点击demo的api-->播放顶部视频，然后选择清晰度

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
感谢你的反馈 这是个问题
