### ISSUE TITLE
小米盒子4有声音没画面

### ISSUE THREAD

**Issue by shl0703** [lipangit/JiaoZiVideoPlayer#2662]
使用cn.jzvd:jiaozivideoplayer:7.0.5在小米盒子4上播放视频有声音没画面（只有Loading+黑屏）。
有人遇到这个问题吗？

**Comment by lipangit** [comment]
怎么样了

**Comment by CleverSJX** [comment]
> 使用cn.jzvd:jiaozivideoplayer:7.0.5在小米盒子4上播放视频有声音没画面（只有Loading+黑屏）。
> 有人遇到这个问题吗？

解决了吗？ 我在Android电视5..1.1上也这样

**Comment by windfone** [comment]
这个问题没跟进了么，也是7.0.5版本在5.1.1的设备上 竖屏可以播放，横屏 只有声音没有画面，但是竖屏状态下点击全屏按钮转换方向就又可以播放了

**Comment by lipangit** [comment]
需要靠老铁们解决
