### ISSUE TITLE
最新版本7.2.0,安卓sdk28,播放http协议的视频，手机上没问题，在车机上出现了播放一会儿，卡住的情况，问题出现次数比较频繁，车机的硬件性能比手机要差，请问有什么思路吗，我之前怀疑是网络问题，后来对比车机和手机测试了3g,4g wifi网络，发现不是网络问题，相同网络下，同一个apk,手机没问题，车机有问题，请问该从什么思路着手解决，这个问题比较着急和重要，项目要使用

### ISSUE THREAD

**Issue by kilitoasuna** [lipangit/JiaoZiVideoPlayer#2673]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by kilitoasuna** [comment]
测试apk是demo中的代码，使用MyJzvdStd播放，视频是一个3分钟20秒的视频，视频超过3分钟，再现几率较大。

**Comment by kilitoasuna** [comment]
我看了相关问题，觉得可以切换一下播放器的内核试一试，请问该如何切换播放器内核。

**Comment by lipangit** [comment]
setMediaInterface()函数，参考demo的customMediaPlayerActivity
