### ISSUE TITLE
全屏返回时，偶尔出现竖屏占满屏幕无法退出。是什么原因？

### ISSUE THREAD

**Issue by Tell-me502** [lipangit/JiaoZiVideoPlayer#2681]
最新版本JzvdStd，自定义播放器。

**Comment by lipangit** [comment]
外面添加layout&nbsp; 参考readme



---原始邮件---
发件人: "YG_Li"<notifications@github.com&gt;
发送时间: 2020年3月13日(周五) 下午5:11
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 全屏返回时，偶尔出现竖屏占满屏幕无法退出。是什么原因？ (#2681)




 
最新版本JzvdStd，自定义播放器。

**Comment by Tell-me502** [comment]
![image](https://user-images.githubusercontent.com/25097200/76716925-da9be480-676c-11ea-9788-418ee45457d5.png)
已经有添加了，这样!

**Comment by lipangit** [comment]
竖屏占满屏幕截图看看，左上角有返回按钮吗，screen变量是几



---原始邮件---
发件人: "YG_Li"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 上午10:00
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 全屏返回时，偶尔出现竖屏占满屏幕无法退出。是什么原因？ (#2681)




 

 已经有添加了，这样!

**Comment by Tell-me502** [comment]
![image](https://user-images.githubusercontent.com/25097200/76736695-4cdaec00-67a2-11ea-8232-64e72c0e4b50.png)
![image](https://user-images.githubusercontent.com/25097200/76737828-73018b80-67a4-11ea-80e9-9b8ce974b821.png)
就是全屏播放完后，点击重播后，再点击返回键就会这样。

-还有个问题，如果再次点击右下角的全屏，就会变成了下面这样
![image](https://user-images.githubusercontent.com/25097200/76737997-c4117f80-67a4-11ea-8ffa-cf73920d28e0.png)

**Comment by lipangit** [comment]
把外面的layout去掉是不是也是这样的效果，目测你写的没有问题，不应该这样。。
你继承jzvdstd以后改了什么？


可以用排除法，先别做任何修改，直接把demo搬过来，没问题之后逐步添加自己的修改，逐步排除问题。



---原始邮件---
发件人: "YG_Li"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 下午4:45
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 全屏返回时，偶尔出现竖屏占满屏幕无法退出。是什么原因？ (#2681)




 

 
 就是全屏播放完后，点击重播后，再点击返回键就会这样。
 
-还有个问题，如果再次点击右下角的全屏，就会变成了下面这样

**Comment by Tell-me502** [comment]
已解决，谢谢。原来是在点击播放就进入全屏时，忘了做screen判断。

**Comment by lipangit** [comment]
ok 么么哒
