### ISSUE TITLE
如何在全屏模式下获取到播放进度的回调

### ISSUE THREAD

**Issue by YaCZHong** [lipangit/JiaoZiVideoPlayer#2684]
**需求描述
你好，我这边需要实现一个保存播放进度的功能，但是我在普通模式下设置的进度回调监听，切换到在全屏模式下就无效了，所以想问一下如何做才能获取到全屏模式下的播放进度的回调。

**其他app是否实现

**截图或者小视频说明

**Comment by YaCZHong** [comment]
版本是6.4.1

**Comment by lipangit** [comment]
用新版



---原始邮件---
发件人: "YaCZHong"<notifications@github.com&gt;
发送时间: 2020年3月24日(周二) 上午10:53
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 如何在全屏模式下获取到播放进度的回调 (#2684)




 
版本是6.4.1

**Comment by lipangit** [comment]
继承jzvdstd复写onprogress函数



---原始邮件---
发件人: "YaCZHong"<notifications@github.com&gt;
发送时间: 2020年3月24日(周二) 上午10:52
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 如何在全屏模式下获取到播放进度的回调 (#2684)




 
**需求描述
 你好，我这边需要实现一个保存播放进度的功能，但是我在普通模式下设置的进度回调监听，切换到在全屏模式下就无效了，所以想问一下如何做才能获取到全屏模式下的播放进度的回调。
 
**其他app是否实现
 
**截图或者小视频说明

**Comment by YaCZHong** [comment]
好的，谢谢
