### ISSUE TITLE
最垃圾的播放器，没有之一

### ISSUE THREAD

**Issue by AttackPangHu** [lipangit/JiaoZiVideoPlayer#2699]
不建议大家使用

**Comment by lipangit** [comment]
说出你的逻辑



---原始邮件---
发件人: "AttackPangHu"<notifications@github.com&gt;
发送时间: 2020年6月9日(周二) 中午12:49
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 最垃圾的播放器，没有之一 (#2699)




 
不建议大家使用

**Comment by StephenGiant** [comment]
不用就不用 不要出来jjyy了 又没挣你钱
