### ISSUE TITLE
使用ExoPlayer播放m3u8会被抓包

### ISSUE THREAD

**Issue by guangmingxiong9999** [lipangit/JiaoZiVideoPlayer#2704]
**需求描述

使用ExoPlayer播放m3u8会被抓包，有没有什么方式使m3u8文件不被抓到，像ijkplayer内核播放一样

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
超出本库解决范围



---原始邮件---
发件人: "guangming"<notifications@github.com&gt;
发送时间: 2020年6月28日(周日) 下午2:17
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 使用ExoPlayer播放m3u8会被抓包 (#2704)




 
**需求描述
 
使用ExoPlayer播放m3u8会被抓包，有没有什么方式使m3u8文件不被抓到，像ijkplayer内核播放一样
 
**其他app是否实现
 
**截图或者小视频说明
