### ISSUE TITLE
怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！

### ISSUE THREAD

**Issue by rainbowtogo** [lipangit/JiaoZiVideoPlayer#2711]

**Comment by CCCCCCCCOOL** [comment]
重写addTextureView，里面设置宽是ViewGroup.LayoutParams.MATCH_PARENT，改为你视频高度，这里要计算的

**Comment by lipangit** [comment]
截图看看   否则无法通过描述知道症状

**Comment by rainbowtogo** [comment]
谢谢大佬 已经在您demo里面看到方法了 已解决！ 现在就是添加封面图后 封面图会变形 封面图是后台直接返回的一张图，感觉好像没法处理封面图的大小展示


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午3:42
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"当人生失意时"<527996462@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)





 
截图看看   否则无法通过描述知道症状

**Comment by CCCCCCCCOOL** [comment]
图片你还要修改Imageview.scaltype.center_crop




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rainbowtogo"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 下午4:35
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 
抄送: "Superman"<1411370511@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)





 谢谢大佬 已经在您demo里面看到方法了 已解决！ 现在就是添加封面图后 封面图会变形 封面图是后台直接返回的一张图，感觉好像没法处理封面图的大小展示 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月8日(星期二) 下午3:42 
 收件人:&amp;nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"当人生失意时"<527996462@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711) 
 
 
 
 
 
   
 截图看看   否则无法通过描述知道症状

**Comment by rainbowtogo** [comment]
谢了 我回头修改下 万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午4:40
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"当人生失意时"<527996462@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)





 图片你还要修改Imageview.scaltype.center_crop 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "rainbowtogo"<notifications@github.com&amp;gt;;  
 发送时间: 2020年9月8日(星期二) 下午4:35 
 收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;gt;;  
 抄送: "Superman"<1411370511@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711) 
 
 
 
 
 
  谢谢大佬 已经在您demo里面看到方法了 已解决！ 现在就是添加封面图后 封面图会变形 封面图是后台直接返回的一张图，感觉好像没法处理封面图的大小展示  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月8日(星期二) 下午3:42  
  收件人:&amp;amp;nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"当人生失意时"<527996462@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)  
   
   
   
   
   
     
  截图看看   否则无法通过描述知道症状

**Comment by CCCCCCCCOOL** [comment]
不客气




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rainbowtogo"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 下午4:42
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 
抄送: "Superman"<1411370511@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)





 谢了 我回头修改下 万分感谢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月8日(星期二) 下午4:40 
 收件人:&amp;nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"当人生失意时"<527996462@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711) 
 
 
 
 
 
  图片你还要修改Imageview.scaltype.center_crop  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "rainbowtogo"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年9月8日(星期二) 下午4:35  
  收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;amp;gt;;   
  抄送: "Superman"<1411370511@qq.com&amp;amp;gt;; "Comment"<comment@noreply.github.com&amp;amp;gt;;   
  主题: Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)  
   
   
   
   
   
   谢谢大佬 已经在您demo里面看到方法了 已解决！ 现在就是添加封面图后 封面图会变形 封面图是后台直接返回的一张图，感觉好像没法处理封面图的大小展示   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "lipangit/JiaoZiVideoPlayer"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年9月8日(星期二) 下午3:42   
   收件人:&amp;amp;amp;nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"当人生失意时"<527996462@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [lipangit/JiaoZiVideoPlayer] 怎么能实现高度过高视频 宽度充满屏幕，高度裁剪播放 现在宽度一直留白。求大佬指点！ (#2711)   
     
     
     
     
     
       
   截图看看   否则无法通过描述知道症状
