### ISSUE TITLE
视频播放的方向

### ISSUE THREAD

**Issue by maimingliang** [lipangit/JiaoZiVideoPlayer#334]
请教一下，视频播放的方向可以设置吗？

**Comment by lipangit** [comment]
查了半天IjkMediaPlayer没找到旋转的api，你可以旋转textureview

**Comment by xiliangxiaoke** [comment]
播放微信的小视频资源，发现是逆时针旋转了90度，不知道应该如何提交判断处理，对视频数据格式一点也不了解

**Comment by lipangit** [comment]
库里暂时不支持解析视频方向

**Comment by flztsj** [comment]
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
                        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-auto-rotate", 1);
                        mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-handle-resolution-change", 1);

加入这些就播放现在MP4流媒体，方向就正确了

**Comment by lipangit** [comment]
你觉得这个是放到库里 还是留给其他程序员自己调用

**Comment by flztsj** [comment]
你们可以在验证下其他视频源看看。 目前我还不太了解这段代码，初步看是使用了硬解。 目前不推荐合入。。

**Comment by flztsj** [comment]
在 void onInfo(int what, int extra) 中加入 
        } else if (what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED) {
            Log.d(TAG, "onInfo rotation - " + extra);
            Log.d(TAG, "MEDIA_INFO_VIDEO_ROTATION_CHANGED");
        }
可以得到视频的rotation信息

**Comment by lipangit** [comment]
我感觉ijkplayer太麻烦了，ijkplayer的信念我觉得还不够简单，自己做一个基于ffmpeg的android视频播放器，接口和系统的视频播放器一样，这事好像非常复杂

**Comment by nwx546250** [comment]
用JZMediaIjkplayer播放  视频方向 会被旋转问题   解决如下
1、在JZMediaIjkplayer中获取视频被旋转角度的地方设置回调

![default](https://user-images.githubusercontent.com/16304707/37750958-9de14018-2dca-11e8-8267-6ae90799c6ff.png)

2.在调用页面把回调实例设置进去
![default](https://user-images.githubusercontent.com/16304707/37750965-b03ad616-2dca-11e8-810d-1037dbd94b86.png)

**Comment by lipangit** [comment]
非常感谢，
![image](https://user-images.githubusercontent.com/2038071/37762918-a21c9b2c-2df8-11e8-9fda-0309d9b8eec2.png) 这个数值是多少。我把它更新到项目里。

**Comment by lipangit** [comment]
用的什么播放器引擎

**Comment by muban** [comment]
![image](https://user-images.githubusercontent.com/17584266/41093495-0f5d839c-6a7e-11e8-9f7e-204a04ffe939.png)
我这log看着10001可以转回来

**Comment by lipangit** [comment]
啥问题 @muban
