### ISSUE TITLE
视频列表正在播放的item滑出屏幕，还是继续播放~

### ISSUE THREAD

**Issue by lijie815917** [lipangit/JiaoZiVideoPlayer#381]

**Comment by lipangit** [comment]
列表中视频重置的依据是列表复用时的setUp，如果列表还没来得及复用，就会出现你的这种情况

**Comment by lipangit** [comment]
你如果有什么好办法，一起交流

**Comment by lijie815917** [comment]
已经解决了，要做一个列表是否滑出屏幕的判断，如果滑出去的话，则回收和释放播放器

**Comment by lipangit** [comment]
怎么判断的，效果好吗@lijie815917

**Comment by lijie815917** [comment]
恩恩，可以实现滑出屏幕不播放，但是对列表有一定限制，可能测量不准确（一般需求都能满足），
核心代码：
  //滚出屏幕停止视频的播放
    class MyScrollListener implements AbsListView.OnScrollListener {
        private int firstVisibleItem = -1, lastVisibleItem, totalItemCount;
        private View fistView, lastView;

        public void GCView(View gcView) {
            if (gcView != null && gcView.findViewById(R.id.video) != null) {
                JCVideoPlayerStandardFresco video = (JCVideoPlayerStandardFresco) gcView.findViewById(R.id.video);
                if (video != null && (video.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING
                                      || video.currentState == JCVideoPlayer.CURRENT_STATE_ERROR)) {
                    video.setUiWitStateAndScreen(JCVideoPlayer.CURRENT_STATE_AUTO_COMPLETE);
                    JCVideoPlayerStandardFresco.releaseAllVideos();
                }
            }
        }


        @Override
        public void onScrollStateChanged(AbsListView view, int scrollState) {

        }

        @Override
        public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {

            if (this.firstVisibleItem < firstVisibleItem) {
                this.firstVisibleItem = firstVisibleItem;
                this.lastVisibleItem = firstVisibleItem + visibleItemCount;
                GCView(fistView);
                fistView = view.getChildAt(0);
                lastView = view.getChildAt(visibleItemCount - 1);
            } else if (this.lastVisibleItem > (firstVisibleItem + visibleItemCount)) {
                this.firstVisibleItem = firstVisibleItem;
                this.lastVisibleItem = firstVisibleItem + visibleItemCount;
                GCView(lastView);
                fistView = view.getChildAt(0);
                lastView = view.getChildAt(visibleItemCount - 1);
            }
        }
    }

**Comment by wangguifa** [comment]
@lijie815917  你好，我也遇到滑动不能暂停播放的问题，有点看不懂你写的   能给个demo吗   我用的是listview

**Comment by lipangit** [comment]
@wangguifa 你看demo中MutiHolderActivity满足你的需求吗

**Comment by wangguifa** [comment]
我看了 照着你的写的，不知道为什么不行，写的一样的，滑动一下就停止了

**Comment by lipangit** [comment]
@wangguifa 断点一下getView()里调用的release()函数什么时候执行的

**Comment by wangguifa** [comment]
感觉listview滑动的时候一直执行release

**Comment by lipangit** [comment]
是最新版本吗，release会判断是不是当前的播放器，如果是才会releaseAllVideos

**Comment by wangguifa** [comment]
是新版，总感觉判断的不准，但是你的项目里是好的，同样的代码  在我这不知道为什么就不行

**Comment by lipangit** [comment]
想起来了，你列表中是有相同url的视频吗，判断正在播放的依据就是url相同，你滑一下就会release视频估计是isMe判断错了

**Comment by wangguifa** [comment]
没有，不知道是什么原因，activity中那个判断是否当前播放那总release，可是你项目没有这问题，我刚才有楼主给的方法试了，可以了 谢作者，谢楼主

**Comment by jfjbYXY** [comment]
如果使用RecyclerView，怎么写？
RecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener()｛？？？？｝
这里的回调方法不一样，参数不一样
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                //可见item总数
                visibleItemCount = mRecyclerView.getChildCount();

            }

**Comment by jfjbYXY** [comment]
mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            private int _firstItemPosition = -1, _lastItemPosition;
            private View fistView, lastView;

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
                //判断是当前layoutManager是否为LinearLayoutManager
                // 只有LinearLayoutManager才有查找第一个和最后一个可见view位置的方法
                if (layoutManager instanceof LinearLayoutManager) {
                    LinearLayoutManager linearManager = (LinearLayoutManager) layoutManager;
                    //获取最后一个可见view的位置
                    int lastItemPosition = linearManager.findLastVisibleItemPosition();
                    //获取第一个可见view的位置
                    int firstItemPosition = linearManager.findFirstVisibleItemPosition();
                    //获取可见view的总数
                    int visibleItemCount = linearManager.getChildCount();

                    if (_firstItemPosition < firstItemPosition) {
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        GCView(fistView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    } else if (_lastItemPosition > lastItemPosition) {
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        GCView(lastView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    }
                }
            }

            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            /**
             * 回收播放
             * @param gcView
             */
            public void GCView(View gcView) {
                if (gcView != null && gcView.findViewById(R.id.video_item_img) != null) {
                    JCVideoPlayerStandardFresco video = (JCVideoPlayerStandardFresco) gcView
                            .findViewById(R.id.video_item_img);
                    if (video != null
                            && (video.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING || video.currentState == JCVideoPlayer.CURRENT_STATE_ERROR)) {
                        video.setUiWitStateAndScreen(JCVideoPlayer.CURRENT_STATE_AUTO_COMPLETE);
                        JCVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });

**Comment by lipangit** [comment]
@jfjbYXY 非常好用的话可以放到demo里给大家参考

**Comment by lipangit** [comment]
这我存个书签研究一下，以后列表里用scroll去判断何时回收视频

**Comment by huangsongyan** [comment]
listview 播放时滑动 ，还是在播放，怎么解决。

**Comment by huangsongyan** [comment]
补充：
有些视频地址相同的。

**Comment by lipangit** [comment]
列表复用的时候setUp会停止播放，由于对JCvideoPlayer的管理逻辑不一样，4.*的版本视频地址不能相同，5.1中视频地址可以相同

**Comment by MiChongGET** [comment]
新版本的需要这样设置，要改一些参数和方法
/**
             * 回收播放
             * @param gcView
             */
            public void GCView(View gcView) {
                if (gcView != null && gcView.findViewById(R.id.JCVideoPlayerStandard) != null) {
                    JCVideoPlayerStandard video = (JCVideoPlayerStandard) gcView
                            .findViewById(R.id.JCVideoPlayerStandard);
                    if (video != null
                            && (video.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING || video.currentState == JCVideoPlayer.CURRENT_STATE_ERROR)) {
                        video.setSystemUiVisibility(JCVideoPlayer.CURRENT_STATE_AUTO_COMPLETE);
                        JCVideoPlayer.releaseAllVideos();
                    }
                }
            }

**Comment by lipangit** [comment]
朋友们，希望能在demo中写一个例子，这个我一直没做成功过

**Comment by lipangit** [comment]
就是列表滑动出屏幕自动暂停的例子

**Comment by MiChongGET** [comment]
我的项目里面用到了，找到package cn.buildworld.ahlive.fragment;下面的GaoxiaoVideo类，主要是在fragment里面使用RecyclerView实现一个播放列表。github地址：[](https://github.com/MiChongGET/AhLive)
![default](https://user-images.githubusercontent.com/15011479/28618475-25861750-7237-11e7-89a6-b5182f9c0711.png)

**Comment by MiChongGET** [comment]
但是好像只能将视频强制关掉，不是暂停，也就是下次还要从头看

**Comment by MiChongGET** [comment]
刚刚代码没提交，现在好了

**Comment by MiChongGET** [comment]
## **修改了一下上面网友的代码，实现上滑item不可见自动暂停，下滑到中间实现自动播放，下滑item不可见自动暂停，上滑到中间实现自动播放**

`mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {

            private int _firstItemPosition = -1, _lastItemPosition;
            private View fistView, lastView;
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
                //判断是当前layoutManager是否为LinearLayoutManager
                // 只有LinearLayoutManager才有查找第一个和最后一个可见view位置的方法
                if (layoutManager instanceof LinearLayoutManager) {
                    LinearLayoutManager linearManager = (LinearLayoutManager) layoutManager;
                    //获取最后一个可见view的位置
                    int lastItemPosition = linearManager.findLastVisibleItemPosition();
                    //获取第一个可见view的位置
                    int firstItemPosition = linearManager.findFirstVisibleItemPosition();
                    //获取可见view的总数
                    int visibleItemCount = linearManager.getChildCount();

                    if (_firstItemPosition < firstItemPosition) {
                        Log.i(TAG, "onScrolled: "+"视频划上去了");
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        GCView(fistView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    } else if (_lastItemPosition > lastItemPosition) {
                        Log.i(TAG, "onScrolled: "+"视频划下去了");
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        GCView(lastView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    }else if (_firstItemPosition > firstItemPosition){
                        Log.i(TAG, "onScrolled: "+"视频从上滑倒下了");
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        ResumeView(fistView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    }else if (_lastItemPosition < lastItemPosition){
                        _firstItemPosition = firstItemPosition;
                        _lastItemPosition = lastItemPosition;
                        Log.i(TAG, "onScrolled: "+"视频从下滑倒上了");
                        ResumeView(lastView);
                        fistView = recyclerView.getChildAt(0);
                        lastView = recyclerView.getChildAt(visibleItemCount - 1);
                    }
                }
            }

            /**
             * 回收播放
             * @param gcView
             */
            public void GCView(View gcView) {
                if (gcView != null && gcView.findViewById(R.id.JCVideoPlayerStandard) != null) {
                    StandardVideoPlayer video = (StandardVideoPlayer) gcView
                            .findViewById(R.id.JCVideoPlayerStandard);
                    if (video != null
                            && (video.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING || video.currentState == JCVideoPlayer.CURRENT_STATE_ERROR)) {
                        video.setSystemUiVisibility(JCVideoPlayer.CURRENT_STATE_AUTO_COMPLETE);
                        JCMediaManager.instance().mediaPlayer.pause();
                    }
                }
            }

            /**
             * 恢复播放
             * @param gcView
             */
            public void ResumeView(View gcView) {
                if (gcView != null && gcView.findViewById(R.id.JCVideoPlayerStandard) != null) {
                    StandardVideoPlayer video = (StandardVideoPlayer) gcView
                            .findViewById(R.id.JCVideoPlayerStandard);
                    if (video != null
                            && (video.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING || video.currentState == JCVideoPlayer.CURRENT_STATE_ERROR)) {
                        video.setSystemUiVisibility(JCVideoPlayer.CURRENT_STATE_AUTO_COMPLETE);
                        JCMediaManager.instance().mediaPlayer.start();
                    }
                }
            }
        });`


# 网友写的StandardVideoPlayer实现在fragment中回到桌面自动暂停视频，再次点击app实现自动播放
`public class StandardVideoPlayer extends JCVideoPlayerStandard {
    // Set the flag for storing if user click the start button for pausing.
    // For fixing the bug about the invalidation of status switching between resume and pause.
    private static boolean isPauseByClick = false;
    private static AudioManager.OnAudioFocusChangeListener onOriginAudioFocusChangeListener;

    public StandardVideoPlayer(Context context) {
        this(context, null);
    }

    public StandardVideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);

        // Store the original listener.
        if (onOriginAudioFocusChangeListener == null) {
            onOriginAudioFocusChangeListener = onAudioFocusChangeListener;
        }
        // Sets the old logic and modifying the field {@link #isPauseByClick}.
        onAudioFocusChangeListener = new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
                switch (focusChange) {
                    // This logic is copied from the origin code.
                    // Remembering update the logic when updating the lib.
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                        pauseVideo();
                        Log.d(TAG, "AUDIOFOCUS_LOSS_TRANSIENT [" + this.hashCode() + "]");
                        break;
                    default:
                        onOriginAudioFocusChangeListener.onAudioFocusChange(focusChange);
                        break;
                }
            }
        };
    }

    @Override
    public void setSystemUiVisibility(int visibility) {
        super.setSystemUiVisibility(visibility);
        switch (currentState) {
            case CURRENT_STATE_PAUSE:
                // It will enter this case when click the start button for pausing.
                isPauseByClick = true;
                break;
        }
    }

    /**
     * Pause the standard video player.
     * Used in the method such as onPause() in Activity or Fragment.
     */
    public static void pauseVideo() {
        try {
            if (JCMediaManager.instance().mediaPlayer != null &&
                    JCMediaManager.instance().mediaPlayer.isPlaying()) {
                JCMediaManager.instance().mediaPlayer.pause();
                isPauseByClick = false;
            }
        } catch (IllegalStateException e) {
            e.printStackTrace();
        }
    }

    /**
     * Resume the standard video player.
     * Used in the method such as onResume() in Activity or Fragment.
     */
    public static void resumeVideo() {
        try {
            if (JCMediaManager.instance().mediaPlayer != null && !JCMediaManager.instance().mediaPlayer
                    .isPlaying() && !isPauseByClick) {
                JCMediaManager.instance().mediaPlayer.start();
            }
        } catch (RuntimeException e) {
            e.printStackTrace();
        }
    }
}`

**Comment by hyr0318** [comment]
@MiChongGET  假如是瀑布流的manager 应该怎么写额？ 试了下好像不可以额，LinearLayoutManager时是可以有效果的。

**Comment by MiChongGET** [comment]
@hyr0318 这个还真没有试过哎

**Comment by lipangit** [comment]
新版完美解决

**Comment by KarasJoker** [comment]
@MiChongGET 我想问一下 用这个检测到视频的item 一半划出屏幕有顶部电池栏白屏的问题么
