### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by Hitexroid** [lipangit/JiaoZiVideoPlayer#422]
Hi , It's the best **sample** for _read_ and _show_ .srt **subtitle** on **textview** inside **videoplayer**

[https://github.com/Sriharia/Subtitles-support-to-Android-MediaPlayer-for-all-versions](https://github.com/Sriharia/Subtitles-support-to-Android-MediaPlayer-for-all-versions)

please **add** this feature in **JieCaoVIdeoPlayer**

**Comment by lipangit** [comment]
Thank you ,I will try this library

**Comment by Hitexroid** [comment]
we are waiting ... :(

**Comment by Hitexroid** [comment]
Hello

**Comment by lipangit** [comment]
Hello

**Comment by lipangit** [comment]
Subtitle is not in my work plan within two month.

You can try yourself and share your code.

**Comment by iHaiderAli** [comment]
have you integrated subtile feature in your project?

**Comment by lipangit** [comment]
yes but I have no time,

**Comment by iHaiderAli** [comment]
sorry to disturb you, can you provide me a link of subtitle support feature where i can see the logic and code?

**Comment by lipangit** [comment]
I have never research subtitle, you can see that url https://github.com/Sriharia/Subtitles-support-to-Android-MediaPlayer-for-all-versions
