### ISSUE TITLE
这个能否实现慢动作播放和快动作播放？

### ISSUE THREAD

**Issue by CreamF** [lipangit/JiaoZiVideoPlayer#602]
具体解释为：
正常的播放速度：为1
慢动作也就是0.5倍的播放速度
快动作也就是1.5倍的播放速度或更高，这个有没有办法进行设置

**Comment by lipangit** [comment]
@CreamF 你查一下exoplayer有没有相关设置

**Comment by lipangit** [comment]
这功能有用，但不知道怎么做

**Comment by lipangit** [comment]
有快速和慢速，但是只支持6.0以上的
