### ISSUE TITLE
分享一种从视频列表页跳转到视频详情页继续播放的实现方案

### ISSUE THREAD

**Issue by OtzOrz** [lipangit/JiaoZiVideoPlayer#711]
需求：视频列表页为recyclerview，列表页可播放视频，如果点击item则跳转详情页，要求详情页能无时差的同步列表页视频播放进度。

最初的实现方式是直接在详情页使用seekto（）跳转到列表页播放的进度，但是这样会有一个重新loading的时差，影响体验。现在的解决方案是：

1、点击列表item跳转的时候，将播放视图（JCVideoPlayerStandard，下同）从容器中清除，并且新建一个相同url和title的播放视图注入到该容器，避免从详情返回的时候没有这一条视频数据了

2、在详情页中使用JCVideoPlayerManager.getCurrentJcvd()获取到列表页清除出来那一个视图，注入到详情页的容器中（这时候已经实现了跳转后无时差播放）

3、在JCVideoPlayer中新建一个context以及setter和getter，getter中当context不为空的时候，返回context，否则返回原来的getContext();

4、替换JCVideoPlayer中所有的getContext()为getter

5、在详情页中的播放视图如果是列表页中拿过来，用setter给当前播放视图注入context；
==============分割线================
3、4、5步是为了解决详情页中的播放视图不能正确全屏的问题

以上解决方案相对改动较小也比较简单，但是有什么后果我不知道/cry.反正能实现效果...hhh，各位大大们有更好的更优雅的解决方案麻烦告诉我一下，Orz........Otz.....Ozz....

**Comment by lipangit** [comment]
@OtzOrz 也可以提个pr，在demo里加上这个

**Comment by luXiuKun** [comment]
注入 是addview？

**Comment by OtzOrz** [comment]
是的

**Comment by AlphaHi** [comment]
感觉很厉害，楼主现在进详情页有遇到什么问题吗，能否分享下进详情页那段代码呢

**Comment by chen2tu** [comment]
@AlphaHi 就是获取到播放器的父视图，然后删掉播放器，重新创建一个塞进去。removeView，addView然后就没有了。从列表跳转到详情，有另外一个人实现的更优雅一点，具体的，你在issue里面搜索“详情”就能看到了

**Comment by 401885064** [comment]
@chen2tu che  麻烦给出你说的那个更优雅实现的issue链接  我搜索“详情”就只有当前这个issue

**Comment by Lee-Jian** [comment]
@OtzOrz  能分享一下代码吗

**Comment by BaiMingxu** [comment]
@OtzOrz 大佬，能分享一下代码么？我也遇到这个需求了呜呜

**Comment by lipangit** [comment]
demo已经实现这个功能

**Comment by BaiMingxu** [comment]
您好，大佬，我看demo中，按home建退出后视频，还会播放。而且JzvdStd.goOnPlayOnPause();和JzvdStd.goOnPlayOnResume();就不能使用了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nathen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月24日(星期一) 下午5:31
收件人:&nbsp;"lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"michel"<806605375@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lipangit/JiaoZiVideoPlayer] 分享一种从视频列表页跳转到视频详情页继续播放的实现方案 (#711)




demo已经实现这个功能
