### ISSUE TITLE
English version of the Readme.md ?

### ISSUE THREAD

**Issue by cougarm6** [lipangit/JiaoZiVideoPlayer#720]
Do you want help with English version of the Readme.md? I am using your library in my application, will be happy to help 👍

**Comment by lipangit** [comment]
Nice hero, you can change every thing to make English native in project.

**Comment by lipangit** [comment]
@cougarm6  you can change every thing in readme.md

**Comment by lipangit** [comment]
@cougarm6  hello do you have time to help with english version of readme

**Comment by cougarm6** [comment]
Sure, can I do it next week?

**Comment by lipangit** [comment]
ok
