### ISSUE TITLE
list列表中如果视频url相同，如果点击播放某一个，则这个item下面的第三个会跟着一起播放

### ISSUE THREAD

**Issue by chaopengTan** [lipangit/JiaoZiVideoPlayer#740]
list列表中如果视频url相同，如果点击播放某一个，则这个item下面的第三个会跟着一起播放

**Comment by SilenceBurst** [comment]
我用的recyclerview，视频的url相同，没出现这个问题。但是播放会按同一个播放进度（不是同一个条目）。

**Comment by chaopengTan** [comment]
@SilenceBurst  播放进度相同是做的缓存，应该不属于bug，但是我这个问题不知道什么情况

**Comment by SilenceBurst** [comment]
@chaopengTan 应该是convertview的复用吧，不复用convertview呢？

**Comment by lipangit** [comment]
用新版5.5.2，url相同不会影响播放

**Comment by SilenceBurst** [comment]
@lipangit 你好，我用的是5.5.2,视频url相同，用的recyclerview，点击不同条目按同一播放进度播放。

**Comment by chaopengTan** [comment]
@lipangit 5.5.2也是一样的效果

**Comment by lipangit** [comment]
二位对比一下demo，demo里有这种情况吗

**Comment by SilenceBurst** [comment]
@lipangit 
1.demo里的recyclerview，我把url改为同一个，也会按同一进度播放。
2.recyclerview点击播放，退出，再进入播放，会按之前的进度播放，而且偶尔会出现感叹号。

**Comment by lipangit** [comment]
保存进度的key是url，相同url会共享一个保存的进度

**Comment by chaopengTan** [comment]
Dome中具有相同url的列表并不是以listview形式存放的，而是以LinearLayou形式固定的，目前我的写法是将item动态加载到LinearLayout里面，就不会出现不同item同时播放的情况

**Comment by lipangit** [comment]
好的 问题能解决就好

**Comment by hrdgr** [comment]
Fragment 里面 的listview 滑动的时候，视频不会暂停，求解决。

**Comment by lipangit** [comment]
@hrdgr 参照demo 列表必须复用
