### ISSUE TITLE
如何做到列表正在播放后进入详情页正常播放？

### ISSUE THREAD

**Issue by my19941001** [lipangit/JiaoZiVideoPlayer#768]
如同今日头条一样，请作者给个思路

**Comment by lipangit** [comment]
还在研究，以前想做这个功能，工程量有点大，要重构窗口转换的部分，比如普通窗口，小窗，全屏，详情页，详情页的普通窗口小窗全屏的转换，这些过程应该是统一管理，以前做过一些但是拿不出手。
其他issue里其他朋友提出过实现过程不知道是否已经实现。思路的话从列表进入详情页和从列表进入全屏应该是相同的道理。

**Comment by my19941001** [comment]
按照你给的思路已经弄出来了，不过我没考虑小窗播放的功能

**Comment by lipangit** [comment]
这么牛逼，来个PR看看吧，如果完美解决以后就放到demo里

**Comment by chen2tu** [comment]
@my19941001 @lipangit 这个功能包含在新版本了嘛？demo里面有没有了

**Comment by my19941001** [comment]
@lipangit @chen2tu 抱歉抱歉，作者，忘记回复你了。我是看源码按照你全屏切换的思路做的，当我在列表点击进入详情页面的时候移除textureView并将当前的状态传递给详情页面，然后重置ui。到详情页面后设置播放状态并且addTextureView就好了。还有不是不想PR，是我不知道怎么PR，作者见谅哈。。。经过我的测试是可以正常播放的，不管是处于缓冲，播放中，暂停中都是可以的。哦，对了，使用的版本是ijkplayer。因为mediaPlayer缓冲时间实在太长，老板那过不去。下面贴一下代码

videoBViewHolder.videoPlayer.textureViewContainer.removeView(JCMediaManager.textureView);
                intent.putExtra("currentState", videoBViewHolder.videoPlayer.currentState);
                mContext.startActivity(intent);
                videoBViewHolder.videoPlayer.resetUi();

详情页面：

videoPlayer.setUp(
                            Util.getImgUrl(mContentList.get(getPlayPosition()).getMediaurl()), JCVideoPlayer.SCREEN_LAYOUT_NORMAL,
                            mContentList.get(getPlayPosition()).getArticlename());
videoPlayer.setUiWitStateAndScreen(getIntent().getIntExtra("currentState", -1));
                videoPlayer.addTextureView();
                JCVideoPlayerManager.putListener(videoPlayer);

**Comment by liweiGe** [comment]
@my19941001 有没有详细点的代码
比如setUiWitStateAndScreen 和  resetUi这两个方法里的操作

**Comment by my19941001** [comment]
@liweiGe 这两个方面内部我没做处理。我开发时的播放器版本比较老，而且那个app也死了，没有继续维护。你可以参考现在版本的切换全屏和退出全屏的代码。
当时我做的时候思路：
1.需要进入详情页时，移除列表页播放器的textureView，并保存当前播放状态。
2.给列表页的播放器重置ui为初始状态
3.在详情页给播放器初始化后，将播放状态设置给详情页播放器
4.给详情页播放器添加textureView并设置监听。
setUiWitStateAndScreen 和 resetUi都是库里的方法，在JCVideoPlayerStandard类
