### ISSUE TITLE
能不能在Recyclerview实现自动播放和暂停

### ISSUE THREAD

**Issue by WooYu** [lipangit/JiaoZiVideoPlayer#783]

**Comment by lipangit** [comment]
这个要自己做了，我没实践过，有不少朋友完成过这个功能了，帮你在群里问问

**Comment by haegyeong** [comment]
兄弟，recyclerview实现自动暂停的有实现方式吗？公司项目也要这个功能

**Comment by lipangit** [comment]
@haegyeong 你就说咱们和今日头条的播放器一模一样，今日头条都没有这功能，想办法拒绝，这种功能没完没了

**Comment by haegyeong** [comment]
今日头条是可以的，他们都是仿今日头条的功能

**Comment by lipangit** [comment]
亲测，头条滑动列表之后视频会重置

**Comment by haegyeong** [comment]
恩恩，是会重置，但是我想要让他滑出界面的时候，视频会停止播放

**Comment by haegyeong** [comment]
@lipangit 有没有办法让正在播放的视频滑出界面后台，视频就会停止播放，不管是不是暂停，只要是停止播放就行了

**Comment by lipangit** [comment]
咱们就是停止的，划出界面之后会release视频

本质上是列表复用的时候，调用setUp，如果正在播放就会停止正在播放的视频

**Comment by lvbell** [comment]
用scrollListener 监听滑动幅度，layoutManager获取当前holder位置，可以模拟实现，但是具体高度计算要自己做

**Comment by lipangit** [comment]
@lvbell 我很想这么做，这样能更准确的判断什么时候划出界面，你弄完这个功能可以提交上来，给大家参考。

**Comment by lvbell** [comment]
@lipangit 写的特别乱就提供个我的思路吧
1. layoutManager.findFirstVisibleItemPosition();
    layoutManager.findLastVisibleItemPosition();
获得当前页面第一个和最后一个的位置

2.在onScrollStateChanged 的idle下，通过layoutManager获得holder，holder继承了一个接口，里面有播放，暂停等控制视频的功能
 holder （implement 控制视频接口）  =  layoutManager.findLastVisibleItemPosition(位置);

3. int itemLocation[] = new int[2]; 
通过viewholder获得在窗口的位置  viewHolder.itemView.getLocationInWindow(itemLocation);
根据itemLocation[1]也就是y值判断第一个视频距离顶部位置，如果顶部有toolbar什么的要另减去就是了

4.遍历 first 到 last ，播放第一个或者第一个完整可见的，然后暂停其他的

**Comment by lipangit** [comment]
好的收藏了

**Comment by ldy441040480** [comment]
jiecao的播放器+https://github.com/waynell/VideoListPlayer的列表自动播放

**Comment by ldy441040480** [comment]
jiecao的播放器+https://github.com/waynell/VideoListPlayer 的列表自动播放
