### ISSUE TITLE
Demo中开始播放时要闪一下,可否改进像今日头条一样点击播放先黑屏在开始播放

### ISSUE THREAD

**Issue by saurylip** [lipangit/JiaoZiVideoPlayer#839]
使用的是最新版的Demo.
ps:关于提供静音与否按钮...大神可不可以给个思路

**Comment by saurylip** [comment]
音量静音已经实现~

**Comment by lipangit** [comment]
开始播放这块听你说完好像是有点闪，不说还真感觉不到，视频第一帧和缩略图应该是样的，但是衔接不流畅。

静音是系统音量还是播放器的音量。

**Comment by qinyang1018** [comment]
闪一下的这个问题有解决办法了吗 ? @saurylip @lipangit

**Comment by ldy441040480** [comment]
视频准备完毕后可以延迟150ms调整UI，但是要注意150ms之后的状态是否是准备中状态，因为这时候可能已经处于释放状态了，时间仅供参考，@lipangit可以考虑一下
    @Override
    public void onPrepared() {
        super.onPrepared();
        mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (currentState != CURRENT_STATE_PREPARING && currentState != CURRENT_STATE_PLAYING_BUFFERING_START)
                    return;
                startProgressTimer();
                onStatePlaying(true);
                setAllControlsVisible(View.VISIBLE, View.INVISIBLE, View.INVISIBLE,
                        View.INVISIBLE, View.INVISIBLE, View.INVISIBLE, View.VISIBLE);
                startDismissControlViewTimer();
            }
        }, 150);
    }

**Comment by lipangit** [comment]
@ldy441040480  这个问题已经解决
