### ISSUE TITLE
RecyclerView中的JCVidedoPlayer在滑出屏幕后不会自动停止

### ISSUE THREAD

**Issue by mylove2693** [lipangit/JiaoZiVideoPlayer#865]
我看Demo里的JCVideoPlayer在滑出屏幕后会自动停止，但是没有找到设置的代码。我的app里JCVideoPlayer在滑出屏幕后不会自动停止。

**Comment by mylove2693** [comment]
我的布局如下：AppCompatActivity中有一个ViewPage，ViewPage中有两个Fragment，Fragment中有RecyclerView等。

**Comment by lipangit** [comment]
划出屏幕停止是因为在列表复用的时候调用了setUp函数，可以参照demo中About ListView Activity-> recycleview Activity里adapter的代码。

最好是能准确判断视频是否可见去停止视频，监听列表滑动还没想到好的做法

**Comment by zw-king** [comment]
我写了下面的方法来监听，效果还不错，可供参考      
 recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(final View view) {
            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                //列表滑动时，滑出屏幕的视频停止播放
                RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
                LinearLayoutManager manager = (LinearLayoutManager) layoutManager;
                int type = manager.getItemViewType(view);
                if (JCVideoPlayerManager.listener() != null && type == HolderTypes.VIDEO_TYPE) {
                    int vi = view.findViewById(R.id.start).getVisibility();
                    JCVideoPlayer videoPlayer = (JCVideoPlayer) JCVideoPlayerManager.listener();
                    if (videoPlayer.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING && (vi==View.INVISIBLE || vi == View.GONE)) {
                        JCVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });
