### ISSUE TITLE
关于从缩略图切换到播放界面会有一帧闪屏的问题

### ISSUE THREAD

**Issue by JokeXiao** [lipangit/JiaoZiVideoPlayer#968]
请问一下,从缩略图切换到播放界面会有一帧闪屏,我下载官方demo也会有闪屏出现,只是速度比较快,感觉不是很明显,但是在网络不是很好的情况下,闪屏就比较明显了,黑屏时间会比较长,希望有一个好的解决方案!非常感谢....

**Comment by lipangit** [comment]
这是个问题，正在酝酿

**Comment by JokeXiao** [comment]
哦哦,非常期待这个可以修复!嫂子就靠你啦!对了,缓冲的大小,有暴露接口么

**Comment by lipangit** [comment]
android.media.MediaPlayer好像没这接口

**Comment by hymlv** [comment]
缓冲的回调,ijkMediaplayer 提供了监听器 OnBufferingUpdateListener

**Comment by Lionet6** [comment]
开始播放闪屏问题处理方案，昨天老板提出来这个问题，我改了下，具体步骤给了，希望作者能及时看一下，优化一下体验
http://blog.csdn.net/qq_24229505/article/details/76549397

**Comment by lipangit** [comment]
已经修复

**Comment by MarnoDev** [comment]
我用的 6.2.9 ，还是有这个问题，在播放前会有一帧的黑屏闪过
